### ISSUE TITLE
Brave web apps closing immediately when AltTab is running

### ISSUE THREAD

**Issue by mathiasandresen** [lwouis/alt-tab-macos#1000]
**Describe the bug**

Whenever AltTab is running, my Brave Web apps/shortcuts closes immediately after opening.
They quickly flash the menu bar.
When I close AltTab, the apps works as normal.

* macOS Big Sur 11.2.3 (20D91)
* MacBook Pro (13-inch, M1, 2020)

**Screenshots / video**

https://user-images.githubusercontent.com/5781825/122112359-064ec400-ce21-11eb-8d3a-ca188d03150d.mov

https://user-images.githubusercontent.com/5781825/122112343-0058e300-ce21-11eb-9c04-a2ce6eade5b4.mov

**Steps to reproduce the bug**

1. Create a Brave web app such as messenger.com
    1. Go to the site
    2. Press Brave's more options (three lines to the right of url bar)
    3. "More Tools" -> "Create Shortcut"
    4. Check "Open as window"
2. Open the app and see that it does not work
3. Close AltTab
4. Open the app again and see that it now works

**Comment by lwouis** [comment]
Hi @mathiasandresen 

Have you shown this issue to the Brave staff? It sounds like it could be a bug on their side.

It may also be related to Big Sur (see https://github.com/lwouis/alt-tab-macos/issues?q=is%3Aopen+is%3Aissue+label%3A%22big+sur%22)

**Comment by mathiasandresen** [comment]
> Hi @mathiasandresen
> 
> Have you shown this issue to the Brave staff? It sounds like it could be a bug on their side.
> 
> It may also be related to Big Sur (see https://github.com/lwouis/alt-tab-macos/issues?q=is%3Aopen+is%3Aissue+label%3A%22big+sur%22). It would be interesting to test on Catalina or before.

I will try to show the issue to the Brave staff, it could be a problem with Brave.
I have tested it, and it seems to work fine with Chrome.
I do not have the ability to test this on Catalina, since this computer is my only Mac, and is a work computer.

**Comment by phao5814** [comment]
Yeah, I can confirm this is a Brave issue. Apparently it was resolved a few days ago. For more info check out the [Brave issue](https://github.com/brave/brave-browser/issues/7205#issuecomment-801664969) that recently got closed.

**Comment by lwouis** [comment]
Great news! Thanks @phao5814 for sharing the ticket with the investigation + resolution. Closing this ticket 👍
