### ISSUE TITLE
Hide Finder with no open windows feature suggestion

### ISSUE THREAD

**Issue by GaganN18** [lwouis/alt-tab-macos#1010]
The app can be improved by adding an option in the appearances tab that hides the Finder app with no open windows, as when there's is nothing open and I press alt tab, I am forced to open Finder just to close it again, that would be a really good feature to add, Thanks.

**Comment by lwouis** [comment]
Such preference is already available. It's not just Finder though. It will hide any app that's running but has no open window.

> I am forced to open Finder just to close it again

I don't understand this sentence 😅 Finder is an app that's always running on macOS. If you have no open Finder window, just ignore the Finder icon in AltTab if you don't want to activate Finder. I don't understand that you are "forced to open Finder" and then that you "close" it.
