### ISSUE TITLE
[Mojave] Cannot use AltTab switch from VSCode to other Apps

### ISSUE THREAD

**Issue by Fightsea** [lwouis/alt-tab-macos#1014]
**Describe the bug**

When use AltTab switch into VSCode window, then I cannot switch to other Apps any more.
(In this case, MacOS native Cmd+Tab works fine.)

MacOS: v10.14.6
AltTab: v6.8.0
VSCode: v1.57.0

You can refer to below video for more detail.

**Screenshots / video**

https://www.loom.com/share/78c1f3de6aac4d10bb1f7f64e2a7aafc

**Steps to reproduce the bug**

1. Enable AltTab (All Apps, All Spaces, All screens).
2. Use AltTab to switch into VSCode window.
3. Once switched to VSCode, then I cannot use AltTab to switch to any other Apps any more (Chrome, Calendar, Finder, etc.).

**Comment by lwouis** [comment]
Please see this: https://github.com/lwouis/alt-tab-macos/issues/992#issuecomment-863836998

**Comment by Fightsea** [comment]
Thank you!
After installed VSCode 1.57.1, it works fine now!

**Comment by JasonLee925** [comment]
it's not working for v1.67.2!
