### ISSUE TITLE
[Question] Is there feature "export settting.json" ?

### ISSUE THREAD

**Issue by ganyariya** [lwouis/alt-tab-macos#1018]
Hello!
I love this app, because it's easy to use very much, and UI is so so beautiful!

I would like to export `alttab`'s setting, because I would like to handle setting in my dotfiles.

#51
#43

In `#43`'s commit, the setting files are registerd in `~/Library/Preferences/alt-tab-macos.json`, however at now this configulation json file is not there...

Thank you!

**Comment by lwouis** [comment]
Please refer to [these explanations with a suggestion on how to proceed](https://github.com/lwouis/alt-tab-macos/issues/650#issuecomment-707567797) 👍

**Comment by ganyariya** [comment]
Thank you very much!
