### ISSUE TITLE
Allow customisation of active item background color

### ISSUE THREAD

**Issue by pedropombeiro** [lwouis/alt-tab-macos#1019]
**Is your feature suggestion related to a problem? Please describe.**
It is hard for me to distinguish which window is going to become active when using AltTab (maybe because I'm using the dark OS theme).

**Describe the solution you'd like**
I would like to be able to customise the color or the item background color to make it stand out more from other items.

**Comment by lwouis** [comment]
Did you try the Windows 10 theme? It's high contrast

**Comment by pedropombeiro** [comment]
> Did you try the Windows 10 theme? It's high contrast

That works, although not ideal since I'd prefer not to have a square rectangle around thumbnails in macOS (looks so out-of-place 😉)

**Comment by lwouis** [comment]
I'll close this ticket now. If you still think the issue can be improved please check out 
https://github.com/lwouis/alt-tab-macos/issues/82#issuecomment-669982304 and comment there in great details what an improvement would involve. So far no one has done that, so the task was closed, but i can reopen it if you're motivated to help make it happen
