### ISSUE TITLE
Add preference: remove AltTab from the menubar

### ISSUE THREAD

**Issue by fturcheti** [lwouis/alt-tab-macos#103]
I don't like to keep lots of apps on the menubar, and AltTab has no crucial feature to be sitting there. Actually, I think it should "invisible" to the user, just showing up when activated to switch windows. So it would be nice to have an option to remove its icon from the menubar.

**Comment by lwouis** [comment]
That sound a bit extreme to me. An app that has no dock icon when active, and no menubar, means that the user has no conventional way to interact with it.

How would you quit the app? How would you change the preferences?

Let's say you can call a shortcut for both. What it you forgot the shortcut, how would you get unstuck then?

**Comment by nathang21** [comment]
Just a though. Is it possible to simply have it open the preferences view
when launched from the Mac Applications menu? For exiting the application,
a quit button could be added in that UI.

**Comment by lwouis** [comment]
I think what you're describing is what The Unarchiver does. I actually
dislike this UX as it is not intuitive and over time you can forget that
the app is running.

I'm kind of against this change, but i want to be open to other people
preferences, so this could be done as a preference.

You're free to open a PR that has a "hide from menubar" checkbox. I think
you'd have to jump through a bunch of hoops to make that happen though as
it's clearly not a use-case Apple has in mind for third-party apps. I'm
guessing the implem would be very hacky.

Please feel free to open that PR though. If it's not adding too many
hard-to maintain things, then i'll merge it for sure :)

**Comment by fturcheti** [comment]
> That sound a bit extreme to me. An app that has no dock icon when active, and no menubar, means that the user has no conventional way to interact with it. 

There are other apps that provide this kind of experience. Often, they warn the user about this choice with some info about the consequences of this option (and generally they're target to "advanced" users). A way to interact with this apps is to "launch them", clicking on its icon in the Applications folder, in the Dock (if they're pinned there) or using Spotlight/Alfred/Quicksilver…

But another way to solve this issue would be to provide a selector "Show AltTab in" with the options "Menu bar" and "Dock". This way, user that like to have apps in the menu bar, including the ones that use apps like Bartender and Vanilla to manage them, could opt to keep things as they are now (that could be the default). But users that don't like to have lots of apps sitting in their menu bar could opt for moving the icon to their Dock.

**Comment by akx** [comment]
> Let's say you can call a shortcut for both. What it you forgot the shortcut, how would you get unstuck then?

E.g. Dash has options for "No Dock Icon" and "No Menubar Icon". If you set both, it helpfully warns that you can re-launch the app, and it'll show the main window for you. I think we could do the same here.

**Comment by jpuris** [comment]
As a workaround that may suit your use case, would be to use something like https://www.macbartender.com/. This is my currently preferred method.

I do agree that this is a welcome change and my thumbs up go for
- Open menu window, when app is open again, while running

Similar or same behavior can be observed with following apps
- Contexts
- Alfred
- ???

**Comment by fturcheti** [comment]
> As a workaround that may suit your use case, would be to use something like https://www.macbartender.com/. This is my currently preferred method.

Yes. For that I'm trying [Dozer](https://github.com/Mortennn/Dozer), cited by @akx in another discussion in this project. It seems to work better than [Vanilla](https://matthewpalmer.net/vanilla/) and it is cheaper than Bartender ;)

> I do agree that this is a welcome change and my thumbs up go for: Open menu window, when app is open again, while running

I think that's the best solution too. And that is what @akx suggested above when using Dash as an example. But just making things clear, this behavior would be better expressed as "_Open ~~menu window~~ Preferences window, when app is launched again while running in background_"

**Comment by davidbarton** [comment]
I understand your position on this issue but there are many people between us including me who have some kind of OCD. In this case to have menu bar extremely thin. I am trying to remove every single app there and keep only os essentials (and not even all of them).

From feature perspective it is much easier to navigate and achieve tasks when you remove all the noise from the menu and keep there only the apps you use frequently.

> Just a though. Is it possible to simply have it open the preferences view
when launched from the Mac Applications menu? For exiting the application,
a quit button could be added in that UI.

This is a preferred way how to interact with the app when required. Mainly because this is setup once and forget kind of app for me and I do not plan to change anything ever.

Would really be happy for option to hide app icon from menu bar.

**Comment by mrc247-DE** [comment]
or exchange the "AltTab" lettering for a small symbol that does not take up so much space in the menubar

**Comment by lwouis** [comment]
> or exchange the "AltTab" lettering for a small symbol that does not take up so much space in the menubar

This is going to be done with the release of v3, hopefully next week. The menubar icon is going to be discussed in #38

**Comment by ezity** [comment]
If/when this is implemented, it would be nice to also implement a shortcut to access the preferences though `,` while Alt-Tab is showing on the screen.

**Comment by L1cardo** [comment]
Is there any PR about this problem?   If non, I would like to do this feature.

**Comment by lwouis** [comment]
@L1cardo nobody has taken the task yet. You are very welcome to do it. In case you haven't seen, here are [some contributing docs](https://alt-tab-macos.netlify.app/contributing).

Regarding the UI, I had this in mind:

![image](https://user-images.githubusercontent.com/106195/87160883-aa211d00-c2fe-11ea-91e7-4352c17ed4fb.png)

Regarding the UX, when the menubar icon is hidden, the user becomes unable to access its dropdown menu, so we need a way to let the user access its features:

![image](https://user-images.githubusercontent.com/106195/87161249-36cbdb00-c2ff-11ea-9714-ae15f72333b0.png)

Thus I suggest these adjustments:

* Double clicking the app in `/Applications` displays the Preferences panel (only if the app is already running)
* The Preferences panels already has ways to check updates, and send feedback. However, we need to let the user quit the app. I found the way Swish does it really nice:  
  ![image](https://user-images.githubusercontent.com/106195/87161212-261b6500-c2ff-11ea-8a50-b1af6208cebb.png)

What do you think?

**Comment by L1cardo** [comment]
I don't know if this will work?
![iShot2020-07-11上午12 07 45](https://user-images.githubusercontent.com/33802186/87175078-b14e2800-c30a-11ea-8e41-2845d93ebe33.gif)

**Comment by medeiroshudson** [comment]
@lwouis is this feature removed for the latest version? I miss it in mine preferences pane 😢

**Comment by lwouis** [comment]
@medeiroshudson no it's there. On the first tab, please click the icon dropdown. There you can select the row with no icon.

**Comment by medeiroshudson** [comment]
It's true. I didn't pay attention to that!
Thanks a lot @lwouis !

**Comment by KingPsychopath** [comment]
> @lwouis OK, it is done. ![屏幕录制2020-07-11 上午1 04 09 2020-07-11 01_09_23](https://user-images.githubusercontent.com/33802186/87180485-32112200-c313-11ea-9a66-e7d45102bf53.gif) [ ![屏幕录制2020-07-11 上午1 04 09 2020-07-11 01_09_23](https://user-images.githubusercontent.com/33802186/87180485-32112200-c313-11ea-9a66-e7d45102bf53.gif) ](https://user-images.githubusercontent.com/33802186/87180485-32112200-c313-11ea-9a66-e7d45102bf53.gif) [ ](https://user-images.githubusercontent.com/33802186/87180485-32112200-c313-11ea-9a66-e7d45102bf53.gif)

Wanted to say Thank you again for this.
