### ISSUE TITLE
Text UNDER the icon

### ISSUE THREAD

**Issue by kravchik** [lwouis/alt-tab-macos#1035]
Would be great to place window names UNDER the icon, because in my scenario - I am usually don't use previews but am making icons big. Because as I work with several IDE windows - preview doesn't make much sense as they mostly look the same. But the icon with text (under it) makes much more sense.

**Comment by lwouis** [comment]
In the preferences, you can disable thumbnails, as well as increase the app icon size and the text size. You can completely customize the UI

**Comment by mr-mmmmore** [comment]
Hey, this ticket has been closed without really answering the main proposition, which was to be able to place the text under the icon and preview. I would love this option which would make it possible to get closer to the system switcher's UI and save a lot of room when only using icons and texts.

**Comment by lwouis** [comment]
@mr-mmmmore. The text being under the icon may be addressed with #351.

**Comment by kravchik** [comment]
I agree, it wasn't answered. But instead, I found an even better approach:

1. only icons ("Hide window thumbnails")
2. no text at all ("Window title font size" == 0)
3. "Preview selected window" (thanks to which - I don't need window thumbnails, and I don't need icon titles)

**Comment by mr-mmmmore** [comment]
thanks @kravchik but I find the "preview selected window" option too "brutal", I don't want the whole screen to change that  fast.
