### ISSUE TITLE
Hide status icon is not working.

### ISSUE THREAD

**Issue by iamyoki** [lwouis/alt-tab-macos#1042]
**Describe the bug**

Hide status icon in preference appearance setting is not working.

**Screenshots / video**

![image](https://user-images.githubusercontent.com/74389358/126093269-9004e215-8282-4611-a500-921a5d6749d4.png)

**Steps to reproduce the bug**

1. Go to 'preference setting'
2. Click on 'appearance' 'hide status icon'

**Comment by lwouis** [comment]
"Hide status icon" hides icons on the thumbnails indicated that windows are minimized, fullscreened, hidden, etc

If you want to hide the menubar icon, you need to use another preference here:

**Comment by iamyoki** [comment]
Thank you!
