### ISSUE TITLE
Dim windows from non-active space

### ISSUE THREAD

**Issue by singalen** [lwouis/alt-tab-macos#1048]
**Describe the solution you'd like**

HyperSwitch manages to cover 2 needs with one Alt-Tab feature: show windows from current Space and from all Spaces, and still make the current space navigate-able.
It shows the windows from other Spaces a bit dimmer than windows from the current one.

It would be awesome to have this feature in AltTab.

**Describe alternatives you've considered**
This could be a configuration option, or it could just work this way.

**Comment by lwouis** [comment]
Similar to https://github.com/lwouis/alt-tab-macos/issues/678

Today we already have the Space number in the corner of the thumbnail to help discriminate windows. We could add another preference to dim these instead yes. It would be yet one more preference thought, which has its drawbacks.

We would probably want to give 2 options for the windows to dim:

* Active Space
* Visible Spaces

The second would be preferred by people with multiple displays setups

**Comment by singalen** [comment]
Thank you!
I'm afraid the space number is too small, I didn't notice it. 
My issue could be solved with a bigger/adjustable space number size, but I feel it's inferior to dimming anyway. The Spaces could be renumbered by the system, so matching the number with current window's number will take some brainpower to calculate.
