### ISSUE TITLE
Not possible to alt-tab from Skype

### ISSUE THREAD

**Issue by s0rl0v** [lwouis/alt-tab-macos#1050]
Does anyone face this too or it's just me?
It started to occurr for me after updating Skype to 8.74.0.152

**Comment by lwouis** [comment]
A quick Google search seems to indicate that Skype is now using Electron. Electron has introduced a change which breaks window focus on macOS. Many apps are impacted. We have established that the bug:

* Is in Electron. I have shown a [video reproducing the bug without AltTab being open](https://github.com/lwouis/alt-tab-macos/issues/1038#issuecomment-883164524) for example.
* Can't be worked around in AltTab

See more info:

* [VSCode ticket](https://github.com/lwouis/alt-tab-macos/issues/992#issuecomment-863836998)
* [Figma ticket](https://github.com/lwouis/alt-tab-macos/issues/1038#issuecomment-883164524)
