### ISSUE TITLE
"Show windows from: Screen showing AltTab" not wroking since AltTab-6.14.0.zip

### ISSUE THREAD

**Issue by wanyaxing** [lwouis/alt-tab-macos#1052]
**Describe the bug**

I have three monitors for working, I used HyperSwitch to switch apps in each monitor.

I tried to replace HyperSwitch with AltTab.

In the lastest version 6.22.1,  the AltTab showed all windows from all monitors, it was too sad.

I tested the old releases of AltTab, luckly, AltTab-6.13.0.zip is working perfect for me.

So, it seems that something was changed in AltTab-6.14.0.zip, please check it.

Thanks.

**Screenshots / video**
<img width="1440" alt="Xnip2021-07-27_14-49-20" src="https://user-images.githubusercontent.com/7940795/127109636-a6e13ebc-f9c6-4f6b-b9cd-5f2a2c141882.png">

↑  AltTab-6.13.0.zip

<img width="1440" alt="Xnip2021-07-27_14-48-25" src="https://user-images.githubusercontent.com/7940795/127109677-0e9e5190-43e3-4d97-9016-81c505e22520.png">
↑ AltTab-6.14.0.zip

**Steps to reproduce the bug**

1. test with two or more monitors.
2. setting as "Show windows from: Screen showing AltTab" 
3. test with AltTab-6.13.0.zip  and AltTab-6.14.0.zip, find the different with these two version.

**Comment by lwouis** [comment]
I need more information to help me understand the issue.

in your screenshot above, I see for example that Chrome is not shown in the old release. 

* On which monitor is that Chrome window?
* What exactly is your multi-monitor setup?
  * Are you mirroring some monitors? Having 3 separate monitors? Extending some screen on multiple monitors?
  * Is this checkbox checked or not?  
  ![image](https://user-images.githubusercontent.com/106195/127141973-0ecb6aa7-babf-4795-a08a-94b946eb80e6.jpeg)

**Comment by wanyaxing** [comment]
* the screenshot is in left monitor, Chrome and GitKraken are in other monitors.  
* NO MIRROING.
* NO CHECKED.

see the images below for more information.
<img width="668" alt="Xnip2021-07-28_15-40-33" src="https://user-images.githubusercontent.com/7940795/127283484-aed9784f-18c7-4ed9-a138-0f069d8d2080.png">

![image](https://user-images.githubusercontent.com/7940795/127269678-72bc9cf4-09d3-427a-a117-8c460fc3dccd.png)

Thanks.

**Comment by lwouis** [comment]
Thank you for the extra info! Which preference did you set in `Appearance > Show on`?

![image](https://user-images.githubusercontent.com/106195/127294222-526c4ff5-ef57-4f3f-ac8e-b053c03a872f.png)

**Comment by wanyaxing** [comment]
Screen including mouse

![image](https://user-images.githubusercontent.com/7940795/127295162-8b240003-0ac9-4a1b-85c3-fe665d9f71e9.png)

**Comment by lwouis** [comment]
I'll try to reproduce this using 2 monitors. Having the "Displays have separate Spaces" checked is uncommon so less tested. Last time I worked on this I remember it working though, so it could be an issue with macOS 11.

Also to note, I think I will update the 2 preferences for Space and Screen:

![image](https://user-images.githubusercontent.com/106195/127337671-5db319a1-4c5b-4963-916f-cc5605392b19.png)

and merge them into one. From:

1. All Spaces
2. Visible Spaces
3. Active Space

1. All Screens
2. Screen showing AltTab

To:

1. All Screens/Spaces
2. Visible Screens/Spaces
3. Screen showing AltTab

**Comment by lwouis** [comment]
I reproduced the issue. It's indeed specific to having the "Displays have separate Spaces" checkbox checked.

I will release a version with the fix soon.

Regarding my proposal to update the preferences (see above), I realized that my proposal didn't make sense. Indeed it's useful to separate screen and Space. A user may want to see all Spaces on a given screen, or only the visible Spaces on that screen.

Thus I modified as such:

```
1. All Spaces
2. Visible Spaces
3. Active Space

1. All Screens
2. Screen showing AltTab
```

To:

```
1. All Spaces
2. Visible Spaces

1. All Screens
2. Screen showing AltTab
```

The `Active Space` was conceptually conflicting with `Screen showing AltTab`, so now that's solved. Furthermore, I don't think anyone was using this setting. `Screen showing AltTab` is useful for most users, then it would be `Visible Spaces`.  Other combinations, though technically possible, don't strike me as realistic for anyone to desire.
