### ISSUE TITLE
Cannot detect muCommander windows

### ISSUE THREAD

**Issue by GJRobert** [lwouis/alt-tab-macos#1053]
(Loving AltTab and thank you!)

**Describe the bug**

Windows of [muCommander](https://www.mucommander.com/) (a Java-based cross-platform file manager), cannot be detected by AltTab. (Pity)

Environment: macOS 11.4, Apple Silicon M1

**Steps to reproduce the bug**

1. Install muCommander.
2. Launch it.
3. Trigger AltTab and see no thumbnail of muCommander windows.

**Comment by lwouis** [comment]
I downloaded muCommander (`v0.9.7 (dmg, 85.9 MB)`), ran it a few times, created windows, and everything shows correctly in AltTab.

I'm running macOS 10.15 on an Intel mac. I'm thinking that your issue could be stemming from either macOS 11 or the M1 mac.

Could you try on a different machine to get more data points, and understand which environments can reproduce this issue? A video of the issue in motion on your system may also help notice a clue of what could be at play.

**Comment by GJRobert** [comment]
Yes indeed, having no problem on my other MacBook, Intel, 10.14 Mojave.

But... man it's doing well all of sudden with muCommander with my M1 MacBook! Oh, I am very embarrassed. I cannot reproduce the issue right now.

Perhaps I should close this issue for the time being. And thanks a lot for your time. Very sorry.

**Comment by lwouis** [comment]
No problem! Let me know if it comes back, and we can re-open this ticket 👍

**Comment by GJRobert** [comment]
A new discovery which does not affect much normal usage:
On my macOS 11.4 + Apple Silicon setup, new windows of muCommander 0.9.7 are appearing normally in the AltTab list. But if a window is opened and closed automatically by muCommander, such as a "Copying files" progress dialog AFAIS, the window is closed but still appearing in the AltTab list.

Just a note for now. I'm wondering if this is due to some different handling of Java app windows on Silicon machines.
