### ISSUE TITLE
Minor issues in French transalation

### ISSUE THREAD

**Issue by Anon9475** [lwouis/alt-tab-macos#1063]
Merci pour le travail de traduction.

Quelques coquilles :
- Menu de l'icône AltTab : "À Propos de AltTab" ==> "À propos de AltTab".
- Préférences... / Contrôles / Fenêtres montrées : "Visible Spaces" ==> "Espaces visibles".
- Préférences... / Apparence : "Lignes d'apercu" ==> "Lignes d'aperçu".

Les remerciements ne sont pas traduits, mais ça ne semble pas nécessaire.

(I'm not used to GitHub, sorry if it is not the right place for translation issues.)

**Comment by lwouis** [comment]
@Anon9475 tu peux [directement faire les changements ici](https://poeditor.com/join/project/8AOEZ0eAZE). Ca ne demande aucune connaissance technique, et c'est ouvert a tous sans condition. C'est mieux que si c'est moi qui reprend tes changements parce que tu seras credite de ta contribution [sur le site](https://alt-tab-macos.netlify.app/thanks), et dans l'app elle meme 👍

![image](https://user-images.githubusercontent.com/106195/127783054-d91088fe-2edc-4683-9cf7-a05fc8354640.png)

**Comment by Anon9475** [comment]
Merci, c'est fait !

**Comment by lwouis** [comment]
The fixes are live I believe. Closing this ticket 👍
