### ISSUE TITLE
Hidden windows (cmd+h) are not listed

### ISSUE THREAD

**Issue by jackbravo** [lwouis/alt-tab-macos#108]
Applications hidden using cmd+h shortcut are not listed.

Seems like HyperSwitch has the same behaviour. And searching their settings I could not find any way to show hidden windows.

On the contrary, this functionality is provided by contexts app:

![Screen Shot 2020-01-03 at 11 34 06](https://user-images.githubusercontent.com/15214/71738844-75974a80-2e1d-11ea-9838-fed3ccf5137c.png)

**Comment by lwouis** [comment]
I just released [version 2.3.0](https://github.com/lwouis/alt-tab-macos/releases/tag/v2.3.0) which supports windows of hidden apps. @jackbravo could you give it a try? :)

**Comment by jackbravo** [comment]
@lwouis indeed it works!!! Thanks a lot!

On a side note, when replacing the previous release and relaunching, I had to delete all `AltTab` entries from the System Settings -> Privacy because otherwise it was complaining about not having the permission. Only after deleting and adding again it recognized the options.
