### ISSUE TITLE
Hope to add the function of adjusting the height

### ISSUE THREAD

**Issue by hicaicai** [lwouis/alt-tab-macos#1083]
1. I would like to be able to lower this box to be able to put it anywhere on the screen instead of at a fixed height.
2. I also want to set the number of recently used programs to be displayed, for example, the last 5 applications, instead of adding all of them, I checked the options and it seems that every program will be displayed, so I resized it so that only 5 applications are displayed in the first line and the others are hidden underneath, but I think it is still not very convenient, because when I use the mouse to automatically select it, it always moves to below, even though I know I can cancel mouse auto select.
![image](https://user-images.githubusercontent.com/43660716/130398391-93cffd9b-e4d7-4bca-b684-c0ee171f95b6.png)

**Comment by lwouis** [comment]
Hi @hicaicai 

I must confess i was quite surprised by the nature of your proposed changes. This is quite a unique setup you're interested in. I can't recall anyone discussing anything similar in around 2 years of this project being open. I don't know any alternative apps that do this either.

1. What's your goal in lowering the bar here?
2. Why do you only want to see 5? What if the one you need is the 6th? Then how would you reach it? Is there no other way you could have a similar workflow? You could maybe have the 5 windows on 1 Space and set AltTab to only show the current Space? Or maybe a setup with [ubar](https://brawersoftware.com/products/ubar)?

**Comment by hicaicai** [comment]
Yes, I often use no more than 5 apps back and forth, but occasionally I use other apps, and if I show too many programs at once, it will be bad for selection, so I will select the less frequently used apps from the dock bar at the bottom, so I can distinguish them. Your method also works, but if you put them to other desktop and then open another app, it will still show more than 5 programs and then I have to readjust, I don't know if I made it clear that this is my usage habit. Also is it possible to add the function of limiting the mouse to select down automatically, if I want to select down I can use the scroll wheel, just like the web page, so I can achieve the purpose I just mentioned.
And I adjust the height because I think it is a little high, every time the mouse moves over too far, I am not too used to keyboard operation. Thank you for your reply.

**Comment by hicaicai** [comment]
I just solved the problem of displaying the number, by another method, which I think is also good, but I still think the height is a bit high.
![Uploading 截屏2021-08-23 19.52.16.png…]()

**Comment by hicaicai** [comment]
I just solved the problem of displaying the number, by another method, which I think is also good, but I still think the height is a bit high.

**Comment by hicaicai** [comment]
I just solved the problem of displaying the number, by another method, which I think is also good, but I still think the height is a bit high.
![image](https://user-images.githubusercontent.com/43660716/130444561-4709db23-cc67-4644-88d2-f129cb498f88.png)

**Comment by lwouis** [comment]
It seems you want the height to be the same as the app switcher. There is a ticket for that: https://github.com/lwouis/alt-tab-macos/issues/585

Since you solved the second issue, I think we can close this ticket. You can follow/participate to the existing ticket for the height issue.
