### ISSUE TITLE
Support moving windows between Spaces

### ISSUE THREAD

**Issue by pedorro** [lwouis/alt-tab-macos#1088]
**Is your feature suggestion related to a problem? Please describe.**
AltTab switcher does not support moving selected window to a different desktop space

**Describe the solution you'd like**
Desired behavior - steps:
1. launch switcher (Alt-Tab)
2. select a window
3. while continuing to hold Alt, tap a number key associated with a desktop space
4. the selected window is moved to the numbered desktop space

**Describe alternatives you've considered**
HyperSwitch supports this function

**Comment by lwouis** [comment]
I think we need to dig deeper into what the UX would be for this feature.

* How would you customize the shortcuts? And avoid conflicts with other shortcuts?
* What does the preferences look like for this feature?
* How do you address Spaces beyond 10?
* What if he Space selected already has fullscreen window(s)?

**Comment by pedorro** [comment]
I think I stumbled across this HyperSwitch feature by accident.  I already have keyboard mappings to jump between Spaces as Cmd+<Space #> (e.g. Cmd+2 switches me to Space #2). So my fingers are just used to that behavior, and I must have just tried it on a whim.  You're right that it's totally undocumented though.  At this point it is a core bit of my daily desktop workflow, and has been for years.  I use it all the time, and can't imagine having to use Mission Control, or something mousey like that, to do this.

As for AltTab UX - I'd be glad to offer ideas.  Perhaps the simplest option would be to just have a single toggle to enable/disable this feature, and then it uses the number keys while the switcher is open.  As you note, this would be limited to 10 Spaces, but I imagine that would be sufficient for the vast, vast majority of use cases.  This does limit customization, but I'll argue that's ok, as the number keys are both intuitive to associate with numbered Spaces, and easily accessible while the thumb is holding the Cmd/Alt key.

For the question about Spaces with full-screen windows, I'll be honest, I don't really understand what happens to full-screen windows on MacOS, but they don't seem to actually be on any desktop Space anymore.  For example, if I open a full-screen window on Space #4, then jump over to Space #3, then back to #4, the full-screen window is gone.  It's still open somewhere (I can see it in the dock), but it's not on Space #4 anymore.  TBH, I actually don't really know how to find it anymore at all (Mission Control? I forget how to open it).  Regardless, I don't think that really adds any complication to this feature.

Please let me know if there's anything I can do to help.  I know nothing about MacOS development, but I'm fully keyboard-first in my desktop workflow, using HyperSwitch, Spectacle, and Vim-bindings anywhere I can.  I'd love to have an alternative to HyperSwitch, which seems relatively abandoned at this point.

**Comment by Mehechiger** [comment]
Amazing findout about how this works in HyperSwitch! I've used this feature in the HS too but never realised how it worked exactly.

I have defined a Hyper key to be combined with numbers in order to switch between Spaces and have remapped the trigger key for HS to be also Hyper + spacebar. Thus I accidently discovered that while having focused a window in HS, still holding the Hyper key and tap the number of the Space would do the job.

Since I merely used the keyboard shortcuts defined in the System Preferences, I can actually go beyond the limit of 10 — by assigning the 11th Space to Hyper + - for exemple.

So one more vote from me to adding this feature and hope that my user case of this feature in the HS could be of help.

**Comment by pedorro** [comment]
Just confirming that this feature of HyperSwitch is broken in Monterey.  So we probably won't be able to replicate whatever tricks it was using, to make this work in Alt-Tab.

**Comment by lwouis** [comment]
After careful consideration, I've decided that this feature will not be implemented. The scope of AltTab is switching to windows. It will not extend beyond and start doing window management, such as resizing or moving windows around. For such a task, a full window management solution is a better target. I recommend https://github.com/koekeishiya/yabai

Thank you 🙇
