### ISSUE TITLE
Window thumbnails only show parts of the window that are on-screen

### ISSUE THREAD

**Issue by lwouis** [lwouis/alt-tab-macos#110]
It seems that the screenshot API doesn't show offscreen content

**Comment by lwouis** [comment]
I compared the 3 known screenshot APIs:

* (private) CGSHWCaptureWindowList: **doesn't** show offscreen content
* (private) CGSCaptureWindowsContentsToRectWithOptions: **doesn't** show offscreen content
* (public) CGWindowListCreateImage: : **does** show offscreen content

The issue being that the only API that shows offscreen content is by far the slowest

**Comment by Robinhuett** [comment]
A possible solution for this would be to check if the `GRect` of a window is in the `GRect` of the screen and if this is not the case taking the screenshot with `CGWindowListCreateImage`.
I have briefly tested this and it seems to work not to bad. Having multiple displays is a performance hit, here would be more logic required than I currently have in place.

@lwouis If you like I can make a PR for this.

**Comment by lwouis** [comment]
I actually already thought about doing that, but I'm not convinced it's actually an improvement:

* The trade-off here is speed vs accuracy. Different people will prefer one over the other.
* Some users may have lots of windows partially off-screen. These users will think the app is slow
* One could argue that the window being cut are a better representation for the user when they are browsing the list of thumbnails. If my window was half off-screen, maybe I'll locate it faster in the list of thumbnails if it's showing the visible half there. I'm not convinced by this argument btw, but I thought it's interesting to think about

We could:

* Add another preference for that
* "Vote" somehow on which way should prevail
* Let the "market" decide by waiting for complaints and change the status quo if people complain enough

Overall I would say because our time is limited, let's keep the status quo until people actually complain by upvoting the ticket I opened

**Comment by lwouis** [comment]
For some reason I don't understand, it seems that the windows are shown entirely now, at least on my machine. I can put them partially off-screen, and they show entirely in AltTab.

Should I close this ticket? It is happening for anyone else?

**Comment by lwouis** [comment]
Closing this ticket as it seems the cropping stopped at some point.
