### ISSUE TITLE
Max width/height in pixels

### ISSUE THREAD

**Issue by jovalle** [lwouis/alt-tab-macos#1107]
**Is your feature suggestion related to a problem? Please describe.**
Usage of percentage is not visually consistent across monitors with different aspect ratios. At 32:9, I prefer 35%/80% but know this won't look as well on a more ubiquitous 16:9 monitor.

**Describe the solution you'd like**
Perhaps a checkbox to toggle units (e.g. pixels).

**Describe alternatives you've considered**
Per monitor configurations would be much more complicated.

**Comment by lwouis** [comment]
This is an interesting workaround that avoid per-monitor configuration. I like it!

**Comment by lwouis** [comment]
A solution was implemented starting with 7.1.0. AltTab now calculate its width based on the estimated user field of view. It will vary based on the physical size of the display.
Thank you 🙇
