### ISSUE TITLE
some apps not showing in Big Sur

### ISSUE THREAD

**Issue by bboles** [lwouis/alt-tab-macos#1123]
**Describe the bug**
In versions 6.23.0 and 6.24.0, Slack and MacVim don't show up in the switcher.  If I downgrade to 6.22.1 the issue goes away.  This is in MacOS 11.5.2.

Things I tried that did not make any difference in 6.23.0 and 6.24.0:
* Stopping and restarting AltTab with the apps in question already active.
* Start AltTab and then start either of the apps in question.
* Uninstalling AltTab, rebooting and re-installing AltTab.

**Steps to reproduce the bug**

1. Install AltTab version higher than 6.22.1.
2. Start Slack and/or MacVim.

Please let me know if any further information is needed.

<details>
  <summary>Debug Info</summary>

  ## Video Info
  ```
  Chipset Model:	AMD Radeon Pro 5500M
  Type:	GPU
  Bus:	PCIe
  PCIe Lane Width:	x8
  VRAM (Total):	4 GB
  Vendor:	AMD (0x1002)
  Device ID:	0x7340
  Revision ID:	0x0040
  ROM Revision:	113-D3220E-190
  VBIOS Version:	113-D32206U1-019
  Option ROM Version:	113-D32206U1-019
  EFI Driver Version:	01.A1.190
  Automatic Graphics Switching:	Supported
  gMux Version:	5.0.0
  Metal Family:	Supported, Metal GPUFamily macOS 2
  Displays:
    2778X:
      Resolution:	2560 x 1440 (QHD/WQHD - Wide Quad High Definition)
      UI Looks like:	2560 x 1440 @ 60.00Hz
      Framebuffer Depth:	30-Bit Color (ARGB2101010)
      Display Serial Number:	GJGHAHA014808
      Mirror:	Off
      Online:	Yes
      Rotation:	Supported
      Automatically Adjust Brightness:	Yes
      Connection Type:	Thunderbolt/DisplayPort
    2778X:
      Resolution:	2560 x 1440 (QHD/WQHD - Wide Quad High Definition)
      UI Looks like:	2560 x 1440 @ 60.00Hz
      Framebuffer Depth:	30-Bit Color (ARGB2101010)
      Display Serial Number:	GJGHAHA014807
      Main Display:	Yes
      Mirror:	Off
      Online:	Yes
      Rotation:	Supported
      Automatically Adjust Brightness:	Yes
      Connection Type:	Thunderbolt/DisplayPort
  
  
  Chipset Model:	Intel UHD Graphics 630
  Type:	GPU
  Bus:	Built-In
  VRAM (Dynamic, Max):	1536 MB
  Vendor:	Intel
  Device ID:	0x3e9b
  Revision ID:	0x0002
  Automatic Graphics Switching:	Supported
  gMux Version:	5.0.0
  Metal Family:	Supported, Metal GPUFamily macOS 2
  ```
</details>

**Comment by lwouis** [comment]
Hi,

Thank you for the detailed report. Could you please share which versions of Slack and MacVim you're using here?

Thank you

**Comment by bboles** [comment]
Slack: Version 4.19.0, 31a81cb6995ba59a85ab1e048ae9207591cac044@1631027846 (App Store)
MacVim: 8.2.1719 (166)

**Comment by lwouis** [comment]
I tried on my macOS 11 (Big Sur) with v6.22 and it shows Slack. Then I updated to v6.24, and it still shows Slack. I was unable to reproduce the issue.

Could you please share a video of the issue in motion?

**Comment by bboles** [comment]
I was about to make a video to reproduce the issue and noticed that version 6.25.0 was available.  I went ahead and upgraded and the issue seems to be resolved.  I can see all of the apps as expected.

Thanks for your work on AltTab @lwouis , I couldn't use MacOS without it!

**Comment by lwouis** [comment]
I'm glad to hear that. However i'm surprised since there was no code change for that issue in the new release. If the issue re-surfaces, let me know and we will re-open this ticket 👍

**Comment by singalen** [comment]
@lwouis, I reproduced it on 6.33.0, Slack, MacOS 12.3.1. Even when Slack window is open, it's not in the switcher.
I tried showing everything with "Hidden windows", "Minimized windows" and "Hide apps with no open windows" - it didn't help.

Restarting AltTab DID help.

Slack is special in that regard that I hide and unhide it a lot of times. Probably some data race happened at some point?

**Comment by singalen** [comment]
This got worse in the latest (6.41.1) - Slack never shows up in AltTab. Tried restarting both Slack and AltTab, didn't help.

**Comment by lwouis** [comment]
@singalen Please update to v6.42.0 which contains a fix for this regression. Let me know if an issue persists on 6.42.0 (not this issue though: #1324; we have no solution for this issue yet)
