### ISSUE TITLE
Add preference to group windows by space and/or by app.

### ISSUE THREAD

**Issue by jaypdl** [lwouis/alt-tab-macos#1126]
I'd like to still show windows from All apps, All spaces, and All Screens.
This would be a separate "Grouping" option, perhaps in appearance?

Add a preference to group app windows by Space, by App, or by both (with an option for which to prioritize by).

When opening the tab switcher currently the order of windows seems almost random (I guess by most recently active?).  
But I'd like to be able to see everything grouped more orderly in one place, without needing separate shortcuts for by app/ by space/ by screen (Especially since there are only 2 shortcut options).

**Comment by lwouis** [comment]
Please discuss this in the already existing ticket #337
