### ISSUE TITLE
Popup window showing in android studio.

### ISSUE THREAD

**Issue by susonthapa** [lwouis/alt-tab-macos#1128]
**Describe the bug**

I have clearly described the bug [here](https://issuetracker.google.com/issues/196244653). In a nutshell Android Studio quickly shows a window when try to switch between files and I believe `AltTab` holds onto the window even after Android Studio internally dismisses the window. 

**Screenshots / video**

It's provided in the attached link.

**Steps to reproduce the bug**

1. Install android studio ArticFox
2. Create a method with only one usage
3. Cmd click the method to find the usage

**Comment by lwouis** [comment]
We've had a lot of issue with Android Studio: https://github.com/lwouis/alt-tab-macos/issues?q=is%3Aissue+android+studio+is%3Aclosed

Did you get a look at those?

As far as I remember, we worked around these issues from Android Studio by hardcoding its `bundleIdentifier` in a few places in AltTab.

My first guess would be that maybe this `ArticFox` version you're using has a different `bundleIdentifier`. Is this the official release, or some kind of alpha/beta version?

**Comment by susonthapa** [comment]
Thank you, I was using older version of `AltTab`. A quick update fixed the issue. Sorry, I created the issue without using the latest versions. Anyway keep up the good work.

**Comment by lwouis** [comment]
Wonderful~
