### ISSUE TITLE
Use keybord Number to Jump to the Target Window

### ISSUE THREAD

**Issue by Acring** [lwouis/alt-tab-macos#1133]
Hey Guy!
Thanks for the perfect mac software and I wish it can be better.

Here is my suggestion: 

I wish that when i open alttab, the index can be positioned on top left of the windows, and I can use keybord number like 1,2,3,4,5 to select window rather than use up, down, left, right. I think it would be more effective for using. 

anyway.

thanks~~

**Comment by lwouis** [comment]
Please have a look at the existing #210. It discusses this, and more
