### ISSUE TITLE
Add new theme/layout which mimics the built-in app switcher

### ISSUE THREAD

**Issue by kodmanyagha** [lwouis/alt-tab-macos#1148]
There are "macOS" and "Windows 10" style window lists. Is it possible that you add "Mac Style" window list?

Thanks...

**Comment by lwouis** [comment]
Hi,

I'm confused by your distinction between `macOS` and `Mac Style`. `macOS` is the name of the mac operating system. This is the default theme. It aims to blend with the all the other apps and the operating system, on a mac.

Could you please go into more details as to what this new theme would change? You can see here the colors, border values, etc, related to themes: https://github.com/lwouis/alt-tab-macos/blob/eabc327edcea85b39c729255db903cdabf7b1f27/alt-tab-macos/logic/Preferences.swift#L45.

Thank you

**Comment by kodmanyagha** [comment]
Hi,

Let me tell you explain with screenshots.

Original Macos window list:
![image](https://user-images.githubusercontent.com/3948692/134354241-330f2c11-00ab-4482-bab7-65d52830ee27.png)

App window list:
![image](https://user-images.githubusercontent.com/3948692/134354587-7f4af740-0d6c-4855-a63e-22112321a278.png)

If you can add this style then it will be awesome I think.

**Comment by lwouis** [comment]
It would be complex to offer exactly this. You can get really close to it already today by increasing the app icon size in the preferences. The text is on the right side always though.

There are complex UX issues with the built-in app switcher design as well. Please read this: https://github.com/lwouis/alt-tab-macos/issues/82#issuecomment-577480530

Offering alternate layouts like the one you suggest should be done properly. It shouldn't conflict with the existing appearance preferences. I'm not sure how we present that in the preferences.

**Comment by gsemet** [comment]
Hi. Would I recommend to have a background selection a bit lighter, because it is hard to tell which icon is select on dark background. Windows 10 theme adds a contour, so it is more visible, but the macos theme is barely usable
![Screenshot 2021-09-28 at 10 14 53](https://user-images.githubusercontent.com/133498/135050292-0b78b5df-63e1-49d7-b418-e9cc6090a66a.png)

**Comment by lwouis** [comment]
Hi @gsemet, please read https://github.com/lwouis/alt-tab-macos/issues/82#issuecomment-577480530 for discussion around why it's hard to make a light background theme.

Of course, feel free to share a PR if you have an idea on how to execute it 👍

**Comment by lwouis** [comment]
Closing this as it's about someone submitting a new theme now, and there is nothing being discussed here anymore
