### ISSUE TITLE
Space doesn't work to focus selected window if another app has ⌥Space set as a hotkey

### ISSUE THREAD

**Issue by lilyball** [lwouis/alt-tab-macos#1152]
**Describe the bug**

The default settings for AltTab is to have the Space key focus the selected window. I have ⌥Space set as my hotkey for Alfred. And of course ⌥⇥ is my hotkey for AltTab. And when I press ⌥⇥ and hold ⌥ to bring up the switcher, pressing Space does nothing at all. If I quit Alfred then it works.

It appears that Alfred is intercepting the Space because of the ⌥Space hotkey, but it's not actually doing anything when I press it. I don't know if this is because it attempts to appear but cannot steal focus, or what.

Is there any way for AltTab to effectively take priority on the Space key here?

**Steps to reproduce the bug**

1. Have Alfred running, with ⌥Space as its hotkey
2. Have AltTab running with the default configuration (⌥⇥ as its hotkey and Space as the "focus selected window" key).
3. Press ⌥⇥ and continue holding ⌥
4. With ⌥ held, press Space
5. See how nothing at all happens.
6. Quit Alfred.
7. Perform steps 3 and 4 again
8. See how it now focuses the window.

**Comment by lwouis** [comment]
Alfred listens to a global shortcut (reacts anytime) whereas AltTab listens to a local shortcut (reacts when AltTab is open). Alfred thus gets the keyboard event first, then decide or not to let it go to the next app. It seems it absorbs it.

Nothing AltTab can do about it. Even if AltTab used a global listener for the local shortcuts, there is no API to negotiate priorities between apps. How would it even look like? Every app would ask for top priority if they could.

Just imagine for a second a user who wants exactly the opposite scenario: they want Alfred to have priority over AltTab. This shows that priority should be a tool in the hands of users, not the apps themselves. Only the user can decide which app should go first. They can even change their mind over time.

Unfortunately macOS provides no such facility to users, and the list of apps listening to global shortcuts is never shared with the user, nor is it tweakable.
