### ISSUE TITLE
Support high-dpi displays

### ISSUE THREAD

**Issue by lwouis** [lwouis/alt-tab-macos#116]
Currently the UI consists of:

* A menubar UI: standard UI components; will scale automatically ✔
* A preferences window: standard UI components; will scale automatically ✔
* The feedback panel: custom UI; will not scale automatically ❌
* The thumbnail panel: custom UI; will not scale automatically ❌
* There may also be some padding and other details where the values are hardcoded in pixels instead of some dynamic solution ❌

Most of the work here should be done on the thumbnail panel to adapt to low/high dpi by adapting it depending on the OS setting in System Preferences > Display > Resolution > Text size:

![image](https://user-images.githubusercontent.com/106195/72408427-3ca88f80-37a6-11ea-9c58-3b6b267c8389.png)

**Comment by akx** [comment]
FWIW, the thumbnail panel looks fine on my MBP's retina display (and I'm running in More Space mode).

![Screenshot 2020-01-17 at 15 10 31 (2)](https://user-images.githubusercontent.com/58669/72614777-cc337700-393b-11ea-96e8-0da815c37f04.jpg)

**Comment by lwouis** [comment]
Here is how scaling is shown on a retina display:

![image](https://user-images.githubusercontent.com/106195/80862576-19501480-8cb1-11ea-9cca-93cb2ad09261.png)

Here are the 2 extremes options on my laptop currently:

| Larger text | More space |
|------------|-------------|
| <img src="https://user-images.githubusercontent.com/106195/80862527-d3934c00-8cb0-11ea-91ff-26d7adba3595.jpg" width="45%" /> | <img src="https://user-images.githubusercontent.com/106195/80862535-d7bf6980-8cb0-11ea-97e7-7d6da00f2f8d.jpg" width="45%" /> |

**Comment by lwouis** [comment]
Scaling of text and images is consistent with the rest of the OS. I'll close this ticket as I can't really see what we could do to improve high-dpi displays.

One issue I found is that the Acknowledgements preference panel is cropped at the bottom, while on the Larger text display mode:

![Screen Shot 2020-05-02 at 20 21 57](https://user-images.githubusercontent.com/106195/80862831-fe7e9f80-8cb2-11ea-9b94-5a0570e2a0ff.jpg)


I was curious and inspected first-party apps. I was expected some of them to have their preferences panel scrollable when too tall for the screen, but it seems they simply never exceed a certain height.

I will change the Acknowledgments tab to be less tall.
