### ISSUE TITLE
Documenting how to map it to Command + Tab

### ISSUE THREAD

**Issue by giacomorebonato** [lwouis/alt-tab-macos#1161]
**Is your feature suggestion related to a problem? Please describe.**
Hi, I love this app and I find it perfect so far. First of all: thank you!
I'd like to make it the default app switching UI by binding it to command+tab.

**Describe the solution you'd like**
This is probably a matter of me not knowing how to achieve this on Macos or reading to quick your docs :)
Is this information available anywhere?
If not, maybe it's a good idea to have it on the website (and sorry if it's already there and I missed it).

**Describe alternatives you've considered**
I didn't consider any other alternative.

**Comment by lwouis** [comment]
Hi @giacomorebonato!

This is supported already. You can simply open the app's preferences. To do that, click the icon on the menubar:

![image](https://user-images.githubusercontent.com/106195/135097110-0dad7f7d-5865-4664-b18e-3ca585e36e54.png)

Then set the shortcut to `command-tab`:

Before (`option-tab`) | After (`command-tab`)
-|-
![image](https://user-images.githubusercontent.com/106195/135097206-be46a46f-47eb-424e-8091-9573ccb1ed08.png)  | ![image](https://user-images.githubusercontent.com/106195/135097161-0f17c9c5-5eed-49ce-933d-55cd2cbca64b.png)

**Comment by giacomorebonato** [comment]
Thank you!
