### ISSUE TITLE
finder open/save dialog becomes slow when alt-tab open

### ISSUE THREAD

**Issue by pdtxie** [lwouis/alt-tab-macos#1169]
when alt-tab is open, finder open/save dialog becomes very slow

reproduce:
1. open alt-tab
2. go to safari
3. open a pdf
4. save pdf, cmd+s, notice that dialog is very laggy upon opening and no float in animatio

video:
https://user-images.githubusercontent.com/65262710/136481985-d39d9eaa-3291-4f8d-ad3c-45c90a1edec1.mp4

n

**Comment by barhom** [comment]
I have the same issue, where is the duplicate issue?

**Comment by lwouis** [comment]
@barhom here is the main ticket: #718
