### ISSUE TITLE
Slowness

### ISSUE THREAD

**Issue by pgpv** [lwouis/alt-tab-macos#1204]
There are several issues here about alttab's slowness but they all focus on the window preview aspect of it. Problem is...it is still slow even with window previews disabled. So I'm thinking either previews are still happening even when disabled or the slowness is not caused (only, at least) by previews.

Just wanted to add that comment but all the slowness issues have been closed and this is more of a general comment so I figured I'd open a new one.

**Comment by lwouis** [comment]
This topic is being discussed in this large ticket: https://github.com/lwouis/alt-tab-macos/issues/563

Your data point that it's happening (not sure exactly what is happening, from your description actually) with thumbnails turned off is useful to exclude that code from the investigation 👍

**Comment by pgpv** [comment]
Sorry, I missed that one. Just to make it clear, I mean slow to show up, as in, when I press alt-tab it takes like a second for the ui to show up.
