### ISSUE TITLE
High ram usage(2GB+!!!)

### ISSUE THREAD

**Issue by DavithkbY** [lwouis/alt-tab-macos#1207]
**Describe the bug**

AltTab uses a lot of ram(2GB+) on M1 pro macbook 16. I don't think it's normal that a background app that runs 24/7 should be using 2GB+ram!

**Screenshots / video**

![image](https://user-images.githubusercontent.com/71630103/140653357-4afbaffc-8810-41a2-92d3-9e7692dec5b8.png)

**Steps to reproduce the bug**

1. Use alttab
2. Open activity manager and see that it uses a lot of ram.

**Comment by lwouis** [comment]
This is not normal. AltTab usually has a small resources footprint on the system. See mine right now for instance:

![image](https://user-images.githubusercontent.com/106195/140654050-4e9ea332-edb9-435f-9adb-960a9476fd0e.png)

Could you please use the this form here to submit a ticket with a debug profile? 

![image](https://user-images.githubusercontent.com/106195/140654064-119b6106-9ca5-4b52-96cb-8960d19420a2.png)

![image](https://user-images.githubusercontent.com/106195/140654080-a718b7bd-f411-45da-be08-00db2995fa8a.png)

In the debug profile is some CPU/RAM info. It may help.

Other than that, could you share more about your setup?

* macOS version?
* AltTab version?
* How many monitors? Resolution and refresh rate of each monitor?

Also, is this always like this from the moment you start AltTab? Or is it possible it happens only under certain circumstances like you launch a particular app?

**Comment by DavithkbY** [comment]
> This is not normal. AltTab usually has a small resources footprint on the system. I've worked hard on this.
> 
> See the consumption on my machine right now for instance:
> 
> ![image](https://user-images.githubusercontent.com/106195/140654050-4e9ea332-edb9-435f-9adb-960a9476fd0e.png)
> 
> Could you please use the this form here to submit a ticket with a debug profile?
> 
> ![image](https://user-images.githubusercontent.com/106195/140654064-119b6106-9ca5-4b52-96cb-8960d19420a2.png)
> 
> ![image](https://user-images.githubusercontent.com/106195/140654080-a718b7bd-f411-45da-be08-00db2995fa8a.png)
> 
> In the debug profile is some CPU/RAM info. It may help.
> 
> Other than that, could you share more about your setup?
> 
> * macOS version?
> * AltTab version?
> * How many monitors? Resolution and refresh rate of each monitor?
> 
> Also, is this always like this from the moment you start AltTab? Or is it possible it happens only under certain circumstances like you launch a particular app?

I just sent the feedback.

Alttab v 6.25.0
Macos 12.0.1
And just the built in display of 2021 M1 PRO 16 inch macbook pro

I haven't checked if this is always but just noticed it after a work session and was amazed that it used that much ram.

**Comment by lwouis** [comment]
> I just sent the feedback.

Github broke the feedback form by revoking their token (they perceived there was a security issue; there wasn't). I fixed it in AltTab v6.26.0. Could you please update to it, and send the feedback again?

![image](https://user-images.githubusercontent.com/106195/140654689-16d54dec-c4e5-442c-a744-f37f87433327.png)

> I haven't checked if this is always but just noticed it after a work session and was amazed that it used that much ram.

Could you please experiment a little bit? I can't reproduce this issue on my machine, so your help is crucial. Could you for instance close AltTab, restart it, and check the RAM then? (updating to v6.26.0 will restart it, so you could just check RAM after that)

**Comment by DavithkbY** [comment]
Hi

Just installed 6.26 with the m1 mac build of alttab. At first it started with 80MB ram usage, after I opened a few tabs and started playing around it's up to 422MB ram within 5 minutes. The feedback tool doesn't work with the m1 arm build, should I get the intel version and try to reproduce it?

**Comment by DavithkbY** [comment]
Since I ended writing this, the ram went up to 500mb almost xD 
![image](https://user-images.githubusercontent.com/71630103/140655064-6e84416b-7cea-4ba3-a3f6-99fed29bc4a7.png)

**Comment by DavithkbY** [comment]
The feedback tool started working after I focussed out of chrome, just sent the feedback.

**Comment by lwouis** [comment]
> The feedback tool started working after I focussed out of chrome, just sent the feedback.

There doesn't seem to have been any ticket posted here. You mentioned using an M1 build. I imagine you got it from the PR? I don't know what's in that build, so not sure if the Github token issue is fixed in that build.

How about the intel build (only one I'm familiar with / am maintaining)? It is also using high RAM? Could you try it? The feedback form should work in that one, as I've triaged multiple feedback tickets recently from it.

**Comment by DavithkbY** [comment]
> > The feedback tool started working after I focussed out of chrome, just sent the feedback.
> 
> There doesn't seem to have been any ticket posted here. You mentioned using an M1 build. I imagine you got it from the PR? I don't know what's in that build, so not sure if the Github token issue is fixed in that build.
> 
> How about the intel build (only one I'm familiar with / am maintaining)? It is also using high RAM? Could you try it? The feedback form should work in that one, as I've triaged multiple feedback tickets recently from it.

I reinstalled mac os fully, since I had used migration assistant to transfer all apps/data from my old mac to my new one. I can't reproduce the memory bug anymore. I have was having big memory leaks on the old install as well. Now I experience no memory leaks on other apps nor on altTab. I will let you know if I notice it again but I think it's fixed with a fresh install of mac os.

**Comment by lwouis** [comment]
Good news, albeit scary that such issues can come from the OS.

I'll close this ticket for now then
