### ISSUE TITLE
feat: able to close windows

### ISSUE THREAD

**Issue by CelinaSkywalker** [lwouis/alt-tab-macos#121]
When you open the tab switch, an 'x' in the upper right corner to close the window would be useful.

**Comment by nathang21** [comment]
+1 I've gotten very use to this on other OS's and i've always felt this
missing on OSX.

**Comment by lwouis** [comment]
We have this, and a lot of other "quick-actions" discussed in #9. We even have a PR #94 that's WIP. As soon as v3 lands (hopefully in a few days/weeks), #9 is one of the highest priority ticket to work on, for me at least.

Closing this for now as there is way more scope and discussion already in #9. Please watch that one to get notified when it's implemented and released :)
