### ISSUE TITLE
Can't get alt-tab to load preferences file from another machine

### ISSUE THREAD

**Issue by dvcrn** [lwouis/alt-tab-macos#1219]
**Describe the bug**

I moved a `com.lwouis.alt-tab-macos.plist` file from my old machine to my new one but alt-tab is refusing to load it, it just overwrites the file with a new one as soon as I do anything. 

I tried locking the preferences file and removing write access completely, but it still doesn't want to load it

**Steps to reproduce the bug**

1. Turn off alt-tab
2. Move `com.lwouis.alt-tab-macos.plist` file into ~/Library/Preferences and overwrite the old file
3. Start alt-tab

Expected behavior:

Alt-tab loads the same settings that my old machine had

Actual behavior:

Alt-tab doesn't load the settings, instead initializes from scratch and overwrites the preferences file

**Comment by lwouis** [comment]
I just tested this on my machine, and it works. I can delete the plist file, launch AT, notice the preferences are reset, then overwrite the plist file with the previous version I had set aside, and after I launch AT, the preferences are back as they were before.

I'm thinking that maybe the issue you have is that you have a different version of AltTab on the new machine? A user who upgrades AltTab sees their preferences carried over / adapted into the new designs/systems as AltTab evolves. The opposite is not supported: using new preferences with a previous version of AltTab.

* Which versions of AltTab are you running on each machine?
* What's the preferences file version in your old preferences? You can see it by running `defaults read com.lwouis.alt-tab-macos preferencesVersion`

**Comment by dvcrn** [comment]
I've deleted alt-tab and installed to the exact same version from scratch and now it's all working fine. Not sure what exactly the issue was but it's all good now, thank you!

**Comment by introom** [comment]
@lwouis My config file is 
```/Users/user/Library/LaunchAgents/com.lwouis.alt-tab-macos.plist```

And the content is quite limited:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>Label</key>
        <string>com.lwouis.alt-tab-macos</string>
        <key>LimitLoadToSessionType</key>
        <string>Aqua</string>
        <key>Program</key>
        <string>/Applications/AltTab.app/Contents/MacOS/AltTab</string>
        <key>RunAtLoad</key>
        <true/>
</dict>
</plist>
```

This is the only plist file I have. There is none in the "Application Support" directory. 

Which file should I back up to save the settings?

**Comment by introom** [comment]
@lwouis My config file is 
```/Users/user/Library/LaunchAgents/com.lwouis.alt-tab-macos.plist```

And the content is quite limited:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>Label</key>
        <string>com.lwouis.alt-tab-macos</string>
        <key>LimitLoadToSessionType</key>
        <string>Aqua</string>
        <key>Program</key>
        <string>/Applications/AltTab.app/Contents/MacOS/AltTab</string>
        <key>RunAtLoad</key>
        <true/>
</dict>
</plist>
```

This is the only plist file I have. There is none in the "Application Support" directory. 

Which file should I back up to save the settings?

**Comment by lwouis** [comment]
@introom the file you mention is for the start-at-login functionality. It doesn't have any preference in it.

Try running this in Terminal.app:

```sh
defaults export com.lwouis.alt-tab-macos > ~/Desktop/com.lwouis.alt-tab.macos.plist
```

It should save AltTab's preferences in a file on your desktop. You can them import it back elsewhere with `defaults import [...]`

**Comment by hotsno** [comment]
This same thing is happening to me on the latest version. Both machines are using the same version of AltTab (6.64.0). As soon as I re-open AltTab after replacing the `.plist`, it overwrites the file with a new one. Can anyone else reproduce this?

**Comment by hotsno** [comment]
> @introom the file you mention is for the start-at-login functionality. It doesn't have any preference in it.
> 
> Try running this in Terminal.app:
> 
> ```shell
> defaults export com.lwouis.alt-tab-macos > ~/Desktop/com.lwouis.alt-tab.macos.plist
> ```
> 
> It should save AltTab's preferences in a file on your desktop. You can them import it back elsewhere with `defaults import [...]`

Just to help anyone finding this comment, I believe the correct command is actually:
```sh
defaults export com.lwouis.alt-tab-macos ~/Desktop/com.lwouis.alt-tab-macos.plist
```
