### ISSUE TITLE
Preferences window is cut off

### ISSUE THREAD

**Issue by MKGitHub** [lwouis/alt-tab-macos#1226]
**Describe the bug**

Preferences window is cut off.

**Screenshots / video**
![Screenshot  2021-11-13 at 17 06 49](https://user-images.githubusercontent.com/535550/141650815-7ff2c382-be25-48ae-aa2a-37b4c9298782.png)

**Comment by lwouis** [comment]
Duplicate of https://github.com/lwouis/alt-tab-macos/issues/1062
