### ISSUE TITLE
allow movement with VIM arrows (H J K L)

### ISSUE THREAD

**Issue by Salomanuel** [lwouis/alt-tab-macos#1229]
It would be mind-blowingly amazing if, among the arrow keys, it would be possible to move around with the vim movement keys (that, as we all know, are fairly superior and should also replace steering wheels and handlebars, but I'll submit that feature suggestion elsewhere)

[Hyperswitch](https://bahoom.com/hyperswitch/get) got me used and now it's difficult to live without
and it's a shame because as far as I know, Hyperswitch development ended and, except for this basic and necessary feature, Alt-Tab is a vastly superior program

The main advantage is that those keys are right where the right hand should be (the J key has a tactile bump for touch typing) and there is no need to blindly move it to the other side of the keyboard or, god forbid, shamelessly look down at the keyboard looking for those keys far in the right beyond any key row.
Also, users not blessed with this habit usually have their right hands sitting over inferior devices such as trackballs or, in unrecoverable cases, over a mouse. So they would hardly press those legendary keys by mistake, rendering this feature not confusing for people with little confidence with computers.

it basically works like this: (unfortunately not my keyboard, as I don't yet have a dedicated key for μ)
![image](https://user-images.githubusercontent.com/14359139/141772758-8da2de6c-83e3-4006-b1b0-d85d3bc1f51e.png)

feel free to state your perplexities and I'll gladly explain why you are all wrong

**Comment by lwouis** [comment]
There is already a PR (https://github.com/lwouis/alt-tab-macos/pull/1080) that's quite close to getting this feature to ship. I messaged its author, as we've let it sleep for a few months. You may be interested to check it out, test it out, and maybe complete it if you're a programmer 👍

**Comment by lwouis** [comment]
Please also note that the PR author's has thought of issues that your ticket don't mention such as:

> The keys H, J, K, and L move the window selection left, down, up, and
right, respectively. AltTab already uses 'H' as the default key to
hide/show apps. If "Vim keys" is enabled when hide/show is in its
default configuration, the hide/show action will be shadowed by "Vim
keys." It is possible to enable both hide/show and "Vim keys" by
overriding the default key for hide/show.

Please read the discussion in the PR to get familiar with some of the issues we've found while discussing the implementation of vim keys in AltTab.

**Comment by david-r-cox** [comment]
I opened an updated PR for this today: https://github.com/lwouis/alt-tab-macos/pull/1272
