### ISSUE TITLE
AltTab blocks ESC key from working in other applications

### ISSUE THREAD

**Issue by florianorben** [lwouis/alt-tab-macos#123]
When AltTab is active (i.e. has been opened, but is not in currently in use) pressing the ESC Key is no longer propagated to other applications.
This is particularly annoying when trying to close modals/dialog windows.

I guess this bug has been introduced here:
https://github.com/phungtuanhoang1996/alt-tab-macos/commit/9fd0c16d701b11a8013556ea6715c71a5a9be010#diff-b338575fcf6c3370769d63a924a2a1deR52

Presumably changing line 52 to 
`if type == .keyDown && isEscape && application.appIsBeingUsed {`
should fix the bug - I don't have an active switft development setup to test the changes though.

**Comment by lwouis** [comment]
Oh that's terrible! I will make a fix right away

**Comment by lwouis** [comment]
@florianorben I just released [2.3.4](https://github.com/lwouis/alt-tab-macos/releases/tag/v2.3.4) which should have this issue fixed

**Comment by florianorben** [comment]
@lwouis Working again with 2.3.4! Thanks for the quick fix!
