### ISSUE TITLE
Quick switch to last tab

### ISSUE THREAD

**Issue by andresespinosapc** [lwouis/alt-tab-macos#1237]
**Is your feature suggestion related to a problem? Please describe.**
When I want to switch to the last opened window, the layout to select windows opens. I found this behavior very annoying.

**Describe the solution you'd like**
When pressing the shortcut for a brief amount of time it should only switch to the last window without showing any UI.

**Describe alternatives you've considered**
Just using the native tab switcher for this matter and having Alt-Tab set with another shortcut.

**Comment by lwouis** [comment]
@andresespinosapc I'm not sure i understand your problem.

AltTab is really quick at showing its view. It means it's actually pretty often impossible for a human to release the shortcut before AltTab shows on screen.

That being said, AltTab caters to your use-case by letting you setting a minimum delay before it shows:

![image](https://user-images.githubusercontent.com/106195/142425595-79b1cb70-ea39-4d75-bfbd-2c41a06a582b.png)

It's `Apparition delay`. Set it to a timing value that you feel comfortable with. I think 250ms is fine for most adults.

**Comment by andresespinosapc** [comment]
Sorry, didn't saw that setting. Thanks! That was exactly what I was looking for, it works like a charm
