### ISSUE TITLE
Better handling of RStudio and apps which launch multiple instances

### ISSUE THREAD

**Issue by benwhalley** [lwouis/alt-tab-macos#1238]
**Is your feature suggestion related to a problem? Please describe.**

RStudio launches different R sessions in different instances of the App, rather than different windows. Some other cross-platform apps which aren't very good Mac citizens may also do the same.

This is super annoying because switching between open windows doesn't work as expected. Also, the text label on each Rstudio window in the default task switcher is tiny and hard to read.

I thought using Alt-Tab might improve this, but using shortcut-2 to cycle between open windows from the same app doesn't work (because they are actually different instances).

**Describe the solution you'd like**

Is it possible to group different app-instances as you would different windows? The executable is identifiably the same in the `ps -A |grep RStudio` output, so it seems like it would be possible.

**Describe alternatives you've considered**

I can't think of any alternatives! But this would be really nice!

**Comment by lwouis** [comment]
> Is it possible to group different app-instances as you would different windows?

I don't understand what you mean. What do you mean by "to group"? You mean that instead of having multiple icons in AltTab, one for each running application, you would like to have only 1? But then which one would it refer to? Like what if you want to close, hide, of focus a specific instance among the multiple instances open?

**Comment by benwhalley** [comment]
Sorry - I just mean, to treat all running instances of the same executable as you would different windows of a single app that is open.

So, with RStudio, if you pressed the alt-tab shortcut which shows windows for the active app, then the other instances of the executable would also be shown. At present, because each instance only has a single window, you can't do this.

I realise it's a workaround for the poor behaviour of the other app (not using windows when they should and instead spawning multiple instances off the app) but it would be useful for this.

**Comment by lwouis** [comment]
Oh, I see what you mean now. Unfortunately that would mean really bending AltTab's internals for that one app. It would be a lot of work, and it could even create regressions for the other apps if there is any mistake. There is too much risk and the reward would be limited to RStudio users with multiple windows.

I'm afraid I'll have to close this ticket. I strongly suggest you share this ticket URL with the RStudio maker so they work on a UX improvement. Hopefully they listen and improve things on their app.
