### ISSUE TITLE
After Update not starting

### ISSUE THREAD

**Issue by niveKKumar** [lwouis/alt-tab-macos#1242]
Just updated to the latest version and first it worked fine, now after restarting my Macbook it doesn't want to open at all.

Device: Macbook M1 Air
OS: 12.0.1 (21A559)

**Comment by lwouis** [comment]
What do you see on screen? Crash report? "This app quit unexoectingly"? Nothing?

Is there any material you can share like logs, crash report, maybe open the app in Terminal.app and share the logs from there.

We need something to work off of

**Comment by niveKKumar** [comment]
I just get nothing when trying top open, also opening it with the terminal open AltTab.app doesn't give any logs...
I tried even with older versions, same result... just nothing

First time I ever got any issue before it all worked...

**Comment by niveKKumar** [comment]
<img width="591" alt="image" src="https://user-images.githubusercontent.com/48483421/142725665-eb5d9e6b-3f00-4f3b-bce2-89f651510cb9.png">
That's what the activity monitor gives, it just closes...

**Comment by lwouis** [comment]
Your screenshot shows the parent process being launchd. This would imply you're showing AltTab after it was launch after you logged in.

You mentioned you also can't open previous versions? That seems weird since you said it was working before.

Can you a video of you opening up the old version in the terminal?

**Comment by niveKKumar** [comment]
Okay using AppCleaner (not just the recycle bin) to uninstall and reinstall made it work again, I have no clue why. I opened the older version also in the terminal got nothing....
