### ISSUE TITLE
Cycling through backwards

### ISSUE THREAD

**Issue by simoheinonen** [lwouis/alt-tab-macos#1247]
**Describe the solution you'd like**
I'd like to go be able to cycle through backwards. If there are many open windows it takes a while to get to the last one

**Comment by lwouis** [comment]
The app already offers that feature. Default shortcut is `option+shift` but you can customize it in the preferences:

![image](https://user-images.githubusercontent.com/106195/143066831-ecc12b41-156c-4b42-a63e-07f84abcb83d.png)
