### ISSUE TITLE
Add donate button

### ISSUE THREAD

**Issue by dr-dimitru** [lwouis/alt-tab-macos#1261]
Hello @lwouis ,

How can we support you? Please, add donate button to your GitHub profile, or at least PayPal link
Great package, thank you for the work you've done.

**Comment by lwouis** [comment]
I appreciate your kind words! Thank you!

I don't take donations. I'm always looking for contributors though, if you have technical background and some time to spend on the app 👍

**Comment by mkudlacek** [comment]
That's a major downside of this application - no donate button. I might stop using it just because of this:)

Seriously, your app increased my productivity by miles. Excellent work @lwouis.
