### ISSUE TITLE
Allow usage without screenshots not requesting access to accessibility "Screen Recording"

### ISSUE THREAD

**Issue by dr-dimitru** [lwouis/alt-tab-macos#1262]
**Is your feature suggestion related to a problem? Please describe.**
UX issue

**Describe the solution you'd like**
1. Allow to disable access if "Hide window thumbnail" option enabled in the app's settings
2. Enable "Hide window thumbnail" by default if a user does not allow access to "Screen Recording" accessibility feature

**Describe alternatives you've considered**
I like it using without thumbs (thumbs distract me). I'd love to add additional context to icon and window title; Icon + App name as the title (window no.) + subtitle with full window title excluding app's title, like (very schematic):

```
——————
|icon|  SAFARI
——————  GitHub · New Issue
```

Other suggestions and alternatives are welcome; thrive the community 👨‍💻

**Comment by lwouis** [comment]
There is already a ticket for this: #1082
