### ISSUE TITLE
make it work

### ISSUE THREAD

**Issue by 1r0npipe** [lwouis/alt-tab-macos#1263]
Hello
I was trying to make it avaliable for my mac, however that options seems to me doesn't work for BigSur 11.6, cause I dont see it works for me after I installed, also the screenshots with "appearance" and others options I dont see at my one, I checked that all around maybe I am missing something, but it doesn't change anything to my one, if you could suggest I would be appreciated, thank you

**Comment by 1r0npipe** [comment]
thank you @lwouis , no, I have no anything there and it is confirmed that installed on my system:
```
~ brew install alt-tab                                                                                                                                                           [ 
Running brew update --preinstall...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 2 formulae.

Warning: Cask 'alt-tab' is already installed.

To re-install alt-tab, run:
  brew reinstall alt-tab
```
Also I tried to find it somewhere in settings, there is no such option like activate(or something), I watched video on youtube and read, as it has been said that should work from scratch, but for me, it doesn't I am afraid :(

**Comment by lwouis** [comment]
When you launch the app, what happens? Do you see any change on screen? You're supposed to get a window asking you for system permissions. After you grant those permissions, the app should be running and visible in the menubar.

Does it crash on launch? Do you see an error message? Can you check in Console.app for a crash report maybe? Maybe launch the app from Terminal.app and share the logs you get?

**Comment by 1r0npipe** [comment]
basically nothing happens at all, no any consequences being applied at least at the interface, also the command `alt-tab` is not exist too:
```
alt-tab                                                                                                                                                                        [ 
zsh: command not found: alt-tab
```
I didn't find the work instruction how to verify (or configure, besides of the main web-site, but I have no such configuration window at all anywhere in the global settings)

**Comment by lwouis** [comment]
@1r0npipe I [recorded a video](https://youtu.be/Pdp7If-SGbg) where I show what's supposed to happen the first time you launch AltTab, and I show how to run the app from Terminal.app to debug your issue.

**Comment by 1r0npipe** [comment]
Great! Thank you so much for that video @lwouis , without I could not probably resolve it, I know it looks simple, but I am not profi user at Mac, appreciate you time for that record, please share it also for everyone on the installation page, if possible...

**Comment by lwouis** [comment]
@1r0npipe I'm very glad I was able to help you 👍
