### ISSUE TITLE
Cmd-< shortcut doesn't work on Monterey

### ISSUE THREAD

**Issue by stanc** [lwouis/alt-tab-macos#1278]
AltTab 6.29.0
Mac OS 12.0.1
On a French system and keyboard, setting the shortcut to < doesn't work on Monterey.
Previously, on Catalina, it worked fine.

![image](https://user-images.githubusercontent.com/5937628/145237420-d6faca50-e55f-46e2-8b0a-1e274d746982.png)

**Comment by lwouis** [comment]
Duplicate of #1190
