### ISSUE TITLE
Add scrolling and maybe a limit/"more"

### ISSUE THREAD

**Issue by GregOriol** [lwouis/alt-tab-macos#128]
I often have a big number of windows open (right now: 48), so thumbnails with alt-tab-macos are either very small if I set a setting that allows to display them all or thumbnails are normal and the window gets out of the screen vertically.

Adding a scroll would prevent the window from getting higher than the screen.
Adding a limit/"more" would allow to view the most useful ones first and then if you need all. (but still need a scroll)

**Comment by lwouis** [comment]
Hi @GregOriol! Thank you for sharing your use-case! It's very interesting to hear about your workflow. This idea of "most useful ones first" made me think.

We have had interesting conversation about this very issue in #69 already. Could you please have a look there? I have actually implemented the "downscale each window as there are more windows" approach in the upcoming v3 branch #114. You may want to check it out and see how it works for you. Here is a [fresh build of that v3 branch](https://github.com/lwouis/alt-tab-macos/files/4120457/AltTab-v3-pr.zip) you can just drop-in to test.

If you find the icons are too small, then I think we should keep your ticket here, and continue the conversation on what a better UX for heavy windows user such as yourself.

**Comment by GregOriol** [comment]
@lwouis Thanks for your answer, indeed #69 is the same subject, sorry I didn't see it.. The v3 branch seems to make it work, at least I don't have to manually change the number of rows. The only reason to improve with a scroll or a "more" would be that at some point the thumbnails become too small and less useful, which is the initial purpose of Alt-tab.

(a setting maybe like when you set the font size in interface builder: downscale if doesn't fit, maximum down to... then clip or scroll)

Maybe we can close this issue and continue in #69

**Comment by lwouis** [comment]
#69 will auto-close once I merge the v3 PR as I tagged some a commit with it. I will actually keep this issue open as a reminder to follow-up. Your use-case is very interesting and highlights limitation of downscaling that nobody raised before you.

I think a scrolling UI is not too difficult to implement as well

**Comment by lwouis** [comment]
@GregOriol I was working on #171 and while reworking the layout code, I took the opportunity to implement scrolling. Could you give it a try? It should be usable with keyboard or mouse. Here is a build for convenience: 
[AltTab.app.zip](https://github.com/lwouis/alt-tab-macos/files/4373701/AltTab.app.zip)

**Comment by GregOriol** [comment]
@lwouis This is nice!
