### ISSUE TITLE
Arrow key not working with Logitech MX Keys

### ISSUE THREAD

**Issue by chilljul** [lwouis/alt-tab-macos#1280]
I am not able to navigate through the windows with my arrow keys when using an Logitech Mx keys. The down arrows work fine but not the up, left and right arrows. Is there some fix for it? I have tried closing the Logitech Options Program but that didnt work

**Comment by lwouis** [comment]
Could you please go on [this page](https://w3c.github.io/uievents/tools/key-event-viewer.html), focus the text box, and press `down`, `right`, `left`, `up` on your logitech mx?

This is what I get on my Logitech K380 keyboard (ignore the first 3 rows):

![image](https://user-images.githubusercontent.com/106195/145509349-e53fadf9-ed68-43d9-a0f7-186139147b93.png)

**Comment by chilljul** [comment]
<img width="1067" alt="Bildschirmfoto 2021-12-10 um 07 10 54" src="https://user-images.githubusercontent.com/93071653/145526199-a0b4bf23-d65f-4300-8892-c45d5c1ef65a.png">

This is what I got. I just realised today that if the Macbook is not connected to an external keyboard, the arrow keys on the Macbook (MB Pro 2018 i5 ) wont work either. But if connected, it would work on the Macbook but not on the external Keyboard. So I think it doesn't has to do with that particular Keyboard model specifically

**Comment by lwouis** [comment]
From your description, it seems like something is wrong in your setup, regardless of AltTab.

Are the arrows working in every other apps, are you sure? How about shortcuts containing arrows like to switch tabs in Chrome? This works on internal and external keyboards?

I'm suspecting a problem on your end, unrelated to AltTab

**Comment by lucasale1** [comment]
I got same issue, but when I turn off the keyboard and turned on it got to work normally...

**Comment by lwouis** [comment]
@chilljul any update?

**Comment by chilljul** [comment]
> @chilljul any update?

Yes! I found the issue. I used to have shortcut to reposition my windows either to the right or left using (CMD +right/left) with a Program called Magnet. This command wasn't overwritten when Alttab was used. Now I fixed it by reprogramming the shortcuts in Magnet to CMD + Shift + (left/right)
