### ISSUE TITLE
JetBrains WebStorm not visible

### ISSUE THREAD

**Issue by jherrera123** [lwouis/alt-tab-macos#1288]
**Describe the bug**

JetBrains WebStorm windows are not visible when I press Alt+Tab

**Screenshots / video**

N/A

**Steps to reproduce the bug**

1. Install latest WebStorm version
2. Have a bunch of other windows open (Chrome, etc)
3. Press Alt+Tab
4. All other windows except WebStorm are visible in the AltTab carousel

This bug does not apply to IntelliJ IDEA

**System Information**
AltTab 6.29.0
WebStorm 2021.3

**Comment by jherrera123** [comment]
This must have been a fluke. I just installed WebStorm and started app through Launchpad. I noticed app was missing from spotlight.

Restarted through spotlight when it became available and now I was able to see it in AltTab. Restarted through Launchpad, and surprisingly enough, it was visible in AltTab as well.

Closing as I can't reproduce anymore.

**Comment by lwouis** [comment]
@jherrera123 there are existing tickets for this. It's not consistent indeed. Please see #1249
