### ISSUE TITLE
Divide the preferences panel by topic

### ISSUE THREAD

**Issue by lwouis** [lwouis/alt-tab-macos#130]
Today every preference is packed together, and a list horizontal bar divides topics:

![image](https://user-images.githubusercontent.com/106195/73332433-1278c680-42aa-11ea-922b-f4e921806cfe.png)

I would like to separate preferences by topic. Here is a great example with Bartender:

![image](https://user-images.githubusercontent.com/106195/73332426-0e4ca900-42aa-11ea-914e-ff5595cfb824.png)

**Comment by Robinhuett** [comment]
In v3 the titles on the tabs "Appearance" and "Shortcuts" are switched

**Comment by lwouis** [comment]
> In v3 the titles on the tabs "Appearance" and "Shortcuts" are switched

Thank you! I think I introduced the switch when I localized the interface. It's fixed on the v3 branch now
