### ISSUE TITLE
Option to not show running applications without an active window

### ISSUE THREAD

**Issue by crimsonpython24** [lwouis/alt-tab-macos#1300]
**Is your feature suggestion related to a problem? Please describe.**
I'm always frustrated when I accidentally open an application that is not open but still running (i.e., pressed cmd+w but not cmd+q) as I couldn't find such an option in alt-tab

**Describe the solution you'd like**
Only show applications that are running *and* has an active window. I.e., not showing the applications circled in red:

![IMG_0117](https://i.imgur.com/js1eZj1.jpg)

**Describe alternatives you've considered**
I've tried other alternatives posted by the author on the program's main page, but I still prefer alt-tab.

**Comment by lwouis** [comment]
This is already supported via a preference. The last one in `Appearance`:

![image](https://user-images.githubusercontent.com/106195/147411865-5d90a76a-780b-4d84-b450-ea6fbf93001f.png)

![image](https://user-images.githubusercontent.com/106195/147411862-92a7dc8d-caf8-4501-8456-a7d646cea9c2.png)

**Comment by crimsonpython24** [comment]
The problem is that, I've already selected the option and restarted the application:

![IMG_0117](https://i.imgur.com/ttqGT1D.jpg)
![IMG_0117](https://i.imgur.com/0HkYkyk.jpg)

and the problem still persists.

I've updated the application to the latest release (December 1st)

**Comment by lwouis** [comment]
On your screenshot, the preference is unchecked. You have to check the checkbox to hide the apps with no open window
