### ISSUE TITLE
Missing Window: VSCode (w/ Remote SSH Extension)

### ISSUE THREAD

**Issue by AlJohri** [lwouis/alt-tab-macos#1302]
**Describe the bug**

I'm running into a strange error where VSCode is missing from AltTab when running using the Remote SSH plugin.

**Screenshots / video**

I recorded a [video](https://www.youtube.com/watch?v=wPEOAzOlMIM) of the bug:

[![Alt text](https://img.youtube.com/vi/wPEOAzOlMIM/0.jpg)](https://www.youtube.com/watch?v=wPEOAzOlMIM)

**Steps to reproduce**

_I think there's probably an easier way to reproduce this locally. I will post a comment if/when I figure that out. I think it just has to do with starting new instances of an application from the CLI, as opposed to anything to do with SSH, but I included the instructions for completeness._

1. Install VSCode on your laptop with the CLI and the Remote SSH extension.
2. SSH into any server.
3. Run the following function which SSH's back into your laptop from the server and starts VSCode via the `code` CLI using the Remote SSH plugin.

    ```
    rcode() {
        proj=$(realpath "$1")
        client=$(cut -d' ' -f1 <<<"$SSH_CONNECTION")
        server=$(cut -d' ' -f3 <<<"$SSH_CONNECTION")    
        ssh $client /opt/homebrew/bin/code --folder-uri "vscode-remote://ssh-remote+$server$proj"
    }
    ```

    Note: Replace `/opt/homebrew/bin/code` with the absolute path of your VSCode `code` CLI. It is `/usr/local/bin/code` for intel mac if installed via homebrew.

    4. Run Alt-Tab Show and see no VSCode window.

**Comment by lwouis** [comment]
Can you confirm that the issue doesn't happen with normal CLI launch of `code`? It's specific to this remote plugin setup, correct?

Have you tried contacting the makers of this extension? It's likely on their side

**Comment by AlJohri** [comment]
Honestly, I think my VS Code is screwed up somehow. I'm getting this error when I even just double click on it, even after re-installing. I'll restart / debug further and update if the issue persists after I fix VSCode.

<img width="961" alt="Screen Shot 2021-12-29 at 11 29 07 AM" src="https://user-images.githubusercontent.com/2790092/147683370-73249a6a-d986-409d-8c10-4e18cd1010df.png">
.

**Comment by AlJohri** [comment]
I completely removed VSCode as per [these instructions](https://linuxpip.org/uninstall-vscode-mac/) and reinstalled. All working now with Alt-Tab!

That was certainly weird. Thanks for the quick response! Closing this issue.

**Comment by AlJohri** [comment]
Weird, just wanted to report that this somehow occurred _again_ a few hours after it working smoothly. Will dig in further later.

**Comment by lwouis** [comment]
Most likely an issue on VSCode side, so please contact their support. Could also be due to #1324 in some cases.
