### ISSUE TITLE
Chrome app windows not showing up

### ISSUE THREAD

**Issue by zaks** [lwouis/alt-tab-macos#1309]
**Describe the bug**

No app shortcuts created in chrome are showing up when running.

**Screenshots / video**

Not sure if that's useful.

**Steps to reproduce the bug**

1. Install a Chrome app (e.g. Spotify)
2. Start the app
3. Press AltTab
4. Look for the app window in the overlay pop-up

**Comment by zaks** [comment]
Hi,

This is truly odd, but the issue disappeared! I will keep an eye on it. The
apps will be gone in June 2022, but I think that the shortcuts will remain.

As for Spotify access you can go to open.spotify.com and in the address bar
you will find a new icon to install the app.

Thank you, Slawek

**Comment by lwouis** [comment]
I installed it and it showed properly. Since it's also working on your end, I'll close this ticket 👍

**Comment by ajma** [comment]
I'm running into this problem now. On with Edge Version 97.0.1072.55. It's not happening with Chrome. Maybe it got fixed and Edge is behind.
