### ISSUE TITLE
AltTab should let users quit Finder.app… sometimes

### ISSUE THREAD

**Issue by szhu** [lwouis/alt-tab-macos#1328]
AltTab is a great app, thanks for making it. I have a small suggestion.

**Is your feature suggestion related to a problem? Please describe.**

Finder can be quit through the UI! Finder has a Quit menu item, hidden by default, that [can be turned on with a hidden setting](https://www.defaults-write.com/adding-quit-option-to-os-x-finder/):

    defaults write com.apple.finder QuitMenuItem -bool true;

I treat Finder like any other app. Note that I also [have the Desktop disabled](https://www.defaults-write.com/os-x-how-to-quickly-hide-the-desktop-icons/), making Finder act even less special.

Because of this, I want to be able to quit Finder sometimes (Finder is running less than half the time I use my computer), and so I have this setting turned on.

**Describe the solution you'd like**

Users who have turned on `QuitMenuItem` should be able to quit Finder from AltTab.

I saw that the change in #362 prevents users from quitting Finder from AltTab. I think this makes sense as default behavior, but is it possible for AltTab to read the `QuitMenuItem` preference and to allow power users who have this preference on to be able to quit Finder via AltTab?

Implementation details:

- On the command line, the preference can be read with:

  ```sh
  defaults read com.apple.finder QuitMenuItem
  ```

  The setting is supposed to be a boolean, but people often set it to be a number or string because there's different versions of the `defaults write` floating around on the Internet. I've tested and it seems like the number 1, as well as the strings "1", "yes", "true" (case insensitive), are interpreted as true, while everything else is interpreted as false.

- In Swift, the preference can be read with:

  ```swift
  import Foundation;
  let userDefaultsValue = UserDefaults(suiteName: "com.apple.Finder")?.object(forKey: "QuitMenuItem") 
  ```

**Comment by lwouis** [comment]
This seems like a reasonable refinement. I'll look into it 👍

**Comment by szhu** [comment]
Interesting suggestion and I think that could work, but on second though maybe it's not ideal.

I think the possibility of having Finder be quit would really confuse people who don't know about the concept, especially since it makes the desktop icons disappear.

Besides, I think that the first solution would be easier to implement, since it doesn't require a UI.

**Comment by feep** [comment]
> And if you do it by mistake once in a while, just restart it, no? For Finder, it's a real problem, but for replacement apps, it's a breeze.

It is not (super) intuitive to restart Finder, but it is a breeze. Just click on it in the Dock. It is always in the Dock, and it is not possible to remove it.

**Comment by szhu** [comment]
Just tried out the new release and this feature works great, thanks a lot!
