### ISSUE TITLE
Uninstall the app

### ISSUE THREAD

**Issue by basalts** [lwouis/alt-tab-macos#1330]
Hi,

How I uninstall the app from my Mac?

Thanks.

**Comment by lwouis** [comment]
Please see https://github.com/lwouis/alt-tab-macos/issues/1326#issuecomment-1013663745

**Comment by basalts** [comment]
I already Ok.Thanks.‫ב-10 בנוב׳ 2022, בשעה 18:45, ‏‏Joaquín Pérez Realini ***@***.***> כתב/ה:‬﻿
I moved the app to the trash, but this Louis Pontoise item is still trying to run in the background. Is that you @lwouis?
