### ISSUE TITLE
Whatsapp App windows not shown in the application

### ISSUE THREAD

**Issue by egherardini** [lwouis/alt-tab-macos#1338]
**Describe the bug**

The whatsapp app windows are not displayed / listed in the AltTab windows list.

**Screenshots / video**

Indeed it is not needed, but I attached one (with very basic anonymization :) ): simply reproduce and you will see that whatapp windows are not shown, independently if whatsapp if minimized or present on the screen.

![Schermata 2022-01-20 alle 14 49 18](https://user-images.githubusercontent.com/37186942/150352706-7ceefcbf-f673-48ea-8916-0e6f60933e8b.png)

**Steps to reproduce the bug**

1. open whatsapp app
2. execute AltTab with the shortcut
3. see that there is no whatsapp window in the list

**Comment by lwouis** [comment]
Previously: https://github.com/lwouis/alt-tab-macos/issues/524

**Comment by egherardini** [comment]
Version of MacOS: 12.1
Version of Whatsapp: 2.2147.16

**Comment by egherardini** [comment]
I found the reason: if you open Whatsapp before AltTab (I installed AltTab while whatsapp was already opened and running) AltTab cannot see its windows.

Closing and opening Whatsapp App while AltTab was running solved the issue.
