### ISSUE TITLE
Notes are not displayed in windows that switch apps

### ISSUE THREAD

**Issue by Tinyu-Zhao** [lwouis/alt-tab-macos#1339]
As shown in this video, the memo doesn't show in the window that switches apps

https://user-images.githubusercontent.com/44396641/150677202-6fe8265e-cf20-4644-8c8a-9e783f7611a5.mov

I also didn't add the memo to the banned list

**Comment by pvsenan** [comment]
Do you have show windows from (All spaces enabled) ?
![image](https://user-images.githubusercontent.com/1115925/150767172-e247f249-0d27-47f5-acd1-fa4d67e1f964.png)

**Comment by Tinyu-Zhao** [comment]
Yes, as shown in the settings in the video, I turned on "All Apps", "All Desktops", "All Screens", but it didn't work like in the video
The strange thing is that after I restarted the computer today, he can work normally, is it because the settings did not take effect

**Comment by wagaman** [comment]
I had the same issue and had "all spaces enabled" checked. After I changed the setting back and forth, the issue was solved. It looks like that the setting profile was not read correctly in the first place.

**Comment by wagaman** [comment]
As I recall, the issue only took place after I upgraded the software by clicking on "check for updates".

**Comment by lwouis** [comment]
May be fixed in v6.32.0?
