### ISSUE TITLE
Internationalize the app

### ISSUE THREAD

**Issue by lwouis** [lwouis/alt-tab-macos#134]
The app has text in English for:

* Menubar
* Preferences window
* Feedback window

It would be nice to provide these in other languages. I think a first batch could be done using Google Translate. Maybe some cheap translation service could be used too. The scope is very scope so cost would be marginal.

**Comment by lwouis** [comment]
I started looking into it. I found it very confusing looking online. I learned about the [complex history of localization with Apple and XCode](https://martiancraft.com/blog/2018/11/where-is-localizable-string/).

I want to go with xliff files since they are industry standard. I checked a few OSS tools to edit xliff. Nothing was great. Weblate seems interesting but is not meant to run locally but to be hosted on some server.

The other remarkable player is [POEditor](poeditor.com). They actually have free plans for OSS! I applied :)

**Comment by lwouis** [comment]
Just received this email:

> Congratulations lwouis,
>
>alt-tab-macos has been approved for a free localization project.
>Enjoy localizing and don't be shy to spread the word that POEditor supports the open source movement! 
>
>Cheers,
>The POEditor Team

**Comment by Robinhuett** [comment]
I'd be more than happy to provide the german localization :)
