### ISSUE TITLE
without an internet connection, Alt-Tab chews through CPU cycles

### ISSUE THREAD

**Issue by e40** [lwouis/alt-tab-macos#1356]
Been using Alt-Tab for a couple of weeks.  It just so happened that my internet was out for 18 hours.  I get alerts on my macOS Big Sur machine when the cpu temps are higher than a threshold.  I started getting alerts as soon as the internet connection dropped and they continued until I found the cause: 

    me             1715 124.3  8.2  9152444 2744172   ??  S    Fri07AM  39:10.67 /Applications/AltTab.app/Contents/MacOS/AltTab

Activity Monitor showed it going full bore on a single core and it was the only process doing much (the internet was down, I was offline mostly).

I haven't tested that it will repeat, but I presume it will.

**Comment by lwouis** [comment]
Hi @e40 

Could you please make sure the issue is reproducible and clearly linked to being offline?

On my machine AltTab works fine offline

**Comment by e40** [comment]
I want to be clear: the network on the mac with Alt-Tab was working perfectly.  It was connected to a switch connected to a router, and that router had a temporary gateway connection during the internet outage.

I just want to be clear, it wasn't that the machine running Alt-Tab was disconnected from the network.

As for testing this, I do plan this weekend to move some stuff around, so I'll see if it happens again.

**Comment by lwouis** [comment]
@e40 any news on this?

**Comment by e40** [comment]
I haven't been able to reproduce it.  I'll close it.  Thanks.
