### ISSUE TITLE
[BUG] iina media player is not being shown.

### ISSUE THREAD

**Issue by tracure1337** [lwouis/alt-tab-macos#1363]
[BUG] iina media player is not being shown.
https://iina.io/.

**Comment by lwouis** [comment]
Most likely it's a bug on their side. Could you please contact them about it? I'll re-open the ticket if it's on AltTab side

**Comment by cocoonkid** [comment]
Today it is shown. Meanwhile I could see that this is a issue with random apps. As soon as I reboot they  all appear but after a few days of sleep/wake some seem to disappear... I will report as soon as I see a clear pattern.

**Comment by lwouis** [comment]
It may be #639
