### ISSUE TITLE
do not suppert ysyy when full screen play

### ISSUE THREAD

**Issue by chaos-cn** [lwouis/alt-tab-macos#1364]
**ysyy**

when i use ysyy download from (https://download.cntv.cn/cbox//macv2/ysyy_v2.0.0.0_1001_setup.dmg?spm=0.PsnVeUG5xmKc.E3nZUgkyxygK.5&file=ysyy_v2.0.0.0_1001_setup.dmg)

## chouse any TV program and full screen play 
![iShot2022-02-05 15 56 33](https://user-images.githubusercontent.com/71205599/152634006-90483d90-0c4a-4c95-9f0a-6a2cc85c609d.jpg)
![iShot2022-02-05 15 57 27](https://user-images.githubusercontent.com/71205599/152634011-2c0d10ea-d190-41c1-a5fe-c515c39cc706.jpg)

## then can not find play window in alt-tab
<img width="734" alt="image" src="https://user-images.githubusercontent.com/71205599/152634160-f09220d1-74bc-441f-9986-7b7d9416725b.png">

## Using Default settings:
<img width="344" alt="image" src="https://user-images.githubusercontent.com/71205599/152634078-08c49534-4e10-4292-bf9a-6fd3cf48a519.png">

**Comment by lwouis** [comment]
This is most likely a problem with this app ysyy. Please contact the people making it, and ask them to look into it 👍
