### ISSUE TITLE
Is it possible to NOT show what's not active when alt-tabbing?

### ISSUE THREAD

**Issue by Cookie755233** [lwouis/alt-tab-macos#1369]
This app is brilliant from a Windows user for almost my age, yet I still found myself accidentally open unnecessary apps that's not completely quitted(I mean cmd+w instead of cmd+Q), especially finder. I just cant stop opening Finder folder when I just want to switch back to the previous tab, and Finder by default cannot be quitted. 

Is there already a feature to solve this making it Windows-like, or it's not possible at all ? Thank you.

**Comment by lwouis** [comment]
You can toggle the checkbox in Preferences > Appearance > Show apps with no open window. This will hide apps that are open but have no open window. I think that's what you're looking for?

**Comment by Cookie755233** [comment]
Brilliant! Thank you sir.
