### ISSUE TITLE
Enable GitHub Sponsoring for this project

### ISSUE THREAD

**Issue by kerner1000** [lwouis/alt-tab-macos#1372]
I would like to donate to this project. This would be easy though https://github.com/sponsors. Maybe this can be implemented.

**Comment by lwouis** [comment]
Thank you for your kind gesture! There is no need for donations~

**Comment by dennis-damico** [comment]
I know this has been brought up a few times, but just wanted to add another comment expressing my interest in donating to the project as well!

**Comment by lwouis** [comment]
@kerner1000 @dennis-damico I've added Github Sponsorship to this project today 👍
