### ISSUE TITLE
Setting some specific custom shortcuts (e.g. command+up) crashes AltTab

### ISSUE THREAD

**Issue by Abdullah-l** [lwouis/alt-tab-macos#1376]
**Describe the bug**

I already have the shortcut `⌥→` assigned under system shortcuts. I went to Alt+Tab to set the same shortcut, the app crashes immediately when I press `→`

**Screenshot**

![alt_tab](https://user-images.githubusercontent.com/35638595/153615103-dd288bce-36c7-41a6-aef7-659dda3ded95.JPG)

**Steps to reproduce the bug**

1. Assign any shortcut under `system preferences -> keyboard -> shortcuts`
2. Open Alt+tab preferences
3. Assign the same shortcut at the same field in the above screenshot
4. App will crash

**Comment by ubunatic** [comment]
Same here, I tried to assign `Cmd`+`Up`, which is a bad idea, but it should not crash.
However, I could rebind other existing keyboard shortcuts, i.e., I stole `Cmd+Tab` from the system, which worked fine.

**Steps to reproduce/debug**
Bind different (uncommon) keyboard shortcuts that are assigned globally or through other apps and check which of them cause crashes.

**System**
AltTab Version: 6.31.0
Hardware: M1 Pro
Other Apps: Rectangle.app

**Comment by Abdullah-l** [comment]
@lwouis Not sure if it helps, but here's the [dump](https://gist.github.com/Abdullah-l/9419e93232fb9ccaf226505d07711bfa)
