### ISSUE TITLE
Move alt tab window position down

### ISSUE THREAD

**Issue by weihao** [lwouis/alt-tab-macos#1388]
**Is your feature suggestion related to a problem? Please describe.**

Alt-tab's window is too high that it is not leveled with the user's eye level. The most frequent used app window will be at the top of the screen, like whenever I hit alt tab I have to move my eyes to find the window that I am looking for.

The least frequently used app will first appear on the eye level when the window opens which is a counterintuitive design.

**Describe the solution you'd like**
Be able to start absolute position for alt-tab windows.

**Comment by lwouis** [comment]
It seems you have your screen/chair/desk setup not optimally set up. Ideally your eye level is more like this:

https://www.google.com/search?q=desk+ergonomics+eye+level&rlz=1CDGOYI_enJP928JP928&hl=en-US&prmd=isvn&sxsrf=APq-WBtwCkd46DFT1pqdweU--GM_Do7c1w:1645146664435&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjkxqX0iIj2AhWFD94KHWtlBssQ_AUoAXoECAIQAQ&biw=375&bih=630&dpr=3

Notice how the eye level is at the top of the screen. It means you should not feel tension/uncomfort when looking at the top of the screen, at macOS menubar for example.

That being said, your request already exist in this ticket: #1061

**Comment by weihao** [comment]
thanks for the info, and I think it is more like a force of habit. would be lovely to be able to align the windows in the center.
