### ISSUE TITLE
Focused window highlight contrast

### ISSUE THREAD

**Issue by spankyed** [lwouis/alt-tab-macos#1393]
It's impossible to identify which window you're switching to at a glance, because the highlight color for the focused window is practically the same color of the rest of the UI. This is especially true when you have a dark window in the background. In order to be sure you're switching to the right window, you have to spend a few seconds just identifying which window is currently highlighted. Thats way too long for alt-tabbing.

 Having some better color contrast to make it quicker/easier to identify which window your alt-tabbing to would make this app a lot more useful.

**Comment by lwouis** [comment]
Please see [#1019 ](https://github.com/lwouis/alt-tab-macos/issues/1019)
