### ISSUE TITLE
Still showing Parsec even after closing the Parsec app

### ISSUE THREAD

**Issue by dqbd** [lwouis/alt-tab-macos#1413]
**Describe the bug**

Alt-Tab still shows Parsec even after closing the Parsec app via Cmd-W and/or Close window action from the menubar. 

A similar issue can be found with Discord, described in #1412.

**Screenshots / video**

https://user-images.githubusercontent.com/1443449/156626548-a9883d77-6081-47b6-ab84-83cda8099ae8.mp4

**Steps to reproduce the bug**

1. Launch Parsec
2. Close window via Cmd-W or from the menu bar (Window > Close)
3. Trigger Alt-Tab, where the Parsec window is still seen.

**Comment by lwouis** [comment]
Please see my answer for Discord here: https://github.com/lwouis/alt-tab-macos/issues/1412#issuecomment-1058765751 I believe Parsec is doing the same thing. So the answer is to contact Parsec's makers as well

**Comment by dqbd** [comment]
Can confirm AltTab is working as expected after changing hiding Hidden windows from AltTab

<img width="547" alt="image" src="https://user-images.githubusercontent.com/1443449/195986800-92a73408-eaf0-45d3-b9e3-7a65997620ba.png">
