### ISSUE TITLE
Reset app/ Import/Export config files

### ISSUE THREAD

**Issue by eleftheriakodikas** [lwouis/alt-tab-macos#1421]
Hi, Absolutely love the app, l would like this app to have a reset to default options somewhere in the preference. Also would like to have an option to Export/ Import config files between computers.

Thanks

**Comment by lwouis** [comment]
Reset already has a ticket: #1275 

Portability of preferences is already possible with the built-in tools from macOS. You can use `defaults` to manipulate preferences of any app and thus export import read write etc
