### ISSUE TITLE
Could you add a new feature

### ISSUE THREAD

**Issue by LeidiGa** [lwouis/alt-tab-macos#1432]
It’s an option. When the user presses CMD + m, it will automatically switch the focus to the recently used window.  I think this will be very helpful for people who like to tidy up their desktop with minimization button.Thanks!!😁

**Comment by Abdullah-l** [comment]
I'm a bit confused, doesn't pressing `Option+Tab` (Aka `Alt+Tab`) switch you to the recently used window?

**Comment by steventheworker** [comment]
I think he wants to focus on the top-most recent app (by layer) like Windows / Ubuntu. MacOS keeps the same app focused even if something else was on top so I've been using BetterTouchTool to work around this, but it's not quite the same (using "bring to front window under cursor")

**Comment by LeidiGa** [comment]
> I think he wants to focus on the top-most recent app (by layer) like Windows / Ubuntu. MacOS keeps the same app focused even if something else was on top so I've been using BetterTouchTool to work around this, but it's not quite the same (using "bring to front window under cursor")

This is also a problem. I mean, if I have a Safari window and a Chrome window on MacOS. Then I minimize the Safari Window, the system focus will not automatically switch to the Chrome window like Windows / Ubuntu. You must click the mouse more on the Chrome window. I'm trying to find a solution to this problem.

**Comment by Abdullah-l** [comment]
I'm not sure I follow. I just opened a Safari and Chrome window, minimized the Safari window then pressed `Option+Tab` and it brought me back to Safari. Isn't that the expected behaviour?

**Comment by LeidiGa** [comment]
> I'm not sure I follow. I just opened a Safari and Chrome window, minimized the Safari window then pressed `Option+Tab` and it brought me back to Safari. Isn't that the expected behaviour?

But why didn't it bring me back to Safari🤣. When I minimized the Safari window, the focus displayed in the upper left corner of the screen still be Safari. So If I press Option+Tab, it will just bring the system focus to Chrome (which I recently used ).

**Comment by lwouis** [comment]
It seems this ticket is about how macOS behaves, not AltTab. Unless i misunderstood the (quite confusing) conversation, AltTab is working as it should.
