### ISSUE TITLE
Mouse wheel applications switch

### ISSUE THREAD

**Issue by erosval** [lwouis/alt-tab-macos#1435]
Ability to "rotate" between applications of the same type using the mouse wheel on the menu bar icons (as in Ubuntu).

**Comment by Abdullah-l** [comment]
Is [this](https://youtu.be/ZzGzC5APDU8?t=89) what you're referring to by rotating between applications of the same type?

If so, it was discussed in issue #337

**Comment by lwouis** [comment]
Closing as author stopped showing interest
