### ISSUE TITLE
The cursor position

### ISSUE THREAD

**Issue by liyuze** [lwouis/alt-tab-macos#1443]
When I switch apps, the position of the mouse moves automatically, I need to slide the mouse to know where it is, and I want a function to turn it off.

**Comment by Abdullah-l** [comment]
When I switch apps, the mouse position remains unchanged. Can you perhaps provide a video of the issue?

**Comment by lwouis** [comment]
There is a preference for this. You probably checked the box and forgot you did? Go to the Preferences to uncheck and disable the mouse jumping to the focused window
