### ISSUE TITLE
Bug with latetest opened tab in macos 12.1

### ISSUE THREAD

**Issue by alexisvisco** [lwouis/alt-tab-macos#1450]
**Describe the bug**

I use the feature called grouped tab and it seems like the latest tabs used isn't the one displayed

**Screenshots / video**

https://youtu.be/JzUGfm_TMdk

**Steps to reproduce the bug**

1. Go to an app with multiple tabs group
2. Click on one of this tab
3. Switch to another tab
4. Alt tab -> you will see the group tab if it's not the last one opened it's the error
5. else alt tab on the group tab, go to the other group tab and go to step 3

**Comment by lwouis** [comment]
There is no API to deal with tabs. AltTab uses elaborate workarounds based on private APIs and system side effects to try and guess the state of tabs. Until Apple provides actual APIs it's a best effort situation

**Comment by lwouis** [comment]
Also in the video you show Intellij, which uses custom tabs I believe, so these we have no chance on displaying in AltTab. They are coded with custom UI code, like custom pixels. The OS has no idea these are tabs
