### ISSUE TITLE
Having more than two shortcuts

### ISSUE THREAD

**Issue by daniel-zeng** [lwouis/alt-tab-macos#1458]
Hello,

Currently, it seems that there's only two customizable shortcuts, and I've searched the Github issues but I don't seem to find anything to add additional shortcuts. 

Specifically, I wanted to have a way to have different types of release behavior, but using the two shortcuts for ("All Apps" and "Active App") for "Focus selected" takes up these two slots and I also wanted similar for the other option as well.

Thank you!

**Comment by PrayagS** [comment]
+1 on this.

**Comment by GJRobert** [comment]
I have also suggested in #1064

**Comment by lwouis** [comment]
Closing as duplicate of #1064
