### ISSUE TITLE
How to use CMD + TAB instead of ALT + TAB

### ISSUE THREAD

**Issue by Delice0** [lwouis/alt-tab-macos#1459]
I like how this program shows all instances of an application but I do not like the shortcut to activate alt-tab.

I want it mapped to CMD + TAP instead.

How do I do that?

**Comment by tonykhaov** [comment]
Hey you just need to go to AltTab preferences > Controls > click on Hold and press `cmd` key
![image](https://user-images.githubusercontent.com/53958746/161106403-20eb0c05-cfa5-4ea4-acc1-f6927b441fde.png)

**Comment by lwouis** [comment]
Thanks @tonykhaov

**Comment by Delice0** [comment]
Thanks it worked @tonykhaov !
