### ISSUE TITLE
From alt-tab preview, allow to pull a window from a different space onto the current one

### ISSUE THREAD

**Issue by rc9000** [lwouis/alt-tab-macos#1460]
**Is your feature suggestion related to a problem? Please describe.**
No, just a quality-of-life improvement

**Describe the solution you'd like**
I'm using multiple spaces. Let's say I'm doing something on space 3, but suddenly this requires to fetch my mail client from space 1. Could alt-tab have an option to instead of switching to the space with the mail client, allow me to pull onto the current space?

I am a developer but I have very little OS X native GUI experience. I would be willing to put in the work, if somebody here can just tell me if this should be possible, and maybe some pointers what APIs I should be using for this.

**Describe alternatives you've considered**

 * not great: click mail client in alt-tab, switch to that space, drag the window to the space I wanted it on, completely lose focus what I was about to do
 * not great: right-click mail client in dock, pick "options: show on all desktops" to get it onto my space, same again for "options: show on None" because I don't want it on all really, just on the current one 
 * hyperdock: can't do this either AFAICT

Thanks guys!

**Comment by lwouis** [comment]
Technically doable. We could add the preference to the existing dropdown of actions to take once the shortcut is released

we already "teleport" all windows to the current space on launch, in order to get their references. It's using a private API which is the only way to do it. It works though. You could probably very easily implement this

**Comment by rc9000** [comment]
Thanks for the quick reply, it looks like I have some reading in the code to do. Cheers!

**Comment by rc9000** [comment]
For future readers: in the meantime I have made a [similar functionality in an Applescript workflow](https://github.com/rc9000/pull_application_to_current_desktop_macos) that can be added in the system-wide Services menu, giving you a hotkey that essentially does what I describe in the original post. Maybe one day I will still get around to try and hack this into AltTab.
