### ISSUE TITLE
File copy progress windows are not picked up

### ISSUE THREAD

**Issue by adarshvadwitiya** [lwouis/alt-tab-macos#1466]
**Describe the bug**

AltTab doesn't pick up file copy progress windows

**Screenshots**
This is what my preferences look like:
![SCR-20220405-na7](https://user-images.githubusercontent.com/30106062/161742473-0480abd5-74fc-4a02-9db1-b80b13e7e61c.png)

![SCR-20220405-naf](https://user-images.githubusercontent.com/30106062/161742474-f94f2242-d41e-464b-9e20-a84063b4a3e3.png)

**Steps to reproduce the bug**

1. Have a file copy progress window open
2. Click CMD+Tab
3. All other windows show up except the file copy progress window

**Comment by lwouis** [comment]
Are these really windows though? AltTab has to filter out things like dialogs and HUDs. It may be that Finder declares those as such and not as windows, in which case AltTab would rightfully filter them out.

Someone should check how they are declared at the technical level

**Comment by joostin81** [comment]
I believe HyperSwitch shows file copy progress windows but not dialogs/HUDs

**Comment by lwouis** [comment]
Anyone knows a trick to spawn such window and have it stay for a little while? My SSD is really fast, and most file copies don't spawn a window, or very briefly.

**Comment by adarshvadwitiya** [comment]
Not sure if they’ll help but you can create large dummy files using `mkfile <size>G your-file-name`. So if you move that to an external drive, the window should stick around for a while

**Comment by XInTheDark** [comment]
> My SSD is really fast, and most file copies don't spawn a window, or very briefly.

What SSD do you use? I wanna get one 😂

**Comment by lwouis** [comment]
The issue I think is that on macOS file-system, moving or even copying a large file is just creating/moving a file descriptor. So it's instant. I was able to get a Finder copy window by copying a folder with lots of subfolders (this repo actually).

So the issue is that the Finder copy window doesn't pass the height > 100px check. On my system, in my language (English), its height is 69px.

I'm not sure how to deal with this situation. I explored the heuristic in https://github.com/lwouis/alt-tab-macos/issues/456 in the past. Here is an example of an app for which we need to filter out windows smaller than 100px: https://github.com/lwouis/alt-tab-macos/issues/562.

What I could do is add a whitelist for Finder: if it's Finder, we show windows regardless of their size. However it doesn't seem ideal as other apps could have legitimate small windows. Yet other apps have small non-windows.

What to do?

**Comment by XInTheDark** [comment]
> What I could do is add a whitelist for Finder: if it's Finder, we show windows regardless of their size. However it doesn't seem ideal as other apps could have legitimate small windows. Yet other apps have small non-windows.

Adding a whitelist for Finder would be great.

I don't really understand why there needs to be a height filter, though; does it serve any real purpose in use?

**Comment by adarshvadwitiya** [comment]
> The issue I think is that on macOS file-system, moving or even copying a large file is just creating/moving a file descriptor. So it's instant. I was able to get a Finder copy window by copying a folder with lots of subfolders (this repo actually).
> 
> 
> 
> So the issue is that the Finder copy window doesn't pass the height > 100px check. On my system, in my language (English), its height is 69px.
> 
> 
> 
> I'm not sure how to deal with this situation. I explored the heuristic in https://github.com/lwouis/alt-tab-macos/issues/456 in the past. Here is an example of an app for which we need to filter out windows smaller than 100px: https://github.com/lwouis/alt-tab-macos/issues/562.
> 
> 
> 
> What I could do is add a whitelist for Finder: if it's Finder, we show windows regardless of their size. However it doesn't seem ideal as other apps could have legitimate small windows. Yet other apps have small non-windows.
> 
> 
> 
> What to do?

A white list seems like the way to go because progress windows appear not just for cut, copy & paste but for archiving & unarchiving, file upload & download etc.

**Comment by lwouis** [comment]
> I don't really understand why there needs to be a height filter, though; does it serve any real purpose in use?

I just gave an example above 😅

> Here is an example of an app for which we need to filter out windows smaller than 100px: https://github.com/lwouis/alt-tab-macos/issues/562.

**Comment by lwouis** [comment]
> A white list seems like the way to go because small (<100px) progress windows appear not just for cut, copy & paste but for archiving & unarchiving, file upload & download etc.

I'm thinking maybe i could whitelist all apps from Apple (i.e. `bundleId` starts with `com.apple`). But that may actually be too much. Apple sometimes doesn't respect its own standard/tech. Maybe Finder is enough?

I could also reverse the approach: let any app show small windows, and as users complain (e.g. intellij), i either redirect these users to these apps customer support, or i add a blacklist to prevent specific windows to show for specific apps.

Actually i think i'll do that

**Comment by lwouis** [comment]
I have a commit which fixes this issue. I'm waiting for other changes to bundle those into a release.
