### ISSUE TITLE
Start at login not working

### ISSUE THREAD

**Issue by akfroman** [lwouis/alt-tab-macos#1470]
I have the "Start at login" check box enabled, but every time I restart or log off then then back in, Alt-tab will not start unless I manually start it.

**Comment by lwouis** [comment]
Here is some info on how this checkbox is implemented: https://github.com/lwouis/alt-tab-macos/issues/1398#issuecomment-1078458456

it you have technical skills, could you investigate on your system? Like is the launchagent file present, what does it contain? If it's there with the right content then why is your OS not taking it into account?

It could be that you have some corporate security policies on your computer blocking custom launchagent, or something like that
