### ISSUE TITLE
thumbnail is missing for VSCode window

### ISSUE THREAD

**Issue by GorvGoyl** [lwouis/alt-tab-macos#1472]
as seen in the screenshot, vscode ide is open but the thumbnail is missing from altTab preview

<img width="888" alt="screenshot 2022-04-07 at 22 17 51@2x" src="https://user-images.githubusercontent.com/7106086/162255445-66f63743-f06c-46c7-a23f-e8c18fbae5ca.png">

**Comment by lwouis** [comment]
Should be fixed in v6.32.0
