### ISSUE TITLE
Activating AltTab makes Finder open dialogue very slow!

### ISSUE THREAD

**Issue by thewhitewayofdelight** [lwouis/alt-tab-macos#1486]
**Describe the bug**
When the AltTab is active in the background, opening Finder pop up (such as 'save as' or 'open') is very slow!
It should perform the same when AltTab is active and not.

My configurations
![image](https://user-images.githubusercontent.com/87333145/162618152-21b0b031-7f16-4cbb-a913-bee226e52047.png)

**Screenshots / video**
https://user-images.githubusercontent.com/87333145/162618327-a85643ba-a306-4a53-9171-4377ee958206.mov

**Steps to reproduce the bug**

1. Activate the AltTab
2. Open text editor, then save it. 
3. Notice that it takes a long time to open the finder pop up
4. Compare it when AltTab is not active

Tested on Apple Silicon

**Comment by Abdullah-l** [comment]
I switched from Windows to Mac OSX several months ago and always wondered why saving/opening files was slow. I had absolutely no idea this could be caused by Alt+tab!

Thanks for sharing @thewhitewayofdelight!

@lwouis any idea on what could cause such issue?

**Comment by thewhitewayofdelight** [comment]
It cost me reinstalling my macbook just to find out this issue because I really hate it 😂 
Hope this issue could be fixed.

**Comment by lwouis** [comment]
Please see https://github.com/lwouis/alt-tab-macos/issues/718#issuecomment-927108121 and the following few posts. Everything is explained. The last comment is someone saying Apple fixed it on macOS 12.3.1. Maybe you could update your macOS to fix the issue?

**Comment by thewhitewayofdelight** [comment]
I just updated my mac and can confirm that the issue has gone 👍 
Thank you
