### ISSUE TITLE
Considering switching for real from hyperswitch, but one annoyance. 

### ISSUE THREAD

**Issue by momomo** [lwouis/alt-tab-macos#1500]
I think this is very promising indeed! Hyperswitch is alright but I was annoyed that you could not resize the stuff shown. 

With AltTab the only annoyance is no **clear** **border** between apps shown. 

I think a border or background per listing, customizable of course could greatly help the astetics. 

This does not look too good, also not clear where one app starts and ends, look at the mail icons: 

![image](https://user-images.githubusercontent.com/9274346/163731515-af62a156-0e8b-4408-9558-98dd1499b1b3.png)

Look at the Music app ..  too much gray from upper one? 

However, I think that if you **add** a **border** with **padding** similar to one that is shown when **hovered**, then we are gold :) 

**Also, quite annoying that I can not select **main display** to show the switcher on** 

![image](https://user-images.githubusercontent.com/9274346/163731637-7f1fcf40-a643-4497-baad-4a0764adb7c9.png)

I have five displays, I can not keep guessing where it is, consistency can be good. Right now it is jumping around where my eyes may not not necessarily be where my mouse is. 

Also, **hidden** or **minimized windows** need to be shown clearly that they are currently impossible for me to distinguish, and likely there is some icon there, but it should not require someone explaining anything. **Just fade it**. 

**Ok, so in the span of testing for 5 minutes I have 3 complains or suggestions.** These could to me be essential for being able to actually use this or dismiss it and go back to hyperswitch. The jumping around is currently the biggest issue.

**Comment by momomo** [comment]
I noticed another thing. I kind of like the feature 

![image](https://user-images.githubusercontent.com/9274346/163731829-b15eddb8-62c9-4680-9b5e-469d73ea108b.png)

But not all the time. So by default off of course. 

But perhaps adding a shortcut to make it sticky so one can release the keys, say by **dot**. 

Could be added here: 

![image](https://user-images.githubusercontent.com/9274346/163731854-6d88ff78-a00d-4c29-8044-1dd874df33aa.png)


Other than that this is looking promising! Great job autist!

**Comment by momomo** [comment]
Also if you look at the music app, and the one above it, they could be aligned center in their own box only. 

Center vertical, center horizontal, and with a background or border around it will look alright!

Currently only center or left option is available and when enabled the entire Music app will go center of the entire row. 

So left for me, but center&center within the box. 

Good night!

**Comment by lwouis** [comment]
> Great job autists!

Did I read this right? You came on this online social forum, where you know no-one, and called people here autists?

**Comment by momomo** [comment]
Of all the things I wrote this is what gets your attention? Not other comments on the other things I mentioned? 

Really, it is a compliment for the desire to do better than other options out there. While you might consider the word autist offensive, there are others who don't, and consider being an autist special. Elon Musk is likely an autist. Ein stein likely was too. 

Maybe the word awesome triggers you too?

Most "normal" people would say hyperswitch is good enough since really, the only area this actually differs from it is the size of the thumbnails.  A true autist would look at this shortcoming and spend enough time to rewrite it completely just to get this one additional feature. 

Hyperswitch to me is free. It nags me about expiring but nothing really happens when you click check for update. I can continue to use it just fine. 

 What makes you associate the word autist with something bad that offends you? That's on you, not me.
So don't be offended. If you are offended by the word autist it is likely only because you personally consider being an autist something bad. 

Regardless, I apologize if the word came at you in a negative way. It was meant as a funny remark and compliment.

**Comment by lwouis** [comment]
@momomo i advise you to not call stranger autists. In the world i live in, it is not socially acceptable. Now that being said, you have explained that your intentions were not to insult, so no harm done i guess.

Now to answer your ideas about features, most of those suggestions already exist in tickets. You can find them with a few keywords, so i'll close this ticket as duplicate.

Also please note that i don't have much time anymore for this project: https://github.com/lwouis/alt-tab-macos/issues/1179
