### ISSUE TITLE
(option to) draw icon on top of the window preview

### ISSUE THREAD

**Issue by singalen** [lwouis/alt-tab-macos#1507]
**Is your feature suggestion related to a problem? Please describe.**
My window previews in the switcher are tiny. The 64px icon and window title take half the space (b/c the former is tall and the latter is wide).
![Screen Shot 2022-04-20 at 10 14 40 AM](https://user-images.githubusercontent.com/151199/164287468-60bc22e0-ae8e-4b90-9b98-1fc500f8a02b.png)

**Describe the solution you'd like**
Window icon could be drawn on top of the preview, [like HyperSwitch does](https://bahoom.com/images/hyperswitch_1_777.png). We don't need to see the entire preview in order to distinguish windows from each other.

For those disturbed by this change, this could be optional.

**Describe alternatives you've considered**
I could decrease the icon size, this would work. But I like the look of app icons, so I prefer them big.

**Comment by lwouis** [comment]
It's a nice idea, but I'm afraid it's too niche at the moment. I'll close the ticket for now.

I hope you understand I have to balance people's requests with the app complexity 🙇
