### ISSUE TITLE
Prevent automatically cycling through windows in reverse (shortcut with Shift)

### ISSUE THREAD

**Issue by ourcore** [lwouis/alt-tab-macos#1528]
**Is your feature suggestion related to a problem? Please describe.**
I often want to browse through windows in reverse (Cmd + Tab + Shift in my case) and with AltTab, the focus automatically cycles through the windows back to the first one and pressing Tab again creates a weird jump.

**Describe the solution you'd like**
I'd prefer the reverse shortcut to cycle one window at a tab (just like in the regular/forwards method, and in Windows). Pressing Tab should focus to the previous window manually.

**Describe alternatives you've considered**
Switching focus with the left and right arrow keys for better control, but I'm already used to using Shift.

**Comment by lwouis** [comment]
I don't understand. The reverse shortcut exists, and it cycle backwards 1 thumbnail at a time.

What would you like to be different?

**Comment by ourcore** [comment]
I noticed that it cycles one at a time if you only press Cmd/Option + Shift, but not if you press Cmd/Option + Tab + Shift, like I did previously on macOS and Windows. Adding Tab cycles to the very front.

**Comment by adelwin** [comment]
Ah, I noticed this too, I almost thought my keyboard was messing up.

If I press and hold Cmd, then start pressing Tab, it works like a charm,
But sometimes I pressed Tab 1 too many times, so I want to go back by one,
I would presume to now press Shift and press Tab once, this would cycle one step back,
And hopefully will land in the previous window.
But I noticed it moves automatically and it messes with my head.

Haha

**Comment by lwouis** [comment]
Ah ok i get your situation.

AltTab uses only shift to back-cycle. Not shift+tab. The reasoning is: look at your left hand when you hold alt+shift+tab; clearly it's not ergonomic/accessible. So AltTab got inspiration from HyperSwitch and uses only shift to trigger.

i understand people coming from another switcher may expect shift+tab. I sacrificed compatibility for accessibility.

that being said, you can easily go in the preferences and change shift to shift+tab and you'll have the experience you're used to
