### ISSUE TITLE
Force Quit as keyboard command

### ISSUE THREAD

**Issue by Fenevadka** [lwouis/alt-tab-macos#1529]
For many years I used Liteswitch X (sadly now abandoned and no longer operational in recent versions of OS X) and one of its most handy features was that users could hit F twice while an item was highlighted to perform a force quit (rather than having to type option-command-esc and then use the mouse to select the app to force quit).

Even after not being able to use Liteswitch X for years, I still find that my muscle memory does this to no avail when an app hangs.

Would it be possible to add equivalent functionality to this application?

**Comment by lwouis** [comment]
It's a very good idea. We already have Q to quit (default, can be customized to something else). We could make it so that a second Q within a delay of let's say 250ms would send a force quit instead of a normal quit.

I wonder if the built-in macOS app switcher has such capability?

**Comment by lwouis** [comment]
> I wonder if the built-in macOS app switcher has such capability?

I tried, and I think it doesn't. However, I discovered a funny trick: if you press `shift`, it will do actions without closing the switcher. For instance you can `shift+q` to quit multiple apps in a row.

**Comment by lwouis** [comment]
[This project](https://github.com/jksoegaard/NonResponding) showcases usage of private API `CGSEventIsAppUnresponsive`. This would let us flag apps as "Non responsive", like Activity Monitor does.

So we could send normal-quits, until we notice the app is "unresponsive", at which point we would probably have some UI to show that on each of its window. Then we could send force-quits.

However, that's not very friendly to power-users. They may want to force-quit when they want to, regardless of the app being unresponsive of not.

I think my preferred UX, amongst all the alternatives so far, is to send force-quit on a second or third press/click. I think a user that's clicking/pressing multiple times is giving intent to wanting the app gone. I think we don't need a special timing like double-click or double-press within a certain time-window. I think simply a second trigger should force-quit. An exception would be if AltTab UI is dismissed; that should reset the counter.

**Comment by Jack-Bristow** [comment]
> However, that's not very friendly to power-users. They may want to force-quit when they want to, regardless of the app being unresponsive of not.

If you're trying to cater to power-users, would it not just be easier to introduce another hotkey that force-quits? Something along the lines of default press 'X' while open to issue force-quit command.
