### ISSUE TITLE
Some apps shows as assigned to all desktop

### ISSUE THREAD

**Issue by Canis1Majoris** [lwouis/alt-tab-macos#1536]
Hi there! Have same issue as https://github.com/lwouis/alt-tab-macos/issues/1310#issuecomment-1115215548_ with bunch of apps including Telegram for MacOS v8.7

AltTab version 6.34.1
MacOS 12.3.1 (Intel)

![image](https://user-images.githubusercontent.com/79000976/166302958-3a2af19a-76d4-4305-aa82-9fd6b6556791.png)

_Originally posted by @Canis1Majoris in https://github.com/lwouis/alt-tab-macos/issues/1310#issuecomment-1115215548_

**Comment by Canis1Majoris** [comment]
Looks like re-openening app helps. But after sleep safari windows started behave same as Telegram. Re opening helped.
Very strange though.

**Comment by lwouis** [comment]
You're on 12.3.1 so could be #1324?

Could you please clarify what the issue is on your screenshot, and the steps that led to that state?
