### ISSUE TITLE
Auto-resize thumbnails based on row max width?

### ISSUE THREAD

**Issue by neilio** [lwouis/alt-tab-macos#1539]
**Is your feature suggestion related to a problem? Please describe.**
I'm trying to replicate how [Hyperswitch](https://bahoom.com/hyperswitch) works, where you have a set max width for the row and the thumbnails scale down to fit all of the open windows in that single row. I don't see any way to do this currently. The goal here is to show all open windows without requiring multiple rows.

**Comment by lwouis** [comment]
You can set `Rows of thumbnails` in the preferences:

<img width="686" alt="image" src="https://user-images.githubusercontent.com/106195/166508375-3aa9f24e-1cb0-4bb5-bb01-a8fc3feb0744.png">
