### ISSUE TITLE
Commander One holds zombie Copy / Move window after operation is done

### ISSUE THREAD

**Issue by lukasszz** [lwouis/alt-tab-macos#1550]
**Describe the bug**
When you copy/move files using Commander One then in the switcher you can see as many progress windows (after compliting operation) as many files you've copied.

It happens only if you turn the option "Show cards as windows". (Btw. what is this option for?)

**Screenshots / video**
How to make screenshot when switcher is opened?

**Steps to reproduce the bug**

1. Open Commander One
2. Copy/Move file from left to right pane
3. Open Alt+Tab 
4. The Copy windows with progress i shown in the switcher

**Comment by lwouis** [comment]
I was able to reproduce the issue. Looking at the logs, it seems that CommanderOne doesn't send an event when the windows are closed. They send the event when they are created, so AltTab lists them. But then it doesn't close/destroy them, so they remain.

It looks like an issue on CommanderOne side. Maybe they hide the windows but keep them in memory to reuse them later? Not sure but it breaks understanding of their app by accessibility apps like AltTab, so they should fix it.

They are a commercial app, so please contact their customer service. Feel free to link to this ticket for documentation.

> It happens only if you turn the option "Show cards as windows". (Btw. what is this option for?)

Do you mean "Show standard tabs as windows"? If yes, then here is what the preference does: if checked, a single window (e.g. a Finder window) with multiple tabs, will show in AltTab as multiple thumbnails/windows that you can navigate to. If unchecked, then you will see only one thumbnail/window in AltTab, which is the tab that's visible/active on the window. It only works with standard tabs, not custom tabs (e.g. Chrome tabs are fully custom, not standard).
