### ISSUE TITLE
Drag and Drop from Finder into "Open Document" window

### ISSUE THREAD

**Issue by hako0711** [lwouis/alt-tab-macos#1555]
**Describe the bug**

First of all, thank you for this great app. It really makes things so much easier. 

I have found some behaviour that is not like the macOS standard behaviour and it's about how AltTab handles "active" application windows. I don't know if many people are using this type of "handling" - when I first found out about this, my mind was blown a little bit and since then, I use it all the time. 
So here's the "trick": When you have an "save as" or "open" window open and you have a Finder window open with the file or the folder you want to navigate, you can simply drag and drop the file or the folder to the "save as" or "open" window. macOS then grabs that location or file easily and you don't have to navigate through you folders etc.     

But with AltTab this behaviour is not there anymore. I think there's a problem with detecting the "active" window when switching between the apps? 

I've added a video where I use Cmd+Tab in the first part and AltTab in the second part. 
I've also tested different Apps, so that's not an TextEdit issue.    

**Screenshots / video**

(https://mkcloud.bazlen.com/index.php/s/zBhvR2XOxG7YVhK)

**Steps to reproduce the bug**

1. Go to 'TextEdit'
2. Click on 'Open File'
3. Switch to 'Finder' and drag a file. Then switch with AltTab back to 'TextEdit" and drop the file on the "open file" window.

**Comment by lwouis** [comment]
Hi,

In your video, I can see that it seems to work fine, but you dropped the file too much to the left, so it didn't work.

At around 0:35 in the video, you hover like this, and it looks great:

![image](https://user-images.githubusercontent.com/106195/167593200-a43f82ed-1215-4beb-9d3e-c23d0f2e8a4f.png)

But then you move to the right, and drop the file here:

![image](https://user-images.githubusercontent.com/106195/167593236-56705e31-d9e3-4494-b8a5-3871882d702c.png)

Do you see how the red outline is gone, indicating that you're not on a drop area?

I tried on my machine, and I can do the workflow you mention without any issue. I AltTab to TextEdit, and I can drop the file in the Open Window without any issue.

Closing this ticket. Let me know if you still have the issue

**Comment by hako0711** [comment]
Do you see how the red outline is gone, indicating that you're not on a drop area?

- If you move the file to the red outline area, the file is copied to the location - the location is not selected like it should be. 
- Also when I'm using CMD+TAB I can drop the file almost anywhere in the Open File window.
- Could you please check this again, if the file is also copied, when you drop it on the outline area? 

Thank you.

**Comment by lwouis** [comment]
I tried to drag the file on the right like in your video and it works. It selects the file properly

**Comment by decodism** [comment]
@hako0711 As a workaround, press the option key again after switching.

**Comment by lwouis** [comment]
@decodism do you also have this issue?

I just tried to set AltTab to `command+tab` or `option+tab` (the default, and I imagine what @hako0711 is using?). In both cases, I could release `tab`, and without releasing the modifier key held, I could drop the file onto the open window, anywhere on the window, even without any colored outline, and it works.

**Comment by decodism** [comment]
@lwouis Yes, I can reproduce this issue. It seems that the system does not register correctly that the option key has been released. If I use the space key to go to the window and release the option key afterwards, or if I release the option key to go to the window and use (briefly) the option key afterwards, the issue does not occur to me.

**Comment by hako0711** [comment]
@lwouis Yes, I'm using command+tab to replace the macOS App Switcher with AltTab. I'm on 12.3.1 - if that's a useful information. 

I noticed, that holding the ctrl key, while or before dragging the file on the window it does the trick. Also if I use the cmd key again before dropping the file like @decodism mentioned.

**Comment by lwouis** [comment]
I tried again with a variety of shortcuts and windows, and it always works correctly for me. I'm not sure what's different on your machines.

Do you have an external keyboard, don't use English, use other apps that interfere with keyboard events like BTT, Alfred, etc?

Could also be that you're both on 12.3+ and there is an OS regression there. There is already a confirmed broken private API there: #1324

**Comment by hako0711** [comment]
> Do you have an external keyboard, don't use English, use other apps that interfere with keyboard events like BTT, Alfred, etc?

Yes, I'm using an wired external Keyboard from Apple. I also use BTT and German as my keyboard layout. 
With BTT off and language switched to English and US, unfortunately the issue is still there.
