### ISSUE TITLE
After it runs for some time (~1 day) using the mouse pointer to hover over thumbnails lags

### ISSUE THREAD

**Issue by mfn** [lwouis/alt-tab-macos#1567]
AltTab: 6.36.1
OSX: 10.15.7

**Describe the bug**

I open AltTab with CMD-Tab and see ~20+ window and use the mouse to select the window I want.

Seems that after some time (roughly 1 day, including hybernation+wakeup) the focus (white border) following the mouse when hovering over the windows has a noticeable lag, something like multiple hundred of milliseconds it must be.

What then happens is that visually the mouse is already over my chosen destination window and I click LMB but then, due to this lag, another window I previously hovered over, is activated.

- When I restart AltTab, the lag is gone
- when it's fast and I sleep/wake-up the system, it's working normally (so it's not directly connected to that; it just happens that usually I noticed it in the morning)

**Screenshots / video**

https://user-images.githubusercontent.com/87493/168005763-51a89659-9ab0-4fa6-a4c9-a43909127e11.mov

Note: for the cast I made artificial terminal windows of the same app because it was a quick way to give me private and not show the work related stuff, which is comprised of different IDEs, browsers and such, but the behaviour independent of that.

**Comment by lwouis** [comment]
Thank you for reporting this issue @mfn

Could you please share a `spindump` and a `Sample Process` through Activity Monitor? You can click on AltTab there, then the buttons are here:

![image](https://user-images.githubusercontent.com/106195/168028555-1a72bba2-54c3-4d49-88d8-799b2a3ff632.png)

That may give us a hint on what AltTab is spending CPU cycles on, slowing it down.

**Comment by mfn** [comment]
Ok, thank you: attached!

[Sample of AltTab.txt.zip](https://github.com/lwouis/alt-tab-macos/files/8677293/Sample.of.AltTab.txt.zip)
[Alt Tab Spindump.txt.zip](https://github.com/lwouis/alt-tab-macos/files/8677294/Alt.Tab.Spindump.txt.zip)

**Comment by mfn** [comment]
> I've already made the app concurrent, and most things are handled off the main thread, in background threads 

If I say "but it must be connected to the internal state of AltTab" based on the observation that "when I restart AltTab, the latency is gone":

Would that give you any ideas? 🤔

Just throwing thoughts around, I'll try to closer observe this and try to figure out if sleep/wakeup is even relevant, maybe it isn't.

Thank you!

**Comment by lwouis** [comment]
> but it must be connected to the internal state of AltTab 

Indeed, it seems correct to assume that.

In the reports you shared, we see AltTab at around 80MB. This indicates that AltTab doesn't have memory leaks or zombie objects.

Furthermore, like I said, the behavior looks like the main thread is stalled and thus can't draw at fast enough.

This would seem to indicate that the main thread is spending cycles on some heavy computation. However your sample report shows that all the cycles are spent waiting for events, aka the app is idle as it should be:

```
    2438 Thread_1225508   DispatchQueue_1: com.apple.main-thread  (serial)
    + 2438 start  (in libdyld.dylib) + 1  [0x7fff677a2cc9]
    +   2438 main  (in AltTab) + 62  [0x1028eb42e]
    +     2438 -[NSApplication run]  (in AppKit) + 658  [0x7fff2ad9ebae]
    +       2438 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]  (in AppKit) + 1352  [0x7fff2adacea0]
    +         2438 _DPSNextEvent  (in AppKit) + 883  [0x7fff2adae659]
    +           2438 _BlockUntilNextEventMatchingListInModeWithFilter  (in HIToolbox) + 64  [0x7fff2c765569]
    +             2433 ReceiveNextEventCommon  (in HIToolbox) + 584  [0x7fff2c7657c5]
    +             ! 2431 RunCurrentEventLoopInMode  (in HIToolbox) + 292  [0x7fff2c765aad]
    +             ! : 2431 CFRunLoopRunSpecific  (in CoreFoundation) + 462  [0x7fff2db3976e]
    +             ! :   2299 __CFRunLoopRun  (in CoreFoundation) + 1319  [0x7fff2db3a2f2]
    +             ! :   | 2299 __CFRunLoopServiceMachPort  (in CoreFoundation) + 247  [0x7fff2db3b825]
    +             ! :   |   2299 mach_msg  (in libsystem_kernel.dylib) + 60  [0x7fff678e4170]
    +             ! :   |     2299 mach_msg_trap  (in libsystem_kernel.dylib) + 10  [0x7fff678e3dfa]
```

The only other thing I can imagine is that in the very few other cycles spent elsewhere, on the main thread, there is a blocking call. Like some draw call we send to AppKit is taking abnormally long for some reason. I think blocking calls are not visible on such reports. But I can't see which call that would be.

This stuff is a nightmare to debug. I've had similar issues in previous year, and no instrumenting tool shows blocking calls nicely, and furthermore, if you want to know why AppKit is not drawing your app UI fast enough, it's also rough due to the lack of tools.

**Comment by lwouis** [comment]
> moved the mouse continuously

Wow I was able to reproduce!

I wonder if this is a new regression. I worked on this recently: https://github.com/lwouis/alt-tab-macos/issues/1565#issuecomment-1123990646

I also just fixed https://github.com/lwouis/alt-tab-macos/issues/1557 and it's about mouse hover, so maybe involved?

I'll try and debug. If you can, it would be really useful if you could try previous versions of AltTab until you find one where the issue didn't exist yet. Locating the version that introduced the issue would narrow down the bug to a few lines most likely

**Comment by mfn** [comment]
> This stuff is a nightmare to debug

😬

Maybe this is also relevant: I've a "three monitor" system: two external full hd displays and the laptop display itself, on a MacBook Pro (16-inch, 2019)

I opened this issue because I never before experienced it or at least not _that_ noticeable.

Maybe it was a recent update: I'll therefore go back in time and try out older releases, since it seems I can reproduce this with quite minimal effort for me.

Stay tuned 🤞🏼

**Comment by mfn** [comment]
> Stay tuned 🤞🏼

v6.35.0 - good
v6.36.0 - bad

**Comment by lwouis** [comment]
I found the root cause, and I'll release a fix very soon. Smooth 60FPS mouse hover will be back 🎉 

Thanks a lot Markus for spotting the issue and helping me debug it and come up with a fix!

**Comment by mfn** [comment]
Oh wow, works great! 🙏🏼

**Comment by devnoname120** [comment]
Can confirm it solved my issues.
