### ISSUE TITLE
Notion is not listed when I use AltTab

### ISSUE THREAD

**Issue by ifsheldon** [lwouis/alt-tab-macos#1570]
**Describe the bug**
(I'm not sure if it's a bug. I searched the issue list and found no one has report this) When I am running notion with a window or without a window, AltTab does not give me a preview of the window or blank preview. I don't know if this is an app-specific problem because every app works well with AltTab so far except Notion.

**Screenshots / video**

Add screenshots to help explain your problem. You can also use Loom to easily record your screen to show the bug in action. That is *really* helpful!

<img width="1171" alt="image" src="https://user-images.githubusercontent.com/39153080/168128459-e8a76b14-5c85-4ae8-b1d9-6dc78c1ce2f9.png">
<img width="1122" alt="image" src="https://user-images.githubusercontent.com/39153080/168128503-2ee6b308-6a17-4338-aca0-40338e596573.png">

**Steps to reproduce the bug**
1. Run Notion and open a window of it
2. Use AltTab

Env:
* M1 Macbook Pro
* Apple-silicon Notion
* macOS 12.4 Beta

If anyone can reproduce this problem with a stable macOS on M1 Mac, it will be great.

**Comment by lwouis** [comment]
I downloaded Notion, created an account, open 2 windows: everything is shown properly in AltTab.

It seems like it could be either linked to their Apple Silicon app, or the fact that you're on the macOS beta.

Could you please contact Notion customer support about this issue? It's probably on their side to fix.

**Comment by lwouis** [comment]
@ifsheldon actually in your Dock you have the following open apps, which don't show anything in AltTab:

* Notion
* WeChat
* Skype
* Slack

Can you try these 2 approaches to see what happens?

* Having AltTab open **then** opening these apps
* Opening these apps **then** opening AltTab

AltTab uses very different mechanisms in the 2 cases. I'm curious if Apple broke a private API or something in macOS 12.4 Beta. They already broke one important one from the 12.2 beta onward (#1324)

**Comment by ifsheldon** [comment]
After macOS was auto-updated to macOS 12.4 RC, the problem is fixed and I cannot reproduce it anymore. Maybe it just an internal bug of macOS 12.4 beta 4 that I used before or maybe reboot solved everything lol. 

Probably #1324  can be solved by updating to macOS 12.4 RC?

Thanks a lot anyway!

**Comment by ifsheldon** [comment]
After macOS was auto-updated to macOS 12.4RC, the problem is sort of gone and I cannot reproduce it exactly. But I found another related small issue. Here is how I reproduce this issue:
0. Enable "Start at login" of AltTab
1. Have some apps opened with some windows and have some apps running without windows. Now everything goes well with AltTab.
2. Restart my Mac with the option: re-open the windows when login (this is my English translation, but I think you know what option it is). With this option, the the context of opened windows is saved and then restored I guess.
3. After the restart, some restored windows pop up and the apps are restored to be running even if they didn't have windows before the restart.
4. The apps that have restored windows will show in AltTab correctly, but the ones that run without windows before the restart will not show in AltTab.

**Comment by lwouis** [comment]
Please see discussion from here: https://github.com/lwouis/alt-tab-macos/issues/447#issuecomment-1112805183 if you're interested in the issue with detecting apps from login.
