### ISSUE TITLE
Docker icon is glitched in the switcher

### ISSUE THREAD

**Issue by AGou-ops** [lwouis/alt-tab-macos#1573]
https://user-images.githubusercontent.com/57939102/168250219-789da90e-4746-46da-a62e-1eeb54792471.mov

Docker Desktop version: 4.8.1 (78998)
alt-tab version: 6.36.1

**Comment by AGou-ops** [comment]
latest v6.37.1 same.
![image](https://user-images.githubusercontent.com/57939102/168251314-5ffbe081-bae6-4d6d-8646-8967cac4c0ae.png)

**Comment by lwouis** [comment]
- Does this happen after you restart AltTab? Reboot the system?
- How does the Docker Desktop icon look like in the Dock?
- Your macOS version?
- Intel or Apple Silicon?

**Comment by AGou-ops** [comment]
Thank you for your reply!

Reboot the system just working! (Restart AltTab not work)😅

- is normal in the Dock.
- MacOS 12.3 with Apple Silicon.

**Comment by lwouis** [comment]
It seems it was a macOS bug then. Glag it's fixed for you~
