### ISSUE TITLE
Missing thumbnails of multiple apps

### ISSUE THREAD

**Issue by Jerome1337** [lwouis/alt-tab-macos#1578]
**Describe the bug**

Thumbnails are missing on multiple apps.
Still missing on VSCode (cf: #1472)

**Screenshots / video**

<img width="1458" alt="Screenshot 2022-05-16 at 10 09 23 AM" src="https://user-images.githubusercontent.com/7968649/168547989-63135648-519e-40b8-a146-6e38bf77a684.png">

**Versions**

AltTab: `6.37.1`
MacOS: `12.3.1`

**Comment by lwouis** [comment]
Please see #1324
