### ISSUE TITLE
App Feedback

### ISSUE THREAD

**Issue by skullz03** [lwouis/alt-tab-macos#1597]
I come from a windows background and this application has helped me a lot. Thanks for developing it. However, I'd like to point out that the mouse pointer plays a spoil sport when switching applications. If my left hand is doing alt + tab and my right hand holding the mouse moves a slight bit then instead of  switching to the next application like it should; the control switches to the application on which the mouse pointer is hovering. I usually try not to hold the mouse while switching but sometimes it is necessary to have one hand on keyboard and one on mouse. Wondering if there is any workaround where we disable the mouse pointer when the switcher layout is ON so that the controls don't jump to random applications. Thanks.

**Comment by lwouis** [comment]
In the preferences, uncheck "mouse hover" at the bottom of the Controls tab.

Also see this if you're curious: #286

**Comment by skullz03** [comment]
> #286

Thanks a ton for pointing me in the right direction. Appreciate it
