### ISSUE TITLE
Use inclusive language

### ISSUE THREAD

**Issue by andypiper** [lwouis/alt-tab-macos#1619]
Many [projects now actively avoid](https://9to5google.com/2020/06/12/google-android-chrome-blacklist-blocklist-more-inclusive/) the use of the term "blacklist" in favour of e.g. "blocklist" or "denylist". As a new user of this app I found it a little jarring, and I'd like to suggest a small change to the UI preferences to use the term "blocklist" instead. Thank you!

**Comment by lwouis** [comment]
Please see #826
