### ISSUE TITLE
Add preference: ignore certain applications

### ISSUE THREAD

**Issue by lwouis** [lwouis/alt-tab-macos#164]
@kimhn and @CAPSLOCK GOD on Discord asked to be able to filter-out some applications from showing in alt-tab thumbnails.

This is interesting and I would like to first discuss how the UI would look like

**Comment by asyncee** [comment]
Not sure if i should create a new issue, but an opposite proposal may be to include certain applications only. My use case is following: i have 10 opened projects in my IDE, each project in it's separate window. It is very convenient to switch only between windows of an IDE.

**Comment by lwouis** [comment]
@asyncee I think your use-case will be better addressed by #72.  In the new preferences, you would simply select "Active app" instead of "All apps". This way, once focused on the IDE, you would only get IDE windows.

![image](https://user-images.githubusercontent.com/106195/74341746-91faaf80-4deb-11ea-915a-d08e0863476a.png)

**Comment by lwouis** [comment]
@asyncee @kimhn @capslock should I close this ticket?

I think #237 covers the use-case for most people. The whitelist/blacklist use-case would be for very few people I imagine.

**Comment by asyncee** [comment]
> @asyncee @kimhn @capslock should I close this ticket?
> 
> I think #237 covers the use-case for most people. The whitelist/blacklist use-case would be for very few people I imagine.

I totally agree with this.
