### ISSUE TITLE
Macro to trigger AltTab instantly fails once every 10min

### ISSUE THREAD

**Issue by neilroy1998** [lwouis/alt-tab-macos#1640]
In Windows, using Autohotkey, I have remapped the Caps Lock to a quick alt+tab press.
This allows me to switch b/w 2 apps i am working with very quickly (alternate b/w the 2).

I tried the same thing with Alt Tab using BTT (this causes issue as it brings up Finder all the time) and Karabiner Elements (with a 100ms delay) which ended up working.

But, sometimes like every 10 mins, Alt Tab would not respond the 1st time it is called. It comes in the 2nd click of the shortcut key (currently Caps Lock, but also tried with other keys)

Any recommendations or alternate ways to go about it? Thanks.

**Comment by lwouis** [comment]
Can you please elaborate on how exactly you setup your macro?

AltTab responds very specifically to:

* `option` pressed down
* `tab` pressed down
* `tab` released
* `option` released

If you make a macro of that exact sequence, it should work. You can also go in the preferences and pick other keys if there is a conflict with anything else on your computer.
