### ISSUE TITLE
Alt Tab does not detect Terminal.app window

### ISSUE THREAD

**Issue by yiqiangjizhang** [lwouis/alt-tab-macos#1645]
Alt Tab seems to work with every app but does not detect the default macOS Terminal.app app.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/68460056/171671635-a71a9002-18d1-48bb-b9a7-a095a7581b0a.png">

Terminal app is open but when I toggle Alt+Tab, it does not appear (you can see through the screenshot)

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/68460056/171671955-792f96e1-9594-4f2b-95a5-9d744b2261a0.png">

How is this possible? Is it related to the OS?

**Comment by lwouis** [comment]
It's not about Terminal.app, but very likely #447 / #1324
