### ISSUE TITLE
Add preference to draw a distinctive bright line around current selection

### ISSUE THREAD

**Issue by artsra** [lwouis/alt-tab-macos#1647]
**Is your feature suggestion related to a problem? Please describe.**
Hi, my old eyes have trouble making out which of the windows is the currently selected one, especially on dark backgrounds, and in the evenings (in dark mode).
When I hold down the Option key, and repeatedly press tab, it's not easy for me to see the selection moving.

**Describe the solution you'd like**
It would be great if you could create a preference for drawing a bright line around the currently selected window.

**Describe alternatives you've considered**
I looked around the preference screen but could not find a way to make the cuurrent selection stand out more. Maybe I missed something. Thanks.

**Comment by lwouis** [comment]
> drawing a bright line around the currently selected window.

Please try Preferences > Appearance > Theme: Windows 10

This is exactly what you're asking for~

**Comment by artsra** [comment]
Ah right! It's probably my bias against Windows that made me not consider this option... Thanks!
