### ISSUE TITLE
Activity Monitor and Commander One are not picked up by AltTab

### ISSUE THREAD

**Issue by Perlence** [lwouis/alt-tab-macos#1655]
Activity Monitor and Commander One are not picked up by AltTab. I believe these two have in common that the toolbar integrated into the title bar. The issue doesn't affect v6.40.0.

AltTab v6.41.0
macOS v12.4

https://user-images.githubusercontent.com/1044300/172024347-1459ae73-c433-409a-b2eb-0084bd4ddb0b.mp4

**Comment by lwouis** [comment]
I just tested on my local machine (10.15), and also on a 12.4 VM. Activity Monitor showed normally in both cases.

In your video, we don't see when the various apps are launched. I suspect this issue may be #1324

**Comment by Perlence** [comment]
Hey @lwouis, thanks for looking! I was able to reproduce it again after a reboot on v6.41.1, this time with starting the apps on the record.

https://user-images.githubusercontent.com/1044300/172043347-e86d8500-1edd-4c2e-b0c3-2f3ac7fe6e34.mp4

**Comment by lwouis** [comment]
Maybe you have a preference set to not show it? I can't think of what could be the cause. It works well for me and probably everyone else since there hasn't been any other ticket/comment.

Could you please share your preferences? Either screenshots or you can run `defaults read com.lwouis.alt-tab-macos` in Terminal.app and paste the results here.

**Comment by Perlence** [comment]
Let me share the preferences:

```
$ defaults read com.lwouis.alt-tab-macos
{
    MSAppCenter310AppCenterUserDefaultsMigratedKey = 1;
    MSAppCenter310CrashesUserDefaultsMigratedKey = 1;
    MSAppCenterInstallId = "0157A58A-42F1-486B-999A-C0A16643FAE6";
    MSAppCenterNetworkRequestsAllowed = 0;
    MSAppCenterPastDevices = {length = 1149, bytes = 0x62706c69 73743030 d4010203 04050607 ... 00000000 00000389 };
    MSAppCenterSessionIdHistory = {length = 460, bytes = 0x62706c69 73743030 d4010203 04050607 ... 00000000 00000156 };
    MSAppCenterUserIdHistory = {length = 455, bytes = 0x62706c69 73743030 d4010203 04050607 ... 00000000 00000151 };
    "NSStatusItem Visible Item-0" = 0;
    "NSWindow Frame SUUpdateAlert" = "410 357 620 398 0 0 1440 875 ";
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2022-06-05 08:57:33 +0000";
    SUUpdateRelaunchingMarker = 0;
    hideWindowlessApps = true;
    menubarIcon = 3;
    mouseHoverEnabled = false;
    preferencesVersion = "6.40.0";
    previousWindowShortcut = "\\U21e7\\U21e5";
    showOnScreen = 0;
    spacesToShow = 1;
    spacesToShow2 = 1;
    updatePolicy = 1;
    windowMaxWidthInRow = 30;
}
```

**Comment by lwouis** [comment]
@Perlence you're on mainstream macOS 12.4, not on a beta or something? Which exact version are you on? You can get that info in the Apple on the top left > About This Mac > Click on the version text > It should reveal a more complete version number.

I can't reproduce the issue in your video on my VM which is on macOS `12.4 (21F79)`:

https://user-images.githubusercontent.com/106195/172132480-39e36e30-732c-40d3-8932-fb9127574338.mov

Also, you say that with AltTab v6.40.0, the issue doesn't happen? Are you sure?

**Comment by Perlence** [comment]
Thanks, the macOS version is also 12.4 (21F79).

Yes, I'm currently using AltTab v6.40.0 and I don't experience this issue.

Would it make sense to drop the preferences?

**Comment by lwouis** [comment]
It doesn't hurt

**Comment by lwouis** [comment]
Can you verify you have given the Accessibility and Screen Recording permissions in System Preferences?

Also is AltTab located in `/Applications`?

**Comment by Perlence** [comment]
Unfortunately, removing preferences doesn't help.

The Accessibility and Screen Recording permissions are set.

Yes, the path is `/Applications/AltTab.app`.

**Comment by Perlence** [comment]
Could it be related to the window detection improvements? https://github.com/lwouis/alt-tab-macos/commit/de0497a

**Comment by lwouis** [comment]
> Could it be related to the window detection improvements? [de0497a](https://github.com/lwouis/alt-tab-macos/commit/de0497a)

It could, of course, but my biggest issue here is understanding why the app behaves differently on your system than on mine, because I'm running code with the commit you mention, and it shows me all the windows, so is it really about the code? It seems there is some environment diff here.

Could you please try the same scenario you do in your last video, but this time you would launch AltTab through Terminal.app? You can run this: `/Applications/AltTab.app/Contents/MacOS/AltTab` to launch it that way. Terminal will then list AltTab logs in real time. If you make the logs visible (like making terminal take the left side of the screen and the other windows the right side of the screen) then maybe I can compare them to what happens on my machine, and find some difference that gives me something to work with.

**Comment by Perlence** [comment]
I had to give the Accessibility and Screen Recording permissions to Terminal.app.

https://user-images.githubusercontent.com/1044300/172144492-af3ed82f-f9fd-481d-a272-7f08ef40d8fd.mp4

Here's the log:

<details>
<pre>
"Current space" 1
"Adding app" 368 "com.apple.loginwindow"
"Adding app" 548 "com.apple.dock"
"Adding app" 550 "com.apple.systemuiserver"
"Adding app" 549 "com.apple.controlcenter"
"Adding app" 571 "com.apple.accessibility.AXVisualSupportAgent"
"Adding app" 547 "com.apple.talagent"
"Adding app" 614 "com.apple.RemoteDesktopAgent"
"Adding app" 654 "com.apple.AirPlayUIAgent"
"Adding app" 672 "com.clipy-app.Clipy"
"Adding app" 660 "com.apple.TextInputMenuAgent"
"Adding app" 629 "com.apple.notificationcenterui"
"Adding app" 667 "com.apple.SSMenuAgent"
"Adding app" 674 "com.apple.coreservices.uiagent"
"Adding app" 679 "com.wireguard.macos"
"Adding app" 642 "com.wacom.wacomtablet"
"Adding app" 682 "com.github.xor-gate.syncthing-macosx"
"Adding app" 677 "com.apple.TextInputSwitcher"
"Adding app" 680 "com.apple.AppSSOAgent"
"Adding app" 687 "org.hammerspoon.Hammerspoon"
"Adding app" 688 "com.theron.UnnaturalScrollWheels"
"Adding app" 611 "com.apple.wifi.WiFiAgent"
"Adding app" 725 "com.apple.CoreLocationAgent"
"Adding app" 739 "com.apple.Spotlight"
"Adding app" 735 "com.apple.security.Keychain-Circle-Notification"
"Adding app" 644 "com.logitech.manager.daemon"
"Adding app" 823 "com.wacom.TabletDriver"
"Adding app" 824 "com.wacom.WacomTouchDriver"
"Adding app" 829 "com.apple.SoftwareUpdateNotificationManager"
"Adding app" 851 "com.apple.OSDUIHelper"
"Adding app" 2984 "com.microsoft.to-do-mac"
"Adding app" 3241 "com.apple.LocalAuthentication.UIAgent"
"Adding app" 3792 "com.apple.UserNotificationCenter"
"Adding app" 10797 "com.apple.PowerChime"
"Adding app" 16434 "com.apple.locationmenu"
"Adding app" 18751 "com.docker.docker"
"Adding app" 18850 "com.electron.dockerdesktop"
"Adding app" 18996 "com.docker.docker"
"Adding app" 69860 "com.apple.nbagent"
"Adding app" 6884 "com.apple.accessibility.universalAccessAuthWarn"
"Adding app" 13470 "com.apple.finder"
"Adding app" 13861 "com.apple.Terminal"
"Adding app" 24283 "com.lwouis.alt-tab-macos"

"Accessibility event" "AXWindowCreated" ""
2022-06-06 14:30:05.258 AltTab[24283:1076618] It's not legal to call -layoutSubtreeIfNeeded on a view which is already being laid out.  If you are implementing the view's -layout method, you can call -[super layout] instead. Break on void _NSDetectedLayoutRecursion(void) to debug.  This will be logged only once.  This may break in the future.
"Adding window" 4114 "sviatoslav — sviatoslav: /Applications/AltTab.app/Contents/MacOS/AltTab - /Applications/AltTab.app/Contents/MacOS/AltTab — AltTab — 95×44" "com.apple.Terminal"
"Adding window" 3770 "Desktop" "com.apple.finder"

"OS event" "apps launched" [(24285, Optional("com.apple.ActivityMonitor"))]
"Adding app" 24285 "com.apple.ActivityMonitor"
"Adding window" 4144 "Activity Monitor – All Processes" "com.apple.ActivityMonitor"
"showUiOrCycleSelection"
"showUiOrCycleSelection: isFirstSummon"
"Accessibility event" "AXFocusedWindowChanged" ""
"Accessibility event" "AXWindowCreated" ""
"showUiOrCycleSelection"
"showUiOrCycleSelection"
"showUiOrCycleSelection"
"showUiOrCycleSelection"
"focusTarget"
"hideUi"
"Accessibility event" "AXApplicationActivated" "Finder"
"Accessibility event" "AXApplicationActivated" "Terminal"
"Accessibility event" "AXApplicationActivated" "Activity Monitor"
"Accessibility event" "AXApplicationActivated" "Terminal"
</pre>
</details>

**Comment by lwouis** [comment]
Do you see the window if you check the checkbox in `Preferences > Appearance > Show standard tabs as separate windows`?

**Comment by lwouis** [comment]
Can you try this build?
[AltTab.app.zip](https://github.com/lwouis/alt-tab-macos/files/8844399/AltTab.app.zip)

It has the old value in some function used for tab detection. It may be the root cause of the regression.

**Comment by Perlence** [comment]
Wow, I see it now after selecting the option. Let me check the build.

**Comment by lwouis** [comment]
Ok I'll release a version which reverts this change then. I still wish I could understand what was different in your environment, but it could be affecting many other users, so I'd rather revert the change for safety, regardless of understanding the issue all the way.

**Comment by Perlence** [comment]
Thank you so much for looking into it! If you need to test any hypotheses about the root cause, please reach out, I'll help with testing them.

**Comment by lwouis** [comment]
@Perlence  Issue should be gone in the new release. Let me know if it's not 👍

**Comment by JoshYEn** [comment]
What's up bro, @lwouis 

I experienced a similar issue in v6.42.0. In my scenario, I have several apps opened in another desktop. And these apps can not be recognized in AltTab unless I minimize and restore it.

**Comment by lwouis** [comment]
@JoshYEn I think you're experiencing #1324
