### ISSUE TITLE
option to hide menu icon on menu bar

### ISSUE THREAD

**Issue by cad0p** [lwouis/alt-tab-macos#1657]
Especially with the new macs with the notch, every menu bar item has become lost precious space. I only would need to occasionally edit the settings for this app (as it works very nicely!), so I would like to have the option to disable the menu bar icon (even if the service is running), so that if it starts at login you don't have to do anything. To kill it, you would have to open the app (AltTab) and click on a button to quit the service. Of course this would be not automatic behavior, but an optional setting.

Thanks!

**Comment by meiser79** [comment]
it's already there. Under "General", select the last selection which is an empty icon.

**Comment by cad0p** [comment]
ah thanks! Maybe this will be useful for others then :)

**Comment by bchilcott** [comment]
> it's already there. Under "General", select the last selection which is an empty icon.

Is there any reason there isn't just a checkbox for hiding the icon? I spent forever trying to figure out how to hide it because that non-icon icon is hidden pretty well..
