### ISSUE TITLE
Time opened/time last active next to window title 

### ISSUE THREAD

**Issue by paul-m-1844** [lwouis/alt-tab-macos#1665]
**Is your feature suggestion related to a problem? Please describe.**
Window management is a big part of how we keep track of our activities. But I've always wondered, why has no-one ever added this simple piece of metadata next to the windowtitle so that we can we easily keep track of how long we have spent on one task. 

**Describe the solution you'd like**
Put simply, I think the simplest implementation would be to have a simple timestamp hh:mm on the right hand-side of the window title. 

**Describe alternatives you've considered**
I've tried many time tracking tools, and all have a large overhead and bloated review and activity retrieval process compared to this option, which can easily fit into any workflow.

**Comment by lwouis** [comment]
I'm afraid this is too outside the mission of this app. AltTab is trying to be the best way to navigate between windows on a mac. Sorry 🙇
