### ISSUE TITLE
Not showing catalyst apps

### ISSUE THREAD

**Issue by CavalloneChen** [lwouis/alt-tab-macos#167]
Twitter and Fiery Feeds don't show up in the switcher. Those two apps are catalyst apps, maybe there are some catalyst app specific bugs?

**Comment by CavalloneChen** [comment]
Quit and reopen these apps solves the problem.

**Comment by lwouis** [comment]
@CavalloneChen thanks for sharing this issue! Indeed I tried on my laptop, and Twitter correctly shows, even if you launch it *then* launch alt-tab.

That being said, I noticed another issue: the shortcut doesn't work when Twitter app is focused. It acts in a similar way to #17. Same approach to fix the issue as that ticket then
