### ISSUE TITLE
切换窗口是否可以隐藏同应用的多个窗口

### ISSUE THREAD

**Issue by zy-dys** [lwouis/alt-tab-macos#1679]
command + tab 切换时，有多个窗口的的应用是否能只显示一个窗口
比如web开发时，因为没有使用多个显示器，需要频繁切换编辑器和浏览器窗口，但是浏览器打开了控制台独立窗口，通常是在浏览器的时候才会切换控制台，而从编辑器切换到浏览器的时候，浏览器的每个窗口都在列表中，看起来很混乱，而且经常会切错，编辑器窗口也是同理，打开多个窗口，切换到编辑器的时候，是否可以只保留最后一次的窗口在切换列表中

**Comment by lwouis** [comment]
If you only care about the latest window of an app, then the native app-switcher from macOS does that. You can also simply press alt+tab quickly to switch between 2 windows.

I don't really understand your scenario and the problem you face.
