### ISSUE TITLE
Two Instances of AltTab open after booting the machine

### ISSUE THREAD

**Issue by namanmansukhani** [lwouis/alt-tab-macos#1680]
**Describe the bug**

When I restart my machine, I see two instances of AltTab that interfere with each other. I have to manually quit one of these.

**Screenshots / video**

<img width="91" alt="image" src="https://user-images.githubusercontent.com/66830320/172836150-1fa7a6ad-06a5-4986-9ca1-c33c33795f3d.png">
<img width="542" alt="image" src="https://user-images.githubusercontent.com/66830320/172836169-070f68e5-c526-4650-85f1-3a4a3427fdc1.png">

**Steps to reproduce the bug**

I'm not sure if the bug can be reproduced on another machine. I simpy installed AltTab using brew. This issue arises every time I restart my machine.

**Comment by lwouis** [comment]
Please make sure:

* AltTab doesn't appear in System Preferences > Users > Login Items
* AltTab is only present in the `/Applications` folder

It's likely you have multiple versions installed on your system somehow. Please look for the other one and remove it.
