### ISSUE TITLE
Improve visibility by adding a border to selected window in alt-tab menu

### ISSUE THREAD

**Issue by bbud148** [lwouis/alt-tab-macos#1691]
Issue: It is difficult to see which application window is selected in the alt-tab menu, especially against dark menus.  This is because the selected window has only a slight difference in shading and lack of contrast.

Solution:  Coming from Windows, the alt-tab functionality has a strong white border that highlights the selected application window within the alt-tab menu.  This would help improve visibility as to what is being highlighted in the peripheral vision.  Possible alternatives include different colored borders or backgrounds.

**Comment by lwouis** [comment]
Please go in Preferences > Appearance > Theme: Windows 10. This is exactly what you want

**Comment by bbud148** [comment]
I'm an idiot, thank you
