### ISSUE TITLE
Hide unused apps 

### ISSUE THREAD

**Issue by Odreeq** [lwouis/alt-tab-macos#1695]
Hello 

Any idea how to remove those apps highlighted in the picture? 
![IMG_3540](https://user-images.githubusercontent.com/107669787/174237809-bbbe9ef9-1e7b-4396-af20-3d09800082b5.jpeg)

Thanks

**Comment by lwouis** [comment]
Preferences > Appearance > Hide apps with no open window

**Comment by Odreeq** [comment]
thanks!
