### ISSUE TITLE
Infinite loop trying to subscribe to stuck processes

### ISSUE THREAD

**Issue by lwouis** [lwouis/alt-tab-macos#170]
I noticed alt-tab using CPU while idle:

![Screen Shot 2020-03-10 at 21 42 48](https://user-images.githubusercontent.com/106195/76335979-ad000700-6338-11ea-9a01-44072957da2d.jpg)

Turns out there is still an issue with the `AXObserverAddNotification` subscription retry loop.

I described the issue in details in https://github.com/koekeishiya/yabai/issues/439

**Comment by koekeishiya** [comment]
If you still care about fixing this, I believe I have actually found a good way to solve this.
I've explained my solution in https://github.com/koekeishiya/yabai/issues/529

Relevant code changes are linked to the issue through commits.
