### ISSUE TITLE
Doesn't show some windows after the update

### ISSUE THREAD

**Issue by mmmmie** [lwouis/alt-tab-macos#1719]
**Describe the bug**

Some windows won't show, occurs every time. Known apps with this issue: Spotify, Wechat, Netease Music. In settings, I selected all apps, all spaces, and all screens.

**Screenshots / video**

https://user-images.githubusercontent.com/37318622/174933943-733f84ef-c66a-43e5-8cb0-e63027610047.mp4

**Steps to reproduce the bug**

1. Open windows
2. Click command tab
3. Some windows doesn't show

**Comment by lwouis** [comment]
Hi,

I tried to reproduce with WeChat, Spotify, and Netease Music. All 3 apps show for me, on v6.45.0.

The title you used contains "after the update". Could you please clarify the version you had, and the version you updated to? If you install the previous version manually (you can find [all previous versions here](https://github.com/lwouis/alt-tab-macos/releases)), is the issue gone?

Also, did you open AltTab then the apps, or did you open the apps then AltTab?

Do you use multiple Spaces? In that case it could be #1324

Thank you

**Comment by mmmmie** [comment]
Hi,

Mine was v6.44.0. I just tried downloading 6.45.0, now it works now!

Thank you.
