### ISSUE TITLE
mpv windows don't show up in AltTab

### ISSUE THREAD

**Issue by hotsno** [lwouis/alt-tab-macos#1720]
**Describe the bug**

[mpv](https://github.com/mpv-player/mpv) windows do not show up in AltTab.

**Steps to reproduce the bug**

1. Open mpv either by launching mpv.app, or using the `mpv` command in a terminal
2. Can't see mpv window in AltTab

**Comment by lwouis** [comment]
I downloaded mpv.app here: https://laboratory.stolendata.net/~djinn/mpv_osx/. I can launch it, open movie in it, and AltTab always shows its windows.

Could you please share more info?

* Video of the issue in motion
* macOS version
* AltTab version
* How you installed mpv
* Etc

**Comment by hotsno** [comment]
Ah, I think I figured out what's causing it. It seems to be a setting I have set in my mpv's configuration file. In `~/.config/mpv/mpv.conf` when I remove the line `ontop` mpv shows up in AltTab as expected, so that setting is what's causing it. You can read about the setting [here](https://mpv.io/manual/master/#options-ontop), but I think this is niche enough to be of very low priority, so I totally understand if you want to ignore this issue.

**Comment by lwouis** [comment]
@hotsno it's most likely mpv using a non-standard window to have it float on top. AltTab filters out certain types of "windows" so you don't see all sorts of HUDs, popups, dropdown menus, etc, when you alt-tab.

I suggest you open a ticket with mpv as AltTab is showing standard windows, and if AltTab filters it out, there is high chance other accessibility apps will.

in other words, mpv likely has issues with their implementation of "always-on-top" windows.
