### ISSUE TITLE
copying application window not showing in alt tab

### ISSUE THREAD

**Issue by 1Mark** [lwouis/alt-tab-macos#1721]
**Describe the bug**
Window should be displayed in alt-tab

**Screenshots / video**
![image](https://user-images.githubusercontent.com/15360245/175012504-4ce62411-1f65-4547-a738-faa7720d76b6.png)

Add screenshots to help explain your problem. You can also use Loom to easily record your screen to show the bug in action. That is *really* helpful!

**Steps to reproduce the bug**

Install docker, then when it asks you to drag it to applications folder and you hit alt tab you can locate the window.

**Comment by lwouis** [comment]
Which window is not showing on your screenshot? The one at the top, or the file copy at the bottom?

For the file copy, we already have https://github.com/lwouis/alt-tab-macos/issues/1466. The other is Finder, so i expect it would show
