### ISSUE TITLE
High CPU usage + Colored circles flickering after startup

### ISSUE THREAD

**Issue by XInTheDark** [lwouis/alt-tab-macos#1726]
**Bug description:**

I have AltTab in my login items. Some time after startup, I see high CPU usage (hitting as high as 20%) in AltTab. Also, whenever I go to the app switcher window, the colored circles start flickering very fast and it is impossible to click on them.

After quitting the process and starting it again, both problems are fixed.

**Steps to reproduce the bug**

1. Add AltTab to login items
2. After startup, use the computer normally.
3. After some time (not certain of the exact time), use the app switcher. 
4. Should notice colored circles flickering & high CPU usage.

**Comment by XInTheDark** [comment]
This happens every time on startup and is fixed by quitting the app.

**Comment by lwouis** [comment]
@XInTheDark you can see the double AltTab instances on your screenshot. That's exactly the issue I predicted.

To avoid this, remove AltTab from your Login Items. If you want AltTab to launch at login, check the checkbox in Preferences > General, but don't add to Login Items yourself. Or add it yourself, then uncheck the checkbox. Both will launch 2 AltTabs, which will create a mess on your system.
