### ISSUE TITLE
Placeholder icon inverted since upgrading to 6.46.0

### ISSUE THREAD

**Issue by frypf** [lwouis/alt-tab-macos#1727]
**Describe the bug**

Just upgraded from 6.45.0 and realised the placeholder icon (for apps with no windows) seems to be inverted now. Not sure if this was an intentional change just figured I'd flag it in case it wasn't - has no effect on functionality.

**Screenshots**
6.46.0:
<img width="1041" alt="Screenshot 2022-06-23 at 14 30 40" src="https://user-images.githubusercontent.com/65832791/175312701-cca6787a-e782-4ef3-9495-08296b7a2e8b.png">
6.45.0:
<img width="989" alt="Screenshot 2022-06-23 at 14 35 12" src="https://user-images.githubusercontent.com/65832791/175312710-97b3c53f-f0ec-4dc6-ba3e-f2e3d872fcc0.png">

**Comment by frypf** [comment]
I did think it looked too "clean" to have been a random change, no worries - should've read through the other issues, I only mentioned it as there was nothing in the changelog.

Although you're right, it is jarring when everything else is in dark mode - ironically the old white icon on transparent background already contrasted plenty for me when compared with other dark windows.

**Comment by imikushin** [comment]
The placeholder for apps without windows looked better prior to 6.46.0, IMO 🙂

Thanks for the fantastic app, BTW!
