### ISSUE TITLE
Remaining window controls #2

### ISSUE THREAD

**Issue by decodism** [lwouis/alt-tab-macos#1730]
**Describe the bug**

Similarly to #925, in some cases, when a window is closed or an app is quit by its control buttons, the element on the right inherits these control buttons.

**Steps to reproduce the bug**

- Open the Finder without a window, an app without a window and an app with a window
- Quit the app without a window by its button

**Comment by lwouis** [comment]
Thanks @decodism for sharing this bug! I was able to reproduce it.

I think the issue goes beyond the the next thumbnails inheriting the previous thumbnails controls. If a thumbnail disappears (app is quit, window is closed, etc), and the mouse doesn't move after that, then we shouldn't show any control.

I'll ship a fix soon~
