### ISSUE TITLE
command+` shortcut not working on macOS 13

### ISSUE THREAD

**Issue by L1cardo** [lwouis/alt-tab-macos#1734]
**Describe the bug**
"CMD+ \`" is not working
I tried to use "CMD+ `" as "select previous window", but it did not work.

**Screenshots / video**

<img width="610" alt="image" src="https://user-images.githubusercontent.com/33802186/175604713-b20a04d7-f931-4c80-aec0-1c7e86e75b45.png">

<details>
<summary><strong>Debug profile</strong></summary>
<p>

* App version: 6.46.1
* App preferences: 
  * MSAppCenter310AppCenterUserDefaultsMigratedKey: 1
  * MSAppCenter310CrashesUserDefaultsMigratedKey: 1
  * MSAppCenterAppDidReceiveMemoryWarning: 1
  * MSAppCenterInstallId: B825E425-EB28-4EB2-A325-6125A724B525
  * MSAppCenterNetworkRequestsAllowed: 0
  * MSAppCenterPastDevices: {length = 1155, bytes = 0x62706c69 73743030 d4010203 04050607 ... 00000000 0000038f }
  * MSAppCenterSessionIdHistory: {length = 460, bytes = 0x62706c69 73743030 d4010203 04050607 ... 00000000 00000156 }
  * MSAppCenterUserIdHistory: {length = 455, bytes = 0x62706c69 73743030 d4010203 04050607 ... 00000000 00000151 }
  * NSNavLastRootDirectory: /Applications
  * NSNavPanelExpandedSizeForOpenMode: {800, 448}
  * NSStatusItem Visible Item-0: 0
  * NSWindow Frame NSNavPanelAutosaveName: 560 336 800 448 0 0 1920 1055 
  * SUHasLaunchedBefore: 1
  * SULastCheckTime: 2022-06-25 上午7:05:57 +0000
  * blacklist: [{"ignore":"0","bundleIdentifier":"com.McAfee.McAfeeSafariHost","hide":"1"},{"ignore":"0","bundleIdentifier":"com.apple.finder","hide":"2"},{"ignore":"2","bundleIdentifier":"com.microsoft.rdc.macos","hide":"0"},{"ignore":"2","bundleIdentifier":"com.teamviewer.TeamViewer","hide":"0"},{"ignore":"2","bundleIdentifier":"org.virtualbox.app.VirtualBoxVM","hide":"0"},{"ignore":"2","bundleIdentifier":"com.parallels.","hide":"0"},{"ignore":"2","bundleIdentifier":"com.citrix.XenAppViewer","hide":"0"},{"ignore":"2","bundleIdentifier":"com.citrix.receiver.icaviewer.mac","hide":"0"},{"ignore":"2","bundleIdentifier":"com.nicesoftware.dcvviewer","hide":"0"},{"ignore":"2","bundleIdentifier":"com.vmware.fusion","hide":"0"},{"ignore":"2","bundleIdentifier":"com.apple.ScreenSharing","hide":"0"},{"ignore":"0","bundleIdentifier":"com.tourbox.ui.launch","hide":"1"}]
  * holdShortcut: ⌘
  * menubarIcon: 3
  * nextWindowShortcut: ⇥
  * preferencesVersion: 6.46.1
  * previousWindowShortcut: `
  * updatePolicy: 1
  * windowMaxWidthInRow: 30
* Applications: 64
* Windows: 9
  * {isFullscreen: false, isWindowlessApp: true, isMinimized: false, isHidden: false, isTabbed: false, isOnAllSpaces: false, shouldShowTheUser: false, spaceId: 18446744073709551615, spaceIndex: 9223372036854775807}
  * {isFullscreen: false, isWindowlessApp: false, isMinimized: false, isHidden: false, isTabbed: false, isOnAllSpaces: false, shouldShowTheUser: true, spaceId: 1, spaceIndex: 1}
  * {isFullscreen: false, isWindowlessApp: false, isMinimized: false, isHidden: false, isTabbed: false, isOnAllSpaces: false, shouldShowTheUser: true, spaceId: 1, spaceIndex: 1}
  * {isFullscreen: false, isWindowlessApp: false, isMinimized: false, isHidden: false, isTabbed: false, isOnAllSpaces: false, shouldShowTheUser: true, spaceId: 1, spaceIndex: 1}
  * {isFullscreen: false, isWindowlessApp: true, isMinimized: false, isHidden: false, isTabbed: false, isOnAllSpaces: false, shouldShowTheUser: true, spaceId: 18446744073709551615, spaceIndex: 9223372036854775807}
  * {isFullscreen: false, isWindowlessApp: true, isMinimized: false, isHidden: false, isTabbed: false, isOnAllSpaces: false, shouldShowTheUser: true, spaceId: 18446744073709551615, spaceIndex: 9223372036854775807}
  * {isFullscreen: false, isWindowlessApp: false, isMinimized: false, isHidden: false, isTabbed: false, isOnAllSpaces: false, shouldShowTheUser: true, spaceId: 1, spaceIndex: 1}
  * {isFullscreen: false, isWindowlessApp: false, isMinimized: false, isHidden: false, isTabbed: false, isOnAllSpaces: false, shouldShowTheUser: true, spaceId: 1, spaceIndex: 1}
  * {isFullscreen: false, isWindowlessApp: false, isMinimized: false, isHidden: false, isTabbed: false, isOnAllSpaces: false, shouldShowTheUser: true, spaceId: 1, spaceIndex: 1}
* OS version: 版本13.0（版号22A5286j）
* OS architecture: arm64
* Locale: zh_CN (current)
* Spaces: 1
* Dark mode: Light
* "Displays have separate Spaces": checked
* Hardware model: Macmini9,1
* Screens: 1
  * {x: 0.0, y: 0.0, width: 1920.0, height: 1080.0}
* CPU model: Apple M1
* Memory size: 8.59 GB
* Active CPU count: 8
* Current CPU frequency: nil
* Resource utilization: 
  * CPU: 1.8%
  * Memory: 81M
  * Threads count: 9

</p>
</details>

**Comment by lwouis** [comment]
``` cmd+` ``` is used by `Shortcut 2` by default. Did you first unbind `Shortcut 2`?

**Comment by L1cardo** [comment]
> `` cmd+` `` is used by `Shortcut 2` by default. Did you first unbind `Shortcut 2`?

Yes. This is my shortcut 2.
<img width="596" alt="image" src="https://user-images.githubusercontent.com/33802186/175750212-d7737706-14e0-4383-a5ec-8bf33c250283.png">

**Comment by lwouis** [comment]
What keyboard do you use?
Can you bind anything successfully to ` or is it just the previous window command that fails?

**Comment by L1cardo** [comment]
1. IQUNIX OG80
2. It is just previous window command that fails, other command works fine with `

**Comment by lwouis** [comment]
Could you click the icon in the menubar > Send feedback > write anything recognizable in the message field, then make sure the checkbox is checked and submit?

That way i can look at some technical specs of your setup and maybe guess what's going on?

**Comment by L1cardo** [comment]
> Could you click the icon in the menubar > Send feedback > write anything recognizable in the message field, then make sure the checkbox is checked and submit?
> 
> That way i can look at some technical specs of your setup and maybe guess what's going on?

#1737

**Comment by XInTheDark** [comment]
I cannot duplicate this. 
Using cmd+` works fine for me.

**Comment by L1cardo** [comment]
![Untitled 2022-06-26 8_24_44 PM](https://user-images.githubusercontent.com/33802186/175814001-05311c45-d125-4514-88cb-20e250f21606.gif)

**Comment by L1cardo** [comment]
> I cannot duplicate this.
> Using cmd+` works fine for me. I am using the MacBook's keyboard so maybe the issue is due to the external keyboard.

I don't think this is related to external keyboard, because "opt+`" works fine.

**Comment by lwouis** [comment]
* Do you use other software to remap/change keyboard mapping (e.g. BTT, Karabineer, IQUNIX OG80 driver app, etc)?
* Is there a new OS shortcut on macOS 13 that's bound to ``` command+` ``` maybe? Does it do anything outside of AltTab? On previous macOS version, it would usually cycle between windows of the current active app:  
  <img width="262" alt="image" src="https://user-images.githubusercontent.com/106195/175821485-d3a59de6-9722-4c5d-8cff-42f0b9807052.png">
* Can you test the same thing on a machine that has a previous macOS version than 13? I often use VMs to test previous macOS versions for some tickets, so that's another way I can recommend if you only own 1 machine, and can't test on a friend's machine.

**Comment by L1cardo** [comment]
> Is there a new OS shortcut on macOS 13 that's bound to `` command+` `` maybe?

I suddenly realized this and checked, find out there IS a new shortcut on macOS 13 that's bound to `` command+` ``!

<img width="706" alt="image" src="https://user-images.githubusercontent.com/33802186/175823342-5e976233-a6a3-43a4-b452-777f560cce99.png">


Really thank you sir! This problem has bothered me for over a week and now it is solved !

**Comment by lwouis** [comment]
I checked on my macOS 10.15, and this shortcut is already there. I guess they call this same shortcut `Move focus to next window` in System Preferences, but `Cycle Through Windows` in the Windows menubar dropdown?

So, this shortcut existed in previous macOS version, _and_ it doesn't interfere with AltTab on macOS 10.15 (i.e. I can use the shortcut as you've setup, and AltTab uses it, instead of the OS shortcut triggering and preventing AltTab from doing its action).

The only conclusion I can draw is that they changed something about the priority of this shortcut in macOS 13 somehow. It seems that the OS reacts to it before AltTab gets a change to, and then the OS absorbs it instead of passing it to AltTab.

If anyone has an idea of more info, please share it here. For now, I'll close this ticket as I don't see anything I could do to improve things, and also this particular workflow is probably a bit niche, so not many people may be affected.

**Comment by yitang** [comment]
I just noticed this issues as well on macOS 12.4. even I disable the cmd + ` shortcut in system setting, alt-tab won't pick up the cmd + `. 

what's more interesting, with the cmd + ` shortcut enabled, it won't work for Emacs. when I press cmd+`, Emacs's own shortcuts takes precedence over OS shortcut.. 

I feel this is a strange issue in macOS shortcuts.
