### ISSUE TITLE
High CPU usage when using cursor

### ISSUE THREAD

**Issue by XInTheDark** [lwouis/alt-tab-macos#1738]
**Describe the bug**

When I use the cursor to select windows, high CPU usage (around 8%) is observed.
However, when I use hotkeys to select the same windows, the CPU usage is only around 3%.

**Screenshots / video**

[Screen Recording](https://vimeo.com/724172845)

**Comment by lwouis** [comment]
Is this really an issue AltTab is having? I think it's simply macOS basic technology. If I open a Finder window and move around on top of it, it goes into high CPU as well.

**Comment by XInTheDark** [comment]
> I think it's simply macOS basic technology. If I open a Finder window and move around on top of it, it goes into high CPU as well.

That's true, although I have no idea why this happens. Why should the movement of the cursor affect CPU usage anyways?

**Comment by lwouis** [comment]
Mouse movement can interact with an app. Like you hover a window and it changes the color of some items, or some buttons get highlighted.

The way this is implemented is that the window gets a callback for every "tick" of the time when there is motion and action from the mouse. The ticks in practice happen at very high frequency, using lots of CPU.

I'm going to close the ticket. Let me know if you have something you think is abnormal
