### ISSUE TITLE
Sometime active windows are not shown on AltTab

### ISSUE THREAD

**Issue by jasonycw** [lwouis/alt-tab-macos#1742]
**Describe the bug**

Sometime active windows are not showing in AltTab.

This happens quite randomly
sometime, the app will just be shown as no open windows and ordered at the very end
sometime, the app will not show up in AltTab at all

Both make quick windows switching impossible

**Screenshots / video**

Opened VS Code but it's not showing on AltTab
![image](https://user-images.githubusercontent.com/4518597/176087959-301b2365-441e-4855-b5f4-8ed581749413.png)

**Steps to reproduce the bug**

1. Install AltTab
2. Open some apps
3. Click AltTab
4. See some active app shown as no open windows and some not shown in the list at all

**Comment by lwouis** [comment]
I think you're observing #1324
