### ISSUE TITLE
icons size

### ISSUE THREAD

**Issue by smo1in** [lwouis/alt-tab-macos#1746]
**Describe the bug**
<img width="702" alt="Снимок экрана 2022-06-29 в 18 21" src="https://user-images.githubusercontent.com/37908645/176476814-76d3449e-2b4c-4d6f-ac84-8e264704181b.png">

Size of icons is randomly different. The purpose to use only icons no text, no preview

**Comment by lwouis** [comment]
Yes, this is known. It's because the preferences can let the user specify contradictory values. The icon height and number of rows and percentage of the screen covered by AltTab are easily in contradiction for instance.

This will be addressed more generally in #351
