### ISSUE TITLE
How to get the currently active window?

### ISSUE THREAD

**Issue by GanZhiXiong** [lwouis/alt-tab-macos#1751]
I know the following code can get the currently activated App:
``` swift
let frontApp = NSWorkspace.shared.frontmostApplication!
```

But what I want to get is the activated window. For example, an app has opened multiple windows, so how to get the activated window corresponding to this app?

I've searched for a long time and can't find a solution.
I believe you should know, thank you very much in advance.

**Comment by lwouis** [comment]
Sorry for the late reply.

Please don't use Github tickets to ask questions, especially unrelated to the project. Use StackOverflow, our Discord, or my email available on Github to ask me personally.

Now to answer your question:

> how to get the activated window corresponding to this app?

What do you mean by "the window"? An instance of which class? There are 2 main ways AltTab is using "get the windows" of other apps:

* The Accessibility APIs (e.g. [`AXUIElementCreateApplication`](https://developer.apple.com/documentation/applicationservices/1459374-axuielementcreateapplication)). They give you a reference to an [AXUIElement](https://developer.apple.com/documentation/applicationservices/axuielement). Then on this object, you can query `attributes` like title of the window, its size, its level on the Z-axis, etc. Note that it's the **accessibility** view of the window. Like a screenreader for blind people would use. It's the most powerful API, but it has many practical limitations, the biggest of all being that you can't retrieve data about windows **on other Spaces than the current Space**.
* The CG APIs (e.g. [`CGWindowListCopyWindowInfo`](https://developer.apple.com/documentation/coregraphics/1455137-cgwindowlistcopywindowinfo)). This is another API from the WindowServer. It gives your similar attributes as the Accessibility API, can get windows from other Spaces, but it can't interact at all with windows (focusing them, closing them, etc).

I hope this helps you
