### ISSUE TITLE
Border Control

### ISSUE THREAD

**Issue by mB-PiBox** [lwouis/alt-tab-macos#1754]
**Is your feature suggestion related to a problem? Please describe.**
Would look cleaner..

**Describe the solution you'd like**
Would be nice to have the ability to adjust the border/bezel/area around the thumbnail to make it thinner.

**Comment by lwouis** [comment]
Are you referring to the shadow around thumbnails, or are you referring to the dark background that's behind the currently selected thumbnail? (which is replaced with a white border with the Windows 10 theme)

In any case, this is a bit too niche. You're the first to ask this level of detail in customizing the UI. Furthermore, we already have too many sliders for that type of customization and are looking to simplify preferences (see #351)

**Comment by mB-PiBox** [comment]
<img width="247" alt="image" src="https://user-images.githubusercontent.com/14003870/177046832-1969f445-5223-4967-8b7b-e705a3c9b75b.png">

 I'm talking about this thonky border in-between the red taking up space..
