### ISSUE TITLE
Tabs!

### ISSUE THREAD

**Issue by mB-PiBox** [lwouis/alt-tab-macos#1755]
**Is your feature suggestion related to a problem? Please describe.**
Sucks not being able to cycle through tabs..

**Describe the solution you'd like**
Add the option tab display for safari, doesn't even have to include thumbnails.
Down arrow key on Safari thumbnail would jump into list of open tabs on that window.
Or for mouse/trackpad users, right clicking Safari thumbnail while Option + Tab is help would jump into list of open tabs on that Safari window.

**Comment by lwouis** [comment]
AltTab already supports showing tabs as windows (Preferences > Appearance > Show standard tabs as windows), but it only works if the app is using standard tabs.

Standard tabs means the app uses the standard macOS/AppKit APIs to create tabs. Finder uses that, Terminal.app uses that. Safari, Chrome, Firefox don't use that. Instead they draw custom graphics. This means there is no way for AltTab to get information about these tabs. We could probably get at least the titles of the tabs, but we can't get the screenshots, that's for sure. And getting the titles would be custom work for each web browser, and it would break anytime they do a redesign of their UI. We won't do that.

it's unfortunate that web browsers are the most used apps these days and they don't use standard tabs, especially Safari being maybe by Apple not using their own API, but c'est la vie :/

**Comment by mB-PiBox** [comment]
So then just do it for Safari .. don't care about Chrome (Malware) or any of the janky browsers based on it.. I mean, after all, if folks wanna use Chrome they should get a Chromebook 🤣

Witch gets the titles of the tabs; don't need screenshots of the tab. That seems like a waste of system resource anyways. Heck if hiding the thumbnails for the windows (apps) was an option, I would check that box real fast.. I don't see the point of the thumbnail anyways, at least on my MBP, they are to small to make out what's in them anyways, at least any text small images..

**Comment by lwouis** [comment]
> Heck if hiding the thumbnails for the windows (apps) was an option, I would check that box real fast.. I don't see the point of the thumbnail anyways, at least on my MBP, they are to small to make out what's in them anyways, at least any text small images..

There is a preference you can check to not show thumbnails. There are also many preferences to change the size of many UI components including thumbnails, if you have issues seeing them clearly. All these are in Preferences > Appearance.
