### ISSUE TITLE
AltTab randomly hides all browser windows

### ISSUE THREAD

**Issue by John15321** [lwouis/alt-tab-macos#1756]
**Describe the bug**

For some reason AltTab randomly hides all of my browser windows, no matter if there are a few of them, a single one, or if they are in fullscreen this happens randomly for a few seconds. Video below

**Screenshots / video**

I link the video which is on my google drive because it's too big to upload here:
https://drive.google.com/file/d/1ayvYlJrkS0shFGnCnt4-hPi3qi5j6kwY/view?usp=sharing

**Comment by lwouis** [comment]
It looks like the cause is most likely #1324
