### ISSUE TITLE
Alacritty windows considered seperate

### ISSUE THREAD

**Issue by LiamKearn** [lwouis/alt-tab-macos#1776]
I've noticed Alacritty's windows are considered separate eg. If I have an alt-tab shortcut to switch between active windows it doesn't consider multiple Alacritty windows as the same app.

I suspect this is an Alacritty issue (or choice) since the same behaviour exists with the default OSX app switcher.

My question here would be if there are any Alt-Tab side "hacks" or workarounds. IMO it would be handy to have something that would "group" windows by Application name or some other identifier in hacky scenarios rather than whatever more reliable API is in place now.

I'll have a look around on the Alacritty side and update here if I find anything that might help future troubleshooters!

**Comment by LiamKearn** [comment]
Well I suppose I should have made at least one search, Alacritty has started supporting multi-window mode since I started using it.

This is the easiest solution.

**Comment by lwouis** [comment]
An app which spawns another instance of itself to spawn a new window is indeed not doing what's expected on macOS.

AltTab will not create a grouping system for such apps. It would be very complex, would complicate the UI, and be used for a very small amount of apps that don't integrate properly with macOS.

I'm closing this ticket. Hopefully, they can fix their macOS integration on Alacritty side.
