### ISSUE TITLE
Microsoft Edge does not show up when you Alt-Tab

### ISSUE THREAD

**Issue by jwshive** [lwouis/alt-tab-macos#1784]
**Describe the bug**

Microsoft Edge browser doesn't seem to show up in the apps list when using alt-tab. Safari will show up, but not edge. I have AltTab set to run on login and if I start a browser after logging in, AltTab doesn't see it. If I close AltTab, open a browser and then reopen alttab, it will show the browser properly.

**Steps to reproduce the bug**

1. Install Edge and AltTab
2. Set AltTab to run at login
3. Restart
4. Open Edge
5. Use AltTab, edge is not found.
6. Close AltTab, leaving browser open
7. Restart AltTab
8. Browser shows up

Using AltTab 6.46.1 and MacOS 12.4

Please let me know if there are any other details you need.

**Comment by lwouis** [comment]
I would guess it's #1324

* What happens if i follow the exact steps you shared above, with Chrome?
* When Edge starts, does it restore previous windows/sessions? On which Space are the windows?

**Comment by tkaufmann** [comment]
Same for Sublime Text and Typora.

**Comment by lwouis** [comment]
Most likely #1324
