### ISSUE TITLE
Preference pane jumps around

### ISSUE THREAD

**Issue by ezity** [lwouis/alt-tab-macos#179]
Currently, the preference pane drastically changes size on every pane. This is (in my opinion) bad UI. 

For comparison, the preference pane for Safari.app only changes height and not width when switching between panes. Safari.app also uses a nice scrolling transition, but that is not necessary.

**Comment by lwouis** [comment]
Hi @ezity! Thank you for the feedback!

Regarding your perception that this is bad UX: I think it's a trade-off. If you resize dynamically, then the preferences panel always fit the content, meaning the window doesn't take more space than needed which is a plus. On the flip-side, the resizing can be a bit distracting. One could argue it is eye-candy as a plus also. The same way many of the animations in macOS are unnecessary and a detriment to UX, but serve marketing / first impressions.

Some facts:

* Safari does actually resize horizontally. On my laptop, it is quite a small difference, but the Extensions tab is wider and animate the same way AltTab does.
* Other apps resize. I use Bartender and it does resize a lot.
* I used a `NSTabViewController` to achieve the preference panel. This component is surprisingly messy in terms of API and has numerous quirks and oddities. During implementation I was very frustrated and looked online for support, only to find [the top Preferences pod](https://github.com/sindresorhus/Preferences) [explain why they had to build a library for something supposedly trivial](https://github.com/sindresorhus/Preferences#why-should-i-use-this-instead-of-just-manually-implementing-it-myself).

Overall, I'm not convinced that there is an issue here. I would like to hear stronger argumentation than "This is (in my opinion) bad UI". At the same time, I'm not overly attached to the current animation, so it would want to raise a PR, I'll merge it.

**Comment by ezity** [comment]
> Safari does actually resize horizontally. On my laptop, it is quite a small difference, but the Extensions tab is wider and animate the same way AltTab does.

You are correct, I did not notice that.

> At the same time, I'm not overly attached to the current UX, so if you want to raise a PR, I'll merge it no problem.

I'll let you know. I am currently a student and just getting started with more advanced programming, so I would like to contribute if possible. However, this seems to be a messy project to get started on (based on what you have mentioned in the text about contributing), so I may want to start with something easier and come back to this later.
