### ISSUE TITLE
See tabs of Safari in AltTab just like in Windows 10/11 with MS Edge

### ISSUE THREAD

**Issue by Arnav-arw** [lwouis/alt-tab-macos#1790]
**Is your feature suggestion related to a problem? Please describe.**
Quickly changing tabs in Finder is very good. It would be a great quality of life improvement to get that feature for Safari. 

**Describe the solution you'd like**
Basically have an option for showing tabs of Safari (just like for Finder) in the preferences page. Also to avoid clutter, we can option to choose from showing only 3 tabs, 6 tabs or custom tabs.

**Comment by lwouis** [comment]
Please see https://github.com/lwouis/alt-tab-macos/issues/1755#issuecomment-1173111180
