### ISSUE TITLE
⌘ + ^ not working as a shortcut for switching between windows of active app

### ISSUE THREAD

**Issue by Ben9000** [lwouis/alt-tab-macos#1791]
I tried setting ⌘ + ^ as  "shortcut 2" for switching between windows from the active app.
The keyboard shortcut is not being used by any other app.
But nothing happens when I do the shortcut. When I change it to something else e.g. ⌘ + ⌥ + ö it works.

![CleanShot 2022-07-17 at 11 39 31@2x](https://user-images.githubusercontent.com/41483574/179392590-3a78c5e2-f371-43d4-949a-784aa36c1bc4.png)

**Comment by XInTheDark** [comment]
What macOS version are you using?
On macOS Monterey this works fine.

**Comment by lwouis** [comment]
Probably some issue with non-US keyboard? Which keyboard do you use? What's the physical layout? What's the language you set at the software level in macOS?

See https://github.com/lwouis/alt-tab-macos/issues/1190

**Comment by lwouis** [comment]
@Ben9000 any update? Without the info I mentionned above, this ticket is unactionable.

**Comment by SumWunSpeshal** [comment]
I think I can respond on @Ben9000's behalf, given that his alternative shortcut contains an 'ö' which would suggest that he's from Germany just like me and I have the same issue. 

So, ...
- German QWERTZ keyboard layout (and physical layout would be ISO)
- German is also the selected system language across the OS
- macOS Ventura 13.0
- have tried disabling Karabiner Elements with no luck. 
- same issue regardless of external or built-in Macbook keyboard.

The QWERTZ layout has the key for ^ and ° above the Tab-key. So Option+^ is probably the shortcut @Ben9000 was going for. 

Hope that helps. Thank you for your great work. Really love Alttab so far.

**Comment by lwouis** [comment]
International keyboard have received more support in the latest version. Please try it out.

I'll close this ticket for now. Please feel free to share additional information if some issue still happens, and we can re-open the ticket

**Comment by SumWunSpeshal** [comment]
@lwouis just updated. works great now. Thank you so much 👍
