### ISSUE TITLE
Don't show minimized applications

### ISSUE THREAD

**Issue by mfn** [lwouis/alt-tab-macos#180]
HyperSwitch (HS) has the behaviour then it does not show minimized applications.

I miss this as I minimize applications a lot to remove clutter from my screen and I don't want to see them in AltTab either.

**Comment by lwouis** [comment]
> HyperSwitch (HS) has the behaviour then it does not show minimized applications

I seem to remember that it does, but only in "show windows from active app" mode.

In any case, this use-case, as well as many others, will be supported in the next release. The [next release](https://github.com/lwouis/alt-tab-macos/milestone/1) focuses on keyboard shortcuts.

Here is what the UI will look like: 

![image](https://user-images.githubusercontent.com/106195/74341746-91faaf80-4deb-11ea-915a-d08e0863476a.png)

See how it will be easy to decide what the shortcut should show.

Note that i'm currently blocked to deliver this release by the lack of support in the ShortcutRecorder library. You may want to [upvote that ticket](https://github.com/Kentzo/ShortcutRecorder/issues/114) or discuss with the author as he mentioned that he may do it quick for some fee.
