### ISSUE TITLE
Update for macOS Ventura's Stage Manager

### ISSUE THREAD

**Issue by maestroDever** [lwouis/alt-tab-macos#1800]
**Is your feature suggestion related to a problem? Please describe.**
macOS Ventura has introduced a feature called ["Stage Manager"](https://www.apple.com/macos/macos-ventura-preview/features) and basically, it manages opened windows by grouping them and putting non-focus apps on the left-hand side of the screen. When you minimize a window with the Stage Manager enabled, the window goes to the side of the screen instead of to the Dock. And AltTab still shows those windows as tilted and faded out, even when you select the "Hide minimized windows" option on the Controls tab.

**Describe the solution you'd like**
As for the Ventura and Stage Manager, minimized windows now have a different look and state. It'd be great if any upcoming updates of AltTab have an experimental feature of "Supporting macOS Ventura" until the official release of Ventura comes this fall.
And this feature should identify and treat minimized apps on the Stage Manager as it used to do before, and users should be able to hide them or show them.

**Comment by lwouis** [comment]
I'll look into Ventura updates when it goes live. This is in an effort to be efficient with my time (see #1179)
