### ISSUE TITLE
[Feat] Add option to support sorting windows by space numbering

### ISSUE THREAD

**Issue by XOR-op** [lwouis/alt-tab-macos#1801]
**Is your feature suggestion related to a problem? Please describe.**
I'm working with a lot of spaces, each with serveral windows open. And I always select "All apps" and "All spaces" in order to switch between apps in different spaces, e.g. from Chrome in space 1 to Terminal in space 4. With 15-25 windows open, it's hard to find the window I want to switch to. Especially in the current dynamic order, I'm struggling to find it without a fixed or nearly fixed position. I have read the [issue 515](https://github.com/lwouis/alt-tab-macos/issues/515), and I don't think my need can be resolved in your suggestions (select active app/space/monitor option). 

**Describe the solution you'd like**
It's still ok to keep current policy for windows within the same space. However, for windows in different spaces, they should be relatively separate just by space. The current layout is the following:

| Chrome 2 | Terminal 4 | Vscode 1 | Chrome 2| Terminal 1|
|---|---|---|---|---|

I hope it can be sorted into:

| Vscode 1 | Terminal 1|Chrome 2| Chrome 2 | Terminal 4 | 
|---|---|---|---|---|

It's way more easy to navigate. It's not only relatively static, but also able to keep the advange of using last focus time. I think more people will perfer a (relatively) static layout instead of a dynamic one. And I believe that, if users choose to use multiple spaces, they will group windows for similar windows in a space. Even if one window is never focused (for example, a document just for reading in right half of the space), it will help user easier to navigate.

**Describe alternatives you've considered**
I don't think there are viable alternatives now. And adding one option won't break habits of current users. There are lots of similar issues there, e.g. [issue 1527](https://github.com/lwouis/alt-tab-macos/issues/1527) and [issue 337](https://github.com/lwouis/alt-tab-macos/issues/337), and I have read them. The need for a better order exists. Thanks for your reading and look forward to your opinion.

**Comment by lwouis** [comment]
There is #515 #378 and as you pointed out #337.

We can implement sorting by Space then by window order within one of those existing tickets. Closing as duplicate, to keep efforts focused.
