### ISSUE TITLE
Add option for the position of the windows to remain static

### ISSUE THREAD

**Issue by orlov-n** [lwouis/alt-tab-macos#1807]
**Is your feature suggestion related to a problem? Please describe.**

Everyone keeps asking the developer to add this, but the developer does not seem to understand what is being asked, which is obvious from the comments when the issue is closed without a fix.  

Current app behavior is to always change position of the windows depending on how recently they were switched to.  This behavior makes it impossible to remember the location of each window and quickly find it.  This is extremely frustrating for the user when the user has more than just a few windows open.  Some users can easily have 20-40 windows open at any time.

**Describe the solution you'd like**
Please add the option to switch AltTab from current behavior to the requested behavior.

Current behavior:
User launches app A it goes to position 1.
User launches app B it goes to position 1 and app A moves to position 2.
User launches app C it goes to position 1, app B moves to position 2, app A moves to position 3.
User switches to app A, app A moves to position 1, app B moves to position 3, app C moves to position 2.

Requested behavior:
User launches app A it goes to position 1.
User launches app B it goes to position 2 and app A remains at position 1.
User launches app C it goes to position 3, app B  remains at position 2, app A remains at position 1.
User switches to app B, app B remains at position 2, app A remains at position 1, app C remains at position 3.

**Comment by lwouis** [comment]
Changing the sorting order of the windows is covered by #515
