### ISSUE TITLE
Brave Browser not showing

### ISSUE THREAD

**Issue by Promax8** [lwouis/alt-tab-macos#1808]
I recently installed Alttab and my Brave Browser Windows are not showing. I tested other browsers like safari and they work completely fine. I have no clue on how to fix this. 

**Screenshots / video**

<img width="909" alt="Screenshot 2022-07-24 at 01 01 24@2x" src="https://user-images.githubusercontent.com/91149120/180625561-e0c24da3-be84-49e8-93ea-277cdbb7bfe5.png">

**Steps to reproduce the bug**

1. Open Brave Browser
2. Doesnt show up

**Comment by Promax8** [comment]
I closed and reopened alttab and it works now :/ Sorry

**Comment by lwouis** [comment]
Most likely #1324
