### ISSUE TITLE
Stops working when Octave-app runs

### ISSUE THREAD

**Issue by KejPi** [lwouis/alt-tab-macos#182]
When Octave-app runs Alt-Tab stops working - shortcut does nothing, clicking on Alt-Tab icon shows busy cursor. It resumes when Octave application is closed. 
This problem is in version 3.x.x (tested latest 3.1.3 and also 3.0.5). I had to downgrade to 2.3.4 that works.

**Comment by lwouis** [comment]
I was able to reproduce the issue with Octave 4.4.1. I see that the `AXObserverAddNotification` calls fail and return `kAXErrorCannotComplete`. This explains why the Octave window is not shown in AltTab, but not why AltTab stops responding quickly and behaves strangely.

**Comment by lwouis** [comment]
Octave.app is pretty Frankenstein'y. You can tell it's a port and not a native mac app. In Activity Monitor, it looks like this:

![image](https://user-images.githubusercontent.com/106195/77420618-bb0c5800-6e0d-11ea-9822-6ab7f08306e5.png)

From a technical perspective, one of these processes bundle ID "org.octave-app.Octave" and never answers the `AXObserverAddNotification` call. I will blacklist it for now. The other process `octave-gui` with bundle ID `nil` answers the call correctly, and we can get Octave.app's windows from it.

Looking into this issue outline a bug in AltTab's `AXObserverAddNotification` retry logic. I'll try to fix it. It's pretty complex as it involves multi-threading.

I'll deliver a fix that fixes this bug, but also blacklists the bogus "org.octave-app.Octave" process that we know to never respond. I also opened a ticket on Octave.app repo so they can fix their issue 👍

**Comment by lwouis** [comment]
I just released v3.2.1 which should fix this issue. I suggest updating to it using the built-in update button:

![image](https://user-images.githubusercontent.com/106195/77505142-ae3b4300-6ea5-11ea-8f60-61493ed736c1.png)

You can also [download it manually here](https://github.com/lwouis/alt-tab-macos/releases/latest).

Let me know if that fixes your issue! 👍

**Comment by KejPi** [comment]
I can confirm it works as expected now. Thank you for this great application!
