### ISSUE TITLE
keyboard shortcuts not working at all

### ISSUE THREAD

**Issue by romainguinot** [lwouis/alt-tab-macos#1820]
**Describe the bug**

I'm fairly new to MacOS. Using Monterey 12.4. Alt Tab 6.46.1. M1 macbook pro.
Configured shortcuts for Shortcut 1 (tried different ones as well). Alt Tab doesn't display at all using the keyboard shortcut. Only shows when clicking on the alt tab icon in the top tray and clicking "Display". 

**Steps to reproduce the bug**

1. Install Alt Tab
2. Preferences > configure a shortcut for shortcut 1, for example option + tab (default) or option +@ (any other key really
3. quit prefs and press the shortcut
4. Nothing happens
5. click the alt tab icon in the top tray, then display. Alt Tab then displays normally. 

I am guessing at this stage that there's probably something i'm not grasping.

**Comment by lwouis** [comment]
* Are you using an external keyboard?
* What's the physical key layout?
* Are you using another language than English (called Input Source in macOS).
* Can you try more shortcuts and see if they work?
* If you reset the preferences (in the first tab), do the default shortcuts work when pressed? (Command+tab and command+[key above tab]

Finally, your name seems French, maybe you're experiencing the issue discussed in #1589

**Comment by romainguinot** [comment]
Hi,

Thanks for your reply. Yes it's been fixed although i'm not sure what did it. tried a bunch of different shortcuts before finding one that worked. what's odd is that finding one that worked unlocked the ability to configure shortcuts that weren't initially working. a bit weird but anyways it's sorted .
