### ISSUE TITLE
Possibility to change windows by pressing numbers

### ISSUE THREAD

**Issue by luchian94** [lwouis/alt-tab-macos#1824]
**Is your feature suggestion related to a problem? Please describe.**
When I need to switch to an app which is in further position I have to press Tab multiple times or select it with mouse.

**Describe the solution you'd like**
It would be nice to have the possibility to switch apps using number keys (1-9), this way you can switch much faster.
Maybe also add numbers as icons.

**Describe alternatives you've considered**
Another way could be using first letter of app name to switch. So for example if Skype is open you could just open AltTab and then just press "S" to switch to it.

**Comment by lwouis** [comment]
Please see existing tickets: #210 #590
