### ISSUE TITLE
Enhancement: display title above or under the icon

### ISSUE THREAD

**Issue by Yv-vY** [lwouis/alt-tab-macos#1827]
I'm using Alt-Tab to circumvent an issue with windows selection of application (Cmd + `) that basically change position on the keyboard when using a different keyboard layout (here FR).

Alt-Tab allows me to have a physical key mapped to the shortcut instead of the character, which is great.

However as the only thing I want to override is switching windows within a given application, I'm looking for getting a similar look and feel as what's available by default.

For this I've:
* hidden window thumbnails
* set icon size to 128 px
* set window min and max size to 15%

This gives me something approximating the system default within app window switching, however the title is displayed to the left of the icon and cut short.

It would be great to have the option to display the title below the icon (and possibly above too) to support this use case.

Thanks for your great work :)

**Comment by lwouis** [comment]
I see exactly what you mean. It's one of the next (very) large ticket i would love to do (but #1179...). Please see #351 where we discuss how to move from many sliders that are hard to make sense of, and can actually be set to contradict each other by mistake, to something more mainstream where the "horizontal line of icons" from macOS would be one of the 2 or 3 presets.

**Comment by ADTC** [comment]
Hi @lwouis is this something that would be included in the near future?
