### ISSUE TITLE
Question: What does "show standard tabs as windows" do??

### ISSUE THREAD

**Issue by XInTheDark** [lwouis/alt-tab-macos#1839]
In preferences, I am confused about what `show standard tabs as windows` does.
<img width="238" alt="image" src="https://user-images.githubusercontent.com/61100393/182849245-2f3ae782-ab38-48fb-8ffe-e98419b05476.png">

I originally assumed that it was an option to show different tabs in the same window as separate window thumbnails; however after enabling the option, my Safari tabs still show as one window.

Just curious about what this option actually does.

**Comment by lwouis** [comment]
Your assumption is correct. What you missed to understand the feature is the word "standard" in the label.

An app can push pixels to the screen in a custom way. Like a video game can have a UI with windows and tabs. No way for AltTab (or a screen reader) to know about such tabs. It's the same for Safari here. Safari uses custom drawing of tabs.

Some other apps like Finder or Terminal use AppKit, the recommended way/toolkit to draw windows and tabs on macOS, to draw their tabs. For these apps, checking that box in AltTab's preference will work as you described.

**Comment by XInTheDark** [comment]
> Your assumption is correct. What you missed to understand the feature is the word "standard" in the label.
> 
> An app can push pixels to the screen in a custom way. Like a video game can have a UI with windows and tabs. No way for AltTab (or a screen reader) to know about such tabs. It's the same for Safari here. Safari uses custom drawing of tabs.
> 
> Some other apps like Finder or Terminal use AppKit, the recommended way/toolkit to draw windows and tabs on macOS, to draw their tabs. For these apps, checking that box in AltTab's preference will work as you described.

Thanks for the clarification :)
