### ISSUE TITLE
Poor quality of thumbnail images

### ISSUE THREAD

**Issue by peterpp** [lwouis/alt-tab-macos#1841]
**Describe the bug**

Quality of thumbnail images is quite poor. It looks like the nearest-neighbour algorithm is used for scaling images.

**Screenshots / video**

![Screen Shot 2022-08-05 at 15 16 09](https://user-images.githubusercontent.com/1448883/183085244-6f847767-bf6b-4f23-97c4-d01f74589cc0.png)

Device: MacBook Pro 2021 (M1 chip)
OS: macOS 12.5

**Comment by lwouis** [comment]
Please see this open PR when we discussed the options and technical trade-offs: [#quality](https://github.com/lwouis/alt-tab-macos/pull/705)

Nothing really great has come up yet, and the PR author has stopped updating the PR, unfortunately.

**Comment by peterpp** [comment]
Thanks for the link, I understand the performance issue here.
