### ISSUE TITLE
mac13 bate5 Open No Response

### ISSUE THREAD

**Issue by each1026** [lwouis/alt-tab-macos#1853]
![ ](https://s2.loli.net/2022/08/10/IUtY7eXgVHbcC3w.png)

Steps to reproduce
The app opens and is stuck directly on unresponsive

After Task Manager was forcibly disabled, the system's own toggle was also disabled. How can I use the toggle app that comes with the system at this stage?

**Comment by hlxxzt** [comment]
a temporary solution

to move AltTab to the non /Applications directory and run it again.

**Comment by lwouis** [comment]
Duplicate of https://github.com/lwouis/alt-tab-macos/issues/1852
