### ISSUE TITLE
Send feedback, fill in the email address, it seems that the email does not receive a reply

### ISSUE THREAD

**Issue by GanZhiXiong** [lwouis/alt-tab-macos#1856]
![image](https://user-images.githubusercontent.com/27394631/183979027-7a078a9c-4088-43c4-8d54-35ab7b0dc8d3.png)

**Comment by lwouis** [comment]
I'm sorry, i couldn't understand your ticket. Are you facing an issue, or suggesting an improvement? Could you explain with more details?

**Comment by GanZhiXiong** [comment]
I just tested it. There's no problem. Sorry.
you can close  https://github.com/lwouis/alt-tab-macos/issues/1857.
Thank you!
