### ISSUE TITLE
geany window now showing up in list of windows in AltTab

### ISSUE THREAD

**Issue by simonhf** [lwouis/alt-tab-macos#1858]
**Describe the bug**

I just upgraded my laptop from an Intel Macbook to an Apple Silicon Macbook. Installed Alt-Tab and it works except for the code editor 'geany' does not show up in the list of windows when pressing alt-tab. This worked on the old Intel Macbook with Alt-Tab but not the new Apple Silicon Macbook.

**Steps to reproduce the bug**

Note: I could only get geany to install on the M1 Mac by using the `+quartz` version using the following commands (the regular X11 version glitched on screen):

```
$ sudo port install gtk3 +quartz
$ sudo port install geany +quartz
```

Also another possible clue:

When not using Alt-Tab to switch, and using the regular Mac Tab switch then mysteriously geany shows up as this `exec` icon?!

![telegram-cloud-photo-size-1-5161173835402291944-y](https://user-images.githubusercontent.com/357158/184059050-c67a781c-d4c6-4db3-9ffd-b2f65ce9418a.jpg)

**Comment by lwouis** [comment]
The issues clearly come from this Geany app. Could you please get in touch with its authors?
