### ISSUE TITLE
Enpass App don't show up

### ISSUE THREAD

**Issue by mrc247-DE** [lwouis/alt-tab-macos#186]
The Enpass App (Password Manager) don't show up in the AltTab switcher (v3.2.1).

**Comment by lwouis** [comment]
Could you please show me a screenshot of which window doesn't show up in AltTab?

I just tried installing Enpass, and the main window is showing:

![image](https://user-images.githubusercontent.com/106195/77563744-05243500-6f05-11ea-9f80-bda42d4cbe4f.png)

![image](https://user-images.githubusercontent.com/106195/77563733-0190ae00-6f05-11ea-92ec-16d70d78111b.png)

**Comment by lwouis** [comment]
As I showed, Enpass shows correctly on my system. I'll close this ticket for now. If you don't see the window, please feel free to re-open this ticket! :)

**Comment by mrc247-DE** [comment]
it seems like it was a Mojave (macOS 10.14.6) issue. After I reported the error I updated to Catalina (10.15.4) and now the Enpass window is correctly displayed in alt-tab. But thanks for looking into all problems. :-)

**Comment by lwouis** [comment]
I wish I could downgrade to Mojave to test what's wrong there, but testing different versions of macOS is an unsolved problem. I wish it was easy to pop-up VMs.

**Comment by mrc247-DE** [comment]
With Parallels it is super easy to make a VM. I have a Mojave, a Catalina and a Windows 10 VM.
unfortunately Parallels is also very expensive ...
