### ISSUE TITLE
Replace the shortcut keys, the mouse wheel does not work properly

### ISSUE THREAD

**Issue by Hugo-Hsiao** [lwouis/alt-tab-macos#1860]
Replacing the AltTab shortcut option + tab with command + tab will cause the external mouse to use the scroll wheel to view the page, and the mouse scroll wheel cannot be used. Press the command key again to return to normal. I don’t know where the problem is?
My device: Macbook air m2 , mouse is: logi anywhere 3 mac

**Comment by lwouis** [comment]
I couldn't quite understand the issue you're describing. Could you try to list step by step, share a video, and explain in more details?

**Comment by Hugo-Hsiao** [comment]
@lwouis You can try it yourself, the shortcut key option + tab is replaced by command + tab, and an external mouse is used.

**Comment by lwouis** [comment]
Please explain the issue in more details. I don't understand the issue.
