### ISSUE TITLE
Option to only show window names and not contents if record screen permission is not granted

### ISSUE THREAD

**Issue by Arsoth** [lwouis/alt-tab-macos#1862]
**Is your feature suggestion related to a problem? Please describe.**
I know the app doesn't actually send anything, but having screen recording on can make corporate environments twitchy etc... especially when dealing with HIPAA.

**Describe the solution you'd like**
If the screen recording permission isn't granted, just have the window title inside or over a nondescript grey box; alternatively replacing the window contents with the app icon and keeping the title above it as it is now.

I'd love to use the app on my work mac, as it's super great (beats the windows alt tab by a LONG shot) but I don't want corporate security coming down on me like a ton of bricks!

**Comment by lwouis** [comment]
The Screen Recording permission is necessary for window titles. More info: https://github.com/lwouis/alt-tab-macos/issues/1069#issuecomment-894733741

Please see this existing ticket discussing what a "degraded mode" would mean: https://github.com/lwouis/alt-tab-macos/issues/1082
