### ISSUE TITLE
I dont know why is shows App with counter of (2) opened windows 

### ISSUE THREAD

**Issue by siempay** [lwouis/alt-tab-macos#1864]
Hi there and thank you for this nice project.

I just installed the latest version Version 6.46.1 and noticed that it does not show all opened windows.
Instead, it shows Apps with a counter of how many windows opened. 
Which is exactly what macOS does.

I was using this project for sake of being able to navigate to other opened Xcode windows in fullscreen mode without having to use the mouse.

Is there a param or something to disable this behavior, or what version was this introduced to I can go back to it

thank you

**Comment by lwouis** [comment]
> it shows Apps with a counter of how many windows opened

If you mean a red circle with a number in it, then no. The badges are the same as the Dock shows. For example, how many unread emails you have in Mail.app.

AltTab shows windows. It has from day 1 and it's the only thing it can do now, before we implement #337.

If you're not seeing all your windows, it's most likely that you're experiencing #1324
