### ISSUE TITLE
I want to select window in reverse order to use command + shift + tab key.

### ISSUE THREAD

**Issue by tiger-git-hub** [lwouis/alt-tab-macos#1866]
Thank you for providing such as excellent projects!

I have a request.
Could you implement that selects window in reverse order to use command + shift + tab key? ( Not only use tab key.)

If this function already provides by settings, please let me know.

**Comment by lwouis** [comment]
Yea it's already available. It's alt+shift by default, no tab.

you can customize it to shift+tab if you prefer, in Preferences > Controls

**Comment by tiger-git-hub** [comment]
@lwouis , thank you for replying!
Oh, exactly that "Select previous window" ( Writed on Japanese settings, "前のウィンドウを選択" )!!

I will continue to use AltTab;)
