### ISSUE TITLE
change the highlighted app color 

### ISSUE THREAD

**Issue by Bentzeh** [lwouis/alt-tab-macos#1867]
Im new in the mac world and i really like your app
its nice and simple so thank you for that

I do have a question
while i move between apps using 'tab' the highlighted app isn't pop into my eyes and i wondered if there's an option to change the color of the highlighted app?

**Comment by lwouis** [comment]
I recommend you use the Windows 10 theme in the Appearance tab in the Preferences

**Comment by Bentzeh** [comment]
not exactly what i had in mind but i guess it will work

thanks any way :)

**Comment by lwouis** [comment]
More context regarding what you had in mind (letting users change the color): https://github.com/lwouis/alt-tab-macos/issues/1019#issuecomment-869529376

**Comment by Bentzeh** [comment]
thanks
