### ISSUE TITLE
Group open windows in a similar manner to stage manager

### ISSUE THREAD

**Issue by simyanliang** [lwouis/alt-tab-macos#1870]
**Issue / Suggestion**
I usually have a bunch of windows open (I assume many other AltTab users do too, hence their need for this), and am usually working on multiple work streams at one time. I'd like to be able to group them based on what I'm working on. I know that I can move associated windows to other spaces, and set AltTab options to only show from one space, but then I would not have a bird's eye view of all that is going on in a structured way (I know I can still see all windows across all spaces). This would be a similar concept (not implementation) to stage manager except it's really not that organized in its current design.

Here is an example of my current work streams (please ignore the CleanShot X windows, those were created when taking the screenshot):
1) Red: My tools such as texts.com and cron calendar - Would be nice to just keep them all at the top or bottom as a group. I would include Spotify in this too.
2) Blue: Alaska trip planning across multiple windows
3) Green: Job searching for roles on Linkedin

![CleanShot 2022-08-14 at 12 31 59](https://user-images.githubusercontent.com/39843511/184546310-c519df67-e97e-44a8-bf8b-721cf5e0e507.png)

**Potential Solution**
It would be great to keep these as grouped per row on the AltTab screen like this. Perhaps it would be to have the ability to create container groups (not unlike Tab groups in chrome), and then you can drag and drop windows into these groups as a home. It would also remember the group home in case mac is restarted.

![CleanShot 2022-08-14 at 12 51 21](https://user-images.githubusercontent.com/39843511/184546947-5abc0f21-2179-48dc-93b6-668ea750ccd8.png)

This could be one option to be used with shortcut 1 and then the normal universal view (with all windows across all spaces) on shortcut 2. Thanks for the consideration!

**Comment by lwouis** [comment]
I think such workflow is extremely close to what is discussed in #337

**Comment by simyanliang** [comment]
I believe #337 refers to sorting windows by app name, but my request here is to group by workflow, and each group may contain only one app type (say multiple chrome windows), or windows of multiple apps (chrome window, excel window etc.).

**Comment by lwouis** [comment]
No, #337 goes beyond and touches on grouping visually. It could be [this style](https://github.com/lwouis/alt-tab-macos/issues/337#issuecomment-639307626), or it could be something like what you drafted above.

It's about grouping + drilldown, which your issue touches on as well. You didn't mention drilldown, but if you start actually thinking about how to use the UI you suggested, it may quickly come up that you need a way to switch from group to group, then inside move around the various windows. Also how does it scale when someone has like 12 of such groups. Then the [solution from Linux desktops](https://github.com/lwouis/alt-tab-macos/issues/337#issuecomment-639307626) may be more compact / UX friendly.

The grouping could be by app, but also by Space which could be a way to have the "stage manager" experience you show on your screenshot. Could be other things even. The other tickets is quite broad.
