### ISSUE TITLE
Setting an option in the "ban list" is not displayed

### ISSUE THREAD

**Issue by Tinyu-Zhao** [lwouis/alt-tab-macos#1876]
**Describe the bug**

Set the first of the three options in the "ban list" to be clear, with no text

**Screenshots / video**

<img width="565" alt="image" src="https://user-images.githubusercontent.com/44396641/184792152-2902b4b6-76a3-49ed-98c4-b566d4fba460.png">

**Comment by lwouis** [comment]
This is not a bug. There are 2 types of blocking, thus 2 columns. The user may want to pick an option in column 1, but no option in column 2, for example.

You can see that with the default values. All of them use column 1 or column 2.

So this is working as expected, unless I didn't understand your issue. In which case, please explain it in more details.
