### ISSUE TITLE
Windows Theme not highlighting thumbnails

### ISSUE THREAD

**Issue by gingerr** [lwouis/alt-tab-macos#188]
v3.2.1

The macOS Theme highlights thumbnails but the Windows theme does not do it anymore.

**Comment by lwouis** [comment]
Hi @gingerr! I think I broke the live nature of some preferences during the new layout rework.

I think on the next restart, the windows theme will apply for you. That being said, I will release a fix to the preferences to make them properly apply live again!

**Comment by lwouis** [comment]
I just released v3.3.0 which fixes that. I hope you enjoy! 👍

Feel free to open a ticket if you have any issue with the new version
