### ISSUE TITLE
Finder always included in the alt tab list?

### ISSUE THREAD

**Issue by theory18** [lwouis/alt-tab-macos#1882]
I see that you can blacklist apps, and finder is already added, i set the option to always, but finder still remains in the alt tab list, i removed finder and added it again, still same issue. Is this a known problem? Or is this not what this feature is supposed to do? I would like to exclude finder from my alt tab list.

Running on Macbook Pro M1 14'
macOS Monterey v12.5

**Comment by lwouis** [comment]
Please share a screenshot of your Preferences? I think you're doing something wrong. I just tested on my machine, and it works properly.
