### ISSUE TITLE
Using alt tab shows individual apps and not individual windows

### ISSUE THREAD

**Issue by LargeProfessor** [lwouis/alt-tab-macos#1888]
When using alt-tab, it does not show the individual windows but only the active apps. 

Not sure if it is really like this or not as I have seen in videos that alt-tab shows each individual window.

Note: I'm using the correct shortcut and even changed the shortcut from option+tab to command+tab. 

<img width="1440" alt="Screen Shot 2022-08-20 at 11 13 18 PM" src="https://user-images.githubusercontent.com/111646542/185750617-ce1282b9-4abd-46b9-b678-c641f74365bb.png">

(Screenshot for reference) (note that there are 3 tabs in safari open when the screenshot was taken but only shows one safari app when using alt tab) 

if this issue was resolved already, I would appreciate a reference. Thank you

**Comment by lwouis** [comment]
AltTab shows windows, not tabs. It can show *standard tabs*, if you check the preference. Standard tabs are tabs drawn using the official macOS API (AppKit). Example of such apps with standard tabs: Finder and Terminal.

Safari and all other browsers use custom tabs. That is, they draw custom components and AltTab has no technical way to understand those as tabs and get a screenshot of them.
