### ISSUE TITLE
Update Homebrew cask formula for auto-updates

### ISSUE THREAD

**Issue by ezity** [lwouis/alt-tab-macos#190]
As specified in the [cask language reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/all_stanzas.md#optional-stanzas), the cask formula should use `auto_updates true`.

As I understand, this will prevent it from being erroneously marked as outdated when I run `brew cask outdated` on my end.

**Comment by lwouis** [comment]
Hi @ezity! Thank you for pointing this issue out! I [opened a PR](https://github.com/Homebrew/homebrew-cask/pull/79347) to the homebrew repo to correct that.

**Comment by lwouis** [comment]
The PR was merge, so I'm closing this ticket 👍
