### ISSUE TITLE
Minimized windows should shift to the end of the list

### ISSUE THREAD

**Issue by heaven** [lwouis/alt-tab-macos#1900]
Every time I minimize a window it stays on the first position in the window list so next Alt+Tab brings the window back. To work around this I currently have to use Cmd+W to get rid of the windows I don't need.

Minimized windows can shift to the end of the list, which would solve the problem and improve the UX.

As an alternative there could be an option to hide minimized windows but that's not a complete replacement of the original feature.

**Comment by lwouis** [comment]
This is already supported. You can change the preferences as such:

![Uploading image.png…]()

**Comment by heaven** [comment]
Whoops, I swear I've been looking for this in the settings multiple times... 🤦‍♂️
