### ISSUE TITLE
Difficult to see which window is selected on dark background

### ISSUE THREAD

**Issue by heaven** [lwouis/alt-tab-macos#1901]
I use white MacOS theme but my IDE is configured to use a dark background in the editor. When switching between windows it is difficult to see which one is selected when on a dark background.

Here's an example
<img width="1373" alt="Screenshot 2022-08-24 at 18 16 57" src="https://user-images.githubusercontent.com/126732/186470634-63941b12-6bb2-484f-900b-3ba27f4c23dc.png">

An ability to change the selection color would solve the problem.

**Comment by lwouis** [comment]
This has been discussed in details in a few tickets. Please see my 2 comments here: https://github.com/lwouis/alt-tab-macos/issues/1867

**Comment by heaven** [comment]
@lwouis I see. The fact that this many similar tickets were open clearly shows there's a UX problem. I tried Windows theme but it looks odd. I think having a light Mac OS theme that would look similar to the native one would be a great solution, even if it's not as well rendered as the native one. The native switcher has a good color scheme that works in both dark and light environments (except the font, which is hardly readable).

**Comment by lwouis** [comment]
Please read https://github.com/lwouis/alt-tab-macos/issues/82#issuecomment-577480530
