### ISSUE TITLE
Not showing applications that are started hidden

### ISSUE THREAD

**Issue by bernardjoseph** [lwouis/alt-tab-macos#1906]
**Describe the bug**

Applications that are started hidden on the terminal are not showing in the switcher list until there are unidden.

**Steps to reproduce the bug**

1. Start the terminal.
2. Start an application hidden, e.g. open -ja Mail.
3. The Mail application is not shown in the list.
4. Launch the Mail application with the mouse from the dock and hide it again.
5. Now the Mail application is shown in the list.

**Comment by lwouis** [comment]
I was able to reproduce this issue.

The windows show if you check the checkbox in `Preferences > Appearance > Show standard tabs as windows`. This shows that AltTab doesn't show these windows as it flags them as tabbed. The way AltTab detects tabs is a fragile heuristic that seems to break here. I'm not sure anything can be done here. There is no nice API to get the right info about such windows. We have to use private APIs and tricks to get something decent for the user.

I'm afraid launching apps hidden is niche, and I don't have a technical workaround to support it. That makes it difficult to move forward and fix. Of course, I would welcome a PR if anyone has an idea/approach.
