### ISSUE TITLE
show all windows that are in the current space

### ISSUE THREAD

**Issue by nikoloz110** [lwouis/alt-tab-macos#1909]
basically the same what mission control does. tried all combinations of preferences but nothing seems to work like that.  is it not possible or am I missing something, or maybe it's a bug?

**Comment by nikoloz110** [comment]
apparently there was a bug, where you need to restart altTab, on the same screen where you want it to work.
closing issue

**Comment by lwouis** [comment]
@nikoloz110 please see why this is happening here: #1324
