### ISSUE TITLE
Works only in the space where you launched altTab

### ISSUE THREAD

**Issue by nikoloz110** [lwouis/alt-tab-macos#1910]
**Describe the bug**
I will provide an example
When I launch AltTab on space N3, it works fine, then if I switch to space N2, altTab shows the windows that are on N2 but **only** if the application is open in space N3. if there are Spotify and chrome on space N2, altTab will only show chrome windows, since space N3 has chrome open, and no Spotify there. To fix it, I can quit altTab, and open it in N2, and everything works fine, but only for N2.
System: macOS 12.2 Intel Mac (2017 macbook pro), 
altTab version: 6.46.1

**Comment by lwouis** [comment]
I think you observed the issue of the pinned issue: #1324
