### ISSUE TITLE
Don't show up when switching quickly

### ISSUE THREAD

**Issue by MilanVarady** [lwouis/alt-tab-macos#1914]
Often times I'm switching between two apps, I quickly press cmd+tab and release it immediately. I don't look at what I'm switching to because I know it. The default mac cmd+tab doesn't show up in this case, but alt tab does show up for a split second, which is kind of annoying.

An easy solution would be to wait for a very short amount of time before showing the alt tab overlay, so if I just want to quickly cycle between two apps it doesn't flicker.

**Comment by lwouis** [comment]
This feature is already in the app in Preferences > Appearance. You can set the delay there.

**Comment by MilanVarady** [comment]
Oh... then I'm just blind. Sorry for bothering.
