### ISSUE TITLE
Discord updater shown constantly

### ISSUE THREAD

**Issue by maticboncina** [lwouis/alt-tab-macos#1924]
**Describe the bug**

Sometimes when Discord is opened, the Discord updater process (empty window) is also included in alt-tab permanently until the mac is restarted after the Discord upgrade. The updater shouldn't be displayed as the normal macOS command tab doesn't recognize it. 

**Screenshots / video**

I do not have screenshots at the moment. So I have reproduced how it looks.

The actual size/height of a window is an orange box and the name is corrected to what it shows. 

![CleanShot 2022-09-04 at 18 54 57](https://user-images.githubusercontent.com/54638868/188324762-8c308091-c3fe-4c37-b78f-46c1d6422dca.jpeg)

**Steps to reproduce the bug**

1a. Wait for Discord to try updating or during launch sometimes the updater remains in the alt-tab permanently until restart. 
1b. You will need to restart the Mac to get rid of it. Killing Discord doesn't work.

**Comment by lwouis** [comment]
I don't understand what's displayed on the screenshot, so I'm not sure what to make of it.

Discord is an electron app. It's possible that they don't close this particular window, but instead hide it, or find another trick to not have it visible (e.g. opacity 0, size 0px, etc). It's most likely an issue on Discord's side.

Could you please contact them to see what they make of this issue?
