### ISSUE TITLE
Some apps don't show in alt tab

### ISSUE THREAD

**Issue by maticboncina** [lwouis/alt-tab-macos#1925]
**Describe the bug**

If the app is automatically opened before Alt-tab (via startup agents), the alt-tab doesn't recognize it. Sometimes alt-tab just doesn't start as the first app.

**Screenshots / video**

There is no screenshot since in such a case the app simply isn't shown in the alt-tab switcher. 

**Steps to reproduce the bug**

1. Get an app to autostart before alt-tab

**Comment by lwouis** [comment]
This is discussed in other tickets: #447 #1324
