### ISSUE TITLE
SnagIt causes extra windows 

### ISSUE THREAD

**Issue by bradhs** [lwouis/alt-tab-macos#1926]
SnagIt causes extra windows to pop up.  They appear as "Floaty" in SnagIt App Expose.

Open SnagIt, do a couple screen grabs.  Then use Alt Tab to view applications to switch to.

<img width="1197" alt="image" src="https://user-images.githubusercontent.com/51719730/188355551-2bf94f85-e41d-4a18-ac84-99d9c1f3341a.png">
<img width="1462" alt="image" src="https://user-images.githubusercontent.com/51719730/188355509-66e21270-c6a5-4aa3-86d5-e1d4c187f456.png">

**Comment by bradhs** [comment]
Appears to be a bug in SnagIt: https://support.techsmith.com/hc/en-us/community/posts/360076040211-Mysterious-Floaty-tasks?page=1#community_comment_8927019384461

Is there any way to hide windows named "Floaty"?  I tried hiding Snag It but did not seem to work.

**Comment by lwouis** [comment]
Please use the blacklist feature to not show windows from SnagIt. You can't hide windows by name, but you can hide windows from that app.

**Comment by bradhs** [comment]
The issue is I want the SnagIt app, I just don't want the Floaty windows rendered.  I've reached out to TechSmith and they are researching a code change to hide those "floaty" windows.

It would be nice to blacklist a specific window name.

**Comment by lwouis** [comment]
@bradhs it would be niche. Very few people need that. This app should be fixed to not need this blacklisting in the first place. Finally, another issue with blacklisting windows by name is that names are localized in various languages.

**Comment by bradhs** [comment]
> @bradhs it would be niche. Very few people need that. This app should be fixed to not need this blacklisting in the first place. Finally, another issue with blacklisting windows by name is that names are localized in various languages.

Yep, working on that with them.

**Comment by greg-tdev** [comment]
@bradhs - could you link to the snagit issue if one exists? I, and maybe others, could add our votes to help resolved this with TechSmith. It's been bugging me as well.

**Comment by brakedalen** [comment]
> > @bradhs it would be niche. Very few people need that. This app should be fixed to not need this blacklisting in the first place. Finally, another issue with blacklisting windows by name is that names are localized in various languages.
> 
> Yep, working on that with them.

Could you please link to TechSmith issue? I have the same issue, and this is extremely irritating! Want to help by making some noise 👍

**Comment by bradhs** [comment]
This is the TechSmith Support issue: https://support.techsmith.com/hc/en-us/community/posts/360076040211-Mysterious-Floaty-tasks?page=1#community_comment_8927019384461

I also emailed their support a few months ago.  I requested an update from them just now.

I'm on SnagIt Version 2023.0.1 (98207)
