### ISSUE TITLE
Microsoft Edge doesn't show 

### ISSUE THREAD

**Issue by eschiebel** [lwouis/alt-tab-macos#1937]
**Describe the bug**

the popup window when pressing the opt-tab hot-key does not include Microsoft Edge

<img width="1269" alt="Screen Shot 2022-09-09 at 8 42 27 AM" src="https://user-images.githubusercontent.com/9463749/189352705-12339904-0406-40f6-b16d-975d832442c5.png">

As you can see in the screenshot, I am entering this bug report in Edge, which does not appear in the alt-tab window.
It used to. I was recently updated to Version 6.46.1

**Steps to reproduce the bug**

1. launch Microsoft Edge
2. type opt-tab
3. notice the alt-tab popup does not include Edge

**Comment by lwouis** [comment]
Most likely #1324
