### ISSUE TITLE
Spotify window preview does not show after minimised

### ISSUE THREAD

**Issue by XInTheDark** [lwouis/alt-tab-macos#1939]
When the Spotify app window is minimised in the app switcher window, its preview thumbnail suddenly disappears.

**Screenshots**

Before being minimised:
<img width="182" alt="image" src="https://user-images.githubusercontent.com/61100393/189485324-60fa96a2-52c6-4d5c-a499-7a3fb9c2be56.png">

After being minimised:
<img width="187" alt="image" src="https://user-images.githubusercontent.com/61100393/189485350-23cb9d9c-b7af-409a-8d8d-6e29869fe7e4.png">

**Steps to reproduce the bug**
1. Open Spotify app
2. Activate the app switcher - the window thumbnail for Spotify should show, as expected.
3. Navigate to the Spotify window in the app switcher, and press M (the hotkey to minimise the window).
4. After the window is minimised, the thumbnail will not show, and instead is replaced by a completely empty window preview.

This is only reproducible for the Spotify app, so I have no idea what might be causing this.

**Comment by lwouis** [comment]
It might be #1324 or/and it might be that Spotify actually unloads the view when minimized (to save on resources maybe?).

In any case, we get the screenshot from the OS. If it's black, nothing much we can do. It probably means the window is actually black.
