### ISSUE TITLE
Configuration dialog is laggy

### ISSUE THREAD

**Issue by akx** [lwouis/alt-tab-macos#194]
Moving the sliders in the configuration dialog is janky. If I'm guessing right, every mouse movement has the app persist preferences onto disk or something?

![atlag](https://user-images.githubusercontent.com/58669/78000055-56388c80-733c-11ea-8971-5a273429c4e4.gif)

**Comment by lwouis** [comment]
I fixed that in 989369c on my [current working branch for v4](https://github.com/lwouis/alt-tab-macos/tree/shortcut-recorder-wip). Related ticket: #188
