### ISSUE TITLE
Alttab does not show some apps

### ISSUE THREAD

**Issue by edenraf** [lwouis/alt-tab-macos#1954]
When I press alt-tab, chrome, notes, spotify do not appear as an option. I believe it used to, and I haven't changed any settings in Alttab. Now it does not work. I have tried when these apps are active and visible.

It is not an app in the blacklist, though I have tried to add it to a maximise blacklist with no luck.
My alt-tab settings should show all apps, all spaces, all screens.
I have another shortcut that should show windows from only active apps (say if I have several chrome windows open). When I use that, I get no alt-tab popup whatsoever.

Perhaps it is the most recentl monterey update?

Using v6.46.1
macOS monterey 12.6

**Comment by lwouis** [comment]
Please see pinned issue #1324
