### ISSUE TITLE
IntelliJ IDEA CPU high

### ISSUE THREAD

**Issue by xiaozhukk** [lwouis/alt-tab-macos#1955]
**Describe the bug**

It is easy to cause the IntelliJ IDEA CPU to be very high when switching between IntelliJ IDEA and other apps.

MacBook Pro
Apple M1 Max

**Comment by lwouis** [comment]
Please don't delete the template when opening a ticket. The template is there to prevent tickets like the one you created where it's hard to understand what you mean, how to reproduce the issue you witnessed, etc.

I'm going to close this as it seems like a problem on IntelliJ side. If you think it's on AltTab's side, please open a new ticket and use the template to fill in necessary information for people to understand.
