### ISSUE TITLE
Change (or allow customization) of background color of selector

### ISSUE THREAD

**Issue by Swandog** [lwouis/alt-tab-macos#1960]
**Is your feature suggestion related to a problem? Please describe.**
I'm using the MacOS theme, and when the switcher comes up over a dark-colored window (e.g., most apps in Dark Mode), it is hard to tell which one I am selecting, because the background color fades into the window behind it (i.e., there isn't enough contrast).

(If needed, I will attach a screenshot later, when I don't have so many open windows that I'm worried about leaking info from.)

**Describe the solution you'd like**
I'd like the background color to be higher contrast from the rest of the overlay, so it's easier to tell which one I'm suggesting. This could be a change to the default themes, or a color could be picked in the settings interface. If there was a config file that this could be written to, that would also work.

**Describe alternatives you've considered**
I can mitigate this somewhat by turning on "Reduce Transparency" in System Preferences -> Display, but I'd prefer a more targeted way to handle this. 
As far as I can tell from the code, the background color is hardcoded in the `Preferences.swift` file. So I think to change it, I would have to compile it myself, which I'd like to avoid.

**Comment by lwouis** [comment]
Please see https://github.com/lwouis/alt-tab-macos/issues/1901#issuecomment-1225971978
