### ISSUE TITLE
If I set``Command + ` `` for previous window it doesn't work

### ISSUE THREAD

**Issue by AGuerriere** [lwouis/alt-tab-macos#1967]
**Describe the bug**

I tried changing the key for selecting the previous window to ``Command + ` ``  but unfortunately it doesn't seem to work. If I set previous window to ``Command + ` ``  nothing happens when I press ``Command + ` `` 

**Screenshots**
![Screenshot 2022-09-22 at 11 51 48](https://user-images.githubusercontent.com/73212960/191728298-f89a6961-66f2-4c1e-b8b9-69dadb47b2fe.png)
![Screenshot 2022-09-22 at 11 51 41](https://user-images.githubusercontent.com/73212960/191728307-1ea293cd-48ed-477f-8538-557d4bc253ce.png)

I love your app. Thank you for making it!

**Comment by lwouis** [comment]
Backtick is used by default by Shortcut 2. On your screenshot, I see that you have the issue discussed in #1190. Could you try removing the shortcut after `and press:`? Click on it then click the cross icon.
