### ISSUE TITLE
AltTab does not start when the only window is minimised (Launch at Login)

### ISSUE THREAD

**Issue by XInTheDark** [lwouis/alt-tab-macos#1971]
**Bug description:**

Upon startup, AltTab does not activate when only one window is minimised.

**Steps to reproduce:**

1. Enable Launch at Login for AltTab.
2. Start up the computer.
3. After the computer starts up, _but before AltTab has launched,_ quickly open a window and minimise it.
4. After a while, AltTab should have started. Press the hotkey to activate AltTab.

Result: The tab switcher does not show, even though a minimised window is present.

**Notes:**

Strangely, the bug only occurs upon the computer's startup. When one window is minimised, if you quit and relaunch AltTab, the tab switcher functions properly.

**Comment by lwouis** [comment]
This edge case can join the list of situations and techniques discussed in #447.
