### ISSUE TITLE
Move minimised windows to end of list

### ISSUE THREAD

**Issue by c-harding** [lwouis/alt-tab-macos#1974]
Currently, if I close all windows in an app, this app is moved to the end of the list, after all windows. Would it be possible to do the same for minimised/hidden windows? This means that the menu should be organised as:

1. Visible windows
1. Hidden/minimised windows
1. Apps without windows

**Comment by lwouis** [comment]
Yes, it's already an option in the preferences, in the dropdown next to minimized/hidden windows.
