### ISSUE TITLE
`,` shortcut to open preferences

### ISSUE THREAD

**Issue by probablykasper** [lwouis/alt-tab-macos#1983]
**Is your feature suggestion related to a problem? Please describe.**

I'd like to more quickly access the AltTab settings

**Describe the solution you'd like**

Pressing `,` when the AltTab menu is open would open the preferences

**Comment by lwouis** [comment]
Duplicate of https://github.com/lwouis/alt-tab-macos/issues/1813

**Comment by probablykasper** [comment]
Sorry for not looking thoroughly enough - and thanks for making AltTab! ❤️
