### ISSUE TITLE
Chrome windows not losing focus if mouse moves

### ISSUE THREAD

**Issue by probablykasper** [lwouis/alt-tab-macos#1984]
**Describe the bug**

Sometimes Chrome windows don't lose focus when you AltTab between them

**Screenshots / video**

You can see the text fields are focused, and the traffic lights are colored, in both of these windows:

![image](https://user-images.githubusercontent.com/11315492/193160214-442faad9-b00a-45d0-a5b1-65ae6a2d9492.png)

**Steps to reproduce the bug**

1. Open two Chrome windows
2. While alt+tab
3. Move your mouse
4. Unpress alt+tab

**Comment by lwouis** [comment]
This is either due to how AltTab focuses windows, which is explored in #922 and other tickets like #447, or a bug in Chrome.

**Comment by probablykasper** [comment]
Could it potentially work if the new window receives focus _after_ the AltTab menu is closed? Maybe the old window doesn't lose focus because the AltTab menu is open.

I'm not able to reproduce the issue using the macOS native `` Cmd+` `` shortcut, so maybe there's a way

**Comment by probablykasper** [comment]
@mnin Is there a difference in how `Alt+tab` and ` `` Alt+` `` focus the window? This issue seems like it might be specific to `` Alt+` ``

**Comment by lwouis** [comment]
@probablykasper no, both shortcuts trigger the same code/events.
