### ISSUE TITLE
Fantastical's "Run in background" window cannot be hidden with blacklist feature.

### ISSUE THREAD

**Issue by blabidu** [lwouis/alt-tab-macos#1985]
**Describe the bug**

Fantastical has a "Run in background" feature which lets me open it in a "mini window," even while it's quit. This mini window is the one I'm having problem with. The main window of the app is hidden after blacklisting, but the separate window isn't.

I don't use another "run in background" app with an active window, so I don't know if this is applies to other apps as well.

**Screenshots / video**

**"Run in background window" is the mini window in the screenshot.**
![Screen Shot 2022-09-30 at 11 17 45](https://user-images.githubusercontent.com/96132519/193177179-970007b3-7a97-4738-8fa7-b782340f7cff.png)
![Screen Shot 2022-09-30 at 11 15 14](https://user-images.githubusercontent.com/96132519/193177204-93b81a62-7f38-47f9-ade5-33b7985442bb.png)

**Steps to reproduce the bug**

After testing, "run in background" toggle doesn't affect if the mini window gets hidden or not.
1. Open Fantastical's mini window.
2. Use AltTab after blacklisting Fantastical app.

**Comment by lwouis** [comment]
Fantastical probably uses another app with another bundleID for this window. So you're blacklisting the main app, but not the app that runs in the background and launches that special window. You have to blacklist the right app. You can use the Accessibility tool shipped with XCode to point the window and get its actual bundleId. Alternatively you can ask its developer for it, or its community on a forum/chat.

With the right bundleId, AltTab will work as intended.

**Comment by blabidu** [comment]
Not much of a programmer here, but that seems like the deal. Unable to follow your instruction, I sent an inquiry to Flexibits team, and I will post here if they reply with the BundleID.

Thank you!

**Comment by blabidu** [comment]
Fantastical mini window BundleID:
85C27NK92C.com.flexibits.fantastical2.mac.helper

Hope this helps other picky souls like me.
