### ISSUE TITLE
Can't code sign on MacOS 12.6 (m1)

### ISSUE THREAD

**Issue by lawand** [lwouis/alt-tab-macos#1997]
**Describe the bug**

I am trying to build alt-tab-macos-6.46.1 on a Macbook air M1 2020. The first step (setup_local.sh) is failing. I am getting an error message when executing `sh scripts/codesign/setup_local.sh` from the root of the project. The error message is `“alt-tab-macos-6.46.1” is damaged and can’t be opened. You should move it to the Bin.` And the following is the command line output:

`+ certificateFile=codesign`
`++ openssl rand -base64 12`
`+ certificatePassword=HEoPdo8k6n8DjQkm`
`+ scripts/codesign/generate_selfsigned_certificate.sh codesign HEoPdo8k6n8DjQkm`
`scripts/codesign/setup_local.sh: line 8: 25682 Killed: 9               scripts/codesign/generate_selfsigned_certificate.sh "$certificateFile" "$certificatePassword"`

**Steps to reproduce the bug**

1. Download alt-tab-macos-6.46.1
2. Unzip
3. open terminal in the root of the project
4. run `sh scripts/codesign/setup_local.sh`

**Update:** video:
https://user-images.githubusercontent.com/424961/194723178-f5cefe5e-0379-4fcc-801e-5fed18ba86ea.mov

**Comment by lwouis** [comment]
I'm quite confused when you mention you want to build code, but then it seems you're downloading alt-tab-macos-6.46.1 already built? Are you following [instructions from the guide](https://alt-tab-macos.netlify.app/contributing)?

Could you please share more info, maybe a video?

**Comment by lawand** [comment]
hi there. thank you for your reply. what I meant is that I am trying to build the tag 6.46.1 of the source code. and yes, I am following "Building the project locally" in the instructions. the first step there is setup_local.sh which I am trying and failing to execute. I think this is some type of permission issue and the OS is not allowing the script to run as it's supposed to. I will record a video a bit later when I get home

**Comment by lawand** [comment]
@lwouis I added a video reproducing the issue. After failing to do setup_local.sh, the build fails on Xcode saying that the code isn't signed

**Comment by lwouis** [comment]
I've never seen that. To me it looks like macos is blocking execution of the shell script as a "security" measure. Like when you run apps you downloaded for the first time, and macos shows you a dialog to confirm. And for un-notarized apps, macos won't even show you the "open" button in that dialog, and you'll have to use an alternative way to open.

Anyway, can you try to follow [this](https://apple.stackexchange.com/a/387002)? It may fix it. If it doesn't, I suggest you don't download the code zipped through github, and instead you use `git` to `git clone` the repo. Probably that way it won't trigger quarantining. I think most people `git clone`, and that may be why you're the first to face this issue.

As a sidenote, you don't need to run `sh script.sh`. You can run `script.sh` directly, and let your zsh shell execute it.

**Comment by lawand** [comment]
@lwouis Thanks for the info. I can confirm that cloning resolves the issue and the script now runs without problems. I guess I was using the latest tag instead of cloning because I wasn't sure master is stable. But anyway I see now that the tag is the latest commit in master. Thanks

**Comment by lawand** [comment]
I am however seeing build errors in Preferences.swift and can add them into a new issue

**Comment by lwouis** [comment]
@lawand please checkout the [dev branch](https://github.com/lwouis/alt-tab-macos/commits/dev) instead of `master`. It has fixes for compilation issues that happen on XCode 13+
