### ISSUE TITLE
Build errors in Preferences.swift

### ISSUE THREAD

**Issue by lawand** [lwouis/alt-tab-macos#2000]
**Describe the bug**

I am seeing errors while trying to build the current master branch. See the screenshot for details.

**Screenshots / video**

<img width="1280" alt="Screenshot 2022-10-09 at 00 15 08" src="https://user-images.githubusercontent.com/424961/194728058-6a3e904a-e0e5-49f8-b862-b1bc015b06ba.png">

**Comment by lawand** [comment]
The following diff fixes the build errors but I'm not good enough in swift to know if this will cause any issues in the application:

**Comment by lawand** [comment]
@available(OSX, deprecated: 10.11)
    private static func migrateLoginItem() {
        do {
            let loginItems = LSSharedFileListCreate(nil, kLSSharedFileListSessionLoginItems.takeRetainedValue(), nil)!.takeRetainedValue()
            let loginItemsSnapshot = LSSharedFileListCopySnapshot(loginItems, nil)!.takeRetainedValue() as! [LSSharedFileListItem]
            let itemName = Bundle.main.bundleURL.lastPathComponent as CFString
            let itemUrl = URL(fileURLWithPath: Bundle.main.bundlePath) as CFURL
            loginItemsSnapshot.forEach {
                if (LSSharedFileListItemCopyDisplayName($0).takeRetainedValue() == itemName) ||
                       (LSSharedFileListItemCopyResolvedURL($0, 0, nil)?.takeRetainedValue() == itemUrl) {
                    LSSharedFileListItemRemove(loginItems, $0)
                }

**Comment by lawand** [comment]
diff --git a/src/logic/Preferences.swift b/src/logic/Preferences.swift
index 589f9d8..49ec188 100644
--- a/src/logic/Preferences.swift
+++ b/src/logic/Preferences.swift
@@ -242,12 +242,12 @@ class Preferences {
     @available(OSX, deprecated: 10.11)
     private static func migrateLoginItem() {
         do {
-            let loginItems = LSSharedFileListCreate(nil, kLSSharedFileListSessionLoginItems.takeRetainedValue(), nil).takeRetainedValue()
-            let loginItemsSnapshot = LSSharedFileListCopySnapshot(loginItems, nil).takeRetainedValue() as! [LSSharedFileListItem]
+            let loginItems = LSSharedFileListCreate(nil, kLSSharedFileListSessionLoginItems.takeRetainedValue(), nil)!.takeRetainedValue()
+            let loginItemsSnapshot = LSSharedFileListCopySnapshot(loginItems, nil)!.takeRetainedValue() as! [LSSharedFileListItem]
             let itemName = Bundle.main.bundleURL.lastPathComponent as CFString
             let itemUrl = URL(fileURLWithPath: Bundle.main.bundlePath) as CFURL
             loginItemsSnapshot.forEach {
-                if (LSSharedFileListItemCopyDisplayName($0)?.takeRetainedValue() == itemName) ||
+                if (LSSharedFileListItemCopyDisplayName($0).takeRetainedValue() == itemName) ||
                        (LSSharedFileListItemCopyResolvedURL($0, 0, nil)?.takeRetainedValue() == itemUrl) {
                     LSSharedFileListItemRemove(loginItems, $0)
                 }

**Comment by lwouis** [comment]
Please see [this comment](https://github.com/lwouis/alt-tab-macos/issues/1997#issuecomment-1272409119)
