### ISSUE TITLE
AltTab shows from main screen if used on secondary screen in an app with pop up window open

### ISSUE THREAD

**Issue by kevinkuo0905** [lwouis/alt-tab-macos#2003]
**Describe the bug**

When a toast window appears within an app, e.g. download/browse for file prompt on a browser on **non main display**, AltTab pops up from the main display, showing its windows. I have AltTab set to show windows from separate screens.

**Screenshots / video**

<img width="1339" alt="image" src="https://user-images.githubusercontent.com/1009444/194952540-7575197b-c8c6-4ef2-b122-36e96c8cbe65.png">

<img width="576" alt="image" src="https://user-images.githubusercontent.com/1009444/194952700-c0520a58-bc82-4663-83f9-2c4e012bfeac.png">

**Steps to reproduce the bug**

1. Set up a main display and extended display
2. Open Safari or Chrome on extended display 
3. Go to File -> Open File to create pop up window inside app
4. Try the AltTab command, it shows up on main screen

This happens on other apps with other pop up windows. Doesn't matter if it's set to show all windows or window from one screen only, it always shows up from main display. AltTab shows up correctly if no pop up window.

**Comment by lwouis** [comment]
You say that your screens are set as extended display? Extended means that the 2 screens act like 2 large screen. In that case i think it's normal that AltTab shows all windows.

but maybe i don't understand your setup well. Could you film it to help me understand? Maybe film with your phone so i see the physical setup of the displays, then the logical setup, then a window that acts ok and a window that doesn't act ok.

**Comment by kevinkuo0905** [comment]
https://user-images.githubusercontent.com/1009444/195505710-e03615ac-e318-4079-ac7e-c7730a4bde64.MOV

Setup: left main, right secondary

1. Alt tab works on main screen normally
2. Switch focus to right screen, alt tab works normally
3. Open a window in browser, alt tab shows up from the left screen and its windows, but I still have chrome on the right focused

**Comment by lwouis** [comment]
Thank you, the issue is clearer now.

You trigger AltTab from the secondary screen, while Chrome has a dialog open, and AltTab shows its UI on the main screen, weirdly.

**Comment by kevinkuo0905** [comment]
> 
> You have set `Show on: Active screen` in `Preferences > Appearance`, correct?
> 
Yes, show on active screen, and this build did fix chrome with 'open file' open, but still has the same problem on safari, microsoft word, powerpoint, etc.

**Comment by lwouis** [comment]
@kevinkuo0905 coud you please check if [this build](https://github.com/lwouis/alt-tab-macos/files/9789435/AltTab.app.zip) fixes it for you?

**Comment by kevinkuo0905** [comment]
Yes, it works correctly on every app I tested so far.
