### ISSUE TITLE
Will the light mode be added?

### ISSUE THREAD

**Issue by kubai087** [lwouis/alt-tab-macos#2005]
I always use the macOS theme and make all the windows invisible to make it more like the native alt-tab on macOS. However, it is still really good to launch the app which have no windows while the native alt-tab cannot do that and I have more gestures to do with the app like cmd Q or cmd W.

I would like to ask if the light mode will be added and it will look more harmonious when I use light mode generally.

**Comment by lwouis** [comment]
Please see https://github.com/lwouis/alt-tab-macos/issues/82#issuecomment-669982304
