### ISSUE TITLE
[esc] button doesn't cancel and hide when using [cmd] + [tab]

### ISSUE THREAD

**Issue by danielrgjoseph** [lwouis/alt-tab-macos#2029]
![CleanShot 2022-10-19 at 15 16 16](https://user-images.githubusercontent.com/42453327/196815040-2e489840-2333-4ab4-9af0-3616b512dc83.jpg)

On macOS Ventura 13.0 (22A379), when using CMD + Tab to activate Alt Tab, the Esc button does not work to cancel and hide. If I change CMD to another modifier such as control or option, esc does subsequently function.

**Comment by lwouis** [comment]
Maybe macOS now reserves `cmd+esc` for a global shortcut?

**Comment by danielrgjoseph** [comment]
As far as I can tell, it does not seem to be a global shortcut. When I close AltTab and press those keys nothing happens. However, I also noticed that specifically in AltTab, if I hit CMD + Tab, and then press ESC, even if I press the key set to exit/hide (which I changed for the number 1), it seems that key inputs after hitting ESC seemed to be ignored.

**Comment by lwouis** [comment]
I was able to test on Ventura today, and regardless of which modifier key I pick, the default `escape` key always works in closing the AltTab window. I think something is going on with your setup (e.g. external keyboard, software to remap some keys like BTT or Karabineer, other language than English, etc).

I'm going to close the ticket for now. If you have new information that could help debug this, please share it here, and we will re-open the ticket if we can help.
