### ISSUE TITLE
Allow in Background relevant information

### ISSUE THREAD

**Issue by mgabs** [lwouis/alt-tab-macos#2044]
Currently AltTab displays the Dev name in Macos 13.

It should be changed to something relative for track-ability.

![Screenshot 2022-10-26 at 1 17 55 PM](https://user-images.githubusercontent.com/66576612/198017123-32e6ca0e-7392-4116-92d2-e205456135e7.png)

```
13:44:36 ❯ sw_vers
ProductName:            macOS
ProductVersion:         13.0
BuildVersion:           22A380
```

**Comment by decodism** [comment]
It is in General / Login Items.
