### ISSUE TITLE
Windows have different sizes (e.g. System preferences window)

### ISSUE THREAD

**Issue by XInTheDark** [lwouis/alt-tab-macos#2045]
<img width="555" alt="image" src="https://user-images.githubusercontent.com/61100393/198037974-48dc0797-c578-449d-9e63-12b5bd7fd849.png">

In the photo, Safari and System Preferences have different window sizes. Is it possible to add an option to resize them so they are of the same size? (e.g. compress the photos, even though it may become disproportionate.)

**Comment by lwouis** [comment]
Hi @XInTheDark,

It's an interesting idea to make the thumbnails same-sized. This would create a visual grid. Alternatively, we could make the "squares" (i.e. the whole square around the thumbnail, including the app icon, title, and paddings) same-sized. That's what HyperSwitch does if I remember correctly.

I think it could be considered, but as part of #351. It shouldn't be just one more checkbox in th Preferences. It should be part of a "preset" (see #351 to understand better what I mean here). So I'll close this ticket, and feel free to help work on #351 to integrate this.

That being said, notice that remove the variation in size means you don't easily locate the wide or tall windows. I personally use the size of the thumbnail to quickly locate windows, for instance. That would be lost of every window is the same size. A bit like making the thumbnails gray-scale would remove the benefit of locating using colors. Shape and colors are powerful ways to leverage our vision system to locate items quickly.

**Comment by XInTheDark** [comment]
Some people would not appreciate this update, so it's probably better to make a "preset" for this as an option in Preferences.
