### ISSUE TITLE
AltTab "forgets" open apps when mac wakes up from sleep

### ISSUE THREAD

**Issue by vcorr** [lwouis/alt-tab-macos#2054]
When my Macbook has been sleeping during the night, using the shortcut only shows apps that were started after the sleep period, even though I have several apps running.
When I restart AltTab, it will again show all the running apps and the shortcut works normally.
This has been happening after the update to Version 6.47.0
I'm on Monterey 12.5.1

**Comment by lwouis** [comment]
Seems like it could be #1324 / #447
