### ISSUE TITLE
Join Github sponsors so people can donate to the project

### ISSUE THREAD

**Issue by lejon** [lwouis/alt-tab-macos#2058]
I just love alt-tab-macos. Perhaps you could join the GitHub Sponsors programme (https://github.com/sponsors) so that people can easily donate to the project.

**Comment by lwouis** [comment]
You're very kind. Your message of appreciation is more than enough.

Thank you~

**Comment by lwouis** [comment]
@lejon I've added Github Sponsorship to this project today 👍
