### ISSUE TITLE
Localization not applied to newly added shortcuts in preference setting of 6.48.0

### ISSUE THREAD

**Issue by ifsheldon** [lwouis/alt-tab-macos#2060]
**Describe the bug**

Localization is not applied to the texts on the newly added shortcuts in preference setting of 6.48.0. I don't know if the localization for other languages is also affected. 

**Screenshots / video**

<img width="584" alt="image" src="https://user-images.githubusercontent.com/39153080/198876648-17cc8d37-dccf-4536-8230-2666bc6055f6.png">

**Steps to reproduce the bug**

1. Go to preference setting
2. Click on 'control' tab
3. See error

**Comment by lwouis** [comment]
It's not a bug, it's simply that no-one has yet localized these new labels.

Localization is crowd-sourced and very easy to add: https://poeditor.com/join/project/8AOEZ0eAZE

**Comment by ifsheldon** [comment]
OK, I thought only "Shortcut" is localized, not the labels lol. Perhaps you can generalized a bit so that we don't need to translate labels one by one but translate texts instead?

**Comment by ifsheldon** [comment]
OK, that is a fun fact for me, although I've been in Saudi for 2 years. Thanks!
