### ISSUE TITLE
Incorrect name in System Settings

### ISSUE THREAD

**Issue by dhruvkb** [lwouis/alt-tab-macos#2069]
**Describe the bug**
In the new macOS System Settings app, the name appears as "Louis Pontoise" instead of "AltTab".

**Screenshots / video**
<img width="469" alt="Screenshot 2022-11-01 at 6 41 54 PM" src="https://user-images.githubusercontent.com/16580576/199260573-62b483e7-e842-4b10-89b1-2e73f714a0f4.png">

**Steps to reproduce the bug**
1. Open System Settings.
2. Navigate to General > Login Items.
3. Scroll in the "Allow in the Background" list to find "Louis Pontoise" which I believe is in fact AltTab.

**System**
macOS Ventura 13.0
Apple M1 arch

**Comment by lwouis** [comment]
It's fixed in the latest release. Please see #2044
