### ISSUE TITLE
Option to hide all apps with no open window in AltTab view

### ISSUE THREAD

**Issue by treanityy** [lwouis/alt-tab-macos#2073]
I find that there is a bit annoying when I don't want to quit an application for some background tasks but they always show up in AltTab view with no open window icon. There are like plenty of icons like that and it is unnecessary. Please add an option to hide all apps with no open window in AltTab view.

![image](https://user-images.githubusercontent.com/66874618/199486014-7e45f0f2-4d42-49a0-8784-9315e952bc92.png)

**Comment by lwouis** [comment]
Such preference already exists in `Preferences > Appearance > Hide apps with no open windows`.
