### ISSUE TITLE
Can't AltTab to the Messenger app in new AltTab version

### ISSUE THREAD

**Issue by adam-binks** [lwouis/alt-tab-macos#2091]
**Describe the bug**

The Facebook Messenger app no longer appears in my AltTab menu since the last update. 

(NB: I don't have chat bubbles enabled in Messenger.)

**Steps to reproduce the bug**

1. Open Messenger app
2. Open another app (e.g. Chrome)
3. Press alt tab
4. Other apps show up, but Messenger specifically doesn't

**Comment by lwouis** [comment]
I just downloaded the Messenger mac app, and run it. It shows correctly in AltTab.

Can you please share a video showing every single step you take, including opening Messenger and opening AltTab?

Also what version of macOS do you have? Do you have all apps on the same Space or multiple? Do you fullscreen apps?

**Comment by glook** [comment]
Have same issue with latest alttab and telegram versions

**Comment by adam-binks** [comment]
@lwouis I just restarted Messenger and it's working now - sorry to bother you!
