### ISSUE TITLE
Telegram is shown as assigned to all desktops

### ISSUE THREAD

**Issue by GHopperMSK** [lwouis/alt-tab-macos#2095]
On switching apps I see Telegram on all desktops but actually it is on 4th desktop only. Furthermore, the app doesn't have proper thumbnail.

![image](https://user-images.githubusercontent.com/19670887/200637938-459d34c1-1f39-4a12-a3d7-c25b5c9851b0.png)
![image](https://user-images.githubusercontent.com/19670887/200638798-dab3199a-1a78-4cdd-94d8-d472c0e37bd2.png)

MacBook Pro 16 2021
MacOS Monterey 12.6 

```
brew install telegram
brew install alt-tab
```
There are 4 desktops and about 15 apps are running constantly. Default hotkey Comd + Tab shows all apps, Option + Tab shows apps from current desktop only. Everything works just fine but Telegram app. It works correct for 1 week after fresh install but then appears on all desktops. After alt-tab reinstall it works good again but in some days the problem returns back.

**Comment by lwouis** [comment]
Duplicte of https://github.com/lwouis/alt-tab-macos/issues/2092
