### ISSUE TITLE
Telegram 9.1.1.238861 Stable not showing

### ISSUE THREAD

**Issue by mazurandy** [lwouis/alt-tab-macos#2096]
After the latest update of Telegram to 9.1.1.238861 Stable the AlTab doesn't show the app in the window switcher. 

Tried:
A) Installing both the Appstore version, and the one that the website distributes.
B) Downgrading from AltTab-6.49.0 to AltTab-6.47.0

**Comment by lwouis** [comment]
Please see #2092

**Comment by limxingzhi** [comment]
This was fixed for me under Telegram 9.2.1.240459
