### ISSUE TITLE
Telegram window bug

### ISSUE THREAD

**Issue by ternerss** [lwouis/alt-tab-macos#2101]
**Describe the bug**

After activating a Telegram window, AltTab does not move it to the beginning of the tabs. Used to use old versions of AltTab as there was no bug in them (6.38). However, this bug has now appeared in any version.

**Screenshots / video**

[Video](https://user-images.githubusercontent.com/20478987/201068382-7ac3e21a-8266-4117-bd0a-089fc0530c13.mov)

**Steps to reproduce the bug**

1. Open Telegram
2. Switch to Telegram using AltTab
3. Telegram tab always at the end

**System Info**
MacOS Montery 12.6.1, Intel, AltTab v. 6.48.0, Telegram 9.1.1. AppStore

**Comment by dschlabach** [comment]
I'm also experiencing this bug.

**System Info**
MacOS Monterey 12.4, M1 Pro, AltTab 6.49.0, Telegram 9.1.1 AppStore

**Comment by heaven** [comment]
Mac OS Ventura, the Telegram window is missing in AltTab.

**Comment by lwouis** [comment]
#2096
