### ISSUE TITLE
Option to Group Thumbnails by App, Linear Layouts for Groups of Windows by App

### ISSUE THREAD

**Issue by wscullen** [lwouis/alt-tab-macos#2105]
**Is your feature suggestion related to a problem? Please describe.**
It is frustrating to not have the option to group windows together by application while viewing all application windows.

**Describe the solution you'd like**
I'd like the option to sort the windows by most recent, but all windows for a given application should be grouped and sorted by most recent within that group. Optionally, I'd like a more linear layout focussed on displaying groups of windows, similar to how the native command-tab window looks, except with window thumbnail previews extending vertically (or horizontally) perpendicular to the axis that the linear layout scrolls in.

**Describe alternatives you've considered**
A (very) rough mockup of the linear layout I am proposing:
![IMG_0086](https://user-images.githubusercontent.com/25625651/201172604-4caaa67f-18dc-4248-afb0-2ac70de23885.jpeg)

**Comment by lwouis** [comment]
This is an interesting UX. I'll close this ticket as there is already #337 which has lots of discussions about the same goal. Please participate there 👍
