### ISSUE TITLE
Undetected apps - Telegram

### ISSUE THREAD

**Issue by afonsojramos** [lwouis/alt-tab-macos#2112]
**Describe the bug**

Every now and then windows stop being detected. It was a bug that used to happen rather frequently, but it was also easily fixed by either restarting AltTab or the app in question. Lately I haven't had these sporadic failures in window betection, however, I have had one app that stopped being detected altogether, Telegram.

**Steps to reproduce the bug**

1. Have Telegram open.
2. Alt Tab.
3. Telegram doesn't show.

Note: Telegram had an update yesterday, so this might be their fault (however, I currently have no idea of AltTab inner workings so can't say for sure).

<img width="282" alt="image" src="https://user-images.githubusercontent.com/19473034/201453224-0762f100-3c66-4217-8cca-964ae88c4518.png">

**Comment by lwouis** [comment]
Please see all the other telegram tickets. E.g. #2096
