### ISSUE TITLE
Integrate Github in semantic-release

### ISSUE THREAD

**Issue by danilofuchs** [lwouis/alt-tab-macos#2120]
The releases page is not formatted properly

![image](https://user-images.githubusercontent.com/17657014/201890485-cbc24a83-b159-46f2-9008-431c5e01cf22.png)

This happens as the repo only uses the 'git' plugin which adds release notes to git tags.
By adding the 'github' plugin, it creates a proper release with Markdown formatting

**Comment by lwouis** [comment]
Hi @danilofuchs,

Please see previous discussions here: https://github.com/lwouis/alt-tab-macos/issues/597

Would you be willing to make a PR on that topic?
