### ISSUE TITLE
When IINA video player is on fullscreen there is an extra unnecessary tile

### ISSUE THREAD

**Issue by Fishel-The-Genius** [lwouis/alt-tab-macos#2121]
Since I haven't found anything similar I've decided I'll make a new issue. If there is one though, ignore me...

**The issue is as follows:**
Starting when I updated my mac to Ventura, whenever I'm watching a video in the [IINA](https://iina.io/) video player, there is an extra tile in the alt-tab focus cycle. Note that it happens only when it's in full-screen mode. When it's not in full-screen, it behaves as expected.

I have not experienced this issue while using other apps, although it might occur - I just haven't had the chance to encounter it in other apps.
<img width="1219" alt="Screenshot 2022-11-15 at 18 49 04" src="https://user-images.githubusercontent.com/90642152/201980288-be590ed7-072d-4b8c-b593-6d1b1c645366.png">

I'm using the latest alt-tab version (6.50.0) and the latest IINA version (1.3.1).
I'm running macOS Ventura on an m1 MacBook pro.

**Comment by lwouis** [comment]
I just tried, and I can't reproduce this issue. I also tried with the 2 states of this IINA preference:

<img width="172" alt="image" src="https://user-images.githubusercontent.com/106195/201991342-12225568-15b7-4c96-a7d2-72b47ddd1634.png">

Could you please post a step-by-step and a video reproducing the issue?

**Comment by Fishel-The-Genius** [comment]
Thank you for your rapid response.

I'm using IINA without _"legacy full-screen"_ mode enabled. **However**, when I did used the _"legacy full-screen"_ mode, I've encountered yet another issue. the tiles are shown correctly but it doesn't focus on the other apps as expected.

I'll attach videos of the two issues.

**Issue 1**, legacy full-screen disabled, extra tile is shown:

https://user-images.githubusercontent.com/90642152/202174523-9124a068-74da-4651-be35-0bd82f771607.mp4


**Issue 2**, legacy full-screen enabled, not focusing correctly:

https://user-images.githubusercontent.com/90642152/202174607-31e61c52-73b8-48ef-92ca-8cc3d465862d.mp4

**Comment by lwouis** [comment]
I tried again, and I can't reproduce. I have the exact version of IINA you say you have. I have Ventura and an M2.

Then I realized that on your videos, the HUD inside IINA doesn't look like mine. Here is how my IINA window looks like. I don't even see the HUD if I don't hover with my mouse:

<img width="1032" alt="Screenshot 2022-11-16 at 22 14 48" src="https://user-images.githubusercontent.com/106195/202295801-8b3c8b90-1ce5-4cf4-8333-9d60ea747b2c.png">

How come yours is so different? Where did you download IINA? Have you changed settings?

**Comment by Fishel-The-Genius** [comment]
If you are referring to the little piece of UI where the controls are, like the play/pause buttons and the duration played, etc., it's just a matter of a UI tweak in the preferences. Just to be sure, I tried all the options available and the problems still remain.

Here is a ScreenShot of the IINA preferences window where you can change the UI.

<img width="819" alt="Screenshot 2022-11-17 at 0 37 44" src="https://user-images.githubusercontent.com/90642152/202310598-c2bb8bfb-a183-4b03-b210-70304c43ef9f.png">
 Under UI/ On Screen Controller/ Layout...

**Comment by lwouis** [comment]
Can you please run `defaults read com.colliderli.iina` in Terminal and share the results?

**Comment by Fishel-The-Genius** [comment]
Sure thing!

`
***@***-MacBook-Pro ~ % defaults read com.colliderli.iina`
`{`
`    MainWindowLastPosition = "{{0, 0}, {1512, 945}}";`
`    NSFullScreenMenuItemEverywhere = 0;`
`    NSNavLastRootDirectory = "~/Downloads";`
`    NSNavPanelExpandedSizeForOpenMode = "{800, 448}";`
`    "NSSplitView Subview Frames NSColorPanelSplitView" =     (`
`       "0.000000, 0.000000, 224.000000, 258.000000, NO, NO",`
`        "0.000000, 259.000000, 224.000000, 48.000000, NO, NO"`
`    );`
`    "NSToolbar Configuration com.apple.NSColorPanel" =     {`
`        "TB Is Shown" = 1;`
`    };`
`    "NSWindow Frame IINAFontPickerWindow" = "98 126 458 536 0 0 1512 950 ";`
`    "NSWindow Frame IINAMiniPlayerWindow" = "29 547 300 372 0 0 1512 944 ";`
`    "NSWindow Frame IINAPreferenceWindow" = "358 155 806 566 0 0 1512 950 ";`
`    "NSWindow Frame IINAWelcomeWindow" = "436 272 640 400 0 0 1512 944 ";`
`    "NSWindow Frame NSColorPanel" = "4 153 224 278 0 0 1512 944 ";`
`    "NSWindow Frame NSNavPanelAutosaveName" = "356 372 800 448 0 0 1512 944 ";`
`    "NSWindow Frame SUStatusFrame" = "556 611 400 135 0 0 1512 950 ";`
`    "NSWindow Frame SUUpdateAlert" = "446 414 620 398 0 0 1512 950 ";`
`    SUEnableAutomaticChecks = 1;`
`    SUFeedURL = "https://www.iina.io/appcast.xml";`
`    SUHasLaunchedBefore = 1;`
`    SULastCheckTime = "2022-11-15 17:00:17 +0000";`
`    SUScheduledCheckInterval = 604800;`
`    SUSendProfileInfo = 0;`
`    SUUpdateGroupIdentifier = 4278700057;`
`    SUUpdateRelaunchingMarker = 0;`
`    arrowBtnAction = 2;`
`    audioLanguage = "";`
`    autoSearchOnlineSub = 1;`
`    controlBarAutoHideTimeout = 2;`
`    controlBarPositionHorizontal = "0.5";`
`    controlBarPositionVertical = 0;`
`    controlBarToolbarButtons =     (`
`        5,`
`        3,`
`        2,`
`        1,`
`        0`
`    );`
`    currentInputConfigName = "mpv Default";`
`    displayTimeAndBatteryInFullScreen = 1;`
`    iinaLastPlayedFilePath = "~/Movies/Movie on 17-10-2022 at 20.14.mov";`
`    iinaLastPlayedFilePosition = "3.8";`
`    initialWindowSizePosition = "";`
`    inputConfigs =     {`
`        "My Configs" = "/Users/***/Library/Application Support/com.colliderli.iina/input_conf/My Configs.conf";`
`    };`
`    musicModeShowAlbumArt = 1;`
`    musicModeShowPlaylist = 0;`
`    playlistAutoAdd = 0;`
`    playlistAutoPlayNext = 0;`
`    quitWhenNoOpenedWindow = 1;`
`    recordPlaybackHistory = 0;`
`    recordRecentFiles = 0;`
`    relativeSeekAmount = 1;`
`    showChapterPos = 1;`
`    showRemainingTime = 1;`
`    softVolume = 100;`
`    subLang = eng;`
`    subPos = 97;`
`    subTextFont = "VarelaRound-Regular";`
`    subTextSize = 45;`
`    themeMaterial = 4;`
`    volumeScrollAmount = 1;`
`    windowBehaviorWhenPip = 2;`
`}`

I've tried to do it as readable a s possible. Let me know if you need anything else.

**Comment by lwouis** [comment]
I tried changing my preferences to match yours. Still, I can't witness the issue. I'm affraid that's all I can do here.

Overall, any window shown in AltTab is a real window. What I mean is that AltTab won't create/invent a window. If it's shown, it means the app created it. If it's not visible to you as a user, then that window is hidden from sight, but does exist, and AltTab only reports on it.

I could add another workaround specific to IINA but since I can't reproduce the issue, I can't fine-tune such workaround.

[Please open a ticket with the IINA project](https://github.com/iina/iina/issues). There have been [a few issues with this app already](https://github.com/lwouis/alt-tab-macos/issues?q=is%3Aissue+IINA).

**Comment by Fishel-The-Genius** [comment]
Just to emphasize, I can see now that you are correct. I'm using another app called [DockMate](https://www.macenhance.com/dockmate) and it shows as if there is another long and narrow transparent panel at the top of the screen. So it seems that's an IINA issue and not from the alt-tab part.

<img width="1512" alt="Screenshot 2022-11-17 at 13 54 16" src="https://user-images.githubusercontent.com/90642152/202439756-d5a63d88-d660-4f37-852e-878d96f0f166.png">

In the image attached, you can see the IINA icon on the right side of the dock, the mouse pointer is invisible in the ScreenShot, but it's hovering over the left thumbnail (the one surrounded with a white border) and thus a blue rectangular widget appears in the top of the screen.

This blue rectangle is actually the second huge tile in alt-tab. So, as mentioned above, it's an issue with IINA and other apps experience this too.

Thanks anyway!
