### ISSUE TITLE
Windows assigned to all desktops are not included in switcher

### ISSUE THREAD

**Issue by pedorro** [lwouis/alt-tab-macos#2123]
**Describe the bug**
In release v6.50.0 windows assigned to all spaces are not included in switcher.  I reverted to v6.49.0 and this issue was resolved.

I keep a few apps pinned to all desktops (e.g. GitKraken).  In the latest release these apps are not included in the app switcher

Screen capture:  https://www.loom.com/share/ad45f2b21c7e4a78b3f00e11a80d0ed9

**Steps to reproduce the bug**
1. Mark an app as assigned to all desktops
2. Activate AltTab switcher
3. App on all desktops is not shown

* AltTab version: 6.50.0
* macOS version:  12.6.1

**Comment by lwouis** [comment]
Thank you for opening this issue! I was able to reproduce it.

I investigated a bit, and it's a regression from fixing #2017. The window assigned to All Spaces is considered tabbed.

I'll look into a fix 👍

**Comment by lwouis** [comment]
@pedorro Could you please try [this build](https://github.com/lwouis/alt-tab-macos/files/10015269/AltTab.app.zip), and let me know if it fixes the issue? (and doesn't show new windows it shouldn't show)

**Comment by pedorro** [comment]
@lwouis  awesome!  I think that does it!  I appear to be getting all windows again using that build :)

thx for the quick response!
