### ISSUE TITLE
The foobar2000 window is not detected

### ISSUE THREAD

**Issue by Perlence** [lwouis/alt-tab-macos#2124]
Hey, I'm using AltTab v6.50.0 on macOS 13.0, and foobar2000 v1.6.11 runs on Crossover 22.0.1. It used to work in AltTab v6.49.0 and before.

This happens when the window is assigned to All Desktops.

https://user-images.githubusercontent.com/1044300/201989728-2551ece3-bec6-4a2b-be47-b28055ffc880.mp4

@lwouis Could I help you troubleshoot this one?

**Comment by Perlence** [comment]
This is actually a duplicate of #2123.

**Comment by lwouis** [comment]
You're sure that it's because of the assignment to All Spaces in this foobar2000 case as well?

Could you please try [this build](https://github.com/lwouis/alt-tab-macos/files/10015269/AltTab.app.zip), and let me know if it fixes the issue? (and doesn't show new windows it shouldn't show)

**Comment by Perlence** [comment]
I think it's due to assigning to All Desktops and not specific to foobar2000. If I select None (desktops) it works fine.

The build you've shared fixes the issue with foobar2000, and I haven't noticed any other extra windows.
