### ISSUE TITLE
Update popup does not show latest release notes

### ISSUE THREAD

**Issue by Reply2Zain** [lwouis/alt-tab-macos#2131]
**Describe the bug**

Update pop-up does not show latest release notes. The update popup only shows the notes for older versions but there is no reference of what is in version 6.51.0.

<img width="699" alt="release_notes_v6 51 0" src="https://user-images.githubusercontent.com/37006843/202328970-393691ef-dd34-4803-a23c-098ea5d1337f.png">

This is not a major issue. Just wanted to bring this to your attention. Feel free to close this is you believe it's resolved.

**Steps to reproduce the bug**
1. Be on a older version (tested v6.50.0)
2. Click on "policies" within alt tab preferences.
3. Click on "check for updates now"
4. See the popup

**Your environment**
* AltTab version: 6.50.0
* macOS version: Ventura (13.0.1)

**Comment by XInTheDark** [comment]
<img width="620" alt="image" src="https://user-images.githubusercontent.com/61100393/202375008-516e8258-0aa0-4fd6-8cc7-3cf6d5ab5e8b.png">

Same.

**Comment by lwouis** [comment]
Thank you for reporting this issue. Indeed, there is an issue with Netlify:

> UNSUPPORTED BUILD IMAGE
>
>  The build image for this site uses Ubuntu 16.04 Xenial Xerus, which is no longer supported.

I guess they broke our pipeline by forcing people to update to the latest thing.

I'll look into fixing this.

**Comment by lwouis** [comment]
I updated the infra on Netlify-side, and things are back to normal. Thank you again everyone for the report! 👍
