### ISSUE TITLE
Make "Hide apps with no open window" option available on the shortcut level

### ISSUE THREAD

**Issue by wicharek** [lwouis/alt-tab-macos#2139]
**Is your feature suggestion related to a problem? Please describe.**
I use two displays. I have one shortcut to open the AltTab switcher for the windows on the display that has the mouse, and another one to open *all* of the windows. The problem is with the applications without windows. They are either shown with both shortcuts or with neither.

**Describe the solution you'd like**
I would like the option "Hide apps with no open window" to be configurable or overrideable on the shortcut level, like minimized or hidden windows are.

**Describe alternatives you've considered**
I don't see any. Either I agree with always seeing the apps without the windows on every screen, which is a bit confusing. Or not see them at all, which is also confusing but in a different way.

P. S. I am a developer myself and would be happy to work on this, but would love to get feedback first on whether it is feasible. Or perhaps there is an existing way to achieve what I need, that I overlooked.

**Comment by lwouis** [comment]
Hi,

Every preference in AltTab that's global, could be made to be per-shortcut. The upside: more flexibility. The downside: more complexity (have to change a given preference for each shortcut you use). So the current situation reflect not what's possible, but what most people have asked to have per-shortcut.

You're the first person to ask for this checkbox to become per-shortcut, in years. So unfortunately, it means that your use-case is quite niche. For that reason, I'm afraid I can't implement the change. I hope you understand that I have to do arbitrage between different people use-cases, and try to keep the app great for most people, at the expense of some particular group of users sometimes 🙇
