### ISSUE TITLE
Telegram shows that it has no opened windows

### ISSUE THREAD

**Issue by danil0110** [lwouis/alt-tab-macos#2141]
**Describe the bug**

With the opened window of Telegram app, AltTab shows that it has no opened windows, and as a result, it is in the very end of the list.

**Screenshots / video**

![CleanShot 2022-11-19 at 18 14 47@2x](https://user-images.githubusercontent.com/38916225/202860881-5e17a645-8b6f-4bd8-8e86-70b4b14b008f.jpg)

**Steps to reproduce the bug**

1. Launch Telegram
2. Make sure the Telegram's window is open
3. Use AltTab to switch between windows
4. See that Telegram shows that it has no opened windows

**Your environment**

* AltTab version: 6.51.0
* macOS version: Ventura 13.0.1 (22A400)
* Other relevant info: Telegram 9.1.1.238861 Stable

**Comment by lwouis** [comment]
#2096
