### ISSUE TITLE
Telegram app not showing preview in app switcher

### ISSUE THREAD

**Issue by EminFPS** [lwouis/alt-tab-macos#2143]
**Describe the bug**

The bug is that when using the Telegram app, whether from the Mac App Store or from their website, it does not show the preview in the alt-tab app switcher. Instead, it shows a grey window with the message "app is running but has no open window" when hovering the mouse over it. 

Also, the Telegram window in the alt-tab app switcher is always last, regardless of how recently it was open.

What should be happening: we should be able to see a preview of the telegram window in the app switcher like with any other actively running app. This regression seems to have happened in the past 2-3 versions since 6.51.

**Screenshots / video**

[IMG_1323.pdf](https://github.com/lwouis/alt-tab-macos/files/10048171/IMG_1323.pdf)

Sorry for the phone photo, I was unable to take a screenshot with the app switcher open. Let me know if you need any additional ones.

**Steps to reproduce the bug**

1. Open the Telegram app
2. Open the alt-tab app switcher by pressing option + tab
3. See error

**Your environment**

* AltTab version: 6.51
* macOS version: Ventura 13.0
* Other relevant info: M1 Macbook air 8 gb, telegram version 9.1.1.238861 Stable

**Comment by lwouis** [comment]
#2096
