### ISSUE TITLE
Windows from some (?) apps are not accounted for

### ISSUE THREAD

**Issue by khour** [lwouis/alt-tab-macos#2149]
**Describe the bug**

Seems that certain apps are ignored within AltTab. For now I've seen this with Telegram (main window, accessory "instant view" windows). Started happening not so long ago, maybe 1-3 weeks?

**Screenshots / video**

![SCR-20221121-l5n](https://user-images.githubusercontent.com/763911/203052331-bde666f4-f634-4583-a405-70f73d7edfb0.png)

**Steps to reproduce the bug**

Nothing particular, just launch Telegram (native app, either from the app store or the official website, not the multiplatform QT one)

**Your environment**

* AltTab version: 6.51.0
* macOS version: 11.7.1 / 12.6 (same on both)

**Comment by billionaire** [comment]
I have telegram in the AltTab-list, but always in the end of the list (regardless of when it was last used) and without a preview.
This behavior has been going on for several weeks.
Restarting the application or operating system does not resolve the issue.

https://apps.apple.com/app/telegram/id747648890?mt=12

AltTab 6.51.0.
macOS 13.0.1 (22A400). m1.
<img width="439" alt="20221120221121_140813_of0em" src="https://user-images.githubusercontent.com/6255854/203064465-8541fa1f-dda7-4df9-a5fe-9912330adf97.png">

**Comment by lwouis** [comment]
For telegram, please see #2096. For other apps, it would most likely be #1324
