### ISSUE TITLE
Telegram app is not visible on M1 while AltTabbing. 

### ISSUE THREAD

**Issue by maxoliinyk** [lwouis/alt-tab-macos#2154]
**Describe the bug**

When trying to AltTab, the Telegram app is not visible on Macbook Pro M1. Though it is visible on the Intel Macbook. 
The apps on both MacBooks have similar settings, the AltTab on both machines is up to date (v. 6.51.0) and Telegram is also on the same version.
Telegram is only visible on the M1 Macbook when I turn the setting "Hide applications that have no open windows." off.

**Screenshots / video**

Screenshot of AltTab with Telegram on Intel Macbook:

![зображення](https://user-images.githubusercontent.com/68681586/203507077-6f23c060-5820-48cd-86da-7294c3846946.png)

Screenshot of AltTab with Telegram on M1 Macbook:

<img width="1437" alt="зображення" src="https://user-images.githubusercontent.com/68681586/203506870-8586d70b-5486-4129-b749-915245964a53.png">

**Steps to reproduce the bug**

1. Open Telegram app on M1 Macbook.
2. Hit AltTab.
3. Error occurred / You cannot see the app here.

**Your environment**

* AltTab version: v. 6.51.0
* macOS version:  Ventura 13.0.1
* Other relevant info: both Macbooks are on identical versions, and no peripherals are used.

**Comment by lukag** [comment]
This is also present on non-M1 Macbooks, I noticed it after updating Telegram yesterday. Alt-tab switching stopped working entirely in another similar app (Hyperswitch). The AltTab app makes Telegram visible, but without the preview window, and always at the end-final position just like in your screenshot of the M1.

Do you have the same Telegram version on both machines? Mine is 9.1.1.238861 Stable.

**Comment by maxoliinyk** [comment]
> Do you have the same Telegram version on both machines? Mine is 9.1.1.238861 Stable.

I've just noticed that I have 9.1.1.238861 Stable on my M1 and 9.1.239879 Beta on Intel.

Seems like Beta is fixing it, should definitely try.

**Comment by lwouis** [comment]
This is a Telegram issue. Please see #2096
