### ISSUE TITLE
AltTab is frozen and unresponsive. How can I force quit or close it?

### ISSUE THREAD

**Issue by liudas-stonys** [lwouis/alt-tab-macos#2158]
AltTab is frozen and is on top in every desktop. How can I close it? It is covering my Activity monitor and I can't bring it to front to force quit. I can't restart my PC. What should I do?

<img width="1096" alt="image" src="https://user-images.githubusercontent.com/38351121/203944968-718b5669-a27e-4823-bd4a-cf4626d77e14.png">

I'm pretty sure, that I have the latest version.

I had to restart my Mac, but would be nice to know, was there a way to shutdown the app, which I didn't know?

**Comment by lwouis** [comment]
Are you able to reproduce this issue consistently? If it's just a fluke, nothing much we can do.

If it's consistent, please share steps to reproduce, a video, etc. All the stuff that was in the template you removed.

**Comment by XInTheDark** [comment]
Maybe it's just some problem with the OS. Also, to force quit, either [quit it from the Activity Monitor](https://support.apple.com/guide/activity-monitor/actmntr1002/mac) or use `Command-Option-Esc`
