### ISSUE TITLE
[Bug] Telegram always shows as minimised

### ISSUE THREAD

**Issue by change-agent** [lwouis/alt-tab-macos#2169]
I have Telegram 9.1.1.238861 (Mac App Store version) installed on my Mac running macOS 12.4. 

I have noticed that altTab always displays Telegram as minimised, despite the fact this isn't the case. I have uploaded a [screen recording](https://share.cleanshot.com/dci26g) replicating the behaviour.

![CleanShot 2022-11-29 at 12 13 05@2x](https://user-images.githubusercontent.com/7474791/204414189-0948d8e1-5897-4af5-a144-84b38684389d.png)

**Comment by XInTheDark** [comment]
AFAIK, this just means that AltTab cannot detect any open windows for Telegram. I believe someone has opened a similar issue before.

**Comment by XInTheDark** [comment]
See #2092, #2096, #2154, #2141, #2149, etc.; those are all reporting the same issue.

I don't think AltTab can do anything right now to fix it.
