### ISSUE TITLE
Can't see Telegram app when use AltTab

### ISSUE THREAD

**Issue by edbond88** [lwouis/alt-tab-macos#2175]
**Describe the bug**

After pressing alt-tab can't see Telegram app

**Video**

https://user-images.githubusercontent.com/1949927/204908151-54571742-b2f9-4082-880a-7df9fbc0086a.mov

**Steps to reproduce the bug**

I don't know what you should to do to reproduce this bug.

**Your environment**

* AltTab version: Version 6.51.0
* macOS version: MacBook Air M1, macOS 13.0 (22A380)
* Telegram version: 9.1.1.238861 Stable

**Comment by lwouis** [comment]
#2096
