### ISSUE TITLE
Telegram app appears always as the last item in the alt-tab list, even if it is active

### ISSUE THREAD

**Issue by tonisk** [lwouis/alt-tab-macos#2176]
**Describe the bug**

Telegram app (ru.keepcoder.Telegram) appears always as hidden and the last item in the alt-tab list, even if it is active. This started happening a few weeks ago.

**Steps to reproduce the bug**

1. Use AltTab
2. Have Telegram open and not hidden
3. Press and hold Alt-Tab
4. Telegram appears as the last item on the list and as a hidden window

**Your environment**

* AltTab version: 6.51.0
* macOS version: 13.0.1

**Comment by lwouis** [comment]
#2096
