### ISSUE TITLE
Unable to see which app highlighted in Dark Mode

### ISSUE THREAD

**Issue by swarupsesha** [lwouis/alt-tab-macos#2177]
**Unable to see which app highlighted in Dark Mode**

When selecting Dark Mode in macOS Appearance and Night Shift Light turned on, its difficult to see which app is highlighted.

**Steps to reproduce the bug**

1. Open AltTab
2. Under Appearance select MacOs Theme
3. Turn on Dark Mode and Night Shift in macOS Setting
4. When selecting windows in ALttab its difficult to make out which App window is highlighted.

**Your environment**

* AltTab version: Version 6.51.0
* macOS version: Ventura 13.0.1

**Comment by lwouis** [comment]
Please use the Windows 10 theme in Appearance. Also please see #1960
