### ISSUE TITLE
2 entries for Android emulator

### ISSUE THREAD

**Issue by lub0s** [lwouis/alt-tab-macos#2178]
**Describe the bug**
Android emulator has 2 entries, when opened, in the overlay. See screenshot.

**Screenshots / video**
![issue](https://user-images.githubusercontent.com/3765920/205011471-c063fb53-c936-4d32-84c9-fb9d7c13722e.png)

**Steps to reproduce the bug**

1. Launch an emulator from android studio
2. Observe 2 entries for it in the overlay

**Your environment**

* AltTab version: 6.49.0
* macOS version: 13.0 (22A380)

**Comment by lwouis** [comment]
Yes, they coded the menu as a mac window, thus why AltTab shows it as a window. Please contact the app maker so they fix it 👍

**Comment by teknogeek** [comment]
Can we make it possible to ignore windows by executable and/or binary name? The "app maker" here is Google...so there's no real easy way to get that fixed 😅

**Comment by lwouis** [comment]
@teknogeek you can block using bundleIdentifier. Is it not working here to use the bundleId to block the app you don't want?

**Comment by teknogeek** [comment]
@lwouis unfortunately `qemu-system-aarch64` is just a binary, so it doesn't have a bundle identifier

**Comment by lwouis** [comment]
I understand. I'm afraid i don't have a solution to offer for now 🙇
