### ISSUE TITLE
Wrong thumbnails in Arc browser

### ISSUE THREAD

**Issue by betty2310** [lwouis/alt-tab-macos#2183]
**Describe the bug**

When I use [Arc](https://arc.net/), beside the thumbnail of window I'm working on. Alt-tab also add a new "window" called Arc with no preview and double width.

**Screenshots / video**

![](https://i.imgur.com/TVKLLTm.png)

**My environment**

* AltTab version: 6.51.0
* macOS version: 12.5.1
* Other relevant info: Arc version: 0.79.1

**Comment by lwouis** [comment]
Most likely Arc spawns this invisible window to do some tricks. Please contact them to fix it. It's 99% chance on their side.

**Comment by adamastern** [comment]
Hi! Adam from the Arc team here. Thanks for reporting. This should be fixed in Arc v0.81.0.

**Comment by AfzalivE** [comment]
Can confirm, it looks like it's fixed!
