### ISSUE TITLE
arc displays two ICONS

### ISSUE THREAD

**Issue by webxmsj** [lwouis/alt-tab-macos#2188]
**Describe the bug**

A clear and concise description of what the bug is. What happened, and what you think should have happened.

**Screenshots / video**

Add screenshots to help explain your problem. You can also use Loom to easily record your screen to show the bug in action. That is *really* helpful!

**Steps to reproduce the bug**

**Your environment**

* AltTab version: 
* macOS version: 
* Other relevant info: e.g. using external keyboard, multiple monitors, etc

**Comment by lwouis** [comment]
Form wasn't filled. Can't investigate issue
