### ISSUE TITLE
Quickly scrolls through selection to last window when activated through remapping.

### ISSUE THREAD

**Issue by Pierce913** [lwouis/alt-tab-macos#2189]
I have a shortcut set up to "Then release: Do nothing".  The activation shortcut being alt+`.
When I press the shortcut everything works as expected. The window appears then I can navigate with arrow keys to my selection and hit enter to select my window.

I have a remapping on my computer where I have remapped right option to f18 using karabiner elements. I then use keyboard maestro to sent the keystroke alt+` when pressing f18. This is set up so I have a single activating key which shows me my windows which I can then select with arrow keys and hit enter. All very quickly with the right hand.

The problem is when alttab is activated through the single key the window selection quickly scrolls to the last window. Like the right arrow key is stuck down. I have also tried the remapping directly in karabiner elements so pressing the right alt key sends alt+` to activate alttab with a single key and it also has the bug. I can't see why simulating the keystroke is causing this behavior.

A quick fix might be to allow directly mapping a single key in alttab UI instead of requiring a modifier key and then I could just activate it with f18.

Here is my karabiner config:
```{
    "global": {
        "check_for_updates_on_startup": false,
        "show_in_menu_bar": false,
        "show_profile_name_in_menu_bar": false
    },
    "profiles": [
        {
            "complex_modifications": {
                "parameters": {
                    "basic.simultaneous_threshold_milliseconds": 50,
                    "basic.to_delayed_action_delay_milliseconds": 500,
                    "basic.to_if_alone_timeout_milliseconds": 1000,
                    "basic.to_if_held_down_threshold_milliseconds": 500,
                    "mouse_motion_to_scroll.speed": 100
                },
                "rules": [                    
                    {
                        "manipulators": [
                            {
                                "description": "Change right option tap to f18",
                                "from": {
                                    "key_code": "right_option",
                                    "modifiers": {
                                        "optional": [
                                            "any"
                                        ]
                                    }
                                },
                                "to": [
                                    {
                                        "key_code": "right_option"
                                    }
                                ],
                                "to_if_alone": [
                                    {
                                        "key_code": "grave_accent_and_tilde",
                                        "modifiers": ["left_option"]
                                    }
                                ],
                                "type": "basic"
                            }
                        ]
                    }
                ]
            },
            "name": "Default profile",
            "parameters": {
                "delay_milliseconds_before_open_device": 1000
            },
            "selected": true,
            "simple_modifications": [],
            "virtual_hid_keyboard": {
                "country_code": 0,
                "indicate_sticky_modifier_keys_state": true,
                "mouse_key_xy_scale": 100
            }
        }
    ]
}
```

Environment

* AltTab version: 6.51.0
* macOS version: Ventrue 13.0.1

**Comment by lwouis** [comment]
I think AltTab works correctly here. Whichever combination of remapping software you are using needs to replicates the events that would trigger if you would press the actual keys manually.

Here is looks like the remapping pipeline sends only the keyDown events but not the keyUp events, thus AltTab considers that the keys are still pressed.
