### ISSUE TITLE
Allow for defining keys for selecting next window

### ISSUE THREAD

**Issue by beyond2001** [lwouis/alt-tab-macos#2193]
Currently selecting previous window can be assigned with a key shortcut, but not selecting next window. People may want to use other keys other than tab to jump to the next window. 

I like to use j to select next window and k to select previous window and at the same time still be able to use tab and backtick to jump back and forth, actually this is a feature liked by many people in the app switcher Witch.

**Comment by lwouis** [comment]
It would complexify too much to add this distinction. The usage is too niche. However we already support arrow keys to do this, and there is an open PR to support vim-style keys, which would answer your use case i believe: #1272

**Comment by beyond2001** [comment]
#1272 looks like is what will address my need. Looking forward to that merging. Thanks!
