### ISSUE TITLE
Mac App Store

### ISSUE THREAD

**Issue by AustinConlon** [lwouis/alt-tab-macos#22]
Any chance this could be distributed on the Mac App Store as well?

**Comment by lwouis** [comment]
It's kind of a follow-up to https://github.com/lwouis/alt-tab-macos/issues/13

Mac App Store means someone is paying apple for a dev account, and listing the app under that account. It doesn't play well with OSS. I opened the ticket to keep the discussion alive though. I may do it on my own account for convenience at some point
