### ISSUE TITLE
Better downgrade/upgrade preferences support

### ISSUE THREAD

**Issue by lwouis** [lwouis/alt-tab-macos#220]
As highlighted in #217, preferences can sometimes crash because of a lack of up/down-grade support. I started adding upgrade support, but I think more can be done.

In particular, I think a catch-all mechanism could be implemented to delete the current preferences if there is no supported path for it. This way the user lose their preferences which is bad, but at least the app doesn't crash on them which is worse.

**Comment by ezity** [comment]
@lwouis I just upgraded from 3.6.0 direct to 3.6.2 (via the auto-updater).

After the upgrade I could not get alt-tab to launch at all, and it would just silently fail every time I tried. After deleting preferences (via command line) it launched just fine. Another data point for you.

**Comment by lwouis** [comment]
Yeah, this behavior is pretty much the worse. Silent crash at startup. We really need to avoid that because most users will just give up and uninstall. Even reinstalling doesn't fix, which is *really* bad

**Comment by cdbattags** [comment]
I'm having the same today. What's the proper fix?

**Comment by lwouis** [comment]
@cdbattags yes, sorry about that! I made a hotfix so that users who upgrade now (to 3.7.0+) won't face the crash. I also raised a PR #224 to handle preference migrations rare cases
