### ISSUE TITLE
Alt Tab usage/configuration question: Show only active windows in the current space instead of all running applications?

### ISSUE THREAD

**Issue by fanofai** [lwouis/alt-tab-macos#2203]
Hi,

Per the wiki: "By default, [AltTab]it shows a scrollable list of thumbnails for all open windows, from all running applications."
Can AltTab be configured to show _only_ the active windows in the current space _instead_ of _all_ running applications?

Attached is a snapshot illustrating what I see when I press the Alt-Tab shortcut. Also attached is a snapshot of my current preferences in Alt-Tab.
![AltTabFeedback1](https://user-images.githubusercontent.com/69817984/207432298-027b1db2-7060-49f9-91ef-0ac0041e1941.jpeg)
![AltTabSelection](https://user-images.githubusercontent.com/69817984/207432313-49d0f993-0c8b-47ad-a50e-0694d61322a6.png)

**Comment by lwouis** [comment]
In appearance, there is a checkbox to "hide apps with no open window" to do just that 👍

**Comment by fanofai** [comment]
Thank you lwouis for the prompt response. Appreciate the help.
