### ISSUE TITLE
Arc displays duplicate, empty windows

### ISSUE THREAD

**Issue by BigEndian** [lwouis/alt-tab-macos#2206]
**Describe the bug**

This issue is somewhat sporadic but may be triggered or exacerbated when opening windows with Arc; Ghost windows appear for each "normal" window Arc has open (see screenshot, which has one window and one incognito window).

**Screenshots / video**
![Arc Issue Displays Ghost Windows](https://user-images.githubusercontent.com/516982/207691975-c5055824-3b26-4777-87cb-ab01ffac215f.jpg)

**Steps to reproduce the bug**

1. Create a new window using Arc
2. A "ghost" window thumbnail, wide without any content appears.
3. Navigating to this "ghost" window thumbnail brings you to whichever normal window the "ghost" is associated with. For example, creating 3 Arc windows creates 3 corresponding "ghost"  window thumbnails.

**Your environment**

* AltTab version: 6.51.0
* macOS version: 13.1
* Other relevant info: No external monitors, just a 16" MacBook Pro plugged into power.

**Comment by lwouis** [comment]
Please contact the makers of the Arc app. The issue is most likely on their side. These windows shown by AltTab do exist. Now why Arc makes them, i'm not sure. AltTab just reports the situation

**Comment by jasdev** [comment]
De-dupes on https://github.com/lwouis/alt-tab-macos/issues/2183 and was fixed today in 0.81.0!
