### ISSUE TITLE
Hide Hidden and Minimized windows

### ISSUE THREAD

**Issue by moisesrodriguez** [lwouis/alt-tab-macos#2208]
**Describe the bug**

I have it to hide hidden and minimized windows. It still shows them at the end.

**Screenshots / video**
[AltTab - Controls - 14 December 2022 - Watch Video](https://www.loom.com/share/da8c2c034b414a6c8d4bbba4c730099c)

**Your environment**

* AltTab version: 6.51.0
* macOS version: Ventura 13.0.1 (22A400)
* Other relevant info: using external keyboard and monitor

**Comment by maestroDever** [comment]
https://github.com/lwouis/alt-tab-macos/issues/2203 @moisesrodriguez

**Comment by moisesrodriguez** [comment]
@maestroDever thanks!
