### ISSUE TITLE
Per shortcut "press X to select previous window"

### ISSUE THREAD

**Issue by olehmisar** [lwouis/alt-tab-macos#2209]
**Is your feature suggestion related to a problem? Please describe.**
I have two shortcuts in place: option+tab and option+backtick. I want to use option+shift+tab to select previous window when I activated the first shortcut and to use option+shift+backtick to select previous window when I activated the second shortcut.

**Describe the solution you'd like**
Right now, the setting "press X to select previous window" is linked to all shortcuts. I would appreciate it if you make this setting per-shortcut.

(this is how it looks now)
<img width="574" alt="image" src="https://user-images.githubusercontent.com/29802592/207795680-6e3ab061-f64b-40fc-909c-5674f9181a7c.png">
<img width="574" alt="image" src="https://user-images.githubusercontent.com/29802592/207795712-ea3b84f3-cd47-41bb-bd67-e505431737cc.png">

**Describe alternatives you've considered**
\-

**Comment by lwouis** [comment]
This would complicate the app for most users, for the benefice of very few users. In other words, i'm afraid it is too niche, sorry.

**Comment by olehmisar** [comment]
no problem. I can totally live with that because I use only 1 shortcut most of the time.

**Comment by chase-miller** [comment]
fwiw I'm in favor of this. I'm coming from the Witch app, which follows the "shift + x" pattern to select a previous window.

**Comment by chase-miller** [comment]
I've implemented this feature via https://github.com/lwouis/alt-tab-macos/pull/2311
