### ISSUE TITLE
Stuck at selection window even after the all the keys are released

### ISSUE THREAD

**Issue by eugenesvk** [lwouis/alt-tab-macos#2215]
**Describe the bug**

I use <kbd>⌘</kbd><kbd>⭾</kbd> as the keybind to select the next window. So if I press and release it right away, I expect the next window to show up.
However, sometimes I just get the app selection window to "stick" after I release this keybind and remain on my screen until I press <kbd>⌘</kbd><kbd>⭾</kbd> again

**Screenshots / video**

In this video I was trying to smash <kbd>⌘</kbd><kbd>⭾</kbd> in succession to induce the bug.
Note that from seconds ~2–5 I'm __NOT__ holding the keybind, yet the app selection window is shown and not going away. It can stay "forever" until I press <kbd>⌘</kbd><kbd>⭾</kbd> again, but in this video it disappears after a couple of seconds because I pressed <kbd>⌘</kbd><kbd>⭾</kbd> again

https://user-images.githubusercontent.com/12956286/208710728-926d956c-525f-457d-8188-183af2deef49.mp4

**Steps to reproduce the bug**

1. Try to <kbd>⌘</kbd><kbd>⭾</kbd> quickly
2. On some <kbd>⌘</kbd><kbd>⭾</kbd> releses, you should see that the switching window doesn't disapper

**Your environment**

* AltTab version: 6.51.0
* macOS version: 10.15
* Other relevant info: internal keyboard, single monitor

**Comment by lwouis** [comment]
Hi,

I'm afraid there is not much I can do here. I don't reproduce this issue on my machine, and other users are not reporting this issue. Do you have software remapping keys (e.g. BTT, Karabiner, etc)?

I'm sorry but I'll close this ticket as it's unactionable for me 🙇

**Comment by eugenesvk** [comment]
I use both, but the exact same setup has never interfered with the default switcher bound to the same keybind <kbd>⌘</kbd><kbd>⭾</kbd>, so it's definitely something unique to Alt-Tab
Is it not possible to add some additional check after a short delay after Alt-Tab has been invoked or afte one key is released to see if <kbd>⌘</kbd> is still pressed, and close the switcher if it's not?

**Comment by lwouis** [comment]
AltTab not closing means that your setup probably doesn't send the event of the key going up.

**Comment by eugenesvk** [comment]
But then why does it not affect the default switcher?
Though you've helped me narrow it a bit down, thanks, — BTT seems to be the reason, I can't seem to repro the AltTab "stickiness" after quitting BTT, so will see if I can tweak something in my BTT (though even without a single key binding there, only with touchpad bindings, it still bugs)

**Comment by eugenesvk** [comment]
Ok, I've narrowed it down to this perfect single-switch reproduction (a clean ↓<kbd>⌘</kbd> tap(↓↑)<kbd>⭾</kbd> then ↑<kbd>⌘</kbd>, so we see all key events are registered properly), this bug often rears its ugly head when you swith to an app that enables __Secure Input__ functionality while BTT is also running
I'll open a bug with the BTT dev, but maybe the additional Secure Input factor might give you an idea of what might be wrong
But with this repro I've also noticed the effet on the builtin switcher: while it doesn't "hang" like AltTab does, the switching takes a tiny, but noticeable (~less than a second?) delay when this is triggered


On the left in this video is iTerm with secure input enabled
On the right is Karabiner Eventviewer, which shows all the key events
(the bug starts at the 1st second after I've reset the previous key events)

https://user-images.githubusercontent.com/12956286/208872655-f4cb6588-d53b-4d3c-aa21-97b91fb2ac28.mp4

**Comment by lwouis** [comment]
AltTab is not affected by Secure Input. I use the old undocumented Carbon APIs to achieve that. I actually found a security flaw in macOS while developping this, just to give you an idea of how intricate the shortcut handling is here.

The bottomline is that you have proved that BTT is causing the issue, so it's up to them now to handle the issue, or up to you to adapt your setup. Nothing I can do at AltTab level here. AltTab is working correctly. If you say that the built-in switcher is showing a delay with your setup, it may be a sign that they added the fail-safe that you suggested (i.e. checking if the key is up or down after a little delay, in addition to checking the keyUp event).
