### ISSUE TITLE
Split screen mode shows two extra entries in the list for the split bar between windows

### ISSUE THREAD

**Issue by ADTC** [lwouis/alt-tab-macos#2216]
**Describe the bug**

When two windows are placed in a split screen view, the AltTab list shows both the windows, but also two additional entries for the split bar.

**Screenshots / video**

<img width="1496" alt="image" src="https://user-images.githubusercontent.com/6047296/208853546-357ab067-594e-492c-a97f-2612d184a94f.png">

**Steps to reproduce the bug**

1. Open two Firefox windows.
2. Use "Tile Window to Left of Screen" to pin one window on left. (This option is in the menu that appears when hovering on the Full screen button (green traffic light).)
3. Use "Tile Window to Right of Screen" to pin the other window on right. (Or select it from the list.)
4. Check the AltTab list.

**Your environment**

* AltTab version: 6.51.0
* macOS version: Ventura 13.1
* Other relevant info: 16" M1 MacBook Pro 2021

**Comment by lwouis** [comment]
This is most likely an issue from Firefox. AltTab just reports the windows, as Firefox is making them. Here Firefox is playing some tricks I imagine, by adding windows to create some separators. Not sure exactly what they are doing, but it's 99% chance the issue is on their side. AltTab has robust window detection at this point, and merely reports on windows. These vertical lines are windows at the technical level.

**Comment by ADTC** [comment]
@lwouis I tried it with TextEdit, and I didn't get any problem. So you may be right that this is a Firefox-specific problem.

> Here Firefox is playing some tricks I imagine, by adding windows to create some separators.

I don't understand. The split bar between windows is supposed to be part of macOS itself, and not added by Firefox. It's the exact same split bar in both apps. But somehow AltTab shows them in list for Firefox, and doesn't show them for TextEdit.

Why is the vertical line reported as two windows in Firefox, but as nothing in TextEdit? It seems so strange.

PS: I tried with Google Chrome, and it too doesn't have any such problem.

Anyway, thanks. I guess I'll have to live with it for now.

**Comment by lwouis** [comment]
> why

My guess would be that they create a fake bar. Maybe stack it on top of the native bar to intercept clicks and do some custom behavior. But it's hard to tell from your screenshot. It's definitely Firefox spawning a window that looks like a vertical bar. Not question about that. Now why they do this? Seems like some sort of hack/workaround they use to accomplish something. Some apps do this. It's not the first time I've seen such trick (e.g. invisible fullscreen windows to intercept clicks on the screen)

> Anyway, thanks. I guess I'll have to live with it for now.

You should contact Firefox support about this.
