### ISSUE TITLE
v3.6.2 crashes on launch

### ISSUE THREAD

**Issue by kikonen** [lwouis/alt-tab-macos#222]
Upgraded to v3.6.2 and seemingly application just flashes screen and exits immediately in OSX 10.15.4. Downgraded to V3.6.1 and it appears to work.

**Comment by lwouis** [comment]
@kikonen Really sorry to hear that!

Could you please type this in a terminal and show us the result?

```bash
defaults read com.lwouis.alt-tab-macos
```

This is to understand better what crashes. After sharing that info, I think you will be unstuck if you type this command and start AltTab again:

```bash
defaults delete com.lwouis.alt-tab-macos
```

Please tell us if it starts after that too. Another user said that it didn't help (see #219) whereas 2 other users said it fixed it for them (see #217)

**Comment by lwouis** [comment]
It seems that 3.6.0 doesn't crash for another user. I'll diff between those versions to try and find what crashes on launch

**Comment by ryenus** [comment]
it worked after deleting its preferences, what I had:

```
$ defaults read com.lwouis.alt-tab-macos
{
    "NSStatusItem Preferred Position Item-0" = "505.5";
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2020-04-08 14:22:40 +0000";
    cancelShortcut = "\\U238b";
    holdShortcut = "\\U2325";
    nextWindowShortcut = "\\U21e5";
    previousWindowShortcut = "\\U21e7\\U21e5";
    theme = "\\Uf8ff macOS";
}
```

After deleting and restarting it worked, now the new output:
```
$ defaults read com.lwouis.alt-tab-macos
{
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2020-04-08 14:29:37 +0000";
    cancelShortcut = "\\U238b";
    holdShortcut = "\\U2325";
    nextWindowShortcut = "\\U21e5";
    previousWindowShortcut = "\\U21e7\\U21e5";
}
```

**Comment by lwouis** [comment]
I'm working on a real migration code, to avoid people crashing, and to actual carry-over their existing preferences. It's something I should have done initially, but it's very easy to forget to add compatibility code. I wish I could have a tool block a PR if it didn't have compatibility code.

**Comment by ryenus** [comment]
@lwouis I only started to use this app recently and quite like it, a BIG THANK YOU for making this and more importantly KEEP IMPROVING IT, well appreciated!

**Comment by lwouis** [comment]
@ryenus your kind words are very appreciated! Today I had quite unpleasant interactions in #219. Your support message cheered me up! :)

**Comment by kikonen** [comment]
For reference, this info I got out (this is, however, with v3.6.1 running)
```
$ defaults read com.lwouis.alt-tab-macos
{
    "NSWindow Frame SUStatusFrame" = "1638 890 400 129 1440 0 1920 1057 ";
    "NSWindow Frame SUUpdateAlert" = "2090 498 620 392 1440 0 1920 1057 ";
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2020-04-08 12:13:39 +0000";
    SUUpdateGroupIdentifier = 3962488451;
    SUUpdateRelaunchingMarker = 0;
    alignThumbnails = Left;
    arrowKeysEnabled = false;
    cancelShortcut = "\\U238b";
    fontHeight = 12;
    hideSpaceNumberLabels = false;
    holdShortcut = "\\U2325";
    iconSize = 16;
    maxCellsPerRow = 5;
    maxScreenUsage = 80;
    minCellsPerRow = 5;
    nextWindowShortcut = "\\U21e5";
    previousWindowShortcut = "\\U21e7\\U21e5";
    rowsCount = 3;
    showOnScreen = "Screen including mouse";
    windowDisplayDelay = 82;
}
```
