### ISSUE TITLE
EXC_BREAKPOINT (SIGTRAP)

### ISSUE THREAD

**Issue by evilmon** [lwouis/alt-tab-macos#2224]
**Describe the bug**

When i try to start AltTab on my Mac mini 2020, it crashes immediately.

**Screenshots / video**

[AltTab-2022-12-23-180959.txt](https://github.com/lwouis/alt-tab-macos/files/10298608/AltTab-2022-12-23-180959.txt)

**Steps to reproduce the bug**

1. start alttab
2. nothing happens
3. have a look at the console and crash reports

**Your environment**

see the attached log file

**Comment by lwouis** [comment]
Could you please share the results of running this command in the Terminal?

`defaults read com.lwouis.alt-tab-macos`

**Comment by evilmon** [comment]
{
    MSAppCenter310AppCenterUserDefaultsMigratedKey = 1;
    MSAppCenter310CrashesUserDefaultsMigratedKey = 1;
    MSAppCenterInstallId = "C909F1DF-2031-4E8C-949E-FBDEA0601A39";
    MSAppCenterNetworkRequestsAllowed = 0;
    MSAppCenterPastDevices = {length = 2240, bytes = 0x62706c69 73743030 d4010203 04050607 ... 00000000 000006a8 };
    MSAppCenterSessionIdHistory = {length = 2658, bytes = 0x62706c69 73743030 d4000100 02000300 ... 00000000 000007cc };
    MSAppCenterUserIdHistory = {length = 2653, bytes = 0x62706c69 73743030 d4000100 02000300 ... 00000000 000007c7 };
    "NSStatusItem Preferred Position Item-0" = 632;
    SUAutomaticallyUpdate = 1;
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2022-07-31 06:25:53 +0000";
    crashPolicy = 2;
    hideAppBadges = false;
    hideThumbnails = false;
    hideWindowlessApps = true;
    iconSize = 32;
    nextWindowShortcut2 = "-";
    preferencesVersion = "6.46.0";
    showTabsAsWindows = false;
    theme = 1;
    updatePolicy = 2;
    windowMaxWidthInRow = 30;
    windowMinWidthInRow = 15;
}

**Comment by lwouis** [comment]
I'm not sure what's going on here. Could you try clicking on the button to reset your preferences? It's at the bottom here:

<img width="686" alt="image" src="https://user-images.githubusercontent.com/106195/209449441-606dbc7d-a8e7-45f2-8094-0df6090b3998.png">

**Comment by evilmon** [comment]
Hello Iwouis,

After executing `defaults delete com.lwouis.alt-tab-macos nextWindowShortcut2`, I was able to start Alttab 👍

**Comment by lwouis** [comment]
Nice to hear. Are you able to set your Shortcut 2 to the value `-` at this point?

I'm a bit puzzled why this particular value was crashing AltTab on your device. On my machine, I can set the shortcut to this key, and when I press it, everything works fine. And upon relaunch, AltTab doesn't crash.

**Comment by evilmon** [comment]
Hello lwouis,
by setting one of the shortcuts to  `-` the application crashes again. Same with `+`

**Comment by lwouis** [comment]
Could you please share a picture of your physical keyboard? I don't understand how this key crashes AltTab for you but not for me. You must be pressing a different key than me.

Do you have any software remapping of the keys? What language is your computer/keyboard in?

**Comment by evilmon** [comment]
It's a german keyboard-layout
![IMG_2378](https://user-images.githubusercontent.com/13575069/209637174-92ad43e9-aeb8-471a-8fc6-4549d97eaca6.jpeg)

**Comment by lwouis** [comment]
So you use the key left of the right-shift-key? You use the bottom or the top symbol on that key? Are these the same signs as an English keyboard? On english keyboard there is the dash`-` and underscore `_` commonly.

**Comment by evilmon** [comment]
yes this is the key. pressing it is a dahs '-'. Pressing it +shift is a underscore '_'.
I used the dash '-' for the shortcut. I get the same crash of alttab using the '+'.
using the default '<' works fine.

**Comment by lwouis** [comment]
I tried to switch my Input Source (macOS jargon for the keyboard language/layout) to German. I get the `-` sign when I press the key left to the right-shift-key. However everything works correctly with AltTab. I can register the shortcut, restart AltTab, no problem.

![image](https://user-images.githubusercontent.com/106195/209858051-0b302a26-32c7-4cdf-a5b3-661da140b516.png)

**Comment by evilmon** [comment]
very strange behavior. I can reproduce it on another mac. 
Maybe you have to change the whole system language and there are some issue with the OS-shortcuts?
For me everything is fine after the reset of the default settings. I just will not use this shortcut anymore.
