### ISSUE TITLE
Fullscreen split handler show up as window

### ISSUE THREAD

**Issue by alphatownsman** [lwouis/alt-tab-macos#2228]
**Describe the bug**

if you have 2 window in split full screen mode, the split handler between the two will also show up as window in AltTab

**Screenshots / video**
<img width="708" alt="Screenshot 2022-12-26 at 21 41 30" src="https://user-images.githubusercontent.com/90480431/209602775-98998a64-b7ad-4daf-997c-e27bd8728bfb.png">

Add screenshots to help explain your problem. You can also use Loom to easily record your screen to show the bug in action. That is *really* helpful!

**Steps to reproduce the bug**

**Your environment**

* AltTab version: 
* macOS version: 
* Other relevant info: e.g. using external keyboard, multiple monitors, etc

**Comment by lwouis** [comment]
#2216
