### ISSUE TITLE
Can not use the | pipe, while AltTab is runing.

### ISSUE THREAD

**Issue by gitttt54** [lwouis/alt-tab-macos#2234]
Hello,

I found [this thread](https://github.com/lwouis/alt-tab-macos/issues/511), but it blows my mind.

I use MS Remote Desktop on my MacBookPro to work on a Windows7 or Windwos10 machine.

This is my settings for AltTab:
<img width="631" alt="Bildschirmfoto 2022-12-31 um 21 19 55" src="https://user-images.githubusercontent.com/96403800/210154956-3fba590e-913c-44b9-88b0-0fb58711d8f1.png">

<img width="637" alt="Bildschirmfoto 2022-12-31 um 21 20 01" src="https://user-images.githubusercontent.com/96403800/210154954-522cb86b-c9f9-47a2-abb7-422780be1831.png">

I understand, that shortcut#2 might prevent me using the | key on my keyboard, when I press "ALT-GR+<":
![keyb](https://user-images.githubusercontent.com/96403800/210155028-ca77aece-a9d1-4ad2-8f17-336ed262e724.jpg)

I'd like to keep the settings for shortcut#1 and shortcut#2, because they work great and are apple "standard" to switch between app-windows and apps.

Is there a way to configure the ALT key on the **right** of the keyboard only to use with the < key ?

**Comment by lwouis** [comment]
No, I'm sorry, currently option/alt triggers with both keys. It's technically possible to detect left or right I believe, but the need is a bit too niche to justify the added complexity (think about how the UI would get complex, to accomodate for people who want _any_ alt vs people who want a _specific_ alt).
