### ISSUE TITLE
Keep Recency, Add Groupings

### ISSUE THREAD

**Issue by turing** [lwouis/alt-tab-macos#2236]
**Is your feature suggestion related to a problem? Please describe.**
I tend to keep.... everything... open nearly all the time, so my machine has a quadrillion little browser windows, text editor windows, spreadsheets, photoshop, terms, etc open at a time. I generally pull a set of windows into a space to perform a task or set or related tasks.

When considering that and a switcher:
- Having the (fixed number, based on row count) ~4 most recently focused windows ordered by last focused is *great*
- But if I'm not mid task, and I'm hunting for something in the pile, I really want to have some groupings to be able to quickly scan all my chrome windows across spaces, or look at what is in each of the spaces.

**Describe the solution you'd like**
- Maintain a fixed number of duplicates of the most recently focused thumbnails
- Separately, below, a display of the windows in other apps grouped by app, or by space, or by space then app. These can be scaled to be identical heights, which will make them very compact visual 'listings'

I would also try to look at strategies for eliminating scrolling, including zooming a thumbnail or section on mouseover that had been scaled >~15% to fit.

**Describe alternatives you've considered**
Unless I'm reeeeally missing something, I don't see a way of achieving what I'd like with the current preferences. They seem to cede presentation control to the user when they should ideally be adaptive to the screen size + the set of spaces, apps and windows.

**Comment by lwouis** [comment]
The grouping seems to be the biggest change you propose. It's discussed in #337
