### ISSUE TITLE
Ability to show standard tabs as windows for certain shortcuts only

### ISSUE THREAD

**Issue by ADTC** [lwouis/alt-tab-macos#2244]
**Is your feature suggestion related to a problem? Please describe.**

I have two shortcuts setup, one to show AltTab for all apps, and another to show AltTab for active app. I find that if I'm in an app with standard tabs, the second shortcut is useless and shows only one thumbnail for the window (not for each tab).

**Describe the solution you'd like**

The ability to enable "Show standard tabs as windows" for certain shortcuts only. In my case, I would keep it disabled for all apps, and enable it for active app. That way, when I use the first shortcut, I only see one thumbnail for the app. But when I'm already in the app, if I use the second shortcut I'd now see separate thumbnails for each tab.

(Of course, this is still subject to the limitations mentioned in #258.)

**Describe alternatives you've considered**

The alternative would be to enable "Show standard tabs as windows" in Appearance, but this applies to all shortcuts. It clutters the view for all apps.

**Comment by lwouis** [comment]
Hi,

I understand the use-case, but i'm afraid it's too niche to get implemented. Other settings could become per-shortcut, but that increases complexity for most users who don't need that. #351 will actually remove some options, in order to better serve most users.

I hope you understand the trade-off at play here 🙇‍♂️

**Comment by ADTC** [comment]
I appreciate the direction you're taking. Surely the current UI has plenty of options which are in a clutter, so a streamlined UI will be a welcome change. (I hope you'll keep the more advanced options available even if they are tucked away in some "Advanced" panel, rather than removing them completely.)

Anyway, if ever in the future the streamlined UI may allow for this in some form, it will be nice to have. But it's not a deal-breaker.

Keep up the good work. I appreciate it! Do you accept donations? (GitHub Sponsors could be an option.)
