### ISSUE TITLE
Terminal tabs are shown as separate windows

### ISSUE THREAD

**Issue by anandrewfiserv** [lwouis/alt-tab-macos#2252]
**Describe the bug**

If I have multiple terminal tabs open, they show up as separate windows (not tabs).

**Screenshots / video**
The settings I am using that exhibit this behaviour.
<img width="551" alt="Screen Shot 2023-01-11 at 09 25 00" src="https://user-images.githubusercontent.com/90014155/211830948-7659f612-625f-4372-88d1-cd43c2047b21.png">

What I see when I press the shortcut.
<img width="612" alt="Screen Shot 2023-01-11 at 09 24 27" src="https://user-images.githubusercontent.com/90014155/211830819-6b42150f-4672-484f-a2e3-1f6ea8cbf244.png">

I also have this other shortcut for the active app and they show up separately as well, which is expected.
<img width="559" alt="Screen Shot 2023-01-11 at 09 26 27" src="https://user-images.githubusercontent.com/90014155/211831254-0083fa50-baed-4561-82a8-2641d8c6c97b.png">

**Steps to reproduce the bug**

1. Set the settings to the above two shortcuts
2. open up the app 'Terminal' and press cmd+t to open up another tab.
3. press the first shortcut -> you will see both terminal tabs (unexpected)
4. press the second shortcut -> you will see both terminal tabs (expected)

**Your environment**

* AltTab version: 6.50.0
* macOS version: 10.15.7
* Other relevant info: n/a

**Comment by lwouis** [comment]
There is a preference in `Preferences > Appearance > Show standard tabs as separate window`. In addition, you may be impacted by this bug: https://github.com/lwouis/alt-tab-macos/issues/2017

**Comment by ianyepan** [comment]
@anandrewfiserv I was experience the same bug, but after updating to macOS Ventura, the issue seems to be fixed.

**Comment by pokrovskyy** [comment]
[v6.61](https://github.com/lwouis/alt-tab-macos/releases/tag/v6.61.0) fixed it for me on Catalina! 🎉 Don't ask why I'm still there tho 😁
