### ISSUE TITLE
Android Studio menu is shifted up after sleep

### ISSUE THREAD

**Issue by guidodavide** [lwouis/alt-tab-macos#2256]
**Describe the bug**
It frequently happens that while using Android Studio, whenever my Mac M1 goes to sleep, upon resumption the only Android Studio UI is compromised. Basically the whole system menu bar is shifted slightly up.
Android menus from the system bar are shifted, basically the mouse cursor is always selecting an entry above its pointer location.

It seems there are some bad interactions between Android Studio and the accessibility service registered by AltTab.
**Screenshots / video**
<img width="781" alt="Screenshot 2023-01-13 at 10 28 58 AM" src="https://user-images.githubusercontent.com/3480319/212287108-8e1e8c77-3da4-48b9-828f-011afcbac88b.png">
<img width="781" alt="Screenshot 2023-01-13 at 10 35 28 AM" src="https://user-images.githubusercontent.com/3480319/212287232-da64b8a8-3593-4108-b061-c948f5f4351c.png">

**Steps to reproduce the bug**
1. Use Android Studio
2. Put the Mac on sleep
3. Unlock the mac and observe
This has not a 100% repro rate, but I can observe it on a daily basis.

**Your environment**
* macOS version:  MacBook Pro M1 Ventura 13.1 (22C65) (it was a problem even on MacOs 12)
* AltTab version: 6.52.1
* Android Studio Dolphin 2021.3.1
* Other relevant info: I'm using two external monitors. I'm using an external usb keyboard.

**Comment by lwouis** [comment]
Hi,

Could you please bring this issue to the Android Studio customer support? It seems it's on their side. AltTab is listening to OS accessibility events, and can't affect other apps UI. If it does, it's either a macOS bug, or a bug in the app itself.

Thank you
