### ISSUE TITLE
iTerm2 not appearing

### ISSUE THREAD

**Issue by Jakobovski** [lwouis/alt-tab-macos#2258]
**Describe the bug**

iTerm2 does not appear as one of the windows to select from despite being open. I am not sure if this is iTerm2 specific but it seems to be the only application with this issue. It is not on the blacklist.

**Steps to reproduce the bug**

1. Open iTerm2
2. trigger alt-tab window switcher using keyboard shortcut

**Your environment**

* AltTab version:  6.51.0
* macOS version: 12.5

**Comment by lwouis** [comment]
Most likely #1324
