### ISSUE TITLE
Problem with the switching window (GUI)

### ISSUE THREAD

**Issue by spunti** [lwouis/alt-tab-macos#226]
Hello!

First I want to thank you for this great tool!

But I notice a strange behavior with the switching window. I am using AltTab on the MacBook Pro 16" with MacOS 10.15.4. 
Attached you can find a picture of the problem. 
![IMG_3255](https://user-images.githubusercontent.com/6967608/78833863-e1c1b580-79ed-11ea-8411-d993f0ab8b5a.jpg)

**Comment by lwouis** [comment]
Hi @spunti! Thanks for sharing this issue!

Are you on the latest version? Yesterday, with the help of some other people on #196, I identified the issue to be linked to Dark Mode. I then released a fix with v3.7.1. Could you please try that version out? It should fix this visual artifact when Dark Mode is enabled.
