### ISSUE TITLE
Hide thumbnails for apps with only one window

### ISSUE THREAD

**Issue by ADTC** [lwouis/alt-tab-macos#2262]
When we have a lot of windows, the sheer number of thumbnails on screen seem to be overwhelming.

I would like an option to "Hide window thumbnails for apps with only one window" so that such apps will just show their icon. Apps with more than one window will show thumbnails.

I have considered disabling window thumbnails across the board.

![image](https://user-images.githubusercontent.com/6047296/213363562-2c5007f6-aa60-4e68-bfe2-6e6f4be9a267.png)

As you can see, to know where the Firefox window I want to switch to is, **I have to read the title.** (I can make the window min width wider to see more of the title. 33% is a good number to show three columns.)

I don't need thumbnails of single-window apps like Fork here, but I do need them for multi-window apps.

PS: Also, the ability to put title above or below icon as in #1827.

**Comment by lwouis** [comment]
I think #337 would work for you, no?

**Comment by ADTC** [comment]
@lwouis for me I didn't think of wanting a hierarchy. I actually don't want to have to drill down multiple levels as it takes time. I still want everything on a flat list.

What I suggested here is to just have thumbnails appear for those apps with multiple windows, like Firefox and TextMate (flower icon) in this example, while those with only one icon could remain with just the icon.

Perhaps an idea would be an option to simply copy the icon and use it as a mock thumbnail for the apps with only one window. That way I can hide the actual icons and enable the thumbnails, but some of the thumbnails would be a snapshot of the app icon, not the screenshot of the window.

If this is doable, kindly consider re-opening ticket.
