### ISSUE TITLE
Thumbnail rows should depend on screenheight or auto 

### ISSUE THREAD

**Issue by muescha** [lwouis/alt-tab-macos#2265]
**Is your feature suggestion related to a problem? Please describe.**

i have a smaller monitor on macbook and a thunderbolt display in portrait mode. 

when i have setup 4 rows then on:
- main screen: the thumbnails have a specific size
- second monitor (portrait):  it is stretched and there is many space between the rows

when i place it to 10 rows then on:
- main screen: i see here 10 rows the thumbnails are shrinked very small  
- second monitor (portrait): thumbnails are in normal size

**Describe the solution you'd like**

i would like to setup the size of the thumbnail (preview card) to a specific size (or height) and then it should fit to the main space i defined about the area on screen.

or rows should be a minimum value -> if the monitor has more height then I would like to see more rows

**Describe alternatives you've considered**

n/a

**Comment by lwouis** [comment]
Supporting multiple monitors has been brought up many times. Please see https://github.com/lwouis/alt-tab-macos/issues/1506#issuecomment-1384556760
