### ISSUE TITLE
Dash window title doesn't update after startup

### ISSUE THREAD

**Issue by lkrms** [lwouis/alt-tab-macos#2275]
**Describe the bug**

Dash (as in [this app](https://kapeli.com/dash)) sets its window title to "Loading..." on startup, and this title sticks around in AltTab until it's restarted. Dash then appears with the title "Welcome!"

**Screenshots / video**

(Sorry about the dodgy blurring. I'll have to figure out something better next time.)

![IMG_0455](https://user-images.githubusercontent.com/2563783/215230921-17081bbd-ae58-4bee-88f0-8463de0d814b.JPG)

**Steps to reproduce the bug**

As above.

**Your environment**

* AltTab version: 6.52.1
* macOS version: 13.2

**Comment by lwouis** [comment]
AltTab listens to title changes, so if it remains "Loading...", it's most likely an issue on Dash's side. Please contact their support 👍

**Comment by lkrms** [comment]
Thanks for getting back to me. I'm not across the API for this at all, so I'm not sure what's relevant and what isn't, but given Dash doesn't actually display the window title anywhere, my best guess would be that something between Dash and Alt-Tab is preventing it from propagating because it's filtered out as irrelevant.

It's more of an annoyance than anything else, but if I happen to figure out a solution I'll flag it here for others.
