### ISSUE TITLE
Menu bar 'Show' shortcut?

### ISSUE THREAD

**Issue by shimo-web** [lwouis/alt-tab-macos#2300]
Is it possible to assign shortcut to have same behavior like clicking on 'Show' option in menu bar? I simply want to AltTab window will stay until I choose the app without holding alt key pressed.

**Comment by lwouis** [comment]
Yes, you can set this preference here:

<img width="573" alt="image" src="https://user-images.githubusercontent.com/106195/217313373-d4417e18-3f73-4f79-aa33-ea636ea615ab.png">

**Comment by shimo-web** [comment]
Thanks so much! I was on the hunt for a way to map my Elgato Stream Deck button to open windows selection. My thumb is tired from hitting the CMD key a million times a day. :D
