### ISSUE TITLE
Can we have different colored borders to easily identify windows of same apps?

### ISSUE THREAD

**Issue by GorvGoyl** [lwouis/alt-tab-macos#2308]
It'd be nice to have different colored rings on all windows so that I can easily identify the window even if it belongs to the same app. To take inspiration, this extension does a similar thing but for VSCode https://marketplace.visualstudio.com/items?itemName=johnpapa.vscode-peacock

**Comment by lwouis** [comment]
I think this need of noticing which windows belong to the same app can already be addressed with:

* Using the app icon. You can make it bigger in the preferences, so it's more obvious which windows share the same app when browser
* #337

**Comment by GorvGoyl** [comment]
@lwouis issue is when there are multiple windows of the same app. see screenshot:

![screenshot 2023-02-09 at 18 34 33@2x](https://user-images.githubusercontent.com/7106086/217801907-438467f8-26a6-44f2-97a9-0d266702bb6b.png)

**Comment by GorvGoyl** [comment]
You want to have AltTab users manually color some windows to distinguish them more easily from others, correct?

manually setting by user is overkill. I was thinking of automatically assign different border colors to each window by AltTab. no user involvement required.

**Comment by lwouis** [comment]
I'm a bit confused? You're saying that you don't want to color windows yourself. Instead, it should be AltTab who does it. How exactly? AltTab would color every single window in a random color, different from color already assigned to other windows? For example, I would open AltTab with 10 windows, and it would look like a rainbow?

Isn't the thumbnail + the title already a quick way to identify the window visually?

**Comment by GorvGoyl** [comment]
> AltTab would color every single window in a random color, different from color already assigned to other windows? 


yes. the problem I'm facing is not able to instantly recognize the particular window of an app as you can see from the screenshot above. colored bordered windows could be one of the ways to fix it. That VSCode extension does the similar thing when multiple vscode projects are open.
