### ISSUE TITLE
Can I replace cmd+tab shortcut by alt-tab-macos?

### ISSUE THREAD

**Issue by stephane-klein** [lwouis/alt-tab-macos#231]
Can I replace cmd+tab shortcut by alt-tab-macos?

If yes

- how?
- I suggest to add this instruction in README.md

Best regards,
Stéphane

**Comment by lwouis** [comment]
You can customize the shortcut by clicking the icon in the menubar:

![image](https://user-images.githubusercontent.com/106195/78952013-137e6d80-7b0f-11ea-8cec-646a4e65c01e.png)

Then open the Preferences, and customize the shortcut there:

![image](https://user-images.githubusercontent.com/106195/78952031-242ee380-7b0f-11ea-9dd9-f22898bf0e3d.png)

Regarding documenting that, another contributor is working on #211 to help with onboarding and documentation for new users :)

**Comment by lwouis** [comment]
Closing this ticket since the feature exist, and the documentation improvement is tracked in another ticket
