### ISSUE TITLE
Add an ability for switching between applications

### ISSUE THREAD

**Issue by Deadricss5** [lwouis/alt-tab-macos#2312]
**Is your feature suggestion related to a problem? Please describe.**

Currently, we can switch only between windows of all Applications. It would be nice to have an ability to switch between applications only. In that case, we can setup shortcuts for switching between apps and for switching between windows.

Example: 
We have two running apps, one window with Browser and five windows with Editor. 
We have next shortcuts: **command+Tab** for switching between apps, and **option+Tab** for switching between windows.
Press on **command+Tab** will show us only two items (Browser and Editor)
Press on **option+Tab** will show us five items in case if selected app is Editor and one item if selected app is Browser.

**Describe the solution you'd like**

Add an ability for switching between applications, not windows of all applications.

**Comment by lwouis** [comment]
I think you could either use the native app-switcher for this (e.g. bind `option+tab` for AltTab and use `command+tab` for the native app-switcher).

If that's not enough, I think #337 could encompass this feature.
