### ISSUE TITLE
Window is not focused upon mouse hover

### ISSUE THREAD

**Issue by XInTheDark** [lwouis/alt-tab-macos#2317]
After the update to 6.53.0, I noticed a behavior change:

Previously, I just needed to activate the window switcher, move the mouse onto a window thumbnail, and that window will be focused.

Now, when I do the same thing, the correct window is not focused. It instead merely focuses the next window in the switcher.
To focus the specified window, I need to click on the window thumbnail.

Is there a setting that brings back the old behavior?

**Comment by XInTheDark** [comment]
Also, I feel that the option in the preferences pane is a bit misleading:

<img width="574" alt="Screenshot 2023-02-11 at 12 29 02" src="https://user-images.githubusercontent.com/61100393/218239884-42f99d58-d0e6-49c1-ba52-05cc1f393c36.png">

It states that I can select windows using "mouse hover", and when I release the keybind, it will "focus selected window", but in fact this is not the behavior now.

**Comment by syrte** [comment]
Thanks for reporting. Same here.

**Comment by XInTheDark** [comment]
It's working properly now, thanks for the quick fix!
