### ISSUE TITLE
Using CMD as a shortcut key does not work on restart

### ISSUE THREAD

**Issue by michaeleadsat** [lwouis/alt-tab-macos#2319]
I'm looking to replace Mac's CMD+Tab function with AltTab, with the hold key being CMD and the select next window key being Tab.

This works whenever I set it up. However, when I restart or log in/out, the computer defaults back into the old CMD+Tab function (where it switches application vs windows). To fix this, I have to go back on AltTab and set the CMD key again each time I log in.

Is there a way to fix this bug? I'm running 6.52.1 and Monterey.

**Comment by lwouis** [comment]
Does it happen only when you restart? What if you restart AltTab, does it also reset the shortcut?

**Comment by michael-johansen** [comment]
Same-ish problem (Version 6.53.1, macos 13.1), restarting AltTab does not work, but "rebinding" the shortcut does. Usually happens after sleep, not necessarily restart (atleast *uptime* hasn't changed).

**Comment by lwouis** [comment]
Is it possible that you are both experiencing this issue: https://github.com/lwouis/alt-tab-macos/issues/2125?

**Comment by michael-johansen** [comment]
More than a week since AltTab was updated, and it did work after the update. Maybe if the circumstance is first sleep/restart after update, but that is pure speculation.
![bilde](https://user-images.githubusercontent.com/1036799/220564750-0310dac5-9538-433b-9ae4-6230bd41d22c.png)

**Comment by lwouis** [comment]
Closing as a duplicate, unless someone knows it's not?
