### ISSUE TITLE
Show AltTab on main screen

### ISSUE THREAD

**Issue by damonpam** [lwouis/alt-tab-macos#232]
Hi,

First, congrats for the great utility. 
It would be great to add the following feature: Show AltTab on the main screen.

![image](https://user-images.githubusercontent.com/12949398/78988192-82b88980-7b30-11ea-9406-892b2ecd537d.png)

Cheers

**Comment by lwouis** [comment]
Hi @damonpam! Thanks for the suggestion!

Could you clarify what you mean by main screen? The current "active screen" is the screen that has keyboard input on. In AppKit, Apple calls it `NSScreen.main`.

I would need a very clear definition in order to help implement what you would like :)

**Comment by damonpam** [comment]
Hi @lwouis!

This scenario occurs when you have more than one display. I guess, the main display is the one which contains the menu bar icon.

![image](https://user-images.githubusercontent.com/12949398/79004885-ec975a00-7b55-11ea-9c4f-420216729d10.png)

In this case, despite having the active application in the small display, when using AltTab the menu should appear in the large display (main display).

I hope this helps.
Thanks :)

**Comment by lwouis** [comment]
@damonpam I'm curious about the use-case. The 2 use-cases supported now are:

* show me AltTab in the screen that has my mouse's attention
* show me AltTab on the screen that has my keyboard's attention

I'm trying to understand why you would want the UI of an app to show on a screen that has the menubar, instead of either keyboard or mouse focused on it. You could be typing text in a window on the small second screen, and you just clicked the textarea, so your mouse is also closeby on that screen, yet you would like to see AltTab pop up on the main screen?

**Comment by lwouis** [comment]
Note that implementing such a preference seems simple. According to the docs:

> The main screen is not necessarily the same screen that contains the menu bar or has its origin at (0, 0). The main screen refers to the screen containing the window that is currently receiving keyboard events. It is the main screen because it is the one with which the user is most likely interacting.
>
> The screen containing the menu bar is always the first object (index 0) in the array returned by the screens method.

So here:

https://github.com/lwouis/alt-tab-macos/blob/master/src/logic/Screen.swift#L7

we could simply add a new line for `NSScreen.screens.first!` which would be the screen with the menubar

**Comment by damonpam** [comment]
@lwouis, many times I use the second screen to see information in different applications but without directly interacting with any of them. For this reason, it is easier for me to know that whenever you press alt + tab, the menu will always appear on the same screen (the menu bar screen).

Despite it being a personal preference, I think switching windows seem faster.

If as you say, it is not very complex, I would be very grateful if you could add this feature. I reviewed the code you mentioned but dunno where to start...

**Comment by lwouis** [comment]
The new release v3.11.0 implements this new feature! Closing the ticket 👍

**Comment by damonpam** [comment]
Thanks a lot @lwouis ! and again, congrats for the app! 💪
