### ISSUE TITLE
Mouse hover can't change app

### ISSUE THREAD

**Issue by zheng-shugan** [lwouis/alt-tab-macos#2324]
**Describe the bug**

Update to v6.53.0 in macOS 13.2, when mouse hover app window can't change the app. So I back to v6.51.0 is work fine

**Steps to reproduce the bug**

1. awaken alt-tab
2. use mouse hover in app window
3. can't change app

**Your environment**

* AltTab version: 6.53.0
* macOS version: 13.2

**Comment by lwouis** [comment]
Please see #2317
