### ISSUE TITLE
Add fade effect to transitions

### ISSUE THREAD

**Issue by anukul** [lwouis/alt-tab-macos#234]
Default MacOS switcher

![default](https://user-images.githubusercontent.com/44864521/79043451-e15b3180-7c1c-11ea-8a46-7d334a973093.gif)

alt-tab-macos

![alttab](https://user-images.githubusercontent.com/44864521/79043546-5d557980-7c1d-11ea-8da5-c0a73d97e05b.gif)

**Comment by lwouis** [comment]
I personally would not want this. I want the snappiest experience possible, and that means no animations. This means this would be another preference in the `Appearance` tab.

**Comment by lwouis** [comment]
It seems that simply changing `animationBehavior = .utilityWindow` on the main window brings an animation

**Comment by anukul** [comment]
Thanks a lot! 🙌
