### ISSUE TITLE
Suggestion: Add "when hidden window" blacklist

### ISSUE THREAD

**Issue by XInTheDark** [lwouis/alt-tab-macos#2348]
I wish to blacklist an app from the window switcher only when one or more of its windows are hidden. i.e. add an option "When window is hidden" to the dropdown list here (found in the "Blacklists" panel): 
<img width="176" alt="Screenshot 2023-02-18 at 13 31 31" src="https://user-images.githubusercontent.com/61100393/219842988-61b40a22-e915-4e1a-a917-243238fcc006.png">

Indeed, this can also extend to the following behavior: that pressing 'H' in the app switcher will also hide the selected window from the switcher itself, meaning that it will no longer be visible in the app switcher. This be a nice setting to have as well, since it reduces cluttering of windows.

**Comment by lwouis** [comment]
I think this preference here may satisfy your use-case:

<img width="568" alt="image" src="https://user-images.githubusercontent.com/106195/219943602-76cd865a-df88-41f9-b320-8c13a9c26c61.png">
