### ISSUE TITLE
Alt-Tab behavior on Mac not consistent after closing apps with cmd+W or cmd+H

### ISSUE THREAD

**Issue by adarc8** [lwouis/alt-tab-macos#2349]
I've noticed a behavior on Mac that can be a bit frustrating. When I close an app using cmd+W and then switch to another app using alt-tab, the app I just closed doesn't show up because it's now the last one in the 'recent apps' list. However, if I use cmd+H to minimize the app instead of closing it, it becomes the last app in the list, and I can switch back to it with one alt-tab press. I understand that this is the intended difference between cmd+W and cmd+H, but I really wish I could change this behavior. Is there a solution to this issue?

**Comment by lwouis** [comment]
I suggest you tweak this preference, so that hidden windows show at the end of the list:

<img width="571" alt="image" src="https://user-images.githubusercontent.com/106195/219943536-4fcbc864-0397-4073-baa3-879d109b721c.png">

**Comment by adar-cohen-imagenai** [comment]
Thank you!
I would prefer instead of changing hidden to be at the end, to actuallly change the closed (cmd+W) to be at the start, like the hidden are. Is it possible?

**Comment by adarc8** [comment]
Thank you!
I would prefer instead of changing hidden to be at the end, to actuallly change the closed (cmd+W) to be at the start, like the hidden are. Is it possible?

**Comment by lwouis** [comment]
No i'm afraid not. Closed windows don't exist anymore for AltTab to report them.
