### ISSUE TITLE
Alt-Tab doesn't handle WezTerm

### ISSUE THREAD

**Issue by 2gn** [lwouis/alt-tab-macos#2350]
**Describe the bug**

When I try to give focus to [WezTerm](https://github.com/wez/wezterm), alt-tab sometimes doesn't recognize it. This issue only happens on WezTerm and no other application have the same issue. 

**Screenshots / video**

![Screenshot 2023-02-19 at 19 41 07](https://user-images.githubusercontent.com/101851090/219942992-14ebac82-5eab-4ff0-ab5c-fc7a0f7f255e.png)

**Steps to reproduce the bug**

1. Open [WezTerm](https://github.com/wez/wezterm) and some other applications
2. Alt + Tab

**Your environment**

* AltTab version: 6.36.0
* macOS version: Ventura 13.2
* On MacOS clamshell mode with external keyboard.

**Comment by lwouis** [comment]
Please open a ticket on the WezTerm project, as it's most likely an issue on their side. AltTab simply reflects the state of apps and windows in the OS.
