### ISSUE TITLE
Option to configure fixed size for windows

### ISSUE THREAD

**Issue by samishchandra** [lwouis/alt-tab-macos#2351]
**Is your feature suggestion related to a problem? Please describe.**
Alt tab only allows for cofniguring the sizes using percentages and not have fixed sizes. The problem is that the window thumbnail sizes quite change depending on the number of active windows. Hyperswitch does a better job at this.

**Describe the solution you'd like**
Can we have a configuration option to specify the size of window thumbnail so that it stays constant irrespective of number of active windows.

**Describe alternatives you've considered**
NA

**Comment by lwouis** [comment]
This will be addressed through #351
