### ISSUE TITLE
Not responding when start the app

### ISSUE THREAD

**Issue by panxnan** [lwouis/alt-tab-macos#2359]
**Describe the bug**
I have updated AltTab to the lastest version, but AltTab is not responding when I just start the app. And the "cmd+tab" doesnt work. I tried to delete it and re-install it, it didnt help. 

Is it any way I can find the logs or somethings? No error code. I really dont know how to find out what happen. 

**Screenshots / video**
![1677047385839.jpg](https://s2.loli.net/2023/02/22/KxkgHmAGoDr47dI.jpg)
![591677048018_.pic.jpg](https://s2.loli.net/2023/02/22/6dlIQ4WwD8ZXiEM.jpg)

**Steps to reproduce the bug**
1. just open the app

**Your environment**

* AltTab version: 6.53.1
* macOS version: Ventura 13.0 Beta 22A5531f

**Comment by lwouis** [comment]
Hi @panxnan,

You seem to be on a macOS Ventura beta. That could explain the issue. Have you faced the issue on other machines, other versions of macOS?

In order to get some logs to debug, could you please generate a Spindump and a Sample here, in Activity Monitor?

<img width="956" alt="image" src="https://user-images.githubusercontent.com/106195/220721936-7f3e3fd2-73ed-4a33-abdf-d9e0014a5148.png">

Thank you

**Comment by panxnan** [comment]
Hi @lwouis ,

Thank you for getting back to me regarding the issue I reported. I appreciate your prompt response.

Since this is my only device, I found that this problem only occur on my machine. I have attached the generated Sample and Spindump files for your reference.

Please let me know if you require any additional information or if there is anything else I can do to assist with resolving this issue.

Thank you for your attention to this matter.

Best Regards. 

[Sample of AltTab.txt](https://github.com/lwouis/alt-tab-macos/files/10810615/Sample.of.AltTab.txt)
[AltTab_Spindump.txt](https://github.com/lwouis/alt-tab-macos/files/10810616/AltTab_Spindump.txt)

**Comment by lwouis** [comment]
From looking at the sample, I see:

> Dispatch Thread Soft Limit: 64 reached in 2129 of 2129 samples -- too many dispatch threads blocked in synchronous operations

There are many threads, from the `axCallsQueue` DispatchQueue. They all look like this:

```
    2129 Thread_6694   DispatchQueue_139: axCallsQueue  (concurrent)
    + 2129 start_wqthread  (in libsystem_pthread.dylib) + 15  [0x7ff8041b0c67]
    +   2129 _pthread_wqthread  (in libsystem_pthread.dylib) + 256  [0x7ff8041b1c9d]
    +     2129 _dispatch_worker_thread2  (in libdispatch.dylib) + 160  [0x7ff804045e6f]
    +       2129 _dispatch_root_queue_drain  (in libdispatch.dylib) + 343  [0x7ff8040456cb]
    +         2129 _dispatch_async_redirect_invoke  (in libdispatch.dylib) + 714  [0x7ff804037bef]
    +           2129 _dispatch_continuation_pop  (in libdispatch.dylib) + 463  [0x7ff804038560]
    +             2129 _dispatch_client_callout  (in libdispatch.dylib) + 8  [0x7ff804035aa4]
    +               2129 _dispatch_call_block_and_release  (in libdispatch.dylib) + 12  [0x7ff80403485b]
    +                 2129 thunk for @escaping @callee_guaranteed () -> ()  (in AltTab) + 25  [0x104b8b509]
    +                   2129 retryAxCallUntilTimeout_(_:_:_:_:)  (in AltTab) + 271  [0x104b6556f]
    +                     2129 partial apply for closure #1 in Application.observeEvents()  (in AltTab) + 25  [0x104b86a69]
    +                       2129 closure #1 in Application.observeEvents()  (in AltTab) + 233  [0x104b860b9]
    +                         2129 _AXObserverAddNotificationAndCheckRemote  (in HIServices) + 43  [0x7ff809a67a08]
    +                           2129 _AXObserverAddNotification  (in HIServices) + 1055  [0x7ff809a67930]
    +                             2129 _os_nospin_lock_lock_slow  (in libsystem_platform.dylib) + 107  [0x7ff8041df6e6]
    +                               2129 __ulock_wait  (in libsystem_kernel.dylib) + 10  [0x7ff804177e06]
```

I'm not sure what to make of it yet. Maybe @decodism, you would have an idea of could be at play here?

**Comment by lwouis** [comment]
Thank you @decodism. I'll close this ticket since it's on a beta of macOS. If the issue persists with the official release, we'll re-open and dig deeper 👍

**Comment by panxnan** [comment]
Thanks. Bug fixed after I updated to the lastest os version. :)
