### ISSUE TITLE
Another shortcut to switch windows in the same app

### ISSUE THREAD

**Issue by txchen** [lwouis/alt-tab-macos#237]
Thanks for making this awesome tool! So far it is running very fast and stable on my laptop!

Is it possible to add another shortcut like (alt + \`), to switch windows in the same app? FYI, hyperswitch has this feature.
We can use system's cmd+`, but that one does not have preview window and always switch to the next windows in a cycle order.

Thank you!

**Comment by PLanB2008** [comment]
Isn't this already part of macos by default? I can switch between windows of the active application by hitting CMD and ^.

**Comment by lwouis** [comment]
Hi @txchen! Thanks for the feedback!

We discussed this previously in #72. You can see towards the bottom the UI I suggested. However, during implementation of this and many other keyboard related tickets, I didn't include the button to add more shortcuts. It would be quite a complex addition in terms of code, and I wonder how many people need *both* global switch and local switch.

I think it would help if you explained in more details your workflow, and how the feature would fit in. You may also share a PR of course ;p

**Comment by mfn** [comment]
> and I wonder how many people need _both_ global switch and local switch.

I'm basically waiting for this 😄  Currently running AltTab for CMD-Tab and HyperSwitch on CMD-~

I was so reliefed/delighted that HS had this. I constantly work with multiple Windows of applications (multiple Firefox, multiple IntelliJ, multiple Iterm), for me it's (personal) "must have" and of course the thumbs are great for that.

**Comment by txchen** [comment]
@lwouis thanks for your reply! I usually open a couple vscode windows for different projects, and multiple chrome instances for different profile. I often need to switch to another vscode/chrome.

cmd+` can cycle them, but IMO it's better to have a preview like AltTab or HyperSwitch, which gives me a more precise control.
