### ISSUE TITLE
More contrast when rotating through windows in dark mode.

### ISSUE THREAD

**Issue by JohnKnoepfle** [lwouis/alt-tab-macos#2379]
I always use dark-mode on all my machines.   When I invoke alt-tab and it shows me all the open windows, there is not much contrast around the currently selected window as I cycle through them.

My suggestion is to show the selected window tile with more contrast so it stands out a bit more.   Possibly adding a preference for color (i.e. a red box) around the currently highlighted window tile.

**Comment by lwouis** [comment]
Please use the Windows 10 theme in Preferences > Appearance, for better contrast. This has been discussed in other tickets if you want to see why changing the background color is non-trivial.
