### ISSUE TITLE
Adding an Alt-Esc-like Shortcut, Cycling windows in reverse order

### ISSUE THREAD

**Issue by smusaitif** [lwouis/alt-tab-macos#2387]
**Is your feature suggestion related to a problem? Please describe.**
No

**Describe the solution you'd like**
On Windows, I really liked using both Alt-Tab and Alt-Esc when working with several windows.

Alt-Esc lets you cycle through open windows but in reverse order. I would like to suggest a feature enhancement that would allow us to assign a shortcut to make Windows' Alt-Esc-like capability possible. Having the ability to cycle through windows with both the traditional Alt-tab and Alt-Esc would be great way to allow users to easily switch back and forth between previously opened windows.

**Describe alternatives you've considered**
I have tried to mess with the available Alt-Tab settings and did not see this available. I have also attempted to replicate the Alt-Esc behavior using a BTT shortcut with an AppleScript action to no success.

**Comment by lwouis** [comment]
Hi,

I'm a bit confused. I believe on Windows, as with AltTab, `alt+escape` closes the UI. I believe on Windows, you use `alt+shift+tab` to cycle backwards. With AltTab, by default, you use `alt+shift` to cycle backwards.

You can customize everything in Preferences > Controls, to suit your preferences. On this screenshot, I have customized the shortcuts to do exactly what you would like, and it works:

<img width="686" alt="image" src="https://user-images.githubusercontent.com/106195/222780460-a8eb4c1c-8527-4d82-86ee-85837a6047df.png">

Thank you
