### ISSUE TITLE
How not to show, esc close the window into the background of the application

### ISSUE THREAD

**Issue by 0nion1** [lwouis/alt-tab-macos#2391]
How not to show, esc close the window into the background of the application

**Comment by lwouis** [comment]
I don't understand your question. Please make an effort to write a nice clear message. You erased the template that's meant to help you, and help us.

**Comment by 0nion1** [comment]
When switching windows how to set not to show the programs that have esc, these programs are not quit, but I have closed the window so that they are running in the background.

**Comment by lwouis** [comment]
Please check the last checkbox on this tab of the preferences:

<img width="686" alt="image" src="https://user-images.githubusercontent.com/106195/222921552-c3614b6a-d2e3-40b4-aea0-a27833e5719e.png">
