### ISSUE TITLE
Automatic Update / Jamf Pro

### ISSUE THREAD

**Issue by ChrisLQ** [lwouis/alt-tab-macos#2394]
Hello Everyone,

i am deploying this tool via Jamf in our Company, is there a Option to deacitvate the autimatic update  ? Do anyone has the same Problem ? Thank you for your answers in advacne.

**Comment by lwouis** [comment]
Hi @ChrisLQ,

In the app's preferences, you can disable automatic updates:

<img width="686" alt="image" src="https://user-images.githubusercontent.com/106195/223056823-fa699470-2765-4489-9299-9d05725e5f5f.png">

This sets a value in the app's preferences: `SUEnableAutomaticChecks = 0`

The app uses standard [macOS UserDefaults](https://developer.apple.com/documentation/foundation/userdefaults) to store preferences. Thus, there is a way to set the value using command line: `defaults write com.lwouis.alt-tab-macos SUEnableAutomaticChecks 0`.

You can probably run that command after installing AltTab, as part of your JAMF setup. It would disable update-checks before the user even opens the app.

I hope this helps.

Thank you
