### ISSUE TITLE
Continuous cycling of windows

### ISSUE THREAD

**Issue by bishshoy** [lwouis/alt-tab-macos#2395]
**Is your feature suggestion related to a problem? Please describe.**
The following is regarding the default app switcher on macOS. Normally when hitting Cmd+Tab and then continue holding Cmd, the default macOS app switcher will select the next app's icon but not switch to it. If I am not wrong, AltTab does not alter this behavior.

**Describe the solution you'd like**
What I want is to have the app come to foreground immediately on pressing Cmd+Tab (even if I don't release Cmd), and then as I continue pressing Tab...Tab...Tab, the selected apps continue coming in to the foreground.

Like if I press Cmd+Tab once and keep holding Cmd without releasing it, then the app that's supposed to come to foreground upon releasing Cmd, comes to the foreground without releasing Cmd. Invoking Tab further, cycles through the list of opened apps as a menu but also keeps on making the selected app come to foreground.

**Describe alternatives you've considered**
None.

**Comment by lwouis** [comment]
I think maybe https://github.com/lwouis/alt-tab-macos/issues/967 could fullfill your needs. In general, this seems a bit too niche to be implemented. Most people are looking for the Windows alt+tab experience, and also something that feels like macOS, which means not too different from the native app switcher.
