### ISSUE TITLE
Maximize a hidden window with a gesture or keyboard shortcut

### ISSUE THREAD

**Issue by Solarli0n** [lwouis/alt-tab-macos#2398]
Hello! I managed to slightly improve the functionality of the application for my request, you may be interested in it.
It's a little weird, but it works)
I really wanted to be able to expand a hidden window using a keyboard shortcut or touchpad gesture.
None of the apps I've tried do this. I have been looking for a solution for a very long time and it seems I succeeded.
So, with the help of Automator, I created an application in which I recorded a keyboard shortcut consisting of only two sequences (the keyboard shortcut 'option' + '[' and the key ']').
I assigned the same keyboard shortcut to the "maximize window" function in AltTab.
After that, I used the Multitouch application to invoke the created application using the Force Touch gesture on the touchpad.
As a result, by pressing with force on the touchpad, I can expand the last minimized window. It's insanely convenient! It will be very cool if such functionality appears in the application, but for now you can use my method.
Best regards, Dmitry.

<img width="1290" alt="Управление 2023-03-07 19-14-45" src="https://user-images.githubusercontent.com/127236729/223514795-151545cb-3ace-4a64-bf25-e4af6d6ba489.png">

<img width="1610" alt="Открыть 2023-03-07 19-17-34" src="https://user-images.githubusercontent.com/127236729/223514831-1154e136-815a-4df3-b588-c72492b62b25.png">

<img width="1800" alt="Развернуть app (Программа) 2023-03-07 19-18-04" src="https://user-images.githubusercontent.com/127236729/223514837-6e943266-4d5d-472d-90bb-9f1be947585c.png">

![Monosnap 2023-03-07 19-15-56 png 2023-03-07 19-21-58](https://user-images.githubusercontent.com/127236729/223515622-96aec113-02cc-4be8-ae13-0a9c4ef1596d.jpg)

**Comment by lwouis** [comment]
Hi,

Thank you for sharing this work flow. I don't think it can be integrated into AltTab as it's quite a different idea from what AltTab aims to do. It's cool to integrate it with other apps like you did. I can suggest to look into BetterTouchTools for such integrations as well. It's wonderful.

Thank you
