### ISSUE TITLE
Thumbnails are ordered by z-axis, not recently-used-first

### ISSUE THREAD

**Issue by lwouis** [lwouis/alt-tab-macos#24]
If you switch to an app via the dock icon, all windows of that app become ‘recently used’ in the alt-tab menu.

The documentation for the kCGWindowListOptionOnScreenOnly constant says:

> List all windows that are currently onscreen. Windows are returned in order from front to back. When retrieving a list with this option, the relativeToWindow parameter should be set to kCGNullWindowID.

Original author on [this HackerNews thread](https://news.ycombinator.com/item?id=21256369)

**Comment by lwouis** [comment]
The order is entirely handled by macOS. I mean the API used to retrieve the windows is already ordered by recent use. That means that the only solution to workaround this issue would be to handle the order on our side. This has 2 issues:

1. When launching alt-tab, the app has no way to know what preceded its launch, so previous order is still up to the system so still the issue will exist at that point in time.

2. We would rely on other OS APIs to know when another window is focused. Maybe these APIs don't exist. Maybe these APIs are expensive and we would be taxing the machine performance/battery spying on every event from other apps.

**Comment by lwouis** [comment]
I tested and both HyperSwitch and WindowSwitcher have he same issue.

**Comment by lwouis** [comment]
I'm investigating doing a big rewrite for v3. That would involve stopping the use of the CG (CoreGraphics) family of APIs in favor of AX (Accessibility) APIs.

How I imagine it: the app boots, then looks in the current Space for all running apps. It then use `AXObserver` to observe all those apps for changes such as quitting the app, closing/opening a window, and changing focus to another window. Using these deltas, we can build a chronology of windows the user interacted with. Moving to another space would also be listened to, and would trigger the app to check if the space has been visited before, and if no, observe everything there.

This approach would close this ticket, as well as provide a more robust foundation going forward, as we are currently sitting on top of a pile of hacks.

The downside would be that on startup, we don't have a complete view of the system (i.e. other spaces contents). However I would argue that it's ok. We can add "launch on startup" to the app, and the problem fixes itself as the user uses the OS and the app catches up with what the system state in other spaces.

**Comment by mckennajones** [comment]
Hey @lwouis, really been loving this tool, so thanks for all the work you've put into it. I was hoping to outline a use case that might be covered by the rewrite you mentioned above. 

I often find myself alt-tabbing between spaces using your tool. Let's say I'm in space A, then I alt-tab to an application in space B. Ideally, if I alt-tab again the first application in the list would be the one I came from in space A. But, if space B has other applications open, then those will be shown before my app in space A. 

It seems like the same issue here is that the apps are not ordered by the order in which they were recently used.

**Comment by lwouis** [comment]
@mckennajones hi and thanks for the feedback!

In v3, i implemented the behavior you describe. Basically time-based instead of z-index based. Once v3 is released (as soon as we have an icon ready in #99), you will be able to switch spaces and go back to a previous space without the space switch messing the time-based ordering :)

**Comment by mckennajones** [comment]
@lwouis wonderful! I'll anxiously be awaiting that release :)

**Comment by mckennajones** [comment]
@lwouis Just wanted to give you and whoever else contributed kudos on the newer releases, this issue is definitely resolved and it feels much snappier. Cheers.
