### ISSUE TITLE
Calendar app's icon does not match icon in dock that shows current date

### ISSUE THREAD

**Issue by DaveBurns** [lwouis/alt-tab-macos#2401]
**Describe the bug**

I typically hide my Dock and the calendar app until I need it. With the standard Mac app-switcher, if I need to know today's date, I have muscle memory of typing Cmd-Tab, seeing the Calendar app's icon (which is dynamically updated to reflect the current date), then Cmd-Esc to dismiss the switcher. This doesn't work with Alt-Tab. The Calendar app's icon always shows Jul 17 (the default icon for the app) when using Alt-Tab. Looking at the Dock does show an icon with the current date.

**Steps to reproduce the bug**

* Ensure both Alt-Tab and Calendar.app are running
* Press Cmd-Tab.
* See that the Calendar app's icon does not match today's date like it would with Mac's default switcher.
* Look in the Dock to see Calendar's icon with today's date.

**Your environment**

* AltTab version: 6.55.0
* macOS version: 13.2.1
* Don't know if it's relevant but I have two monitors, each 3840x2160.

**Comment by lwouis** [comment]
Hi @DaveBurns,

I'm afraid this is a limitation of macOS APIs.

Currently, AltTab uses the API [`NSRunningApplication.icon`](https://developer.apple.com/documentation/appkit/nsrunningapplication/1529885-icon). This API returns an image, which I guess comes from the icon bundled inside the app. A Static icon. This API doesn't seem to be able to grab the live, dynamic icon shown on the Dock.

I also looked at the other, more obscure API that AltTab uses to grab the red notification badges on the Dock icon. The Accessibility APIs we use are a bit more complex. We use `AXUIElementCreateApplication` and various digging methods. However, using the Accessibility Inspector, we can quickly conclude that the icon is simply not available:

<img width="699" alt="image" src="https://user-images.githubusercontent.com/106195/223854689-11b298f9-ccbf-4cc2-94ff-877c0524ee3b.png">

There may be a private API to grab the icon, but I'm not aware of it. If you know of a way to implement it, please do let me know, and I'll look into implementing it. For now, it seems like it's simply not possible to do it with the public APIs.

Thank you

**Comment by DaveBurns** [comment]
I figured it might be a private API. I'm an experienced dev but I've never worked in any Apple environment so I doubt my abilities to help out. At least this is logged here for future historians. :-)

db
