### ISSUE TITLE
Always show finder option 

### ISSUE THREAD

**Issue by Ishaanrathod09** [lwouis/alt-tab-macos#2423]
**Is your feature suggestion related to a problem? Please describe.**
when apps are running and dont have any windows open, they are still shown in the switcher, which is not the case with finder.

**Describe the solution you'd like**
A option which we can toggle to either show the finder(always) in the switcher or not.

**Describe alternatives you've considered**
I always keep one window of finder open as of now so that i can easily naviagte back to finder through the switcher

**Comment by lwouis** [comment]
You can see Finder if you remove it from the blacklist in the preferences, blacklist tab 👍
