### ISSUE TITLE
The setting is not reflected when the shift key is pressed in the key setting.

### ISSUE THREAD

**Issue by hokut-o** [lwouis/alt-tab-macos#243]
It looks like this.
![out](https://user-images.githubusercontent.com/10446161/79567617-82e7f480-80ef-11ea-9d8a-c63a9d8d4860.gif)

**Comment by lwouis** [comment]
Hi @hokut-o! Thank you for sharing this issue!

This is intended behavior. The first shortcut accept modifier keys only. For example `alt` or `alt+cmd`. The 3 shortcuts on the right accept either non-modifier key like `tab` or `t`, or mix-keys like `shift+tab` or `shift+t`. They don't accept modifiers-only like `shift`.

That being said, I tried to remember why these restrictions exist and couldn't find a good reason. I made the change to allow what you want locally and I couldn't find a problem with that.

I will release an update that allow your use-case today 👍

Note: It seems that you have your mac set with the Japanese language. It looks a bit freaky with half in Japanese and half in English.

If you want to help localize the app in Japanese, you can just go to [here](https://poeditor.com/join/project/8AOEZ0eAZE) and type the correct Japanese text. It's very easy and fast 💯

**Comment by hokut-o** [comment]
Hi @lwouis . Thanks for the quick reply and improvement!
I would like to participate in a translation project.
I was able to log in.
![image](https://user-images.githubusercontent.com/10446161/79676610-c7c07800-8222-11ea-80b4-69772d20f784.png)

**Comment by hokut-o** [comment]
I was able to access the edit page.
Thank you.

**Comment by lwouis** [comment]
@hokut-o cool :)

By the way, did the new release of AltTab fix your issue?

**Comment by hokut-o** [comment]
@lwouis 
I've solved the issue!
Thanks for the quick resolution:grin::+1:
