### ISSUE TITLE
Opens two applications after a restart or shutdown

### ISSUE THREAD

**Issue by danielbuubble** [lwouis/alt-tab-macos#2446]
**Describe the bug**

When ever I turn my pc on after a restart or shutdown, the app starts itself after login because I have check marked the box. But when the app is opening itself up, it opens two of the program. I can see two icons at the menu bar, so when I am alt-tabing, the program glitches itself. And I have to manually close one program down, for it to work again properly. 

**Steps to reproduce the bug**

1. Shutdown PC
2. Log in and have it automatically open after a log in
3. Have enabled icon showing on menu bar
4. See that two icons is showing
5. Try Alt Tab, and you will se it glitches itself out

**Your environment**

* AltTab version: 6.56.00
* macOS version: Ventura 13.2.1
* Other relevant info: e.g. using external keyboard, multiple monitors, etc

**Comment by lwouis** [comment]
The same version of AltTab can't open twice. This means that you somehow have 2 different versions of AltTab installed on your machine at once. I suggest looking in your Downloads and Applications folder to find those. You can also locate where the apps are by using Activity Monitor, as such:

<img width="794" alt="image" src="https://user-images.githubusercontent.com/106195/228551993-969650e9-b363-4054-83e3-df89a5eb1968.png">

**Comment by danielbuubble** [comment]
<img width="1526" alt="Screenshot 2023-03-29 at 15 36 32" src="https://user-images.githubusercontent.com/116361422/228555629-73d09b6b-9274-449b-bdb9-c8f11d23e9bc.png">
Could not upload the screenrecording because the file was to big. But here is a screenshot from the recording. You sure alt tab cannot open two window of the same version? I have checked my application folder and download folder, and I can only see one app.

**Comment by lwouis** [comment]
You can try to reopen AltTab manually and you'll see that it only shows the Preferences panel. It doesn't start a new instance. Now we have seen this before: https://github.com/lwouis/alt-tab-macos/issues/1840 and we have no clue what in the OS triggers it.

Could you show in Activity monitor, which process is the parent of each of those AltTab instance? You can just click the rows in Activity monitor and get more info (like on my screenshot above, but first tab of the panel then).

**Comment by danielbuubble** [comment]
<img width="1470" alt="Screenshot 2023-03-30 at 20 19 31" src="https://user-images.githubusercontent.com/116361422/228928423-03712869-652b-4d0e-af7c-b32e0fbe1112.png">
Is this the screenshot of what you were asking for? (Lifelong windows user that just switched to macos, sorry for the 
inconvenience)

**Comment by lwouis** [comment]
Thank you for your help @danielbuubble. This is what I was asking for.

Could you please open Terminal.app and paste this command?

```sh
ls ~/Library/LaunchAgents/com.lwouis*
```

Press return, then share the results here?

Thank you 🙇

**Comment by danielbuubble** [comment]
<img width="1470" alt="Screenshot 2023-03-30 at 21 25 57" src="https://user-images.githubusercontent.com/116361422/228942986-f8430e53-96a7-4d16-9a0a-9899a524e4f2.png">

**Comment by jcoddaire** [comment]
I think I figured this out. I have alt-tab installed via homebrew, tested on both an intel i9 and M1 max macbook pros.

Mac OS 13.3.1
Alt Tab 6.56.0

The application checkbox `General > Start automatically` was checked. **There was also a setting under `System Settings > General > Login Items > Open at Login`**. 

Therefore two instances was spawned each time the user logged in. Which results in odd, glitchy behavior.

To fix this I unchecked the `Start at login` box for the Alt Tab preferences, and left the "launch at login" setting for macos preferences.

Hopefully this helps someone else. This may resolve issue 1840 too, that's what led me from google to here.

**Comment by lwouis** [comment]
Thank you for sharing these findings @jcoddaire

You have been using AltTab for a long time, no? A long time ago, AltTab would add itself to the Login Items when the checkbox was checked. Then, i think around the arrival of Catalina, Apple broke that API, and AltTab moved to using another API which doesn't show the login item in the list.

What surprises me is that i added migration code, so that existing user got the Login Item removed and the new system used instead.
