### ISSUE TITLE
Do not list a floating/always-on-top window in the switcher

### ISSUE THREAD

**Issue by caioquirino** [lwouis/alt-tab-macos#2448]
**Is your feature suggestion related to a problem? Please describe.**
I am really satisfied with this app, it is working very similarly as the standard Windows alt+tab, but the only thing that annoys me a bit is the fact that always when my MS Teams meeting lose focus, it opens a floating window that gets the second focus, so I have to Alt+Tab twice to go to the next window. In a nutshell, when I have the floating MS Teams window, I have to press Alt+Tab twice to go to the next window.

**Describe the solution you'd like**
I would like to be able to ignore the floating / always-on-top windows as they are always showing up anyway, or fix the focus order for them so it don't mess with my Alt+Tab order

**Describe alternatives you've considered**

1. Make possible to ignore all the floating windows
2. Make possible to ignore specific floating windows (like the blacklist way)
3. Correct the focus for the floating windows so they are not stopping the single-alt+tab from changing to the previous window

**Comment by caioquirino** [comment]
@lwouis Then I would say it is a bug because when I open a MS Teams meeting and lose its focus, a floating window appears and that is influencing in the Alt-tab behaviour. Do you need any help to reproduce the steps?

**Comment by lwouis** [comment]
> a floating window appears and that is influencing in the Alt-tab behaviour

It influences AltTab because it's a full-on window. If you think it shouldn't be a window (and thus AltTab should ignore it), then please contact Microsoft and ask them to change that window to a floating panel, HUD, etc. Basically not a main window, but a helper UI element.
