### ISSUE TITLE
Disable App Switching Animations (space transition animation)

### ISSUE THREAD

**Issue by ndbeals** [lwouis/alt-tab-macos#2458]
Love this app, it's a must-have for me.

I hate the MacOS transition animation when switching from one space to another (or switching from a fullscreen app), it's slow and jarring.  Yes I have tried the "Reduce Motion" setting, and it helps, but it could be better.

I'd like if alt-tab-macos could bypass triggering that space transition animation altogether. An instant application without any animations at all would be ideal for me.

TotalSpaces3 implements it's own method of changing spaces with it's own custom animations, it appears to be theoretically possible.

FWIW I'm a professional software engineer and I'm capable of implementing this with the right direction (I'm brand new to Macs entirely)

Thank you

**Comment by lwouis** [comment]
Hi,

AltTab integrates in macOS. It asks the OS to focus the window, and the OS decides to do animations, timing, show UI elements, etc. AltTab is no longer involved after the call to focus.

Removing animations for Space transitions is a system-wide change that user can do. It's outside the scope of AltTab i'm afraid.

Thank you

**Comment by ndbeals** [comment]
Ahh I see, thanks for the quick response :)
