### ISSUE TITLE
Not switching to Cisco WebEx meeting window when selected via Alt-Tab

### ISSUE THREAD

**Issue by cmcgrew** [lwouis/alt-tab-macos#2466]
**Describe the bug**

When trying to switch to my open WebEx meeting window, I can see the focus goes to WebEx Meetings in the top bar but it does not show the window, I have to manually go click on either the icon or the window.

**Screenshots / video**
Cannot provide screenshot due to privacy concerns.

**Steps to reproduce the bug**

1. Join Cisco WebEx Meeting (can be your personal room)
2. Switch to a different open window (I.e. Chrome)
3. Attempt to switch back to the WebEx meeting.

**Your environment**

* AltTab version: 6.54.0
* macOS version: 12.6 Monterey
* Other relevant info: Using M1 Mac Book Pro. Only happens with WebEx Meeting.

**Comment by lwouis** [comment]
I believe this issue lies with Cisco WebEx Meeting. Could you please contact their support so they fix it?

Thank you 🙇

**Comment by cmcgrew** [comment]
WebEx Desktop Version: 42.6.7.13

**Comment by cmcgrew** [comment]
> I believe this issue lies with Cisco WebEx Meeting. Could you please contact their support so they fix it?
> 
> 
> 
> Thank you 🙇 

It works with the default Cmd+Tab functionality so they probably won't do anything about it.

**Comment by pushkarajthorat** [comment]
I can confirm that there is an issue with CISCO webex . It does not bring front the meeting window when meeting is started

**Comment by abhinavd** [comment]
I have this issue too. Is there no workaround?
