### ISSUE TITLE
Quick swap most recent and current apps without releasing the modifier

### ISSUE THREAD

**Issue by eugenesvk** [lwouis/alt-tab-macos#2468]
**Is your feature suggestion related to a problem? Please describe.**
One of the best way to compare things visually it to have similar text/images 'swap' in the same location on the screen.
However, currently Alt-Tab requires you to release the modifier to achieve that, so fast repeatable swaps are cumbersome

**Describe the solution you'd like**
Allow holding the modifier and trigger only on release of the other key

  - Hold modifier <kbd>⌘</kbd>
  - Tap <kbd>⭾</kbd>
  - Your 1st app switches to the most recent 2nd app (like would happen when you press and release <kbd>⌘</kbd><kbd>⭾</kbd>)
  - Tap <kbd>⭾</kbd>
  - Your 2nd app switches to the 1st app
  - Tap <kbd>⭾</kbd>
  - Your 1st app switches to the 2nd app
  - Release modifier <kbd>⌘</kbd>

The switcher itself should never appear (I think current apparition delay should suffice since you're never expected to hold <kbd>⭾</kbd> in this scenario)

**Describe alternatives you've considered**
Using some scripting solution to bind this behavior to a keybind

**Comment by lwouis** [comment]
I'm not sure to understand.

what's wrong with pressing alt+tab quickly, seeing the previous window, pressing alt+quickly, seeing the other window > repeat? That's what people do on Windows and even on mac using command+tab.

I think it would want more comparative power, the best way is side-by-side.

You may also use the new Preview feature in AltTab (checkbox at the bottom of the Appearance tab) to preview things quickly.

Beyond these 3 solutions, i don't think we can rethink the keyboard logic as you mention. It's a bit of a niche request i'm afraid, so can't consider it until there are many people asking for it

**Comment by eugenesvk** [comment]
> what's wrong with pressing alt+tab quickly, seeing the previous window, pressing alt+quickly, seeing the other window > repeat?

You can't press it quickly enough not only because of weird location of the keybinds, but also because you have to be mindful of the key press order, so your switching frequency drops. On the other hand, spamming a single key is always fast for any finger

> That's what people do on Windows and even on mac using command+tab.

People do all sort of suboptimal things, but then some other people use Autohotkey on Windows to implement the fast swap approach with a single key tap

> I think it would want more comparative power, the best way is side-by-side.

This is also much worse, the ability to spot dynamic changes in a single spot is far superior to having to move your eyes to achieve the same (since then too many things change). Try it on some great image comparion website like this one https://eclipseo.github.io/image-comparison-web/#abandonned-factory*3:1&AOM_3.1.1=t&Original=s&subset1 and use <kbd>⇧</kbd> to quickly swap betwen the images. 


> You may also use the new Preview feature in AltTab (checkbox at the bottom of the Appearance tab) to preview things quickly.

But the switcher window overlays the app window, for this to work I'd need to be able to change the apparition delay on a per-shortcut basis to permanently suppress the switcher.
Also, this involves two keys and not limited to two apps, so it's easier to mistakenly switch to the wrong one. Otherwise it's a passable workaround

> Beyond these 3 solutions, i don't think we can rethink the keyboard logic as you mention. 

Would at least adding per-shortcut apparition delay to have the ability to suppress switcher completely be possible?

> It's a bit of a niche request i'm afraid, so can't consider it until there are many people asking for it

Ok, could you keep the feature request open to make the discovery easier for those many other people?

**Comment by lwouis** [comment]
I think your best bet here is to use a tool like BTT to bind a single key to send alt+tab. That way you get exactly what you want. It should also be fast enough that you don't even see the UI (even without appearance delay)

**Comment by eugenesvk** [comment]
I'm doing that via Karabiner-Elements, and single key is a nice benefit, and yeah, even the default app picker didn't show up
(though there seems to be some bug with trying to use a key combo with modifiers, the app picker shows up and doesn't hide)

It's just that it's such a great feature (even if relatively unknown) that I thought would be nice for your app to have it
