### ISSUE TITLE
For Finder & Preview, consider multiple tabs in 1 window as 1 window 

### ISSUE THREAD

**Issue by vfl97** [lwouis/alt-tab-macos#2477]
**Describe the bug**
For Finder or Preview, I set open new windows as tabs, so that I don't get lost in multiple windows. But alttab still considers each tab as an window, so even if I have 1 Finder window open but multiple tabs, AltTab shows the tabs as separate windows.

Is there a way to change altTab's behaviour? It looks very cluttered and that's the reason why I often use the inferior cmd+Tab for switching apps instead, but altTab to switch between windows of the same app. I only have 1 window for each app, except Brave (3 windows). It' so cluttered, I even have to scroll down in altTab to access the last used window. 

**Screenshots / video**

![collage](https://user-images.githubusercontent.com/15114846/231843444-eed17e06-13c3-4070-b020-ed2320e4dca0.jpg)
![Bildschirmfoto 2023-04-13 um 20 05 40](https://user-images.githubusercontent.com/15114846/231846353-2aae20fd-ff24-4cf3-b0ad-a703890178bd.png)

**Steps to reproduce the bug**

1. In Finder settings: set open in tabs instead of new window
2. alt Tab

**Your environment**

* AltTab version: 6.56.0
* macOS version: 12.6.5 Monterey
* Other relevant info: e.g. using external keyboard, multiple monitors, etc

**Comment by lwouis** [comment]
Yes, you can check the checkbox at the bottom of the preferences here:

<img width="686" alt="image" src="https://user-images.githubusercontent.com/106195/231855264-f53d31c5-8dee-4e24-9832-f232395e96b9.png">

This will show tabs as individual windows. Note that it only works with standard tabs. Finder and Preview use standard tabs, so it will work. Apps like Chrome or Safari uses custom tabs, so these won't show individually.

**Comment by lwouis** [comment]
I think you're seeing consequences of #1324, which is a technical limitation on the newer macOS which there is no way to deal with currently, unfortunately.
