### ISSUE TITLE
Display thumbnails below macOS app-switcher

### ISSUE THREAD

**Issue by kbysiec** [lwouis/alt-tab-macos#248]
Hi, 
in the beginning, I would like to thank you and congrats for a great app. It is very useful.

The only thing I miss from previously used Hyperswitch is displaying thumbnails in default App Switcher (cmd + tab). Would it be a big effort to implement such functionality? Do you consider this at all?

Have a look at below short video presenting the feature I described:

![hyperswitch_small](https://user-images.githubusercontent.com/26285420/79669217-4b924a00-81ba-11ea-8bb9-be08facd62cd.gif)

**Comment by lwouis** [comment]
Hi @kbysiec!

To be honest I think this will probably not happen. The complexity of such a feature is through the roof. The OS gives us **no API** to get information regarding the built-in app-switcher. I think the HyperSwitch creator did an amazing retro-engineer work to achieve the feature. He must have spent months disassembling macOS binaries on his machine to understand the inner workings of the OS.

Combined with the fact that it's so challenging, I also feel that such functionality is directly in opposition with the main UX of AltTab which shows you everything directly and immediately, with large thumbnails. In your video example, look how small the thumbnails are. I feel at this point I would rather use the built-in UX of pressing `cmd + tab` then pressing `down arrow` on the app icon to do Expose on that app. This built-in UX is fully keyboard compatible too for some reason, unlike normal Expose.

**Comment by kbysiec** [comment]
Hi @lwouis! Thank you for the detailed explanation. In case there is no API it is clear for me that it would be very challenging and at the same time not worth digging.

I am keeping my fingers crossed for the project.

**Comment by lwouis** [comment]
As discussed, I think could be its own separate app as the features and workflow is separate from what AltTab does today. I'll close the ticket for now. Feel free to re-open or discuss it more if you feel there is still potential here
