### ISSUE TITLE
Suggest adding a specific area that can be displayed in the small window when switching windows

### ISSUE THREAD

**Issue by CryptoSun1989** [lwouis/alt-tab-macos#2484]
Hello
    I am a multi-chrome account user and often need to have more than 10 chrome accounts open at the same time, but when I switch windows with alt-tab, it always confuses me because I can't tell which is the window I need to open.
So I suggest adding a feature that shows the content of a specific area in the small window where i switch windows. For example, each of my chrome windows has a different avatar, so if I can clearly see my chrome avatar for each window in the window bar, I can easily tell which window I should click on.
I'm sure this feature will be useful for other workers as well, zooming in on special areas will allow us to easily identify each window,Looking forward to your response.
<img width="1112" alt="WeChat7fbf087de8558c67981a8d4314a294dc" src="https://user-images.githubusercontent.com/87864605/232179578-cb3cc42a-553b-468a-8545-65f7e988cd41.png">

.

**Comment by ZHDI-1** [comment]
that should be not easy to implement, if you have different users, you can try to set different tab colors to distinguish.

**Comment by lwouis** [comment]
Yes, please use tab colors to differenciate windows from a distance 👍

**Comment by CryptoSun1989** [comment]
But I have over 100 chrome accounts and it's hard to remember what color each one is😅

**Comment by ZHDI-1** [comment]
> each

That may not easy to do, you can easily find chrome user avatar icon, but they are named numbers, I'm not sure can we find out matched window😄
We even need to figure out source code of chrome, that's not worth

**Comment by ZHDI-1** [comment]
> But I have over 100 chrome accounts and it's hard to remember what color each one is😅

after some test, you can find your image in `~/Library/application support/google/chrome/default/account/avatar images`
They all named by account id, you can find it easily in same root default dir named preference file, format by json, in first several lines, if you have time you can try to implement it

**Comment by lwouis** [comment]
You can look at the discussion on a previous similar ticket for context: https://github.com/lwouis/alt-tab-macos/issues/527

If we were to implement this, we would need to use the Accessibility API from macOS to parse the UI of the web browser. Each main web browser is unique in that regard. Some are parsable, some less so, or not at all. We would need to maintain that code, for each browser, over time as they update their UI with every version.

The benefits are too niche to warrant this amount of effort. Who would write it and maintain it? Please keep in mind that I have been looking for someone to take over this project for a very long time, and no-one has raised their hand: #1179

**Comment by CryptoSun1989** [comment]
Okay, thank you for your replies.
