### ISSUE TITLE
hide menubar icon?

### ISSUE THREAD

**Issue by wwsalmon** [lwouis/alt-tab-macos#2486]
thoughts on adding option to hide the menubar icon? after setting it up i don't open the app itself very often and it'd be nice to just have it hidden

**Comment by lwouis** [comment]
It's already possible using the icon dropdown on the first tab of the preferences

**Comment by kennethjwong** [comment]
I must be blind I only saw options to change the look of the icon but not actually disabled/hide the menu bar icon in version 6.59.0

**Comment by lwouis** [comment]
@kennethjwong there are 4 rows in the dropdown on your screenshot. The last/bottom row is empty => no icon

**Comment by kennethjwong** [comment]
thanks @lwouis, have a good weekend.

**Comment by giuliac-edgetier** [comment]
Can I just say that is not very intuitive?! thank you though 👍🏼

**Comment by lwouis** [comment]
Hi @giuliac-edgetier,

The UX has been improved. Instead of picking an empty option, you can now toggle off the menubar icon using the toggle button on the right of the dropdown list.

Thank you

**Comment by giuliac-edgetier** [comment]
@lwouis thank you so much 🙏🏼 not sure how I missed that.
