### ISSUE TITLE
Tabs as window option for each Shortcut

### ISSUE THREAD

**Issue by exidler** [lwouis/alt-tab-macos#2489]
There already option in Appearance: "Show standart tabs as windows"
There will be useful to move it to each Shortcut setting, so for example:

- Cmd+Tab switches between windows
- Option+Tab switches between active app Windows and Tabs

Is it possible?

**Comment by lwouis** [comment]
I'm afraid it's a bit too niche to move this global setting to a per-shortcut setting. If more users ask for it, let's reconsider 👍
