### ISSUE TITLE
CMD + Shift + Tab = backwards tab, instead of CMD + Shift

### ISSUE THREAD

**Issue by paraversal** [lwouis/alt-tab-macos#2493]
**Is your feature suggestion related to a problem? Please describe.**
Currently, you can only select a single hotkey to tab backwards (by default pressing shift)

**Describe the solution you'd like**
I would like the option to tab backwards by using shift as a modifier key instead of the hotkey itself, so that holding CMD + shift and then pressing tab would tab backwards. In essence, exactly the same way as it behaves on Windows.

**Comment by lwouis** [comment]
You can simply set previous to `shift+tab` instead of `tab` to achieve this 👍
