### ISSUE TITLE
Block specific apps from ever showing up in AltTab

### ISSUE THREAD

**Issue by towerofnix** [lwouis/alt-tab-macos#2506]
**Is your feature suggestion related to a problem? Please describe.**

Hey there! I've been using AltTab for a few weeks and loving it. Thanks for your work on it! My use case is having a bunch of spaces at once with specific apps assigned to them (via the Dock context menu, so they always stay in that space) and using AltTab to quickly switch between just the windows visible in that space.

AltTab gets the job done almost perfectly, but there are certain apps which layer some visual on the screen *in the background* (or are otherwise generally non-interactive). Those apps usually provide controls via the menu bar or Dock rather than with an interactive window. Some example apps like this: [Desktop Clock Live](https://apps.apple.com/ca/app/desktop-clock-live/id894760156) and [lo-rain](https://lo.cafe/lo-rain).

I *never* want to interact with these apps via the app switcher (whether built-in or AltTab) because that's not how they've been designed. But I do want them to be visible on all my spaces - again, they're all about overlaying a non-interactive effect on the screen somewhere, no matter what space you're on.

But they still end up taking space in AltTab's switcher and, if I happen to land on one by accident, bring up a settings window (for the app) which I hardly even remember still existed (let alone want to create... because now I have to mouse over to the close button... it's an awkward interruption!).

**Describe the solution you'd like**

I'd love an option in AltTab's settings to nice and easily block certain apps from ever showing up in the switcher. I just don't need to get to these with the app switcher, and I'd rather have a nice and clean lay of only the apps on the current space I want immediate access to!

**Describe alternatives you've considered**

These apps showing up isn't so infuriating because they at least don't get mixed in with my other apps - they naturally clump at the end of the list since I generally, you know, don't access them. But they're still there taking up space, and make cycling round from the end of the list to the start less convenient (you have to skip across an extra item you'd never select anyway).

**Comment by lwouis** [comment]
There is already a system for this in Preferences > Blacklists 👍

**Comment by towerofnix** [comment]
Hey, awesome! I totally missed it! Thanks 🎉
