### ISSUE TITLE
AltTab is always blinking when used

### ISSUE THREAD

**Issue by azad-resolver** [lwouis/alt-tab-macos#2507]
**Describe the bug**
Whenever I try to use AltTab, it's endlessly blinking, which makes the switcher almost unusable/inaccessible.

**Screenshots / video**
[AltTab blinking.webm](https://user-images.githubusercontent.com/131415063/234392384-ff507390-be16-46ab-a1c1-2b78bf0caabb.webm)

**Steps to reproduce the bug**

1. Hit Alt+Tab

**Your environment**

* AltTab version: 6.56.0
* macOS version: 13.3.1 (the bug also occured with the previous version)
* Other relevant info: using external keyboard & 2nd monitor

**Comment by lwouis** [comment]
This looks like what happens when there are multiple instances of AltTab running (see #1840). Could you please check in Activity Monitor how many AltTab instances are running when this happens?

Thank you

**Comment by azad-resolver** [comment]
Oh Indeed! I wasn't aware there were two instances running, but closing one of them fixes the issue.
Now I just gotta figure out why two instances are started on every boot.
Thanks for your help!
