### ISSUE TITLE
When I used Android virtual machines, the toolbar of the virtual machine and the virtual machine were split into two Windows

### ISSUE THREAD

**Issue by choby** [lwouis/alt-tab-macos#2508]
**Describe the bug**

When I used Android virtual machines, the toolbar of the virtual machine and the virtual machine were split into two Windows

**Screenshots / video**
this is AVD window :
![image](https://user-images.githubusercontent.com/13461239/234439732-61160c62-5020-4797-85c0-59b35866bada.png)

this is in ALT-TAB:
![image](https://user-images.githubusercontent.com/13461239/234439874-55edf51e-f072-4fe2-a723-dc4a562fce75.png)

**Your environment**

* AltTab version: 6.56.0
* macOS version: 13

**Comment by lwouis** [comment]
Yes, these are 2 windows. AltTab simply report that
