### ISSUE TITLE
Show only most recent window of application

### ISSUE THREAD

**Issue by vip9** [lwouis/alt-tab-macos#2512]
A configuration option to show only recent window of an application - behaviour similar like default macos switching mechanism.
When you're used to cmd+`, it is easier to find specific app, then just switch (if needed) to other window.

something like "Show applications instead of all windows"

**Comment by lwouis** [comment]
This is already possible. It's also possible by default to press alt+` to cycle through windows of the active app. You can review and customize this deeply in Preferences > Controls

**Comment by vip9** [comment]
Which exact option should I check, to show only one position per application? 
Tried everything, but two or more Brave windows (not tabs) always show in the preview.

**Comment by lwouis** [comment]
Oh ok, i think i understand what you're looking for now. This is discussed in #337
