### ISSUE TITLE
Add feature to add Application selection on "Show windows from:"

### ISSUE THREAD

**Issue by ljack** [lwouis/alt-tab-macos#2515]
- I wish i could select a list of app from which i want to see windows because many times i want to select either Chrome or IntelliJ window and don't want to see the other apps on list. Yes, I've too many Chrome and Idea windows open at the same time, i know, but i like it.
- 
-
-  Basically add 3rd option to Show windows from: "All apps", "Active app, "Apps with name: "
In the dialog you could enter selector string which would then choose the apps which to show.

Eg. 
Apps with name:  chrome --> only show windows from chrome
Apps with name:  chrome|IDEA --> only show windows from chrome and intellij IDEA
You get the point.

Then i could bind some special binding to this use configuration.

**Comment by lwouis** [comment]
It's an interesting idea. However i'm afraid it's a bit too niche. If more users ask for this, i'll re-open the ticket 👍
