### ISSUE TITLE
Vertical list

### ISSUE THREAD

**Issue by mindyourlifeguide** [lwouis/alt-tab-macos#2518]
I would like to be able to see a vertical list - an icon and a title.
It is much more convenient and faster than horizontal.
Plus, you have a preview window of the selected one, which, together with the vertical list, will be extremely convenient.
Linux kde has just that and the user experience is excellent.
There is a similar functionality in Contexts, but there is no preview window for the selected

**Comment by lwouis** [comment]
This design is explored in #351. You can also get a vertical ui today by playing with the preferences but it won't show thumbnail on hover but always show them or never show them

**Comment by mindyourlifeguide** [comment]
You can try to be inspired by the main menu example, as in [kde](https://www.debugpoint.com/configure-task-switcher-kde/).

[This option](https://www.debugpoint.com/wp-content/uploads/2022/02/Compact-Task-Switcher.jpg) vertical menu with the preview window selected is the most convenient, as for me

**Comment by huyz** [comment]
playing around with the UI preferences is tricky…

**Comment by sapoepsilon** [comment]
> playing around with the UI preferences is tricky…

I am working on a new UI in preferences. It will take some time until it is ready. But will be way easier to have different appearances. Here is a quick sneak peak: 

<img width="573" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/47342870/7888b1c8-e9dc-4ccd-bdb3-5e3e426ab9bb">
