### ISSUE TITLE
Editing blacklist entry messes up rows

### ISSUE THREAD

**Issue by lawand** [lwouis/alt-tab-macos#2528]
**Describe the bug**

Removing an item from the blacklist then editing items after it causes issues and duplicates

**Steps to reproduce the bug**

1. Open preferences
2. Go to blacklist
3. Remove the first item
4. Edit the text of the second item (which is now the first)
5. Quit alttab and start it again
6. Go to blacklist again, the items in the list are duplicated and have errors

**Your environment**

* AltTab version: 6.53.0
* macOS version: 13.3.1

**Comment by lwouis** [comment]
Hi @lawand,

I was able to reproduce the issue. I also located the issue in the source code. It's an issue with editing a row in the list. The rows are numbered, and when a row is deleted, the numbers are not reset, so when editing a row after deleting one, the editing affects the wrong row.

I'll work on a fix 👍
