### ISSUE TITLE
Preview not showing closed windows

### ISSUE THREAD

**Issue by litsnarf** [lwouis/alt-tab-macos#2529]
**Describe the bug**

Before updating to `MacOS Ventura 13.3.X`, if i closed a windows (sat Telegram or Outlook) with `Cmd+W`, the application would still show up in `AltTab` (this is similar to the default MacOS behavior). At the moment, if i close an app with `Cmd+W`, even tho  the app appears in the bar with the "white dot" at the bottom, it doesn't show up anymore when switching application in AltTab. 

**Screenshots / video**

This is the current config I have in AltTab

![image](https://github.com/lwouis/alt-tab-macos/assets/8859570/559261cf-f804-48db-b614-80e714f6287b)

**Steps to reproduce the bug**

1. Open an application like telegram, outlook, mail, etc.
2. Close it with Cmd+w (or clicking the red X on the top)
3. Press AltTab combination to switch windows
4. The application doesn't show

**Your environment**

* AltTab version: Version 6.57.0
* macOS version: Ventura 13.3

**Comment by lwouis** [comment]
Hi,

There is a preference to hide/show apps with no open window. It's located here:

![image](https://github.com/lwouis/alt-tab-macos/assets/106195/b49a0d59-95df-4daa-a2aa-f328eee47bcd)

Furthermore, you can also hide things in the Blacklists tab of the preferences, as seen at the top of the screenshot.

If your preferences are set up correctly, you should see apps with no window. It's working correctly on my side, for instance.

Thank you

**Comment by litsnarf** [comment]
Hi lwouis, thanks a lot! I totally missed that option. It is indeed working as expected.

Thank you again.
