### ISSUE TITLE
Only show apps *without windows* which are assigned to a specific Desktop space on that space

### ISSUE THREAD

**Issue by towerofnix** [lwouis/alt-tab-macos#2540]
**Is your feature suggestion related to a problem? Please describe.**

When an app doesn't have any windows open, it shows up in AltTab on every space, even if AltTab is configured to show windows from visible spaces only. This is important so you can interact with the app in the first place (as though clicking it from the Dock, to open up a new window) — but it also adds some clutter to the menu.

**Describe the solution you'd like**

My layout in principle could avoid this clutter. I have the majority of my apps each assigned to a specific Desktop space, so that no matter where I open an app, I'm automatically brought over to the space which it belongs to.

My requested solution is to have AltTab automatically read which spaces any given app is assigned to, and only show ones without any apps open in the AltTab switcher when you are on the space it's assigned to.

For example, I have Calendar assigned to Desktop 3. If I show AltTab while Calendar is running without any windows open, it should only appear in the switcher if I am currently viewing Desktop 3. If Calendar *does* have a window open, and I have forcibly dragged that window over to Desktop 2, then it should still show up in the switcher for Desktop 2 (but not any of the Desktops without any Calendar windows).

**Describe alternatives you've considered**

There are two main alternatives. The first is to simply always have a window open from every app. Only the apps whose windows are on the current Space will be displayed. This is generally workable if you like to keep apps hidden (Command+H for example), or if you use Stage Manager, but it is a bit awkward, requiring more fine management (as you go, not just during setup).

The second is to outright quit apps which you aren't currently using. This is the purest way to get rid of the running state of an app, but drawbacks include a bit of delay when reopening, and having to use Spotlight or the Dock to do so, making AltTab totally useless (for that app) until you reopen the app another way.

These workarounds aren't huge bothers for me so I still use AltTab constantly without much annoyance, but they do take away from the usability of AltTab in their own ways. I can't think of another workaround which avoids clutter while still making it easy to get to the apps I want to with AltTab, so here's my suggestion! 🐿️

**Comment by lwouis** [comment]
I think this should do it for you: https://github.com/lwouis/alt-tab-macos/issues/2529#issuecomment-1547317029

**Comment by towerofnix** [comment]
I could be misunderstanding but I don't believe that option covers what I discussed here — I don't want to enable that option because I still want to access apps with no open windows via AltTab, just only on the space they're assigned to. If I enable it then I have no option to access an app with closed windows via AltTab, I have to use the Dock or Spotlight. I want to be able to open those apps with AltTab, without cluttering the switcher on spaces that they aren't assigned to.

**Comment by lwouis** [comment]
@towerofnix oh I understand now. In order to enable this behavior, we would need to expose yet another checkbox/toggle in the preferences, as some people may prefer the current behavior of accessing apps with no open window from anywhere. I'm reluctant to add a new preference for a niche use-case (see #351).

However, I think #337 may help you since it's another approach to handle clutter that's pretty generic and flexible.

**Comment by towerofnix** [comment]
You got it, totally understood. Thanks for the links for further discussion and help!
