### ISSUE TITLE
When I press Option + Tab and then release both keys, AltTab does not remain on the screen.

### ISSUE THREAD

**Issue by khius** [lwouis/alt-tab-macos#2549]
I'm not certain if this is the intended behavior, but when I press Alt + Tab in Windows and then release all keys, all windows remain on the screen, eliminating the need to keep pressing the keys. However, on my Mac Studio, when I press Option + Tab and then release both keys, AltTab disappears along with all the thumbnails, leaving me unable to perform any actions. As a result, I must continually press the Option key to keep AltTab visible on the screen. Is this the expected behavior?

**Comment by lwouis** [comment]
Hi,

i'm not sure how you believe that the UI remains if you raise the alt key on Windows. On Windows 7 and 10 it definitely goes away and focuses the selected window, like AltTab is doing on macOS.

If you want to have AltTab remain on screen it's actually possible through a preference. It's in Preferences > Controls.

thank you

**Comment by khius** [comment]
Could you please tell me how I can change that in the settings? I was tweaking around and couldn't figure it out.

**Comment by lwouis** [comment]
Please select this option:

<img width="589" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/106195/e8399ba5-c05c-4b65-b7e2-5e269fea699d">

**Comment by khius** [comment]
Thank you so much!
