### ISSUE TITLE
Suggestion: Hide Window Title Completely (or Place Window Title Below App Icon)

### ISSUE THREAD

**Issue by socketflow** [lwouis/alt-tab-macos#2550]
I'm always frustrated when I tried to retain the default look & feel of macOS' default Cmb-Tab. The best I can do now is:

```
1. Hide Window Thumbnail : true
2. Window App Icon Size: 128 px
3. Window Title Font Size: 0 px
4. Hide Space Number Lables: true
```

However, this resulted in a incorrect alignment where the app icon is not is the center of its grid.

**result:**
<img width="884" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/46785285/5fbb0d39-e669-4eee-95b3-989c0712b1d5">
<img width="884" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/46785285/6570beb7-44b1-4637-b1c5-f02237b8e265">
<img width="884" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/46785285/1f30e98b-9f95-4960-bf58-e7ad26c0591f">

**but it's actually off-center:**
<img width="884" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/46785285/20f792ac-9732-4146-9d53-7a03032ce0b1">
<img width="884" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/46785285/6ec22fc9-665a-4aa9-a659-7e3c1785fc68">
<img width="884" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/46785285/d0ad4daf-0356-4201-9e9c-a9505a38fa0b">

**Describe the solution you'd like**
I assumed (maybe I'm wrong) that this is because the alignment still left some space for window title. I really would prefer if there's a toggle to hide the window title altogether, because the app icon is already clear enough for me.

Or at least when the font size is set to zero, the alignment would be properly centered.

**Describe alternatives you've considered**
An alternative would be a setting to place the window title below (like macOS) or even above the app icon.

**Comment by lwouis** [comment]
Your desired layout will be made way easier through #351
