### ISSUE TITLE
I am wonder how to fix this

### ISSUE THREAD

**Issue by doxxx93** [lwouis/alt-tab-macos#2553]
<img width="226" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/51396905/94a82421-edf8-4061-a771-5649639dd35d">

![image](https://github.com/lwouis/alt-tab-macos/assets/51396905/f0482c58-4567-42b6-bffb-eca22d8732f5)

I am using m1 mac air, with belkin display link docking station.

![image](https://github.com/lwouis/alt-tab-macos/assets/51396905/17ca16b2-af2b-4527-84b4-cd42a3d92835)

first image is when I alt-tab in m1 air screen, second image is when I alt-tab in other screens.

![image](https://github.com/lwouis/alt-tab-macos/assets/51396905/6256b52b-6f7e-40e3-9a78-a68a2206aea2)

I am using 2 lg FHD monitors, 1920 * 1080 and 1080 *1920(pivot)

I just reinstalled docker, alt-tab. not worked.

**Comment by lwouis** [comment]
This issue has happened to a few people over the years. I'm afraid there is nothing we can do. We get the image from the OS, and straight away display it.

It may disapear after you update macOS later on. In the meanwhile, I'm afraid we can't help since it's an OS bug.
