### ISSUE TITLE
System Keyboard Layout Selector now displayed as a separate window of each application

### ISSUE THREAD

**Issue by thebitstick** [lwouis/alt-tab-macos#2573]
**Describe the bug**

This is partially a bug of the first macOS Sonoma Beta, where the layout selector keeps showing up when ⌘+Tabbing, but AltTab will probably have to add this to its blacklist defaults.

**Screenshots / video**

![CleanShot 2023-06-06 at 23 00 15@2x](https://github.com/lwouis/alt-tab-macos/assets/13919134/2a10f861-2498-427e-af72-b4d87ff657ca)

**Steps to reproduce the bug**

1. Click onto a text field in an application.
2. Layout selector appears for no good reason (possibly if no text fields are activated for a minute?).
3. ⌘+Tab
4. Current application has a new window in AltTab with the layout selector.

**Your environment**

* AltTab version: 6.59.0
* macOS version: 14.0 Sonoma Beta 23A5257q

**Comment by lwouis** [comment]
I don't know anything about macOS Sonoma. Based on the screenshot you shared, it looks like macOS added new UI elements that AltTab shows. AltTab only shows standard windows, so I assume Apple will fix whatever this new UI is to use the proper implementation (e.g. a HUD / popover).

I'll close this ticket until the new release is live. Then we can look at the situation 👍

**Comment by thebitstick** [comment]
![CleanShot 2023-06-07 at 02 19 28@2x](https://github.com/lwouis/alt-tab-macos/assets/13919134/d948947e-3faa-4b3a-a781-a4a7148260b8)
Strangely, when trying to screenshot the new UI, the old UI showed up for a bit.

![image](https://github.com/lwouis/alt-tab-macos/assets/13919134/175161e0-74d5-406f-91ed-0ff5f0367702)
