### ISSUE TITLE
Browser tab title doesn't update with latest Microsoft Edge version (and workspaces)

### ISSUE THREAD

**Issue by beliven-valentino-cossar** [lwouis/alt-tab-macos#2575]
**Describe the bug**

Microsft Edge title doesn't update with the latest seen browser tab on Alt Tab while using new Microsoft Edge feature called "Workspace".

**Screenshots / video**

![SCR-20230607-dhd](https://github.com/lwouis/alt-tab-macos/assets/104220896/aac2abed-092f-4772-b5f2-818f38ed0e01)
![SCR-20230607-dhs](https://github.com/lwouis/alt-tab-macos/assets/104220896/c7c2cb6e-126e-440c-a537-67c610e36a4a)

**Steps to reproduce the bug**

1. Install the latest version of Microsoft Edge and enable workspace feature
2. Create a new workspace
3. Open some browser tabs
5. Use AltTab to see that the Microsoft Edge tab title doesn't update inside AltTab

**Your environment**

* AltTab version: 6.59.0
* macOS version: 13.3.1 (a)
* Microsoft Edge version: 114.0.1823.37 (Official build) (arm64)
* Single external monitor with Mac put on docking station

**Comment by lwouis** [comment]
AltTab displays window titles from macOS API calls. In other words, AltTab gets the titles from macOS. So if the titles are not correct, it's an issue with Microsoft Edge, not AltTab. It is merely reporting the data, not modifying it in any way. Every other app has correct titles, pointing again to Edge.

I advise contacting their customer support and mentionning that titles are broken with the new workspace feature. They probably missed this during their development cycle and QA 👍

**Comment by beliven-valentino-cossar** [comment]
Hi @lwouis, thank you for the clarification! I've just sent feedback to the Microsoft Edge team.
