### ISSUE TITLE
Outlook not appearing in alt tab

### ISSUE THREAD

**Issue by Joeyn1993** [lwouis/alt-tab-macos#2576]
**Describe the bug**

Outlook for mac does not appear in the alt-tab menu. It is open and accessible via other gestures etc.

**Screenshots / video**

Can't figure out how to screenshot with the alt-tab menu open.

**Steps to reproduce the bug**

1. Open outlook.
2. It does not appear in the list

**Your environment**

* AltTab version: 6.59
* macOS version: 12.6
* Outlook version: 16.73.2
* Other relevant info: Default laptop setup

**Comment by lwouis** [comment]
I just tested, and it shows every Outlook windows, on my computer. I can't reproduce what you describe.

Could you please share a video of the issue in action, so the situation is clearer?

Note: are you fullscreening the windows perhaps? If so, you could be facing #1324

**Comment by Joeyn1993** [comment]
Rebooted the computer yesterday, wasn't there, magically working this morning - Going to close this for now :)
