### ISSUE TITLE
Re-add Generic Open New Window Icon (#2561)

### ISSUE THREAD

**Issue by falchion10** [lwouis/alt-tab-macos#2577]
Could you please re-add this and give users the choice to pick between the generic icon or the app icon? I liked the generic icon better than having the app icon, since the normal icon is already in the top left corner. 

Pretty low priority as users could just use v6.58.0.

<img width="218" alt="Screenshot 2023-06-07 at 9 20 38 PM" src="https://github.com/lwouis/alt-tab-macos/assets/122236745/b1a78355-689a-416d-8df4-3234292a740c">

**Comment by lwouis** [comment]
Hi,

Unfortunately, there are already too many preferences. See #351.

For the time being, the new approach will remain.

Thank you for your understanding 🙇‍♂️
