### ISSUE TITLE
How to report identified security vulnerabilities with the codebase

### ISSUE THREAD

**Issue by abdulrafaykhan** [lwouis/alt-tab-macos#2578]
Hello guys, 

I was looking at this tool and this is one of the best tools I have came across :)

I wanted to have a discussion related to the security vulnerabilities

Is there any process currently in place to report and maybe submit a PR for a vulnerability fix ? 

Let me know what it is and I can share the heads up :)

**Comment by lwouis** [comment]
Hi @abdulrafaykhan,

There is no process for this. What I can suggest is to [email me](https://github.com/lwouis) so I can understand the issue, and work to release a fix, without showing the vulnerability out in the open first. This way we can minimize potential impact on users.

Thank you 🙇‍♂️
