### ISSUE TITLE
Failed to build project with Xcode 14.3

### ISSUE THREAD

**Issue by XOR-op** [lwouis/alt-tab-macos#2581]
**Describe the bug**

When trying to build the project, I got the following errors:
> ld: file not found: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_macosx.a
clang: error: linker command failed with exit code 1 (use -v to see invocation)

This could be a problem that `LetsMove` and some other pods not supported by Xcode 14.3, similar issue can be found on https://github.com/libsdl-org/SDL/issues/7563. However, although manually bumping `MACOSX_DEPLOYMENT_TARGET` of these pods solves this error, it introduces other bunches of compile errors. I have no idea how to solve those with my little Swift experience.

**How to reproduce it**
1. Directly clone the project on master branch
2. Use Xcode 14.3 & macOS 13.4 to build the project (either by clicking the button or by cli)

**Your environment**

* AltTab version: N/A (master branch)
* macOS version: 13.4
* Xcode version: 14.3

**Comment by lwouis** [comment]
I'm afraid I can't help you here. I myself actually had to downgrade to XCode 13.4.1.

The way Apple does SDK is terrible. It's embedded into XCode, with no way to switch. This means that when you upgrade XCode, you also start compiling against a new macOS SDK. When I upgraded to XCode 14, I got an error that a public API was not available, even though it is available. Apple changed the SDK and removed a public API, even though the API is actually there on the latest macOS. I don't know why they did that, but there is no way to deal with this change. AltTab requires the API to do its job.

All I can advise is to downgrade to a XCode 13.X. It's actually not easy to do. I used [this method](https://stackoverflow.com/a/74192401/2249756). I'm sorry you have to go through this. The macOS ecosystem is treated terribly by Apple, and there is no recourse or dialog possible with Apple.

**Comment by XOR-op** [comment]
Thanks for you explanation and I'll give the downgrade a try.

**Comment by lwouis** [comment]
Hi @decodism!

I don't think i received any email. I also checked my spam. Did you send it to the email on my github profile? Could you try sending it again perhaps?

Thank you 🙇‍♂️
