### ISSUE TITLE
In the Coherence mode of the parallel desktop, the window of the Windows app does not appear in the alttab

### ISSUE THREAD

**Issue by juzijun233** [lwouis/alt-tab-macos#2585]
**Describe the bug**

In the Coherence mode of the parallel desktop, the window of the Windows app does not appear in the alttab
**Screenshots / video**

Add screenshots to help explain your problem. You can also record your screen to show the bug in action. That is *really* helpful!

**Steps to reproduce the bug**

**Your environment**

* AltTab version: 6.59.0
* macOS version: 13.4
* Other relevant info: e.g. using external keyboard, multiple monitors, etc

**Comment by lwouis** [comment]
It's either #1324 or a bug of the Parallels app
