### ISSUE TITLE
Option to not show apps with no open windows

### ISSUE THREAD

**Issue by jrhbcn** [lwouis/alt-tab-macos#2588]
Hi,

New user coming from hyperswitch. I really like alt-tab so far, great work!

I'm not sure if already exists, but I would like to disable showing apps with no windows in the switcher. Most of the time I just want to switch between open windows. However, I don't seem to find the option in the preferences.

Is it possible? Does it make sense to add it, if not?

Best regards,

**Comment by lwouis** [comment]
It's at the bottom of Preferences > Appearance 👍

**Comment by jrhbcn** [comment]
Perfect! I knew it should be somewhere :)  I was expecting it related to shortcut (so it could be changed by shortcut).

Many thanks!
