### ISSUE TITLE
Tab-switcher lacks contrast when background is dark

### ISSUE THREAD

**Issue by tophee** [lwouis/alt-tab-macos#2593]
Is this by design, or am I doing something wrong, or is it a bug?

Everything works fine when the tab-switcher is used over a bright background:

![image](https://github.com/lwouis/alt-tab-macos/assets/3662750/ec91deff-406c-4d01-a045-2185b722a4be)

But when the background is dark, it is almost impossible to see which window is currently selected:

![image](https://github.com/lwouis/alt-tab-macos/assets/3662750/6f2426ce-fc6a-43bb-ae84-02664d42b765)

**Comment by lwouis** [comment]
I can only suggest using the Windows theme in Preferences > Appearance
