### ISSUE TITLE
Blacklists: Hide in AltTab when no visible window

### ISSUE THREAD

**Issue by laurensk** [lwouis/alt-tab-macos#2594]
**Problem**

First of all, I love AltTab. But I have one issue that drives me crazy in my workflow: If you close Discord with cmd+w or pressing the x-button, it hides itself rather than closing. Because I like having the windows **I** hid in AltTab, I don't want to only show active windows. But there should be a way to say that Discord behaves like a closed window when it's hidden.

**Solution**

A possible solution would be to add a third option in the Backlist features under the action "Hide in AltTab" which is called something like "When no visible windows" (see picture). So I could define a rule for Discord to not make it show up when it does not have any visible windows.

<img width="616" alt="Possible design of third option in select" src="https://github.com/lwouis/alt-tab-macos/assets/39766854/de7d6da3-e33f-4dac-8f63-e30091a666af">

**Alternative**

As I already mentioned, you could just disable to show hidden windows at all, but I think there are many that wants to see hidden windows, but have the option of ignoring windows that hide themselves on a per app basis!

Edit: Another alternative is to exclude Discord from AltTab entirely, but as you can imagine, for someone who uses Discord a lot, this is also not a great experience.

Thanks a lot!

**Comment by lwouis** [comment]
Discord has been brought up a few times. It seems clear that their implementation is not following expectations of macOS users. The issue would be best addressed by Discord.

i suggest you contact their customer support 👍

**Comment by laurensk** [comment]
Sure its a problem of Discord, but adding the option would allow users to not only fix the Discord problem (which they have refused to solve for many years) but also give more flexibility using and configuring AltTab.

**Comment by lwouis** [comment]
Unfortunately, implementing what you mention would be at odds with #1179 and #351. Since Discord is the only app that has been reported behaving like this, it makes sense that they would fix this.
