### ISSUE TITLE
Alert "AltTab" is using a deprecated API that will be removed in the future. Please contact the developer for an updated version.

### ISSUE THREAD

**Issue by cupboardunderscore** [lwouis/alt-tab-macos#2599]
just got this message after updating to the newest macos dev beta and thought i should let you guys know
![image](https://github.com/lwouis/alt-tab-macos/assets/54553422/d99fecc5-5f8f-4e27-86f0-ebbc76c89472)

**Comment by DHepworth** [comment]
I got the same error on my MacBook Air M1 running the latest Sonoma beta.

**Comment by borisborat** [comment]
Same here

**Comment by Bentheminernz** [comment]
Same here!

**Comment by jessedelira** [comment]
Same here

**Comment by lwouis** [comment]
Let's review issues after the beta when it's live 👍 This may go away

**Comment by Xela9624** [comment]
same here accept the alert says "(null)" instead of saying "AltTab"
