### ISSUE TITLE
MacOs Sonoma Deprecating some library

### ISSUE THREAD

**Issue by 100472175** [lwouis/alt-tab-macos#2604]
I have been using the MacOs Sonoma Beta for Developers, and when updating to Beta 2, there was a message indicating that AltTab using a library that is going to be deprecated in the future. (I think it was a library, but I'm not sure)

Also, now, when altTab is started, this icon appears in the control Center: 
![image](https://github.com/lwouis/alt-tab-macos/assets/95641726/d9ba011b-d05d-4fff-af33-05852afb79fa)

**Comment by lwouis** [comment]
There have been many recent ticket about this. Let's please wait until the end of the beta to open tickets 👍
