### ISSUE TITLE
Mouse hover enhancement: Place pointer over active selection on invocation

### ISSUE THREAD

**Issue by binarycamper** [lwouis/alt-tab-macos#2611]
**Is your feature suggestion related to a problem? Please describe.**
When invoking Alt-Tab while using the mouse I always first have to move the pointer to the currently selected window. This has become especially apparent with the newly introduced window orders in v6.60.0: I have read the discussion in the pull request [#2583](https://github.com/lwouis/alt-tab-macos/pull/2583) and do find the sorting and selecting logic to be sound for "Alphabetical" and "Space". I had not known I would find use in these ordering styles, but now I am already using them for my non-primary shortcuts, as a robust multi-space Mission Control substitution. In my opinion these deterministic sorting styles only make sense when combined with "Then release: Do nothing" and using the mouse, otherwise a lot of tabbing will be necessary. Having the currently active window selected does make sense (since in a static order we cannot predict the next window) and placing the pointer immediately right above it makes even more sense. I think this will also be a nice enhancement for "Recently Focused" order since it will be very easy to go back multiple layers just by moving the pointer to the right.

**Describe the solution you'd like**
Add a checkbox in the preferences besides / under "Mouse hover", which is only visible when hovering is already enabled. I am unable to come up with a concise unambiguous description right now: "Move mouse to selection" may serve as a starting point.
When using the keyboard instead, the white hover border should disappear until the mouse is moved again and so on. Otherwise the white border would be too distracting when using solely the keyboard at times, since a white border at the starting selection under the relocated pointer will be initially guaranteed.
Side note: Maybe we want to use the term "mouse" for all mouse related features thus renaming "Mouse follows focus" in the process to be consistent.

**Describe alternatives you've considered**
Maybe implicitly enabling this when "Mouse hover" is checked would be reasonable (no checkbox needed). With hovering enabled I cannot find any scenario where this would be undesirable, other than the initially jumping pointer being possibly perceived as distracting?

**Comment by lwouis** [comment]
I think very few people who would like that workflow. Many people for instance have asked the oppositive: they quickly alt+tab and they don't want the cursor to accidentally interact with the UI and mess the target window when they release tab.

This is why AltTab now defaults to having mouse hover show a separate white outline i stead of controlling the selection.

I'm afraid this workflow is too niche to be implemented 🙇‍♂️
