### ISSUE TITLE
Alt+Tab doesn't work when AltTab is open

### ISSUE THREAD

**Issue by ok-coder1** [lwouis/alt-tab-macos#2613]
**Description of the bug**

When AltTab is mapped to the keyboard shortcuts Alt+Tab, Tab doesn't get recognized. Pressing Alt works but then pressing Tab doesn't work. If AltTab is not open (quit), then Alt+Tab works perfectly fine.

**Screenshots / videos**
**_(Sending link to Youtube because the video is too large.)_**
https://youtu.be/qmnhPULUFN8

**Steps to reproduce the bug**

1. Open AltTab
2. Try pressing Alt+Tab

**My environment**

* AltTab version: 6.60
* macOS version: 10.12.6
* Other relevant info: Using Logitech USB Keyboard

**Comment by lwouis** [comment]
I couldn't quite understand everything on the video. Keyboard management is very robust after 3 years of improving it in details thanks to user feedback. Thus it is most likely that you have something about your setup that creates the issue you mention. Could be your keyboard hardware, key remapping software, languages, etc.

**Comment by ok-coder1** [comment]
When AltTab is open, the system doesn't recognize the Tab after pressing Alt. When AltTab is not open, it recognizes the Tab after pressing Alt.

**Comment by lwouis** [comment]
Like I said, it's most likely something with your setup. It works correctly on my machine, and most likely every other user:

https://github.com/lwouis/alt-tab-macos/assets/106195/7f76edc3-454e-43cb-b17b-50fce77ac867

**Comment by ok-coder1** [comment]
@lwouis Can you open this again?

**Comment by ok-coder1** [comment]
Pressing Alt and Tab at the same time doesn't work.

**Comment by lwouis** [comment]
Pressing alt+tab means you want AltTab to show. Of course AltTab shows, and it absorbs the key strokes so that other apps don't also react to it. You wouldn't want the app that right bellow AltTab to receive tab every time you cycle thumbnails forward in AltTab in the forefront.

**Comment by ok-coder1** [comment]
Yeah, but AltTab doesn't show up.

**Comment by ok-coder1** [comment]
Now, it suddenly works for some reason. I haven't been using this Mac for a few weeks.

**Comment by ok-coder1** [comment]
AltTab just worked, and now it's not working again.

**Comment by lwouis** [comment]
It's most likely something about your setup. External keyboard, key-remapping software, language change in hardware or software, third party app which intercept key presses, etc

**Comment by ok-coder1** [comment]
It only works when apps are fullscreen.

**Comment by ok-coder1** [comment]
AltTab only works when apps are in full screen. I don't have any key-remapping software installed. It also works sometimes as a fluke.
