### ISSUE TITLE
Highlight colour for current selected window

### ISSUE THREAD

**Issue by gaultpeter** [lwouis/alt-tab-macos#2621]
**Is your feature suggestion related to a problem? Please describe.**
It is hard to see which window is selected over a dark screen, a lot of my apps are dark mode and makes it hard to see which alt tab I have selected.

**Describe the solution you'd like**
Being able to change the colour, or have a light mode for the highlighted option.

**Describe alternatives you've considered**
Nothing yet, no current option to change the highlight colour.

**Comment by lwouis** [comment]
Please use the Windows theme in Preferences > Appearance 👍

**Comment by gaultpeter** [comment]
I guess that will do for now, but the highlight has changed from a background colour to a box highlight, not as pleasant to look at
