### ISSUE TITLE
Dock Window Preview

### ISSUE THREAD

**Issue by chaos-cn** [lwouis/alt-tab-macos#2630]
**Is your feature suggestion related to a problem? Please describe.**
Not related to a problem.

**Describe the solution you'd like**
Simply hover the mouse over the Dock to show a preview of all the Windows.

**Describe alternatives you've considered**
Since #967, alt-tab get full screen live preview.  Could you please add a feature that simply hover the mouse over the Dock to show a preview of all the Windows. It will be like [hyperdock](https://bahoom.com/hyperdock/) or [this answer](https://github.com/lwouis/alt-tab-macos/issues/967#issuecomment-1283782648). I understand this suggestion doesn't fit with the name "Alt-tab", but I really don't want too many apps taking screenshots all the time,alt-tab is enough. Thank you very much!

**Comment by lwouis** [comment]
We explored this in the past (#529) but ended up drawing the line there. AltTab will not stray too far from its initial goal and become a swiss-knife app.

Sorry about that, I hope you can understand 🙇‍♂️
