### ISSUE TITLE
Allow for do not show windows of apps in switcher but an icon or the previous recent window of opened apps

### ISSUE THREAD

**Issue by drkhn1234** [lwouis/alt-tab-macos#2636]
I would like to preserve extra functionality AltTab provides over default windows switcher of MacOS, such as shortcuts for window operations, i.e. minimizing, maximazing windows, etc.; displaying hidden and minimized windows in switcher, etc., but at the same time remove all other windows of apps in the switcher except their last focused window. Implementation wise, it would be beneficial to be able to choose which apps displayed in the switcher get to show multiple windows of itself and which to show only its last focused window.

Unfortunately, there doesn't exist an alternative within the boundaries of AltTab to achieve what I aim to as far as I could find in preferences. One possible approach is to use default MacOS switcher and combine it with AltTab provided switcher but only for windows of "Active App" in which case, for application switching, you lose both the shortcuts, window content preview, and ability to show hidden and minimized windows, windows from other workspaces compared to the default MacOS switcher.

**Comment by lwouis** [comment]
I believe the experience you desire is covered by #337
