### ISSUE TITLE
Add customization shortcuts for arrow key

### ISSUE THREAD

**Issue by zhaoxuan** [lwouis/alt-tab-macos#2637]
Possibly add customization shortcuts function instead of arrow key to select app.

**Comment by lwouis** [comment]
You can already customize shortcuts in Preferences > Controls 👍

**Comment by zhaoxuan** [comment]
> You can already customize shortcuts in Preferences > Controls 👍

Sorry, I didn't express it clearly, I mean using "hjkl" instead of arrow key to move app selection.

**Comment by lwouis** [comment]
There is an open PR to add vim-style keys in addition to arrow keys: #1272
