### ISSUE TITLE
One app is broken to several windows in AltTab menu (f.e. Fusion 360)

### ISSUE THREAD

**Issue by alexme-space** [lwouis/alt-tab-macos#2650]
**Describe the bug**
I have opened Fusion 360 app among others. No one app except fusion has no such behaviour, but I think this app can be considered as well-build. Fusion has inner window menus, that in AltTab are shown as separate apps. 

**Screenshots / video**
![photo_2023-07-08 01 23 00](https://github.com/lwouis/alt-tab-macos/assets/5106236/64a68980-8c2d-4b7c-a808-c37266be29d2)

**Steps to reproduce the bug**
The only way is to 
1) install Fusion 360 (It has trial version)
2) check behaviour in AltTab app switching menu

**Your environment**
* AltTab version: Version 6.60.0
* macOS version: macOS Monterey, version 12.6.7 (21G651)
* Macbook Air (M1, 2020) M1 chip, 16gb memory, no other devices connected

**Comment by lwouis** [comment]
The issue is with this Fussion 360 app. AltTab just shows the windows for that app. Other apps written in non-macOS native ways have done this before. Steam for example.

I suggest you contact Fusion 360 support so they fix their implementation 👍

**Comment by alexme-space** [comment]
Thanks for reply! I'll try to contact Fusion support

сб, 8 июл. 2023 г., 01:44 lwouis ***@***.***>:

**Comment by alexme-space** [comment]
Sorry for late response, but it was expected that autodesk aren't going to change app) 

I've tried AltTab alternatives - Hyperswitch. It renders fusion windows the same way, as AltTab, but the only diff is - when I switch to _any_ fusion window, I get fusion app correctly opened, when AltTab in the same situation can hide some of those "rosetta windows". May be its possible to fix this at least? AltTab is better for me, and this is the only inconvenience to feel happy =)

**Comment by lwouis** [comment]
I'm afraid we can't change the way we focus windows. It's a very sophisticated implementation that handles lots of exotic scenarios. You're saying that AltTab doesn't focus the app when you select a window like on your screenshot above?

**Comment by maartenvandillen** [comment]
Same issue here. After using Fusion 360 for a while the amount of floating tool windows grows quite large to a point where AltTab is only showing those since there is no room left for other apps. Would it be possible to setup filters based on window title?

**Comment by lwouis** [comment]
Hi @maartenvandillen,

[This is the way it should be fixed](https://github.com/lwouis/alt-tab-macos/issues/2650#issuecomment-1626335701). Not adding another layer of complex blacklisting in AltTab.

Thank you

**Comment by maartenvandillen** [comment]
Hi @lwouis although I totally agree with you I don't see that happen. I'll try something in my own fork.
