### ISSUE TITLE
Some apps didn't in switch window

### ISSUE THREAD

**Issue by zhaoxuan** [lwouis/alt-tab-macos#2660]
**Describe the bug**

QQ is an app, it is not in blacklist. When I started QQ, it was in the Dock (the last one app, penguin icon), but it didn't appear in alt-tab window.

**Screenshots / video**
<img width="624" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/1038132/c06fea03-2e30-494c-999a-bfb23b4ffa07">
<img width="134" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/1038132/4da93f77-7249-4a2e-a479-5bf46f955462">
![WechatIMG55](https://github.com/lwouis/alt-tab-macos/assets/1038132/d42bd007-3668-43f4-8e46-ca0bd1f8bbe4)

**Your environment**

* AltTab version: 6.60.0
* macOS version: 13.4.1 (22F82)
* Other relevant info: e.g. using external keyboard, multiple monitors, etc

**Comment by lwouis** [comment]
Hi,

This is most likely an issue with this app QQ. Could you please contact their maker/support to get it looked at?

Thank you 🙇

**Comment by zhaoxuan** [comment]
> Hi,
> 
> This is most likely an issue with this app QQ. Could you please contact their maker/support to get it looked at?
> 
> Thank you 🙇

Hi,
Alright, how should I explain this problem. It is ok in the system alt-tab window
![WechatIMG56](https://github.com/lwouis/alt-tab-macos/assets/1038132/73695e09-8e67-4d5e-824b-f9ff5e878db6)

**Comment by zhaoxuan** [comment]
Hi,
I found this situation was fine, first I started QQ app, then run alt-tab-macos app, all apps were in alt-tab-macos window.
![WechatIMG57](https://github.com/lwouis/alt-tab-macos/assets/1038132/ef7d2986-4fdd-440b-b030-9baf9b427232)
Thanks.
