### ISSUE TITLE
Cannot focus the selected window

### ISSUE THREAD

**Issue by richardchui** [lwouis/alt-tab-macos#2669]
After switching to the selected window, that window does not receive the focus. Would require an additional mouse click.

**Comment by lwouis** [comment]
Could you please share a video of the issue? Which app is affected? All apps or a specific one?

**Comment by richardchui** [comment]
It seems to happen when the apps are on different spaces. When I first switch to a new app, it won't get focus. If I Alt-Tab to it again (it is now first in the list), it will get focus.

I am not sure if you can see my actions from this video. 
- I switch to a notes app, no focus and cannot type
- I Alt-Tab to itself, can now type
- I switch to a browser app, no focus and cannot invoke the dialog box with keyboard shortcut
- I Alt-Tab to itself, now can invoke the dialog box
https://github.com/lwouis/alt-tab-macos/assets/678409/f9d5c156-fd9a-48d7-8985-5b28a6652985

**Comment by richardchui** [comment]
Any update on the above?  Thanks!

**Comment by lwouis** [comment]
Hi @richardchui,

I just tested this, and it focuses correctly on my machine. I think something is going on with your setup.

* Does this happen if the windows are on the same Space?
* When you switch to the other Space, and the window is not focused, I can see indeed that the window traffic-light buttons (i.e. the buttons to minimize, fullscreen, or close the window) are not colored. This confirms that the window is indeed not focused. What is the app title in the menubar at that point in time? It's not captured on the video. I have a feeling that it could be that you have another app running on your system that for some reason grabs focus right after you switch Space. Maybe it's that screenshot app I see listed in AltTab; not sure.

Thank you

**Comment by lwouis** [comment]
Thank you @richardchui 

Could you please share what the app title is in the menubar, when you switch to another window, but it is not focused? It could let us know right away which app is stealing focus.

Thank you

**Comment by richardchui** [comment]
Hi @lwouis ,

The menubar is show the title of the app that I am switching from.

**Comment by lwouis** [comment]
It's not that clear then what is happening. I'll close this ticket for now since it's not actionable with the current data we have. In the meantime, we discuss a general potential new implementation of window tracking/focusing here: https://github.com/lwouis/alt-tab-macos/issues/447
