### ISSUE TITLE
Android emulator shown as two windows

### ISSUE THREAD

**Issue by exidler** [lwouis/alt-tab-macos#2671]
**Describe the bug**

Android Emulator run from Intellij IDEA (Community, or possible Android Studio too) (Launch in a tool window disabled) show like 2 windows (emulator window and control panel separate)
I think must be show like only one window (possible to hide control window from windows list)

**Screenshots / video**

<img width="748" alt="Screenshot 2023-07-14 at 00 40 35" src="https://github.com/lwouis/alt-tab-macos/assets/4411993/556659c5-14c3-4453-88bb-6ea9cdfaf51b">

**Steps to reproduce the bug**

1. Run IDEA
2. Go to Settings, Tools, Android, Android Emulator.
3. Uncheck Launch in a tool window
4. Run any instance of device emulator
5. Press Alt+Tab :)

**Your environment**

* AltTab version: 6.60.0
* macOS version: 13.4.1
* Other relevant info: qemu version 33.1.15

**Comment by lwouis** [comment]
Please see https://github.com/lwouis/alt-tab-macos/issues/2178
