### ISSUE TITLE
Hide from menubar

### ISSUE THREAD

**Issue by nexuspcs** [lwouis/alt-tab-macos#2680]
**Is your feature suggestion related to a problem? Please describe.**
Not specifically, rather, in an ideal world, i believe that introducing a checkbox in AltTab settings to hide the application from the MacOS menu bar would be an ideal outcome. 

**Describe the solution you'd like**
A button allowing users to hide the AltTab icon from the menubar, freeing up valuable menubar space. 
**Describe alternatives you've considered**
Installing software such as BarTender, but I do not want to run extra software such as bartender if needed

**Comment by lwouis** [comment]
It's already possible in Preferences. Please use the dropdown to pick a different icon. The last row is "no icon".
