### ISSUE TITLE
Show windows from: All but current app

### ISSUE THREAD

**Issue by cyaconi** [lwouis/alt-tab-macos#2684]
**Is your feature suggestion related to a problem? Please describe.**
I normally have several browser windows active, and I have shortcuts for cycling windows from the current app and another for cycling windows from all apps. Other windows from the same app are presented when I use the shortcut to cycle all apps, and because I have a special shortcut for that, I expect to cycle windows from other apps exclusively.

**Describe the solution you'd like**
I propose adding a new option to the "Show windows from" menu: **All but current app**.
This allows users to cycle among windows from other open applications rather than the one they are now using.

**Describe alternatives you've considered**
Another alternative could be a select box in the same shortcut configuration: **Windows from the same app**: Show|Hide

**Comment by lwouis** [comment]
Hi,

It's an interesting idea. I'm afraid it's too niche to warant the added complexity though. Please see #351 for context on why we want to reduce the number of preferences.

I'll close the ticket for now. If other people show interest here, we can re-open the ticket.

Thank you 🙇
