### ISSUE TITLE
Apps, not windows

### ISSUE THREAD

**Issue by michaelcushing** [lwouis/alt-tab-macos#2689]
My workflow doesn't require seeing both all windows and all apps and so the ability to display only the apps would be great.  I suspect adding a "No apps" choice to the "Show windows from:" pulldown menu in Controls/Shortcut 1,2,... would do it.

The default apple version doesn't launch a new window if one is not open which is why I have been looking for alternatives.

**Comment by lwouis** [comment]
Hi @michaelcushing,

I'm afraid it's a bit niche at the moment. When more people ask for this, I'll re-open the ticket 👍 

Thank you
