### ISSUE TITLE
Removing accessibility permission breaks the `cmd` key

### ISSUE THREAD

**Issue by gitgetgot** [lwouis/alt-tab-macos#269]
I'm using a MacBookPro 2015, Mojave, AltTab v3.15.0.

At first start of AltTab, I need to create and activate this:
<img width="493" alt="Bildschirmfoto 2020-04-23 um 20 51 40" src="https://user-images.githubusercontent.com/974980/80138238-cab1c480-85a4-11ea-8af8-4a39a30c75ad.png">

When I -for whatever reason- DISABLE it
<img width="519" alt="Bildschirmfoto 2020-04-23 um 20 54 03" src="https://user-images.githubusercontent.com/974980/80138235-c8e80100-85a4-11ea-9c9a-2a0cda4ffbbc.png">

the CMD key is **inacessible** anymore,
I cannot use systemwide CMD+TAB to navigate anymore,
but I can use ALT+TAB (as configured by default in AltTab) to navigate.

Exiting AltTab ends this strange behaviour, where it seems, that CMD key is not working anymore (not possible to start spotlight via CMD+SPACE or take a screenshot with CMD+SHIFT+4)

Same odd behaviour, when I configure CMD instead of the ALT key in AltTab

Same odd behaviour was in older version of AltTab too.

Re-Activating, as in the first screenshot, and everything seems normal again.

**Comment by lwouis** [comment]
You are disabling the permissions while already using AltTab, correct? This is currently not supported unfortunately. There is a ticket to support that (kind of): #127.

I don't think many people change the permissions while running the app. Also the issue goes away if you restart the app as it asks you again for permissions, or if you re-enable the permission.

You said "When I -for whatever reason- DISABLE it". Could you help me understand what's your use-case to disable the permission while the app is running?

**Comment by lwouis** [comment]
@gitgetgot I released a new version of AltTab which quits if you the permission is removed during runtime. It's a first quick win, as the app doesn't swallow keyboard inputs now. A more advanced UX can now be discussed in #127.

Also I'm still curious about your use-case of disabling permissions during runtime. Why do you need to do such a thing?
