### ISSUE TITLE
All arrow key short cuts override

### ISSUE THREAD

**Issue by michaelcushing** [lwouis/alt-tab-macos#2690]
I use command+arrow keys to move between desktops which means I cannot use the arrow keys to move between icons when alt/tab is showing because I end up switching desktops instead.  Wondering if there is a way to mimic the apple command-tab which allows me to move between apps when the switcher is active using command+arrows but also allows me to use command+arrows to move between desktops when the switcher isn't active.

**Comment by lwouis** [comment]
Hi @michaelcushing,

I'm afraid this is not possible, or would be really complex technically to implement. Arrows are a Local shortcut for AltTab, whicile the Desktop Switching shortcuts you have set are Global. Global shortcuts have priority over Local ones, so AltTab doesn't get a chance to react. I can only suggest avoiding the conflict by using something else than `command` for either AltTab or the System shortcuts you've set.

Thank you
