### ISSUE TITLE
Live Preview like windows 11

### ISSUE THREAD

**Issue by AISLVE** [lwouis/alt-tab-macos#2694]
It would be great to see the live update feature like when i play a video in windows it can be seen being played after pressing alt+tab or like the stage manager

**Comment by lwouis** [comment]
Please see #122

**Comment by AISLVE** [comment]
What about even windows, right now they are shown in preview based on their size(some are small some are large), but I sometimes have visual problems where I can't exactly see the preview because it's too small, it's not that big of a deal,but would be a great QOL feature
