### ISSUE TITLE
Is it possible to make it compatible with older macOS versions

### ISSUE THREAD

**Issue by sebamenabar** [lwouis/alt-tab-macos#27]
Hello, the app is a great idea, always suffer this problem.

I think the title is self descriptive, could it work with older versions, for example (I'm using)
Sierra 10.12.6 (Can't update to new versions).

**Comment by lwouis** [comment]
Could you help describe the issue you experience on Sierra? I only have a laptop with Mojave, so can't reproduce on my side unfortunately

**Comment by adrianbj** [comment]
Running High Sierra and I get a message saying that this app requires 10.14 or higher.

**Comment by lwouis** [comment]
Please checkout [version 1.2.0](https://github.com/lwouis/alt-tab-macos/releases/tag/v1.2.0) that should run from 10.11 onwards.

I tried to test in a VirtualBox VM, but couldn't get it to work. It should work in theory as all APIs are available from 10.11 onwards, but we never know. If you see any issue please open a new ticket

**Comment by sebamenabar** [comment]
Thanks, it works! Is it possible to change the keymap to alt+tab? ctrl+tab is the firefox method to change tabs.
