### ISSUE TITLE
Allow navigation with up/down arrow keys

### ISSUE THREAD

**Issue by gitgetgot** [lwouis/alt-tab-macos#270]
<img width="571" alt="Bildschirmfoto 2020-04-23 um 21 05 43" src="https://user-images.githubusercontent.com/974980/80139159-45c7aa80-85a6-11ea-9aa7-f2874604bc90.png">

If activated, only use of left/right arrows seems to be possible, but with two or more rows it would be nice to press up/down to quickly access the desired tab.

**Comment by lwouis** [comment]
There is already a ticket for that: #64. It's not trivial to implement, thus while it's been in the backlog for a little while now, unfortunately. I'll close the other one as duplicate as yours has screenshot and the other ticket talks about the old collectionview which is no longer how it's implemented.

**Comment by lwouis** [comment]
While implementing this, I first started with a geometrical-based approach: going down means finding the next thumbnail in that direction, potentially skipping multiple rows. For example going from `1` to `2`, by pressing `down`:

```
[   ]  [   ]  [ 1 ]
       [   ] 
[   ]  [   ]  [ 2 ]
```

Then I tested on Windows 10, and they do row-by-row which I think is more suited for what our use-case of switching windows. The same example would do this here:

```
[   ]  [   ]  [ 1 ]
       [ 2 ] 
[   ]  [   ]  [   ]
```
