### ISSUE TITLE
Input source indicating bubble on macos senoma makes AltTab fail to switch windows

### ISSUE THREAD

**Issue by cuiweiwei** [lwouis/alt-tab-macos#2711]
**Describe the bug**

macos 14 senoma added an input source indicating bubble when switching Windows, but AltTab may recognize this input source indicating bubble as a window, make it cannot be switched, can only wait forindicating bubble to disappear

**Your environment**

* AltTab version: 6.61.0
* macOS version: 14 beta

**Comment by lwouis** [comment]
#2604
