### ISSUE TITLE
Shortcut not saved after restart

### ISSUE THREAD

**Issue by KiritoXD01** [lwouis/alt-tab-macos#2712]
**Describe the bug**

Everything started when I added a Mac Mini to my iCloud account, I disabled handoff because I don't need it, but after that, in my Macbook Pro, every time AltTab starts, it forgets the Command + Tab shortcut that I assigned to it, and default to the Mac OS default switcher, AltTab runs as normal and I can set the shortcut back, but this is happening a lot

**Screenshots / video**

<img width="570" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/46627083/702023b5-a23c-472e-87d4-7efec60938db">

**Steps to reproduce the bug**

1. AltTab is set to run on Startup
2. When I hit Command + Tab, it shows the default Mac OS switcher

**Your environment**

* AltTab version: 6.61.0
* macOS version: 13.5
* Other relevant info: e.g. using external keyboard, multiple monitors, etc

**Comment by lwouis** [comment]
Hi,

I'm not sure I understand. Are you saying that when you reboot, AltTab gets set to `option+tab`, and you have to re-set it to `command+tab` like on your screenshot?

Thank you

**Comment by KiritoXD01** [comment]
Correct, like it reset the shortcuts to the default settings, the other configurations are fine

**Comment by lwouis** [comment]
Could you please execute this command in Terminal.app, before you fix the shortcut (when it's set to `option+tab`) and after you've fixed it (when it shows `command+tab`)?

```sh
defaults read com.lwouis.alt-tab-macos
```

Thank you

**Comment by KiritoXD01** [comment]
Before shortcut fix
<img width="344" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/46627083/5b0a22d8-530a-4c53-94e3-09ee99160019">

After shortcut fix
<img width="336" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/46627083/0311de80-e9f3-44da-8dfe-57f3bba47bd2">

Should I reinstall the program?

**Comment by lwouis** [comment]
This is unexpected. The output you get means that AltTab has not saved *any* preference.

My best guess would be that you're running AltTab from a non-standard folder (i.e. not `/Applications`), or that you're running it from a non-standard account (e.g. low priviledges), or something of that sort (e.g. company software or antivirus which messes up with permissions).

AltTab is using the most standard way on macOS to store preferences. Same way other apps and Apple first-party apps do it. It also works for all other users. Thus I believe something unique about your setup is at play here.

**Comment by KiritoXD01** [comment]
Everything started when I linked a new PC to my iCloud account, I'll try reinstall it and I'll let you know

**Comment by KiritoXD01** [comment]
@lwouis I reinstalled and it works now, maybe I did something wrong when I created the account on the new PC, thank you for your assistance
