### ISSUE TITLE
Preview open windows from dock

### ISSUE THREAD

**Issue by tmnrdhf** [lwouis/alt-tab-macos#2721]
Ever since I've been using macOS, I'm heavily missing a way to preview all open windows of a specific app right from the dock, simply by hovering over the app icon.

There used to be [Hyperdock](https://bahoom.com/hyperdock/) (which AltTab is comparing itself to on the website) and [Dockmate](https://www.macenhance.com/dockmate) but both are not supported anymore (outdated to the point that they don't work anymore) and not open source. 

Since AltTab already records the open windows to fix another big flaw of macOS, it would be amazing if it could also give us the option to preview windows right from the dock.

**Comment by lwouis** [comment]
AltTab won't support this, unfortunately. It's a bit of a different use-case, for another audience often.

I know that this exists: https://dockalttab.netlify.app/

You may want to check it out 👍

**Comment by tmnrdhf** [comment]
Ok, I understand that. Thanks anyways for creating this awesome app!
(And also thanks for recommending the alternative, I will check it out.)
