### ISSUE TITLE
Switch Between Spaces instead of Windows?

### ISSUE THREAD

**Issue by AlJohri** [lwouis/alt-tab-macos#2723]
**Is your feature suggestion related to a problem? Please describe.**
I'm interested in a feature that can allow switching between entire spaces or desktops as opposed to windows.

**Describe the solution you'd like**
I've recently moved to a tiling window manager (yabai) and instead of pressing `CMD+TAB` to switch between applications or windows, I would love to switch between entire spaces.

**Describe alternatives you've considered**
Alternatively I can use `ctrl+left` and `ctrl+right` to switch between spaces or `ctrl+up` and then move my mouse to the top of the screen to directly select a space. However, I would like a quick keyboard shows that shows me a visual representation of what each space currently looks like and the ability to quickly switch to any one of them by cycling through `CMD+TAB`.

P.S. If you know of any alternative apps that can do this I would love to hear.

Related Links:
- Hyperspaces: https://hyperspacesapp.com/
- TotalSpaces 2: https://totalspaces.binaryage.com/
- TotalSpaces 3 Alpha: https://discuss.binaryage.com/t/can-we-help-test-total-spaces-3-if-we-have-apple-silicon/8199
- https://github.com/dshnkao/SpaceId
- https://github.com/xiamaz/YabaiIndicator
- https://github.com/gechr/WhichSpace
- https://github.com/lwouis/alt-tab-macos/issues/337

**Comment by lwouis** [comment]
Hi,

i think yabai should let you bind a shortcut to switch. It won't show previews of the Spaces though. There are all the apps you linked as well. You didn't get the result your wanted with those?

Regarding AltTab, it could happen through #337 perhaps.

**Comment by AlJohri** [comment]
Thanks for the quick response @lwouis! I think what I am looking for is really #337 as I would like to see a preview of the spaces and iterate between them like AltTab does. Yabai space management requires disabling SIP which is currently not an option for me.

The closest I found so far is the TotalSpaces3 alpha which shows a preview like this upon pressing a keyboard shortcut and appears to be working with the latest macOS:
![Screenshot 2023-08-07 at 7 57 24 AM](https://github.com/lwouis/alt-tab-macos/assets/2790092/4dd28417-716b-478c-9622-cb1f8e13324b)

However, it seems development has stalled on TotalSpaces3. Currently its a bit buggy (occasional crashes) and opening the spaces preview has a long transition which cannot be disabled. I'm primarily looking for an Alt-Tab like experience through the spaces like #337 describes.
