### ISSUE TITLE
Wired window shows in AltTab when using Tencent meeting

### ISSUE THREAD

**Issue by realCrush** [lwouis/alt-tab-macos#2727]
When using Tencent Meeting, when using Alt+Tab to switch windows, strange windows such as empty windows and floating windows will appear in addition to the main meeting window, as shown in the picture.
![image](https://github.com/lwouis/alt-tab-macos/assets/57980447/b6888e9f-f5ef-492c-819d-300b58bdcec6)

**Comment by lwouis** [comment]
This is an issue with that app. AltTab reports these windows because they exist, and report themselves as user windows.

Could you please contact the customer support of Tencent Meeting so they can fix their issues?

thank you
