### ISSUE TITLE
Switch between windows of the same application

### ISSUE THREAD

**Issue by lianaling** [lwouis/alt-tab-macos#2744]
**Is your feature suggestion related to a problem? Please describe.**
Windows' alt+tab has been great for multiple windows within and across different applications, whereas Mac's cmd+tab is great for many applications with single windows. Using alt+tab is great until there are simply too many windows to switch from. It would be great if Mac's cmd+tilde was enhanced so that we can choose the application we want and switch only between that application's windows.

**Describe the solution you'd like**
Mac's cmd+tilde only **cycles** through all windows, which is frustrating when you have more than 2 windows open. It would be great for Alt-Tab to implement an additional hotkey to switch between windows only from the **same** application ordered based on the two most recent windows for fast switching. (It's just like cmd-tab but for windows within the same application only.)

**Describe alternatives you've considered**
For now I have not found any alternatives available online to combine the best of both worlds from Windows and Mac. I really just want Apple to change their cmd+tilde logic — instead of cycling through, just switch between two most recent windows. But I guess that's never going to happen.

**Comment by sapoepsilon** [comment]
Hey, @lianaling  that feature is already supported in Settings -> Controls -> Shortcut 2
<img width="656" alt="Screenshot 2023-08-22 at 7 49 12 PM" src="https://github.com/lwouis/alt-tab-macos/assets/47342870/3c2f5d42-c1de-4eaa-9129-54a12ac2b139">

**Comment by lianaling** [comment]
Oh. Thanks for the reply. Sorry for missing that out!
