### ISSUE TITLE
Ubuntu-style alt + tab

### ISSUE THREAD

**Issue by justanhduc** [lwouis/alt-tab-macos#2745]
Hi. I moved on from Ubuntu to MacOS and somewhat I miss its alt+tab that switches between apps, not windows, and alt+` switches between windows of the active app. Is there any way to do that in the current version? If not, I would like to suggest this new feature. Thanks!

**Comment by lwouis** [comment]
Alt+` already does exactly that. For alt+tab to switch between apps, we have this ticket already: #337
