### ISSUE TITLE
Arc browser's "Little Arc" window does not appear in the switcher

### ISSUE THREAD

**Issue by zzamboni** [lwouis/alt-tab-macos#2751]
**Describe the bug**

I've been using [Arc](https://arc.net/) as my main browser recently, and one of its features is "Little Arc" - a simpler, unadorned window that is used by default to open "temporary" links. I have noticed that the Little Arc window does not appear at all in the AltTab switcher. This window appears correctly in the native macOS Mission Control switcher.

**Screenshots / video**

Little Arc in Mission Control (it's the Google window):
<img width="1392" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/32876/28dd56c8-f54e-4c46-bfaa-9e765f1b6838">

Exact same set of windows open, but it does not show up in the AltTab application-window switcher (it also doesn't appear in the all-windows switcher):
![image](https://github.com/lwouis/alt-tab-macos/assets/32876/d52d447e-f6b4-4947-bc88-fa172eb06a29)

**Steps to reproduce the bug**

1. Install Arc
2. Run in the Terminal: `open -a Arc https://google.com/` - this should open the Google page in the Little Arc window by default.
3. Try switching to the Little Arc window with AltTab.

**Your environment**

* AltTab version: 6.61.0
* macOS version: 13.5.1 (22G90)

**Comment by lwouis** [comment]
Please see https://github.com/lwouis/alt-tab-macos/issues/2257
