### ISSUE TITLE
Screen recording symbol in the menu bar

### ISSUE THREAD

**Issue by SHM93** [lwouis/alt-tab-macos#2756]
Hello, my name is Shlomi and I've just found this amazing app and started to use. 
One thing that I wanted to point is why every time I use Alt+tab the Mac will notify me that the screen recording is on by a purple symbol on the top right of the menu bar. 
It's quite annoying I would say and and will be nice to get rid of this if possible.

**Comment by lwouis** [comment]
Hi Shlomi,

There is already a ticket to track this: https://github.com/lwouis/alt-tab-macos/issues/2606 It's an issue with macOS Sonoma beta.

**Comment by SHM93** [comment]
Thanks for answering!! 
I actually have one more question if possible.... is there an option to change the way the windows are presented, more specifically the angle. Some windows appear exactly like in 'windows' and some are oblique and I tried to play with the preferences but nothing changed. 
Attached a picture. 

Look at the calendar app, it's different from the other in this example ![image](https://github.com/lwouis/alt-tab-macos/assets/124248452/7e2b16c2-0bcf-495c-9ddd-63050155ddd1)

**Comment by lwouis** [comment]
Hi,

The tilted windows are due to Stage Manager being enabled on your machine. I suggest you disable it if you don't use it.

Thank you

**Comment by SHM93** [comment]
Ohh ok! 
Thanks a lot 🙏🏽
