### ISSUE TITLE
Input methods and caps lock indicator shown as windows in Alt-Tab

### ISSUE THREAD

**Issue by freewizard** [lwouis/alt-tab-macos#2758]
**Describe the bug**

macOS 14.0 Beta (23A5328b)
Alt-tab Version 6.61.0

 input methods and caps lock indicator shows up as windows in Alt-Tab

**Screenshots / video**
![image](https://github.com/lwouis/alt-tab-macos/assets/7655/c1e6666b-fc91-4eb6-919c-eb0295ba0763)

**Comment by lwouis** [comment]
Thank you for reporting. We've seen similar macOS bugs in previous Betas. I guess it's the purpose of Betas to catch such regressions in the OS.

I'll close this as it's a macOS bug, and it's likely to be fixed once the OS goes live 👍

**Comment by WinnieJiangHW** [comment]
The problem seems still be there in the stable version.
