### ISSUE TITLE
Tab group support with names and icons

### ISSUE THREAD

**Issue by avivo** [lwouis/alt-tab-macos#2771]
**Is your feature suggestion related to a problem? Please describe.**
I don't know which windows have which tab groups.

**Describe the solution you'd like**
I want to be able to easily see the current tab group of a chrome window, both in the name and with the icon. This would also be great across other browsers that now include tab groups. The window name for alt-tab would then ideally be "${tabgroup}: ${pagetitle}". The icon would ideally be the icon for the browser, and then a smaller icon for the tab group/color as a sort of subscript.

**Describe alternatives you've considered**
You can manually name windows in Chrome, but that messes up other software that relies on the window name.

**Comment by lwouis** [comment]
These tab groups are custom UIs from apps. It's not using a standard macOS UI. We can't support that. It's the same reason we support standard tabs today but not browser tabs. All major browsers do custom tabs instead of standard tabs, so we can't support it.

**Comment by avivo** [comment]
Yes, this would likely require building things custom for different browsers based on their API's. I figured it was worth sharing as a possibility in case the benefit was high enough for people. From my perspective the browser is its own sort of OS and window manager so it seems worth it to have ways of better navigating it! But I totally understand if you are concerned about the sort of bloat that comes out of custom features like this.
