### ISSUE TITLE
altTab should not show itself at all if pressing alt + tab and immediately letting go of alt

### ISSUE THREAD

**Issue by BDR159** [lwouis/alt-tab-macos#2790]
**Is your feature suggestion related to a problem? Please describe.**
Yes. When I press `alt + tab` and immediately let go of alt, I can still see the AltTab window for a split second before it disappears and changes to the previous window I was looking at.

**Describe the solution you'd like**
With the traditional `cmd + Tab`, if you press `cmd + tab` quickly and immediately let go of `cmd`, it will switch to the prevous application without the `cmd + tab` menu coming up at all, so it doesn't visually distract me. I think this behaviour would be great in AltTab too.

**Describe alternatives you've considered**
There doesn't appear to be any alternatives - the principle of the solution is quite simple. I did check for settings to see if this behavior could be replicated.

**Comment by lwouis** [comment]
Hi @BDR159,

If you think longer about what you describe, you'll realize that it's not that simple.

AltTab was optimized to be low latency. That means that after only a few milliseconds after you press the shortcut, it will show on screen. In other words, you're probably not fast enough to release the keys before AltTab is shown.

The only way then is to introduce an artificial time window during which the window won't show. That's exactly what we've added. You can set it in the preferences > Appearance. Set for instance 250ms delay and any press+release shorter than this will not have AltTab show.

I prefer a reactive app over an esthetic app, so by default AltTab is as fast as it can. For people who don't like the flickering, they can set a delay to avoid it. I didn't want the delay for everyone by default, so it's an opt-in preference.

Thank you
