### ISSUE TITLE
Ability to limit nr of windows

### ISSUE THREAD

**Issue by carpusmedia** [lwouis/alt-tab-macos#2795]
**Is your feature suggestion related to a problem? Please describe.**
I found AltTab a few days ago and have been using it a lot since. I often have 60-100 windows open on my Mac, many in fullscreen mode, and this sometimes crashes AltTab (stops responding and I have to force quit it through Activity Monitor)

**Describe the solution you'd like**
Is there a feature coming where one could limit the number of windows showing? This could help on my end.

Thank you for an awesome piece of software!

**Comment by lwouis** [comment]
It's surprising that AltTab would hang on 60-100 windows. Perhaps you're on older hardware?

I can suggest filtering the windows in the preferences. You could hide windows which are minimized, hidden, on other Spaces, on other Screens, etc. This should help you reach a reasonable number of windows to display 👍

**Comment by carpusmedia** [comment]
Actually it's a maxed out MacBook Pro 2021 (M1 Max 64GB 4TB), Ventura 13.5.

I'll try that, thank you!
