### ISSUE TITLE
Monero GUI does not show

### ISSUE THREAD

**Issue by Noiden** [lwouis/alt-tab-macos#2798]
**Describe the bug**

If I have Monero GUI open and do "alt-tab" I can't see this in the application.

**Screenshots / video**

I don't think this is needed. I just don't see the Monero GUI window in the "alt-tab" window.

**Steps to reproduce the bug**

1. Start Monero GUI.
2. Use the "alt-tab" shortcut to open alt-tab and see open programs.
3. See that the Monero GUI window is missing.

**Your environment**

* AltTab version: 6.61.0
* macOS version: 13.5.2 (22G91)
* Other relevant info: Using multiple screens. The Retina Display on the MacBook Pro and also an external screen through a USB-C Docking station.

**Comment by lwouis** [comment]
This is most likely an issue with this software. Please contact their customer support. They likely are misusing macOS SDK and not making a proper window
