### ISSUE TITLE
show window on display with the mouse, not where an active window is

### ISSUE THREAD

**Issue by Somberland** [lwouis/alt-tab-macos#28]
I'm working with an 3-display setup, sometimes it happens that I select the wrong window. when I open the switcher again the overlay is on the monitor with the opened app, even if my mouse is on an other display.

see also #8

**Comment by lwouis** [comment]
To illustrate your reference to #8, this is what the preference looks like in HyperSwitch:

![image](https://user-images.githubusercontent.com/106195/67002112-268f2280-f116-11e9-8baf-34df5d43cd05.png)

**Comment by lwouis** [comment]
Please check out [release 1.12.0](https://github.com/lwouis/alt-tab-macos/releases) which implements this feature!
