### ISSUE TITLE
Slack displayed even when minimized

### ISSUE THREAD

**Issue by dospolov** [lwouis/alt-tab-macos#2803]
The slack app is closed with X-button (no minimized window in the doc). Nevertheless it is displayed in the list of the apps.

<img width="1352" alt="Screenshot 2023-09-22 at 07 35 21" src="https://github.com/lwouis/alt-tab-macos/assets/670682/6af4f000-1bc1-4106-8427-5fcc53f50fb4">

1. Set "Hide minimized windows" in the settings
2. Close slack
3. Observe slack persist in alt-tab list. No other apps cause this issue

AltTab Version 6.61.0
System Version:	macOS 13.5.1 (22G90)
MacBook pro m1, 14-inch, 2021, no external monitor.

**Comment by lwouis** [comment]
Slack does non-standard things on macOS. Closing the window doesn't close it buy hides it.

AltTab just reports things. If you right click the Slack Dock icon, you'll see the window as well.

This behavior is the work of Slack. Please contact their support.
