### ISSUE TITLE
AutoCad Windows is not shown . 

### ISSUE THREAD

**Issue by Usefz89** [lwouis/alt-tab-macos#2809]
**Describe the bug**

While the AutoCad application windows is open. You cannot see it in AltTab. Please check the attached screenshot. 
- Macbook Air M2.
-  Mac OS Ventura. Version 13.4.1
- Alt-Tab version: 6.61.0
- Autocad 2024.

**Screenshots / video**

<img width="1470" alt="Screenshot 2023-09-25 at 12 48 51 PM" src="https://github.com/lwouis/alt-tab-macos/assets/16023398/14f19bbe-bbe4-45ba-b1d3-2c2ebbcd59b2">
<img width="1470" alt="Screenshot 2023-09-25 at 12 48 44 PM" src="https://github.com/lwouis/alt-tab-macos/assets/16023398/f0548d50-83e2-44ad-9b2b-6393171000ba">

**Comment by lwouis** [comment]
Hi,

Please contact AutoCAD's customer support. It's most likely a bug on their side.

Thank you

**Comment by lwouis** [comment]
The latest release adds a workaround for AutoCAD. Windows should show up now. Hopefully this workaround works until AutoCAD makes their actual fix 👍
