### ISSUE TITLE
Not working with some apps (not blacklisted)

### ISSUE THREAD

**Issue by jgarces02** [lwouis/alt-tab-macos#2810]
**Describe the bug**

I don't know why but (the wonderful) AltTab is not working with some specific apps (and these aren't included in the blacklist)

**Steps to reproduce the bug**

1. Activate _AtlTab_
2. Open _Sublime Text_ or _iTerm2_
3. Try to adjust their position with your custom shortcut... not working for me.

**Your environment**

* AltTab version: 6.61.0
* macOS version: Ventura 13.5.2 (22G91)
* Other relevant info: using external Magic keyboard and Magic Trackpad, and an additional external monitor (not affecting).

**Comment by lwouis** [comment]
I think you're seeing #1324. You could try having all apps on the same Space, with no app in fullscreen? Does AltTab show the app windows then?

thank you

**Comment by jgarces02** [comment]
It seems rebooting the system was enough. Thanks and sorry for this silly thing!
