### ISSUE TITLE
Unable to hide no-window apps.

### ISSUE THREAD

**Issue by Oscar-Rosenwald** [lwouis/alt-tab-macos#2812]
**Is your feature suggestion related to a problem? Please describe.**
Whenever I want to switch to another window, I see a list of apps with no windows in addition to regular windows, and I couldn't find an option to hide them. It would be really nice to be able to map some shortcuts to only list open windows, rather then all running apps.

**Describe the solution you'd like**
A new option line after the fashion of "Hidden windows" and "Fullscreen windows," which would let me hide the list of apps with no windows.

**Comment by lwouis** [comment]
There is a checkbox for this in Preferences > Appearance

**Comment by Oscar-Rosenwald** [comment]
There is, thank you for pointing it out to me. This applies the setting to all shortcuts. Is there a way to do this per shortcut instead?

**Comment by lwouis** [comment]
No sorry, it's global only 🙇
