### ISSUE TITLE
Please make an update to hide the screencapture icon on macos sonoma

### ISSUE THREAD

**Issue by anglee0323** [lwouis/alt-tab-macos#2819]
**Please make an update to hide the screencapture icon**

**Screenshots / video**

![](https://raw.githubusercontent.com/anglee0323/Picbed/main/CleanShot%202023-09-27%20at%2022.38.21%402x.png)

**My environment**

* AltTab version: 6.60.0
* macOS version: macos sonoma

**Comment by Neoconair** [comment]
Same for me, probably universal on 14.0
![Screenshot 2023-09-27 at 4 31 19 pm](https://github.com/lwouis/alt-tab-macos/assets/117582025/957e58d1-d048-443d-a899-9810b62e6a4e)
