### ISSUE TITLE
'AltTab is capturing screen' message shown when tabbing to a new window 

### ISSUE THREAD

**Issue by tejxv** [lwouis/alt-tab-macos#2822]
**Describe the bug**

This Indicator appears whenever i tab to another window. It's happens almost 99% of the time.

**Screenshots / video**

<img width="379" alt="Screenshot 2023-09-27 at 11 48 41 PM" src="https://github.com/lwouis/alt-tab-macos/assets/54097365/575ad690-8c38-48d9-b82a-de986df51844">

**Your environment**

* AltTab version: 6.61.0
* macOS version: Sonoma 14.0

**Comment by taschetto** [comment]
Relates to https://github.com/lwouis/alt-tab-macos/issues/2600
