### ISSUE TITLE
Start up properly without screen caprturing permission granted

### ISSUE THREAD

**Issue by mikluko** [lwouis/alt-tab-macos#2836]
**Is your feature suggestion related to a problem? Please describe.**

Application startup gets blocked if no screen capturing permission is granted. Related to #2606.

<img width="623" alt="Screenshot 2023-09-27 at 23 38 33" src="https://github.com/lwouis/alt-tab-macos/assets/42915/36eb5d60-c925-43b4-a69a-7a09255f3a76">

**Describe the solution you'd like**

I'd like application to start up normally even though I don't grant screen capturing permission. From GUI perspective, "proceed" button along with "don't show again" checkbox might be a viable solution.

**Describe alternatives you've considered**

Alternative is granting the permission but switching off window thumbnails. That is a kind of okayish workaround for the time being.

**Comment by lwouis** [comment]
#1082
