### ISSUE TITLE
"alt tab is capturing your screen" is constantly being shown up in the menu bar when apps are switched on macOS Sonoma

### ISSUE THREAD

**Issue by Peterr1001** [lwouis/alt-tab-macos#2841]
**Describe the bug**

As soon as I updated my m2 macbook air to the newest macOS Sonoma, this purple popup started showing up in the menubar, which is a bit annoying.

**Screenshots / video**

<img width="897" alt="Screenshot 2023-09-30 at 13 52 04" src="https://github.com/lwouis/alt-tab-macos/assets/145347259/fd05ccbe-36ed-48e6-85b9-42d965abd362">

<img width="659" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/145347259/426223b5-5271-48bd-bac4-92876c890251">

**Steps to reproduce the bug**

1. Switch windows
2. It appears as shown in the attached image

**Your environment**

* AltTab version: Version 6.61.0
* macOS version: 14.0 (23A344)

**Comment by lwouis** [comment]
#2606
