### ISSUE TITLE
Bug while switching between windows (MacOS Sonoma 14.0)

### ISSUE THREAD

**Issue by shipotech** [lwouis/alt-tab-macos#2848]
**Describe the bug**

After I updated to MacOS Sonoma the app doesn't work properly. When I hold "cmd" and then press "tab" to switch from one app to another the "active windows" (I mean where all the active windows appears and allow you to select one or another) starts to blink very fast, mixing up my "window titles" and then if I release "tab" to go to an app, the "active windows" is still on screen, I have to click outside in order for it to disappear. I tried changing and mixing all the custom preferences, nothing helped.

**Steps to reproduce the bug**

Just use the app to switch between windows.

**Your environment**

* AltTab version: 6.60 or 6.61
* macOS version: 14.0
* Other relevant info: macbook air m1, using external keyboard (logitech mx keys), one external monitor.

**Comment by lwouis** [comment]
Hi,

Blinking and having to click outside to close. These sound like symptoms coming from you having 2 instances of AltTab running at the same time. Do you see 2 AltTab icons in the top menubar?

Thank you

**Comment by shipotech** [comment]
<img width="200" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/46910608/ead0b799-71cc-481a-899b-0e52781eedd9">

You are right, there are two instances. Idk how, I tried to uninstall, restart, install again and it works properly. As soon as I restart my mac, I can see 2 icons on the top menubar (I didn't see them before because I used the transparent icon). What can I do?

**Comment by lwouis** [comment]
In the preferences, uncheck the checkbox to have AltTab run at login. Then quit that instance of AltTab.

I'll close the ticket since it's not an issue with the app 👍

**Comment by shipotech** [comment]
Thank you so much!
