### ISSUE TITLE
Deselected "Hide apps with no open window", but still can't select Finder with no Finder window

### ISSUE THREAD

**Issue by snoblenet** [lwouis/alt-tab-macos#2850]
Great app, thanks.

**Describe the bug**

I have deselected "Hide apps with no open window", but I still can't see Finder in AltTab when Finder has no open windows.

**Steps to reproduce the bug**

1. Deselect "Hide apps with no open window" in AltTab preferences and save
2. Close all Finder windows
3. Focus an app other than Finder
4. Trigger AltTab
5. See that you cannot see the Finder

**Your environment**

* AltTab version: 6.61.0
* macOS version: 14.0
* Other relevant info:
  * M1 MacBook
  * Apple branded external keyboard and trackpad
  * LG monitor as primary display
  * laptop screen as secondary display
  * Universal Control enabled, with MacBook as primary and my personal MacBook Air as secondary
  * Recently uninstalled my paid-for copy of Which, in favour of AltTab, which is faster
  * Using Rectangle (not pro) for window management
  * My other active apps that have similar privileges to AltTab include:
    * Alfred
    * Paletro
    * KeyCue
    * KindaVim

**Comment by lwouis** [comment]
Please remove Finder from Prererences > Blacklist 👍

**Comment by snoblenet** [comment]
thanks -- i missed that
