### ISSUE TITLE
Window not brought to foreground, but focused on alt-tab (Webex)

### ISSUE THREAD

**Issue by davidweisscode** [lwouis/alt-tab-macos#2863]
**Describe the bug**

When alt-tabbing to a window, the window gets focused *but is not brought to the front*, so it remains in the background and is not visible. However, the app becomes active/focused (as I can see by the macOS menu bar). Then, I can bring the window to the foreground by clicking "Window" --> "Bring all to front", which is very cumbersome.

This has only been observed for the "Webex Meetings" app.

**Screenshots / video**

The screenshot shows that "Webex Meetings" window is focused, but not visible in the foreground. It is covered by e.g. Outlook.
<img width="370" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/8447009/2ab685ff-1279-4dbc-806d-3157b17b9b46">

The screen recording shows the active "Webex Meetings" window, then alt-tabbing to a window which will cover it, then alt-tabbing back to the window, which is then focused, but stays in the background.
https://github.com/lwouis/alt-tab-macos/assets/8447009/591b7a5a-23bb-4dd0-befe-51a006b27f88

**Steps to reproduce the bug**

1. Have a window open from any app, which will later cover the same screen area as "Webex Meetings" (see step 2.)
2. Have a "Webex Meetings" window open (covering the app from step 1.)
3. Alt-tab to the window from step 1. (that window should be focused and in the foreground as expected)
4. Alt-tab to the "Webex Meetings" window
5. See issue, the "Webex Meetings" window is focused *but not brought to the front*

**Your environment**

* AltTab version: 6.61.0
* macOS version: Ventura 13.5.1
* Other relevant info:
  * I also use Karabiner-Elements 14.12.0 and the Rectangle extension
  * I have only observed this with the "Webex Meetings" app. However, the same works for the "Webex" app.

**Comment by lwouis** [comment]
Hi,

There have been many reports/issues with Webex over the years.

Given that every other app behaves correctly, it makes sense to assume that the issue lies with Webex window management, and not with the way AltTab focuses windows, which is the same for every app.

This issue is most likely something Webex should fix. Could you please contact their customer support to let them know?

Thank you

**Comment by davidweisscode** [comment]
Hi @lwouis,
Thank you so much for both your blazing fast response, as well as your awesome project here.
It is a life saver and simply amazing!

Although, Im left with this issue, Im happy to get your answer and now know that this is known and not related to alt-tab-macos.

I already suspected that it is Webex related for two reasons:
- I only spot the issue with Webex
- The "Webex" app (for chats and 1on1 calls) opens another app for scheduled group videocalls. Then it is called "Webex Meetings", where I observe the issue. There is no issue with the normal "Webex" app.

If I hear anything back from Webex customer support, I will post here.

Thank you

**Comment by davidweisscode** [comment]
Hi @lwouis ,
You were right. The issue is on Webex Window Management side.
I contacted Webex customer support (without zero expectations) and got positively surprised :-)

They handled the case very smoothly, and I provided a screen recording of the issue.
They even downloaded AltTabMacOs and reproduced the issue on their side.

They are rolling out a new, converged platform architecture ("Webex Suite") on which the issue no longer persists. I saw that everything works as expected there with AltTabMacOs with my own eyes in a video call when customer support invited me to a meeting hosted on the new platform.
Also, it is expected that "most organisations will be migrated within the following 2-3 months".

So with the old Webex version there are both "Webex" and "Webex Meetings", and the issue persists. You are on the old one if you can see this icon.
![image](https://github.com/lwouis/alt-tab-macos/assets/8447009/7e895e1a-059d-4ad2-902a-8ba068bdd486)

In the new Webex version everything (both chat and meetings) will happen inside the same application, and there is no issue with AltTabMacOs anymore.

Happy hacking
David

**Comment by lwouis** [comment]
Hi @davidweisscode,

This is great news!
Thank you very much for sharing with everyone 🙇 

Thank you
