### ISSUE TITLE
Dynamic/Realtime thumbnails

### ISSUE THREAD

**Issue by bogdan-manole** [lwouis/alt-tab-macos#2876]
**Is your feature suggestion related to a problem? Please describe.**

First I want to congratulate the creators of this tool, the best utility I installed in years on macOS (I use the keyboard a lot)

I often work in my code editor for a long period (full-screen/separate space) and play videos/podcasts in the background. 
For the moment, the thumbnails are a capture of the window at the moment of showing the apps (hitting alt-tab).
I think it will be awesome to have the real-time capture in those exposed thumbnails
In this way, people might use the tool also for just previewing from time to time what happens in certain windows, by hitting their shortcut and after a few seconds they would just hit the <esc> and return to their main work.

I know there is macOS Expose for that, but there are multiple reasons for not using that:
  - that involves using the mouse/trackpad
  - it makes you lose focus since it modifies the whole aspect of your focused window
  - alt-tab would be the main, fastest, and complete way to switch and watch/preview into the other windows  

**Describe the solution you'd like**

I realize that might involve a lot of work and might imply more demanding resources, but I think it would be awesome to have this feature 😄 

Bellow I just uploaded an example of how spaces are seen in macOS

https://github.com/lwouis/alt-tab-macos/assets/3176255/1f69195e-3bae-4840-ab9f-16f6e7210a68

**Comment by lwouis** [comment]
#122
