### ISSUE TITLE
Can alt-tab control whether to turn on transparency? Rather than relying on the system's transparent options

### ISSUE THREAD

**Issue by Allsochen** [lwouis/alt-tab-macos#2887]
When the transparency option is turned on, the open application window is black, and the alt-tab window preview turns black, making the window difficult to recognize.

here is close the system transparency option under the black application windows.
<img width="1686" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/5805484/bb423aa2-9289-495c-b200-33ff67077311">

here is open the system transparency option under the black application windows.
<img width="1609" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/5805484/6c14d430-b4e2-4411-a601-0f43cca6f2ab">

I don’t want to turn off the system’s transparency option, because the system’s transparency option makes the window more beautiful, and I just want to see the preview of the alt-tab window under the black application clearly, so the transparent line selection controlled by alt-tab will be more suitable, many Applications do this too, such as iTerm.

Another approach is to adjust the alt-tab preview black color when the background is black.

**Comment by lwouis** [comment]
Hi,

Here are 2 things you can do to help your issue:

* Use the Window theme in Preferences > Appearance. It has better contrast for the selected window
* ~Override the transparency option just for AltTab. You can execute a command in Terminal.app to change that setting only for AltTab. It's a standard macOS feature. You can use it to change the language of just 1 app for instance: `defaults write com.lwouis.alt-tab-macos reduceTransparency 1`~ It works for other preferences, but not for this one for some reason.

**Comment by Allsochen** [comment]
Can the transparency be adjusted appropriately? Makes the background easier to identify, like the system settings panel

**Comment by Allsochen** [comment]
Or can set the border background, just like the border background displayed by executing the "command+tab" shortcut key on macos?

**Comment by lwouis** [comment]
@Allsochen how do you set the border background of the native app switcher?

**Comment by Allsochen** [comment]
> @Allsochen how do you set the border background of the native app switcher?

There is not special settings, but the border background of native app switcher can be easily distinguished under each app.
