### ISSUE TITLE
Sometimes, the colored icons on top of each window are translucid

### ISSUE THREAD

**Issue by liuzongyang255** [lwouis/alt-tab-macos#2892]
**Describe the bug**

Sometimes the icons blend into the background

Sometimes icons have transparency

**Screenshots / video**

<img width="670" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/54257047/58e68d29-430d-4662-b339-60ef17a41c15">

<img width="463" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/54257047/9f20f29e-b350-457a-b4cb-e922a5bf1992">

**Steps to reproduce the bug**

 just use the shortcut keys to enter

**Your environment**

* AltTab version: 6.62.0
* macOS version:  14.1 Beta(23B5067a)
* Other relevant info: e.g. using external keyboard, multiple monitors, etc

**Comment by liuzongyang255** [comment]
sure!
<img width="254" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/54257047/34dc77bb-b593-4b6d-a6b7-30956f93a05a">


![Oct-19-2023 17-33-40](https://github.com/lwouis/alt-tab-macos/assets/54257047/26a39262-fbbc-4ba4-86d2-fb4b83a74a86)

**Comment by lwouis** [comment]
Hi,

I can't reproduce the issue. Looking at the code, I don't see how this could be a bug on AltTab's side.

Could it be because you're in a macOS beta? Have you witnessed this issue on the public release of macOS, in the past, or on another machine?

Thank you 🙇

**Comment by liuzongyang255** [comment]
Hello, the same applies to me after reinstalling the latest version of AltTab. I used to use Mac Ventura 13.5 without any issues, possibly due to issues with the beta version. Thank you for your patience in answering the questions

**Comment by Allsochen** [comment]
I reproduce the issue again at the dark theme.
<img width="715" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/5805484/7a5becf4-da1d-4549-b522-46c80abf9376">
<img width="485" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/5805484/dabc8fa6-16a5-4bc9-8357-498056fc8d4b">
<img width="1659" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/5805484/1455ed1d-0da5-406d-9f2a-dda09cc0ac41">
<img width="1649" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/5805484/90b3febd-1736-4bdd-ad1f-b68e3f386513">

**Comment by wc2184** [comment]
Having this issue too, as Allsochen said it is caused by Dark Mode in MacOS. Thank you Allsochen for the fixing this issue yourself, for now I will change my OS appearance to light mode until AltTab approves his PR. It's really annoying when I'm trying to close windows quickly and it is barely visible which buttons are which.

**Comment by Allsochen** [comment]
> Having this issue too, as Allsochen said it is caused by Dark Mode in MacOS. Thank you Allsochen for the fixing this issue yourself, for now I will change my OS appearance to light mode until AltTab approves his PR. It's really annoying when I'm trying to close windows quickly and it is barely visible which buttons are which.

You can temporarily use the Cmd+W shortcut or the middle mouse button to close the window.
