### ISSUE TITLE
Caps Lock shown as a active window in MacOS Sonoma

### ISSUE THREAD

**Issue by satyajeetking** [lwouis/alt-tab-macos#2898]
**Summary -**
If Caps Lock is on while we are typing in any document and we use AltTab then the Caps Lock is being shown as a window in MacOS Sonoma.

**Steps to replicate -**

1. Open one or two other applications.
2. Open TextEdit in MacOS Sonoma.
3. Hit the Caps Lock Key..
4. Use the Alt+Tab key mapped to the AltTab application.

**Expected -**
The Caps Lock should not be shown as an application.

**Actual -**
Caps Lock is being shown as an open application and with an empty window, making switching difficult.

Note - I gave example of TextEdit, but this happens with MS Powerpoint and MS Word also.

**Comment by lwouis** [comment]
#2849
