### ISSUE TITLE
Better contrast for active tab

### ISSUE THREAD

**Issue by Zerotask** [lwouis/alt-tab-macos#2909]
**Is your feature suggestion related to a problem? Please describe.**
If I navigate with Option + Tab, the active tab I'm focusing has a dark background, which is compared to the dark applications (I use dark mode) barely seen. In Windows you can see the active tab way better.

**Describe the solution you'd like**
For example add a white border, the same as you do, when you hover a tab with your mouse. This makes it more clear

**Comment by lwouis** [comment]
There have been many discussions around this. Please look for previous tickets

For now, i can advise to use the Windows 10 theme in Preferences > Appearance
