### ISSUE TITLE
Vim keybindings setting does not persist between upgrades

### ISSUE THREAD

**Issue by gnufied** [lwouis/alt-tab-macos#2919]
**Describe the bug**

I have noticed that whenever alt-tab is restarted because of upgrades etc, I have to open settings again and enable vim keybindings.

**Comment by lwouis** [comment]
Hi @gnufied,

I can't reproduce this. Does it reset when restarting AltTab manually?

Thank you 🙇

**Comment by gnufied** [comment]
It indeed seems to be reproducible for me, when I restart alt-tab manually.

**Comment by zhaoxuan** [comment]
Vim setting does not persist, When I restart it manually.

**Comment by lwouis** [comment]
Hi,
I found the root cause. I'll release an update which stops this issue soon 👍 
Thank you
