### ISSUE TITLE
Mail.app has an extra window showing in AltTab

### ISSUE THREAD

**Issue by mrc247-DE** [lwouis/alt-tab-macos#292]
Mail App appears twice after the last updates

<img width="1532" alt="image" src="https://user-images.githubusercontent.com/55986035/80962004-77453f00-8e0c-11ea-8d6c-a5520a1112e6.png">

but definitely only one window of the Mail app is open

When I quit the Mail app (cmd q) and restart, there is only one window. After a certain period of time, a second appears in alt-tab.

**Comment by lwouis** [comment]
Hi @mrc247-DE! Thanks for sharing this issue!

I couldn't reproduce locally. Could you please help me with steps to reproduce?

* You say it's about waiting. How long do you wait for it to happen?
* Also how come the windows have different titles? Is "Eingang" the German localization for "Inbox"?
* What happens if you focus the left window with AltTab? What about the right window?

**Comment by mrc247-DE** [comment]
_"You say it's about waiting. How long do you wait for it to happen?"_

I can't say exactly, this morning it was just one window. At lunchtime there were two. I will continue to watch this.


_"Also how come the windows have different titles? Is "Eingang" the German localization for "Inbox"? Which window is the correct one?"_

that with the different titles also surprised me. Yes, "Eingang" is the German translation for Inbox.
Inbox was the correct window.
Today the title of one window is "Inbox - GMX" and the other "Inbox - GMX 15.080 E-Mails ..."


_"What happens if you focus the left window with AltTab? What about the right window?"_

It doesn't matter which window I choose with alt-tab, the exact same thing happens, the mail app is focused. There is only one window in the Mail app.

**Comment by mrc247-DE** [comment]
even with the current version (3.22.6), the mail app still appears twice to me.

**Comment by lwouis** [comment]
@mrc247-DE Is it systematic? Could you share steps to reproduce?

**Comment by mrc247-DE** [comment]
it seems that the problem with the latest version of alt-tab is permanent.
I added the mail app to my user as a login object and it is currently the case that I see two windows immediately after starting the Mac.
I hope my English translated with google is understandable.

<img width="490" alt="image" src="https://user-images.githubusercontent.com/55986035/81684893-acc6d980-9457-11ea-8aa6-6e3b5c9b20b1.png">

**Comment by mrc247-DE** [comment]
what exactly does this new setting mean?

<img width="243" alt="image" src="https://user-images.githubusercontent.com/55986035/81685091-0b8c5300-9458-11ea-8e55-6929cabff730.png">

**Comment by lwouis** [comment]
> what exactly does this new setting mean?
> 
> <img alt="image" width="243" src="https://user-images.githubusercontent.com/55986035/81685091-0b8c5300-9458-11ea-8e55-6929cabff730.png">

Some apps use standards tabs, for example: Finder, Terminal. Some apps have non-standards tabs, for example: Chrome.

Now let's say you have a Finder window with 2 tabs on it. This new feature let's you chose between seeing that window as 1 window in AltTab (default), or see each tab as an individual window (if you check the box).

It let's you navigate tabs easily, if you prefer that flow

**Comment by lwouis** [comment]
> it seems that the problem with the latest version of alt-tab is permanent.
> I added the mail app to my user as a login object and it is currently the case that I see two windows immediately after starting the Mac.
> I hope my English translated with google is understandable.
> 
> <img alt="image" width="490" src="https://user-images.githubusercontent.com/55986035/81684893-acc6d980-9457-11ea-8aa6-6e3b5c9b20b1.png">

I was actually able to reproduce the issue! I can't reproduce it when launching Mail normally, but I can reproduce it at login, but having the same settings as on your screenshot.

**Comment by lwouis** [comment]
@mrc247-DE I just released a new version that should fix this issue. Could you please let me know if it's working correctly for you now?

**Comment by mrc247-DE** [comment]
Sorry about the late reply, I was on vacation last week. (at home but not on my Mac). You solved the problem, it did not reappear. Thanks for your quick support. :-)
