### ISSUE TITLE
Signal application not visible in AltTab

### ISSUE THREAD

**Issue by Punt13140** [lwouis/alt-tab-macos#2923]
Hello,

I don't know why but sometimes my application [Signal](https://signal.org/fr/download/) doesn't show up in AltTab, and sometimes it is visible.
I tried to update to the latest version and I have the same problem, and I could not find a reason why from time to time it appears.

If you want me to try something, let me know.

Thanks

**Comment by lwouis** [comment]
Hi,

I think you're facing the issue described in #1324. I assume you're using multiple Spaces, or fullscreening some apps?

Thank you

**Comment by Punt13140** [comment]
What do you mean by fullscreening apps ? By pressing the green tick on the left of the topbar to make it real fullscreen ? Or just double pressing the top bar so that my apps take the most space (which is also fullscreen but you know what I mean haha).

Because I'm just double pressing the top bar.
And I never use spaces.

**Comment by lwouis** [comment]
Hi @Punt13140,

I meant the green icon. When you click it, it fullscreens the window. Behind the scenes, that creates a Space for that window. The user may not think that they use Spaces, but if they use fullscreen windows, they use Spaces.

The other reason could be that Signal uses incorrectly implemented windows. That's very possible. Could you perhaps contact their customer service?

Thank you
