### ISSUE TITLE
The application “AltTab.app” can’t be opened.

### ISSUE THREAD

**Issue by amityweb** [lwouis/alt-tab-macos#2939]
**Describe the bug**

Download latest, unzip, double click to extract. Double click app and get a popup error:
The application “AltTab.app” can’t be opened.

**Your environment**

* AltTab version: AltTab-6.63.0.zip
* macOS version: Anoma 14.0
* Other relevant info: Macbook 13"

**Comment by lwouis** [comment]
Hi,

Could you please share a screenshot of the error message? A video would be even better

Thank you

**Comment by amityweb** [comment]
As I was filming it it all worked fine! 🤦

The only thing I have done since is restart my Macbook, so I guess something was up with it yesterday!

So nevermind and thanks for replying fast.
