### ISSUE TITLE
AltTab not invoked when active focus is on password field

### ISSUE THREAD

**Issue by DaVince** [lwouis/alt-tab-macos#294]
When a window is open and active on specifically a password field, the AltTab window switcher will not show up. AltTab works fine when focused on other widgets in the same window.

I have set up AltTab to use the Command key instead of Option. In this case, MacOS's default window switcher shows up instead.

The easiest way to test this is by attempting to connect to an unknown secured Wi-Fi network.

My guess is that this is blocked on the OS level, but maybe removing focus from the password field could make it work.

**Comment by lwouis** [comment]
Hi @DaVince! Thanks for the detailed feedback!

It turns out we have already dug into that behavior, and have decided to not workaround it for security reasons. I invite you to check out the bottom comments on the previous ticket #17

**Comment by DaVince** [comment]
Alright, that makes sense. I can live with it not working in this one uncommon situation. Better than implementing a security risk. :)
