### ISSUE TITLE
Group windows by Space

### ISSUE THREAD

**Issue by amityweb** [lwouis/alt-tab-macos#2942]
**Is your feature suggestion related to a problem? Please describe.**

I have used window switchers for years, they are a huge productivity boost. I've used several and just discovered AltTab. I wanted to try it because none of the others I found include something so crucial for the way I work...

I have multiple spaces and I use them for different kind of work. So as a web developer I would have for example my browser and code editor on one space, and maybe email and my task manager in another space. Think of them as "workspaces" that group the windows for the task I am undertaking at that time. 

When in a workspace (specific desktops/spaces), I want I CmdTab back and forth between only those windows in that group very frequently. I dont want other windows in that switching to avoid accidentally switching to the wrong ones. 

But when I do use the full list of all window switchers list either ALL windows in a list, or I can choose just the windows in that space. I have to setup different shortcodes to switch when I just want to switch between current space windows, then another shortcode to show all windows. The problem is, when I do show all windows its a long list and I often do not know which window I want when there are multiple windows open from the same app. The long list can add confusion and mistakes, I often switch to the wrong windows. 

Ideally it would be good to group windows somehow. Perhaps by Desktop/Space. 

Attached is a screenshot of another window switcher that shall remain nameless, so this is good, EXCEPT this is not the CmdTab window switcher, this is a side panel which shows on mouse over, and not by keyboard shortcuts. So this is no good. I would ideally like this side panel in the middle and open by the keyboard like a window switcher. And to hide empty Desktops. And have the current Desktop at the top, so you can just keep switching easily between your group, but the other windows are there when you want to switch. I hope you can see how this grouping of desktops is useful I hope. 

I also have 3 monitors, and I am trying using Stage Manager or not, so I can understand it may get complex for window switchers to group by different setups. The grouping in that panel does not quite work well when Stage Manager is off, as there are loads more Desktops then so windows wont group. 

**Describe the solution you'd like**

Grouping window by desktop/space. Basically its like having "workspaces" that have a few apps windows in each, and groups windows by the workspace. 

**Describe alternatives you've considered**

Multiple keyboard shortcuts. One to either show current "workspace" windows and another to then show all windows so you can switch to others. BUT I cant find a solution to group the All windows list. 

Thanks

![Screenshot_2023-10-30 12 25 30_vW3WfS](https://github.com/lwouis/alt-tab-macos/assets/1562777/27bffe6b-1763-437c-88b0-fccdfb2592ec)

**Comment by lwouis** [comment]
Hi,

We have #337 already for the general idea, I believe. For a short-term workaround, I can suggest that you create 2 shortcuts in Preferences > Controls: Shortcut 1 will switch between windows of **all Spaces**, and Shortcut 2 will switch between all windows of the **active Space**.

Thank you

**Comment by amityweb** [comment]
Thank you. I do that now but use a different app at the moment.
