### ISSUE TITLE
Can't work in VMware

### ISSUE THREAD

**Issue by dengshenkk** [lwouis/alt-tab-macos#2947]
**Describe the bug**

A clear and concise description of what the bug is. What happened, and what you think should have happened.

when I entry the vmware(win10&fullscreen), press command + tab then trigger windows window preview, it's should be trigger altTab.

**Screenshots / video**

Add screenshots to help explain your problem. You can also record your screen to show the bug in action. That is *really* helpful!
no, only windows desktop picture
**Steps to reproduce the bug**

1. Go to vmware and fullscreen
2. Click command + tab

**Your environment**

* AltTab version: 6.64.0
* macOS version: 11.6.6 (20G624)
* Other relevant info: e.g. using external keyboard, multiple monitors, etc

**Comment by lwouis** [comment]
Hi,

by default, VMWare is blacklisted so that you can use Windows alt+tab in it. You can change that in Preferences > Blacklists 👍
