### ISSUE TITLE
Notify about updates less periodically

### ISSUE THREAD

**Issue by DaVince** [lwouis/alt-tab-macos#295]
Regular updates are great! But at some point I got several updates on a single day. I would like to request for updates (especially on the patch level) to be checked less often, like once a week.

Of course, when there is a new version available, this should still be reflected in the Updates tab and if someone wants to update sooner, they should be able to. But an actual notification should only be shown once, after a certain amount of days has passed.

There are, of course, alternative solutions, like collecting a certain amount of code changes across several days before releasing. But this would mean that testing can only happen after a certain point, so in this case a beta-release update channel would have to be considered. That might be a little much when the above strategy works just fine. 🙂

**Comment by lwouis** [comment]
Hey @DaVince! Thanks for sharing this feedback!

You make a valid point, and others have voiced a concern for frequent updates as well.

One way i see to deal with this is perhaps to add a dropdown on the existing UI. The second radio button would indicate: "Check updates [every day/week/month]"

The default being weekly seems more reasonable for the average user i imagine.

Should be pretty easily to add as all APIs already exist in the library we use for updates (i.e. Sparkle).

**Comment by lwouis** [comment]
Actually the UI is more complex than I thought. Also I wonder how many users care to be able to set the schedule to daily/week/monthly vs the added UI complexity of making it possible to customize that.

For the time being, I'll simply change the schedule from daily to weekly without any UI change. If more people want to be able to customize the frequency, then we may go further.

**Comment by mfn** [comment]
I think that's good call, as long as I can get my daily AltTab fix and manually check for updates ;) Thanks!
