### ISSUE TITLE
Possibility to display application title under the application icon

### ISSUE THREAD

**Issue by grassokvp** [lwouis/alt-tab-macos#2950]
Hi!
Could you please add possibility to display application title under the application icon?
Screenshot as example.
Thanks!
<img width="442" alt="Screenshot 2023-11-02 at 21 53 43" src="https://github.com/lwouis/alt-tab-macos/assets/26289252/96df7997-5bb6-475e-87a6-36a453dbc89b">

**Comment by lwouis** [comment]
#351
