### ISSUE TITLE
Duplicate windows while switching input language in Sonoma 14.1

### ISSUE THREAD

**Issue by wasichris** [lwouis/alt-tab-macos#2956]
**Describe the bug**

Duplicate windows while switching input language in Sonoma 14.1

**Screenshots / video**

![image](https://github.com/lwouis/alt-tab-macos/assets/12275870/1628a0ac-2b02-4620-b880-d67ed8225624)

**Steps to reproduce the bug**

1. Switch input language and input source popup
2. Trigger alt-tab-macos right away
3. See the duplicate windows 
4. The 2 duplicate windows are actually positioned next to each other and not able to switch to the next window as I need

**Your environment**

* AltTab version: 6.64.0
* macOS version: Sonoma 14.1

**Comment by lwouis** [comment]
This is a macOS bug that we can't do anything about. Please report it to Apple customer care.

thank you

**Comment by wasichris** [comment]
Thank you for your response. I found some interesting scenarios to share with you for reference, and it appears to be related to the app startup time. I hope this information is helpful to you as well.

Scenario 1:

1. Open the Sublime app.
2. Open the AltTab app.
3. Switch the input language in Sublime and immediately trigger AltTab.
4. There are no duplicate windows.

Scenario 2:

1. Open the AltTab app.
2. Open the Sublime app.
3. Switch the input language in Sublime and trigger AltTab right away.
4. Duplicate windows appear.
