### ISSUE TITLE
Treating browser tabs as windows

### ISSUE THREAD

**Issue by craigmartell** [lwouis/alt-tab-macos#2957]
It would be great if browser tabs could be treated as windows - just like the way finder tabs are treated as windows when "Show standard tabs as windows" is checked.  If this is suppose to be the case already, then there is a bug using 6.64.0 on Sonoma.  

Thanks for an AMAZING project.   If there is a way for me to donate money, I would be happy to.

**Comment by craigmartell** [comment]
Or, instead of treating it like a window, at least allowing me to alt-tab between tabs.  Often I need to quickly go back and forth between two tabs in my workflow.  Work around is to move the tabs to windows.  But being able to go back and forth like Witch (from ManyTricks) would be really cool.

**Comment by lwouis** [comment]
Hi,

Web browsers use custom tabs. We can't handle them. We can't screenshot them for instance. It's technically not possible. This is why the preference says "Show **standard** tabs as windows". It only works if the app uses standard tabs. We can't show any custom drawn UI elements that looks like a tab. Unfortunately all major web browser today use non-standard tabs, Safari included.

Thank you
