### ISSUE TITLE
Command Tab Shortcut makes the Alt Tab Window previews stutter. 

### ISSUE THREAD

**Issue by codeRSH** [lwouis/alt-tab-macos#2969]
**Describe the bug**

I have sent command tab as the shortcut to use AltTab App. Pressing command tab sometimes acts slow and sometimes stutters. I suspect it has started happening since I updated to Sonoma 14.1 (From Sonoma 14). 

Please note that this works fine with alt-tab (original) shortcut key. 

**Screenshots / video**

https://github.com/lwouis/alt-tab-macos/assets/4953198/d007fe40-acd8-4f9b-bf71-b7b0b409380c

Please See screencast (stuttering can be seen from about 10 second onwards). 

**Steps to reproduce the bug**

1. Set Command Tab as the Shortcut on Alt Tab Preference page. 
2. Open a bunch of apps/windows and use cmd-tab shortcut. 
3. Pressing Command-tab a bunch of times will result it in a sluggish behaviour  and it also stutters sometimes. 

**Your environment**

* AltTab version: 6.64.0
* macOS version: 14.1

**Comment by lwouis** [comment]
Hi,

I can't reproduce this issue.

It looks like:

* You could have multiple instances of AltTab running. I don't see the icon(s) in your menubar, so it's hard to tell
* You could be having another piece of software messing with key presses (e.g. BTT, different language, keyboard driver/pilot)
* You could be having an external keyboard interfering

Thank you

**Comment by codeRSH** [comment]
Hi lwouis, 

Thanks for the response. The issue occurs without external keyboard as well. 

However, I did find couple of instances of Alt Tab showing in Activity Monitor. I killed one of them and it seems to be working fine for now. I will continue to monitor the behaviour and get back if the issue returns (with only single instance showing in Activity Monitor). 

Thanks for the help!
