### ISSUE TITLE
Support for PureRef app

### ISSUE THREAD

**Issue by chriscrofty** [lwouis/alt-tab-macos#2975]
**Is your feature suggestion related to a problem? Please describe.**
The window for PureRef does not appear in AltTab's windows select. 

**Describe the solution you'd like**
It would be great to be able to show the window somehow, may it is a different type of window since it allows you to overlay and passthrough ( see https://www.pureref.com/)

**Comment by lwouis** [comment]
Hi,

The issue most likely lies with PureRef. Could you please contact their customer support?

Thank you
