### ISSUE TITLE
Option to donate

### ISSUE THREAD

**Issue by adisidev** [lwouis/alt-tab-macos#2980]
Okay, I absolutely love this: the vim shortcuts, the customisability, just everything! I believe others feel the same, and I'd love to donate (even if it's a small amount, say 5-10$), because this is an app I would definitely pay for! Would you consider adding an option to donate?

I already tried looking through the website, your github profile, and your username on google, but could not find a way to donate!

**Comment by lwouis** [comment]
I'm glad you enjoy the app. There is no need for a donation.

Thank you~

**Comment by adisidev** [comment]
Thank you for considering. I just noticed the many previous posts of people asking for the same thing (which is honestly crazy, people love your work so much that they feel the need to pay for it!). Cheers!

**Comment by lwouis** [comment]
I've added Github Sponsorship 👍 
The link is at the top of the [github project page](https://github.com/lwouis/alt-tab-macos).

Thank you~
