### ISSUE TITLE
Refresh alttab when external monitor/s are dis/connected

### ISSUE THREAD

**Issue by EcksDy** [lwouis/alt-tab-macos#2983]
**Is your feature suggestion related to a problem? Please describe.**

These are the settings I'm using, note that I show windows only from the monitor where the alttab is shown. 
![image](https://github.com/lwouis/alt-tab-macos/assets/994443/e13fe606-1aea-4797-82d8-2540ebbc7706)

Currently I have to close and reopen alttab to show the actual windows on the monitor when I connect/disconnect external monitors. I actually have it on an automator script that I run when that happens.

**Describe the solution you'd like**
I want alttab to detect any monitor dis/connection and make sure the correct windows are shown.

**Comment by lwouis** [comment]
Hi,

Could you please share a video showcasing the issue? I can't reproduce it.
I'm wondering if the issue you face could be #1324?

Thank you 🙇

**Comment by EcksDy** [comment]
Hey @lwouis , 
first of all thank you for the amazing software, alttab is beyond anything else there is out there. My mac experience would be unbearable without it 🙏 

I couldn't make a video, but I made screenshots and detailed reproduction steps:

My spaces are turned off.
My external monitor acts as the main monitor(will call it that from now on), and the builtin is secondary. So the menubar is on the external only.

1. Mac asleep, disconnected from anything.
2. Connect HDMI cable
3. Open up the lid, login
4. All windows are on the main monitor, these are the screenshots of mission control:
<img width="1662" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/994443/594831b8-8c1c-42db-aaf3-488996ff9c33">
<img width="1662" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/994443/4ded01e4-99cf-41b9-a704-24a33a382cc6">

5. Try to alttab, these are the screenshots of alttab from both screens:
<img width="1655" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/994443/5cd013b1-3a9c-49a0-b975-88a846d4be1b">
<img width="1655" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/994443/fea427b7-de38-4df7-8deb-41876b59244d">

6. Disconnect HDMI, and all windows gather to the builtin screen(on mission control and alttab)
7. Reconnect HDMI, windows return to their places(I have DisplayMaid configured), and alttab also picks up on the changes. 

To me it seems that the issue is when waking up from sleep when everything is connected.
When I had a docking station with 3 screens at my previous workplace this was very pronounced. Maybe there are some other cases, I'll try to monitor them.

In any case, I think that a double click on the menubar icon, or an entry in the icon context menu that will force the alttab to refresh - can be a nice addition :)

**Comment by lwouis** [comment]
Hi @EcksDy,

I can't reproduce your scenario. AltTab always shows what's on the screen correctly to me. Furthermore, on your step 4, you write "All windows are on the main monitor". In my case, when I open the macbook lid, and log in, windows are spread accross both monitors, as they were previously.

In my attempts, macOS always remembers where windows were. If I disconnect the external monitor, all windows go onto the builtin display. However, as soon as I reconnect the external monitor, windows which were previously there go back there.

I don't understand how you get to step 4. And on Step 7, you mention that reconnecting HDMI will have the "windows return to their places".

What version of macOS and AltTab are you using?

**Comment by spocke** [comment]
I have a similar problem but to me it happens when the computer goes to sleep. I have 2 external monitors connected to a M2 Mac Book Pro. The main screen is disabled though BetterDisplay. Every time the computer goes to sleep some of the windows no longer appear in the AltTab carousel when i start it up again. So I have to restart the the app, even made a script for that since it happens so often. I do not use fullscreen mode just regular zoomed windows.

Here are some version details: AltTab 6.72.0, Mac OS: 14.6.1  let me know if you need some more information. Thanks.
