### ISSUE TITLE
QQ not showing from time to time

### ISSUE THREAD

**Issue by KingfuChan** [lwouis/alt-tab-macos#2994]
**Describe the bug**

QQ (NT version) not showing in alttab dashboard randomly. It happens every few time per day and I have to restart alttab for it to function well. Double clicking a chat or opening QQ settings page is fine, i.e. sub-windows for the process is shown in alttab properly.

**Screenshots / video**

Not convenient to post here.

**Steps to reproduce the bug**

Happens randomly.

**Your environment**

* AltTab version: 6.64.0
* macOS version: macOS Sonoma 14.1.1
* Other relevant info: QQ-NT version 6.9.22-18394, downloadable at https://im.qq.com/macqq/index.shtml

**Comment by lwouis** [comment]
Hi,

Please see my answer here: https://github.com/lwouis/alt-tab-macos/issues/1560#issuecomment-1123795100

Thank you
