### ISSUE TITLE
Toggle Show/Hide Open Windows with Single Hotkey Combination

### ISSUE THREAD

**Issue by CrayzBrian** [lwouis/alt-tab-macos#2996]
I would really like to be able to use a single hotkey combination to toggle the Open Windows Viewer in addition to how it works currently. Unless I am mistaken, there is no workaround for this issue. So, please let me know if there is a terminal command or simple script I can use in the meantime. 

My use case involves using a hot corner, middle mouse button, dock app, and Alfred workflow to toggle hiding and showing the Open Windows Viewer without switching windows unless selected by mouse or arrow/enter inputs. 

 I would like to use Apple Shortcuts, Keyboard Maestro, Alfred, Better Touch Tool, and Stream Deck to execute this either through the hotkey or some other execution. Perhaps the easiest way to picture what I am trying to do would be to just replace Mission Control in a hot corner with AltTab.

**Comment by lwouis** [comment]
Hi,

It's not clear to me exactly what you want to achieve. However, i think it's probably possible simply by setting BTT and AltTab correctly. You can use a shortcut in AltTab that is 2 or 3 modifiers. Then in BTT you could rebind a hot corner to send the keys of these 2 or 3 modifiers. In AltTab in Controls, you can set the Open Windows Viewer to remain on screen after the modifier keys are released.

i hope with this advice you can realize your workflow.

thank you

**Comment by CrayzBrian** [comment]
Hi,

Thanks for helping me understand this.

I would really like to be able to use the same hotkey to call and then, dismiss the AltTab screen showing open applications. I would love for Control-Tab pressed once to show the window and then, for it to hide when Control-Tab is pressed again. I just want to alternate showing the window with each hotkey press.

Is there any way to do something like this? 

I'm open to any way it can be done like by a Terminal Command, a URL Handler, a Dock App execution, or some other Macro Key.

Currently, I can get it to open just fine using any of the five shortcuts you provide such as Control-Tab or Control-`. It is just that when I want to dismiss it, I have to use a separate hotkey like Esc or Control-Esc, for example. Once I have a hotkey toggling the running apps window, I could then bind it in BTT to a hot corner or the middle mouse button, for instance.  

Visually, I'm trying to achieve something like this with AltTab and BTT:

Tuck
https://www.irradiatedsoftware.com/tuck/

I even tried using Tuck on the window, but it can't see the window, of course.

Slidepad also works this way. 

Slidepad
https://slidepad.app

Thanks again for helping me realize my workflow.

**Comment by lwouis** [comment]
Hey @CrayzBrian,

I'm afraid I don't see a direct way to do this with AltTab. This UX is too far off the AltTab experience from Windows.

I think what you want to achieve may be doable with some scripting. In BTT for instance. You can probably map the shortcut to send the activation keys or the escape keys, alternating between those. That way, the first keypress will activate and the second keypress will escape, and repeat. It's not ideal as it can desync (e.g. you open AltTab with the mouse).

Thank you and good luck with this project 🙇
