### ISSUE TITLE
Some windows don't show in the list

### ISSUE THREAD

**Issue by gtfunes** [lwouis/alt-tab-macos#30]
Some apps (like Slack) seem to handle window titles differently. 

In `WindowManager.swift`'s `axWindows` function, windows get filtered by whether they have a title or not. Slack for example does have a title (passes the check in `Application.swift`'s `computeOpenWindows`) but it returns `nil` here. My guess is we should remove the title validation in `axWindows`.

**Comment by lwouis** [comment]
Unfortunately I did not document why I added this `hasTitle` filtering. You can be sure however that there was a reason. Basically `AXUIElementCopyAttributeValue` returns lots of UI elements that a normal person would not consider a window. I have these 2 workarounds to filter the non-windows elements: `hasTitle` and `isReasonablyTall`. Being workarounds, both of them have cases they fix and cases they break.

Ideally there would be a nicer way to identify windows that look like windows in the mind of users. I remember going through [every single attribute in AXAttributeConstants.h](https://developer.apple.com/documentation/applicationservices/axattributeconstants_h/miscellaneous_defines?language=objc) (more extensive doc in the actual file), and printing values locally to see if I could not use something like `kAXRoleAttribute` to identify windows, but I remember noticing that basically nobody plays the same game so different apps use different frameworks, and these attributes are very inconsistently qualified.

**Comment by lwouis** [comment]
This was fixed in f150b7e3dc5e423ec6795c2d98b049acc3308963. It is available in the new [1.4.4 release](https://github.com/lwouis/alt-tab-macos/releases/tag/v1.4.4)
