### ISSUE TITLE
macOS 14.1.1 (23B2082) does not get the application together correctly after a long sleep

### ISSUE THREAD

**Issue by XiaoDaiGua-Ray** [lwouis/alt-tab-macos#3003]
**Describe the bug**

macOS 14.1.1 (23B2082) does not get the application together correctly after a long sleep.

**Screenshots / video**

Due to the temporary and sudden discovery of the problem, no pictures or videos have been collected.

**Steps to reproduce the bug**

System: macOS 14.1.1 (23B2082)
Sleep time: about two hours
Double line steps:
1. Sleep the computer for two hours or more
2. Open as many apps as possible
3. After unlocking the computer, AltTab will not get some apps correctly

**Your environment**

* AltTab version: 6.64.0
* macOS version:  macOS 14.1.1 (23B2082)

**Comment by lwouis** [comment]
Hi,

Do you have multiple Spaces or fullscreen windows? I suspect the issue you face is #1324 

Thank you

**Comment by XiaoDaiGua-Ray** [comment]
I guess I don't have multiple windows set up. Because when I re-click the application alone, AltTab can be displayed correctly.

If there is a chance to reproduce it, I will take a screenshot and give feedback immediately.🌸

**Comment by XiaoDaiGua-Ray** [comment]
hi.
I seem to have repeated the problem today, AltTab has the problem I raised last time.

The activated application cannot be obtained correctly. At the same time, I'm pretty sure I didn't make any mistakes.

<img width="1561" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/51957438/47511ebb-6a6e-4d4b-be51-90639a8a3d20">
<img width="570" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/51957438/572525f8-e7be-4d1c-a5c3-101bf68ba39d">

**Comment by prastomat** [comment]
This happens to me every day. MacOS 14.2.1. 
After a sleep, the app doesn't work at all. Hitting ALT+TAB does nothing. I have to close the app from tray and then the dafault mac window switch works. When I start the app again, same thing, nothing is working. 
I have to restart Mac completely and it works after a fresh boot correctly again. 

I have Mac connected to the external monitor.

**Comment by lwouis** [comment]
Hey @XiaoDaiGua-Ray and @prastomat,

As I said above, I suspect you're facing https://github.com/lwouis/alt-tab-macos/issues/1324. This issue is a current blocker that we can do nothing about. There is no API for us to see windows which are other Spaces.

@prastomat I suspect that when you wake from sleep, because you have an external monitor, your windows are sent to that monitor which is on another Space. Thus you're facing https://github.com/lwouis/alt-tab-macos/issues/1324.

@XiaoDaiGua-Ray do you use multiple monitors, or simply multiple macOS Spaces?

Thank you

**Comment by XiaoDaiGua-Ray** [comment]
This is looking at the problem of [1324](https://github.com/lwouis/alt-tab-macos/issues/1324), and it seems so.

3q!
