### ISSUE TITLE
first alacritty window in a space is not listed.

### ISSUE THREAD

**Issue by penglei** [lwouis/alt-tab-macos#3009]
I open an Alacritty window by pressing a shortcut key that is bound to alacritty msg create-window. 
However, when I am in a space without any Alacritty windows and press the shortcut key to create a new window, 
the new window is not listed in AltTab.

**Your environment**

* AltTab version: 6.64.0
* macOS version: 13.4.1
* Other relevant info: e.g. using external keyboard, multiple monitors, etc

**Comment by lwouis** [comment]
I believe this is a symptom of #1324
