### ISSUE TITLE
Add option to explicitly set a particular screen to show the UI of alt-tab on

### ISSUE THREAD

**Issue by philipreichen** [lwouis/alt-tab-macos#3015]
**Is your feature suggestion related to a problem? Please describe.**

It's not a problem, just a feature suggestion.

**Describe the solution you'd like**

It would be great if there was an option in "Appearance" > "Show on" that would let the user lock a particular screen where the alt-tab UI would _always_ show, regardless of where the menu bar and the mouse are and regardless of which screen is active.

The reason might seem a bit petty: I use a MacBook Pro 2021 (the one with a notch) together with 2 external screens. I have the MacBook Pro off to my right on a stand and I have a big screen in front of me and a medium-sized one to my left in portrait mode.

I like to maximize my screen real estate and that's why I always have the menu bar _only_ show on my MacBook Pro because that's where the notch is anyways. I don't like to have the menu bar on my other screens (since they don't have a notch). However, what I do like to have is the alt-tab UI on my main screen in front of me.

So currently I'm stuck with two sub-optimal solutions. Either:

- have to place the menu bar on my main screen, in order to have alt-tab on the main screen (but losing some screen real estate because of the menu bar) or
- having to turn my head to the right at my small MacBook Pro screen every time I want to look at the alt-tab UI because I have "Show on:" set to `Screen including menu bar` (but not losing screen real estate on my main monitor because it doesn't have the menu bar)

Again, it might be a petty edge case, but I thought I'd mention it. 

P.S. Love the product, @lwouis! You have made my life as a Mac user so much better!

**Describe alternatives you've considered**
Currently no alternatives for my particular scenario, except the two sub-optimal setups mentioned above.

**Comment by lwouis** [comment]
This would be a bit too niche and complex regarding the preferences UI. I think a good alternative would be #535 👍
