### ISSUE TITLE
Mimic macos backtick behavior (reverse cycling while in app switcher + cycling through active app's windows otherwise)

### ISSUE THREAD

**Issue by YBPN** [lwouis/alt-tab-macos#3017]
I'd like a way to mimic the macos default backtick behavior:

- Pressing backtick while inside the macos built-in app switcher (while holding command) cycles in reverse order. The effect is identical to pressing command+shift+tab.
- Pressing command+backtick outside the app switcher works as usual -- cycling through the active app windows. (AltTab is superior because it includes fullscreen windows in the cycle.)

Mimicking this macos default behavior is currently impossible with AltTab because it's a conflict. It would be nice if the backtick key could function differently depending on context. 

I know AltTab's default for reverse cycling is command+shift, but I find the macos default shortcuts more ergonomic for my poor hands.

**Comment by lwouis** [comment]
Hi @YBPN,

You can rebind all shortcuts the way you want them, I believe. By default backtick is used in Shortcut 2. You can change that in Preferences > Controls. You can use Backtick to cycle backward.

Thank you 🙇

**Comment by YBPN** [comment]
> You can rebind all shortcuts the way you want them, I believe. By default backtick is used in Shortcut 2. You can change that in Preferences > Controls. You can use Backtick to cycle backward.

I already kinda addressed that by mentioning that it's impossible to mimic macos default because it's a conflict in AltTab. To be clear, it's impossible in AltTab to have two things **simultaneously**:

1. backtick to reverse cycle **while in the app switcher**
2. command+backtick to cycle through the active app's windows otherwise

**Comment by lwouis** [comment]
I'm sorry, I understand now, thank you.

Yes, this UX is not possible now. It's a bit too complex to allow, given that AltTab lets user rebind everything, and it's already quite complex. It would complexify the Preferences UI too much to add such advanced behavior. It's a bit too niche to warrant the added complexity. We are currently trying to remove complexity: #351 

Thank you
