### ISSUE TITLE
Bind windows together

### ISSUE THREAD

**Issue by xingyuXXX** [lwouis/alt-tab-macos#3036]
Hello deps.

When I'm working on a job, I often need to use multiple apps (windows) at the same time, and if those windows aren't topped, then I need to switch to them one by one in order to make them all topped. This is a tedious operation as I have to switch multiple windows in turn.

Is it possible to bind a number of windows together so that when I switch to a certain window, all the windows bound to it are topped?

Thx a lot.

**Comment by lwouis** [comment]
Hi @xingyuXXX,

I'm afraid AltTab is not the right tool for this.

I suggest using Stage Manager for that. If all the windows are from the same app, you could also use the built-in app switcher (command+tab) which brings all windows from the app to the forefront.

Thank you 🙇
