### ISSUE TITLE
Shows input status on macOS Sonoma

### ISSUE THREAD

**Issue by ReyReyy** [lwouis/alt-tab-macos#3045]
**Describe the bug**

When I switch the input method and use AltTab at the same time, it'll shows input method status box as one of the switchable window.

**Screenshots / video**

![截圖 2023-12-08 清晨5 12 24](https://github.com/lwouis/alt-tab-macos/assets/46741598/a34fe2ae-68ad-4e37-9398-74b508f0d475)

https://github.com/lwouis/alt-tab-macos/assets/46741598/3b3061fd-8102-4935-8ac3-67e492473aea

**Steps to reproduce the bug**

1. Open a Chat app (iMessage, Telegram or anything else).
2. Switch input method on typing box, it'll appear an input method status box.
3. Press Command+Tab after appearing the box immediately.
(If you do this and no bugs appear, reopen the Chat app and retry)

**Environment**

* AltTab version: 6.64.0
* macOS version: macOS Sonoma (14.1.2)
* Device: Macbook Air 2022
* Keyboard: built-in keyboard

**Comment by lwouis** [comment]
This is a known macOS bug. Nothing we can do on our side unfortunately
