### ISSUE TITLE
Maybe a modern app icon ?

### ISSUE THREAD

**Issue by VoxDai** [lwouis/alt-tab-macos#3054]
Hi! AltTab is great, but I couldn't help notice that the app icon is a little bit old and doesn't really fit in the macOS style.  Maybe change it to a modern designed icon 🤔 ? 

I've found some cool icons on [this website](https://macosicons.com/#/), and here is a  preview of them (BTW, this website also provides an icon template so one can draw an icon conviniently). I've already repalced the app icon on my own Mac, [here](https://support.apple.com/guide/mac-help/change-icons-for-files-or-folders-on-mac-mchlp2313/mac) is how to do it.

![Icon preview](https://github.com/lwouis/alt-tab-macos/assets/61178988/b46dbb33-ab78-409b-b326-04952aacbbfa)

**Comment by lwouis** [comment]
Hi @VoxDai,

An issue with updating the icon would be that we would either need to show the new icon on old systems, or keep both the new and the old, to match the different systems.

For now, we'll stick with the status-quo. We'll probably revisit this situation at some point.

Thank you for sharing the idea.

For people seeing this thread later, please upvote the OP if you'd like a new icon.

Thank you!

**Comment by oguzhanygi** [comment]
I think this app needs a new icon. I also think there is no need for two icons. Why not use a new one everywhere?
