### ISSUE TITLE
Is it possible to hide windows from the same app when cycling through apps ?

### ISSUE THREAD

**Issue by alexandredepape** [lwouis/alt-tab-macos#3059]
I have a shortcut dedicated to cycling between windows of a same app and one for cycling between apps, but the second one shows two windows if an app has two windows for example.

Help appreciated :)
<img width="580" alt="Screenshot 2023-12-13 at 00 57 59" src="https://github.com/lwouis/alt-tab-macos/assets/25705704/1c83eb24-a512-48dc-87aa-c0979615858f">
<img width="585" alt="Screenshot 2023-12-13 at 00 57 54" src="https://github.com/lwouis/alt-tab-macos/assets/25705704/03d6a6d7-9de1-43c0-b48d-fe09f287f30b">

**Comment by lwouis** [comment]
I think you need #337
