### ISSUE TITLE
Option to group by app when showing options from all apps

### ISSUE THREAD

**Issue by sirmspencer** [lwouis/alt-tab-macos#3070]
**Describe the solution you'd like**
The normal alt-tab behavior on mac shows only the app icon, and only one even if more windows are open.  The alt ` and default opt ` in the app cycles through the individual windows.  It would be good to have an option to match macs default on the alt tab.  Here is an example why.  If I switch from chrome to vs code, and then cycle through my 5 open vs code windows, opt tab requires me to scroll past all 5 vscode windows to get to chrome.  if I needed those recent vscode windows, id stick with opt `.

**Describe alternatives you've considered**
The only alternative is to use the lame mac alt tab and the cool alt-tab-macros for opt `.

**Comment by lwouis** [comment]
#337

**Comment by sirmspencer** [comment]
In retrospect what else is there to show than the icon like mac os.  The ungrouped atl-tab with window previews is also helpful if put in alphabetical order.  That seems good for now.

**Comment by sirmspencer** [comment]
Is there a way to replace the three finger swipe to mission control with one of shortcuts?  The alt-tab with windows sorted alphabetically is more useful than mission control which is basically random.

**Comment by lwouis** [comment]
#730
