### ISSUE TITLE
Show white outline border when a window is highlight for "macOS" theme

### ISSUE THREAD

**Issue by azhongzl** [lwouis/alt-tab-macos#3073]
**Is your feature suggestion related to a problem? Please describe.**
If configuring the theme to "macOS", it doesn't show the white outline border for highlight window. If the background is dark, it's difficult to find which window is highlight. "Windows 10" theme has this feature.

Theme settings:
<img width="589" alt="SCR-20231223-ktry" src="https://github.com/lwouis/alt-tab-macos/assets/22796369/267acc9e-2536-4bd2-a70b-ace81a656390">
 
When using theme "macOS", it's difficult to find which window is highlight:
<img width="1792" alt="SCR-20231223-kpvo" src="https://github.com/lwouis/alt-tab-macos/assets/22796369/4e098eb5-34b8-46bf-a077-b1ff033fe3c6">

When using theme "Windows 10", there is a white outline border so it's easy to find which window is highlight:
<img width="1792" alt="SCR-20231223-kqac" src="https://github.com/lwouis/alt-tab-macos/assets/22796369/cfa3c523-7e78-4f68-bf79-a144b7ef0362">

**Describe the solution you'd like**
Show a white outline border for theme "macOS" which is similar to the theme "Windows 10"

**Describe alternatives you've considered**
N/A

**Comment by lwouis** [comment]
This is a tricky topic which has been discussed here: #82
