### ISSUE TITLE
Focus back to current window when mouse leave

### ISSUE THREAD

**Issue by mayeths** [lwouis/alt-tab-macos#3074]
**Is your feature suggestion related to a problem? Please describe.**
I use both Windows and MacOS extensively for my everyday work and appreciate how productive AltTab is. However, my experience led me to believe there is one difference between AltTab and Windows. I just found out what it is: If we move the mouse in and out of AltTab's preview, AltTab will navigate to the "last window that the user hovers" when releasing alt-tab. On Windows, the focus will fall back to the current window, instead of the "last hover window".

The following two pictures are what I found on Windows 10:

When the user hovers over another window, the focus changes to it (Edge):
<img width="1312" alt="231226_202827_676" src="https://github.com/lwouis/alt-tab-macos/assets/37110574/0aff8d95-6480-489f-ad69-895130bd456e">

If the mouse pointer leaves, the focus fallbacks to the current window (Chrome):
<img width="1311" alt="231226_202859_486" src="https://github.com/lwouis/alt-tab-macos/assets/37110574/7d8e0aee-b1d7-4cb8-9fd8-93d84d0ed9d8">

**Describe the solution you'd like**
Maybe a drop-down list in AltTab's preferences can be helpful, allowing us to choose how AltTab should behave in such a scenario, e.g.,  "If no hovering: (1) do nothing; (2) switch to last hovered window".

**Comment by lwouis** [comment]
You can get that behavior by unchecking the mouse hover checkbox in Preferences > Controls

**Comment by mayeths** [comment]
Thanks, that's exactly what I need!
