### ISSUE TITLE
Shift is not treated as a modifier

### ISSUE THREAD

**Issue by EcksDy** [lwouis/alt-tab-macos#3085]
**Is your feature suggestion related to a problem? Please describe.**
`option+tab` moves windows selection forwards. Pressing `option+shift` moves selection backwards. 

**Describe the solution you'd like**
The behaviour on windows is that `alt+tab` moves forward, while `alt+shift+tab` moves backwards. Nothing happens until you hit `tab`. `alt` and `shift` are treated as modifiers and what actually sends the command is the press of the `tab`.

**Describe alternatives you've considered**
![image](https://github.com/lwouis/alt-tab-macos/assets/994443/f5a689c6-0667-4f4a-964a-2119b73c7667)
Under the highlighted area, add a line along the lines of:
```
Hold [option] and [shift] and press: [tab] to Select previous window
```
If this is set then unset the key from the list below:
<img width="545" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/994443/92a6c678-dfd0-4798-bca5-d81ec483d2d2">
... and vice versa, if the key in the list is set, then unset the new option.

**Comment by lwouis** [comment]
You can set `Select previous window` to `shift+tab` to achieve this 👍

**Comment by EcksDy** [comment]
I've been wrestling with this for 2 years, thank you! :)
