### ISSUE TITLE
Taskbar / dock replacement feature

### ISSUE THREAD

**Issue by mfmayer** [lwouis/alt-tab-macos#3102]
**Is your feature suggestion related to a problem? Please describe.**
Besides the alt-tab feature that I love and thanks for bringing this to mac, I'm also missing a taskbar with the same features. That allows me to show all my open windows next to each other and in a way that I can order them accordingly to my needs and that I'm always finding them at the same place.

**Describe the solution you'd like**
I would love to see a feature that allows me to show a taskbar/dock from alt-tab as a macos dock replacement. Alt-tab is already able to give me an overview of all open apps/windows. I would love to see the same features in my taskbar/dock.

**Describe alternatives you've considered**
All other taskbar apps out there don't reliably work in that aspect. Alt-tab is by far the best working tool that quickly helps me to switch to the window I'm looking for. So I believe providing this taskbar feature would be a really cool upgrade (at least to me ;-)).

**Comment by lwouis** [comment]
Please see https://github.com/lwouis/alt-tab-macos/issues/529
