### ISSUE TITLE
Consider not using Google Translate automatically on Release notes

### ISSUE THREAD

**Issue by bjoernahrens** [lwouis/alt-tab-macos#3120]
Whenever an update is available, the app shows this release notes view (which I guess is a webview of https://alt-tab-macos.netlify.app/changelog-bare).

I always get a bit confused when mid-reading the text changes from English to my native language (German).

Additionally, **the quality** of the translation **is horrible** and sometimes quite hilarious.
As Google Translate does not know the context, it tries its best, but fails to do it right in this software update context.

Let's check an example:
<img width="75%" alt="AltTab update" src="https://github.com/lwouis/alt-tab-macos/assets/47995029/c40b27fa-4e73-439b-8f05-7663b24bbe41">

#### “don't absorb key up events after summon” ➔ “Akzeptieren Sie nach der Beschwörung keine Key-Up-Ereignisse”
- "Don't absorb" becomes "Akzeptieren Sie": That literally means "You accept" in the imperative form as a demand for the reader (with the word for "you" explicitly written).
- "after summon" becomes "nach der Beschwörung": [Beschwörung](https://www.dict.cc/?s=Beschwörung) means "incantation" or as in "summoning a demon"

So this line literally translated back became: **After the incantation, please accept no key up events**

The same applies to the next line:
#### "stop vim keys preference disabling on launch" ➔ "Stoppen Sie die Deaktivierung der VIM-Tastenpräferenz beim Start"
This became: **"Please stop the deactivation of vim keys preferences on launch"**

Furthermore, the next header "Features" became "Merkmale". That word means features as in the characteristics of a person, but not software features.

#### In my opinion all those messed-up translations don't help the users.

Besides that, I'm also not quite sure on the legality (at least in the EU) of just calling an external service like that without the users explicit approval, but I guess that's debatable as I'm no law expert.

This was introduced in #333 / https://github.com/lwouis/alt-tab-macos/commit/1927f2c

**Comment by lwouis** [comment]
Hi,

This allows users to get release notes in their native language. It's not as high quality as what a professional translator would do, but we can't afford that. This project is volonteer work with no revenue. We have volonteers translate the app (e.g. Preferences UI), but we can't get release notes translated fast enough. It would block the releases for months.

I understand the translation is not perfect, but it's often understandable and gets the idea across. It may seem silly to you, but please keep in mind it helps people from other countries who can't speak English, using the app at all.

Regarding the legality, of course it's legal. Why would it not? Most apps you use call external web services to function. AltTab is extremely cautious about using the user's resources, or doing any networking without user permission. We show release notes to user who request auto-update. If you disable them, AltTab will do absolutely no networking.

Lastly, if you prefer English release notes, [you can switch the app to English](https://apple.stackexchange.com/a/95191). You don't need to switch the whole OS; just the app.

Do you see a better alternative than the status quo?

Thank you
