### ISSUE TITLE
Hide apps with no windows

### ISSUE THREAD

**Issue by realkosty** [lwouis/alt-tab-macos#3125]
Love the app but this one thing is driving me nuts.
![Screenshot_2024-01-22_at_2_19_35 PM](https://github.com/lwouis/alt-tab-macos/assets/490201/69f16dd3-1d5d-4c0b-a9b4-0b0a3c3d6bee)

After a while the number of these "zombie" apps grows and it takes longer to cycle through to the app I care about with Cmd+Tab

**Solution**
Another option in the menu to Hide apps with no windows.

**Comment by lwouis** [comment]
Please check the checkbox in Preferences > Appearance, and these will be hidden 👍
