### ISSUE TITLE
Preview on multiple screens

### ISSUE THREAD

**Issue by BioCla** [lwouis/alt-tab-macos#3134]
**Is your feature suggestion related to a problem? Please describe.**
I noticed there wasn't any option to enable/view previews of applications on the screens in which they reside

**Describe the solution you'd like**
 Have altTab create a preview of each application on the single screen  in which they reside if a particular box is ticked.
 In this way you can instantly tell in which screen the application you are searching for is in

**Comment by lwouis** [comment]
#535
