### ISSUE TITLE
Coloured boarders

### ISSUE THREAD

**Issue by morfien101** [lwouis/alt-tab-macos#3149]
When using the alt tab I often have many windows open of the same application. In my case vscode and a few terminals. The all look similar and I am left trying to read the text that describes the window or looking at the thumbnail to see if it the one I want.

It would be amazing if there was a way I could have a sticker or a coloured board on certain windows or priority applications to quickly reference the ones that I want. For an example, in chrome I use different profiles and the top bar is a different color for each profile. That way I can very quickly and without much detail required know which profile I am working with.
As a side note, this also makes it easy to find the windows in the alt tab display.

I have tried to make different application windows different colours but it requires that all the apps have this kind of behaviour in them.

**Comment by lwouis** [comment]
Hi,
Thank you for sharing this idea. It's been discussed in #337 already, so I suggest following discussions there 👍 
Thank you
