### ISSUE TITLE
The behavior of AltTab when using multiple monitors

### ISSUE THREAD

**Issue by jiangtann** [lwouis/alt-tab-macos#3155]
My situation:
- Macbook built-in monitor with two extra monitors
- Enable macOS setting: `Displays have separate Spaces`
- Use a mouse side button as opening AltTab shortcut

AltTab setting:
- `Controls`:
    - `Show windows from`: `All apps` `All space` `Screen showing AltTab`
    - `Then release`: `Do nothing`
    - `While open, press` `Q` `Cancel and hide`
    - `Also select windows using`: Enable `Mouse Hover`

- `Appearance`:
    - `Show on`: `Screen includeing mouse`

I usually place different applications on different monitors. For example, I want to switch to Chrome, so I click on my mouse side button to open AltTab on the minitor A. If I don't find the chrome on that screen, I will move my mouse to the minitor B and click on my mouse side button again.

My expectation is that AltTab on the minitor A closes and AltTab opens on the minitor B. In fact, however, it wil lead to the result that AltTab on the minitor A select the next window, and nothing happens on the monitor B. 

So my current workaround is:
1. Click on my mouse side button to open AltTab on the minitor A do not find Chrome 
2.  **<ins>press Q to cancel and hide AltTab</ins>** 
3.  move the cursor to the monitor B 
4.  Click on my mouse side button to open AltTab on the minitor B

To avoid step 2, I have two proposals:

1. When the cursor moves to another screen which has a seperate space, modify the behavior of AltTab shortcut (i.e. close AltTab on the old screen and open AltTab on the new screen).

2. Follow the behavior of `Mission Control`. When you open Mission Control, all minitors will change to bird's-eye view. So I want a AltTab preference setting `Appearance -> Show on`: `All screens`. If this option is enabled, AltTab will open on all screens and show different applications on different screens when AltTab shortcut is triggered.

**Comment by lwouis** [comment]
Hi,

The first proposal would be an optimization for your particular workflow. However, it would be surprising for most users. AltTab is expected to react to a second shortcut press by moving to the next window preview. AltTab is expected to be opened and closed manually. Either by releasing the keys, or by pressing the focus or close shortcuts. Here, a second invocation would close AltTab, then re-open it on the other screen. It's unexpected and inconsistent with normal use. Again, it would be optimizing your particular workflow. I do understand that.

I think the best solution lies with your second proposal, which is already tracked in #535. Closing this as duplicate

Thank you
