### ISSUE TITLE
Enable per-shortcut (1-5) toggle for "Hide apps with no open window"

### ISSUE THREAD

**Issue by sknudsen** [lwouis/alt-tab-macos#3156]
I have overridden Macos command+tab hotkey an AltTab control, which only shows active windows. However, now I cannot get to running applications without launching Activity Monitor. 

I would like to set up two separate hotkeys in AltTab. One which does as described above and one that shows apps without open windows. This would be implemented by moving the toggle for "Hide apps with no open window" from the Appearance tab in AltTab settings to individual Shortcut tabs. 

Alternatively, this could be resolved by remapping the default Macos command+tab hotkey to some other hotkey in the OS. However, that seems to not be possible in the OS directly. And using something like Karabiner Elements seems to just remap the AltTab hotkey action (I tried the suggestion described here: https://superuser.com/a/1546595).

**Comment by lwouis** [comment]
Hi,

I'm affraid too few people would like to have this setting per-shortcut. Most people don't need this level of detail. It's a trade-off between the few and the many, and I'm afraid I have to favor the experience of the many.

Sorry for not being able to proceed 🙇 

Thank you

**Comment by udiNur** [comment]
I'm also pretty much need it, there is a way to tack about how many wants it?

**Comment by lwouis** [comment]
Hi,

The app doesn't do telemetry/spying. The only data we have about feature requests is tickets here on github, and how people engage with them./

Thank you 🙇
