### ISSUE TITLE
Formatting options for space number

### ISSUE THREAD

**Issue by BAY-EJQMB** [lwouis/alt-tab-macos#3161]
With windows of the same application separated on different monitors, for example, it is a little more complicated to identify visually with the small space number and difficult to differentiate.

Some formatting options with colors and sizes to more easily indicate which space each item is in.
In the "Appearance" part we have more detailed settings for other items. But not for the small number of space.

I know that spaces can be created and it would be difficult to define the colors in advance. But the part about being able to increase the size would be interesting at first.

**Comment by lwouis** [comment]
Hi,

The size of Space labels already scales with the size of window title. I think it's enough to make them more visible if needed. Maybe you mean that the user could decide to have windows from certain Spaces have their title and Space number made bigger/smaller?

Regarding colors, we could color window by their Space, yes. We could also color them by their app, or other things.

All these ideas, and more, are already discussed in #337. I'll close this ticket to keep the conversation in one place 👍 

Thank you
