### ISSUE TITLE
Toggle between spaces of same application (similar to Ubuntu Alt + `)

### ISSUE THREAD

**Issue by vignesh99** [lwouis/alt-tab-macos#3163]
Hello I am new here. Is there a way I can toggle between multiple spaces of the same application using the app? Command + ` does not work for me, especially when using multiple Google Chrome spaces. I know I can just do Command + Tab and look at all the windows and pick the one I want to go. But it would be cool if I could just go to the other spaces of the same application using Command + apostrophe . 

I could not find an existing issue asking this when I checked briefly. Apologize if I am reposting something that is already asked/explained.

**Comment by vignesh99** [comment]
Also, is there a way to revert back to just showing various application icons that are open, like the default Mac? Because sometimes, deciding between too many windows being shown is confusing. Would like to know if the app has a setting to do that using a shortcut.

**Comment by lwouis** [comment]
Hi,

You can achieve some of what you explained by playing with the Preferences > Controls and Appearance.

You may also want to follow #337 

Thank you

**Comment by vignesh99** [comment]
I actually don't have pictures as suggested in #337. I don't have the `Group windows by` option in mine like below
![image](https://github.com/lwouis/alt-tab-macos/assets/29650155/7ef9819a-1794-479b-936d-097b94878481)

Mine looks like below. I installed via brew. Should I install the latest version from git in order to see the above version? Also, I could not find there how to toggle the same application using a single shortcut. Can you point me a link to that as well?
<img width="586" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/29650155/e708c2d5-90fc-465f-84f7-3bb70251fef8">

**Comment by vignesh99** [comment]
Got it, thanks @lwouis
