### ISSUE TITLE
New appearance options to get closer to the original macOS tab

### ISSUE THREAD

**Issue by Pierre-LHOSTE** [lwouis/alt-tab-macos#3166]
**Is your feature suggestion related to a problem? Please describe.**
I prefer the pure and simple design of macOS, but I'd like to keep the power and efficiency of AltTab.

**Describe the solution you'd like**
I'd like to modify the visuals more to look like the macOS tab.
To do this, I suggest adding two options:
- An checkbox option to display the title only when the frame is focused or hovered.
- An checkbox option to display the text at the bottom (or below the icon) rather than next to the icon.
- An checkbox option that defines the frame shape as square.

By adding these options and modifying those already available, such as icon size and hidden preview, we could return to the original design.

**Describe alternatives you've considered**
Otherwise, a new theme that allows you to defined it directly (like `classic macOS`)

**Comment by lwouis** [comment]
Hi,

For items 1 and 3, I'm afraid it would be too niche. For item 2, it may happen through #351. I suggest you follow this existing ticket 👍 

Thank you
