### ISSUE TITLE
Sync settings to a dot file

### ISSUE THREAD

**Issue by GabeKuslansky** [lwouis/alt-tab-macos#3176]
**Is your feature suggestion related to a problem? Please describe.**
I'd like to sync this project's settings with my other dotfiles so I can keep my settings backed up and synced across machines. The current storage implementation works great locally but is not portable to my knowledge.

**Describe the solution you'd like**
AltTab automatically syncs settings to a dotfile like .alttabrc or .alttab.cfg, and reads from it on startup by default if exists. As this is a new feature after an existing persistence implementation, the cfg should be created on startup if not present so the user doesn't have to modify a setting to get it to appear. Could be cool to be able to modify settings in the file, but that is out of scope for this. If it's easier to serialize the settings to a file, that is fine as long as it is read by AltTab on startup and always reflects the current settings as they change.

**Describe alternatives you've considered**
Haven't considered any alternatives. I believe this is the least opinionated way to allow a user to sync, as they have their choice of where to store that dotfile, and this works nicely with the traditional dotfile/git structure many use. This is understandably a potentially large undertaking that may not be in scope or alignment with the project's feature set. If this seems feasible, I'd be interested in helping build this at some point in the future.

Thank you again for your volunteer hard work. Not a day goes by it is unappreciated

**Comment by lwouis** [comment]
Hi,

AltTab uses the OS preferences system. This means that you can export/import its preferences with a CLI.

Please refer to this thread for concrete instructions: https://github.com/lwouis/alt-tab-macos/issues/1219#issuecomment-1908819091

This will allow you to get a file in your dotfile which you can persist. You can export manually, or automate it with something like cron for a daily export.

It works for any app which uses the standard OS preferences system 👍 

Thank you
