### ISSUE TITLE
Odd behaviour when switching between Blender and other applications

### ISSUE THREAD

**Issue by paraversal** [lwouis/alt-tab-macos#3198]
**Describe the bug**

When switching in between Blender and other windows, especially if it happens relatively rapidly, AltTab will sometimes either
1. not switch over (unless the mouse is moved while the alt-tab interface is open), or,
2. when switching _to_ Blender, will not focus correctly (some inputs will work, others won't), and the only way to re-engage properly is to switch to another window, click inside it, switch to Blender, and click inside the window.

**Screenshots / video**

https://github.com/lwouis/alt-tab-macos/assets/104731964/7651b654-5d0d-4f02-aec6-1e26454e0bbf

- behaviour 1. happens more often and more "reliably" than behaviour 2, so I only have a video of that

**Steps to reproduce the bug**
 
1. open Blender
2. switch to another app
4. repeat a couple times

**Your environment**

* AltTab version: 6.64.0
* macOS version: Sonoma 14.0 
* Other relevant info: happens on all types of displays, with all types of keyboards

**Comment by lwouis** [comment]
Hi,

I can't reproduce the issue on my machine.

Could you please share another video with the full screen recorded, and going slower with the switches?

Thank you 🙇‍♂️

**Comment by NayamAmarshe** [comment]
I'm having the same issue and it seems that it happens when the mouse is in the same position as Alt-Tab window. When the mouse and the window clash, it refuses to switch the applications and bugs out.

**Comment by lwouis** [comment]
Hi @NayamAmarshe,
Could you please share a video, similar to what I described above?
Thank you 🙇‍♂️

**Comment by NayamAmarshe** [comment]
> Hi @NayamAmarshe, Could you please share a video, similar to what I described above? Thank you 🙇‍♂️
Hi, here's a video:

https://github.com/lwouis/alt-tab-macos/assets/25067102/58085ea0-f2af-46ad-8b7a-1de239774944

**Comment by lwouis** [comment]
@NayamAmarshe I think from your video, you're seeing #3117. This issue is not related to the Blender issue in this thread.

**Comment by NayamAmarshe** [comment]
> @NayamAmarshe I think from your video, you're seeing #3117. This issue is not related to the Blender issue in this thread.

Ah ok, sorry for the confusion.

**Comment by paraversal** [comment]
Hey! Sorry for keeping you waiting for so long, I completely forgot about this issue for a while and was on a Blender hiatus.

After some more trying around, I think it may be a Blender issue after all, because the same unexpected behavior happens with the stock tab switcher too (I honestly didn't consider this when first opening the issue because using the stock macos tab switcher is something I don't even like _thinking_ about).

I also still cannot find a list of steps to reproduce either of the two bugs reliably, they seem to flicker on and off and different variations happen over time after switching back to Blender from another application. 

The behavior also seems to be affected, oddly, by how long ago the other window was last switched to (such that it is more likely a bug occurs the longer ago the window was last switched to) but I just cannot nail down a set of instructions that works every time.

My guess is that in some cases, only keyboard events or mouse events are read by Blender after acquiring focus ("behavior 2" from my original issue), and in some other situations, the application focusing signal (however that is implemented internally) isn't correctly received by Blender ("behaviour 1").

Since this doesn't seem to be an Alt-Tab specific bug after all, I think we can close this issue here. I'm not even sure this is a Blender-specific bug, or rather a my-machine-specific bug because one of the highest search results for a description of this behavior is this exact Github issue. Huh.

Thank you anyway for investigating, and thank you for maintaining this beautiful piece of software!

**Comment by lwouis** [comment]
Thank you for your message~
