### ISSUE TITLE
Hide Apps with No Open Windows

### ISSUE THREAD

**Issue by AlJohri** [lwouis/alt-tab-macos#3203]
**Is your feature suggestion related to a problem? Please describe.**
I would like to hide apps with no open windows.

**Describe the solution you'd like**
If I close a window with by clicking the red "X" button or by pressing CMD-W and there are no more windows open for an app, I don't want to see the app in the Alt-Tab list.

**Describe alternatives you've considered**
Alternative is to fully quit the app so it doesn't show in the Alt-Tab menu.

This is what I see right now:
![Screenshot 2024-02-25 at 5 17 08 PM](https://github.com/lwouis/alt-tab-macos/assets/2790092/8a1844ac-c261-4e0c-8e13-11f247ccace5)

And these are my settings:
![Screenshot 2024-02-25 at 5 18 15 PM](https://github.com/lwouis/alt-tab-macos/assets/2790092/f52ae8ae-4b85-4fc7-8df7-90268c6bdf73)

While I have hidden all minimized and hidden apps, and this works properly when using CMD-M or CMD-H I want it to also work when I use CMD-W.

In the screenshot above, Slack, Sublime, Parallels all have no open windows yet I see the icon in AltTab.

```
❯ yabai -m query --windows | jq -Mc '.[] | {app, "is-visible", "is-minimized", "is-hidden"}'
{"app":"iTerm2","is-visible":true,"is-minimized":false,"is-hidden":false}
{"app":"Preview","is-visible":false,"is-minimized":false,"is-hidden":false}
{"app":"iTerm2","is-visible":false,"is-minimized":false,"is-hidden":false}
{"app":"Code","is-visible":false,"is-minimized":false,"is-hidden":false}
{"app":"macOS VM","is-visible":false,"is-minimized":true,"is-hidden":false}
{"app":"Firefox","is-visible":false,"is-minimized":true,"is-hidden":false}
{"app":"Parallels Desktop","is-visible":false,"is-minimized":true,"is-hidden":false}
```

**Comment by AlJohri** [comment]
Thanks! I swear I knew this feature existed in the past but couldn't find it.

Perhaps it could be made shortcut-specific instead of global? I was expecting to find this setting under Shortcut 1 as I was customizing the output of that shortcut. Other similar settings for hiding minimized/hidden windows appear there.

**Comment by yyNoBug** [comment]
> Thanks! I swear I knew this feature existed in the past but couldn't find it.
> 
> Perhaps it could be made shortcut-specific instead of global? I was expecting to find this setting under Shortcut 1 as I was customizing the output of that shortcut. Other similar settings for hiding minimized/hidden windows appear there.

I also want this feature! Shortcut-specific (instead of global) hide apps features could be very useful.

**Comment by MaskyS** [comment]
Can confirm I similarly got confused- didn't occur to me to look under "appearance". Would be nice to have shortcut-specific option to hide apps with no open windows.

**Comment by davecore82** [comment]
I don't see these options anymore in 7.18.0. Were they removed? 

<img width="572" alt="Screenshot 2025-01-09 at 10 36 36 AM" src="https://github.com/user-attachments/assets/c109140e-81b0-41e7-807e-20591fcd47b4" />

**Comment by tom-hehir** [comment]
In case anyone is searching for this feature and stumbles across this thread, the feature has now moved to being shortcut-specific as suggested earlier in this thread. On version 10.5.0 you can find it at Controls --> (select the shortcut that you want to modify the behaviour of) --> Show minimized windows / Show hidden windows
