### ISSUE TITLE
Alt-Tab Does Not Display AutoCAD 2024

### ISSUE THREAD

**Issue by regiulien** [lwouis/alt-tab-macos#3219]
Environment:
Affected Application: AutoCAD 2024
Operating System: macOS 14.3.1

Description:
Alt-Tab fails to display AutoCAD 2024 in the application switcher. When I use the Alt-Tab shortcut, AutoCAD 2024 does not appear among the list of active applications, despite being open and in use.

Steps to Reproduce:

1. Open AutoCAD 2024 on macOS.
2. Use the Alt-Tab shortcut to switch between applications.
3. Observe that AutoCAD 2024 does not appear in the application switcher.

Expected Behavior:
AutoCAD 2024 should appear in the Alt-Tab application switcher when it is open and running.

Actual Behavior:
AutoCAD 2024 is not displayed in the Alt-Tab application switcher, making it difficult to switch to it using the shortcut.

Additional Information:
This issue seems to be specific to AutoCAD 2024, as other applications appear normally in the Alt-Tab switcher.

Video attached.

https://github.com/lwouis/alt-tab-macos/assets/162313450/274b79e0-a66d-4901-8771-cdc195d35bcc

**Comment by lwouis** [comment]
Please see https://github.com/lwouis/alt-tab-macos/issues/2809#issuecomment-1733345296

**Comment by lwouis** [comment]
The latest release adds a workaround for AutoCAD. Windows should show up now. Hopefully this workaround works until AutoCAD makes their actual fix 👍
