### ISSUE TITLE
Modified Shortcut Option

### ISSUE THREAD

**Issue by Jonlb21** [lwouis/alt-tab-macos#3244]
I wanted to reach out and see if it would be possible to add/modify Alt-Tab's shortcut. Right now, the app requires you to select a key to hold, and another to trigger the window. Would it be possible to add just a single key shortcut instead of two? 

For instance, I select Shift as my single hotkey and when I hold Shift down Alt-Tab window pops up instead of having to press an additional key to trigger the window. I know it's a nice to have not need to have but I wanted to ask. I appreciate all the hard work and the frequent improvements. 

<img width="578" alt="Screenshot 2024-03-15 at 6 07 39 PM" src="https://github.com/lwouis/alt-tab-macos/assets/161039460/53c58219-7c0a-4d1c-8c38-07e7d2557143">

**Comment by lwouis** [comment]
Hi,

This is too niche to be added as a feature. I'm also wondering how you would use the shift key, like when you want to uppercase text, or in many software as a modifier, if AltTab pops up every time.

You can achieve the behavior you describe by using another app to remap Shift to send AltTab shortcut (e.g. BTT, Karabiner, etc).

Thank you
