### ISSUE TITLE
Allow customizing the "Select Previous Window" key per shortcut

### ISSUE THREAD

**Issue by jchayat** [lwouis/alt-tab-macos#3255]
Let's say I have 2 shortcuts defined: Alt+Tab for switching all windows and Alt+\` for switching from current App.
I would like to have Alt+Shift+Tab and Alt+Shift+\` do the backwards switching ("Select Previous Window"). Currently I can configure one of those shortcuts for this action but not have them both (depending on which shortcut I'm currently using).

I would suggest moving the "Select Previous Window" option under the shortcut tabs to allow customization on a per shortcut basis.

**Comment by lwouis** [comment]
Hi,

This has been discussed in the past. It's a bit of a niche use-case. It would complexify things for 99% of users, to enable a better flow for 1% of power-users. Because of this, it will not be changed.

Sorry about this. Thank you 🙇‍♂️
