### ISSUE TITLE
Move Selected Application to Current Desktop Space

### ISSUE THREAD

**Issue by calism2** [lwouis/alt-tab-macos#3268]
**Is your feature suggestion related to a problem? Please describe.**
Just wanted to drop a huge thank you to all the awesome folks who worked on this amazing app!  Over the course of the past three months, I have been utilizing Alt-Tab extensively. With a dual-monitor configuration, I frequently engage multiple desktop spaces for both work-related tasks and personal use. However, I find it difficult to access frequently used applications such as WhatsApp, Telegram, Discord, and others without necessitating a change in the current desktop space.

**Describe the solution you'd like**
I have [forked](https://github.com/calism2/alt-tab-macos) your repository and devised a solution tailored to my specific needs. Admittedly, my understanding of the code's internals is limited. Essentially, the implemented solution identifies the selected application and orchestrates the relocation of the current desktop space while also ensuring that the application receives focus accordingly.

I obtain the process ID (PID) corresponding to the application, while others are managed by Yabai, a distinct window management tool.

```
    func move(completion: @escaping ( ()-> Void)){
        runShellCommand(command: "/opt/homebrew/bin/yabai -m query --windows | /opt/homebrew/bin/jq '.[] | select(.pid==\(runningApplication.processIdentifier)) | .id'") { output in
            if let output = output {
                let command = "/opt/homebrew/bin/yabai -m query --spaces | /opt/homebrew/bin/jq '.[] | select(.\"has-focus\"==true) | .index' | xargs -I{} /opt/homebrew/bin/yabai -m window \(output) --space {}"
                let replaced = command.replacingOccurrences(of: "\n", with: " ")
                debugPrint(replaced)
                self.runShellCommand(command: replaced){ result in
                    completion()
                }
            } else {
                print("Failed to execute command.")
            }
        }
        
    }
```

**Comment by lwouis** [comment]
Hi,

Moving windows across Spaces is outside of AltTab's scope. It is more tailored for window management solution like yabai indeed.

Thank you 🙇‍♂️
