### ISSUE TITLE
Why Alttab needs screen recording on macOS

### ISSUE THREAD

**Issue by DanVin001** [lwouis/alt-tab-macos#3270]
Hi.
Why AltTab needs access to screen recording on macOS? Isn't it a breech of security?
I'm using Sonoma, latest version.
Thank you for your answer.

**Comment by lwouis** [comment]
Hi,

This is explained when you open AltTab for the first time. Permissions are required for basic function of the app.

There are numerous tickets discussing this here. This open ticket may interest you: #1082.

Thank you
