### ISSUE TITLE
Hide apps without window for all apps by default

### ISSUE THREAD

**Issue by tgeng** [lwouis/alt-tab-macos#3283]
**Is your feature suggestion related to a problem? Please describe.**
When an app is running without any windows, atl-tab would show an entry with the app icon. I find this kinda useless and I have to manually configure individual apps to be hidden when they do not have a window open under "blacklists" tab. This is tedious and sometimes it's not easy to find the bundle ID if the app running is not directly under the application folder.

**Describe the solution you'd like**
Can we add an option to simply hide all apps that don't have any windows open? Possibly under the controls tab. Like add a `All apps with windows` option to "Show windows from".

**Describe alternatives you've considered**
N/A

**Comment by lwouis** [comment]
This option already exists in Appearance 👍

**Comment by jmsosso** [comment]
I agree with [tgeng](https://github.com/tgeng), I was almost uninstalling the app when I found this post. I think the option to hide app without open windows should be included with the ones at the top of each shortcut.

**Comment by jruaaa** [comment]
this option doesn't really function for me on 14.2.1, still grabs hidden windows.
