### ISSUE TITLE
Hard to tell apart the highlighted tile on dark backgrounds

### ISSUE THREAD

**Issue by patrickmao93** [lwouis/alt-tab-macos#3285]
**Is your feature suggestion related to a problem? Please describe.**
When using the "macOS" theme, if the current screen content is in dark mode, it is very hard to tell which tile is the highlighted tile. This is especially unusable for users who use dark modes in a lot of apps. (I suspect a big portion of programmers have this issue).

**Describe the solution you'd like**
Maybe increase the contrast between the selected tile and the background. Or allow further customization of the themes.

**Describe alternatives you've considered**
Switching to the windows theme which has very high-contrast borders for the selected tile. But it's quite a bummer it's not as visually pleasing because of the sharp corners.

**Comment by lwouis** [comment]
Please see https://github.com/lwouis/alt-tab-macos/issues/1901#issuecomment-1225971978
