### ISSUE TITLE
Sometimes AltTab loses track of apps and thinks there's only one

### ISSUE THREAD

**Issue by timkgh** [lwouis/alt-tab-macos#3287]
**Describe the bug**

Sometimes AltTab loses track of apps and thinks there's only one. E.g. I just ran into it, it thought iTerm was the only open app, but there were definitely many more (browsers, slack, etc.)

If I restart AltTab, it's fine again.

The setup is simple, just laptop screen, single desktop, no external monitor.

**Steps to reproduce the bug**

Hard to reproduce, it seems to be random 😢 but I ran into it a few times.

**Your environment**

* AltTab version: 6.68.0
* macOS version: 14.4.1

**Comment by lwouis** [comment]
Hi,

I was suspecting you were facing #1324, but you mentioned having only 1 Space.

Does this happen when AltTab launches, or at login, or does it happen after it's been launched for a while and previously was reporting things correctly? Also does it happen after sleep then wake or is it in the middle of a session?

Thank you

**Comment by timkgh** [comment]
It happens randomly after AltTab has been running for a while, it reports things correctly, then it gets into this state and only restarting AltTab fixes it. It doesn't happen often hence it's hard to reproduce. I do not put my laptop to sleep so I don't think it's related to that.

**Comment by lwouis** [comment]
It may be related to fullscreening those apps. When a window is fullscreen'ed, it creates a dedicated Space.

So for instance, if you fullscreen a window, then go to your other Space with the other non-fullscreen windows, then restart AltTab, it will not list the fullscreen window, because it's on another Space, which is the issue #1324 I mentioned above.

I'll close this ticket as a duplicate since it's most likely this issue at play here.

Thank you 🙇

**Comment by timkgh** [comment]
It's possible, but I rarely fullscreen apps. And it's kinda weird that all apps disappear from AltTab, except one. I certainly don't fullscreen all apps that I run.

**Comment by lwouis** [comment]
The opposite is probably happening then: you boot your laptop and it brings back previous windows, and sets you on a fullscreen one; the last you used last time. AltTab then doesn't see any window except that one, since the others are on another Space.
