### ISSUE TITLE
just downloaded for macOS apple silicon & its not working. is there a setting i need to enable or something to get it to work?

### ISSUE THREAD

**Issue by ComfortableMilk4454** [lwouis/alt-tab-macos#3291]
**Describe the bug**

A clear and concise description of what the bug is. What happened, and what you think should have happened.

should look like this:
<img width="1512" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/43555540/c80ef4d2-d484-405d-aed9-3cc30e2929f9">

instead looks like this:
<img width="1264" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/43555540/5f8cb3f2-1e4b-49fa-8105-fa37f900c797">

note that ive restarted my mac to no avail.

**Screenshots / video**

https://github.com/lwouis/alt-tab-macos/assets/43555540/0d3479f8-c670-4769-9130-f794e1257d5b

Add screenshots to help explain your problem. You can also record your screen to show the bug in action. That is *really* helpful!

**Steps to reproduce the bug**

1. Cmd + Tab

**Your environment**

* AltTab version: 6.68.0
* macOS version: 14.3
* Other relevant info: e.g. using external keyboard, multiple monitors, etc

**Comment by lwouis** [comment]
Hi,

The default shortcut is alt+tab, not command+tab. You can customize it in the preferences if you prefer command+tab to replace the default macOS switcher.

Does it work for you with the right shortcut pressed?

Thank you

**Comment by ComfortableMilk4454** [comment]
ah im sorry i didnt know that lol! i changed it to be triggered by cmd + tab. it does work with that. thanks for the help!

**Comment by ComfortableMilk4454** [comment]
while we're here, is there any way to hide the menu bar icon?

**Comment by lwouis** [comment]
Yes, please select the empty option in the Icon dropdown menu in the first tab of the preferences.

Thank you
