### ISSUE TITLE
vim key hl to switch window, but use k to kill 

### ISSUE THREAD

**Issue by intijk** [lwouis/alt-tab-macos#3292]
current setting has below things conflict
vim keys to choose
key 'k' to kill 

But I only use vim key 'h' and 'l' for cursor moving choose, not use k, it should allow me in this case to use k to kill window.

**Comment by lwouis** [comment]
Hi,

Vim keys are used for navigating thumbnails. I think you are asking that if there is a conflict with another shortcut, the other shortcut should happen. Today, the vim keys preference is a toggle. It's all or nothing. I'm afraid we will not make it more complex and fine-grained. The usage is already very niche.

Thank you 🙇
