### ISSUE TITLE
AltTab scriptable starts two times?

### ISSUE THREAD

**Issue by davidwagner343** [lwouis/alt-tab-macos#3294]
Is it correct that AltTab starts two times?
It also creates two icons in the bar where all the application icons are.
Here is also a screenshot:
<img width="495" alt="Screenshot 2024-04-14 at 16 26 05" src="https://github.com/lwouis/alt-tab-macos/assets/165799174/3df824fc-bc2a-4ba2-89d3-4fd374e57500">

**Comment by lwouis** [comment]
Hi @davidwagner343 ,

If you click on the (i) icon on the right of your screenshot, where does it lead you? I suspect you have AltTab installed in 2 different places in your machine.

Thank you

**Comment by davidwagner343** [comment]
its both the same file in the applications folder. I deleted it and installed it again but same result. I guess it saves some applications settings somewhere.

**Comment by lwouis** [comment]
This is what the login item looks like on my machine. It's surprising yours isn't like this.

<img width="468" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/106195/2c4e7dd0-0b40-4ce5-9b0f-907d6f935157">

Did you install from the website or homebrew? Which version of AltTab and macOS are you using?

Thank you

**Comment by davidwagner343** [comment]
about brew, not sure anymore if I did install one version with brew. but
its not listed in brew under my installed applications.
but what I did: I installed first the 'normal' Alttab version and then I
realized I needed the scriptable version to be able to use the DockAltTab.
Could it be that there are some files leftover from that? Do you know how
to clean Alttab completely from system?

Am So., 14. Apr. 2024 um 23:06 Uhr schrieb lwouis ***@***.***

**Comment by lwouis** [comment]
Hi,

The simplest solution is probably to simply click on the menubar icon then in the preferences, uncheck "Launch at login". Repeat for the second menubar icon.

Thank you

**Comment by davidwagner343** [comment]
yeah that seemed to be sufficient 👍

Am Di., 16. Apr. 2024 um 11:11 Uhr schrieb lwouis ***@***.***
