### ISSUE TITLE
Mouse Click on Window thumbnail to focus the window

### ISSUE THREAD

**Issue by Romasato** [lwouis/alt-tab-macos#3298]
Hello there,

Thank you for creating this nice app - could not live without it after switching from Windows to MacOS just last week :) 

I have one question about mouse use: does AltTab support mouse clicks on thumbnails to focus specific windows? 

Because it seemed it was working at one point: I was clicking on the desired window thumbnail to switch to it and window would focus. But now it does not work anymore... 

So I am not sure if mouse clicks are a thing at all in AltTab? If not, then maybe they could be implemented?

Thanks!

**Your environment**

* AltTab version: 6.68.0
* macOS version: Sonoma 14.4.1
* Other relevant info: same with Macbook Touchpad and external Razer Viper Ultimate mouse.

**Comment by lwouis** [comment]
Hi @Romasato,

Yes, clicking with the mouse on a thumbnail should focus that window. It's been possible from the start, and has not been changed. It seems you're having an issue, probably due to your setup?

What exactly happens when you click it? Could you please share a video of the situation?

Thank you 🙇‍♂️

**Comment by Romasato** [comment]
Hi @lwouis,

You were right! I was pretty sure mouse clicks worked at one point - and then stopped. 

So I went checking around as you've suggested killing other apps related to mouse/keyboard customization and voila - it was Easy Move+Resize app bound to _Command_ key for moving windows around. 

When I was triggering **AltTab** via _Command+Tab_ it was also entering _Command+MOUSE-MOVE_ mode in **Easy Move+Resize** app.

I'll just rebind Easy Move+Resize to ⌥ Option key - and hope that does overlap with some other keyboard shortcut. It is an absolute mine field regarding keyboard shortcuts given I also have Karabiner and PC-Style overrides... 🤷‍♂️

We can close the ticket - thank you.
