### ISSUE TITLE
Put minimized window to the end of list

### ISSUE THREAD

**Issue by anki-code** [lwouis/alt-tab-macos#3312]
Hi! First of all thank you for alt-tab app for mac! It helps me every day, every hour, every minute! One thing I have:

Expected behavior: if window was minimized it will stay at the end of the list because no intent to use it.

How it works now:

<details>

We have list of windows:

![untitled0](https://github.com/lwouis/alt-tab-macos/assets/1708680/6a6e63b5-4c01-443a-b1e0-765994384ac4)

After minimization Alt-Tab config we see it on the first place:

![untitled(2)](https://github.com/lwouis/alt-tab-macos/assets/1708680/62f4d3ed-eef5-4b44-8515-3ec784849e26)

But expected behavior is to have it on the last place and current Alt-Tab pair here Firefox and PC.

</details>

JFYI: In KDE there is a feature that allows to exclude the minimized windows from alt-tab entirely. In this case if you want to get window back you use clicking on app in dock.

Thanks!

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by lwouis** [comment]
Hi,

This feature is already available:
<img width="586" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/106195/06a10483-b63f-42da-be3b-ab164f06cf1b">

Thank you 🙇

**Comment by lwouis** [comment]
Yes, on the same preferences tab:
<img width="589" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/106195/3f862e3e-bc43-44ce-82cc-a0348698bcaa">

There are many filters and options to customize. Please explore the preferences to find everything you may need 👍
