### ISSUE TITLE
Alttab often has quit after waking up Macbook from sleep - just disappeared as a process 

### ISSUE THREAD

**Issue by mrvalossa** [lwouis/alt-tab-macos#3318]
**Describe the bug**

Without errors, when I wake up my Macbook M1 from sleep, the Alttab process has quit and disappeared from the process list. This happens often, but not always. In the mornings when I wake the machine up, it has very often quit itself.
I have an extra display connected to the laptop via HDMI, Samsung LU28R550 (https://www.samsung.com/au/monitors/high-resolution/uhd-monitor-28-inch-lu28r550uqexxy/).

**Steps to reproduce the bug**

1. Run alttab
2. Use it happily and enjoy its powerful features that add to your productivity
3. When going to your RL errands, put Macbook to sleep. 
4. Often, but not always, when you open the lid and log in -> Alttab has vanished, I suppose process has quit quietly without any crash reports on screen..

**Your environment**

* AltTab version: 6.68.0
* macOS version: 14.4.1 , Macbook M1, 14 inch, 2021
* Other relevant info: e.g. using external keyboard, multiple monitors, etc
- Macbook M1 itself
- Samsung external display
- Apple Magic keyboard, wireless
- MX Master 2S mouse, wireless

**Comment by CzBiX** [comment]
should be the same issue #3253

**Comment by lwouis** [comment]
Thank you @CzBiX. I've reopened the other ticket. It has lots of info. Let's close this one and focus efforts in the older one 👍
