### ISSUE TITLE
Freezing Screen

### ISSUE THREAD

**Issue by Heynewhere** [lwouis/alt-tab-macos#3327]
The bug occurs when attempting to open (click) multiple times in quick succession, causing the system to freeze for approximately 30 seconds. Ideally, the system should handle multiple screen openings seamlessly without freezing or experiencing significant delays.

This happens on lockdown browser app often. 

* AltTab version:  is 6.68.0 and perviously
* macOS version: 15-inch Macbook Air 2023 M2

I use option  ⌥ and tab ↹.

**Comment by kaessert** [comment]
Facing the same :/

**Comment by lwouis** [comment]
@kaessert could you please open a new issue and use the template to provide information such as a video of the issue and steps to reproduce?

Thank you

**Comment by kaessert** [comment]
@lwouis sorry, ignore my comment please. Was able to reproduce it without alt-tab later.
