### ISSUE TITLE
Cannot tab back to full-screened video (sonoma 14.4.1) (alttab 6.67.0) (exclusive to librewolf)

### ISSUE THREAD

**Issue by RobustMarker** [lwouis/alt-tab-macos#3330]
When alt-tabbing out of a fullscreened video it is hard to alt-tab back into a fullscreened video and you have to use cmd + arrow up to view the window again. ~~This is not exclusive to youtube it also happens in plex but only when you have fullscreened in the same desktop~~ This happens to any video / photo fullscreened in ~~firefox /~~ librewolf ~~(just more secure firefox)~~, does NOT happen in safari or firefox, dont know about chrome havent tested it. looks like it is exclusive to how librewolf handles fullscreen content. I will check back later for plex.

video example:
https://github.com/lwouis/alt-tab-macos/assets/74292007/cd1ca7c6-2f72-4491-9bce-3bed686dd243

photo example:
https://github.com/lwouis/alt-tab-macos/assets/74292007/61327dd9-e5c6-4b03-a843-dfc6c04c28fd

To reproduce:
1. Launch AltTab
2. Open a ~~youtube/plex video~~ photo or video in firefox and fullscreen it
3. Switch to a different tab / app
4. attempt to switch back to said full-screened video/photo

* AltTab version: 6.67.0
* macOS version: 1.14.1 
* Other relevant info: Thunderbolt dock into a 4k external monitor, M1 macbook pro with 8gb ram, external keyboard/mouse also.

**Comment by lwouis** [comment]
Hi,

It seems that the issue only hapens in librewolf. I suggest you contact their support since the issue is likely on their side.

Thank you 🙇
