### ISSUE TITLE
Possible to center the application UI

### ISSUE THREAD

**Issue by huyhoang8398** [lwouis/alt-tab-macos#3331]
**Is your feature suggestion related to a problem? Please describe.**

Is it possible to center the UI in the screen, for me i think it a bit high on top comparing to the default macOS altab

<img width="2048" alt="Screenshot 2024-04-30 at 22 38 26" src="https://github.com/lwouis/alt-tab-macos/assets/25379882/5576101c-a07f-40e7-a5b3-eda1eacb07ec">

**Comment by azhongzl** [comment]
+1, a bit high

**Comment by JohnnyFireOne** [comment]
+1000 for me will be awesome!

**Comment by alexaldearroyo** [comment]
Also talked [here](https://github.com/lwouis/alt-tab-macos/issues/585). The issue was created 4 years ago but it seems no developer is working on that right now.

**Comment by lwouis** [comment]
Duplicate of https://github.com/lwouis/alt-tab-macos/issues/585
