### ISSUE TITLE
Cant overwrite System Default Command+Tab

### ISSUE THREAD

**Issue by bdrogja** [lwouis/alt-tab-macos#3334]
When I try to rebind the shortcut to Command+Tab, it doesnt work.
The default system behaviour of Command+Tab kicks in. When I use the AltTab default (Option+Tab), it works fine.

Mac OS: Sonoma 14.4.1

<img width="700" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/13269125/79903edc-b10d-48b7-8be3-6088f8f3f620">

**Comment by lwouis** [comment]
Hi,

I can't reproduce this.

Could you please share a video where you set the preferences then press the shortcut. With a few back and forth with setting alt or command, to see the behavior clearly.

External keyboards or remapping software could be at play as well. It's best to test on the laptop internal keyboard, with no remapping software running.

Thank you

**Comment by bdrogja** [comment]
I found out, that KeyboardMaestro were running in the background.
So this was the reason for this behaviour. I disabled the related macros, now it is working fine.
Thanks @lwouis!
