### ISSUE TITLE
Ability to show only one tile per app for the "All Apps" configuraiton

### ISSUE THREAD

**Issue by LunaticoCR** [lwouis/alt-tab-macos#3335]
**Is your feature suggestion related to a problem? Please describe.**
Sort of,  the default window switcher on macOS only shows one tile per application, regardless of how many windows are opened for that application. I can't get used to the fact that alt-tab shows all windows of all apps. If I want to go to app x it will most likely land on the right window (last used), but if not then I can do cmd+` to switch to the right window. Having all windows there makes the alt-tab window switcher unnecessarily busy.

**Describe the solution you'd like**
A checkbox that's only usable when "Show widows from: All apps" is selected, the checkbox can be called "Show only one tile per app" or something along those lines.

**Describe alternatives you've considered**
An alternative solution would be to change the "Show windows from" dropdown to "Show tiles for" with the following options: all windows of all apps, all open apps, all windows of current app.

**Comment by lwouis** [comment]
#337
