### ISSUE TITLE
Filter Windows by Window name

### ISSUE THREAD

**Issue by dipsy** [lwouis/alt-tab-macos#3337]
My problem with Jump Desktop App
It s app for remote connections.
It has main window and remote connection windows:
![CleanShot 2024-05-03 at 18 34 22@2x](https://github.com/lwouis/alt-tab-macos/assets/1336665/c5cd60f7-1537-4aff-a1a0-f6f36d3e8e07)
But I want to exclude main window from alt-tab.
It has one app bundle id, and it s not a bug of jump desktop app. Is it possible?

**Comment by lwouis** [comment]
Hi,

Unfortunately, there is no way to exclude individual windows. You can exclude an app, but not a particular window.

Thank you

**Comment by dipsy** [comment]
It s technical restriction or not app related function?

**Comment by lwouis** [comment]
Both.

A window doesn't have an identity. You can close a window, reopen "the same" window. Their screenshots would be the same, but their ID would be different. In other words, a window is ephemeral. They don't last between reboots for example. So AltTab would need to match the window on some characteristic like name, size, position. It's ambiguous as you can easily have multiple windows with the same name, size, position.

In addition, this feature is niche. Very few people would use it, yet it would increase the app's scope, complexity, debug, weight, etc. It's not worth it to implement such nice feature, unfortunately.

Thank you
