### ISSUE TITLE
Rename "Cursor follow focus" option to mention mouse

### ISSUE THREAD

**Issue by singalen** [lwouis/alt-tab-macos#3348]
"Cursor" doesn't always mean "Mouse cursor". This ambiguity causes issues like #1443.

I too was unable to find the option when I was looking for a source of this behavior which I totally didn't want. Only finding that issue and double-checking helped.

Perhaps call it "Mouse follow focus"?

**Comment by lwouis** [comment]
Hi,

Mouse would be too narrow. The cursor is controlled by the mouse but also by the trackpad, or a finger, for example. Perhaps "pointer" would be less ambiguous? A quick Google search doesn't seem to show a consensus there.

I'll keep the status quo for now. If more people come here and upvote, I'll re-open this ticket and implement an improvement. I'm not sure if the issue exists beyond English, also.

Thank you 🙇
