### ISSUE TITLE
Closing a preview window shows two empty preview windows temporarily

### ISSUE THREAD

**Issue by lawand-dot-io** [lwouis/alt-tab-macos#3351]
**Describe the bug**

If I have one Preview window open, and I have alttab shown using the menubar option (so it stays visible) and I close the Preview window, two random Preview windows are displays while the window closure animation is there.

**Screenshots / video**

https://github.com/lwouis/alt-tab-macos/assets/132961914/b1367450-1671-42f7-bfe9-799cc8357470

**Steps to reproduce the bug**

1. Open a finder window which contains a pdf file
2. Open the pdf file (using Preview)
3. Show alttab using the menubar action "Show", so that it stays visible
4. Close the preview window (using a keyboard shortcut triggered by a custom mouse button, since closing the window using a mouse click on the red button would hide alttab)
5. The bug happens

**Your environment**

* AltTab version: 6.68.0
* macOS version: 14.3
* Other relevant info: I notice that the bug starts happening after https://github.com/lwouis/alt-tab-macos/commit/31b5a3df775602730f6fe24b91024aee4da7cb26

**Comment by lwouis** [comment]
Hi,

Thank you for reporting this issue. It seems to be a regression from 31b5a3df. It inadvertently made AltTab show non-standard windows from Preview, in an effort to show the bugged windows. In short, we show too many window types for Preview, at the moment.

I'll ship a fix in the next release 🚀 

Thank you 🙇
