### ISSUE TITLE
Shows closed windows

### ISSUE THREAD

**Issue by mwisnicki** [lwouis/alt-tab-macos#3353]
**Describe the bug**

Applications with no windows are listed even when they shouldn't.

**Screenshots / video**

https://github.com/lwouis/alt-tab-macos/assets/96032/aebfc956-8047-4032-a33c-7a16632e251e

**Steps to reproduce the bug**

1. Open Notes then close, keep app running
2. Set AltTab to hide minimized and hidden windows
3. Press Alt-Tab
4. Notes will be displayed at the end as application icon (no preview).

**Your environment**

* AltTab version: 6.69.0
* macOS version: 14.4.1 (23E224)
* Other relevant info: ext mouse, keyboard, screen, Maccy

**Comment by mwisnicki** [comment]
I'm guessing `hidden windows` is supposed to control that?

**Comment by lwouis** [comment]
Hi,

No, hidden windows are something else. It's when you hit `command+H` for instance. The app hides its windows. There are not closed, but hidden.

What you're seeing here is the app which is open, but has no window. All its windows have been closed; not hidden.

By default, AltTab shows windows, and apps with no window. If you want to **hide apps with no open window**, there is such a checkbox to check in Preferences > Appearance 👍 

Thank you

**Comment by mwisnicki** [comment]
Thanks, that worked. Seems a bit inconsistent to have almost all the visibility options on Control tab while that one setting in appearance.

**Comment by lwouis** [comment]
The options in Controls are per-shortcut, and the options in Appearance are the same for all shortcuts 👍
