### ISSUE TITLE
Annoying Caps Lock Icon Bug in VSCode - How to Fix It

### ISSUE THREAD

**Issue by dayas-kr-coder** [lwouis/alt-tab-macos#3356]
When I turn on Caps Lock on my keyboard while using VSCode, a separate window with a thumbnail of the Caps Lock icon appears. This is quite annoying. I have provided a screenshot of my macOS screen for reference. Please help me fix this bug.

By the way, your app is excellent!

![Screenshot 2024-05-15 at 3 41 01 PM](https://github.com/lwouis/alt-tab-macos/assets/149292309/2f2f525f-35be-413f-a989-a306b4587c8b)

**Comment by lwouis** [comment]
Hi,

This is a macOS bug. I think it was fixed in later updates of macOS. It's likely that you're on a previous version. Which version are you on? Could you please try updating?

Nothing AltTab can do about this. It reports this "window" because it exists. The system creates it.

Thank you
