### ISSUE TITLE
Arc Application Window Stops Displaying Randomly

### ISSUE THREAD

**Issue by FernandoHN99** [lwouis/alt-tab-macos#3362]
When starting the Alt Tab app with the Arc browser application, it works correctly initially. However, after some time, the Arc browser application window stops being displayed. To make it show again, it is necessary to restart Alt Tab, but the error reoccurs afterward.

Note: This only happens with Arc browser.

Steps:
Download the Arc application and use it
Initialize Alt Tab and use it normally

<img width="660" alt="SCR-20240517-buwc" src="https://github.com/lwouis/alt-tab-macos/assets/86134291/ec13275a-2ddb-46f5-941b-6f8bb87ac665">

* AltTab version: 6.69.0
* macOS version: 14.4.1

**Comment by lwouis** [comment]
Could it be that you're seeing #1324? Is Arc fullscreen at times, or on other Spaces?

**Comment by FernandoHN99** [comment]
No, despite Arc not being in full screen or in other workspaces, when I put the app in full screen and then return to normal view, the bug happens.

**Comment by lwouis** [comment]
> when I put the app in full screen 

Yes, you're seeing #1324 then

**Comment by Lurrobert** [comment]
Never put arc browser to full screen and it just doesnt show up.
