### ISSUE TITLE
Can't do next window with the assigned hotkey when do nothing on release is selected?

### ISSUE THREAD

**Issue by asgeirtj** [lwouis/alt-tab-macos#3363]
Is this intended behaviour?

**Comment by lwouis** [comment]
Hi,

Yes, it's intended. See the wording on the Controls tab:

<img width="538" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/106195/fd2e74d9-c600-4b26-b498-ff2982c046a0">

Notice how the last section is "while open".

Thank you
