### ISSUE TITLE
VS Code auto save on window change doesn't work

### ISSUE THREAD

**Issue by QumiQumi** [lwouis/alt-tab-macos#3367]
**VS Code auto save on window change doesn't work**

In vs code there is a setting that allows you to save the file when changing windows. With a standard window change, the save works correctly, but when using AltTab the file is not saved on Window change.

**Screenshots / video**
<img width="358" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/43902909/750b4b52-9c1d-4c43-812e-ee25e92127a2">

<img width="687" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/43902909/269386be-5e2d-43d0-b44a-a8f32a699d5c">

**Steps to reproduce the bug**

1. Go to 'Preferences -> Files: Auto Save -> On Window Change'
2. Add changes to any file
3. Alt tab to other window and back
4. File is still unsaved

**Your environment**

* VS Code version: 1.89.1
* AltTab version: 6.69.0
* macOS version: Sonoma 14.4.1

**Comment by lwouis** [comment]
Not much we can do on our side to fix this. See https://github.com/lwouis/alt-tab-macos/issues/1663#issuecomment-1196996219

i think VSCode may have a possible fix on their side. Could you please contact their support?

**Comment by QumiQumi** [comment]
VS Code can not do anything either 🙁
https://github.com/microsoft/vscode/issues/213062#issuecomment-2120913519
