### ISSUE TITLE
Imitate Windows mouse operation, clicking the mouse once will display the interface, clicking the mouse again will hide the interface.

### ISSUE THREAD

**Issue by xiaokentrl** [lwouis/alt-tab-macos#3372]
Imitate Windows mouse operation, clicking the mouse once will display the interface, clicking the mouse again will hide the interface.

**Comment by lwouis** [comment]
You can bind special clicks to the keyboard shortcut to achieve this. There is no plan to have the app itself trigger with the mouse. There are plans for trackpad activation, like on Windows, though.
