### ISSUE TITLE
Windows view hopping after system restart

### ISSUE THREAD

**Issue by gradypark86** [lwouis/alt-tab-macos#3374]
**Describe the bug**

After restarting the system or logging out and logging in, the windows switch view jumps when the cmd key is held.
Restarting alt-tab solves the issue. Or change key ⌘ to other keys.

**Screenshots / video**

[Add screenshots to help explain your problem. You can also record your screen to show the bug in action. That is *really* helpful!](https://github.com/lwouis/alt-tab-macos/assets/39909237/d0d8a8d6-032b-4361-a322-61d2c9798e95)

**Steps to reproduce the bug**

1. Restart OS or log out.
2. Log in.
3. Hold the ⌘ and press ⇥.

**Your environment**

* AltTab version: 6.69.0
* macOS version: 14.5
* Other relevant info: logi mx keys

**Comment by lwouis** [comment]
#633
