### ISSUE TITLE
Mark of input method will appear as a window

### ISSUE THREAD

**Issue by xthemailbox1** [lwouis/alt-tab-macos#3378]
Mark of input method will appear as a window
<img width="609" alt="Xnip2024-05-23_15-02-34" src="https://github.com/lwouis/alt-tab-macos/assets/170606577/23a84f24-5bba-41b8-9c2d-46aeab43cc71">

**Comment by lwouis** [comment]
Hi,

this is a macOS bug. Could you please update to the latest macOS version? It should solve the issue.

thank you
