### ISSUE TITLE
Make AltTab appear in a fixed display form at the bottom of the screen.

### ISSUE THREAD

**Issue by coder-virjay** [lwouis/alt-tab-macos#3395]
**Is your feature suggestion related to a problem? Please describe.**
For users who work with multiple spaces on macOS, the Dock is not very practical, as it displays too many applications simultaneously, resulting in very low efficiency when searching for applications. The AltTab feature has a very nice functionality where, when activated, it only shows the applications of the current space, significantly improving efficiency. However, pressing the key to activate AltTab itself also comes with a cost of usage.

**Describe the solution you'd like**
Could we make AltTab appear in a fixed form at the bottom of the screen to replace the Dock? There is no alternative application on the market that only shows the applications of the current space. Although this has been mentioned by someone a few years ago, I still want to bring it up again. Thank you.

**Comment by lwouis** [comment]
Hi,

Always-on "dock" or UI is not in scope for this app. It was [discussed in depth here in the past](https://github.com/lwouis/alt-tab-macos/issues/529). Please have a look at that conversation. Many other apps are mentionned. I think many of them do what you described.

Thank you 🙇
