### ISSUE TITLE
Mouse selection from thumbnails rather than needing to toggle through them all

### ISSUE THREAD

**Issue by adrianbj** [lwouis/alt-tab-macos#34]
It would be great if we could select an app/window by mousing over it, just like you can do with CMD+Tab by mousing over the app icon.

Thanks!

**Comment by lwouis** [comment]
Note that currently you can click with the mouse on a thumbnail to focus that window. Adding mouse hover seems useful. I will look into it

**Comment by adrianbj** [comment]
:) - I didn't even notice that clicking worked - that helps significantly, but yes, hovering to highlight the border of the thumbnail and select when releasing CTRL would be a great addition - thank you!

**Comment by lwouis** [comment]
I just released [1.9.0](https://github.com/lwouis/alt-tab-macos/releases/tag/v1.9.0) with this feature. Check it out! :)

**Comment by adrianbj** [comment]
This is great - thank you!

**Comment by lwouis** [comment]
**Update:** there was a regression in that release. Please [download the latest version instead](https://github.com/lwouis/alt-tab-macos/releases/latest). Sorry about that!
