### ISSUE TITLE
Lighter appearence of the switcher window/pop-up (Accessibility Feature/Setting)

### ISSUE THREAD

**Issue by Bravosierra0** [lwouis/alt-tab-macos#3402]
with the current material-style implementation it is hard to see, not really poping up the switcher window.

Please, consider to let change the Appearance of the switcher window/pop-up:
Adjustment or user-option to make the background a bit brighter...so that the effect is the same or similar to the standard macOS AppSwitcher?

might also be some kind of Accessibility-Feature. Would be great to have such an option like enhance contrast/increase brightness for those who have a visual impairment.

Thank you, Merci!

**Comment by lwouis** [comment]
Please see https://github.com/lwouis/alt-tab-macos/issues/82#issuecomment-669982304
