### ISSUE TITLE
Docker Desktop icon looks corrupted

### ISSUE THREAD

**Issue by acataluddi** [lwouis/alt-tab-macos#3405]
**Describe the bug**

Hi, for some reason, the Docker Desktop icon looks corrupted. This behavior is consistent to two different MacBooks that I'm using.

**Screenshots / video**

![Screenshot 2024-06-04 at 16 48 45](https://github.com/lwouis/alt-tab-macos/assets/8874358/f6bc9334-2b4d-423c-a582-71779598df67)

**Steps to reproduce the bug**

1. Install Docker Desktop
2. Open Docker Desktop
3. Trigger Alt-Tab and see the icon

**Your environment**

* AltTab version: 6.69.0
* macOS version: 14.5

**Comment by lwouis** [comment]
Please see https://github.com/lwouis/alt-tab-macos/issues/2050

**Comment by acataluddi** [comment]
Hi @lwouis,

Unfortunately the reboot has not solved the issue. I’ve been working for months on an Intel-based Mac and now on an Apple Silicon one, and the Docker Desktop icon has always looked broken. Isn’t strange this consistent problem just with Docker’s icon?

Thanks,
Adriano

**Comment by lwouis** [comment]
I imagine that the issue is a unique combination of particular bits in the Docker image binary data, and how the operating system handles it. There could be a defect in the image, or a bug in interpreting that data by the OS, or both.

It's all out of our hands of course. AltTab uses standard OS APIs to retrieve the icon, and display it.

**Comment by acataluddi** [comment]
Hi @lwouis,

I've just noticed that the Docker icon looks broken also in the Apple _Activity Monitor_ so definitively not a problem of Alt-Tab!

![Screenshot 2024-06-06 at 09 14 46](https://github.com/lwouis/alt-tab-macos/assets/8874358/53f7507c-e827-44c1-ab11-de6e849d9d91)

Kind regards,
Adriano C.

**Comment by lwouis** [comment]
That is conclusive evidence! Thank you @acataluddi for sharing 🙇‍♂️
