### ISSUE TITLE
Alt-tab sporadically doesn't open or switch windows.

### ISSUE THREAD

**Issue by johnnymatthews** [lwouis/alt-tab-macos#3406]
Alt-tab sporadically doesn't open or switch windows. If I encounter this, I generally have to keep rebooting my machine until it starts working again. It seems to happen most often after waking up from _sleep_, but this isn't consistent.

I've:

- Confirmed that it's running (I can see it in `htop`.
- Closed and re-opened the app.
- Reset the preferences and restarted the app.
- Reinstalled the app with `brew reinstall alt-tab`.
- Restarted my machine.
- Switched from using `CMD` + `tab` to `OPTION` + `tab`.
- Completely re-fomatted my Macbook back to factory settings (not just _reinstalling MacOS, but wiping the drive, and then install MacOS from fresh).

Still the app doesn't switch windows. If, however, I use spotlight to open the app _twice_ I can get to the preferences window. The app is running, it's just not switching windows or showing any indication that it can./

Sorry, this a super weird bug and I don't see any tips on how to troubleshoot the app. **Is there a way I can run the app from a terminal window and see any debug messages?**

**Your environment**

* AltTab version: Version 6.70.1
* macOS version: 14.4 (23E214)
* Other relevant info: No special hardware. I'm running Alfred 5.5, but I can't see how that would interfere with anything.

Again, sorry there isn't much else I can think to tell you. Running the app with debug messages would be most helpful, I think.

**Comment by lwouis** [comment]
Hi,

I don't think there should be anything unique about how the app is started. `open -n` is extremely close to double-clicking the app icon, as far as i know.

You mention that it "doesn't switch windows". You mean that the app is running, but nothing happens when you press the shortcut? What happens if you click on the icon in the top menubar, and click on `Show`? Does it show?

Thank you 🙇

**Comment by lwouis** [comment]
Hi,

What happens when you press "Show" with the mouse?

It's most likely that you have something interfering on your setup: external keyboard, keyboard remapping software (e.g. Karabineer, BTT, Logitech driver, etc), language software, accessibility software, etc.

Is that the case?

Thank you 🙇

**Comment by vsuharnikov** [comment]
It works again if you rebind keys in Controls > Shortcut N. By default I have `cmd`+`tab` to switch windows. I change `cmd` to `ctrl+shift+cmd` and then again to `cmd` to solve the described issue.

Also I use skhd and raycast, but there is no such binding.

AltTab version: 6.68.0
macOS version: 14.5 (23F79)

**Comment by johnnymatthews** [comment]
So, after reformatting my machine and installing everything again, it seems to be working fine. I haven't yet installed Alfred though, so I'm thinking that might have something to do with my problems. Anyway, I'm gonna close this for now since it seems that the issue likely isn't with AltTab.
