### ISSUE TITLE
mouse skipping

### ISSUE THREAD

**Issue by Gobaio** [lwouis/alt-tab-macos#3407]
**Describe the bug**

When switching between pages using AltTab, sometimes there will be a hint to capture the screen, and then the mouse will jump randomly. It's a very bad experience.

**environment**

* AltTab version: 6.70.1
* macOS version: 14.5
* Chip: Apple M1 Pro

**Comment by lwouis** [comment]
Hi,

I'm not sure to understand the behavior described clearly. Could you please share a video of the issue?

Thank you 🙇

**Comment by Gobaio** [comment]
Why do I capture the screen every time I switch? The mouse flutters when you capture the screen.

**Comment by Gobaio** [comment]
<img width="720" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/35323039/0ae9e923-a367-458b-8910-faebb9fb2e2f">

After switching the window, this capture screen icon will appear, and the mouse will drift with the capture of the screen.
This issue did not occur before version 14 of MAC OS, but it did occur after version 14.

**Comment by lwouis** [comment]
Hi,

> Why do I capture the screen every time I switch?

Please see #108. It will explain in great details why the app needs permissions to show you thumbnails and window titles.

Regarding the mouse drifting, could you please share a video to help understand the exact behavior on display?

Thank you 🙇

**Comment by Gobaio** [comment]
https://github.com/lwouis/alt-tab-macos/assets/35323039/7f203fa7-d7ff-46e7-8d1e-c413bbcc539c

**Comment by Gobaio** [comment]
<img width="644" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/35323039/7ab11d4a-3955-4c9b-abb8-e7c8d8d27a9a">

When I switch the window, there will be an icon to capture the screen. When this icon appears, it will appear that the mouse has not moved, but the menu in the upper right corner will be opened automatically, and sometimes the right desk scheduling will also be clicked, it will feel as if the mouse has automatically clicked the leftmost area of the screen. Take another look at what happens in the video. I didn't connect an external keyboard or launch any keyboard control apps

**Comment by lwouis** [comment]
Hi,

Is this still happening to anyone, with the latest versions? Perhaps we can close this ticket otherwise.

Thank you 🙇

**Comment by Gobaio** [comment]
Can be closed, this is another application bug
