### ISSUE TITLE
Fresh install v.6.70.0 - crash when activating All Apps shortcut

### ISSUE THREAD

**Issue by alexjustdoit** [lwouis/alt-tab-macos#3409]
**Describe the bug**

Fresh install, default settings - crashes when triggering All apps shortcut. Tried changing the Hold keybinding, still crashes. If setting "Show windows from: active app" I can trigger the shortcut without a crash. Crashes immediately upon key binding combination being pressed, the switcher window doesn't show up.

Crash reports are on - you should have several from 6/6/24, roughly 10:15am PST

**Screenshots / video**

![Screenshot 2024-06-06 at 10 18 10 AM](https://github.com/lwouis/alt-tab-macos/assets/126411930/4364e06f-383e-470d-b1b2-68f3ed49da08)
![Screenshot 2024-06-06 at 10 18 39 AM](https://github.com/lwouis/alt-tab-macos/assets/126411930/366b3f46-08bd-4377-b3c7-6f1052fae3d9)

**Steps to reproduce the bug**

See settings in screenshot above - then try to trigger the shortcut to select next window. 

**Your environment**

* AltTab version: 6.70.0
* macOS version: Sonoma 14.5
* Other relevant info: ext. bluetooth keyboard, secondary monitor connected, MacBook Pro 13-inch, M2, 16gb RAM, 2022

**Comment by alexjustdoit** [comment]
Oh, btw I just realized.
Looks like the latest ver in your change log is 6.70.1, but the download link on your site downloads 6.70.0.
This does not trigger a crash in 6.70.1!

**Comment by lwouis** [comment]
@alexjustdoit thank you! It's a CI/CD bug which happens sometimes. I fixed it 👍
