### ISSUE TITLE
Click outside to cancel

### ISSUE THREAD

**Issue by fennecs** [lwouis/alt-tab-macos#341]
Anyway to click outside to cancel now ?

**Comment by lwouis** [comment]
Hi @fennecs! Thanks for sharing this idea!

I'm wondering how that interaction would play with the current drag-and-drop you can do onto the thumbnails. Also general mouse usage with things in the background while having AltTab UI open.

To my great surprise, the macOS app-switcher does close on an outter click. This means that to drag-and-drop onto it, you need to drag > invoke the UI > drop. This is not very nice as you may open it, then attempt a drag-and-drop, only to see it fail.

Windows 10 is even worse as it doesn't seem to let me drag-and-drop at all.

There are also questions of clicks that start outside the UI, but and released inside the UI on a thumbnail. And the opposite.

When need to flesh out these interactions to better define what we are talking about here.

**Comment by nathang21** [comment]
+1 this would help me a lot as I am still running into #286 quite often which results in the Alt-Tab overlay being stuck open.

When I get into that state, each time I instinctively try and press **esc** or **click outside to cancel** but neither work. Thus I think this adding **click to cancel** would be a large quality of life improvement when getting into an unexpected state.

As I type this, I'm realizing this might warrant a separate bug, as the Alt-Tab keyboard shortcut **Cancel and Hide** which defaults to Esc, does not seem to working as expected either.

**Comment by lwouis** [comment]
> As I type this, I'm realizing this might warrant a separate bug, as the Alt-Tab keyboard shortcut Cancel and Hide which defaults to Esc, does not seem to working as expected either.

Is this issue still happening to you @nathang21? I'm thinking it must have been at that time. I think today it works fine, no?

**Comment by lwouis** [comment]
Regarding this ticket specs, I think I have a spec that takes care of all use-cases through all 4 scenarios:

Terminology:

* `click`: `mouseDown`, followed by `mouseUp`, without `mouseMove` in between.
* `drag-and-drop`: `mouseDown`, followed by `mouseMove`, followed by `mouseUp`

Scenarios:

| Scenario | AltTab action | Events absorbed by AltTab |
|----------|--------------|--------------------------|
| `click` outside the UI | Close the UI | Yes |
| `click` inside the UI | Focus the hovered window | Yes |
| `drag-and-drop` from inside the UI to outside | Nothing | Yes |
| `drag-and-drop` within the UI | Nothing | Yes |
| `drag-and-drop` from outside to inside the UI | React to drag-and-drop if any; don't focus the hovered window | Yes |
| `drag-and-drop` outside the UI | Nothing | No; let the other apps handle the `drag-and-drop` |

**Comment by lwouis** [comment]
I finished implementing this ticket. During implementation, I realized that some apps react on mouseDown instantly, thus to enable `drag-and-drop` *after* AltTab is opened, we would need to enable all `mouseDown` events while AltTab is open. I decided that it's better to work like the macOS built-in app switcher, and have `drag-and-drop` only work if the drag is started *before* AltTab is open. Once it's open, `drag-and-drop` can't be initiated anymore, as all `mouseDown` events are absorbed by AltTab. I think it's the best UX possible

**Comment by nathang21** [comment]
> > As I type this, I'm realizing this might warrant a separate bug, as the Alt-Tab keyboard shortcut Cancel and Hide which defaults to Esc, does not seem to working as expected either.
> 
> Is this issue still happening to you @nathang21? I'm thinking it must have been at that time. I think today it works fine, no?

Just tested, and yeah **Esc to Cancel** is working as expected, no longer an issue.

Regarding **Click to Cancel** the new PR you are working on and the above table sounds perfect, excited to try that. Your latest implementation UX decision seems logical as well.
