### ISSUE TITLE
When an application does not have a window open, AltTab will display the application.

### ISSUE THREAD

**Issue by coder-virjay** [lwouis/alt-tab-macos#3411]
**Is your feature suggestion related to a problem? Please describe.**
I have set AltTab to only display applications in the current space, but I don’t want it to show applications that have no windows open. Is there a feature or configuration for this? If not, could you add this configuration feature?

**Describe the solution you'd like**
When the application has no open windows, AltTab will not display the application.
<img width="1730" alt="iShot_2024-06-07_11 42 53" src="https://github.com/lwouis/alt-tab-macos/assets/166351383/3635c7bd-9488-4533-9a8d-8f4eecdfcb11">

**Comment by lwouis** [comment]
Yes, there is a checkbox for that in Preferences > Appearance 👍
