### ISSUE TITLE
Allow vim key set customization

### ISSUE THREAD

**Issue by eugenesvk** [lwouis/alt-tab-macos#3413]
**Is your feature suggestion related to a problem? Please describe.**
Vim key feature repeats the age old vim mistake of using a key off Home keys (<kbd>H</kbd>) for cursor navigation

I'd like to stay on the home keys all the time for such a frequent operation and use `jkl;` instead of `hjkl` to match the cursor movement commands in other apps

(this is different from https://github.com/lwouis/alt-tab-macos/issues/3292 as that one is about adding more complicated commands, this one is just changing the default keys)

**Describe the solution you'd like**
Allow editing alpha keys that comprise the vim cursor commands

**Describe alternatives you've considered**
I'm using generic cursor keybinds with right Command + `jkl;`, but don't know of an alternative that would allow not using a modifier key

**Comment by lwouis** [comment]
Hi,

I'm afraid this is a bit too niche of a feature. Vim uses `hjkl` to move the cursor, by default. AltTab offers that behavior. It's probably used by less than 1% of users. It wouldn't make sense to expand on it, and add more customization. If anything, I think it may potentially go away one day. I'm the first one to love powerusers feature. However, in the context of #1179, I'd like to maintain only the core features of AltTab.

Thank you 🙇
