### ISSUE TITLE
Pull and App (rather than being pulled)

### ISSUE THREAD

**Issue by rpc31** [lwouis/alt-tab-macos#3421]
One of my biggest annoyance with cmd-tab is that apps are too much little smart when it comes to desktop occupancy

- If an App (ex. mail) is assigned to non desktop (by default) and opened in desktop 1 (ex. personal). If I cmd-tab (or alt-tab) this app from desktop 2 (ex. work), then I am "pulled" myself to desktop 1, losing context of what I wanted to write.
- If an App (ex. mail) is assigned to all desktops, then, let say I am writing an email on desktop 1 (personal) and quickly want to see an operation being run on chrome on desktop 2 (work), then Mail is "pulled" with me and I have to hide it to see what I wanted to see.

How to you people cope with that?
**Is there a way, when I use command tab to select a running macOS app on another desktop, to "pull" and bring the app to my current desktop rather than me being pulled to where lives the app?** (or to automatically "hide" the focused app when I switch to another desktop?)

**Comment by lwouis** [comment]
Hi,

This is how macOS works, and AltTab can't change it. I believe you may be able to achieve the workflow you want with [yabai](https://github.com/koekeishiya/yabai). It is a full window management system on macOS. It requires intrusive installation though, as it's the only way to hack the OS and bend its functionality to the user's will.

Thank you
