### ISSUE TITLE
Let toggle apps only on current desktop

### ISSUE THREAD

**Issue by ericmp33** [lwouis/alt-tab-macos#3424]
Lets setup the scenario:
In the Desktop 1 i have Discord & Telegram apps opened
In the Desktop 2 i have google Chrome and Firefox apps opened

If I currently do alt tab on the Desktop 1, I can also switch to apps on Desktop 2.

But I'd love to be able to only alt tab on apps on the desktop I am!!!

if I'd do alt tab on the desktop 1 I could only be able to switch to Discord or Telegram.

**Comment by ShlomoCode** [comment]
You can define this in the alt-tab preferences:
![CleanShot 2024-07-03 at 03 37 37@2x](https://github.com/lwouis/alt-tab-macos/assets/78599753/f74e3349-aa0d-403f-bc85-a2e0cbe4406f)

**Comment by ericmp33** [comment]
No way! `Visible Spaces` is the one. TY

**Comment by slrgt** [comment]
I tried switching it to Visible Spaces but it still shows apps on other desktops? What exactly is a Space?
<img width="519" alt="Screenshot 2024-12-01 at 3 25 52 PM" src="https://github.com/user-attachments/assets/010b29f5-3a94-47e9-84d8-c8660c2aec9a">

**Comment by lwouis** [comment]
@slrgt a Space is a virtual Desktop. You can see all Spaces at the too of the UI is you trigger Mission Control.

if you have multiple monitors, they can either have their own Spaces, or can share the same Spaces if you use them as one extended monitor

**Comment by slrgt** [comment]
<img width="550" alt="Screenshot 2024-12-02 at 1 57 12 AM" src="https://github.com/user-attachments/assets/33dbdf1e-8e41-4ed6-a00d-6962feacdc10">

where do you see customize?

<img width="539" alt="Screenshot 2024-12-02 at 1 57 28 AM" src="https://github.com/user-attachments/assets/5e55c271-ad32-4fdc-9e0d-ac4fc35f4709">

the customize thumbnail style doesnt include that option

**Comment by slrgt** [comment]
<img width="1512" alt="Screenshot 2024-12-02 at 2 00 46 AM" src="https://github.com/user-attachments/assets/5f57bcce-6e1e-4a06-be1d-223197addad4">

this is what i see

**Comment by slrgt** [comment]
restarting my computer fixed it
