### ISSUE TITLE
App not starting for 14.5 (23F79)

### ISSUE THREAD

**Issue by NiklasHe** [lwouis/alt-tab-macos#3430]
**Describe the bug**

I cannot open the app, it doesn't start but crashes immediately. Tried reinstalling but didn't work.

**Screenshots / video**

Nothing to see, just the app "starting" after double click and then nothing happening. When reinstalling I got the "app crashed" system dialogue.

**Steps to reproduce the bug**

1. have newest mac OS 14.5 (23F79)
2. try opening the app

**Your environment**

* AltTab version: newest (AltTab-6.70.1) 
* macOS version: 14.5 (23F79)
* Other relevant info: ---

**Comment by lwouis** [comment]
Hi,
Are you perhaps pressing command+tab instead of alt+tab (also known as option+tab)?
When you say it crashes. Do you mean you see a popup telling you about a crash? Is the icon visible in the top-right menubar?
Thank you 🙇

**Comment by lwouis** [comment]
Hi @Krokogator,

Are you on AltTab version 6.70.1?
Could you please tell me the date of the latest crash?
Finally, could you please run this command in Terminal.app and share what's returned?

```sh
defaults read com.lwouis.alt-tab-macos
```

Thank you

**Comment by TreeBranches** [comment]
Not the person who started this issue but;


```
defaults read com.lwouis.alt-tab-macos
{
    MSAppCenter310AppCenterUserDefaultsMigratedKey = 1;
    MSAppCenter310CrashesUserDefaultsMigratedKey = 1;
    MSAppCenterInstallId = "06D8CA37-1708-484E-AD38-8BAF3A6157DF";
    MSAppCenterNetworkRequestsAllowed = 0;
    MSAppCenterPastDevices = {length = 1149, bytes = 0x62706c69 73743030 d4010203 04050607 ... 00000000 00000389 };
    MSAppCenterSessionIdHistory = {length = 460, bytes = 0x62706c69 73743030 d4010203 04050607 ... 00000000 00000156 };
    MSAppCenterUserIdHistory = {length = 455, bytes = 0x62706c69 73743030 d4010203 04050607 ... 00000000 00000151 };
    preferencesVersion = "6.72.0";
    updatePolicy = 1;
    windowMaxWidthInRow = 30;
}

```

I came here to try and figure out how to even use it as I've only just heard about it today.

**Comment by lwouis** [comment]
Hi everyone,

This thread is becoming confusing since the OP @NiklasHe has never replied, and @Krokogator has not replied either.

In addition, I see no crash reports for v6.72.0, in the past month. This would seem to indicate that there are no crashes, or that their reports are not being sent.

@TreeBranches do you see the app icon at the top of your screen, after you launch the app? Does it work when you press option+tab, command+tab?

Thank you 🙇

**Comment by HillbillyZT** [comment]
@lwouis 
I am experiencing similar on 14.4.1. I am unable to even launch AltTab after updating to this (from some earlier 14.x, which I do not know). I've tried reboots, uninstalling, installing via brew or separately, I completely lost the ability to even launch the app.

The only sign of life I have been able to get out of the app at all has come from removing its permission listing in the screen recording menu in System Settings. Then, next launch I got "Send a crash report?" (which I just did) alongside "AltTab needs some permissions" dialog. Then, after being prompted to Quit & Reopen after granting the permission again, I am back to square one, with no signs of life whatsoever. Not in Activity Monitor, not in ps. I am at a loss.

```
❯ defaults read com.lwouis.alt-tab-macos      
{
    MSAppCenter310AppCenterUserDefaultsMigratedKey = 1;
    MSAppCenter310CrashesUserDefaultsMigratedKey = 1;
    MSAppCenterInstallId = "56C0132B-415C-43AF-BACF-FFAC5030C332";
    MSAppCenterNetworkRequestsAllowed = 0;
    MSAppCenterPastDevices = {length = 2227, bytes = 0x62706c69 73743030 d4010203 04050607 ... 00000000 000006a3 };
    MSAppCenterSessionIdHistory = {length = 1112, bytes = 0x62706c69 73743030 d4010203 04050607 ... 00000000 00000312 };
    MSAppCenterUserIdHistory = {length = 1107, bytes = 0x62706c69 73743030 d4010203 04050607 ... 00000000 0000030d };
    "NSStatusItem Preferred Position Item-0" = 571;
    "NSWindow Frame NSFontPanel" = "1213 176 445 239 0 0 1728 1079 ";
    "NSWindow Frame SUStatusFrame" = "664 726 400 135 0 0 1728 1079 ";
    "NSWindow Frame SUUpdateAlert" = "554 529 620 398 0 0 1728 1079 ";
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2024-10-09 21:37:24 +0000";
    SUUpdateGroupIdentifier = 1601720359;
    SUUpdateRelaunchingMarker = 1;
    appsToShow2 = 0;
    appsToShow3 = 1;
    crashPolicy = 1;
    fadeOutAnimation = false;
    holdShortcut = "\\U2325";
    holdShortcut2 = "\\U2318";
    holdShortcut3 = "\\U2318";
    nextWindowShortcut = "`";
    nextWindowShortcut2 = "\\U21e5";
    nextWindowShortcut3 = "`";
    preferencesVersion = "7.0.0";
    screensToShow = 1;
    screensToShow2 = 0;
    screensToShow3 = 0;
    spacesToShow = 2;
    spacesToShow2 = 0;
    spacesToShow3 = 0;
    theme = 0;
    titleTruncation = 2;
    updatePolicy = 1;
    windowDisplayDelay = 0;
    windowMaxWidthInRow = 30;
}```

**Comment by lwouis** [comment]
I believe this issue should be gone with the recent versions. I'll close this ticket 👍
