### ISSUE TITLE
Supports windows 11 theme

### ISSUE THREAD

**Issue by Allsochen** [lwouis/alt-tab-macos#3431]
**Is your feature suggestion related to a problem? Please describe.**
Windows 11 theme are nicer to look at, with larger and clearer gaps between each window of thumbnail.

![image](https://github.com/lwouis/alt-tab-macos/assets/5805484/27bebaf3-9862-4c0c-ad21-2569ca723916)

**Comment by lwouis** [comment]
Hi,

Yes, why not. The themes feature is challenged in #351. If it stays, why not add this theme. Please anyone, share a PR if you want this. It's quite easy to add a new theme for a newcomer to this project.

Thank you
