### ISSUE TITLE
ALT key sent through the active application when triggering AltTab menu

### ISSUE THREAD

**Issue by christophe-calmejane** [lwouis/alt-tab-macos#3432]
**Describe the bug**

When my shortcut to open AltTab triggers (the default ALT+TAB) I noticed that the ALT KeyDown event is sent through to the application that has the focus. More problematic, no KeyUp event is ever sent to that application when AltTab changes the active window. This is very easy to see if you have the web version of Excel or Word, that will display the menu shortcuts when you press ALT.

**Screenshots / video**
Here for example a partial screenshot of the web version of Excel showing in overlay the letter to trigger the menus. These overlay only appear when ALT is pressed.
![image](https://github.com/lwouis/alt-tab-macos/assets/23314088/4aa51cd9-48fe-4a42-9a2c-6fb57c426d07)

**Steps to reproduce the bug**

1. Open a web browser and open an Excel/Word page online
2. Have your web browser in focus
3. Press ALT+TAB to trigger AltTab menu
4. Change active window
5. Notice in your web browser the overlay for menu shortcuts

I will add that the problem occurs wether you quickly change the active window (ie. AltTab menu doesn't open) or slowly with AltTab selection window active.

I'm seeing some strange behavior sometimes on some applications (much like if the ALT key was pressed), so I wonder if it is because of this.

**Your environment**

* AltTab version: 6.70.1
* macOS version: Sonoma 14.5
* Other relevant info: External kbd, but same issue with builtin kbd

**Comment by lwouis** [comment]
Hi,

I think the key-down and key-up event are correctly sent through. I just tested on [this online input viewer](https://w3c.github.io/uievents/tools/key-event-viewer.html) and I see the correct sequence.

I think it may be specifically a bug with these online Excel/Word apps. Can you reproduce the issue with the online input viewer?

Thank you 🙇

**Comment by christophe-calmejane** [comment]
You are right that it seems to be OK on your online viewer.
But still, since I'm using AltTab, I'm often have some applications that behave very very weirdly (like I cannot click on text entry or things like that... sorry it's not very clear yet to me), or behave like the ALT key is pressed (virtually). As soon as I quit AltTab and only use macOS default app-switcher, I don't experience this behavior.

So my guess was that if a simple online app has the same kind of issues, maybe it explains what I experience with other apps (including Finder) when AltTab is active.
I used witch before and never had this kind of issues, very weird!!

Let me know if I can do anything to help understand the reason. (PS: I'm using Karabiner to remap a lot of keys as well, but I experience my issues if Karabiner is closed and only AltTab active).

PS: Awesome app though!

**Comment by lwouis** [comment]
As I've shared, I think you're experiencing bugs with specific apps. You mention text entry. I've seen such issues in the past, and they were all coming from Adobe Illustrator or After Effects having bugs, for instance.

I'm afraid if the input viewer says that AltTab is not absorbing the event, there is nothing we can do. The input viewer is getting key down then key up. This means Word and Excel are also getting the same events. Why they don't handle them properly is beyond our reach.

Thank you 🙇

**Comment by christophe-calmejane** [comment]
I'm not using this kind of applications. I get my weird errors mostly on Finder and VSCode and Chrome, where it's as if ALT and/or SHIFT is pressed.
Again, I only have the issue when AltTab is active (I have this kind of errors every 5 minutes or so, not a single in days when AltTab is not started).

The way to revert to a working state is clicking on the desktop or another app (not using the kbd), hitting alt/shift/ any control key, and click back on my application.

**Comment by lwouis** [comment]
Could you please share a video of the issue you witness with Finder?
Thank you

**Comment by christophe-calmejane** [comment]
I'll try to refine things but capturing a video is very tricky as it relies on clicking on a different window to start the capture, and clicking on a different window is what mainly "fixes" the issue. Another example of the problem when AltTab is active: when the system is in the bugged state, I can no longer close a tab in my Chrome using the kbd (but I can still type characters or change URL).
This is very weird, it really looks like a key is stuck :D

**Comment by lwouis** [comment]
Perhaps you could capture a video from your phone? This way you can show keyboard, screen, etc

**Comment by christophe-calmejane** [comment]
Smart :)
I need to figure out how to hide confidential information as this is a work station.
