### ISSUE TITLE
Incorrect focusing next tab

### ISSUE THREAD

**Issue by Armanio** [lwouis/alt-tab-macos#3438]
**Describe the bug**
Hi! Sometimes on opening alt tab current index instead of going next card go to ahead
I understand that it difficult to understand thats why i attach video from my screen.

**Screenshots / video**

https://github.com/lwouis/alt-tab-macos/assets/3195714/7d20a890-2054-43c3-8393-bfff86b6c237

**Steps to reproduce the bug**

**Your environment**

* AltTab version: 6.70.1
* macOS version: 14.4.1
* Other relevant info: 
<img width="247" alt="Снимок экрана 2024-06-18 в 18 07 28" src="https://github.com/lwouis/alt-tab-macos/assets/3195714/ecd5e20f-c0e8-4032-a543-fa154043e735">

PS: sorry for my terrible english, feel free to correct me and edit this issue.

**Comment by zhaoxuan** [comment]
Sometimes I get the same problem.

**Comment by Armanio** [comment]
@DavidAllewell last few days i use build from referred comment. All works like a charm! Thank you!

**Comment by DavidAllewell** [comment]
@Armanio glad to hear :) Would recommend closing this as a duplicate, in that case, and following #3117 for any updates.
