### ISSUE TITLE
Why's it recording?

### ISSUE THREAD

**Issue by viktorashi** [lwouis/alt-tab-macos#3458]
Sometimes in the upper tab it would show alt-tab capturing screen, this has recently happened since i upgraded to macos 14, it didn't need to do that before in order to see previews for my windows. Thanks for the response in advance!

**Comment by viktorashi** [comment]
<img width="329" alt="image" src="https://github.com/lwouis/alt-tab-macos/assets/33178074/3af2ca13-b116-4338-bad4-9e7f98625418">
yep

**Comment by lwouis** [comment]
Please see #1082
