### ISSUE TITLE
Showing other apps from other spaces when restarted

### ISSUE THREAD

**Issue by MattOrmianek** [lwouis/alt-tab-macos#3462]
When I restart AltTab (because of other problem I reported earlier), I see apps from other spaces, when I choose them to switch AltTab changes space to where the app is and removes bug with seeing this app (actually group of app per space). 
For example:
Space 1: VSC, Terminal
Space 2: Arc, Notion
Space 3: Calendar, Mail

Upon restarting AltTab, I am initially on space 1 but can see applications from spaces 2 and 3 as well. When I select an app from space 2, AltTab switches to space 2 and opens the selected app. Using the same shortcut again, I now see apps from spaces 2 and 3. I have to select an app from space 3, and AltTab switches to space 3. At this point, I only see apps from the current space, as intended from the beginning.
Settings for shortcut I am using:
Show windows from:
All apps
Visible Spaces
Screen showing AltTab

**Screenshots / video**

https://github.com/lwouis/alt-tab-macos/assets/16574489/4dc6834a-d85a-4cad-9aee-8d5bca972b32

**Steps to reproduce the bug**

1. Set same settings that I got and restart AltTab

* AltTab version: 6.69.0
* macOS version: 14.5 (23F79)
* Other relevant info: using multiple monitors

**Comment by lwouis** [comment]
I think you're experiencing #1324

**Comment by MattOrmianek** [comment]
Yea, probably, sorry for bad issue searching.
