### ISSUE TITLE
Running app icons showing despite no open windows

### ISSUE THREAD

**Issue by RubikOwl** [lwouis/alt-tab-macos#3467]
**Describe the bug**

In the last couple weeks I noticed that apps that were running but had no windows were showing up in AltTab. Thought it was a bug that would go away in a bit, but it's still here. Is this a new feature, and is there a way to disable it? Or might something else be causing it?

**Screenshots / video**

https://github.com/lwouis/alt-tab-macos/assets/59575282/3b5a27ad-a955-4756-8cd4-acf99e847cd4

**Steps to reproduce the bug**

Noticed it about the same time as I started using a new app, DockDoor. I have quit both apps though and the problem persisted.

**Your environment**

* AltTab version: 6.70.1
* macOS version: 14.5

* Other relevant info: e.g. using external keyboard, multiple monitors, etc

Macbook Pro, M2 Pro, 16GB RAM. Built in screen, keyboard, etc.

**Comment by lwouis** [comment]
Hi,

If I understand correctly, you don't want to see apps-with-no-open-window? There is checkbox to disable this behavior in Preferences > Appearance.

Thank you 🙇

**Comment by RubikOwl** [comment]
Thank you, looked through settings and I guess I missed it.
