### ISSUE TITLE
AltTab freezes when a window or an app is unresponsive

### ISSUE THREAD

**Issue by lwouis** [lwouis/alt-tab-macos#348]
This is a follow-up to #342. I explained the situation there.

This ticket is about investigating the current impact, and discussing ways to mitigate it.

**Comment by lwouis** [comment]
Sharing here this [small utility app I made to simulate an app that freezes](https://github.com/lwouis/alt-tab-macos/files/4662473/FreezeTester.app.zip)

**Comment by lwouis** [comment]
I tried playing with setting a global `AXUIElementSetMessagingTimeout`. The smallest value that effective seems to be `0.001` (i.e. 1ms)

**Comment by lwouis** [comment]
I just thought about a solution that doesn't involve using concurrent datastructures, and making the app 10x as complex.

The idea would be to listen to AX events on another queue. Then when an event triggers, put it on a concurrent queue. There, we would gather all AX info for the relevant window and/or app. Here if the AX call blocks, we are not blocking the app. Then once the AX info is gathered, we send the rest of the work to the main queue, where all the datastructures are sequential/simple.

There remains an extra dozen calls to get AX info outside the AX events. These will need to be looked at separately. It's a difficult situation as we have AX calls to check for tabs for instance, as there are no way to get events for tab, so we check last-second, on the latency-critical path, unfortunately.

Another thing is that these AX calls can fail as the default timeout is 6s, but an app can be unresponsive for more than that. So we need to implement retries as we did for the AX observers, if we want to not miss updates from unresponsive apps.

**Comment by lwouis** [comment]
I ended up digging way deeper. I discovered what may possibly be the root cause of #157. I think the issue was "thread explosion". Currently the way we fetch the window screenshots is sending one block of code *per window* to `DispatchQueue.global`. I learned watching this WWDC video that you need to manually cap thread creation, otherwise you reach the limit of 60-something threads, and the app deadlocks, which I think is why it would stop work. That would also explain why it would fail on reboot. After the user closes a few window, then the app would start working again.

I addressed this and way more by reworking basically everything about how the app does multi-threading/concurrent code. The app now uses a mix of manual static threads for accessibility events, and keyboard events; and dispatch queues for multi-threading the thumbnails or other things on invocation, as well as processing shortcuts affecting the windows (e.g. `alt+m`, `alt+w`).

Here is more examples from the commit:

> fix: rework all multi-threading to handle complex scenarios
>
>BREAKING CHANGE: this rework should fix all sorts of issues when OS events happen in parallel: new windows, new apps, user shortcuts, etc. Here are example of use-cases that should work great now, without, and very quickly:
>
>* AltTab is open and an app/window is launched/quit
>* A window is minimized/deminimized, and while the animation is playing, the user invokes AltTab
>* An app starts and takes a long time to boot (e.g. Gimp)
>* An app becomes unresponsive, yet AltTab is unaffected and remains interactive while still processing the state of the window while its parent app finally stops being frozen
>
>closes #348, closes #157, closes #342, closes #93

**Comment by mfn** [comment]
Your work, detail, scrutiny on this software is ridiculous. In a positive way. I'm in awe. Thank you 🙇
