### ISSUE TITLE
Hiding Firefox from AltTab also hides Firefox Developer Edition

### ISSUE THREAD

**Issue by metametapod** [lwouis/alt-tab-macos#3480]
**Describe the bug**

When Firefox is hidden from AltTab under the Blacklists tab in preferences, Firefox Developer Edition becomes hidden as well with no option to disable.

**Screenshots / video**

<img width="700" alt="Screenshot 2024-07-11 at 10 27 10" src="https://github.com/lwouis/alt-tab-macos/assets/80652640/36b964b4-7c62-4e13-a82b-bd3a34ef7b78">

**Steps to reproduce the bug**

1. Use config shown above (`org.mozilla.firefox` set to Always Hide in AltTab and `org.mozilla.firefoxdeveloperedition` set blank, or unset.
2. Open a window in Firefox Developer Edition.
3. Use AltTab window switcher, it won't be shown.

**Your environment**

* AltTab version: 6.71.0
* macOS version: 14.5

**Comment by lwouis** [comment]
Hi,

The strings added to the blacklist will be matched as prefixes. That is, if the app bundle ID *starts with the string*, it will match it.

I'm afraid that in this case, the bundle IDs share the same prefix, and there is no way to discriminate one but not the other. Or more preciselu discriminate the main release and not the developer edition. The opposite is possible.

I'm afraid i can't provide an easy solution there 🙇‍♂️

Thank you
