### ISSUE TITLE
The Passwords app is ignored in Sequoia Beta 3

### ISSUE THREAD

**Issue by AChangXD** [lwouis/alt-tab-macos#3485]
**Describe the bug**

If you open the Passwords app in Beta 3, the app does not appear in the list when Alt Tabing.

**Screenshots / video**

**Steps to reproduce the bug**

1. Go to Passwords
2. Alt Tab

**Your environment**

* AltTab version: Version 6.71.0
* macOS version: MacOS Sequoia Beta 3
* Other relevant info: Doesn't work on single or multiple monitors.
<img width="481" alt="image" src="https://github.com/user-attachments/assets/c6531510-56d3-4b84-8c7e-8e1176cc22ba">

**Comment by lwouis** [comment]
Hi,

It's likely a bug of the Passwords app. AltTab merely reports windows. If an app uses the wrong thing, like a non-window UI element, then AltTab doesn't show it. AltTab shows what the OS reports.

Furthermore, this is a beta. Apple typically fixes many of these issues every beta cycle.

I'll close this ticket. Let's revisit it after the public release. In the meanwhile, I suggest using the Feedback app to report this issue to Apple so they can fix it 👍 

Thank you
