### ISSUE TITLE
The Quit button is not accessible when the system language is RTL

### ISSUE THREAD

**Issue by ShlomoCode** [lwouis/alt-tab-macos#3487]
**Describe the bug**

When the system language of macOS is RTL language (Hebrew/Arabic), macOS places its traffic light buttons on the right side of the window instead of on the left, which causes a lack of access to the Quit button (see screenshot)
Note that what determines is the system language and not the specific language for the application, even if one is selected in System Settings (it doesn't make much sense on Apple's part, but that's how it works).

**Screenshots / video**

![CleanShot 2024-07-14 at 02 47 23@2x](https://github.com/user-attachments/assets/78164241-c3d1-44cf-84b6-ab096eb13744)
![CleanShot 2024-07-14 at 02 39 15@2x](https://github.com/user-attachments/assets/59f1841d-c851-43e9-918a-4976068d6bbe)

**Steps to reproduce the bug**

1. Go to System Settings > Language & Region
2. Change the language to hebrew
3. Open alt-tab settings

**Your environment**

* AltTab version: 6.71.0
* macOS version: 14.5

**Comment by lwouis** [comment]
Hi,

Thank you for raising this issue, and thank you for sharing an MR to fix it!

I've left a comment on the MR. Could you please give it a look?
After that, I think we should be able to merge and ship it in the next release 👍 

Thank you 🙇
