### ISSUE TITLE
Better options to give you money?

### ISSUE THREAD

**Issue by blahdeblahde** [lwouis/alt-tab-macos#3489]
Hey,
I'd really like to be able to support your project but $5/mo on Patreon is more than I can manage. I'd love to be able to pay $5/year or $10/yr or something else. 
Also, I don't want to connect github to my financial info so I don't want to use that. 

Thanks

**Comment by lwouis** [comment]
Hi,
Thank you for your kind message. Another time maybe 👍 
Thank you 🙇
