### ISSUE TITLE
When launching the program on the macOS 15 beta version, the permission for screen recording was failed to obtain. Repeated attempts to add the permission were made, but none of them could solve the problem.

### ISSUE THREAD

**Issue by yunteng-2023** [lwouis/alt-tab-macos#3494]
**Describe the bug**

When launching the program on the macOS 15 beta version, the permission for screen recording was failed to obtain. Repeated attempts to add the permission were made, but none of them could solve the problem.
<img width="441" alt="image" src="https://github.com/user-attachments/assets/02a8a737-bc71-49e5-918a-f9bffd169a3d">

**Comment by 0x5b62656e5d** [comment]
#3477
