### ISSUE TITLE
Alt-tab window preview don't stop overlapping other windows when you click with mouse.

### ISSUE THREAD

**Issue by Lego4m** [lwouis/alt-tab-macos#3505]
**Describe the bug**

Alt-tab window preview don't stop overlapping other windows when you click with mouse.

**Screenshots / video**

![Screen Recording 2024-07-22 at 16 28 34](https://github.com/user-attachments/assets/9c2677b4-00e3-4429-b879-14a98a5ce36f)

**Steps to reproduce the bug**

1. Enable the "Preview selected window" option at "Appearance" menu.
2. Open two windows and overlap a little of one over the other.
3. Alt+tab until one of the windows.
4. Click with mouse in the other window (while holding alt-tab).
5. The window focused by the alt-tab will overlap any other window.
6. Press alt-tab again to the bug go away.

**Your environment**

* AltTab version: 6.72.0
* macOS version: 14.4.1

**Comment by lwouis** [comment]
Hi,

I haven't been able to reproduce this issue.

Does it happen every time for you? Are you able to replicate it with a Finder window and a web browser window for instance?

Could you please share screenshots of your AltTab preferences?

Thank you 🙇

**Comment by lwouis** [comment]
Hi,

I was able to reproduce the issue with Preview. Indeed, there was missing code to remove the Preview window, if an app-with-no-window was selected. I'll release a new version of the app with a fix soon 👍 

Thank you 🙇
