### ISSUE TITLE
Is there method to add a shortcut for "show" function in the menu?

### ISSUE THREAD

**Issue by foralan** [lwouis/alt-tab-macos#3511]
As the title, I want to add a keyboard shortcut for this function, so that I can use touchpad to triger the shortcut and open the AltTab window,  just like open the mission control.

Is there any convenient methods?

<img width="219" alt="image" src="https://github.com/user-attachments/assets/9441b39c-4ebd-4b8c-9864-106adb669448">

**Comment by lwouis** [comment]
Hi,

You can press alt+tab to trigger AltTab. You can also customize this shortcut in Preferences > Controls. If you want to have the panel remain on screen after you release alt+tab, you can set this in Preferences > Controls > Do Nothing, as shown here:

<img width="583" alt="image" src="https://github.com/user-attachments/assets/fe7ead51-3bca-453b-9dbb-b807d9a86951">

Thank you 🙇
