### ISSUE TITLE
Apps with no windows show on all spaces

### ISSUE THREAD

**Issue by ngagun** [lwouis/alt-tab-macos#3513]
First thank you for this wonderful app!

Even though I have Show windows from Visible Spaces selected, apps with no windows show on all spaces. This is an odd behavior which I think rises to the level of a bug in some cases. For example, if you command-click an app with no windows in the dock, and Options --> Assign to this desktop, then you go to a different desktop and use AltTab choose the windowless app, it actually switches you back to the different space where the app was assigned. That is definitely not behavior anyone is looking for! If we have selected "Show windows from Visible Spaces", I think all users would intend that we want AltTab to refer only top the context of our active space.

I understand the issue of the relationship between windowless apps and multiple spaces is tricky, e.g., this previous issue:
https://github.com/lwouis/alt-tab-macos/issues/1700

But I think an easy solution that would solve this problem would be to have an option simply not to show windowless apps in AltTab. For me personally, the only reason I would have a windowless app running would be so that I can "boot" it faster when I actually want to do something with it later. For example, I am going to use Excel multiple times every day, so even if I don't have any Excel docs open right now, I'm going to keep the app open because I know I'll be needing it again soon. But this doesn't mean that I need Excel to be showing up in AltTab. When I need it again, I'll launch it with Spotlight. It's not something that I want to "switch" to because in my mind, it's not really an active app. Hope that makes sense.

Could you add an option to not show windowless apps?

Thanks again for this program.

AltTab version 6.72.0
macOS Sonoma 14.5

**Comment by lwouis** [comment]
Hi,
You can hide apps with no window. The checkbox is in Preferences > Appearance 👍 
Thank you 🙇

**Comment by ngagun** [comment]
Hello, oh sorry I missed that, perfect!

Thanks again for your fantastic app.

**Comment by liuxy10** [comment]
> Hi, You can hide apps with no window. The checkbox is in Preferences > Appearance 👍 Thank you 🙇

Hi, it looks like it's not there anymore. Please return this feature.

<img width="558" alt="Image" src="https://github.com/user-attachments/assets/56c7b458-5eef-4570-b6a8-9a11d070aa00" />

**Comment by lwouis** [comment]
@liuxy10 the feature is still there. It's in the Customize popover
