### ISSUE TITLE
No menu bar icon

### ISSUE THREAD

**Issue by acer51-doctom** [lwouis/alt-tab-macos#3514]
# Bug by itself:

I basically have no menu bar icon

# Environment:

* AltTab version: 6.72.0
* macOS version: Sonoma 14.5
* Other relevant info: Using Vanilla and has never done that before

# Screenshots:
<img width="734" alt="AltTab Menu Icon not showing." src="https://github.com/user-attachments/assets/08774907-310e-4511-8663-01df8b6ce6e8">

(Oh and sorry for the French text in the screen, I am French (DO NOT SAY OUI OUI BAGUETTE))

**Comment by lwouis** [comment]
Salut,

Je suis l'auteur de cette app. Je suis francais moi aussi 👋 

Est-ce que l'app fonctionne malgre que l'icone ne soit pas visible ? Si tu presse alt+tab, la fenetre apparait ?

Je me demande si tu n'as pas desactive l'icone. C'est une preference dans le premier onglet des Preferences. Tu peux cliquer sur le menu deroulant de l'icone, et selectioner la derniere option, pour ne pas afficher d'icone :

<img width="591" alt="image" src="https://github.com/user-attachments/assets/e97d6067-41ef-4184-83a3-d4f4ea0e8d40">

Pour afficher le panneau de preferences quand on n'a pas l'icone, il suffit de lancer AltTab de nouveau, depuis le dossier Applications. Cela ouvre le panneau de preferences.

Merci 🙇

**Comment by acer51-doctom** [comment]
Ah okay! Je savais pas que t'étais français mais bon. Du coup, nan j'ai pas désactivé l'icône, a ce que tu peux voir dans cette image.

<img width="659" alt="Capture d'écran de AltTab avec la première icône par défaut" src="https://github.com/user-attachments/assets/49e521e2-7f57-4e4b-8095-e0943d404126">

J'ai aussi essayé de réinitialiser les paramètres mais rien, sa ne marche pas, j'ai aussi essayé de changer l'icône mais aucun effet aussi.

**Comment by lwouis** [comment]
Sur ton screenshot, j'ai l'impression de voir que tu utilise un menubar manager comme Vanilla ou Bartender. Le probleme se trouve peut-etre la ? Pourrais-tu essayer de quitter cette app tierse pour voir si cela resoud le probleme ?

**Comment by acer51-doctom** [comment]
> Sur ton screenshot, j'ai l'impression de voir que tu utilise un menubar manager comme Vanilla ou Bartender. Le probleme se trouve peut-etre la ? Pourrais-tu essayer de quitter cette app tierse pour voir si cela resoud le probleme ?

Oui effectivement sa marche, AltTab se remet dans la barre des menus. Je ferais attention, merci pour l'aide 👌
