### ISSUE TITLE
Windows are not center aligned, sometimes

### ISSUE THREAD

**Issue by ngocphamm** [lwouis/alt-tab-macos#352]
**Describe the bug**

Windows are not centered, but only somtimes, like after I have some windows/apps opened (maybe with their weird sizes?)

**Screenshots / video**

<img width="1199" alt="Screen Shot 2020-05-22 at 3 53 23 PM" src="https://user-images.githubusercontent.com/395123/82707043-3b520c80-9c49-11ea-8e45-e8a7f190fb30.png">

**Steps to reproduce the bug**

Not sure... Just open AltTab window I guess...

**Comment by lwouis** [comment]
Hey @ngocphamm :)

This looks like a layout bug. The layout code is around 50 lines of code but it's pretty tricky to follow and easy to make off-by-1-px calculations which completely ruin the layout.

Is it happening all the time, or is it just with specific combination of windows sizes? I haven't used centered alignment in a while so not sure if this issue has been going on for a while or not

**Comment by ngocphamm** [comment]
This is happening only with a certain combination of windows, of various sizes I have not been able to figure out the pattern yet.

**Comment by ngocphamm** [comment]
And also I noticed the font for the window title sometimes is different for 1 or more windows 🤔 

<img width="521" alt="Screen Shot 2020-05-23 at 10 53 21 AM" src="https://user-images.githubusercontent.com/395123/82733730-e9aa9000-9ce3-11ea-9341-82244f677fe7.png">

**Comment by lwouis** [comment]
@ngocphamm i remember fixing that issue a long time ago [with a workaround](https://github.com/lwouis/alt-tab-macos/commit/0de7a5515cbf999366a9712eefe15fcf119ac68b#diff-7b6f61502360544587ff300d05bcb331L43). I then removed it as it seemed no longer necessary after I rewrote the whole layout for performance. How is this stuff still bugging? *sigh* macOS...

**Comment by lwouis** [comment]
For the windows not being aligned, I think I found the issue. It happens only in center-aligned layout, and when you have preferences set to hide some windows (like from other spaces, or minimized, etc).

I fixed it, and it will be released soon 👍
