### ISSUE TITLE
Sequoia Beta - System-Popup: Alt-tab can access screensharing allow

### ISSUE THREAD

**Issue by zilchulant** [lwouis/alt-tab-macos#3524]
**Describe the bug**

New permission message is nagging. Message is something like Alt-Tab can access screen and audio. Open system settings or continue to allow.

Solution: According this [reddit comment](https://www.reddit.com/r/MacOS/comments/1ef95gu/comment/lfk9c2l/), an API Update is needed to ScreenCaptureKit or SCContentSharingPicker

* AltTab version: 6.72.0
* macOS version: MacOS Sequoia Public Beta (24A5298h)

**Comment by lwouis** [comment]
#3477

**Comment by zilchulant** [comment]
Thanks for your reply, but I want to adress the permission message from MacOS, not the one from alt-tab. Sorry for not having a screenshot at first, but here it is:

This is the error message, sometimes there will be multiple messages.
<img width="409" alt="Bildschirmfoto 2024-07-31 um 18 34 53" src="https://github.com/user-attachments/assets/e99c9cf7-c505-4b1c-9cc2-5b3e3b26e3f7">

**Comment by lwouis** [comment]
Indeed, there are 2 issues:

* The way AltTab checks for permission seem to have issues on macOS Sequoia Beta
* Apple has added a warning dialog "are you still sure you want to permit this?" in the Beta

This ticket here discusses your issue more: https://github.com/lwouis/alt-tab-macos/issues/3183
