### ISSUE TITLE
On mouse hover, focus shifts down pop-up list automatically

### ISSUE THREAD

**Issue by evanhammer** [lwouis/alt-tab-macos#3525]
**Describe the bug**

When my mouse is hovering over the alt-tab window, the focus automatically moves several windows down the list. I have "Mouse hover" and "Cursor follows focus" unchecked.

**Screenshots / video**

https://github.com/user-attachments/assets/62321698-5ad5-4228-9c81-0f972a88f0e4

**Steps to reproduce the bug**

1. Turn off "Mouse hover" and "Cursor follows focus"
2. Put your cursor where the Alt Tab panel will appear
3. Press "Alt-Tab" once
4. See focus move down several items in the list rather than just a single one

(To clarify: the focus does not move to where my cursor is, but just down several items in the list.)

**Your environment**

* AltTab version: Version 6.70.1
* macOS version: 14.5 (23F79)
* Other relevant info: Happens if I'm using built-in trackpad (in my laptop) or Apple's Magic Trackpad (via Bluetooth)

**Comment by evanhammer** [comment]
I upgraded to 6.72.0 and this no longer happens. Sorry about the request!

**Comment by lwouis** [comment]
I hope it doesn't come back. It seems to me that you may have experienced https://github.com/lwouis/alt-tab-macos/issues/3117

**Comment by evanhammer** [comment]
@lwouis Yeah, it's that one. Thanks!

**Comment by tanaysengar-ylconsulting** [comment]
I just updated to ver 7.4.0. Cursor is no longer following the application that is in focus. I am also not able to find the setting. Please help me resolve this
