### ISSUE TITLE
Is it possible to have the window picker show up in all screens

### ISSUE THREAD

**Issue by pgsill** [lwouis/alt-tab-macos#3526]
I don't see an option for here, but I'd assume that there is some way to make this happen?
<img width="321" alt="image" src="https://github.com/user-attachments/assets/059ae095-d185-4ad0-bcd5-657902db96c3">
I also looked for it in Controls but it's not there either.
If this feature doesn't exist yet I'll open a proper feature request.
Thanks!

**Comment by lwouis** [comment]
Duplicate of https://github.com/lwouis/alt-tab-macos/issues/535
