### ISSUE TITLE
Hidden windows still show up as icons when Hidden windows is set to "Hide"

### ISSUE THREAD

**Issue by ForzaAaRon** [lwouis/alt-tab-macos#3532]
Currently, when AltTab is activated, large icons show up as previews when they are hidden. I've tried toggling between "Show", "Hide" and "Show at the end" to no avail. Have also tried to resetting but the issues persists. 

A clear and concise description of what the bug is. What happened, and what you think should have happened.
<img width="607" alt="image" src="https://github.com/user-attachments/assets/62edea1f-83a1-4f9c-989a-14a55fd4f384">
<img width="700" alt="image" src="https://github.com/user-attachments/assets/bf4d4519-dcd5-4b58-a486-2ef4209686e2">

**Steps to reproduce the bug**

1. Hide an application by clicking on the red button or control+w
2. Activate AltTab with shortcut
3. Icons show up as previews

**Your environment**

* AltTab version: Version 6.72.0
* macOS version: Sonoma 14.0
* Other relevant info: No external monitors

**Comment by lwouis** [comment]
The setting you want is in Preferences > Appearance > Hide apps with no open window
