### ISSUE TITLE
Passwords app in macOS 15 not visible

### ISSUE THREAD

**Issue by Aradig26** [lwouis/alt-tab-macos#3545]
**Describe the bug**

The passwords app does not shop up  in the alt tab menu. No preview or app icon

**Screenshots / video**

Add screenshots to help explain your problem. You can also record your screen to show the bug in action. That is *really* helpful!

**Steps to reproduce the bug**

1. Open passwords
2. Open any other app on top
3. Alt-tab 
4. Passwords app missing
**Your environment**

* AltTab version: 6.71.0
* macOS version: 15.1

**Comment by lwouis** [comment]
Hi,

I'm not familiar with this new Sequoia Passwords app. Based on what 1Password is doing, I think Passwords.app is likely to purposefully hide its windows, so apps like AltTab don't grab their contents.

Closing this as there is likely nothing on our side. Also let's see once Sequoia is live. Betas are moving targets. We should wait for things to be stable to discuss potential problemes.

Thank you 🙇

**Comment by lwouis** [comment]
It will either not showing, or showing as an all-black window.

Nothing can be done. These apps are purposefully working to not have their window accessible by apps like AltTab, to increase security of their customers.

**Comment by josdyr** [comment]
When using the built in tab switcher in MacOS, the Passwords app shows up fine and as I'd expect, however this is indeed not the case for AltTab.
