### ISSUE TITLE
Alt-Tab selection does not disappear after I clicked to choose already

### ISSUE THREAD

**Issue by Charlie-Dang** [lwouis/alt-tab-macos#3550]
Alt-Tab selection does not disappear after I clicked to choose already

1. Cmd + Tab and hold the Cmd to see app list
2. Click on one app at the end of the list (As I don't want to tab when the list is quite long)
3. After clicking I still see the Alt Tab selection showing and not disappear as my expectation
4. Click 2nd time then it disappears

VIdeo reproduce: [Here](https://drive.google.com/file/d/1DhHbFdVshcM4x-X1dqUz5y1Re4xYbcJN/view?usp=drive_link ) 

* AltTab version: Version 6.72.0
* macOS version: Version 14.6.1 (23G93)
* Other relevant info: N/A

**Comment by lwouis** [comment]
Hi,

Is there perhaps multiple AltTab icons in the top menubar? Having multiple instances running may explain this behavior.

I can't reproduce it.

Do you use an external keyboard, or the built-in laptop keyboard? Do you use software remapper (e.g. BTT, Karabineer, etc)?

Can you reproduce this every time, like after a reboot?

Thank you 🙇

**Comment by Charlie-Dang** [comment]
Yes it occurs every time even after reboots. 
I found out that only happens when I use Cmd + Tab, no issue at all when I use Option + Tab as Shortcut 2
When I use Cmd+Tab, the selection highlight/icon are shaking blinking just like any button-stuck, but not like that with Option+tab
I don't use any external keyboard, only macbook pro laptop keyboard. No software, only Logi Option+ from Logitech mouse.

**Comment by lwouis** [comment]
My guess is that you have some app or setting on your setup, which messes with command.

If AltTab works with option, then it works. It trreats keyboard shortcut the same.

So i suspect another app is intercepted the command key for example

**Comment by Charlie-Dang** [comment]
Hi friend,
I just want to update that now it's work OK after I do only one change: I try to change to another button and then re-register the Cmd + tab in Controls > Shortcut 1 (Previously it's was by default, I never touch)
Will monitor, thank you for your support

**Comment by Charlie-Dang** [comment]
Hi bro,
Just to update you that the issue reoccurs after few reboots, not sure why
I confirmed that all other shortcut can have same issue: Cmd+tab/Option+tab/shift+tab, but intermittently, I cannot see any clue yet

**Comment by lwouis** [comment]
Are you sure that you don't have 2 AltTab running at once?

could you please share a video of the issue?

Thank you 🙇

**Comment by Charlie-Dang** [comment]
Hi bro,
Yes you are correct, I found 2 lines of AltTab in Activity Monitor. At first I only look at upper menu bar and only see 1 icon, but actually in Activity Monitor it's 2 lines. 
Maybe because I checked inside app "Start at login" and also register this app as "Open at login" in General Setting?
After that I force stop 1 AltTab in Activity Monitor and seems everything OK now.

**Comment by lwouis** [comment]
> Maybe because I checked inside app "Start at login" and also register this app as "Open at login" in General Setting?

Indeed! The `Start at login` checkbox is enough 😅 

I'm happy that the issue is gone for you 🎊
