### ISSUE TITLE
How can I only see "open" windows?

### ISSUE THREAD

**Issue by muezz** [lwouis/alt-tab-macos#3563]
See the following image:
<img width="1640" alt="image" src="https://github.com/user-attachments/assets/897641fe-51d9-402f-beb7-ff436f4cb35e">
I have only 3 things open - 1 arc window, VS code and an ios simulator.
This is what AltTab shows me:
<img width="1408" alt="image" src="https://github.com/user-attachments/assets/8a181b10-5166-453d-8853-43bd30a4e26d">
How can I make these "closed" apps disappear from this without actually quitting them? Keeping them makes it hard to quickly toggle the 2-3 active apps.

For context, here are me settings:
<img width="656" alt="image" src="https://github.com/user-attachments/assets/9782465d-af2c-443f-bbb8-e923721d2d6b">

**Comment by lwouis** [comment]
Hi,

You can hide those in Preferences > Appearance > Hide apps with no open window 👍 

Thank you

**Comment by ah185284** [comment]
Sorry, I just happened to find this again, but it doesn't seem like that checkbox exists any longer under Preferences > Appearance > Hide apps. Would you mind showing me where it's been moved?
![Screenshot 2024-10-22 at 11 40 32 AM](https://github.com/user-attachments/assets/6a9724c4-29a0-4fcb-905a-25bc500e636a)

**Comment by lwouis** [comment]
Hi @ah185284,

Please click on the `Customize Thumbnails Style...` button seen on your screenshot. Then on the `Hide apps with no open window`, as seen here:

<img width="672" alt="image" src="https://github.com/user-attachments/assets/6775f40c-9da5-4249-b5ff-ea5d412e6786">

Thank you
