### ISSUE TITLE
Add preference: 

### ISSUE THREAD

**Issue by Gouzhong1223** [lwouis/alt-tab-macos#359]
Add preference: Is it possible to **add a new setting item to open or close the menu bar icon at the top**, because some users may have limited top menu bar position and need to display other icons.

**Comment by lwouis** [comment]
Hi @Gouzhong1223! Thanks for sharing this feedback about the menubar icon!

It turns out there is already an existing ticket for that change. I'll close this ticket as a duplicate. Please follow progress in #103
