### ISSUE TITLE
Allow user to see the version used

### ISSUE THREAD

**Issue by cmf** [lwouis/alt-tab-macos#36]
When filing bug reports, it's useful to be able to send the version of the software that the user is running. Currently, as far as I can tell, there's no way to see this. When there's a config panel (#8) it could be shown there. It would also be a good idea to put the version in the downloaded archive name.

**Comment by lwouis** [comment]
For implementation: the version is generated during CI build on master. A bash script could replace some placeholder in the code before the xcodebuild happens, as well as the archive file name.

**Comment by lwouis** [comment]
There were some CI issues with 1.4.0 and 1.4.1. Starting from [1.4.2](https://github.com/lwouis/alt-tab-macos/releases/tag/v1.4.2), the app shows version in the archive names, and in the menubar UI 👍

**Comment by cmf** [comment]
Nice, thank you!
