### ISSUE TITLE
Firefox fullscreen videos are not listed in AltTab

### ISSUE THREAD

**Issue by lwouis** [lwouis/alt-tab-macos#360]
From @nathanshelly in https://github.com/lwouis/alt-tab-macos/issues/335#issuecomment-635111799:

👋 first off thanks so much for this app! love having Windows alt-tab behavior on macOS

I think I'm seeing a similar bug even on the latest v4.0 (happy to open a separate issue if you'd prefer). For some reason if I fullscreen a video in Firefox the window no longer shows up in the switcher. 

Here's a video showing this behavior - [https://photos.app.goo.gl/NujoYwHvbBz4pAuL9](https://photos.app.goo.gl/NujoYwHvbBz4pAuL9)

Couple potentially interesting things to note:

- weirdly if I fullscreen the window before fullscreening the video everything works correctly (demonstrated at the end of the linked video)
- this occurs only in Firefox, have tested Chrome, Edge & Safari without the same results
- doesn't seem to be Youtube specific as I have reproed on Vimeo as well

thanks in advance for any help you can give and all the amazing work you've put into this app!

**Comment by lwouis** [comment]
My first reaction, from the other thread:

I could reproduce the issue in Firefox. I will open a new issue for this, as I believe the root cause is completely different from this ticket here. This ticket here was about a complex interaction where a window is spawned already in fullscreen, and we would detect it as a tab, due to the hacky way we have to detect tabs (no API exist to do it cleanly). Here this Firefox issue seems to be Firefox using some custom view to display fullscreen video, instead of using macOS built-in fullscreen APIs. For instance, moving the mouse cursor to the top of the screen doesn't bring the normal fullscreen title bar, and also invoking Expose reveals that they are not fullscreening, as normal fullscreen on macOS uses a dedicated Space.

Interestingly, when you fullscreen Firefox using the top left button, it does native fullscreening. Then when you double-click a video, it shows the fullscreen window within the fullscreen'ed window, which normal native behavior.

I'll see what can be done, but off the bat there is a chance that nothing can be done as we use the Accessibility API to understand what windows are shown to the user. If an app draws hacky custom views instead of using macOS windows (AppKit's NSWindow or NSPanel), then these windows are not reported by the Accessibility API and they basically don't exist as far as AltTab (but also potentially other accessibility software, like a screen reader) is concerned.

**Comment by nathanshelly** [comment]
Thanks for the followup here!

Did some additional digging based on your comments about non-native fullscreen and came across [this Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1403085) & [the associated fix](https://phabricator.services.mozilla.com/D37151).

Setting the native fullscreen preference like the photo below fixes this behavior and allows AltTab to find it:

<img width="952" alt="image" src="https://user-images.githubusercontent.com/9750687/83165213-cfe9be00-a0d2-11ea-9f12-2fb9d32e7769.png">

Apologies for not doing my due diligence earlier, feel free to close this out anytime.

**Comment by lwouis** [comment]
@nathanshelly Thanks for sharing this finding. I'm not sure why this is not the default 3 years later, but Mozilla must have their reasons.

I'm fine with whitelisting/hardcoding things to help support major apps. Firefox is a major app. So I'm going to add an exception for Firefox, so its fake-fullscreen windows appear in AltTab. This way noone has to change the obscure flag, and by the way I totally agree with their rationale that the default fullscreen experience is bad UX. It's sluggish, create another Space, and other jank. So it can only be a plus to support both fullscreen mode on Firefox.
