### ISSUE TITLE
Window Previews with Stage Manager: On.

### ISSUE THREAD

**Issue by vmyts539** [lwouis/alt-tab-macos#3614]
**Describe the bug**

When the Stage Manager is on, the application previews are skewed.

**Screenshots / video**
<img width="1710" alt="screenshot" src="https://github.com/user-attachments/assets/210ccde4-9990-48d0-a9d1-7e3dc7be1420">
**Steps to reproduce the bug**

1. Go to Control Center
2. Turn on Stage Manager
3. Use Alt-Tab
4. Observer window previews in the Alt-Tab task manager.

**Your environment**

* AltTab version: 6.72.0
* macOS version: 14.16.1

**Comment by lwouis** [comment]
https://github.com/lwouis/alt-tab-macos/issues/1731
