### ISSUE TITLE
[feature request] keyboard intreact with alt-tab-macos, show on multi displays,do not show the switcher panel immediately

### ISSUE THREAD

**Issue by eret9616** [lwouis/alt-tab-macos#3626]
I use context pastly, i think this ia a great app, but i miss some features,
wish can add these feature:

1. when select an window, press command + q or command + w should kill or close of of that window

2. use shortcut to press the shortcut again should close the switcher 
![image](https://github.com/user-attachments/assets/5a24b31e-a250-4bde-9145-bb2dcd7756f9)

3. add an option to display the switcher on all displays, not only active one

4. if use "then release focus selected window" ,delay the show of switcher panel ,because  if press key fast, there will a flash
![image](https://github.com/user-attachments/assets/a5c3efbd-2bb8-484d-855b-0eff3956fc96)

**Comment by lwouis** [comment]
Hi,

1. is already in the app. You can even customize the shortcuts in Preferences > Controls. You can also use the mouse to click on the colored disks to close/quit. You can also middle-click to close a window.
2. It's an interesting idea. We will look into it
3. #535 
4. There is already an option of that in Preferences > Appearance. You can decide how much delay you want, to avoid flashing the UI.

Thank you 🙇

**Comment by lwouis** [comment]
For this, you can check the checkbox about Mouse hover at the bottom of Preferences > Controls. Then what's hovered will be selected, and then shortcuts will apply to that, instead of keyboard selection 👍
