### ISSUE TITLE
Multiple Instances of Alttab

### ISSUE THREAD

**Issue by JDH247** [lwouis/alt-tab-macos#3647]
When my Mac starts up again, or when I close Alttab and open it again, it runs multiple instances of Alttab.
I need to close down one of the instances in order for Alttab to work again.

**Comment by lwouis** [comment]
https://github.com/lwouis/alt-tab-macos/issues/1840

**Comment by milon27** [comment]
facing the same issue on the latest version
<img width="568" alt="image" src="https://github.com/user-attachments/assets/0a41d6fb-5b60-44cf-8032-526f9423c170">
