### ISSUE TITLE
AltTab crashes on launch, after update to v7.0.0

### ISSUE THREAD

**Issue by omarpach** [lwouis/alt-tab-macos#3653]
**Describe the bug**

When I open Alt-Tab and press CMD-Tab which is the shortcut I used to switch applications, Alt-Tab closes. When I open it again it never shows the "crash" popup, but it is not working properly.

**Screenshots / video**

https://github.com/user-attachments/assets/55d9dc5e-6858-49b3-8673-0b21d20bea01

In the video I show karabiner elements viewer to show that it is registering correctly the CMD-Tab key combination. To keep the video short enough to upload I didn't show it, but Option-Tab also causes it to close. And if I try to open it again to go to preferences it also closes.

**Additional Context**
The app was working properly today but it prompted me to update it which I did, after that I don't remember using it because that happened in school. When i got home and tried to use it it started failing. I tried rebooting my mac but it didn't work, I tried uninstalling it via homebrew and reinstalling it but it didn't work, I tried installing it from the website and running it that way but it didn't work. When that didn't work, I tried updating my MacOS version from 12.7.4 to 12.7.6 and tried once again but nothing changed

**Steps to reproduce the bug**

1. Open Alt-Tab
2. Press CMD-Tab or Option-Tab
3. See error

**Your environment**

* AltTab version: 7.0.0
* macOS version: 12.7.6
* Other relevant info: using external monitor, and using external keyboard as well as karabiner elements

**Attempted solutions**

After looking in to some other issues, I saw someone recommended to run the following command in the terminal
`/Applications/AltTab.app/Contents/MacOS/AltTab`
I tried it and the app did open. The terminal also showed the following errors:

`2024-10-09 19:31:55.080 AltTab[2446:47281] [AppCenterCrashes] WARNING: +[MSACErrorLogFormatter formatStackFrame:report:]/467 Cannot find image for 0x116afa52e
2024-10-09 19:31:57.114 AltTab[2446:47300] [AppCenterCrashes] WARNING: +[MSACErrorLogFormatter formatStackFrame:report:]/467 Cannot find image for 0x108c6852e
2024-10-09 19:31:57.129 AltTab[2446:47300] [AppCenterCrashes] WARNING: +[MSACErrorLogFormatter formatStackFrame:report:]/467 Cannot find image for 0x11e94552e
2024-10-09 19:31:57.156 AltTab[2446:47300] [AppCenterCrashes] WARNING: +[MSACErrorLogFormatter formatStackFrame:report:]/467 Cannot find image for 0x10c54052e
2024-10-09 19:31:57.171 AltTab[2446:47300] [AppCenterCrashes] WARNING: +[MSACErrorLogFormatter formatStackFrame:report:]/467 Cannot find image for 0x10845b52e
2024-10-09 19:31:57.188 AltTab[2446:47300] [AppCenterCrashes] WARNING: +[MSACErrorLogFormatter formatStackFrame:report:]/467 Cannot find image for 0x115edd52e
2024-10-09 19:31:57.210 AltTab[2446:47300] [AppCenterCrashes] WARNING: +[MSACErrorLogFormatter formatStackFrame:report:]/467 Cannot find image for 0x11321c52e
2024-10-09 19:31:57.227 AltTab[2446:47300] [AppCenterCrashes] WARNING: +[MSACErrorLogFormatter formatStackFrame:report:]/467 Cannot find image for 0x10c91d52e
2024-10-09 19:31:57.241 AltTab[2446:47300] [AppCenterCrashes] WARNING: +[MSACErrorLogFormatter formatStackFrame:report:]/467 Cannot find image for 0x10c30a52e
2024-10-09 19:31:57.258 AltTab[2446:47300] [AppCenterCrashes] WARNING: +[MSACErrorLogFormatter formatStackFrame:report:]/467 Cannot find image for 0x103bad52e
2024-10-09 19:31:57.281 AltTab[2446:47300] [AppCenterCrashes] WARNING: +[MSACErrorLogFormatter formatStackFrame:report:]/467 Cannot find image for 0x11a99552e
2024-10-09 19:31:57.326 AltTab[2446:47300] [AppCenterCrashes] WARNING: +[MSACErrorLogFormatter formatStackFrame:report:]/467 Cannot find image for 0x10ad7152e`

and more but they were all of the same style. When the app did open it showed the following screen

![image](https://github.com/user-attachments/assets/5489fd5b-d215-46be-8e35-5a0340ebfd4e)

Which prompted me to give it permissions, which it already had, I tried removing said permissions and adding them again. When I gave screen recording permissions it restarted and it showed that it had those permissions now, but when I gave it accesibility permission and it restarted, it didn't open again, and the bug described at the beginning kept happening. When i then tried running the command again, it showed the same type of errors I wrote and it showed that again it did not have permissions. I am stuck now and don't know how to proceed.

**Comment by omarpach** [comment]
As suggested in another issue, I tried giving my terminal app (Alacritty) accesibility and screen recording permissions and then tried to run the Alt-Tab binaries again and got the following error and crash

![image](https://github.com/user-attachments/assets/4cb04116-ca1c-4c25-a788-048d40a23a8a)

**Comment by SirPole** [comment]
Hello, just updated to v7.0.0 on Sequoia, unfortunately getting the same thing when running it through terminal, except that it crashes right away on it's own... (When I start it normally, it doesn't show anything)

```
2024-10-10 10:18:00.958 AltTab[1774:19130] [AppCenterCrashes] WARNING: +[MSACErrorLogFormatter formatStackFrame:report:]/467 Cannot find image for 0x18e020274
"Exiting after receiving signal" 5
```

Downgrading to v6.73.0 works as expected...

**Comment by vmironovich** [comment]
Hello, I have the same issue on Sequoia (Version 15.0 Beta (24A5331b)). 

After the update the app seems to crash with the following log:
```
2024-10-10 09:17:15.498 AltTab[16351:11508598] [AppCenterCrashes] WARNING: +[MSACErrorLogFormatter formatStackFrame:report:]/467 Cannot find image for 0x18213c274
"Exiting after receiving signal" 5
```

Trying it to open in a new terminal app it goes through the following:
1. The window for permission check appears (that you need to provide to the terminal app). There are multiple `[AppCenterCrash]` logs, but the permission check window does not disappear.
```
2024-10-10 09:22:52.678 AltTab[18657:11525199] +[IMKClient subclass]: chose IMKClient_Legacy
2024-10-10 09:22:52.678 AltTab[18657:11525199] +[IMKInputSession subclass]: chose IMKInputSession_Legacy
2024-10-10 09:22:53.330 AltTab[18657:11525216] [AppCenterCrashes] WARNING: +[MSACErrorLogFormatter formatStackFrame:report:]/467 Cannot find image for 0x18213c274
2024-10-10 09:22:53.341 AltTab[18657:11525216] [AppCenterCrashes] WARNING: +[MSACErrorLogFormatter formatStackFrame:report:]/467 Cannot find image for 0x18213c274
2024-10-10 09:22:53.353 AltTab[18657:11525216] [AppCenterCrashes] WARNING: +[MSACErrorLogFormatter formatStackFrame:report:]/467 Cannot find image for 0x18213c274
2024-10-10 09:22:53.361 AltTab[18657:11525216] [AppCenterCrashes] WARNING: +[MSACErrorLogFormatter formatStackFrame:report:]/467 Cannot find image for 0x18213c274
2024-10-10 09:22:53.367 AltTab[18657:11525216] [AppCenterCrashes] WARNING: +[MSACErrorLogFormatter formatStackFrame:report:]/467 Cannot find image for 0x18213c274
```
2. If you kill the app, it will run and show permission window again, without `AppCenterCrashes`.
```
> /Applications/AltTab.app/Contents/MacOS/AltTab
2024-10-10 09:26:57.782 AltTab[19187:11533328] +[IMKClient subclass]: chose IMKClient_Legacy
2024-10-10 09:26:57.782 AltTab[19187:11533328] +[IMKInputSession subclass]: chose IMKInputSession_Legacy
```
3. After providing both permissions, this window appears, but the app crashes in the background.
<img width="247" alt="image" src="https://github.com/user-attachments/assets/2a21286e-8df9-437a-a363-f60f6f01e626">
```
2024-10-10 09:28:04.543 AltTab[19415:11535696] [AppCenterCrashes] WARNING: +[MSACErrorLogFormatter formatStackFrame:report:]/467 Cannot find image for 0x18213c274
2024-10-10 09:28:05.604 AltTab[19415:11535770] [AppCenterCrashes] WARNING: +[MSACErrorLogFormatter formatStackFrame:report:]/467 Cannot find image for 0x18213c274
2024-10-10 09:28:05.615 AltTab[19415:11535770] [AppCenterCrashes] WARNING: +[MSACErrorLogFormatter formatStackFrame:report:]/467 Cannot find image for 0x18213c274
"Exiting after receiving signal" 5
```

4. Afterwards running the app always produces the same result:

```
> /Applications/AltTab.app/Contents/MacOS/AltTab
2024-10-10 09:28:55.103 AltTab[19531:11537445] [AppCenterCrashes] WARNING: +[MSACErrorLogFormatter formatStackFrame:report:]/467 Cannot find image for 0x18213c274
"Exiting after receiving signal" 5
```

**Comment by alexandrpaliy** [comment]
I just opened another bug report ( https://github.com/lwouis/alt-tab-macos/issues/3654 ), but basically I have the same situation as @SirPole (except my "... Cannot find image for XXX" is a bit different).
I decided to open another issue because I don't even need to press anything - the app crashes right away.

**Comment by lwouis** [comment]
Given these logs from AppCenter, I wonder if it's not trying to find a crash report that's missing.

Could you please try running this command in Terminal.app? `defaults delete com.lwouis.alt-tab-macos`. It will reset all preferences for AltTab. Then running AltTab again. Does it still crash the same way?

Thank you 🙇

**Comment by vmironovich** [comment]
I don't know what exactly caused it to start working for me now, but after the following v7.0.0 does not crash anymore now and seems to work:
1. Reinstall v6.73.0.
2. Run it, a couple of "Send crash report" windows appeared, I did not send them. The app worked fine.
3. Open all the settings (wanted to record a backup).
4. Press "Reset preferences and restart...", but cancel without actually resetting preferences.
5. Update via the app.
6. Run v7.0.0. It works. 🤷

**Comment by alexandrpaliy** [comment]
> Could you please try running this command in Terminal.app? defaults delete com.lwouis.alt-tab-macos. It will reset all preferences for AltTab. Then running AltTab again. Does it still crash the same way?

1. Removed 6.73.0
2. Executed `defaults delete com.lwouis.alt-tab-macos`
3. Installed 7.0.0

And now it works, no crashes anymore. Thank you.

**Comment by SirPole** [comment]
Can confirm as well, did it the same way as @vmironovich 😄

**Comment by lwouis** [comment]
Based on your feedback, it seems that the key step is "downgrading to 6.73.0 first and skipped some "send crash report" pop-ups"

Maybe the issue is:
* v6.73.0 crashed, and was not opened afterwards, so crash popup was not shown
* v7.0.0 is installed
* v7.0.0 is opened. It finds the crash reports from v6.73.0, but crashes trying to handle them
* At this point the app is crashing on launch always
* Opening v6.73.0 again allows to click the crash popups, which purges the crash reports
* At this point v6.73.0 and v7.0.0 work without issue

If this speculation is correct, I'm sure there is anything we could do about it.

The only change I can think of is that AppCenter will be shut down next year, and that means we'll have to remove AppCenter from AltTab before that happens. That will stop this issue.

**Comment by SirPole** [comment]
I haven't had any crash report popup, to be honest, I have the option disabled (it's nothing personal, I just do it automatically for everything). Do you think it's possible, that when it was closed for the automatic update, it was considered a crash?

**Comment by lwouis** [comment]
> when it was closed for the automatic update, it was considered a crash

I'm sorry, I don't understand what you mean here 🙇

**Comment by DvdGiessen** [comment]
> I wonder if this issue is happening only with v7.0.0. You're also on macOS 12.7.6 which is quite old. Maybe that combination of versions has issue?

Reporting in from an even older macOS version. I encountered the crash of v7.0.0 on Catalina (10.15.7, released in 2022) running on a late 2012 model iMac. v6.73.0 still works well on this system.

Let me start by saying that I think it's very reasonable that my old system is no longer supported! But presumably the `sparkle:minimumSystemVersion` should be updated, and perhaps it can be mentioned in the changelog.

Some observations about the crash: It seems to crash on an unsupported instruction. Presumably the compiler target was bumped; or a new/updated dependencies have newer requirements.

The crash happened somewhere after the initial check for permissions. I would get those when launching through my terminal (since my terminal lacked those permissions), and after those were granted AltTab crashed.

```
$ /Applications/AltTab.app/Contents/MacOS/AltTab
Illegal instruction: 4
```

And I should say, congrats on the new version! On my other (more modern) systems the new version runs fine, and the updated preferences do look very nice!

**Comment by lwouis** [comment]
> Let me start by saying that I think it's very reasonable that my old system is no longer supported! But presumably the sparkle:minimumSystemVersion should be updated, and perhaps it can be mentioned in the changelog.

I'd like to clarify that we did not intentionally break compatibility. The app still claims to support macOS >= 10.12. It the latest update doesn't work on old macOS version, it is a bug, not something we intended 🙇

**Comment by RichDom2185** [comment]
I am on macOS Sequoia 15.0.1 and AltTab also keeps crashing after updating to v7.0.0.

Logs on Console.app don't seem to show much:

<img width="1206" alt="image" src="https://github.com/user-attachments/assets/72289160-2fb6-4209-a3da-eac0b374ec9e">

**Comment by lwouis** [comment]
@RichDom2185 your logs mention "MDM" which is often software added on employees machines by their employer to control things.

Perhaps your company had whitelisted AltTab v6.73.0, but has not whitelisted v7.0.0 yet. The "crashing" would then be the MDM software preventing AltTab v7.0.0 from launching?

**Comment by neobrain** [comment]
Had the same issue upon updating. I fixed it by downgrading to 6.73.0, starting and closing it once, and then reinstalling 7.0.0 (both by downloading the respective zips from https://github.com/lwouis/alt-tab-macos/releases).

**Comment by RichDom2185** [comment]
> @RichDom2185 your logs mention "MDM" which is often software added on employees machines by their employer to control things.
> 
> Perhaps your company had whitelisted AltTab v6.73.0, but has not whitelisted v7.0.0 yet. The "crashing" would then be the MDM software preventing AltTab v7.0.0 from launching?

@lwouis I'm on a personal device though, and I've never installed any company-related applications on it&hellip;

Regardless, `isMDMAllowed` is true so shouldn't it not affect?

> Had the same issue upon updating. I fixed it by downgrading to 6.73.0, starting and closing it once, and then reinstalling 7.0.0 (both by downloading the respective zips from https://github.com/lwouis/alt-tab-macos/releases). (I.e. there's no need to delete defaults or reset the application)

@neobrain this did the trick, thank you so much!

**Comment by rastytheamateur** [comment]
> Had the same issue upon updating. I fixed it by downgrading to 6.73.0, starting and closing it once, and then reinstalling 7.0.0 (both by downloading the respective zips from https://github.com/lwouis/alt-tab-macos/releases). (I.e. there's no need to delete defaults or reset the application)

Had very similar issue (maybe even the same) and this has done the trick, it is working now... Thanks!

**Comment by hicaicai** [comment]
Exactly the same problem, my system is also mac OS, 12.7.5

**Comment by umaranis** [comment]
I have the same issue... upgraded to 7.0.0 and the app doesn't work anymore.

**Comment by phendan** [comment]
Hmm, I tried installing 6.73.0 again, and it does open and prompt me to send a crash report, but I've gone through the cycle of doing that and then updating to 7.0.0 again multiple times now and it still always crashes, unfortunately.

**Comment by jameswei** [comment]
Hi all, I encountered the same issue after upgrade to v7.0.0.
Just share what I tried and the issue got fixed.
Besides 'Screen & System Audio Recording' permission, I also add AltTab to the 'System Audio Recoding Only' permission list. It worked! but it was weird, the former permission definitely include the latter one.
<img width="472" alt="image" src="https://github.com/user-attachments/assets/19034ba6-770d-4cc0-85d1-80e1c9c23a05">

**Comment by GitMalk** [comment]
Version 7.0.0 did not start on MacOS 12.7.6. Switched to version 6.73.0 which does the job.

**Comment by aruncodes** [comment]
I had the same issue on Mac 14.7 Sonoma. After upgrade to 7.0.0, app refused to open and crashes. All I did was execute this command and re-launched. It started working for me afterwards.
```
defaults delete com.lwouis.alt-tab-macos
```

**Comment by xdanik** [comment]
> I had the same issue on Mac 14.7 Sonoma. After upgrade to 7.0.0, app refused to open and crashes. All I did was execute this command and re-launched. It started working for me afterwards.
> 
> ```
> defaults delete com.lwouis.alt-tab-macos
> ```

Same here. This resolved the issue for me.

**Comment by espadrine** [comment]
I’ll add my reproducible steps (on macOS 14.7) after what I think is a full reset, since I don’t think I quite match [the conditions listed](https://github.com/lwouis/alt-tab-macos/issues/3653#issuecomment-2404536339).

1. In Settings > Accessibility: Delete AltTab. (In my experience, setting it is what caused the crash.)
2. In Settings > Screen & Audio recording: Delete AltTab.
3. rm -rf /Applications/AltTab.app/
4. [Download v7](https://github.com/lwouis/alt-tab-macos/releases/download/v7.0.0/AltTab-7.0.0.zip). Unzip, drag-and-drop to /Applications.
5. Launch AltTab through ⌘Space. “Are you sure you want to open it?” > Open. Three windows appear: “AltTab needs some permissions”, “AltTab would like to record this computer's screen and audio”, “Send a crash report”.
6. Click Don't Send (the crash report).
7. In the “AltTab needs some permissions”, click on each button (Screen Recording > toggle AltTab, “AltTab may not be able to record the contents of your screen until it is quit” > Later; then Accessibility > toggle AltTab). The “AltTab needs some permissions” page disappears.
8. Launch AltTab through ⌘Space. Nothing happens.

When I do `/Applications/AltTab.app/Contents/MacOS/AltTab` after that, I get the situation of step 6, but the settings are set.

But `defaults delete com.lwouis.alt-tab-macos` works.

**Comment by lwouis** [comment]
Thank you @espadrine for the thorough message

I was able to reproduce parts of your experience, but I needed to add another step:

* After removing AltTab.app, Running `tccutil reset All com.lwouis.alt-tab-macos`. This remove the AltTab rows from the `System Settings > Privacy & Security` sections. Note that at this point, my System Settings panel got broken (see [video](https://github.com/user-attachments/assets/8becd92d-abf8-4cd6-849c-71a7397cedcc)) showing once again that macOS permission system is not the most robust subsystem.
* Somehow I got a crash report dialog this time, for the first time in months. I sent it, but couldn't see it in AppCenter. Looks like AppCenter has issues. I wonder if it's not an AppCenter crash being reported, in the first place
* After I give permissions, AltTab runs correctly. I can't reproduce the part where it crashes.
* Now if I redo the whole procedure, I don't see the Crash Report dialog when I launch the freshly installed AltTab.app

**Comment by wilky761** [comment]
v7.0.0 and v.7.0.1 are both crashing so I've gone back to the last stable version - v6.73.0. 

I'm on macOS 12.7.6......happy to share my crash report if it helps. 

Thanks

**Comment by AlexZeitler** [comment]
> I'm on macOS 12.7.6..

Same here

**Comment by frypf** [comment]
I'm also on Monterey and also unable to fix the issue via any of the suggested workarounds. Regardless of resetting tccutil permissions or deleting AltTab's prefs, v7+ fails to launch. The permissions checker correctly shows, but once I've granted permissions AltTab just quits itself silently and doesn't reopen.

If I roll back to 6.73.0, the "Send Report" dialogue shows up fine. However, subsequently clean-quitting 6.73.0 and reinstalling / reopening either of the newer versions via terminal only shows `"Exiting after receiving signal" 5` the first time, without the `…Cannot find image…` part. Subsequently reopening the later versions shows the same `[AppCenterCrashes] WARNING: … Cannot find image for …` message that others have reported.

**Comment by lwouis** [comment]
On v7.0.1, I see some crashes from macOS 12.7.6 and other 12.x versions. I don't see crashes for that particular crash, from more recent macOS version.

<img width="931" alt="image" src="https://github.com/user-attachments/assets/89ea39ea-2f74-40f5-b733-df3db5b875cd">

This is the crash:

<img width="1406" alt="image" src="https://github.com/user-attachments/assets/0a975e31-de58-4553-afe5-10d0691d2bef">

Looking at the code, I don't see anything that could go wrong. The fact that only macOS 12.x seems to have the issue makes it suspicious. Some of the `NSSegmentedControl` API require 10.13. We only use 10.12 compatible APIs, but maybe Apple made a mistake?

It's really hard to know without being able to run it on macOS 10.12. I used to have VMs for this, but on my M2 mac, older VMs are no longer possible. I think they broke old VMs support with Catalina back then.

**Comment by Allsochen** [comment]
> <img alt="image" width="1406" src="https://private-user-images.githubusercontent.com/106195/375777403-0a975e31-de58-4553-afe5-10d0691d2bef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MTkwMDksIm5iZiI6MTcyODcxODcwOSwicGF0aCI6Ii8xMDYxOTUvMzc1Nzc3NDAzLTBhOTc1ZTMxLWRlNTgtNDU1My1hZmU1LTEwZDA2OTFkMmJlZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMlQwNzM4MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYWVjZjM4Njc1NGY2NDdlN2IxMDc2YjkyMjNhMzM5MjhjNjlmNTI0YzFjYTQzODc4MTViMzhlNGQ4NmQ3YjhiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.lMiSKUnjd3dNFgQMQKNCkESm8QNawUM6Wfq47835O-E">
> Looking at the code, I don't see anything that could go wrong. The fact that only macOS 12.x seems to have the issue makes it suspicious. Some of the `NSSegmentedControl` API require 10.13. We only use 10.12 compatible APIs, but maybe Apple made a mistake?
> 
> It's really hard to know without being able to run it on macOS 10.12. I used to have VMs for this, but on my M2 mac, older VMs are no longer possible. I think they broke old VMs support with Catalina back then.

- Maybe it's the `systemSymbolName` causing it?
- Maybe it's caused by the version supported by `NSSegmentedControl`. I see that it is supported by 10.3+
![QQ_1728719260159](https://github.com/user-attachments/assets/9628d3aa-bdae-48a5-b75d-1f655078189c)

**Comment by Allsochen** [comment]
Hi, everbody, currently v7.0.2 has tried to fix the problem, we can upgrade and try it.

**Comment by frypf** [comment]
> Hi, everbody, currently `v7.0.2` has tried to fix the problem, we can upgrade and try it.

Seems to work for me - I upgraded via the inbuilt "Check for updates…" and `v7.0.2` opens without issue. Thanks 👍

**Comment by omarpach** [comment]
Hi, sorry for the late reply. Thanks, @lwouis for your hard work, as @Allsochen mentioned, upgrading to `v7.0.2` fixed it for me. Now I'm able to open and use the app with zero issues so far. I was only prompted to send a crash report, which I did, and it caused zero issues.
