### ISSUE TITLE
7.0.0 release crashes right after launching

### ISSUE THREAD

**Issue by alexandrpaliy** [lwouis/alt-tab-macos#3654]
**Describe the bug**

As soon as I updated the app to the 7.0.0 release, I can't use the app at all.
During the update it closed the old process instance but (apparently) failed to launch the new one.
If I try launching it via the MacOS UI - nothing happens at all. No pop-ups, no errors, nothing.
If I try launching it via a terminal - I get this:
```
$ /Applications/AltTab.app/Contents/MacOS/AltTab
2024-10-10 10:19:12.598 AltTab[75732:33016187] [AppCenterCrashes] WARNING: +[MSACErrorLogFormatter formatStackFrame:report:]/467 Cannot find image for 0x19ec47154
"Exiting after receiving signal" 5
```

The difference between this bug report and the https://github.com/lwouis/alt-tab-macos/issues/3653 one is the fact that I don't need to press anything at all - the app crashes right away.

**Screenshots / video**

-

**Steps to reproduce the bug**

1. Update the app to the 7.0.0 release
2. Launch the app

**Your environment**

* AltTab version: 7.0.0
* macOS version: Sonoma 14.6.1 (Apple M2 Pro - an "arm64" one)

Other relevant info: 
* I usually use two-display configuration (macbook's display + an external one), but the app crashes even if I disconnect the external display.

**Comment by lwouis** [comment]
Let's keep the discussion going in one thread: https://github.com/lwouis/alt-tab-macos/issues/3653 👍
