### ISSUE TITLE
Why is ´mouse follows focus´missing after the newest update?

### ISSUE THREAD

**Issue by qns7** [lwouis/alt-tab-macos#3656]
Hey there,

this option (title) is missing now, right? Is this intentional or a bug? The release notes didn't say that the feature was dropped.

Best regards Q

**Comment by Allsochen** [comment]
Hey, I'm very sorry. During the refactoring process, we thought that few users would use this option and that it interfered with the user's normal behavior, so we decided to delete the option. If there are many users who give feedback, we will reconsider adding it back.

**Comment by qns7** [comment]
> Hey, I'm very sorry. During the refactoring process, we thought that few users would use this option and that it interfered with the user's normal behavior, so we decided to delete the option. If there are many users who give feedback, we will reconsider adding it back.

I also use yabai extensively and it has this option, but with the yabai one I have problems with some apps: for example zoom.us; and your implementation was flawless and worked without any problems on all my apps. I guess I then have to live with the yabai feature and make it somehow togglable for apps that don't work with it.

Thanks for the fast answer.

**Comment by Allsochen** [comment]
OK, I understand, we will revisit this feature later.

**Comment by lwouis** [comment]
Closing this ticket for now. As @Allsochen mentioned, let's revisit this later after we see the general reaction to the latest update 👍
