### ISSUE TITLE
7.0 Titles style width issue

### ISSUE THREAD

**Issue by linking2014** [lwouis/alt-tab-macos#3661]
7.0 is really great. Thank you so much for your work.
after upgrade to 7.0, when use Titles style, the window width is weird: 
1. on my main screen (horizontal orientation),  the window width is too big
2. on my side screen (vertical orientation), the window width is too small, even can't see a word

hope we can customize window width like 6.x. 

![19991728556967_ pic_hd-tuya](https://github.com/user-attachments/assets/91789804-5030-4abf-96fd-c6d0dc1d0e02)
![20001728556976_ pic_hd-tuya](https://github.com/user-attachments/assets/9b491714-3f8a-4b89-a9d4-666d353c3312)

**Comment by lwouis** [comment]
Let's keep the conversation going in this thread: https://github.com/lwouis/alt-tab-macos/issues/3658 👍

**Comment by Allsochen** [comment]
Can you provide more detailed information? For example, screen resolution, screen settings, etc. When developing v7.0, we tested the horizontal screen. Currently, the horizontal screen performance is normal here.

![QQ_1728623332073](https://github.com/user-attachments/assets/4403d3e4-df99-4fc0-909b-5df4e29fd428)

**Comment by linking2014** [comment]
> Can you provide more detailed information? For example, screen resolution, screen settings, etc. When developing v7.0, we tested the vertical screen. Currently, the horizontal screen performance is normal here.
> 
> ![QQ_1728623332073](https://private-user-images.githubusercontent.com/5805484/375632621-4403d3e4-df99-4fc0-909b-5df4e29fd428.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MjY2NDUsIm5iZiI6MTcyODYyNjM0NSwicGF0aCI6Ii81ODA1NDg0LzM3NTYzMjYyMS00NDAzZDNlNC1kZjk5LTRmYzAtOTA5Yi01ZGY0ZTI5ZmQ0MjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTFUMDU1OTA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDY2OWUyZTg2ZmVjNjFkNzc5ODFiMGRkZmYwOTkyMzQ2MGFkOTQ4Yjg0ODVlM2U4MDU5ZDYxNDJhYzU1ZGNlYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.NNgo-lV6DOhhi5k9qXZGkrYKwM43E62oZVhm26M7KXA)

after have a test, i know how to reproduce:
1. quit app
2. open app on side vertical screen, press cmd+tab the picker window is ok
3. focus the main horizontal screen, press cmd+tab the picker window is ok
4. focus back the side vertical screen, press cmd+tab the picker window become very narrow

**Comment by Allsochen** [comment]
> hope we can set picker window a fixed width, on 5k screen picker window is too wide. the current width calculation method may cause similar problems on wide screen like 21:9 screen.

This suggestion is very nice and can be considered for later version improvements.
这个建议非常好，后续的版本改进可以考虑下

**Comment by Allsochen** [comment]
> after have a test, i know how to reproduce:
> 
> quit app
> open app on side vertical screen, press cmd+tab the picker window is ok
> focus the main horizontal screen, press cmd+tab the picker window is ok
> focus back the side vertical screen, press cmd+tab the picker window become very narrow

Hey, I tried this step, both my monitors are normal, I can't reproduce it.
你好，我试了下这个步骤，我这里两个显示器都是正常，不能复现出来
