### ISSUE TITLE
Unable to set Cmd+Tab as activation shortcut after upgrading to v6.73.0

### ISSUE THREAD

**Issue by tieniu1** [lwouis/alt-tab-macos#3665]
Dear alt-tab-macos team,

I hope this message finds you well. I'm reaching out for some assistance with setting up the activation shortcut in the latest version of alt-tab-macos.

My system details:
- MacBook Pro 2017
- macOS 12.6
- alt-tab-macos version 6.73.0

I recently upgraded from version 6.70.0 to 6.73.0. Previously, I was using Cmd+Tab to activate alt-tab. However, after the upgrade, I'm unable to figure out how to set Cmd+Tab as the activation shortcut.

I would greatly appreciate any guidance on how to configure this shortcut in the new version. If possible, could you please provide screenshots of the configuration process? This would be immensely helpful.

Thank you very much for your time and assistance. I truly appreciate the work you've put into this fantastic tool.

**Comment by lwouis** [comment]
Hi,

Your previous settings should be unchanged. So it you set the shortcut to command+tab, it should still work.

Could you please share a screenshot of Preferences > Controls?

Thank you 🙇

**Comment by tieniu1** [comment]
> Hi, 嗨，
> 
> Your previous settings should be unchanged. So it you set the shortcut to command+tab, it should still work.您的先前设置应保持不变。因此，如果您将快捷键设置为 command+tab，它应该仍然有效。
> 
> Could you please share a screenshot of Preferences > Controls?您能分享一下“偏好设置 > 控制”的截图吗？
> 
> Thank you 🙇 谢谢 🙇

Sorry, I wasn't clear in my expression. I didn't upgrade directly; I first uninstalled the old version and then installed the new version.

![image](https://github.com/user-attachments/assets/65483d23-5377-41bc-bb86-f175ea0b4fd6)

**Comment by Allsochen** [comment]
![QQ_1728647777111](https://github.com/user-attachments/assets/b5d4ffc6-1bf5-458d-8b22-cf509e87bb37)

你重置一下配置试试，看是否OK
Reset the settings and see if it works.

**Comment by lwouis** [comment]
Could you please try out the latest v7.0.2 and see if the issue is fixed?

Thank you 🙇

**Comment by qns7** [comment]
> Could you please try out the latest v7.0.2 and see if the issue is fixed?
> 
> Thank you 🙇

I uninstalled alt-tab via the AppCleaner, reinstalled it with home brew (to v7.0.2 of course) and then 'restore and restarted' it for good measure even though the settings where gone anyway.
And after that it seems to work flawlessly again.
If the bug occurs again I edit this post. 

Thanks alt-tab-Team: You are truely awesome! <3

**Comment by sacrificeme** [comment]
Have the same problem. Command + Tab does not work. Option + Tab works. Tried Command + S also works, something odd with Command + Tab.

**Comment by qns7** [comment]
Have you tried what I answered in the duplicated thread? Since then it works on my machine again and I made several restarts then.Am 13.10.24 um 19:50 schrieb Yakov Shipilov
                
            
            
                
                    Von: "Yakov Shipilov" ***@***.***>Datum: 13. Oktober 2024An: "lwouis/alt-tab-macos" ***@***.***>Cc: "Comment" ***@***.***>,"qns" ***@***.***>Betreff: Re: [lwouis/alt-tab-macos] Unable to set Cmd+Tab as activation shortcut after upgrading to v6.73.0 (Issue #3665)
                
                
Have the same problem. Command + Tab does not work. Option + Tab works. Tried Command + S also works, something odd with Command + Tab.

**Comment by sacrificeme** [comment]
Uninstalled, just moved app to trash bin. Reinstall from homebrew. Reset preferences. Without restart, will try restart and update thread.

**Comment by sacrificeme** [comment]
Restart made the trick, command + tab works again.

**Comment by tieniu1** [comment]
> Could you please try out the latest v7.0.2 and see if the issue is fixed?
> 
> Thank you 🙇

https://github.com/lwouis/alt-tab-macos/issues/3665#issuecomment-2408617847

**Comment by lwouis** [comment]
It seems to happen to a few people. Thus my guess would be:

* Either people affected by the issue has complex setups. For instance, having BTT, Karabineer, and other Input Capturing apps, or external keyboards, etc. And those mess up with AltTab reading command+tab.
* Or AltTab has issues disabling the built-in command+tab. We use a private API to do it. Otherwise, the OS will always capture the shortcut first, and display the built-in switcher. I'm not sure why it would not work everytime. It would make sense that restarting AltTab would fix it though, since it would reapply the private API to disable it.

Thank you 🙇

**Comment by sacrificeme** [comment]
Makes sense, I use Keyboard Logitech MX Mechanical Mini and it comes with Logi+ software, which also try to catch input before all :) Probably it's the root cause.

**Comment by tieniu1** [comment]
> It seems to happen to a few people. Thus my guess would be:
> 
> * Either people affected by the issue has complex setups. For instance, having BTT, Karabineer, and other Input Capturing apps, or external keyboards, etc. And those mess up with AltTab reading command+tab.
> * Or AltTab has issues disabling the built-in command+tab. We use a private API to do it. Otherwise, the OS will always capture the shortcut first, and display the built-in switcher. I'm not sure why it would not work everytime. It would make sense that restarting AltTab would fix it though, since it would reapply the private API to disable it.
> 
> Thank you 🙇

I am using a Niz keyboard and I'm also using Karabiner.
