### ISSUE TITLE
AltTab doesn't focus next window when I move my mouse cursor to another monitor

### ISSUE THREAD

**Issue by MartinZemanik** [lwouis/alt-tab-macos#3668]
**Describe the bug**

When I'm using AltTab while having multiple monitors, AltTab isn't behaving as I would expect when I move my cursor to another monitor.

**Screenshots / video**

https://github.com/user-attachments/assets/82c83003-df64-4df1-8b68-f845e38e5fa9

**Steps to reproduce the bug**

(Follows the video above. Monitor 1 is on the left and Monitor 2 is on the right)

1. Open Window 1 and Window 2 on Monitor 1 (Window 2 is in the background)
2. Open Window 3 and Window 4 on Monitor 2 (Window 4 is in the background)
3. Move your mouse cursor to Monitor 1
4. Focus Window 1 on Monitor 1
5. Activate AltTab - Window 2 is focused as expected
6. Activate AltTab - Window 1 is focused as expected
7. Move your mouse cursor to Monitor 2, but don't click anything
8. Activate AltTab - Window 3 is still focused
9. Active AltTab again - only now is the Window 4 focused

**Expected behavior**
In step 8, I would expect that Window 4 on Monitor 2 would be focused

**Your environment**

macOS Sequoia 15.0.1 (24A348)

* AltTab version: 7.0.1
* macOS version: Sequoia 15.0.1 (24A348)
* Other relevant info: using multiple monitors

**Comment by lwouis** [comment]
Hi,

Thank you for the detailed ticket.

I don't think this should be considered a bug.

It's all about the 0:06 time:
<img width="145" alt="image" src="https://github.com/user-attachments/assets/accf0e2e-3689-4a5d-8e72-15edc77d98bb">

At this point, we present the switcher in the context of Monitor 2, which hides window 1 and 2.

You argue that in that context, AltTab should consider that window 3 is "recent"/"focused" and that AltTab should already be on window 4 when it appears.

However, at this point, window 2 is focused. The most recent window to jump to next, on monitor 2, is window 3.

I think the behavior is correct. I understand you may want a different workflow. However, I think other people will want the current one. They would be surprised if window 3 is not offered, even though it's not focused and it's the most recent window on that screen.

Thank you 🙇

**Comment by MartinZemanik** [comment]
Hey @lwouis, thanks for the response. I understand your argument, but I don't really understand why would anyone prefer the current behavior. When Window 3 is already visible on Monitor 2, activating AltTab doesn't do anything except focusing that window, which I can do simply by clicking.

Would it be possible to consider controlling this by some setting?
