### ISSUE TITLE
Suggestion: Coloured circles on "Titles" layout

### ISSUE THREAD

**Issue by pojka** [lwouis/alt-tab-macos#3671]
Firstly, awesome updates!

I really like the new "Titles" layout however it's missing one thing - the "coloured circles" - it's really valuable to be able to close apps from AltTab directly and I wish it was available in this layout as well 🙏

**Comment by Allsochen** [comment]
The UI display of `colored circles` in `Titles` mode is not very good. You can currently turn it off by pressing Alt/Cmd+W/Q on the keyboard or by clicking the middle mouse button.
