### ISSUE TITLE
AltTab shows one icon per application, instead of one icon per window

### ISSUE THREAD

**Issue by ymost** [lwouis/alt-tab-macos#3688]
**Describe the bug**

After upgrade to 7.0.X, AltTab shows one icon per application, instead of one icon per window like it did before. It basically reproduced the native cmd+tab behavior.

**Screenshots / video**

I can't take a screenshot of the AltTab UI, since it disappears when I try to take a screenshot.
It basically looks like the native cmd-tab UI, except the icons are a bit bigger and it has titles.
For example: I have several windows open in Google Chrome, but the AltTab UI only shows one icon for Google Chrome, instead of an icon per each open window.

**Steps to reproduce the bug**

1. Have at least one app with more than one window open.
2. Click option + tab.

**Your environment**

* AltTab version: 7.0.2
* macOS version: Sonoma 14.6

**Comment by lwouis** [comment]
Hi,

There are new preferences to support this, in v7.0.0. It's surprising that you got this experience after the update, without touching the Preferences. Or maybe you did?

In any case, if you want to see all windows, you can set it in Preferences > Appearance 👍 

Please explore that tab. You'll find what you need.

Thank you 🙇

**Comment by ymost** [comment]
I did not touch the preferences, except for the "size" part.
Which option will allow me to get an item per each window, instead of an item per each app?

![image](https://github.com/user-attachments/assets/d4a848c1-3240-441e-800d-1ac279176f31)

**Comment by Allsochen** [comment]
![QQ_1728805799023](https://github.com/user-attachments/assets/2eaa6c37-3755-4aee-9170-cc4f92359c84)
