### ISSUE TITLE
Releasing CMD doesn't always switch to the selected window, Window preview remains open

### ISSUE THREAD

**Issue by rcwmt** [lwouis/alt-tab-macos#3689]
**Describe the bug**

This problem randomly occurs for me, so very hard for me to find the reason, could be a bug but could also be something on my end.

When the problem occurs (maybe every 10-20th time of using CMD+TAB), I press CMD + TAB, the window switcher opens, I click TAB to go to the window I want to switch to, but after releasing the keys, nothing happens. 

The "After release" - "Focus selected window" is turned ON. 

I have this problem already since July with older Alt-Tab versions and I always hope with the next update it fixes itself 😃 I will update in case I find more information.

**Your environment**

* AltTab version: 7.0.2
* macOS version: Sequoia 15.0.1

**Comment by lwouis** [comment]
https://github.com/lwouis/alt-tab-macos/issues/3567
