### ISSUE TITLE
Start Minimized on Launch

### ISSUE THREAD

**Issue by sx7en** [lwouis/alt-tab-macos#3693]
**Is your feature suggestion related to a problem? Please describe.**
The application opens the settings window on launch when you select "Open at Launch", adding clutter to the windows when your mac has started

**Describe the solution you'd like**
If possible, can you make an option so that when the application is open at launch the application would be minimised

**Comment by lwouis** [comment]
Hi,

At launch, the preferences window doesn't open. It opens if you try to open AltTab when it's already opened. Thus, I suspect that you have AltTab launching twice, and the second time opens the preference window.

Did you perhaps add AltTab to Login Items and at the same time check the "Launch at Login" checkbox in AltTab's preferences?

If AltTab is launched once, it will not open its preference panel.

Thank you 🙇
