### ISSUE TITLE
Alt-Tab Displays Windows from All Desktops (Workspaces)

### ISSUE THREAD

**Issue by serdarsen** [lwouis/alt-tab-macos#3698]
**Describe the bug**

Alt-Tab displays windows from all desktops (workspaces) instead of filtering by the current workspace.

**Screenshots / video**

**Steps to reproduce the bug**

1. Open 10 desktop workspaces.
2. Open a Chrome window on desktop 10 and a Firefox window on desktop 3.
3. While on any desktop, press Alt + Tab.
4. AltTab for macOS displays all windows without filtering based on their respective desktops.

**Your environment**

* AltTab version: 7.0.2
* macOS version: Sequoila 15.0.1

**Comment by lwouis** [comment]
Hi,

Yes, AltTab shows all windows by default. You can customize everything in Preferences > Controls. For example:

<img width="562" alt="image" src="https://github.com/user-attachments/assets/ded59438-c004-4ed1-9830-93f9ad633d78">

Thank you 🙇

**Comment by siikamiika** [comment]
This setting was set to an empty value for me recently and behaved as if it was set to "All Spaces". I used to have it only show windows from the current space. I think it might be related to the migration of the `spacesToShow` preference in https://github.com/lwouis/alt-tab-macos/pull/3468 but I'm not sure. Not a big issue but I hope this helps someone

**Comment by siikamiika** [comment]
@lwouis I didn't check it when I upgraded but according to the data in `~/Library/Application Support/com.lwouis.alt-tab-macos/com.microsoft.appcenter/Logs.sqlite` I had 6.72.0 2 days ago and the next version is 7.0.2

**Comment by eyalzek** [comment]
Currently seeing this behavior on a fresh install of version 7.23.0, setting is set to `Show windows from Spaces "Visible Spaces"` yet I'm seeing windows from _all_ spaces instead...
Tried toggling back and forth as suggested by the commenter before me, but that didn't work.
