### ISSUE TITLE
Allow a different keyboard shortcut for switching between current app windows

### ISSUE THREAD

**Issue by borna761** [lwouis/alt-tab-macos#370]
**Is your feature suggestion related to a problem? Please describe.**
First of all, I am so happy to have found alt-tab, it is indeed great. One thing HyperSwitch does well is to have two separate settings for allowing switching between all windows and the current app's windows:
![image](https://user-images.githubusercontent.com/9056534/84154076-a0bd4000-aa34-11ea-8822-bedd5391823e.png)

From what I have found, alt-tab only seems to allow one or the other, and not both:
![image](https://user-images.githubusercontent.com/9056534/84154151-bcc0e180-aa34-11ea-97f2-ec147751a904.png)

**Describe the solution you'd like**
It would be nice to be able to have a separate keyboard shortcut that would allow for switching only between the current app's windows, similar to HyperSwitch.

**Describe alternatives you've considered**
For now, I'm running both alt-tab and HyperSwitch, which seems redundant.

**Comment by lwouis** [comment]
Hi @borna761! Thanks for the suggestion!

Turns out this very idea has already been suggested in #237. I'm going to close this ticket as duplicate. Please catch up on the discussion in #237, and follow there for progress 👍

**Comment by borna761** [comment]
My bad! I thought I had read through all the created issues properly, turns out I hadn't!

**Comment by lwouis** [comment]
@borna761 it is my fault; there are too many issues! I'm happy that there are only 2 or 3 bugs left, and everything else is an enhancement suggestion. However, as I try to be very open to ideas, it can be hard to navigate the big list of suggestions. That's why I opened #351 but I haven't taken time yet to open the discussion there
