### ISSUE TITLE
Request: Support a unique Appearance per Shortcut

### ISSUE THREAD

**Issue by Shreebz** [lwouis/alt-tab-macos#3704]
**Is your feature suggestion related to a problem? Please describe.**
I'd like Shortcut 1 CMD+Tab to show App Icons (Appearance 1). This would be similar to native macOS behavior.

For shortcut 2, I'd like to use a different Appearance. Shortcut 2 is CMD+` to show active app windows with window thumbnails (Appearance 2).

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
None

**Comment by lwouis** [comment]
Hi,

It's always hard to decide which setting should be global vs per-shortcut. We base this choice on usage. If many users would want per-shortcut, then we do that. If it's only a few, we keep it global.

Having settings per-shortcut is quite complex for most users to understand, thus we limit them. This idea here is interesting. However, I would expect niche usage of it, so unfortunately it should be closed for now.

If more people ask for it, we'll of course reconsider.

Thank you 🙇
