### ISSUE TITLE
Request: Change XY placement on screen

### ISSUE THREAD

**Issue by Shreebz** [lwouis/alt-tab-macos#3705]
**Is your feature suggestion related to a problem? Please describe.**
I'd like to change the placement of Alt-Tab switcher from the center of the screen. For instance, Keyboard Maestro has an application switcher, and that appears in the upper quarter of the screen instead of the center. 

**Describe the solution you'd like**
I'd like to have some offset values to play with XY placement on-screen.

**Describe alternatives you've considered**
None

Thanks!

**Comment by lwouis** [comment]
Hi,

AltTab before v7.0.0 used to be centered at 1/3 vertically. Standard Apple centering, or like book titles do. There was [criticism of it](https://github.com/lwouis/alt-tab-macos/issues/585), and we finally moved to 1/2 centering with v7.0.0.

I don't think we'll consider adding a setting for this, and it's very niche.

Thank you 🙇
