### ISSUE TITLE
Why not use SwiftUI to implement the new preferences panel?

### ISSUE THREAD

**Issue by GanZhiXiong** [lwouis/alt-tab-macos#3707]
> [7.0.0](https://github.com/lwouis/alt-tab-macos/compare/v6.73.0...v7.0.0) (2024-10-09)
Features
major rehaul of the preferences! ([6d97cbd](https://github.com/lwouis/alt-tab-macos/commit/6d97cbd)), closes https://github.com/lwouis/alt-tab-macos/issues/351
BREAKING CHANGES
The old preferences panel has been replaced with a brand new one
Preferences are now much simpler, full of visual illustrations, and should provide a much better experience. Pick between 3 styles (thumbnails, app-icons, titles), sizes, dark/light themes, high visibility options, and more!

SwiftUI is recommended by Apple, so why not use it?

**Comment by lwouis** [comment]
SwiftUI is only available from macOS 10.15. Currently, AltTab can be used from macOS 10.12.

We try to support as many users as possible, that's why we haven't used SwiftUI.

Thank you
