### ISSUE TITLE
Let me select my preferred language

### ISSUE THREAD

**Issue by Towelie90** [lwouis/alt-tab-macos#3717]
It seems that AltTab uses the system language. In my case, German. But the German translation is "below all pig" (bad, literally translated). I would prefer to select English, so that I can understand, what you mean be certain terms.

**Comment by lwouis** [comment]
Hi,

MacOS offers a [built-in way to change the language of specific apps](https://www.makeuseof.com/how-to-change-language-settings-for-mac-apps/), while keeping the OS is your native language. You can use that right now to switch AltTab to English.

Furthermore, we'll soon add Language Switcher in the preference panel. There is an [ongoing PR](https://github.com/lwouis/alt-tab-macos/pull/3687).

Finally, some new terms have been translated using Google Translate for v7.0.0. If you know better translations, please consider [going to poeditor and updating the current translations](https://poeditor.com/join/project/8AOEZ0eAZE). It will then ship in the next release 👍 

Thank you 🙇
