### ISSUE TITLE
Windows switcher position

### ISSUE THREAD

**Issue by webmasterunac** [lwouis/alt-tab-macos#3722]
After the update. I noticed that windows switcher is in the middle of the screen, and there's no option to put it back a little bit higher like previous versions. The position in the middle is uncomfortable to eyes when you have a big iMac screen. 
Here's two screenshots:

_This one is the 6.7.3 version_

<img width="1080" alt="Alt-tab 6 7 3 windows switcher position" src="https://github.com/user-attachments/assets/c8bd63bc-d206-48a0-974c-2290a9322771">

_This one is the 7.0.2 version_

<img width="1080" alt="Alt-tab 7 0 2 windows switcher position" src="https://github.com/user-attachments/assets/e5aa3869-56f7-42c1-8de7-bb0a6204dfb1">

**The solution that I suggest is a slider in settings to adjust the position of the windows switcher.**

**Comment by lwouis** [comment]
Hi,

Users have asked to have it centered: https://github.com/lwouis/alt-tab-macos/issues/585. So we centered it with v7.0.0.

Thank you 🙇
