### ISSUE TITLE
When the "don't show hidden windows" setting is enabled, hidden windows continue to be shown in the selection menu

### ISSUE THREAD

**Issue by Dfuz** [lwouis/alt-tab-macos#3723]
**Describe the bug**

When the "don't show hidden windows" setting is enabled, hidden windows continue to be shown in the selection menu.

**Screenshots / video**

https://github.com/user-attachments/assets/40dbfbcf-89fb-406c-95a7-f27b8c2d7e91

**Steps to reproduce the bug**

1. Go to 'Settings'
2. Click on 'Hide' in 'Show hidden windows'
3. Alt-tab
4. See windows for hidden apps

**Your environment**

* AltTab version: 7.0.2
* macOS version: 14.7
* Other relevant info: m3 pro, no external keyboard or monitor

**Comment by lwouis** [comment]
Hi,

The item on the right at the end is not a window. It's the App being open, with no window. That's how macOS works: you can have an app open, with no window open. It has the dot visible under its app icon, in the Dock.

AltTab shows you this. If you don't want to list it, you can toggle it in `Preferences > Appearance > Customize [...] > Hide apps with no open window`

Hidden windows are when you hide an app. You can press command+H for instance. The app is hidden, and its windows are hidden. This is what Preferences > Controls is referring to.

Thank you 🙇

**Comment by Dfuz** [comment]
Thanks!

**Comment by anukul** [comment]
Did this change recently? I believe the "Hide apps with no open window" setting used to be in the Controls tab 🤔 
It does not quite appear to be a customization of the thumbnails style as the other options do.

**Comment by lwouis** [comment]
@anukul it was always in Appearance. Since v7, it's been moved to the submenu Customize. The reasoning is that most people won't toggle it, so we bury it in a submenu for power users to find
