### ISSUE TITLE
Shift-Tab doesn't work properly

### ISSUE THREAD

**Issue by danilagalimov** [lwouis/alt-tab-macos#3730]
**Describe the bug**

Pressing Shift-Tab while holding Command (i.e. inside of the window selection) is causing selected window to continuously go back (as if Shift-Tab) was held.  

Steps to reproduce:

Preconditions: Press Command-Tab to bring window selection and release Tab while holding Command.

Scenario 1:
While holding Command, Press Shift+Tab once simultaneously (to go one window back)
Expected result - focus changes one window backwards.
Actual result - focus continuously moves back until first window is selected.

Scenario 2:
While holding Command, Hold shift and press Tab a few times(to go a few windows back)
Expected result - focus changes one window a tab is pressed.
Actual result - focus continuously moves back until first window is selected.

* AltTab version: 7.0.2
* macOS version: 14.5

**Comment by lwouis** [comment]
Hi,

Default backwards shortcut is alt+shift; no tab. Have you customized it? Please share a screenshot of `Preferences > Controls > Shortcuts when active...`

Thank you

**Comment by danilagalimov** [comment]
Hi,

Thanks for your quick reply. No, I didn't customize it although It looks like Alt+Shift is reserved for me (via karabinera) to switch the keyboard layouts, so I may need to figure it out.

**Comment by danilagalimov** [comment]
I've just changed the backwards key to Shift+Tab and it works perfectly for me - exactly as I want, thanks again!
