### ISSUE TITLE
Bring back multiple columns in title mode

### ISSUE THREAD

**Issue by lywlywly** [lwouis/alt-tab-macos#3737]
In previous version prior to 7.0, I was able to have two columns of windows in title mode by adjusting **max width** and **window max width**.
<img width="862" alt="Screenshot 2024-10-19 at 1 02 15 PM" src="https://github.com/user-attachments/assets/91f3d7ac-e56a-47b6-8252-b398d042c2b2">

However, after version 7.0, it seems that I can no longer adjust width of the whole popup or width of a single window tab.
<img width="665" alt="Screenshot 2024-10-19 at 1 08 09 PM" src="https://github.com/user-attachments/assets/2f652e4c-0a39-4d73-bd05-268e2608d56e">

Please correct me if there is a way to make two columns of windows.

This feature is important to me because I do not want to see the "screen capturing" icon in the menu bar, and therefore I only use window titles instead of thumbnails. In title mode, if there is only one column, too few windows can be displayed.

**Comment by lwouis** [comment]
Hi,

Please check out the build in https://github.com/lwouis/alt-tab-macos/issues/1082 to test the new degraded mode. It's designed to void the "screen capturing" icon.

Regarding having 2 columns, we'll consider supporting it in further versions. We are currently gathering feedback from the v7 launch.

Thank you 🙇

**Comment by ADTC** [comment]
> We are currently gathering feedback from the v7 launch.

Hi @lwouis is there an official channel to send feedback? I'm also looking to bring back the option to have 2 to 3 columns in Titles Mode.

Also, would like to see Advanced fine-grain control to adjust the maximum width (at least) and height as we used to be able to do in previous UI.

The new Settings UI is very cool, but it also removes a bunch of advanced options. In App Icons mode, I'm stuck with this (too wide):

<img width="1728" alt="Screenshot 2025-01-16 at 12 42 07 PM" src="https://github.com/user-attachments/assets/5bab17a2-c5b2-41b6-b01b-ef29f909462b" />

And in Titles mode, I have only one column. So there are two extremes and I can't find a balance. 😆

**Comment by lwouis** [comment]
@ADTC thank you. These topics are discussed here: https://github.com/lwouis/alt-tab-macos/issues/3882
