### ISSUE TITLE
In Titles Style, window list is collapsed on secondary monitor

### ISSUE THREAD

**Issue by lubomirfiala** [lwouis/alt-tab-macos#3744]
Window list is collapsed on secondary monitor and doesn't show any content. See photo.

It happens only on secondary monitor, i tried to tweak some random appearance settings and it happens only in Titles view, only after alt tab was once used on primary monitor. No other settings seems to interfere with this.

Sorry for photo, but i cannot take screenshot when alt tab is active.

![IMG_1273](https://github.com/user-attachments/assets/585db3e3-f3ec-4a4c-b5e9-bf4e04a720c2)

my other preferences looks like this:

![SCR-20241021-lhja](https://github.com/user-attachments/assets/b10ee025-cfb1-4636-b96d-bba99af0b3ac)

![SCR-20241021-lhjx](https://github.com/user-attachments/assets/ff5d0405-0899-4c82-a5c4-0767519ac4ff)

Edit: thank you for this view option, it's much better than tiles or icons :)

**Comment by lwouis** [comment]
Hi,

Thank you for sharing this issue.

Could you please share the resolutions of your 2 monitors? Maybe a picture of how AltTab looks on the other monitor, as well?

Thank you 🙇

**Comment by lwouis** [comment]
I wonder if this could be due to the display of this macbook having a notch? Maybe grabbing the dimensions of such a display creates the issue?

**Comment by emanueldima** [comment]
I tested some more and I see this reproduces when there is a big difference between the secondary screen resolution and the main screen resolution. E.g. it 
- reproduces at 3200x1800 (secondary) and 1728x1117 (main) 
- does not reproduce at 3200x1800 (secondary) and 2056x1392 (main)
- reproduces at 2560x1440 (secondary) and 1496x967 (main)
- does not reproduce at 2560x1440 (secondary) and 1728x1117 (main) 

It also only reproduces on the laptop screen, not on the secondary display, even when I set a high resolution on main and a low resolution on secondary.

**Comment by zawadzkipiter** [comment]
same here, also only bug appears on laptop screen - when secondary is big 4k screen.

**Comment by lwouis** [comment]
@zawadzkipiter is your laptop screen having a notch at the top?

@emanueldima

> reproduces at 3200x1800 (secondary) and 1728x1117 (main)

In that situation, do you reproduce the issue if the secondary monitor is not connected? I mean, is this issue about the 2 monitors, or does it happen already with 1 monitor, with specific resolutions?

Thank you 🙇

**Comment by emanueldima** [comment]
No, the secondary monitor must be connected for the bug to show up. I also tried changing the display arrangements (i.e. which monitor is to the left of the other one or one on top of another) but this does not seem to matter. 

Another interesting thing is that if I change the resolution of the primary display the titles are rendered correctly until I switch to the other display. Once the titles are rendered on the secondary display they will not be rendered correctly on the primary one anymore.

**Comment by lubomirfiala** [comment]
I tried all 4 common setups for me and i can reproduce this bug on all of them:
```
external 5120x1440 primary & mbp 1512x982 (scaled) secondary
external 5120x1440 primary & mbp 1800x1169 (native) secondary
mbp 1512x982 (scaled) primary & external 5120x1440 secondary
mbp 1800x1169 (native) primary & external 5120x1440 secondary
```

Then i tried to change resolution on my external monitor to some funky values, first i thought it was related to screen ratio, but now it seems it only happens above 3400px of width of screen, but that is not consistent with @emanueldima :

can reproduce it:
```
external 3440x1440 & mbp 1800x1169
external 3440x1080 & mbp 1800x1169
external 3840x2160 & mbp 1800x1169
```

cannot reproduce it:
```
external 1920x1080 & mbp 1800x1169
external 2560x1440 & mbp 1800x1169
external 1280x1024 & mbp 1800x1169
external 1920x540 & mbp 1800x1169
```

Yes my mbp has a notch and it only happens on mbp screen only.

**Comment by lwouis** [comment]
Hi,

Here is a [local build with special logs](https://github.com/user-attachments/files/17560924/AltTab.zip). Could you please run it from Terminal.app, and share here the logs you get?

You should see logs when you hit the AltTab shortcut. It should print the screens and their resolution.

This should helps us settle if its a macOS bug or an AltTab bug.

Thank you 🙇

**Comment by emanueldima** [comment]
Unfortunately the newest macos version does not allow me to run it: `Apple could not verify “AltTab.app” is free of malware that may harm your Mac or compromise your privacy`. Is there a way to compile it from source with the logs? It will run if I compile it on the same machine.

**Comment by emanueldima** [comment]
Apologies for the delay. You're right of course about starting the application. I ran it like this: 
- start and test on the secondary monitor: window displays correctly
- switch mouse to primary (laptop) monitor, show the switcher: window displays correctly 
- switch mouse on secondary monitor, show the switcher: window displays correctly 
- switch mouse on the primary (laptop) monitor: window displays **incorrectly**

[alttab-issue.log](https://github.com/user-attachments/files/17616945/alttab-issue.log)

**Comment by lwouis** [comment]
Thank you @emanueldima 

From the logs, I see 2 things:
* Screen resolutions seem to have reasonable values. No `(0, 0)` for instance
* Screen resolutions don't change over time

This seems to indicate a problem in AltTab layout logic, versus an issue with macOS support of the screen, or some notch issue.

You mentionned previously:

> reproduces at 3200x1800 (secondary) and 1728x1117 (main)
> does not reproduce at 3200x1800 (secondary) and 2056x1392 (main)
> reproduces at 2560x1440 (secondary) and 1496x967 (main)
> does not reproduce at 2560x1440 (secondary) and 1728x1117 (main)

In the logs, I see the following screens:
* 6030EF86-73F3-79BA-0857-D6964E3302DB (0.0, 0.0, 3008.0, 1692.0)
* 37D8832A-2D66-02CA-B9F7-8F30A301B230 (3008.0, 412.0, 1440.0, 900.0)

These resolutions of 3008x1692 and 1440x900 were not mentionned before. How come?

Thank you 🙇

**Comment by emanueldima** [comment]
@lwouis I tested the AltTab with logs on a macbook air M1, which supports different resolutions for the secondary screen (I was not aware of that). The previous tests were made, I think I mentioned, on a Macbook Pro m1 16"

**Comment by lwouis** [comment]
https://github.com/lwouis/alt-tab-macos/issues/3816 Maybe related?

**Comment by ildarworld** [comment]
confirming - same behavior for MacBook Pro M2 with connected external display with resolution  2560x1440

the interesting thing - as soon as I change some setting in "Appearance" tab it starts working as expected for first time

**Comment by BinaryMuse** [comment]
I created #3945 before seeing this issue; here are my logs (slightly sanitized) in case they're helpful. I split them into four blocks, the second and third are when AltTab displayed normally, and the last one is when it didn't.

**Comment by BinaryMuse** [comment]
> #3816 Maybe related?

I was having this issue too until the last time I updated AltTab, and I haven't seen it since. Unfortunately I can't remember if I was only seeing it on the external displays or not.

Perhaps also helpful: I only experience this bug after I show AltTab on the large display connected via HDMI; it displays correctly on the iPad (using Sidecar) and the main laptop screen until I do so.

**Comment by uiop860** [comment]
Can also confirm this bug happening on MacBook Pro M3 with 2 displays connected (MacBook lid closed).
displays:
- 1080 x 1920
- 3440 x 1440

When i change the widescreen to 2048 x 858 the bug stop occurring.

**Comment by lwouis** [comment]
I was finally able to reproduce today after trying all sorts of resolution from this thread. What got me to repro:

* Laptop screen: 1440x900
* Dell monitor: 2560x1440

Both screens are on. I see the collapsed list on the laptop screen. It works fine on the Dell monitor.
