### ISSUE TITLE
Native Stickies App - Minimised Windows Scaled Huge 

### ISSUE THREAD

**Issue by r1shi-j** [lwouis/alt-tab-macos#3746]
AltTab version: 7.02
macOS version: 24B5077a

Using the Stickies App my Apple
When you have a sticky that is minimised, on AltTab it is enlarged a lot.
The icon on a sticky to minimise is the top right one.

<img width="1908" alt="Screenshot 2024-10-21 at 13 35 35" src="https://github.com/user-attachments/assets/81aee914-c354-4090-9164-3ca91dd77f6b">

**Comment by lwouis** [comment]
Please see https://github.com/lwouis/alt-tab-macos/issues/351#issuecomment-2419571785. We are considering how to improve this 👍
