### ISSUE TITLE
Show Space Number - differentiate between shortcuts

### ISSUE THREAD

**Issue by bhiltunen** [lwouis/alt-tab-macos#3766]
I'm using AltTab to manage my spaces, using the following shortcuts:

Command+Tab cycles through every window _in the currently active space._ Here, I don't need to see the **space number labels**, as I know that every window is open in the space I'm currently within:
![Screenshot 2024-10-25 at 23 49 54](https://github.com/user-attachments/assets/b7a052cb-454b-45a1-981b-24f96d4acbf1)

Option+Tab cycles through _all windows_ open on the computer. Here, I _do_ want to see the space number labels, as it gets pretty confusing without them.
![Screenshot 2024-10-25 at 23 53 04](https://github.com/user-attachments/assets/5d8f5864-333b-4a13-b8de-ffd35fa42f53)

**There's currently no way to set up this sort of behaviour** - showing space numbers is an all-or-nothing type of setting. Same goes for every other Thumbnail setting - you can't, for example, make one shortcut that shows plain windows and another that shows the same windows with detailed status indicators.

I think it would be a big improvement to allow the customisation of Thumbnails Styling to be tied to specific shortcuts. This would open the door for more dynamic setups.

**Comment by lwouis** [comment]
I've implemented the following change: if the user has a single screen, and is using a shortcut showing only visible Spaces, then AltTab won't show Space Labels 👍

**Comment by bhiltunen** [comment]
One potential issue came to mind when considering the "Show windows from screens - Screen showing AltTab" setting. 

If the user has both Visible Spaces and the above settings on, but is using multiple monitors, I think Space Labels should also be hidden. 

This is a bit more niche, but I think it's worth implementing that logic into this as well!

**Comment by lwouis** [comment]
@bhiltunen good catch! I've implemented it. It will be in the next release.
Thank you 🙇
