### ISSUE TITLE
Auto fit (width) for "Titles" style

### ISSUE THREAD

**Issue by J-Siu** [lwouis/alt-tab-macos#3769]
**Is your feature suggestion related to a problem? Please describe.**

Currently, when titles style is used, the selector pop-up is very wide

![Screenshot 2024-10-27 at 21 43 49](https://github.com/user-attachments/assets/3dc973c5-8451-4d8a-b2d3-cd26e1692f34)

**Describe the solution you'd like**

Add an option, instead of fix width, auto-fit content width:

![Screenshot 2024-10-27 at 21 43 49](https://github.com/user-attachments/assets/33eeba86-4376-4dd8-a47b-919f5102d272)

**Describe alternatives you've considered**
n/a

**Comment by lwouis** [comment]
Let's use https://github.com/lwouis/alt-tab-macos/issues/3770 as a central ticket to gather discussion around this 👍
