### ISSUE TITLE
Question: How to ignore some windows

### ISSUE THREAD

**Issue by maticboncina** [lwouis/alt-tab-macos#3774]
Hello,

I tried searching for open/closed issues on a similar topic but wasn't able to find a solution. If it exists, a close reply with an issue/solution link would be appreciated. 

When I am using alt-tab (I am not sure if this happens on the default app switcher as well) some "background" apps are always shown.

![CleanShot 2024-10-29 at 11 04 24@2x](https://github.com/user-attachments/assets/d8ec2448-fdf1-44a3-998f-acdd56f79f75)

Marked with green in the screenshot. 

I would like to specify in the alt-tab that this app shall be always ignored. Would this be possible? An dif so where can I toggle?

If the feature is not there yet I will gladly upvote or add a contribution to the existing feature request. 

Many thanks and all the best,
Matic

**Comment by lwouis** [comment]
Hi,

You can add the `bundleIdentifier` of these apps in the `Blacklists` section here:

<img width="672" alt="image" src="https://github.com/user-attachments/assets/22854cc6-c172-4953-bc87-93abcd12c981">

Then, AltTab won't show these apps anymore.

I'm wondering how come you see BetterTouchTool though. I'm using it myself and it's not listed in AltTab like this, on my side. It only shows if I open its preferences window for instance

Thank you
