### ISSUE TITLE
Unable to switch between windows and applications with different shortcuts

### ISSUE THREAD

**Issue by ghfalcon7** [lwouis/alt-tab-macos#3775]
**Describe the bug**

If I enable the following option:

![image](https://github.com/user-attachments/assets/fd348a12-ffab-4042-b36e-cb5b2cc8f05b)

this option no longer works:

![image](https://github.com/user-attachments/assets/e7ffadae-062f-4dae-9e08-eb976e19e22c)

* AltTab version: 7.0.2
* macOS version: 15.0.1

**Comment by lwouis** [comment]
Could you please share a video showing how it doesn't work? What the behavior you see is.

Thank you

**Comment by ghfalcon7** [comment]
> Could you please share a video showing how it doesn't work? What the behavior you see is.
> 
> Thank you

couldn't upload the video here because of the size restriction, so I uploaded it to youtube as an [unlisted video](https://youtu.be/sd92utODIvI)

**Comment by lwouis** [comment]
Thank you for your message

It seems to work fine on your video.

Do you expect perhaps that the settings in `Appearance` are attached to specific Shortcuts? That's not supported today. `Appearance` is global, and Shortcut-specific settings are in each Shortcut tab in `Controls`.

Thank you

**Comment by ghfalcon7** [comment]
> Thank you for your message
> 
> It seems to work fine on your video.
> 
> Do you expect perhaps that the settings in `Appearance` are attached to specific Shortcuts? That's not supported today. `Appearance` is global, and Shortcut-specific settings are in each Shortcut tab in `Controls`.
> 
> Thank you

no not that, if you select this option:
![image](https://github.com/user-attachments/assets/53dc48fb-ec6f-4154-9192-566d94e11cc2)
this option:
![image](https://github.com/user-attachments/assets/74c21404-1460-4354-bed2-e554cca2f6c1)
becomes useless in any shortcut

I want to be able to switch to an app without being overwhelmed with all the open windows of each app, then I would like to switch to a specific window of that app. currently I can't do that with alt-tab. I really hope this gets supported as it feels like the missing piece for me to this great app!
