### ISSUE TITLE
Add preference: sort windows alphabetically

### ISSUE THREAD

**Issue by indigital** [lwouis/alt-tab-macos#378]
First and foremost I would like to thank you for this marvellous program.

I would be pleased to see a function that somehow (alphabetically) sorts the previewed windows.

Thanks.

**Comment by lwouis** [comment]
Hi @indigital! Thanks for sharing this suggestion!

Could you help me understand the use-case here? It's hard for me to understand the benefit of alphabetical sorting compared to the current chronological sorting?

That being said, that preference could be combined with #337 as a dropdown menu such as "Sort windows":

* Chronologically (default)
* By app
* Alphabetically

**Comment by indigital** [comment]
Thank you for your immediate reply.

At times I work with dozens of open programs/windows. As an example, I run Excel with - let's say - 5 spreadsheet windows and it's unconvenient for me that the individual windows are scattered over the preview window.

**Comment by lwouis** [comment]
Wouldn't that use-case be addressed better with either grouping windows by app (#337) or having another shortcut to only show windows of the current app (#237)?

**Comment by lwouis** [comment]
Hey @indigital, could you reply to me previous message? Otherwise I will have to close the ticket as inactive

**Comment by lwouis** [comment]
The author didn't reply, so I'm closing this ticket. I think what they want is going to be introduced with #337 and/or #237

**Comment by stagfoo** [comment]
I think this is the right place to comment on window sorting?

```
Could you help me understand the use-case here? It's hard for me to understand the benefit of alphabetical sorting compared to the current chronological sorting?
```
For me I might have 3 full screen programs and I want to tab between them, I guess it muscle memory from windows or linux but i subconsciously remember the number tabs it takes to show a window.

alt + tab = browser
alt + tab + tab =  code editor
alt + tab + tab + tab = terminal

with chronological ordering, the keyboard shortcuts are sometime in sync but sometime not. 
My current work around if the shortcuts get out of sync is alt tab and then mouse over the current window but i get tripped up some times and  just alt tab tab tab madly until i see the window i want 😅

**Comment by lwouis** [comment]
@stagfoo seems to me like your workflow would be addressed best with this: https://github.com/lwouis/alt-tab-macos/issues/210

**Comment by stagfoo** [comment]
@lwouis sorry for the late reply 🙇  Yes i think the number keys would work also I'll stop comment on this ticket and follow the one you suggested.
