### ISSUE TITLE
Circular multitasking switch with the mouse pointer as the center of the circle

### ISSUE THREAD

**Issue by louishino** [lwouis/alt-tab-macos#3780]
Horizontal bar-shaped application switching is too inefficient
I think that when pressing the shortcut key, draw a circle with the current position of the mouse cursor as the center. Different sectors correspond to different applications.
This will be much more efficient. I hope developers will consider this interaction.

**Comment by lwouis** [comment]
Hi,

It's a very interesting idea. I'm afraid it's not a match for AltTab though. I think it would be better realized in another app in the same space.

AltTab focuses on replicating the Windows alt+tab experience. This means keyboard control, and snappy UI. We have a layout system that produces 3 styles of grid. We don't have the tech to draw a circle at the moment. Furthermore, such design would be tricky to navigate with the keyboard efficiently. It would really shine for mouse interactions.

I'll close this for now. We may revisit later 👍 

Thank you

**Comment by louishino** [comment]
1. Thank you, sir, because I still find the mouse more convenient.

2. I am currently using the Alt+Tab method:

3. Pressing the side button on the mouse triggers the following actions:  
   - The mouse cursor automatically moves to the center of the screen (where Alt+Tab is located).  
   - The Alt+Tab multitasking selection box appears.  
   - I click on the task I need to switch to.  

4. As you can see, the automation level of the steps above is very high. You might consider this efficient method.
