### ISSUE TITLE
 Quick switch shortcut between two apps  

### ISSUE THREAD

**Issue by louishino** [lwouis/alt-tab-macos#3782]
1. Quick switch shortcut between two apps  
2. Often, we switch between two applications. Can we add a shortcut to switch between the current app and the last opened app?  
3. For example, pressing Command + Option + T can quickly switch to the last opened app, and pressing it again will switch back.

**Comment by lwouis** [comment]
You can press alt+tab to achieve that. With a little bit of delay (preferences > appearance > animations), the swircher will not show up

Thank you
