### ISSUE TITLE
What happened to the good old Windows 10 theme?

### ISSUE THREAD

**Issue by dilirity** [lwouis/alt-tab-macos#3788]
In the latest version, it seems like the macos theme is the default and there's no way to change that.

Is there a way to switch to windows 10 like in 6.73.0? I really like the windows 10 theme.

![CleanShot 2024-10-30 at 16 02 02](https://github.com/user-attachments/assets/7cc5569f-48db-44af-8f75-d97a912b7d45)

**Comment by lwouis** [comment]
Hi,

Sorry, the Windows theme is gone. However, there are many influences from that theme in the v7 design. You can also increase visibility to get a blue outline like Windows does:

<img width="513" alt="image" src="https://github.com/user-attachments/assets/338ebe61-b736-414f-90db-85fed3ebe922">

Thank you 🙇

**Comment by dilirity** [comment]
Ah thanks!

I was liking the straight edges of the main box. Not a fan of curved edges 😅

**Comment by ADTC** [comment]
@lwouis I couldn't understand what the "Visibility" option is. Honestly I thought it's like "z-index" or something, but above I'm reading it changes the appearance by adding blue border, and what else does it do?

Could you perhaps add a `(i)` ℹ️ help text next to the Visibility label, explaining what it is, and the difference between Normal, High and Highest as well.
