### ISSUE TITLE
Add disabling the hot-key in particular programs

### ISSUE THREAD

**Issue by indigital** [lwouis/alt-tab-macos#379]
I'm not sure if my suggestion is going too far, but I consider it to be helpful that the hot-key (alt-tab) isn't active in particular programs (blacklisting). For example in RDP or VNC tools that are connected to remote Windows sessions it's currently impossible to trigger the Windows' own alt-tab for window management.

Thanks.

**Comment by lwouis** [comment]
Hi @indigital! Thanks for another suggestion!

There is actually a ticket already for RDP and VNC (and other virtualization apps): #239. Regarding blacklist/whitelist, this has been discussed in that ticket around [that comment](https://github.com/lwouis/alt-tab-macos/issues/239#issuecomment-623669727).

Overall I would rather we fix the issue for virtualization apps than add a blacklist/whitelist system, as it's a worse user experience, and more work. If that's not doable though, that could be done.

I'll close this ticket as duplicate. Let's continue the conversation in #239 👍
