### ISSUE TITLE
Updating while on (Proton) VPN crashed the updater

### ISSUE THREAD

**Issue by Coffeeling** [lwouis/alt-tab-macos#3793]
**Describe the bug**

Tried updating Alt+Tab while on Proton VPN. Updater crashed multiple times.

Switched VPN off, update worked.

**Your environment**

* AltTab version: 
* macOS version: Sequoia 
* Other relevant info: Laptop only, on Proton VPN

**Comment by lwouis** [comment]
Hi,

We use [Sparkle](https://github.com/sparkle-project/Sparkle) for the auto-update. That project is widely used by macOS apps. I think it's very robust.

Could it be a setup issue on your side? Perhaps your VPN doesn't let other traffic through? Perhaps it blocks certain type of traffic?

This is the first time someone mentions a VPN issue in 4 years. I think it's likely that it works for everyone else. I works with my VPN for instance.

Thank you 🙇
