### ISSUE TITLE
Closed and reopened tab no longer focusable

### ISSUE THREAD

**Issue by giorgiPapava** [lwouis/alt-tab-macos#3799]
**Describe the bug**

After you close some applications using command+w or close button and reopen them, you are no longer able to alt+tab them. It' shown in alt+tab but after trying to focus you cant see it.

**Screenshots / video**

https://github.com/user-attachments/assets/164ef7ba-b98e-4ffe-850b-889399d2f5fe

**Steps to reproduce the bug**

1. Open Telegram
2. Close it using cmd+w
3. Reopen Telegram
4. Try to alt+tab on telegram

**Your environment**

* AltTab version: 7.0.2
* macOS version: 15.0.1

**Comment by lwouis** [comment]
Hi,

There are a number of issues with Telegram. I believe they are on their side, since most apps don't have the issue.

I suggest you open a ticket with their customer service.

On our side, there is nothing we can do at the moment. The window focusing code is as good as it can be, given macOS limited APIs.

Thank you 🙇

**Comment by giorgiPapava** [comment]
> Hi,
> 
> There are a number of issues with Telegram. I believe they are on their side, since most apps don't have the issue.
> 
> I suggest you open a ticket with their customer service.
> 
> On our side, there is nothing we can do at the moment. The window focusing code is as good as it can be, given macOS limited APIs.
> 
> Thank you 🙇

This problem is not only for telegram but other apps like spark, chatgpt, etc...

**Comment by lwouis** [comment]
Yes, you can see the open tickets for those apps. They each have unique issues.

**Comment by giorgiPapava** [comment]
> Yes, you can see the open tickets for those apps. They each have unique issues.

It works fine with macos builting app switching

**Comment by lwouis** [comment]
The native app switching activates the whole app. It brings all its window to the front. AltTab focuses individual windows.

They don't do the same things, thus the differences in behavior
