### ISSUE TITLE
Icon Size Setting in Thumbnails Mode

### ISSUE THREAD

**Issue by mining-id** [lwouis/alt-tab-macos#3800]
The latest update is great and makes the setup process clearer. However, some features have been lost.

Here’s how I used the previous version:
I set the app icons to a large size so that I could first locate the app by its icon and then use the preview window’s content to pinpoint specific content.

But with the new version, I can’t do that anymore. It’s been split into two modes: Thumbnails and App Icons, which has reduced my efficiency.

Could you add an option to adjust icon size in Thumbnails mode?
Thank you very much

**Comment by lwouis** [comment]
We'll consider it. Thank you 🙇
