### ISSUE TITLE
Telegram under current windows

### ISSUE THREAD

**Issue by snajper1677** [lwouis/alt-tab-macos#3803]
When trying to alt-tab telegram i see it on selection, but when selected it doesnt appear on front, its under any other windows.
But teleram is active cuz in top left corner i see its active.
Its mostly like on video, sometimes it work fine but mostly like on video

Uploading Nagranie z ekranu 2024-11-3 o 17.54.54.mov…

**Your environment**

* AltTab version: 7.0.2
* macOS version: 15.1 (24B83)
* Other relevant info: e.g. using external keyboard, multiple monitors, etc: same on mac without connected multiple monittor and also with connected

**Comment by lwouis** [comment]
https://github.com/lwouis/alt-tab-macos/issues/3799
