### ISSUE TITLE
Suggestion: A quick switch to a previous window w/o showing the switching panel

### ISSUE THREAD

**Issue by thesla13** [lwouis/alt-tab-macos#3804]
Hello, @lwouis!

A small suggestion.
I use your wonderful app together with a Logi mouse. It is set up so that, with a side button pressed, a gesture to the right brings up AltTab's window switching panel, a gesture to the left — the panel with the current app's windows. But, most importantly and most often, 90 percent of the time, and I'm sure that is the case for 90 percent of people, — I would use the simple side button press, just to send ⌘+Tab and switch to the previously active window of whatever app that was.

I works like a charm. But. While switching, AltTab also flashes, for some milliseconds, the window switching panel. And this is something that is supposed to be used a thousand times a day. And it's always flashing, and it does become tiring and distracting.

Maybe there is a way to produce this simple action without rendering the switching panel? Maybe it is somewhere in the preferences, and I miss it? If not, maybe you could implement it as a separate scenario in the Controls section of the app?

For years I used not to trigger AltTab with that button, but BetterTouchTool's "Activate Previous Window" action, for the very reason that it allows to switch without the flash. But it has its own quirks, sometimes it activates an app with all its windows, and such. It would be so great if this simple action could be performed with AltTab.

Thank you so much for your hard work!

**Comment by lwouis** [comment]
Hi,

Yes, you can use Appearance > Animations and add a little delay before the switcher shows. This way, there won't be flashing, as you desire.

Thank you
