### ISSUE TITLE
Switch to Non-Focused Tabs

### ISSUE THREAD

**Issue by jphung101** [lwouis/alt-tab-macos#3806]
**Is your feature suggestion related to a problem? Please describe.**
macOS's default `⌘ + Tab` shortcut switches to another window **_from another app_**. However, there does not seem to be an option for Alt-Tab to replicate this functionality. 

**Describe the solution you'd like**
I would really appreciate it if there was an option to turn on this functionality, where you can **_switch to windows exclusively from other apps_**.

**Describe alternatives you've considered**
I tried digging around in settings but could not find what I wanted.

Thanks and take care!

**Comment by lwouis** [comment]
* `Preferences` > `Appearance` > pick `App Icon Style`
* Then click `Customize App Icon Style...` > `Advanced` > pick `Show in switcher: Applications`
Thank you

**Comment by jphung101** [comment]
Hey thank you for getting back to me! 

I do apologize if I missed something, but now with the `App Icon Style` view selected, the `Show windows from applications` -> `Active app` option **_no longer switches at all_** (I'm assuming it is because windows are no longer shown). 

Also, I was wondering if it was possible to have the **_exclusive switching to other apps to be available under the `Thumbnails` view_**? If not, I completely understand.

Have a nice day!

**Comment by lwouis** [comment]
> Show windows from applications -> Active app

Well yes, if you want to show only one item per app, like the native app switcher from macOS, then you can't filter to only show the active app. Otherwise you see only 1 app: the active app. This setting only make sense if you list windows, not app

Thank you
