### ISSUE TITLE
No way to permanently show window titles as of 7.2.0

### ISSUE THREAD

**Issue by joachimbulow** [lwouis/alt-tab-macos#3809]
I just updated to `version 7.2.0` and i was appalled to notice that you have removed the possibility to always show window titles?

This makes this app basically no better than the default `MacOs`-native tab bar, unless you want to use thumbnails.

<img width="1302" alt="image" src="https://github.com/user-attachments/assets/4165a400-d1bb-4034-8173-59ab5a357ae4">

Is there a new MacOs limitation i am unaware of, or why was this decision made?

**Comment by lwouis** [comment]
We will consider your feedback. Thank you
