### ISSUE TITLE
Broken layout in Titles Style

### ISSUE THREAD

**Issue by maciej-skurznica** [lwouis/alt-tab-macos#3816]
**Describe the bug**

As shown in the screenshot some items appear wider but only sometimes.

**Screenshots / video**

<img width="1710" alt="Screenshot 2024-11-06 at 13 01 03" src="https://github.com/user-attachments/assets/a4582395-9d41-409b-bd7b-ab60dbbd48cf">

**Steps to reproduce the bug**

Not sure what is causing it.

**Your environment**

* AltTab version: 7.2.0
* macOS version: 15.0.1

**Comment by lwouis** [comment]
Hi @maciej-skurznica ,

Is this issue solved with the latest version? I think it should.

Thank you

**Comment by maciej-skurznica** [comment]
Hi thanks for letting me know but to be honest I rolled back to the version before the UI updates and keeping that for now.
