### ISSUE TITLE
Ability to move the switcher on the screen

### ISSUE THREAD

**Issue by maciej-skurznica** [lwouis/alt-tab-macos#3817]
**Is your feature suggestion related to a problem? Please describe.**
Yes, The previous version was a perfect 10/10 app, and the recent update spoiled it.

**Describe the solution you'd like**
Bring back the ability to adjust position of the swithce on the screen as well as the custom width. The large tiles one is not enough large.

**Describe alternatives you've considered**
Instead of custom you can add some user pre-set choices how to position the switcher. For example (middle, 2/3 screen height, 1/4 screen height etc.). Add extra large options for tiles style.

**Comment by maciej-skurznica** [comment]
Please

**Comment by lwouis** [comment]
Hi,

We're collecting feedback such as yours, after the v7 release.

We'll take it into consideration

Thank you

**Comment by maciej-skurznica** [comment]
I am going to install the 6.73.0 version for now and disable automatic updates. I hope this will be fixed in the new versions.
