### ISSUE TITLE
Opening the app creates com.plausiblelabs.crashreporter.data

### ISSUE THREAD

**Issue by moenodedev** [lwouis/alt-tab-macos#3836]
**Describe the bug**

`~/Library/Caches/com.plausiblelabs.crashreporter.data` is created when the app is opened. I can't find any reference to plausible in the code or the app acknowledgements.

**Screenshots / video**

Add screenshots to help explain your problem. You can also record your screen to show the bug in action. That is *really* helpful!

**Steps to reproduce the bug**

1. Open the app
2. `~/Library/Caches/com.plausiblelabs.crashreporter.data` is created

**Your environment**

* AltTab version: Version 7.3.0
* macOS version: 15.1

**Comment by moenodedev** [comment]
It's AppCenter

**Comment by lwouis** [comment]
AppCenter shuts down in 2025. We'll remove it from AltTab then:
