### ISSUE TITLE
Add option for not showing Title

### ISSUE THREAD

**Issue by KristofferLinderman** [lwouis/alt-tab-macos#3842]
**Is your feature suggestion related to a problem? Please describe.**
In previous versions of Alt-Tab we could chose to hide the title of the apps completely. That option seems to have disappeared now. 

**Describe the solution you'd like**
To be able to not show any title under the icons at all.

**Describe alternatives you've considered**
N/A

**Comment by lwouis** [comment]
Thank you for your message

We'll take your feedback into consideration. We're listening to such feedback, and may bring back some settings from v6, in one form or another. It has to balance the usage-rate amongst users and added complexity.

We'll look into it. Thank you 🙇
