### ISSUE TITLE
Move mouse to center of selected window

### ISSUE THREAD

**Issue by KristofferLinderman** [lwouis/alt-tab-macos#3843]
**Is your feature suggestion related to a problem? Please describe.**
Previous version of Alt-Tab allowed for having the mouse move to the selected window when switching between screens. This option is no longer available.
 
**Describe the solution you'd like**
To be able to have the mouse move to the selected window when selecting a window/app that's active on another screen.

**Describe alternatives you've considered**
N/A

**Comment by lwouis** [comment]
https://github.com/lwouis/alt-tab-macos/issues/3656
