### ISSUE TITLE
Is this possible: don't show apps that don't have windows open?

### ISSUE THREAD

**Issue by mapleroyal** [lwouis/alt-tab-macos#3846]
Is it possible to only make alt+tab show windows? Currently, it includes windows AND icons of apps that don't have any windows open, which is confusing.

I don't know if this is a new functionality because I don't specifically remember noticing it until today, but I'd like to disable it.

Version 7.0.0
macOS 15.1

**Comment by vladunev-tomtom** [comment]
There is an option to "Hide apps with no open windows".
And there is a way to hide misbehaving apps in the Blacklist options.

**Comment by lwouis** [comment]
Hi,

Indeed, you can toggle it in `Preferences > Appearance > Customize... > Hide apps with no open window`

Or you can add apps to the blacklist, and it will hide the apps indicator only for those apps.

Thank you 🙇
