### ISSUE TITLE
Esoteric crashing / permission callout _**occasionally**_ displayed erroneously

### ISSUE THREAD

**Issue by frypf** [lwouis/alt-tab-macos#3850]
**Describe the bug**

_AKA "AltTab gets confused when I attempt to confuse it on purpose 😅"_ – only noticed while testing proposed fix for #3801:

> ...I also tried revoking SR permission and checking the option to skip it, and the warning reappears as intended. I did notice that with the option checked, if I then click `Check permissions...` (or `Grant permission`, which now also seems to work as intended), the option is automatically unchecked when AltTab's permissions window appears. The flow of this all makes a bit more sense now.
>
> At that point if I either re-grant the SR permission within System Prefs or re-check Use the app without permission… , AltTab reopens itself and the warning goes away again. However in the second case, AltTab will always crash when I actually try to switch windows via the shortcut.
>
> AltTab also gets confused (either re-showing the warning or crashing upon shortcut, or both) if I check the option to skip while SR permission is already granted, or revoke the permission while the option is already checked, or generally when I toggle things out of the intended order. I sent all the crash reports I was presented with - feels like some sort of race condition in certain circumstances between checking granted vs skipped. By no means something that will affect day-to-day use, just thought you might want to be aware.
<br>

Caveats:
1. I was purposefully attempting to do things out-of-order - a consistent pattern is hard to nail down.
2. I did attempt to get some log data by running via terminal, but the combination of running AltTab via a different parent and AltTab automatically restarting itself after changing permissions made it a fruitless exercise.
3. I always grant Screen Rec permission; none of these flows ever come up in my (or potentially any _"normal"_) usage pattern.

**Screenshots / video**

https://github.com/user-attachments/assets/aee5e8bf-bb2e-464f-bae0-f16120882a91

https://github.com/user-attachments/assets/3c503a11-90b3-440a-bc09-767bf59e5ada

**Steps to reproduce the bug**

The most consistently reproducible crash I've found (see caveats above) - as shown in vid 1:
1. AltTab running with all permissions granted and callout successfully hidden.
2. Revoke SR permission via system prefs window.
3. Check `Use the app without this permission…` when AltTab's permission window pops up.
4. Wait for AltTab to restart and then hit shortcut to switch windows.
5. Immediate crash.

**Your environment**

* AltTab version: (unreleased test build >7.3.0)
* macOS version: Monterey

**Comment by lwouis** [comment]
Thank you for sharing the issue here

Is this still happening with v7.4.0?
I'm not able to reproduce the issue on my side

**Comment by frypf** [comment]
Seems resolved in v7.4.0 AFAICT 👍👏.
