### ISSUE TITLE
McAfee Endpoint Security sometimes shows an empty window in AltTab 

### ISSUE THREAD

**Issue by pitirri** [lwouis/alt-tab-macos#386]
**Describe the bug**

Alt-Tab shows McAfee background antivirus some times, some other times it doesn't. Which makes alternating between windows back and forth useless: it tries to switch to a a non-windows application (McAfee), and since there is no window, no switching between apps / windows happen.

McAfee background task which has no window should not be shown in the list / icons.

I don't have that issue with Contexts

**Screenshots / video**

I've added a loom video. However I couldn't reproduce when the McAfee window disappears. It stuck during the video recording. But sometimes it goes away, and some other time it stays.

https://www.loom.com/share/a435261aa9f540a7b922c1575f93a090

**Steps to reproduce the bug**

Just alt-tab

**Comment by pitirri** [comment]
I've recorded another loom just after posting the bug where I was able to show the issue with McAfee showing and hiding in the icons of alt+tab. Look in this video for the McAfee icon. You will see it some times, not see it other times, and even see it disappear while showing the list of icons.

https://www.loom.com/share/323774c0dc4d4af9825cd6c7947cea2d

**Comment by lwouis** [comment]
Hi @pitirri!

Thanks for the feedback! Especially thanks for including a loom video. It really helps demonstrate the issue 👍

I'm surprised to see Loom red square recording icon itself in the list of windows. I just tested on my machine, and it doesn't appear in the list.

Are you on the latest version of AltTab? Actually the simplest way would be for you to use the built-in feedback form within AltTab, and keep the "Debug Profile" checkbox checked. This will open a github issue with details from your machine like macOS version, AltTab version, etc. I think here it would be very useful.

Regarding McAfee, I'm a bit hesitant to install it on my machine to test, as these anti-virus apps are famous for destroying performance by intercepting disk access and network traffic to analyze it. Also I just tried downloading their trial version and they ask for a huge amount of personal info just to get the app. I really distrust these companies, so before resorting to installing their trial on my machine, I would like to learn more about your machine, and why Loom for instance is showing as a window when it shouldn't (and doesn't, on mine).

Thanks!

**Comment by lwouis** [comment]
@pitirri any update? Is it still happening on the latest version of AltTab for instance?

**Comment by lwouis** [comment]
The author is not responding anymore. Closing this ticket as abandonned.

If the issue still occurs and you are interested in getting it fixed, please let me know and i'll re-open the ticket 👍

**Comment by lwouis** [comment]
Author updated on Discord:

> The last one of these three did the trick:
>
>`com.mcafee.Menulet`
>`com.mcafee.McAfeeReporter`
>`com.McAfee.McAfeeSafariHost`
>
>Using: 
>
>`mdls -name kMDItemCFBundleIdentifier -r "/Library/Application Support/McAfee/MSS/Applications/McAfeeSafariHost.app"`
>
>and `ps aux | grep McAfee` to get the apps
>or:
>
>`ps aux | grep "Library[a-zA-Z0-9/ ]*.app/"`
>
>to get all the apps if you don't know what app it is
>
>in case that helps anyone else
>So:
>
>1. List all the apps running: `ps aux | grep "Library[a-zA-Z0-9/ ]*.app/"`
>2. Check the bundle id: `mdls -name kMDItemCFBundleIdentifier -r "/Library/Application Support/McAfee/MSS/Applications/McAfeeSafariHost.app"`
>3. Add to the blacklist

**Comment by lwouis** [comment]
As a consequence, I will add `com.McAfee.McAfeeSafariHost` as a default in the "don't show in AltTab" blacklist.
