### ISSUE TITLE
Alt+Tab between sets of apps, only (Work set, Personal set, Screensharing set)

### ISSUE THREAD

**Issue by lemoscaio** [lwouis/alt-tab-macos#3862]
**Is your feature suggestion related to a problem? Please describe.**

I don't use spaces on MacOS because they have bugs, are slow, and have close to 0 configuration. That leaves me with one space full of apps and windows. Sometimes, when I'm working or sharing my screen, I want to use Alt+Tab faster, and I don't want to show 80% of the windows I have open. 

**Describe the solution you'd like**

Instead of just "windows of same space, same monitor or visible spaces" as options for what to show in Alt+Tab, choosing between sets of apps and triggering them differently would be good. 

Example: 
- Option + Tab would trigger: Everything
- Option + Backtick (Work set): VSCode, Warp, Slack, Brave Browser (1 specific profile only, like Velja does), Notion Calendar.
- Command + Tab (Screensharing set): VSCode, Warp, Brave Browser (1 specific profile only).

**Describe alternatives you've considered**

I haven't found any other alternative yet.

**Comment by lwouis** [comment]
Hi,

App and windows management is handled by the OS. Recent macOS offers 2 ways to organize groups of apps/windows: Spaces, and the recently added Stage Manager.

Both of these features have no public APIs for apps like AltTab to interact with. This is why we have broken Space integration (#1324) and broken Stage Manager integration (#1731).

As far as I understand you proposal, you'd like to introduce another way to group apps/windows. That way is not supported by macOS. It would be entirely supported by AltTab. You would manage the groups in AltTab, and other apps wouldn't know these groups exist.

I'm afraid this feature would be both niche, in terms of usage, and also if going beyond what the scope of AltTab is. AltTab doesn't intend on moving windows, resizing them, grouping them, etc. It's a window switcher. It tries to use existing window management features from macOS, but it has no ambition to go beyond.

I can suggest that you take a look at https://github.com/koekeishiya/yabai which is a comprehensive window management solution. Using it, I believe you'll be able to create the custom workflow you desire.

Thank you 🙇
