### ISSUE TITLE
Music / iTunes MiniPlayer icon is much too large in v7.4

### ISSUE THREAD

**Issue by DisasterAreaDesigns** [lwouis/alt-tab-macos#3869]
**Describe the bug**

In v6 and below, the MiniPlayer was much smaller, but now it's gotten huge in the app switcher.

**Screenshots / video**

v6.73.0 behaviour:

![v6 73 0](https://github.com/user-attachments/assets/8646d413-7816-4bdb-bef5-8ac4d6e09e7c)

v7.4.0 behaviour:

![v7 4 0](https://github.com/user-attachments/assets/f4f2b342-e8dd-4f7b-8818-3169aadb05a2)

**Steps to reproduce the bug**

Use AltTab with Music / iTunes active and the Music set to Window... MiniPlayer 

**Your environment**

* AltTab version: 7.4.0
* macOS version: 15.1.1

**Comment by lwouis** [comment]
Thank you for sharing this issue

Could you please share the resolution of your screen?

Thank you 🙇

**Comment by DisasterAreaDesigns** [comment]
3440 x 1440 on this machine, which is a Mac Mini connected to an LG monitor, but the same issue occurs on all of my Retina MacBook Pros regardless of the DPI setting.

**Comment by lwouis** [comment]
Thank you @DisasterAreaDesigns 

3440 x 1440 is the resolution of the screen on which you took the screenshot above?

Could you please share the dimensions of the miniplayer window on the monitor as well?

Thank you

**Comment by DisasterAreaDesigns** [comment]
Sure thing.  Miniplayer is 298 x 91px.

In 6.73 it's the same size in the switcher, 298 x 91:

![6 73](https://github.com/user-attachments/assets/c603f1a4-7b9c-4bb8-bcea-1a27002aa17a)

In 7.4.0 it's much larger, 705 x 219px

![7 40](https://github.com/user-attachments/assets/175e9be2-cc9e-4a49-9e04-b761e0a1b258)

**Comment by lwouis** [comment]
Thank you for the great screenshots!

This makes me realize that we should probably not have thumbnails bigger than their actual windows. Note that it's a separate problem from the width being so wide. I'll open a ticket for that second topic.

**Comment by lwouis** [comment]
Hey,

The default values for min/max thumbnail width used to be 15/30% for every version before v7. This leads me to think that you have customized it in the past, using the sliders available before v7.

Could you please run this command in Terminal.app?

`defaults read com.lwouis.alt-tab-macos windowMaxWidthInRow`

Thank you 🙇

**Comment by lwouis** [comment]
Hi,

I found time to work on this today. Here are some reference values:

30% | 20% | Windows 11 (29%)
-|-|-
![30%](https://github.com/user-attachments/assets/1cbf6d5b-3243-412f-b479-e10f9a1b3f9a) | ![20%](https://github.com/user-attachments/assets/19ef3936-438b-44b1-9fe0-60a08f3ce332) | ![29% Windows 11](https://github.com/user-attachments/assets/0e4eebb2-494d-471a-a779-114ff7a8aa1c)

Windows 11 has wide thumbnails as well. I suspect they have the same max value as us: 30%

If the best UX people at Microsoft have picked 30% for their huge user base, it's probably good enough for us. I think we will stick to it.

I think the main issue we see on your screenshot is the fact that a window thumbnail is bigger than the window itself. It creates a very weird, ugly, zoomed in thumbnails.

I'll close this ticket, and we'll implement the fix for https://github.com/lwouis/alt-tab-macos/issues/3902. That should provide a good experience 👍 

Thank you

/cc @Allsochen

**Comment by lwouis** [comment]
@Allsochen sharing another interesting UX thing. I'm adding unit-test to your heuristics method to calculate min/max width for thumbnails.

Here are the value the method generates for a variety of monitors:

```
("11\" Laptop: MacBook Air 11\": HD", 1366, 768, (0.13, 0.28)),
("13\" Laptop: MacBook Air 13\": WXGA+", 1440, 900, (0.15, 0.30)
("14\" Laptop: MacBook Pro 14\": 3K", 3024, 1964, (0.16, 0.30)),
("15\" Laptop: MacBook Pro 15\": QXGA", 2880, 1800, (0.15, 0.30)
("16\" Laptop: MacBook Pro 16\": 3.5K", 3456, 2234, (0.16, 0.30)
("19\" Monitor: Apple Studio Display 19\": HD", 1440, 900, (0.14
("20\" Monitor: Apple Cinema Display 20\": WSXGA+", 1680, 1050, 
("21\" Monitor: LG 21:9 UltraWide: UWHD", 2560, 1080, (0.09, 0.2
("22\" Monitor: ASUS 22\" Full HD: Full HD", 1920, 1080, (0.13, 
("24\" Monitor: Dell P2419H: Full HD", 1920, 1080, (0.13, 0.28))
("27\" Monitor: LG 27UK850-W: 4K", 3840, 2160, (0.13, 0.28)),
("30\" Monitor: BenQ PD3200U: 4K", 3840, 2160, (0.13, 0.28)),
("32\" Monitor: BenQ EW3270U: 4K", 3840, 2160, (0.13, 0.28)),
("34\" UltraWide Monitor: LG 34UC79G-B: UWHD", 2560, 1080, (0.09
("34\" UltraWide Monitor: LG 34WN80C-B: UWQHD", 3440, 1440, (0.0
("32\" TV: Samsung UE32T5300: Full HD", 1920, 1080, (0.13, 0.28)
("40\" TV: Samsung Q60B: 4K", 3840, 2160, (0.13, 0.28)),
("43\" TV: LG 43UN7300: 4K", 3840, 2160, (0.13, 0.28)),
("50\" TV: Samsung TU8000: 4K", 3840, 2160, (0.13, 0.28)),
("55\" TV: LG OLED55CXPUA: 4K", 3840, 2160, (0.13, 0.29)),
("60\" TV: Vizio 60-inch 4K: 4K", 3840, 2160, (0.13, 0.28))
```

Here are the unique values it outputs, with the input resolutions:

```
(0.09, 0.21) UWHD, UWQHD
(0.13, 0.28) HD, Full HD, 4K
(0.13, 0.29) Full HD, 4K
(0.14, 0.30) HD, WSXGA+
(0.15, 0.30) WXGA+, QXGA
(0.16, 0.30) 3K, 3.5K
```

**Comment by DisasterAreaDesigns** [comment]
> Hey,
> 
> The default values for min/max thumbnail width used to be 15/30% for every version before v7. This leads me to think that you have customized it in the past, using the sliders available before v7.
> 
> Could you please run this command in Terminal.app?
> 
> `defaults read com.lwouis.alt-tab-macos windowMaxWidthInRow`
> 
> Thank you 🙇

Showing 30.  To my knowledge I didn't  change anything in the sliders, and the same thing happens on three different machines.  I see this is closed, hoping you found the issue.
