### ISSUE TITLE
cursor follow focus option

### ISSUE THREAD

**Issue by samiabid** [lwouis/alt-tab-macos#3875]
Not sure if I've gone blind, but I can't seem to find this option in the new releases of Altab.

![CleanShot 2024-11-20 at 14 48 58](https://github.com/user-attachments/assets/229c35e5-448b-4266-9788-44715f89a8ed)

Can anyone guide me if I am not looking at the right place in the newer version? Currently on 6.53.0

**Comment by lwouis** [comment]
https://github.com/lwouis/alt-tab-macos/issues/3882
