### ISSUE TITLE
Thumbnails should not be enabled unless requested if they require periodic screen capture.

### ISSUE THREAD

**Issue by resuna** [lwouis/alt-tab-macos#3881]
**Describe the bug**

I just upgraded.

I was just sitting there and it says "alt tab is capturing your screen".

Apparently this is required for thumbnail view. Which is apparently a new thing.

If so, that should require an explicit settings change to thumbnail view. It should not be done by default.

**Screenshots / video**

Add screenshots to help explain your problem. You can also record your screen to show the bug in action. That is *really* helpful!

**Steps to reproduce the bug**

1. Run Alt Tab
2. Observe an icon in the menu bar
3. Select that Icon
4. See "Alt Tab is capturing your windows"
5. Dig through preferences and see that thumbnail mode is selected.
7. Rack your brains because you don't think you have seen that option before.
8. In any case, you don't recall seeing thumbnails in this app.
9. Maybe you turned them off? How long have they been there?
10. Well they're on now.
11. And they periodically capture your screen to enable them.
12. Yuck.
13. Turn them off.
14. Maybe disable that permission for this app.

**Your environment**

* AltTab version: 7.4.0
* macOS version: 14.7.1
* Other relevant info: e.g. using external keyboard, multiple monitors, etc

**Comment by lwouis** [comment]
AltTab has required the Screen Recording permission to function, for years. You've given it that permission in the past. Thumbnails are the default experience. Most people want this out of the app.

If you're not comfortable with thumbnails, you can pick one of the other 2 Styles in Preferences > Appearance.

If you're not comfortable with the permission being given, you can click on the menubar icon > Check Permissions. On the popup, check the checkbox at the bottom, then go in System Settings and remove the Screen Recording permission for AltTab.

Thank you

**Comment by mcampbellsb** [comment]
> If you're not comfortable with thumbnails, you can pick one of the other 2 Styles in Preferences > Appearance.

I didn't even know this was an option - haha.  Love it!
