### ISSUE TITLE
Chrome "Window Name" no longer visible on Tile in Alt-Tab

### ISSUE THREAD

**Issue by Gadagadanagadanagana** [lwouis/alt-tab-macos#3888]
**Describe the bug**

In Chrome, when you have multiple windows open that represent different projects, you can name these windows and it is extremely helpful to see the window names (representing the project name) then in Alt-Tab. This is no longer the case, now only the name of the active tab is visible. 

**Screenshots / video**

**Steps to reproduce the bug**

1. Go to Google Chrome, name a window via "Window --> Name Window"
2. Bring-up Alt-Tab

**Your environment**

* AltTab version: latest
* macOS version: latest

**Comment by shawn-peng** [comment]
I have the same issue.

**Comment by lwouis** [comment]
https://github.com/lwouis/alt-tab-macos/issues/3834

**Comment by vandrieu-lus** [comment]
@Gadagadanagadanagana and @shawn-peng
I had the same issue, the good news is it should be solved soon, see the update here: https://github.com/lwouis/alt-tab-macos/issues/3834#issuecomment-2511780747
