### ISSUE TITLE
Various inconsistent bugs on macOS 15

### ISSUE THREAD

**Issue by lawand** [lwouis/alt-tab-macos#3890]
**Describe the bug**

hello. I have been noticing some inconsistent bugs with alttab on macOS 15 but only in some specific cases. I did some various testing and was able to at least consistently reproduce one issue. if the accessibility keyboard was turned on in system preferences, some of alttab's behavior breaks. an example is that closing a window doesn't immediately update the interface. Here is a screen recording showing this case. I am making a chrome window close after 2 seconds and when the accessibility keyboard is turned off, the interface updates immediately, but when the accessibility keyboard is turned on, the interface doesn't update (and debugging shows that the kAXUIElementDestroyedNotification event never triggers)

https://github.com/user-attachments/assets/5797d9de-d5b3-4860-ad5d-7481ed6ab136

I know this might seem trivial since opening the alttab interface again will show the correct windows being listed, but this is one example of various window listing issues I have been having since installing macOS 15. and by the way I tested the same example above on macOS 14 and didn't see the same bug.

not sure if this bug is only caused by turning on the accessibility keyboard or if other preferences also cause this issue.

is this a macOS 15 bug you guys are aware of? did something in the private API change? hope this report is helpful in catching whatever is causing this and avoiding more bugs for other users. cheers

**Your environment**

* AltTab version: 7.4.0
* macOS version: 15.1
* Other relevant info: testing on UTM but also saw the same behaviour outside of UTM

**Comment by lwouis** [comment]
Thank you for the great report!

Indeed, it's a Sequoia bug discussed here: https://github.com/lwouis/alt-tab-macos/issues/3589

**Comment by lawand** [comment]
Ah, I see. Ok nice. So, the plan is at some point to update alttab to make the api calls that work on sequoia?
