### ISSUE TITLE
Update the thumbnails live when windows get closed or new windows are opened

### ISSUE THREAD

**Issue by lwouis** [lwouis/alt-tab-macos#39]
Right now the UI shows a snapshot of windows at the time the shortcut is pressed. This has pros: the UI is stable and not changing on the user, but also cons: the UI doesn't reflect the current state of windows.

It's a tradeoff between stability and change. I would love feedback from other people about this. Making it should be a preference?

**Comment by mfn** [comment]
HyperSwitch shows the ones "currently cached"; if you've the thumbnails open and wait with your window choose action, it will update them with a delay.

Which it was always up2date like on Windows, but feels like a good compromise to me.

**Comment by lwouis** [comment]
This was closed by #114
