### ISSUE TITLE
Random flickering

### ISSUE THREAD

**Issue by KosyoK1104** [lwouis/alt-tab-macos#3904]
**Describe the bug**

AltTab sometimes starts to flicker and vibrate and is not usable, while trying to open certain application. It fixes after force quitting the app and then opening it. It happens randomly.

**Screenshots / video**

Will provide a video when it happens again. 

**Steps to reproduce the bug**

1. Open the popup (but again it happens sometimes).
2. Start changing focus through shown apps.

**Your environment**

* AltTab version:  7.3.0
* macOS version: Sequoia 15.1.1
* Other relevant info: External keyboard and mouse, Multiple monitors

**Comment by lwouis** [comment]
Hi,
Could it be that there are multiple instances running? See #1840
Thank you

**Comment by KosyoK1104** [comment]
> Hi,
> 
> Could it be that there are multiple instances running? See #1840
> 
> Thank you

Next time when it occurs I will check. Thanks for the suggested reason.

**Comment by KosyoK1104** [comment]
https://github.com/user-attachments/assets/9bf0b059-38ff-4008-83a4-b26dbee18f71

Hello again. There were indeed 2 instances running. Also attaching a video if it helps to see what it looks like.
