### ISSUE TITLE
Preferences are not saved

### ISSUE THREAD

**Issue by michaelomichael** [lwouis/alt-tab-macos#3906]
When AltTab starts up (e.g. after a Mac reboot), I expect it to have remembered the preferences that I configured while it was last running. Instead, it starts up with what appear to be "default" preferences. I have to go into the Preferences panel and dial in my settings every time.

I've attached a screen recording showing this happening. It starts with AltTab  running, with my settings the way I want them. Then I restart AltTab and the settings are reverted back to defaults.
https://github.com/user-attachments/assets/6c3005e8-f2cb-46ea-bb06-3f1fa59e3668

I've noticed it happening with the last few versions of AltTab.

It's a company laptop, so I don't usually have admin permissions on the OS, but this has always been the case, and the preferences used to save just fine. To troubleshoot, I got granted admin permissions, and re-installed AltTab, but the issue still happens.

I like the new preferences UI, BTW :)

**Your environment**

* AltTab version: 7.4.0
* macOS version: Sonoma 14.7.1 (23H222)
* Other relevant info: I use the built-in monitor on my MacBook Pro, plus a single external monitor.

**Comment by lwouis** [comment]
Hi,

This issue is very unexpected. The preferences use the standard macOS preference APIs. They've been the same from the early days of the project some 4 years ago. I don't think it was changed much recently.

Is AltTab located in `/Applications`?

I suspect that the root cause is the setup of your machine. You mention that IT is restricting many things on your machine.

Could you try changing the settings? For instance running:

`defaults read com.lwouis.alt-tab-macos appearanceStyle`. This should show `0` by default
Then you could run `defaults write com.lwouis.alt-tab-macos appearanceStyle 1`
Then you could check that the preference is indeed checked with another `defaults read com.lwouis.alt-tab-macos appearanceStyle`

Does that work?

Thank you 🙇

**Comment by michaelomichael** [comment]
Thanks for getting back to me so quickly.

No luck with any of the commands you provided. 

Here's a record of everything I ran:

```console
$ defaults read com.lwouis.alt-tab-macos appearanceStyle
2024-11-27 12:33:41.451 defaults[52603:1315484]
The domain/default pair of (com.lwouis.alt-tab-macos, appearanceStyle) does not exist

$ cd  ~/Library/Application Support
$ find com.lwouis.alt-tab-macos
com.lwouis.alt-tab-macos
com.lwouis.alt-tab-macos/com.microsoft.appcenter
com.lwouis.alt-tab-macos/com.microsoft.appcenter/Logs.sqlite
com.lwouis.alt-tab-macos/com.microsoft.appcenter/crasheslogbuffer
com.lwouis.alt-tab-macos/com.microsoft.appcenter/crasheslogbuffer/30.mscrasheslogbuffer
com.lwouis.alt-tab-macos/com.microsoft.appcenter/crasheslogbuffer/53.mscrasheslogbuffer
com.lwouis.alt-tab-macos/com.microsoft.appcenter/crasheslogbuffer/43.mscrasheslogbuffer
com.lwouis.alt-tab-macos/com.microsoft.appcenter/crasheslogbuffer/20.mscrasheslogbuffer
com.lwouis.alt-tab-macos/com.microsoft.appcenter/crasheslogbuffer/10.mscrasheslogbuffer
com.lwouis.alt-tab-macos/com.microsoft.appcenter/crasheslogbuffer/3.mscrasheslogbuffer
... etc ...
com.lwouis.alt-tab-macos/com.microsoft.appcenter/crasheslogbuffer/2.mscrasheslogbuffer
com.lwouis.alt-tab-macos/com.microsoft.appcenter/crashes

$ defaults write com.lwouis.alt-tab-macos appearanceStyle 1
2024-11-27 12:36:09.781 defaults[52774:1319688] Could not write domain com.lwouis.alt-tab-macos; exiting

# Then I quit AltTab and moved the folder:
$ mv com.lwouis.alt-tab-macos com.lwouis.alt-tab-macos_backup

$ open -a AltTab

# The same "crasheslogbuffer" files were re-created
$ find com.lwouis.alt-tab-macos
com.lwouis.alt-tab-macos
com.lwouis.alt-tab-macos/com.microsoft.appcenter
com.lwouis.alt-tab-macos/com.microsoft.appcenter/Logs.sqlite
com.lwouis.alt-tab-macos/com.microsoft.appcenter/crasheslogbuffer
com.lwouis.alt-tab-macos/com.microsoft.appcenter/crasheslogbuffer/30.mscrasheslogbuffer
com.lwouis.alt-tab-macos/com.microsoft.appcenter/crasheslogbuffer/53.mscrasheslogbuffer
com.lwouis.alt-tab-macos/com.microsoft.appcenter/crasheslogbuffer/43.mscrasheslogbuffer
com.lwouis.alt-tab-macos/com.microsoft.appcenter/crasheslogbuffer/20.mscrasheslogbuffer
com.lwouis.alt-tab-macos/com.microsoft.appcenter/crasheslogbuffer/10.mscrasheslogbuffer
com.lwouis.alt-tab-macos/com.microsoft.appcenter/crasheslogbuffer/3.mscrasheslogbuffer
... etc ...
com.lwouis.alt-tab-macos/com.microsoft.appcenter/crasheslogbuffer/2.mscrasheslogbuffer
com.lwouis.alt-tab-macos/com.microsoft.appcenter/crashes

$ defaults read com.lwouis.alt-tab-macos appearanceStyle
2024-11-27 12:41:23.046 defaults[53107:1328779]
The domain/default pair of (com.lwouis.alt-tab-macos, appearanceStyle) does not exist

# Then I deleted /Applications/AltTab.app using the Finder, emptied the bin

$ rm -rf com.lwouis.alt-tab-macos

# Then I downloaded AltTab 7.4.0, dragged it into /Applications, and ran it

$ find com.lwouis.alt-tab-macos
com.lwouis.alt-tab-macos
com.lwouis.alt-tab-macos/com.microsoft.appcenter
com.lwouis.alt-tab-macos/com.microsoft.appcenter/Logs.sqlite
com.lwouis.alt-tab-macos/com.microsoft.appcenter/crasheslogbuffer
com.lwouis.alt-tab-macos/com.microsoft.appcenter/crasheslogbuffer/30.mscrasheslogbuffer
com.lwouis.alt-tab-macos/com.microsoft.appcenter/crasheslogbuffer/53.mscrasheslogbuffer
com.lwouis.alt-tab-macos/com.microsoft.appcenter/crasheslogbuffer/43.mscrasheslogbuffer
com.lwouis.alt-tab-macos/com.microsoft.appcenter/crasheslogbuffer/20.mscrasheslogbuffer
com.lwouis.alt-tab-macos/com.microsoft.appcenter/crasheslogbuffer/10.mscrasheslogbuffer
com.lwouis.alt-tab-macos/com.microsoft.appcenter/crasheslogbuffer/3.mscrasheslogbuffer
... etc ...
com.lwouis.alt-tab-macos/com.microsoft.appcenter/crasheslogbuffer/2.mscrasheslogbuffer
com.lwouis.alt-tab-macos/com.microsoft.appcenter/crashes

$ defaults read com.lwouis.alt-tab-macos appearanceStyle
2024-11-27 12:49:54.017 defaults[53667:1344456]
The domain/default pair of (com.lwouis.alt-tab-macos, appearanceStyle) does not exist

$ defaults write com.lwouis.alt-tab-macos appearanceStyle 1
2024-11-27 12:50:16.492 defaults[53680:1345033] Could not write domain com.lwouis.alt-tab-macos; exiting

$ ls -l | grep lwouis
drwxr-xr-x@  3 mor27  staff    96 27 Nov 12:47 com.lwouis.alt-tab-macos
```

**Comment by michaelomichael** [comment]
Oh, I've just realised that the preferences will be in `~/Library/Preferences` not `~/Library/Application Support`, and that I had a symbolic link in there to an older version of `com.lwouis.alt-tab-macos.plist`! 

I deleted the symbolic link, restarted AltTab, and now the `defaults read ...` command is working, and the changes in the preferences UI are being saved correctly. 😄

**Comment by lwouis** [comment]
Wonderful! 👍
