### ISSUE TITLE
Allow "Show in switcher" option to be configurable for each shortcut

### ISSUE THREAD

**Issue by mattkinnersley** [lwouis/alt-tab-macos#3907]
**Is your feature suggestion related to a problem? Please describe.**
I have two shortcuts which mimic the native macos options. Alt-Tab and Alt-backtick. Currently there is an option called 'Show in switcher'  (pictured below) which gives you the option to show all windows of each app, or just the application itself. The issue however, is that I want to be able to set this to 'Applications' for my Alt-Tab shortcut but 'Windows' for my Alt-` shortcut.

**Describe the solution you'd like**
It would be great if this 'Show in switcher' option could be configured differently for each shortcut.

<img width="541" alt="image" src="https://github.com/user-attachments/assets/75ac0fd6-c00a-43fa-92a1-d2f4fdcba70c">

**Comment by lwouis** [comment]
Hi,

I'm afraid this is not on the roadmap. It would serve too few users for a huge increase in complexity for most users. Also it's unclear how we would present the UI for the preferences. That would be really complex to design.

Thank you
