### ISSUE TITLE
Alt-Tab shows multiple instances of tabs and random pop-ups from the past when using Orion browser on 7.4.0 and 7.3.0

### ISSUE THREAD

**Issue by yoonabob** [lwouis/alt-tab-macos#3908]
**Describe the Bug**
When using Orion Version 0.99.129-beta (WebKit 619.1.11.111.2), hitting Alt-Tab shows multiple instances of old tabs and very old and random, unclickable pop-ups. Some of these are just random pop-ups that have since been closed, others are videos I've watched days ago, others are just static images of random a random home page menu like New Tab or Bookmarks. Most of these take you nowhere when clicked, and was never an issue 2-3 weeks ago (Orion seems to not be the causer of the issue as I've tried previous versions). Also at times this issue includes random flickering of an unclickable tab, rendering the Alt-Tab useless. Sometimes when clicking a Finder instance, it just doesn't work. I loved this app and it had caused me no issue until this.

**Screenshots / video**
(Show standard tabs as windows is turned on)
https://github.com/user-attachments/assets/9b67f7a1-de7a-4160-a8fb-abbc166884cc

Here is the shaking (Show standard tabs as windows is turned off - this video is on 7.3.0)

https://github.com/user-attachments/assets/7af15f29-b3e9-4b65-ae0e-5e69f2c49e19

**Steps to reproduce the bug**

Pretty much what I expanded upon in the above description. One thing I will add is that quitting and re-opening the app does work but only for 30ish mins to an hour or two, depending on workload

**Your environment**

* AltTab version: Version 7.4.0
* macOS version: Sequoia 15.0
* Other relevant info: Orion Version 0.99.129-beta (WebKit 619.1.11.111.2)

**Comment by lwouis** [comment]
https://github.com/lwouis/alt-tab-macos/issues/3589
