### ISSUE TITLE
AutoDesk Fusion 360 detected as multiple windows

### ISSUE THREAD

**Issue by ScreamZ** [lwouis/alt-tab-macos#3913]
![image](https://github.com/user-attachments/assets/319d17e7-c9c8-47a1-a630-5b243cf1e373)

Hi there, 

Using Fusion 360 on macOS, having strange issue maybe you have some idea how to solve it ?

See the interface element that gives 3 fusion windows (one with comments, and the main, …)?

Thanks

**Comment by lwouis** [comment]
https://github.com/lwouis/alt-tab-macos/issues/2650#issuecomment-1626335701
