### ISSUE TITLE
Option for "After release", to switch to the selected application but NOT focus a window

### ISSUE THREAD

**Issue by bzadon** [lwouis/alt-tab-macos#3915]
I would like to have an option for the native MacOS alt-tab behavior, for after releasing, the application is selected and "active" but no window is focused if there is no window on the current workspace. This way, I can "Command-N" to open a new window in the workspace. The current behavior of "After release" "focus selected window" is that the workspace switches over to the workspace where the selected application does have an open window. But that makes it difficult to open a new window in the desired workspace that does NOT have an open window.

Thank you!!!

**Comment by lwouis** [comment]
Hi,

I'm afraid that most users prefer the current behavior. The workflow you describe is a power-user workflow. It would see niche use if we added it in the app, and we would need to add another preference. See the recent work to remove niche preferences: #351

I hope you can undersand 🙇 

Thank you

**Comment by bzadon** [comment]
I understand. Thx for the great app nonetheless
