### ISSUE TITLE
Preview window offset

### ISSUE THREAD

**Issue by spro** [lwouis/alt-tab-macos#3916]
**Describe the bug**

The outlined preview jumps by a few hundred pixels when tabbing through, makes it pretty hard to figure out which window I'm actually going to when there are a lot of windows.

Seems to specifically happen on my external monitor.

**Screenshots / video**

https://github.com/user-attachments/assets/c58396b3-c59a-4de5-9107-ef680536b6cd

**Your environment**

* AltTab version: 7.5.0
* macOS version: 14.5
* Other relevant info: multiple monitors

**Comment by lwouis** [comment]
https://github.com/lwouis/alt-tab-macos/issues/3461
