### ISSUE TITLE
Alttab sometimes laggy for large screens

### ISSUE THREAD

**Issue by alexus37** [lwouis/alt-tab-macos#3920]
**Describe the bug**

Thank you for this amazing analyzing tool! <3 I occasionally notice that the AltTab window can be a bit laggy when I'm using a large screen. I'm not sure if it's a rendering issue or if some process is causing a blockage, but it can be quite frustrating since I often end up selecting the wrong window.

**Screenshots / video**

https://github.com/user-attachments/assets/67ed7691-51b4-45ef-b28b-e030098cec10

**Steps to reproduce the bug**

1. Have a big screen
2. Use alttab 
3. See laggy behaviour 

**Your environment**

* AltTab version: Version 7.4.0
* macOS version: 14.6.1
* Other relevant info: I am using the [49'' dell monitor](https://www.dell.com/de-de/shop/geschwungener-dell-ultrasharp-49-usb-c-hub-monitor-u4924dw/apd/210-bgtx/monitore-und-monitorzubeh%C3%B6r)

**Comment by imkebe** [comment]
Same here.

**Comment by lwouis** [comment]
https://github.com/lwouis/alt-tab-macos/issues/3845
