### ISSUE TITLE
Flashing App Switcher on startup with second monitor & when machine left on for days

### ISSUE THREAD

**Issue by purin-kan** [lwouis/alt-tab-macos#3928]
**Describe the bug**

upon startup of the laptop while connected to a second monitor, when attempt to use the alttab switcher it flashes and make it practically impossible to see which window I am switching to. it fixes itself after using the switcher to switch to an app. 

More importantly, the same issue of flashes happens when the laptop is left on for extended periods of time. This happens nearly every time I leave the laptop on for an estimate of 1 or 2 days. 

**Screenshots / video**

![B4C01D53-E4C3-4F07-B2CF-FC3408B2B61B_1_201_a](https://github.com/user-attachments/assets/2fb39539-8e06-4f33-8e51-b54fb9012404)

**Your environment**

* AltTab version: Version 7.6.0 (The second issue persist since 5.X.X)
* macOS version: 15.1.1 (24B91)
* Other relevant info: Macbook Air M1 2020 with 8 GB of ram

**Comment by lwouis** [comment]
Hi,

I'm not sure what to look for on your photo? Could you please provide a video of this "flashing"? It's hard to imagine what it looks like. I certainly have never seen it.

Are you sure that there is only 1 instance of AltTab running?

Thank you 🙇

**Comment by purin-kan** [comment]
Hello, 

My mistake, I thought I had attached a video, turns out its just the thumbnail.

This video is taken as soon as I restart my laptop and enter my password.
It was cut short due to the 10MB video size limitation of github.


https://github.com/user-attachments/assets/b31f0ad2-fd82-4168-ba2f-3eecbce8ba52


Let me know how I can help.

**Comment by lwouis** [comment]
Are you sure that there is only 1 instance of AltTab running?

**Comment by purin-kan** [comment]
Since it happens right after startup, alttab was opened automatically by the login items feature. There should be only one instance. Additionally, I did not know there can be multiple instances running at once.

**Comment by lwouis** [comment]
Can you please confirm if there was one or two instances? You can see the icons in the top menubar.

Some people check the box "launch at login" in AltTab's preferences AND in addition they add AltTab in System Settings > Login Items, resulting in 2 instances on every boot.

See #1840

**Comment by purin-kan** [comment]
I checked the open at start up in the alttab settings and removed alttab from the login items in system settings. 

This fixed the issue.
