### ISSUE TITLE
Feature Request: Group Snapped Windows for Alt-Tab Functionality

### ISSUE THREAD

**Issue by alanchan12354** [lwouis/alt-tab-macos#3930]
**Is your feature suggestion related to a problem? Please describe.**
I'm always frustrated when switching between multiple snapped windows in AltTab because I have to cycle through each window individually. This process can be cumbersome and time-consuming, especially when I'm working with related applications.

**Describe the solution you'd like**
I would like to see a feature that groups snapped windows together in AltTab, similar to how Windows 11 handles them during Alt-Tab switching. This would allow users to switch between related applications as a single group, enhancing multitasking efficiency.

**Describe alternatives you've considered**
Currently, the only option is to manually switch through each snapped window one at a time. I have also considered using other window management tools, but they do not offer the same integration with AltTab as this proposed feature would. You can use this structured request directly when submitting your suggestion on GitHub.

**Comment by lwouis** [comment]
#337

**Comment by maxwellhibbert** [comment]
This is the number one Windows 11 feature that I'd love to have on MacOS. It wouldn't be trivial to implement because the window snapping would need to be handled as well. It's the only missing piece from 1Piece, which has the visual tab switcher, as well as the snapping, split assist, and even dynamic resizing of splits, but it looks like that has been abandoned :(

> [#337](https://github.com/lwouis/alt-tab-macos/issues/337)

@lwouis That other issue doesn't really sound like the same thing as the Windows 11 snap groups feature...

**Comment by lwouis** [comment]
@maxwellhibbert @alanchan12354 sorry I misread the OP. Indeed, it's not about grouping windows of the same apps. It's about remembering groups of windows that were set together.

AltTab will not expand in that area. This is window management. We decided a few years ago that we won't do: moving windows, resizing windows, moving windows to another Space, etc.

For this, I suggest you try out [yabai](https://github.com/koekeishiya/yabai) or [aerospace](https://github.com/nikitabobko/AeroSpace). There are other smaller-scope apps that I [list here as well](https://alt-tab-macos.netlify.app/#Alternatives).

Thank you
