### ISSUE TITLE
Sub-screen display abnormality under multi-screen layout

### ISSUE THREAD

**Issue by chestnutqiang** [lwouis/alt-tab-macos#3939]
**Describe the bug**

In a multi-monitor scenario, the primary monitor can be displayed properly, but the secondary monitor cannot be

**Screenshots / video**

<img width="1115" alt="image" src="https://github.com/user-attachments/assets/22b4c7ab-21ea-43f6-8255-9c347763edf7">

<img width="890" alt="image" src="https://github.com/user-attachments/assets/57a7b59a-e175-4944-ac70-06a0a8cd8c39">

**Steps to reproduce the bug**

<img width="534" alt="image" src="https://github.com/user-attachments/assets/fe926edf-2d5d-4195-a0f3-ab55658d5485">

<img width="550" alt="image" src="https://github.com/user-attachments/assets/9e81b223-0f7e-4a46-876c-bce155e61d16">

1. The focus switches on the main screen and alttab is displayed correctly
2. The mouse focus is on the main screen, but the mouse is pointing to the secondary screen, the secondary screen can also display alttab
3. Mouse focus on secondary screen, mouse pointing to secondary screen, secondary screen shows alttab exception

**Your environment**

* AltTab version: 
<img width="560" alt="image" src="https://github.com/user-attachments/assets/f0ad8546-518d-45c6-b62d-81f7de260c0a">

* macOS version: 
 
<img width="216" alt="image" src="https://github.com/user-attachments/assets/5ae282ac-f7c6-4e60-930f-2288b8d68b24">

* Other relevant info: e.g. using external keyboard, multiple monitors, etc

Display layout

<img width="582" alt="image" src="https://github.com/user-attachments/assets/68a33349-81c1-489d-ac14-facd47d0411f">

**Comment by chestnutqiang** [comment]
<img width="556" alt="image" src="https://github.com/user-attachments/assets/8808e9d2-24c7-45f4-81f1-641ec51e31f8">
<img width="558" alt="image" src="https://github.com/user-attachments/assets/f8524971-33d9-4b67-8ebf-b5091d7f8dc7">

**Comment by lwouis** [comment]
https://github.com/lwouis/alt-tab-macos/issues/3744
