### ISSUE TITLE
Chrome window title not shown

### ISSUE THREAD

**Issue by DenisLug** [lwouis/alt-tab-macos#3954]
For the past few weeks, the manually set titles of Chrome windows have not been shown in Alt+Tab anymore. I really liked this feature to know which Chrome window I needed to switch to. It would be great to have that back.

**Steps to reproduce the bug**

1. Set the "Show titles" setting in the thumbnail advanced tab to "Window Title"
2. Rename a Google Chrome window
3. When AltTab is triggered, only the tab title is shown

**Your environment**

* AltTab version: 7.7.0
* macOS version: 15.1.1

**Comment by lwouis** [comment]
https://github.com/lwouis/alt-tab-macos/issues/3834
