### ISSUE TITLE
macOS 15.2 privacy notification always show

### ISSUE THREAD

**Issue by tidus2102** [lwouis/alt-tab-macos#3966]
**Describe the bug**

after upgrade to 15.2, macOS continuously shows this notification, there is no way to turn it off 
![Screenshot 2024-12-12 at 10 26 02](https://github.com/user-attachments/assets/8b50a9ef-30d6-49cc-8825-682d54d10265)

Video: https://github.com/user-attachments/assets/1d0434c9-d2fa-4bd9-9f01-86af2031f8db

**Your environment**

* AltTab version: 7.12.0
* macOS version: 15.2

**Comment by lwouis** [comment]
Hi,

Apple controls what macOS shows users. It seems they have yet again increased warnings that apps are capturing the screen. AltTab is capturing windows to show thumbnails to users.

We can't do anything about that. MacOS decides how permissions management behaves, and decide to show various UI elements.

Thank you

**Comment by tidus2102** [comment]
Found the solution for this issue: [screencapture-nag-remover](https://github.com/luckman212/screencapture-nag-remover)
