### ISSUE TITLE
3 finger swipe gesture is not working properly if the cursor is on top of preview windows

### ISSUE THREAD

**Issue by DavidWeinzierl** [lwouis/alt-tab-macos#3975]
If the cursor is for example in the center of the screen before triggering alttab via the newly implemented 3 finger swipe, the cursor will refocus on the preview window that is in the center (or whereever the cursor is positioned) once alttab is activated.

**Comment by lwouis** [comment]
Hi,
I'm not able to reproduce this. Could you please share a video of the issue?
Thank you 🙇

**Comment by DavidWeinzierl** [comment]
Hi lwouis, thanks for your response.
Here is a short video showing this issue:
https://youtu.be/lrR5c_O_sec

In this video I am slowly dragging 3 fingers from left to right (I drag it slowly so it can be seen properly but it also happens when doing it quickly). As you can see, the preview window where the cursor is located get refocused constantly.

Thank you!

**Comment by lwouis** [comment]
Thank you for the video

In the video, we see that the cursor is moving. It also seems that you have checked `Preferences > Controls > Additional controls > Select windows on mouse hover`. Thus, when the cursor moves, it forces the selected thumbnail to the one it's hovering.

I'm wondering what could explain that your cursor is moving. Normally with 3 fingers down, AltTab intercepts the fingers to only move the selection. The cursor shouldn't be moving at all.

When I perform a 3-finger swipe on my side, the cursor doesn't move at all. Could you perhaps record with your phone to show how you're swipping on the trackpad?

Thank you 🙇

**Comment by DavidWeinzierl** [comment]
Thanks for the quick respones!
I did not know about these additional settings, but this solves my problem of course.

Here is a quick video of me using the 3 finger swipe. It is quite difficult due to the auto focus, but I hope you can see what you want to see:
https://youtube.com/shorts/R6qmksq7YKE?feature=share

Thanks again!

**Comment by lwouis** [comment]
Hi @DavidWeinzierl,

In the video, we can see that your 3-finger scrolling is perfectly executed. I'm puzzled by how it's possible for your cursor to move then.

[Here's a record, for comparison, on my laptop](https://youtube.com/shorts/QsLTurZYzaA). I can move my fingers any way I want, and the cursor never moves. That's as long as I have the 3-fingers down while moving.

The only hypothesis I have is that you have interferances. Do you use BTT or Karabiner, or any software interfering with trackpad events?

Thank you

**Comment by DavidWeinzierl** [comment]
That is odd!
Yes I use BTT but even if I quit it, this behaviour persists.
Personally, it doesn't bother me at all and it doesn't interfere with the functionality of alttab.
But if you want to get behind it, I can of course try to assist you.

Best regards!

**Comment by lwouis** [comment]
Thank you
Then I'll close the ticket since: you are happy with your workaround, and no other user has come in to report this issue.
Thank you
