### ISSUE TITLE
Saved preferences path

### ISSUE THREAD

**Issue by miromannino** [lwouis/alt-tab-macos#398]
I would like to know where the preferences are saved. 
Asking in order to include it in my .dotfiles

Thank you!

**Comment by lwouis** [comment]
Hi @miromannino!

AltTab uses the [standard user preferences from macOS](https://developer.apple.com/documentation/foundation/userdefaults). This means that its preferences are stored in the system-wide preferences system. You can access the current values of your preferences by using the `defaults` binary as such:

```bash
defaults read com.lwouis.alt-tab-macos
```

It seems the system also stores it in a file at the following location: `~/Library/Preferences/com.lwouis.alt-tab-macos.plist`. I'm not sure if you can just save that file and restore it later to bring back your conf, like you would a linux .dotfile.

I hope my answer helped you! If yes, let me know, and I will close the ticket 👍

**Comment by miromannino** [comment]
Hello I just tried it works using the defaults import.

I need to replace the .plist file and then do:

```
defaults import com.lwouis.alt-tab-macos ~/Library/Preferences/com.lwouis.alt-tab-macos.plist
```

AltTab need to be quit before doing this operation.

It would be better if there was a way to automatically load that, but that's up to you to decide.
