### ISSUE TITLE
First tab on Firefox gets selected while tabbing

### ISSUE THREAD

**Issue by arjunarul** [lwouis/alt-tab-macos#3988]
I have multiple Firefox windows, and one other application (Chrome window in the video attached). I am on the last tab of one of the Firefox windows. When I AltTab (Cmd+Tab) from Firefox to the other application, and come back to the Firefox window, the first tab also gets selected. If I repeat this again, the second time it works fine, but the third time has this extra selected tab, and it keeps alternating like this.

If instead of a different application, I alternate between different windows of Firefox, this issue doesn't arise.
This issue doesn't arise with Chrome tabs.
This issue doesn't arise after I quit AltTab.

The reason this matters is because after the extra tab gets selected, when I Cmd+W to close the current tab I'm on, the other tab also gets closed which can get irritating over time.
I've had this issue for a long time now.

[AltTab_Firefox_ScreenRecording.webm](https://github.com/user-attachments/assets/43fe49e0-0ea4-44ae-abe6-2496e26a548d)

* AltTab version: 7.12.0
* macOS version: 15.1.1 (24B91)
* Firefox version: 133.0.3 (aarch64)

**Comment by lwouis** [comment]
Hi,
This issue is most likely on Firefox side. Could you please open a ticket with their support?
Thank you 🙇

**Comment by arjunarul** [comment]
Thanks have reported it here - https://bugzilla.mozilla.org/show_bug.cgi?id=1937966
