### ISSUE TITLE
Why 3 shortcuts from 5?

### ISSUE THREAD

**Issue by wtfzambo** [lwouis/alt-tab-macos#3995]
I'm a long time user of Alt-tab and I absolutely love it.

I was using all 5 different shortcut options and was quite disappointed to see that in latest major release, 2 of them were gone.

Now I have to redo my shortcuts, and lost an option that was very convenient for me. I don't understand why the removal rather than just leaving the option to keep them on or off somewhere.

Is there a way to restore the 2 missing options, besides downgrading to the previous version?

Cheers, thanks in advance and thanks for this awesome product.

**Comment by snk-actian** [comment]
Same here.. Happy user with 4 shortcuts and now feel like crippled :-/

**Comment by wtfzambo** [comment]
> Edit: I have downgraded to previous version but still I see only three shortcuts and "gesture" options

How is it possible 🤔?

**Comment by wtfzambo** [comment]
> > > Edit: I have downgraded to previous version but still I see only three shortcuts and "gesture" options
> > 
> > 
> > How is it possible 🤔?
> 
> Now thinking of it: Probably, I switched to an old version but not old enough. I thought I was up-to-date until 7.12.0 so I tried with 7.11.0. Apparently I was not that up-to-date.. I need to try older versions one by one, until I see the change.

I think this change happened 2 or 3 versions ago at most. LMK your findings.

**Comment by lwouis** [comment]
The [change happend in v7.11.0](https://alt-tab-macos.netlify.app/changelog)

Thank you for the feedback. We'll take it into account as part of https://github.com/lwouis/alt-tab-macos/issues/3882
