### ISSUE TITLE
suggested vim key enhancements

### ISSUE THREAD

**Issue by snoblenet** [lwouis/alt-tab-macos#3999]
**Is your feature suggestion related to a problem? Please describe.**

I love Alt-Tab but I am looking for ways to use it more quickly, especially when I have many open tabs and windows with similar names.

**Describe the solution you'd like**

1. If vim keys is enabled, `/` allows search by text. For example, type `/chrome` to only see all your Chrome-related tabs and windows.
2. If vim keys is enabled, `CTRL-F` and `CTRL-B` move up or down by more than one line.
3. If vim keys is enabled, `v` puts you in something like `visual` mode until you select a tab/window or press `esc`. That is, you no longer have to hold down the trigger keys to keep the Alt-Tab list open.

**Describe alternatives you've considered**

None. Alt-Tab is great. I just think these three enhancements would make it greater.

**Comment by lwouis** [comment]
Hi,

For 1, #590
For 2, I'm sorry, no plans for this
For 3, you can do it with `Preferences > Controls > After release: Do nothing`

Thank you
