### ISSUE TITLE
Improve responsiveness of thumbnails appearing

### ISSUE THREAD

**Issue by lwouis** [lwouis/alt-tab-macos#4]

**Comment by moeffju** [comment]
It would be great to have an option to just not use thumbnails. Original Windows switcher just showed the app icon and the window title. Usually I memorize the tab order anyway, so I don’t need a window preview.

Should I put this as a new enhancement suggestion issue?

**Comment by lwouis** [comment]
@moeffju i think for the title + app icon flow you are describing, Witch or Contexts are richer, better alternatives. They are 10 and 14 dollars though

You can make a ticket for the feature of course. If it's not too hard i'll do it soon
