### ISSUE TITLE
Show Chrome profile icon and/or theme color

### ISSUE THREAD

**Issue by lukehutch** [lwouis/alt-tab-macos#4003]
**Is your feature suggestion related to a problem? Please describe.**

When running multiple Chrome profiles (e.g. work and personal), all the Chrome icons show exactly the same way in the alt-tab switcher. In Windows 11, the Chrome profile icon is shown as a thumbnail at the top right of the Chrome icon in the switcher, and I believe the Chrome profile color is also shown in the switcher icon. This makes it much easier to see which profile is which.

**Describe the solution you'd like**

It would be great if alt-tab could show chrome profile icon thumbnails in the corner of each Chrome icon. It would be great if the theme color could also be shown as a background box around the Chrome icon.

I assume that this info can be obtained from Chrome programmatically in some way on macOS, since it is supported on Windows, but I don't know the details.

(Presumably it would be useful to support this for other browsers too, but it would be great to at least start with Chrome...)

**Describe alternatives you've considered**

--

**Comment by lwouis** [comment]
Hi,

I imagine that Chrome has special integration on Windows. On the mac, apps can customize their Dock icon, like add a badge (which AltTab will show), or other customizations. It seems mac Chrome doesn't show the profile on its Dock icon.

AltTab can only show the Dock icon as it is. We can't go beyond, unfortunately.

Thank you 🙇
