### ISSUE TITLE
Switching to some apps like slack or beeper changes focus but the app window stays hidden behind previous app's window

### ISSUE THREAD

**Issue by LaeekAhmed** [lwouis/alt-tab-macos#4010]
**Describe the bug**

Switching to some apps like slack or beeper changes focus (in the menu bar) but the app window stays behind the previous app's window, when it should have focused and brought the window in front.

> [!NOTE]  
> This only happens after a while and thus will take some time to reproduce, so if I quit alt-tab (or slack or beeper) and relaunch it and then try to switch to it, it will work but only for a while and will eventually stop working, so please let it stay in the background for a while and then try to reproduce it.

**Screenshots / video**

https://github.com/user-attachments/assets/dada4e8a-eb91-4f47-836e-d28181377345

As you can see in the screen recording, it works for Arc, Warp and Keymap (a keyboard related app) but not for Slack or Beeper

**Steps to reproduce the bug**

1. Have slack or beeper running
2. Switch to either (might work for first few tries but stops working after a while)

**Your environment**

* AltTab version: 7.12.0
* macOS version: Sequoia Version 15.1.1
* Other relevant info: using external keyboard: yes, multiple monitors: yes (laptop screen + secondary monitor)

**Comment by lwouis** [comment]
https://github.com/lwouis/alt-tab-macos/issues/3823
