### ISSUE TITLE
Swipe up/down to trigger

### ISSUE THREAD

**Issue by katzelad** [lwouis/alt-tab-macos#4012]
The new trackpad swipe feature is great, it would be nice to be able to use a vertical swipe instead of horizontal for those of us who like the titles style (like me).
Thanks!

**Comment by katzelad** [comment]
@lwouis 
Thanks for the very quick release!
But I would appreciate being able to choose between horizontal and vertical swipe. With the current implementation it's either both or none, and choosing both conflicts with some useful Mac gestures.

**Comment by lwouis** [comment]
@katzelad 

Thank you for your message

> choosing both conflicts with some useful Mac gestures.

Which gestures are conflicting? Can't you move to 3-finger or 4-finger swipes to avoid the conflict?

> choose between horizontal and vertical swipe

![image](https://github.com/user-attachments/assets/e43d19fd-4764-4dd6-9125-af8bdf9094a7)

How would we do that? Having 5 options here?
* Disabled
* Horizontal Swipe with 3 Fingers
* Vertical Swipe with 3 Fingers
* Horizontal Swipe with 4 Fingers
* Vertical Swipe with 4 Fingers

What about people who want both?

What do you think?

Thank you

**Comment by katzelad** [comment]
@lwouis
I want to use a three finger vertical swipe to switch apps, and I use a three finger horizontal swipe for back/forward navigation (2 finger swipe doesn't work for non-browser apps).
Alternatively, using 4 finger swipe would conflict with mission control (because there is no 3-finger-swipe-only option for mission control - when choosing 3 finger swipe using 4 fingers also triggers the gesture).
The 5 options look great. The option to use both directions at the same time doesn't add much value in my opinion.
Thanks!
