### ISSUE TITLE
Software Crashes (Unable to Open Settings Panel)

### ISSUE THREAD

**Issue by Yoza2524** [lwouis/alt-tab-macos#4017]
**Describe the bug**

I just updated Alt-Tab to the latest version via Homebrew and encountered this bug while trying to view the new settings interface. Please feel free to contact me if you need any additional information.

**Screenshots / video**

![录屏2024-12-24 15 36 37](https://github.com/user-attachments/assets/120c68f6-b3eb-4641-b7f5-b904b03f103d)

**Steps to reproduce the bug**

1.	Open the software using Mac’s Finder; the Alt-Tab interface works normally.
2.	Open it again using Finder, expecting to access the settings panel, but the software crashes.

**environment**

* AltTab version: 7.13.0
* macOS version: 15.0 (24A335)

**Comment by lwouis** [comment]
https://github.com/lwouis/alt-tab-macos/issues/4016

**Comment by Yoza2524** [comment]
thanks
