### ISSUE TITLE
I followed the instruction but still can't build it. 

### ISSUE THREAD

**Issue by kundeng** [lwouis/alt-tab-macos#4023]
```
scripts/codesign/setup_local.sh
+ certificateFile=codesign
++ openssl rand -base64 12
+ certificatePassword=YQQ7ZgQj4nx/7meR
+ scripts/codesign/generate_selfsigned_certificate.sh codesign YQQ7ZgQj4nx/7meR
+ certificateFile=codesign
+ certificatePassword=YQQ7ZgQj4nx/7meR
+ cat
+ openssl genrsa -out codesign.key 2048
+ openssl req -x509 -new -config codesign.conf -nodes -key codesign.key -extensions extensions -sha256 -out codesign.crt
+ openssl pkcs12 -export -inkey codesign.key -in codesign.crt -out codesign.p12 -passout pass:YQQ7ZgQj4nx/7meR
+ scripts/codesign/import_certificate_into_main_keychain.sh codesign YQQ7ZgQj4nx/7meR
+ certificateFile=codesign
+ certificatePassword=YQQ7ZgQj4nx/7meR
+ security import codesign.p12 -P YQQ7ZgQj4nx/7meR -T /usr/bin/codesign
security: SecKeychainItemImport: MAC verification failed during PKCS12 import (wrong password?)

xcodebuild -workspace alt-tab-macos.xcworkspace -scheme Debug
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace alt-tab-macos.xcworkspace -scheme Debug

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00006031-000849921E44001C, name:My Mac }
{ platform:macOS, arch:x86_64, id:00006031-000849921E44001C, name:My Mac }
{ platform:macOS, name:Any Mac }
Prepare packages

ComputeTargetDependencyGraph
note: Building targets in dependency order
note: Target dependency graph (7 targets)
    Target 'alt-tab-macos' in project 'alt-tab-macos'
        ➜ Implicit dependency on target 'Pods-alt-tab-macos' in project 'Pods' via file 'Pods_alt_tab_macos.framework' in build phase 'Link Binary'
        ➜ Implicit dependency on target 'LetsMove' in project 'Pods' via options '-framework LetsMove' in build setting 'OTHER_LDFLAGS'
        ➜ Implicit dependency on target 'ShortcutRecorder' in project 'Pods' via options '-framework ShortcutRecorder' in build setting 'OTHER_LDFLAGS'
        ➜ Implicit dependency on target 'SwiftyBeaver' in project 'Pods' via options '-framework SwiftyBeaver' in build setting 'OTHER_LDFLAGS'
    Target 'Pods-alt-tab-macos' in project 'Pods'
        ➜ Explicit dependency on target 'AppCenter' in project 'Pods'
        ➜ Explicit dependency on target 'LetsMove' in project 'Pods'
        ➜ Explicit dependency on target 'ShortcutRecorder' in project 'Pods'
        ➜ Explicit dependency on target 'Sparkle' in project 'Pods'
        ➜ Explicit dependency on target 'SwiftyBeaver' in project 'Pods'
    Target 'SwiftyBeaver' in project 'Pods' (no dependencies)
    Target 'Sparkle' in project 'Pods' (no dependencies)
    Target 'ShortcutRecorder' in project 'Pods' (no dependencies)
    Target 'LetsMove' in project 'Pods' (no dependencies)
    Target 'AppCenter' in project 'Pods' (no dependencies)

GatherProvisioningInputs

CreateBuildDescription

ExecuteExternalTool /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -v -E -dM -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.1.sdk -x c -c /dev/null

ExecuteExternalTool /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -v -E -dM -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.1.sdk -x c -c /dev/null

ExecuteExternalTool /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -v -E -dM -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.1.sdk -x objective-c -c /dev/null

ExecuteExternalTool /Applications/Xcode.app/Contents/Developer/usr/bin/ibtool --version --output-format xml1

ExecuteExternalTool /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc --version

ExecuteExternalTool /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -V

ExecuteExternalTool /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld -version_details

ExecuteExternalTool /Applications/Xcode.app/Contents/Developer/usr/bin/actool --version --output-format xml1

Build description signature: 7356ed29e00b474db6f87a09070a9b3e
Build description path: /Users/kundeng/Library/Developer/Xcode/DerivedData/alt-tab-macos-fyytusfduhmnhnalmtpwfxfzizam/Build/Intermediates.noindex/XCBuildData/7356ed29e00b474db6f87a09070a9b3e.xcbuilddata
/Users/kundeng/Dropbox/alt-tab-macos-master/Pods/Pods.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.10, but the range of supported deployment target versions is 10.13 to 15.1.99. (in target 'SwiftyBeaver' from project 'Pods')
/Users/kundeng/Dropbox/alt-tab-macos-master/Pods/Pods.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.11, but the range of supported deployment target versions is 10.13 to 15.1.99. (in target 'ShortcutRecorder' from project 'Pods')
/Users/kundeng/Dropbox/alt-tab-macos-master/Pods/Pods.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.7, but the range of supported deployment target versions is 10.13 to 15.1.99. (in target 'Sparkle' from project 'Pods')
/Users/kundeng/Dropbox/alt-tab-macos-master/Pods/Pods.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.9, but the range of supported deployment target versions is 10.13 to 15.1.99. (in target 'AppCenter' from project 'Pods')
/Users/kundeng/Dropbox/alt-tab-macos-master/Pods/Pods.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.12, but the range of supported deployment target versions is 10.13 to 15.1.99. (in target 'Pods-alt-tab-macos' from project 'Pods')
/Users/kundeng/Dropbox/alt-tab-macos-master/Pods/Pods.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.6, but the range of supported deployment target versions is 10.13 to 15.1.99. (in target 'LetsMove' from project 'Pods')
/Users/kundeng/Dropbox/alt-tab-macos-master/alt-tab-macos.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.12, but the range of supported deployment target versions is 10.13 to 15.1.99. (in target 'alt-tab-macos' from project 'alt-tab-macos')
/Users/kundeng/Dropbox/alt-tab-macos-master/alt-tab-macos.xcodeproj: error: No certificate matching 'Local Self-Signed' found: Select a different signing certificate for CODE_SIGN_IDENTITY, a team that matches your selected certificate, or switch to automatic provisioning. (in target 'alt-tab-macos' from project 'alt-tab-macos')
warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'alt-tab-macos' from project 'alt-tab-macos')
** BUILD FAILED **


The following build commands failed:
        Building workspace alt-tab-macos with scheme Debug
```

**Comment by kundeng** [comment]
Is it possible to update this repo so that one can easily build it under 15.3 Beta (24D5034f)?  

I spend 2 hours trying to build it without success.

**Comment by lwouis** [comment]
Hi,
The issue was discussed here: https://github.com/lwouis/alt-tab-macos/issues/3170. It's the version of openssl you're using that's different.
I've just pushed a fix on master, based on the previous discussion. Could you please try it out?
Thank you 🙇

**Comment by kundeng** [comment]
I added the legacy flag but I still ran into a lot of issues.  Mostly because the xcode for 15.3 has minimum version of 10.3 for target version.

**Comment by kundeng** [comment]
The first issue is that Xcode complains that the target version must be 10.13 or higher. I used the following script to update all targets.  In order to do so, I had to install a more recent version of ruby.  

```ruby
# update_deployment_target.rb
require 'xcodeproj'

project_path = 'alt-tab-macos.xcodeproj'
project = Xcodeproj::Project.open(project_path)

project.targets.each do |target|
  puts "Updating deployment target for #{target.name}"
  target.build_configurations.each do |config|
    config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.13'
  end
end

# Update Pods project
pods_project_path = 'Pods/Pods.xcodeproj'
pods_project = Xcodeproj::Project.open(pods_project_path)

pods_project.targets.each do |target|
  puts "Updating deployment target for Pods target #{target.name}"
  target.build_configurations.each do |config|
    config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.13'
  end
end

project.save
pods_project.save
```

The second issue involves the Ruby version that comes with macOS. To address this, I used Devbox to install a more recent version of Ruby, Gem, and CocoaPods. After running `pod install`, I needed to exit Devbox to avoid a conflict with `clang` from Xcode.


The third issue is After all that, I still encountered the following errors:

```
The following build commands failed:
    SwiftCompile normal arm64 /Users/kundeng/Dropbox/alt-tab-macos/src/api-wrappers/AXUIElement.swift (in target 'alt-tab-macos' from project 'alt-tab-macos')
    SwiftCompile normal arm64 Compiling AXUIElement.swift, CGWindow.swift, HelperExtensions.swift, PrivateApis.swift, CGWindowID.swift /Users/kundeng/Dropbox/alt-tab-macos/src/api-wrappers/AXUIElement.swift /Users/kundeng/Dropbox/alt-tab-macos/src/api-wrappers/CGWindow.swift /Users/kundeng/Dropbox/alt-tab-macos/src/api-wrappers/HelperExtensions.swift /Users/kundeng/Dropbox/alt-tab-macos/src/api-wrappers/PrivateApis.swift /Users/kundeng/Dropbox/alt-tab-macos/src/api-wrappers/CGWindowID.swift (in target 'alt-tab-macos' from project 'alt-tab-macos')
    SwiftCompile normal arm64 Compiling PermissionsWindow.swift /Users/kundeng/Dropbox/alt-tab-macos/src/ui/permission-window/PermissionsWindow.swift (in target 'alt-tab-macos' from project 'alt-tab-macos')
    Building workspace alt-tab-macos with scheme Debug
(4 failures)
```

**Comment by lwouis** [comment]
You don't need to update the target like this. I was on XCode 16.2 yesterday, and it complained about one line needing 10.13. I clicked to auto-fix by surrounding it with #available.

The project is usually built with XCode 14.2 (locally and on CI). That's why it doesn't compile right away on XCode 16.2.

After the auto-fix of that 1 line that required 10.13, the project built for me.

No need to pod install either. The dependencies are already ready from git clone.

Could you please try this?

**Comment by lwouis** [comment]
@kundeng I've pushed fixes to the XCode 16.2 compilation errors. If you checkout `master`, you should be able to compile right away 👍 
Thank you

**Comment by kundeng** [comment]
I was trying to build it from the CLI.  Is your instruction for CLI still current? Does it only work with Xcode 14?  I will try to build it using the XCODE GUI and let you know.

**Comment by kundeng** [comment]
When building using the xcode GUI, the error is:

alt-tab-macos-master/src/logic/Windows.swift:274:44 Capture of 'screen' with non-sendable type 'NSScreen' in a `@Sendable` closure; this is an error in the Swift 6 language mode

**Comment by lwouis** [comment]
The CLI is how the app builds on CI. It's totally supported. Using Xcode is supported too.

The project uses Swift 5 not 6. The .xcconfig files contain that. I'm not sure how it's possible that it tries to use Swift 6 in your case. You opened the .xcworkspace file, then clicked Run, without modifying anything?

Thank you

**Comment by kundeng** [comment]
> The CLI is how the app builds on CI. It's totally supported. Using Xcode is supported too.
> 
> The project uses Swift 5 not 6. The .xcconfig files contain that. I'm not sure how it's possible that it tries to use Swift 6 in your case. You opened the .xcworkspace file, then clicked Run, without modifying anything?
> 
> Thank you

yes.  The master branch. Opened the workspace file and clicked Run.  I don't understand it either AS why it tries to use Swift 6.  I can confirm that the build setting also states it's using swift 5.

**Comment by kundeng** [comment]
I downloaded Xcode 16.2 from 16.1 and the error is now:

Command PhaseScriptExecution failed with a nonzero exit code

**Comment by lwouis** [comment]
Hi,

> Command PhaseScriptExecution failed with a nonzero exit code

This happens usually when the code-signing fails. There was probably an issue with the first step of running `scripts/codesign/setup_local.sh`

Thank you

**Comment by kundeng** [comment]
The first step was run before I started the debug build.  It prompted me unlocking keychain with fingerprint etc, so it seems to be successful.  How do I check?

**Comment by lwouis** [comment]
You can check in Keychain (`open /System/Library/CoreServices/Applications/Keychain\ Access.app`). You should see such self-signed certificates, if it went well:

![image](https://github.com/user-attachments/assets/a1be4f82-06c5-4d35-98cb-4b04b34eca1f)

**Comment by kundeng** [comment]
I have those, as you can see that I also generated a new one just now, and when I open the xcode,  it asks me to unlock the keygen for which I did, but then it just failed again with the same error message. 

<img width="897" alt="image" src="https://github.com/user-attachments/assets/216c8170-c3c5-4917-b0ee-b7748401e56f" />

**Comment by lwouis** [comment]
Hi,

I think the issue may be that you have multiple certificates with the same name. Could you please try deleting them and making a new one?

If it doesn't work, could you please run this command and share the result? I think it's the one which fails:

`CODE_SIGN_IDENTITY="Local Self-Signed" CODESIGNING_FOLDER_PATH="DerivedData/Build/Products/Release/AltTab.app" scripts/codesign/codesign_sparkle_embedded_apps.sh`

Thank you

**Comment by kundeng** [comment]
The build finally succeeded after I deleted all those certs and created a new one!  Thanks.

**Comment by kundeng** [comment]
Now how can I actually run it?  I removed the one I installed from brew.  The debug version showed the settings dialog but I can't seem it let it get access to accessbility and screen recording.

**Comment by kundeng** [comment]
<img width="1169" alt="image" src="https://github.com/user-attachments/assets/1cc66b17-dde8-44d8-8735-ef1455a2086f" />

**Comment by lwouis** [comment]
I think you may need to grant permissions to XCode since the app is started by XCode.

**Comment by kundeng** [comment]
Same
<img width="1197" alt="image" src="https://github.com/user-attachments/assets/bb8626ce-5046-41de-8efb-3b62fdfb7643" />

**Comment by lwouis** [comment]
I've never seen this. I don't know how to assist you further. Are you sure that the AltTab on your screenshot is running inside XCode?

Thank you

**Comment by kundeng** [comment]
yes,  I did a "show in finder" of that alt-tab and it's under some temp debug release folder of xcode.  

Can you tell me what is your exact set-up? I have another mac laptop, and I can roll back the mac OS version  and try it there.

**Comment by lwouis** [comment]
I'm on macOs 15.2. I develop the app in AppCode. I run it often in XCode as well. I have XCode 14.2 on my machine, which is the one I use with AppCode. It's also the one used by the CI for new releases. I also have XCode 16.2 on my machine. It runs AltTab as well.

I'm not sure the issue you face is about the versions of macOS or XCode. I think you should look into [resetting the permissions](https://apple.stackexchange.com/questions/384230/how-do-i-reset-screen-recording-permission-on-macos-catalina). Or maybe there is something unique about how your XCode is setup?

I'm surprised that the Accessibility Permission is also red on your screenshot. This one typically is not as capricious as Screen Recording. I've never seen someone having an issue with it.

Finally, it could be something wrong with CodeSigning. In that case, it could be that every build you end up with an app that macOS considers a different app. And you need to give permissions again. That's what happened 5 years ago when I started developping the app. That's why I created the self-serve certificate script. So that we can sign the app. This way the permissions stick between runs.

I hope these advices help!

Thank you

**Comment by kundeng** [comment]
I did some more digging.  
The self-signed certificate need to be set to "always trusted".  Not sure how that can be done on the CLI and it can be done in the keychain UI. 
I also tried xcode 15 and the compiling works both on the CLI and xcode GUI without any strangeness.
