### ISSUE TITLE
The thumbnail of Xcode cannot be destroyed.

### ISSUE THREAD

**Issue by shay-wong** [lwouis/alt-tab-macos#4030]
**Describe the bug**

The thumbnail of Xcode cannot be destroyed.

**Screenshots / video**

https://github.com/user-attachments/assets/040c7056-f859-4a9c-a37e-16edaa91cbe1

**Steps to reproduce the bug**

**Your environment**

* AltTab version: 7.13.1
* macOS version: macOS Sequoia 15.2
* Other relevant info: using multiple monitors

**Comment by lwouis** [comment]
https://github.com/lwouis/alt-tab-macos/issues/3589
