### ISSUE TITLE
When i take a screen shot ALT TAB starts to show in the screen shots even tho it does not show while taking the screen shot

### ISSUE THREAD

**Issue by fwends** [lwouis/alt-tab-macos#4033]
![image](https://github.com/user-attachments/assets/cdf90a63-f638-4c78-b9dc-79aab173ea13)
When i take a screen shot while alt-tab does not show it's started to show in my screen shots like this 
it does not happen all the time but it's happening 50% of the time

I was not doing it before , it has only just started doing it i use shottr as my screen shot tool 
mac air m1
15.1.1 (24B91)
AltTab
Version 7.13.1
GPL-3.0 license

**Comment by lwouis** [comment]
Hi,

Do you see AltTab show when your do the screenshot? Or is it not visible but magically appears on the screenshot at the end, like a ghost?

Do you use the swipe gesture to trigger AltTab (Preferences > Controls > Gesture)?

Thank yoy

**Comment by fwends** [comment]
I do not see the alttab when i do the screen shot it is not visible but
magically appears only on the screen shot
i do not use swipe gestures to trigger alt tab is says it is disabled

**Comment by lwouis** [comment]
Hi,

I can't think of how this could be an issue with AltTab since it's not showing. I think it could be an issue with how shottr is doing the screenshotting.

Could you please open a ticket with their customer support?

Thank you 🙇
