### ISSUE TITLE
macOS 10.15.5, Alt-Tab 4.1.6 hang

### ISSUE THREAD

**Issue by foss-** [lwouis/alt-tab-macos#412]
Not sure what exactly triggers the hang. Might be related to #401 and #410 although for me the CPU is at 0,0% for AltTab.

Debug data:
- [Process Sample](https://bin.disroot.org/?e2c401163e87654e#Hca5JU66iQpZsUUYDbLy1ubrhxfosVYXsMgu7sE2j3W8)
- [Spin Dump](https://bin.disroot.org/?86ce63aaf0145442#G2Ucd6Dno3iNBXpP4DzAfJarscD2hpiz7bhrhgaZ6NrD)

Testing build https://github.com/lwouis/alt-tab-macos/files/4903741/AltTab.app.zip now and will see if the hang returns. Feel free to set to duplicate if this is indeed the same problem.

**Comment by lwouis** [comment]
Thank you very much for the nice report and logs. A new release will be available in a moment, and it will hopefully fix the hanging. Hopefully we can close those 3 tickets at once 🙏

**Comment by foss-** [comment]
No hangs with 4.1.7 or 4.2.0 so far.
