### ISSUE TITLE
Hidden windows not showing

### ISSUE THREAD

**Issue by alexandremjacques** [lwouis/alt-tab-macos#413]
Even with the `Show the following windows` - `Hidden` checked, windows that were hidden by the `x` button won't show on the windows list (minimized windows show normally).

System:
MacBook Pro Mid 2014
macOS Catalina (10.15.5)
Dual-Core Intel Core i5 - 8 GB

Alt-Tab Version 4.1.7

**Comment by lwouis** [comment]
Hi! Thanks for sharing this feedback!

I'm a bit confused by your description. You said:

> windows that were hidden by the x button won't show on the windows list

What do you mean "the x button"? You mean the red circle button with the cross inside?

![image](https://user-images.githubusercontent.com/106195/87214607-1df80f80-c369-11ea-9ef9-33860bb6970a.png)

That button is to close the window, not hide it. There is no button to hide windows, to my knowledge, you have to use the keyboard shortcut, or click-click the Dock icon of the app then "hide".

Could you please clarified the scenario here? A quick [Loom](https://www.loom.com/) would help a lot 👍

**Comment by alexandremjacques** [comment]
Hi,

Sorry if I made it confusing. I actually meant closed the windows (not hidden). 

I have the impression that, somwhere in time, closed windows used to appear when alt-tabbing. I really liked that approach.

Regards.

**Comment by lwouis** [comment]
Showing closed windows? That must have been a bug. It has never been supported.

Now that is quite a strange/interesting concept. What would be the point of that? Also currently windows are sorted by chronological focus. Where would these ghosts windows be? At their "last used" place in the chronology? At the end in a special section? And when the user release the shortcut on that window, what would happen? AltTab can't bring it back through magic. If the window is closed, its content may be gone for good, depending on the app. Even if the app is saving its content, there is no way to ask the app to reopen the window. There is no universal handling for this.

**Comment by alexandremjacques** [comment]
I have the tendency of closing windows instead of minimizing them. Most of the apps I use keep the state of the last open window (Sparck, Whatsapp, etc.). That's why I mentioned the case.

If there's no handling to deal with them, that's Ok. I really was under the impression that, at some point, my Whatsapp window was being listed even if I closed its window. Again, sorry for the confusion.
