### ISSUE TITLE
Support for macOS version 10.16+

### ISSUE THREAD

**Issue by trucnguyenlam** [lwouis/alt-tab-macos#418]
Hi,

Could you please let me know whether the is plan to support for macos 10.16+?

Many thanks,
Truc

**Comment by lwouis** [comment]
I plan on supporting 10.16. I have no idea about the scope it represents though. AltTab uses a lot of private APIs and side-effects. While necessary to provide its features, these can be broken at any point.

Furthermore 10.16 brings large OS UI changes.

Finally, I won't be able to migrate to 10.16 in a while. I may try via a VM, even though I have not managed to make a VM work so far (using VirtualBox).

I'll close this ticket. As soon as the requirements/scope to support 10.16 is clearer, and 10.16 is publicly released, we can open a new ticket to add support 👍
