### ISSUE TITLE
Add Shortcuts to change which windows to show

### ISSUE THREAD

**Issue by bb** [lwouis/alt-tab-macos#430]
**Is your feature suggestion related to a problem? Please describe.**
I just started AltTab a few minutes ago and was unsure if I would want to show minimized and hidden or not, couldn't decide. I thought it would be very convenient to decide on the fly, while showing the list.

**Describe the solution you'd like**
I'd add three new shortcuts to toggle showing minimized, hidden, and fullscreen directly while tabbing through my windows. I think I'd chose `,`, `.`, and `-`. On my German layout, those are between "M" and right shift key. `,` is directly next to `M` (minimized). `.` coincides nicely with hidden files (and the similar finder shortcut to show/hide those). The last one just because it's next to the others.

**Describe alternatives you've considered**
I also considered
* settling for one combination of settings and see if I like it and stick with it.
* defining shortcuts for all-apps, all-spaces, all-screens but didn't do so because I wouldn't change those as often as the above.

I thought if it would be better if the toggling should be permanent (i.e. change the setting) or just for this single invocation. I couldn't decide for one and wondered if it would be overkill to add more shortcuts for a permanent and non-permanent toggle. I think it actually would be overkill. If you'd add those anyway, I think I'd use the keys from above in combination with shift.

Yet another consideration was, if it would be nice to not add those to the main list but switch to a completely different list of entries. E.g. setting: all three checkboxes off. When pressing alt-tab, I'd see only regular non-minimized, non-hidden, non-fullscreen windows. Then pressing the shortcut for minimized would show ONLY minimized (but not regular, not hidden, ...). Pressing the shortcut for hidden would show only hidden ones but not the other ones. This would probably require adding a fourth new shortcut to switch back to regular windows. (Maybe having this setting might make sense anyway, but I suppose nobody would actually switch that off by default).

And another variation: Add a new shortcut to cycle through the different kinds of lists mentioned above, but only with ONE shortcut which toggles just for this invocation (i.e. non-permanently). E.g. (Assuming setting minimized=off,hidden=off,fullscreen=off): alt-tab to invoke, then alt-a (or whatever) to show alternate lists: alt-a: show ONLY minimized, again alt-a: show ONLY hidden, again alt-a: show ONLY fullscreen, again alt-a: show only regular. If the setting was different from all-checkboxes-off; there would be 5 list variations to cycle through: as-configured, only-regular, only-minimized, only-hidden, only-fullscreen.

Finishing this brain dump, maybe the initial solution-proposal and the last variation could even be implemented in parallel because they wouldn't really interfere with each other.

Thanks for creating AltTab. I'm really happy that I found it and will probably use it a lot.

**Comment by lwouis** [comment]
Hi @bb! Thanks for sharing these interesting explorations!

It's a bit all over the place, rich with ideas, some of them I've never heard of before! I'll try my best to address the whole picture you paint.

I feel like the complex dynamic filtering you discuss resemble what you would find in let's say, a photos management app. You open it and are shown a lot of pictures. More than 20. The number of pictures is important to the discussion here. If you had let's say less than 10 pictures, you wouldn't need any filtering. Having the raw information, visually browsing all of them would probably be fast enough, and you wouldn't need any filters or visualization aid.

However, if you have more than 10, 20 pictures, it starts being useful to have filters, sorting, grouping, etc. AltTab is based on Windows 10 `alt-tab` which is not meant to be opened for a long time, and browsed in an exploratory manner, going through a huge list of windows. It's evident as the way you scroll when you reach a large number of windows in Windows 10  `alt-tab` (but also other apps in that space like HyperSwitch) is basically an after-thought and works terribly. AltTab does a way better job here imo.

I think if you have a large number of windows, you may want to organize your workflow by dividing it. If most of your pictures are from specific apps like Chrome or Excel, then a second shortcut to cycle through the active app windows may be the right approach. If you have a variety of windows all over the place from many different activities, you may want to separate your work on multiple Spaces, and have AltTab only show windows on the current Space.

To summarize I would say that window management is not similar to pictures management, in that windows are activities that are usually anchored in time. As time passes, windows become less relevant usually. You're not revisiting windows from 2 years ago like you do for photos. Exploratory visualization may not be the right approach for the domain.

Thus I think ideally you want a context like:

* "windows on that space" if you segregate your work with virtual Spaces
* "windows on that display" if you segregate your work on physical displays
* "windows for the active app" if most of your window come from a few apps

Currently there is only 1 shortcut. In #237, I'm planning of implementing 2 or 3 shortcut which will have their own filtering. This should accommodate most people workflows. Yes, users would set these statically, not on-the-fly. I hope I showcased above how I think it's a more efficient workflow, at least for a wild majority of users

If you're satisfied with this, please feel free to close the ticket. I'm trying to reduce the number of tickets as they represent a lot of work on my side. I'm currently the only maintainer for these tickets, and basically everything in this project.

**Comment by bb** [comment]
Hi @lwouis,

Thanks for this extensive answer and sorry for my late reply to it.
I agree your assessment and agree that I went over the top with all those options.

Regarding the number of items: I often have more than 20 windows open for different reasons and was overwhelmed when starting Alt-Tab for the first time. Most likely because that complexity was simply hidden before. **After getting used to it and especially with the second shortcut available since 4.0.7, it's much better.**

Regarding the contexts you mentioned:
* i'm currently not using spaces
* very often I don't have an external display attached and especially without a second display I have more need for alt-tabbing
* **windows for the active app: This is where the second shortcut option shines. Thanks for adding that! It already completely replaced the corresponding native macOS shortcut and I think that's good enough.**


BTW, I noticed that the windows are not in recently-used order when starting Alt-Tab but that solves quickly - probably hard to solve as the app can't keep track of it while it is not running. I don't consider this an issue worth investing time into.

**Comment by lwouis** [comment]
I enjoyed our discussions on this ticket :)

> I noticed that the windows are not in recently-used order when starting Alt-Tab but that solves quickly

When AltTab starts there is literally no way to get usage information. The system doesn't store that. One thing is available though: windows z-order (which windows are on top of which). Turns out that it's a good proxy for recency, but not an exact one, thus as AltTab runs, it keeps track of actual user interaction and that becomes the order over time

**Comment by bb** [comment]
Using z-index is indeed a great idea.

That makes me aware of one of the main issues which drove me to AltTab, which I was not consciously aware of:

I often have a few browser windows full screen and a few of them only on one half while e.g. VS Code is on the other half.

It’s impossible to switch between VS Code and the browser using cmd+Tab because that hides VS code behind the (full screen) Browser window (which I didn‘t use for longer time and which isn’t visible fully because of the half-screen browser window above).

I‘d love if AltTab could fix this, i.e. raising only the top most window when switching to another app (e.g. by replacing cmdTab completely, both short cut and UI).

**Comment by lwouis** [comment]
> I‘d love if AltTab could fix this, i.e. raising only the top most window when switching to another app (e.g. by replacing cmdTab completely, both short cut and UI).

Related tickets: #396, #337, #384, #397
