### ISSUE TITLE
Not available on macos 10.15.6

### ISSUE THREAD

**Issue by wanguishan** [lwouis/alt-tab-macos#437]
Not available on macos 10.15.6

**Comment by lwouis** [comment]
Hi @wanguishan!

Could you please share a little bit more information than that? 😅

Thank you!

**Comment by miromannino** [comment]
Just updated to 10.15.6, pressing alt and tab it doesn't work anymore completely, even changing keys.

**Comment by miromannino** [comment]
Quick update. Not sure what the issue was, I even tried to quit and reopen AltTab with no luck.
But simply restarting MacOS made it work.

**Comment by lwouis** [comment]
I'm suspecting that you just experienced the issue discussed in #157. You can see in that ticket: explanations of what's happening and why it's happening, what we discussed we could do about it, what you can do on your own machine to test if that's what's happening to you, etc. It starts [here](https://github.com/lwouis/alt-tab-macos/issues/157#issuecomment-659162278).
