### ISSUE TITLE
Crash when clicking >> button on About tab

### ISSUE THREAD

**Issue by buttercrab** [lwouis/alt-tab-macos#439]
**Describe the bug**

New `blacklists` tab apeared on preferences so `>>` button appeared. When I goto `About` tab and press `>>` button, the app crashes.

*I am on MacOS 11.0*

**Steps to reproduce the bug**

1. Go to Preferences.
2. Go to About tab.
3. Click >> button on the top right.

**Comment by buttercrab** [comment]
I think it was just some random crash. It works second time.

**Comment by lwouis** [comment]
Hi @buttercrab!

Could you check in the Console for a Crash Report entry for AltTab? Any crash is a bad crash. Let's hunt it down! ;)

Also you said you're on macOS 11, Big Sur? You mean the Beta program?

**Comment by buttercrab** [comment]
@lwouis How can I send you the report?

**Comment by lwouis** [comment]
Open Console.app, search for AltTab in the Crash Report section:

<img width="898" alt="Screen Shot 2020-07-20 at 21 15 13" src="https://user-images.githubusercontent.com/106195/87936726-4d77ec00-cace-11ea-8f37-2c5835c04ecc.png">

Right-click on the line for the crash you want to share, then "Reveal in Finder":

<img width="898" alt="Screen Shot 2020-07-20 at 21 16 18" src="https://user-images.githubusercontent.com/106195/87936733-523ca000-cace-11ea-91ce-39fe57ed4ffc.png">

You can then share the file here. I suggest compressing it into a .zip first

**Comment by buttercrab** [comment]
There were some other crashes, I think this should be this crash:
[AltTab_2020-07-18-134404_*.crash.zip](https://github.com/lwouis/alt-tab-macos/files/4953591/AltTab_2020-07-18-134404_.crash.zip)
