### ISSUE TITLE
Close on Esc

### ISSUE THREAD

**Issue by eyeds** [lwouis/alt-tab-macos#44]
Not sure, how it is now in Windows 10, but my fingers remember that when looping through windows hitting Esc cancels it, which is pretty useful when you've changed you mind or satisfied with a window preview. Of course Ctr-Shift-Tab is an option to go back but not that useful.

**Comment by lwouis** [comment]
I think you're right. This sounds very useful! I'll try to do it when I have time. Of course you may want to submit a PR ;p

* [Keyboard listener code](https://github.com/lwouis/alt-tab-macos/blob/master/alt-tab-macos/logic/Keyboard.swift#L24)
* [Code to hide the UI](https://github.com/lwouis/alt-tab-macos/blob/master/alt-tab-macos/ui/Application.swift#L214)

**Comment by lwouis** [comment]
@eyeds [release 1.7.0](https://github.com/lwouis/alt-tab-macos/releases/tag/v1.7.0) adds this feature. Check it out!

**Comment by lwouis** [comment]
**Update:** there was a regression in that release. Please [download the latest version instead](https://github.com/lwouis/alt-tab-macos/releases/latest). Sorry about that!
