### ISSUE TITLE
DVDFab 11 is not showing in AltTab

### ISSUE THREAD

**Issue by mrc247-DE** [lwouis/alt-tab-macos#450]
DVDFab 11 is not showing in AltTab

It's not a really important problem, I just wanted it to be mentioned.
The DVDFab11 window also looks strange to me. It looks like a "Windows 98" window. ;-)

There is a 30 day trail of the Mac version, maybe you can check why the window is not shown in AltTab, maybe that also affects other apps.

https://dvdfab.cn

**Comment by lwouis** [comment]
Hey @mrc247-DE! Nice to read you again!

You know one of the unexpected consequence of me working on this project has been to get a glimpse at how people use their computer. Earlier today I helped a user get his game to show in AltTab #441. This game is using Adobe Air. In 2020! What blast from the past! I really enjoyed revisiting this. I miss the glory days of Flash. I found my Kongregate account the other week. I opened it when I was in highschool. It still has my history and achievements from that time.

Anyway, I'll look into this Window 98 looking app ;)

**Comment by lwouis** [comment]
It's another ported app that has the wrong `subrole`. It also opens very janky windows like the preferences window, or when you click to select files or after you select files. All these windows look like independent windows, but they block interaction with the base window while they are shown. Thus they ask more like modal sheets. I played with showing them in AltTab, but in the end it makes little sense, so I went back to a more straightforward fix.

This will be included in the next release 👍

**Comment by mrc247-DE** [comment]
Thanks again for the quick support. :-)

It's nice to read that you have fun and nostalgic feelings when you examine other users' problems. ;-)

I work as a system administrator in the area of VMware and Windows Server and I think I know what you mean. ;-)
