### ISSUE TITLE
switch keybinds from ctrl tab to alt tab

### ISSUE THREAD

**Issue by MaxLeiter** [lwouis/alt-tab-macos#46]
I couldn't find an issue on this, so sorry if it's been asked before.

Why isn't the keybind alt+tab, instead of ctrl+tab?

**Comment by lwouis** [comment]
This leaves in #8. Here is [how you can currently customize the shortcut](https://github.com/lwouis/alt-tab-macos/issues/8#issuecomment-543632853) by editing a JSON file on your machine.

I'm working on a proper Preferences UI so that casual users can also customize this. See #8 for more details

**Comment by lwouis** [comment]
@MaxLeiter I just released [1.6.0](https://github.com/lwouis/alt-tab-macos/releases/tag/v1.6.0) which features an easy dropdown menu to select which shortcut key you want to use to trigger the app. Check it out! :)
