### ISSUE TITLE
Allow to hide new close/min/max icons

### ISSUE THREAD

**Issue by oshatrk** [lwouis/alt-tab-macos#460]
**Is your feature suggestion related to a problem? Please describe.**
With the new icons to close/min/max windows introduced in 4.8.0 there is a possibility to accidentally close/min/max a window with a missclick.

**Describe the solution you'd like**
Add a configuration switch to hide/show those close/min/max icons.

**Describe alternatives you've considered**
Downgrade to 4.7. )

**Comment by lwouis** [comment]
There has been [extensive discussion about this](https://github.com/lwouis/alt-tab-macos/issues/9#issuecomment-662226467) already. Bottomline: I will add a preference for this

**Comment by oshatrk** [comment]
@lwouis It will be helpful. My personal misclick counter is around 3 per last day (I usually work with 50-70 windows, 10 per row in alt-tab, so thumbnails are relatively small on 15").
