### ISSUE TITLE
AltTab crashes when I try to edit appearance

### ISSUE THREAD

**Issue by mikekaminsky** [lwouis/alt-tab-macos#464]
**Describe the bug**

If I select any option on the "appearance" tab the app immediately crashes. I assume this is not reproducible -- but I (believe) the crash reports are being sent. Let me know if I can send anything else :)

**Screenshots / video**

[Loom](https://www.loom.com/share/32c38d49bb2c41d78d2a7fb424320f10)

**Steps to reproduce the bug**

See Loom video -- I open the preferences and click on the appearance setting I want to change and the app crashes.

**Comment by lwouis** [comment]
Hi @mikekaminsky! Thanks for sharing this issue!

I released 4.9.1. Could you please update to it, and share here it that fixed the issue for you?

**Comment by mikekaminsky** [comment]
It works now! Thank you :)

Awesome app.
