### ISSUE TITLE
Todoist app not showing up in alt-tab

### ISSUE THREAD

**Issue by eguendelman** [lwouis/alt-tab-macos#475]
Hi, 

The Todoist app https://todoist.com/downloads/mac is not showing up in alt-tab.
Its bundle identifier is `com.todoist.mac.Todoist`

I saw your post about improving the heuristic https://github.com/lwouis/alt-tab-macos/issues/456
While I agree that a whitelist is not a good out-of-box experience, at least it would allow some users mitigate these issues without waiting for a fix...  I don't know enough about macOS to be able to suggest a better permanent solution.

Thanks

**Comment by lwouis** [comment]
Hi @eguendelman! Thanks for sharing this issue!

I tried to reproduce the issue, but on my machine, the app is showing its windows. At least the login window:

![image](https://user-images.githubusercontent.com/106195/88764025-2cd72280-d1af-11ea-9a41-ed6e8e4a532d.png)

Could you please share screenshots or a [Loom](https://www.loom.com/) of which window is not showing?

**Comment by eguendelman** [comment]
Hmm, you're right.  I updated from 4.9.1 to 4.10.0, and it worked, but then I also tried reverting to 4.9.1, and it still worked... So not sure what changed from before when it appeared to not work.  Sorry about that!   😕

**Comment by lwouis** [comment]
It must have been a fluke. Hopefully it doesn't happen again 👍
