### ISSUE TITLE
No crash report when crashing during launch

### ISSUE THREAD

**Issue by LittleShell07** [lwouis/alt-tab-macos#479]
Hi, thanks for your efforts for reinforcing macOS users' experience.

But I encountered a problem when opening the software. It will crash and exit itself.

I tried to open the alttab terminal under MacOS file in the package content, but it prompted **"zsh: illegal hardware instruction /Applications/AltTab.app/Contents/MacOS/AltTab**" 

I think that's the point to solve this problem. What should I do?  My mac version is 10.15.5 (19F101). Thanks a lot!

**Comment by lwouis** [comment]
Hi @LittleShell07! Thanks for sharing this issue!

When you open then app normally, and it crashes, what do you see in Console.app when searching for "alttab"? Can you share the crash report? ("Crash report" section on the left sidebar.

When you used Terminal.app to open AltTab, I think you run the binary inside directly. I don't think you can do that. You should instead use the `open` command on the `.app` bundle to open the app in the Terminal.

In a recent version I added a crash report to the app. When it crashes and you start it again, do you get prompted to share a crash report? If you do and you sent it, it will get collected in AppCenter where i periodically review those crashes and try to fix the issues. It's quite hard to do but i try my best to understand these reports

**Comment by paulproteus** [comment]
I believe I'm hitting the same problem. Here's a gist with more information. I, too, am getting an illegal instruction error.

https://gist.github.com/paulproteus/ea616f2cf71d0263c1fa129ec7851cfa

Happy to work with you to diagnose however needed.

**Comment by paulproteus** [comment]
I don't see a prompt to add a crash report, for what it's worth.

**Comment by lwouis** [comment]
> I don't see a prompt to add a crash report, for what it's worth.

That's surprising. Normally after a crash, the next time you open the app, it will prompt you. Did you open the app multiple times?

Looking at the crash report, it crash after the crash report code is executed, so it should be ready to intercept the crash.

Also i have seen multiple crash report at a similar place in AppCenter

**Comment by paulproteus** [comment]
Hey @lwouis ! https://drive.google.com/file/d/1MLRu2f3EYdK8zl5J9Qm-vmXbx-Xyj789/view is a video showing the absence of the crash screen.

Here's the preferences, too.

```
$ defaults read com.lwouis.alt-tab-macos
{
    MSAppCenter310AppCenterUserDefaultsMigratedKey = 1;
    MSAppCenter310CrashesUserDefaultsMigratedKey = 1;
    MSAppCenterInstallId = "5AF380E6-FB41-46DD-A609-6B6F786156C3";
    MSAppCenterPastDevices = {length = 2202, bytes = 0x62706c69 73743030 d4010203 04050607 ... 00000000 0000068c };
    MSAppCenterSessionIdHistory = {length = 2209, bytes = 0x62706c69 73743030 d4000100 02000300 ... 00000000 0000067b };
    MSAppCenterUserIdHistory = {length = 2204, bytes = 0x62706c69 73743030 d4000100 02000300 ... 00000000 00000676 };
    "NSWindow Frame SUUpdateAlert" = "428 363 620 392 0 0 1440 877 ";
    "NSWindow Frame com.sindresorhus.Preferences.FrameAutosaveName" = "463 204 549 524 0 0 1440 877 ";
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2020-07-24 20:57:04 +0000";
    SUSkippedVersion = "4.4.0";
    holdShortcut = "";
    preferencesVersion = "4.17.2";
    updatePolicy = 1;
}
```

Happy to diagnose in other ways if needed; let me know. Cheers. :)

**Comment by lwouis** [comment]
Thanks @paulproteus for the video! I have no idea why AppCenter is not showing. It should.

Regarding your crash, you got the same issue as #495. Somehow your `holdShortcut` is empty. When we discussed this in #495, the other user said they were in the middle of setting that shortcut when it crashed. Do you remember setting it as well? It would really help to understand the exact interactions you did before it crashed and you ended up with it being empty in the preferences, which crashes the app on launch.

To fix your setup, simply run `defaults delete com.lwouis.alt-tab-macos holdShortcut`. That will remove the bogus preference value, and should let AltTab start normally.

**Comment by lwouis** [comment]
Ticket to follow: https://github.com/microsoft/appcenter/issues/1954

**Comment by lwouis** [comment]
Microsoft doesn't want to work on this. Furthermore, AltTab is stable now, so such scenario won't happen anymore. Closing
