### ISSUE TITLE
Non-critical interface bug

### ISSUE THREAD

**Issue by MrBaseMax** [lwouis/alt-tab-macos#483]
**Describe the bug**

The block of controls is moving

**Screenshots / video**

<img width="611" alt="image" src="https://user-images.githubusercontent.com/10533782/89205362-48339a80-d5c0-11ea-9fcf-967ffec43214.png">

**Steps to reproduce the bug**

Choose the 2nd tab (preset)
Play with switching to another app and back

**Comment by lwouis** [comment]
Hey @MrBaseMax! Thanks for sharing this issue!

This has already been reported in #457. I'm working on a fix. Please follow up progress in that ticket 👍

**Comment by MrBaseMax** [comment]
oh, sorry!

**Comment by lwouis** [comment]
No worries :)
