### ISSUE TITLE
AltTab doesn't reorder the windows list after focusing a window, with XCode and Notes

### ISSUE THREAD

**Issue by MrBaseMax** [lwouis/alt-tab-macos#484]
**Describe the bug**

Alt+Tab quick (blind) combination not working in some cases.

**Steps to reproduce the bug**

Two cases found:

1) Xcode normal window and Xcode settings window.
I can switch to the normal window, but i can't switch back to settings, cuz the settings window is always the first in a queue.
Playing with other apps and windows can force that couple to change places, but the switching still works in just one direction. One of the windows always remains first.

2) When you open any youtube video to fullscreen (Safari), two windows remain: the blank window of Safari with simple text and the window with the video itself. 
The same trouble..

**Comment by MrBaseMax** [comment]
Feels like AltTab app haven't realize that i **have** switched to that particular window

**Comment by lwouis** [comment]
Hey @MrBaseMax! Thanks for reporting another issue! That's very helpful

I was able to reproduce the issue with XCode, and also with Notes. It seems to be about multiple windows of the same apps, yet it doesn't happen in chrome. Not sure what is happening, but I'm fairly confident this was working in the past, so I guess it's a recent regression.

I'll investigate further

**Comment by lwouis** [comment]
Wow that regression was introduced in May I believe (8419ad9fcebf648549488a26a03d60196add8e44). I'm very surprised no one has raised the issue before.

I'll release a fix soon
