### ISSUE TITLE
Better UX to set user preferences

### ISSUE THREAD

**Issue by lwouis** [lwouis/alt-tab-macos#49]
Current UI to set user preferences is raw:

![image](https://user-images.githubusercontent.com/106195/67402534-b25bef80-f5eb-11e9-9217-fa778197eb1c.png)

**Goal 1**

Fewer options and better validation. In order of priority:

* tab key -> dropdown or "press the key" button
* meta key + meta key modifier -> dropdown or "press the key" button
* thumbnail quality -> dropdown
* maximum size of main window -> clarify unit; maybe switch to a slider
* padding in the main window -> clarify unit; maybe switch to a slider
* padding in each cell -> clarify unit; maybe switch to a slider
* border width of each cell -> clarify unit; maybe switch to a slider
* max number of thumbnails -> maybe switch to a slider
* maximum width of thumbnails -> clarify unit; maybe switch to a slider
* maximum height of thumbnails -> clarify unit; maybe switch to a slider
* app icon size -> clarify unit; maybe switch to a slider
* font height -> clarify unit; maybe switch to a slider
* padding  between cells -> clarify unit; maybe switch to a slider
* delay in ms -> clarify unit; maybe switch to a slider

Here is HyperSwitch more refined UI as reference:

![image](https://user-images.githubusercontent.com/106195/67402468-9ce6c580-f5eb-11e9-8fc0-bd2d17825a64.png)

**Goal 2**

Better documentation. Replace current text with shorter explanations, and add either a hover tooltip or some other variation of more-info-on-demand UI, so that users who found the short text unclear can get more explanations. We can think about adding illustrations/images/videos here too to help get the point across.

**Goal 3**

Make categories like dimensions, keyboard, performance, etc. This can be tabs as is traditional on macOS, or any other approach.

**Goal 4**

Make all preferences live. Currently some of them are live, and some require a restart to apply. An easy fix would be to kill and recreate the main window on preferences change. Another brute-force approach would be to add a "restart the app" button at the bottom.

**Comment by gingerr** [comment]
I am working on some parts of this. A primer into macOS programmatic UI.

**Comment by gingerr** [comment]
Regarding **Goal 4**: Ive implemented the brute force approach -> Restart app button.

What do you mean by recreating the main window. Just a new instantiation of `ThumbnainPanel` in `Application`?

**Comment by lwouis** [comment]
> What do you mean by recreating the main window. Just a new instantiation of `ThumbnainPanel` in `Application`?

The settings that are not updatable live currently are set at boot time. For instance in `ThumbnailsPanel` initializer.

In order to have all settings be live and not require a restart, changing them should call a method an replays that init phase.

It's inefficient to recreate everything compared to manually targeting the specific attributes that were changed in the preferences, but given that the global init is fast i think it makes the code simpler to just recreate some objects rather than update specific properties

But maybe i'm wrong and it's simpler to update them. I haven't access to a computer right now so can't assess the work.

Chose the approach that has the less code and complexity since here performance is not a concern

**Comment by gingerr** [comment]
Sounds manageable.

The restart button works but it seems like it requires a new permission (dialog pops up) since it executes a shell command.

```
    func relaunch(afterDelay seconds: TimeInterval = 0.5) -> Never {
        let task = Process()
        task.launchPath = "/bin/sh"
        task.arguments = ["-c", "sleep \(seconds); open \"\(Bundle.main.bundlePath)\""]
        task.launch()
        self.terminate(nil)
        exit(0)
    }
```

Iam gonna iterate up in performance and ease of use then.
Thanks for clarification! 😎

**Comment by gingerr** [comment]
Integrating sliders now. Also removing `inputsMap`, `textDidEndEditing` & `dropdownDidChange`.

**Comment by lwouis** [comment]
I'm closing this ticket as I think that #76 covers most of the goals. The only goal that was not addressed I think was:

> Goal 2. Better documentation. Replace current text with shorter explanations, and add either a hover tooltip or some other variation of more-info-on-demand UI, so that users who found the short text unclear can get more explanations. We can think about adding illustrations/images/videos here too to help get the point across.

And maybe goal 3 could been done a bit more clearly, but this is really minor

> Goal 3. Make categories like dimensions, keyboard, performance, etc. This can be tabs as is traditional on macOS, or any other approach.

I'll close the ticket for now, and maybe someone will re-open one for further improvements. I think for the time being, the preferences are clean and usable and don't require much additional work
