### ISSUE TITLE
Add preference: additional shortcut to display windows of the current app only

### ISSUE THREAD

**Issue by lwouis** [lwouis/alt-tab-macos#50]
Suggestion from [this comment](https://github.com/lwouis/alt-tab-macos/issues/8#issuecomment-543659755)

This is how HyperSwitch does it:

![image](https://user-images.githubusercontent.com/106195/67403725-52fedf00-f5ed-11e9-83d0-58e3014fef44.png)

**Comment by mfn** [comment]
I currently run AltTab and HS side-by-side exactly because of this missing feature 😅

**Comment by lwouis** [comment]
I just released v3.3.0 which implements not exactly a second control, but at least a way to pick which windows to show. I hope you guys enjoy! 👍

If you think multiple shortcuts is still a must, feel free to open a ticket for that :)

Feel free to open a ticket if you have any issue with the new version
