### ISSUE TITLE
*-Shift-Tab for backwards navigation in the switcher

### ISSUE THREAD

**Issue by mindfulsource** [lwouis/alt-tab-macos#512]
Firstly, THANK YOU for a perfect project. After all this time waiting for HyperSwitch to improve itself and fix its bugs, we have this! It took me 5 minutes to switch. And GPL3 and Github to boot? Christmas has come all at once. :)

What's missing is *-Shift-Tab for backwards navigation. It's standard in Windows, offered in HyperSwitch, and many others.

Currently you can only navigate forward in the list pressing Tab repeatedly, but not backwards while Shift is held down in addition to the main modifier key (such as Alt or Cmd).

This request also applies to the 'Shortcut 2' (by default, single window switcher.) 

Many thanks.

(I note HyperSwitch has a design flaw in their implementation of it, it jumps back two items as Shift itself does the jumping, which isn't 'normal' or logical alt-shift-tab behaviour.)

**Comment by lwouis** [comment]
Hey @mindfulsource! Thanks for sharing this feedback!

I just replied to another user raising similar concerns in https://github.com/lwouis/alt-tab-macos/issues/510#issuecomment-670825669. Could you please check the conversation over there? You'll find there the explanation of why HyperSwitch doesn't actually have a bug ;p

In addition to this background information, and design rationale, note that you can get the behavior you describe by simply changing the shortcut from `shift` to `shift-tab` in the preferences:

![image](https://user-images.githubusercontent.com/106195/89708687-22d5d080-d9b4-11ea-9a77-6ce86b61f8b3.png)

**Comment by mindfulsource** [comment]
PERFECT! Done, and many thanks. Finally, the Mac has a powerful alt-tab which is powerfully configurable. I've been waiting a decade.
