### ISSUE TITLE
Allow arrow keys

### ISSUE THREAD

**Issue by wdfry** [lwouis/alt-tab-macos#53]
Allow arrow keys to move backward and forward between open windows when switcher is active. Right now, the only way to move backward is to shift tab, or to select previous window with mouse.

**Comment by lwouis** [comment]
Sounds like a small enhancement. I just implemented #44 today so I expect similar easy work

**Comment by lwouis** [comment]
I just released [1.8.0](https://github.com/lwouis/alt-tab-macos/releases/tag/v1.8.0) which has this feature. Check it out!

**Comment by lwouis** [comment]
**Update:** there was a regression in that release. Please [download the latest version instead](https://github.com/lwouis/alt-tab-macos/releases/latest). Sorry about that!

**Comment by wdfry** [comment]
Awesome app. Thanks for the quick fix!
