### ISSUE TITLE
Sometimes the AltTab shortcuts simply stop working.

### ISSUE THREAD

**Issue by mindfulsource** [lwouis/alt-tab-macos#531]
**Describe the bug**

This is bad enough for me to now bring this up. I've noticed it about 10 times so far, and this time, it's refusing to resolve itself without having to restart macOS (which is a big deal, obviously).

Sometimes, the set hotkeys (cmd+tab and cmd+tilde for me) simply stop working. They fail to bring AltTab up. Something is going on in the system that suddenly makes it fail. Sometimes it magically comes back after about 10 minutes. It's really random and doesn't happen that often.

This time I had a weird kernel hang on my 2019 16-inch MBP. macOS even thought the keyboard wasn't present for a brief moment (then the keyboard and trackpad worked again). Maybe related. However, at other times I don't have such a strong symptom related to this bug. It just stops working. Point is, if other apps can use the keyboard once more, so could AltTab.

**Screenshots / video**

N/A

**Steps to reproduce the bug**

I don't know. This just happens sometimes. Does the program have a log for debugging?

**A clue:**

I just tried locking the screen then unlocking. That reset it! A clue! Hooray, my AltTab is back!

**Comment by zzamboni** [comment]
I can confirm this - it has happened to me a few times, randomly, when the machine comes back from sleep. I had resorted to logging out/back in to fix it, but it's good to know locking/unlocking also works :)

**Comment by lwouis** [comment]
You're most likely experiencing #157. Please see the discussion in this thread to understand Secure Input which is the macOS mechanism at play here, and see the latest messages from me there in which i link a preview build that should workarouns this buggy mess from apple 👍
