### ISSUE TITLE
TAB key after SHIFT+CMD+TAB

### ISSUE THREAD

**Issue by kodmanyagha** [lwouis/alt-tab-macos#533]
This is very good app, thank you very much for this. I have a suggestion and a bug report.

Suggestion: I can assign SHIFT+CMD+TAB key for "Shortcut 2". Then window list is coming but it must be select previous window. It is selecting next window. This is a wrong movement.

Bug: I put macos to sleeping mode and then I'm waking it up. After wake up this app doesn't recognize open windows. Window list isn't coming after wake up from sleep mode.

Actually I'm a developer and I want to change source code of this app but I don't have experience about xcode. If you handle these suggestions then this app will be most preferred apps in the world :) Thanks.

**Comment by lwouis** [comment]
Hi @kodmanyagha! Thank you for sharing these issues!

* The first issue your described is already being discussed in #510 
* The second issue is most likely due to a bug in macOS described in #157 

I'll close this ticket as duplicate. Please follow progress in those 2 existing tickets 👍
