### ISSUE TITLE
World of Warcraft not shown in the list

### ISSUE THREAD

**Issue by Nils89** [lwouis/alt-tab-macos#536]
Hi, first, thanks for that amzing app 👍 

I had the issue, that World of Warcraft (all Versions) are not shown in the list.

Anything I can do?

**Comment by lwouis** [comment]
Hi @Nils89! Thanks for sharing this issue!

I downloaded WoW to reproduce. The WoW experience included 3 distinct app, in my case:

* The installer (i.e. `World of Warcraft Setup.app`). It is not showing in AltTab.
* The launcher (i.e. `Battle.net.app`). It shows in AltTab.
* The game (i.e. `World of Warcraft.app`). It is not showing in AltTab.

The reason these 2 don't show up is the typical reason I see with these cross-platform apps: they report themselves incorrectly to the Accessibility API, thus AltTab ignores them as they are not declaring themselves as windows.

I'll make 2 exceptions for the installer and the game. They should show in the next AltTab release 👍

**Comment by Nils89** [comment]
Thanks :)
