### ISSUE TITLE
Preferences not sticking

### ISSUE THREAD

**Issue by adrianbj** [lwouis/alt-tab-macos#54]
For some reason I had the tab key code set to 58 which obviously isn't the tab key. I tried to change to 48 in the preferences GUI, but it wouldn't stick. I had to change in the json file and now it works again.

**Comment by adrianbj** [comment]
Maybe you just fixed this: https://github.com/lwouis/alt-tab-macos/releases/tag/v1.9.4 :)

Please close if you think it's no longer an issue.

**Comment by lwouis** [comment]
Yes, indeed there was a breaking regression from `1.7.0` to `1.9.3`. More information in [this thread](https://github.com/lwouis/alt-tab-macos/issues/51#issuecomment-546418306).

It should be fixed now. Sorry about that!
