### ISSUE TITLE
dock icon badges too small with icon size = 64px

### ISSUE THREAD

**Issue by mrc247-DE** [lwouis/alt-tab-macos#559]
I refer to:
https://github.com/lwouis/alt-tab-macos/issues/523

_"It looks too small if the user sets the app icons bigger than 32px, but that can be polished later"_

I can confirm that, I have set the icon size to the maximum of 64px and the badges number are unfortunately much too small on my 27" iMac.

it's not a big problem, but the feature that the badges are now displayed doesn't make much sense, at least on a large display with very high resolution.

I love your support for the app.
I can no longer imagine macOS without an AltTab. :-)

Greetings from Germany

**Comment by lwouis** [comment]
Thank you for the kind words! And thank you for opening a ticket so we don't forget to fix this 👍

**Comment by lwouis** [comment]
Also, I was planning on implementing the badge size as a ratio of the app icon size, so it's always sitting on the top right corner. However, reading your comment, I'm now questioning if it shouldn't be a separate slider preference, as some people may want small app icons, or even no icon at all, but would like the badges to show.

Maybe I'm overthinking it, and scaling it with the app icon would satisfy everyone.

**Comment by Anon9475** [comment]
Thanks lwouis, just scaling would satisfy at least me.

**Comment by mrc247-DE** [comment]
I'm afraid the topic is not a high priority, my comment is about to celebrate an anniversary.

**Comment by lwouis** [comment]
106 open tickets, no one else but me working on them, dozens of new tickets every week i have to triage, and finally my life is very busy with big endeavors. I can only do moderate maintenance on this project at the moment.

I would love other people to contribute to the work. That way the project wouldn't stagnate when i'm too busy

**Comment by 610** [comment]
@lwouis I've just discovered this app and found this issue. The app costs $24 and this minor bug has been know for 2 years already. Whats the plan for future support and bug fixes?

**Comment by lwouis** [comment]
@610 what are you talking about? AltTab is a free open-source app.

**Comment by 610** [comment]
@lwouis I apologize for my stupid mistake, somehow google got me to this topic when I was searching for unite4 app and I didn't look at the repo name closely. Disregard my comment, please.

**Comment by mrc247-DE** [comment]
@lwouis do you think you can look at the problem again next year? :-)

**Comment by lwouis** [comment]
@mrc247-DE I'll ship this fix today in a release 👍

**Comment by mrc247-DE** [comment]
> @mrc247-DE I'll ship this fix today in a release 👍

Thank you very much for the quick implementation.

and sorry that I didn't have time to install and test the new version sooner.
At first glance, the icon badges work as expected. 👍👍👍
