### ISSUE TITLE
Highlighting of selected window isn't obvious enough

### ISSUE THREAD

**Issue by adrianbj** [lwouis/alt-tab-macos#56]
Maybe it's just me, but I find the dark highlight not distinct enough from the background to quickly see which one is selected. 

I thought I'd try the Windows theme to see if that was any better, but there doesn't seem to be any highlighting at all - maybe a recent regression?

**Comment by lwouis** [comment]
I just tested a fresh install of 1.9.5 and the Windows theme works. Did you... restart the app as suggested by the text in red at the bottom of the preferences panel? 😅

**Comment by lwouis** [comment]
I will close the ticket in the meanwhile. Please re-open if you think the contrast is still not enough, and the windows 10 theme doesn't cut it.

That being said, please suggest what to do. Keep in mind that having too many preferences is not user friendly, but so does too few. It's a balancing act. I replaced the 15 preferences like padding inside each thumbnail, with a few macro-preferences recently. I think it strikes a good balance.

A solution for your case would be to add another theme such as "Mac (high contrast)". It's literally about [adding one line here](https://github.com/lwouis/alt-tab-macos/blob/master/alt-tab-macos/logic/Preferences.swift#L40). Feel free to open a PR to add that theme/line ;)

**Comment by mfn** [comment]
I'm with @adrianbj , it's really hard.

I've dark mode enabled and it's impossible to quickly understand which one has the focus with the "macOS" theme.

With the "Windows 10" them it's rather easy, as it's a clear distinguishable white border around it.

The problematic thing is that "macOS" is the default, and the default shouldn't be hard to use.

**Comment by adrianbj** [comment]
Thanks @lwouis - I do think that it's better now. I guess the key thing is that it's always the second thumbnail/window that is selected when you first trigger it. I don't think I need the high contrast option enough to bother with it. Although perhaps the current theme could be dark mode and we could have a light mode theme for those that want it.

FYI, the Windows theme is working now also - I had restarted last time I switched to it, but definitely no white borders, but it's working now, so who knows :)

**Comment by lwouis** [comment]
> The problematic thing is that "macOS" is the default, and the default shouldn't be hard to use.

Please open a PR and make the default better. Like I said it's only [1 line of code here](https://github.com/lwouis/alt-tab-macos/blob/master/alt-tab-macos/logic/Preferences.swift#L40) to make a new theme :)
