### ISSUE TITLE
Improve the "Hold [...] and press: [...]" preference UI

### ISSUE THREAD

**Issue by caduellery** [lwouis/alt-tab-macos#560]
![Captura de Tela 2020-08-19 às 00 03 44](https://user-images.githubusercontent.com/10601241/91461983-05cc4900-e860-11ea-8c55-f613e9679ac2.png)

Actually the first sentence seems weird with a colon ":" after "press" and with "Select next..." beginning with a capital "S". Even more when the second ("then release:"), begins with a lower case. So the proposal is a more fluid text.

Something like: "Hold [...] and press [...] select next window"
And: "Then release:"

**Comment by lwouis** [comment]
But then it's no longer perfectly aligned, isn't it? Think of the OCD people ;p

**Comment by lwouis** [comment]
I updated the text with v6.2.0. What do you think of the way it reads now?

**Comment by lwouis** [comment]
Closing as the author is not responding, and I think the update is satisfying

**Comment by caduellery** [comment]
> I updated the text with v6.2.0. What do you think of the way it reads now?

Definitely better now. Thanks!
