### ISSUE TITLE
Jetbrains PHPStorm in-app notification bubbles show up in AltTab and ghost windows too

### ISSUE THREAD

**Issue by mfn** [lwouis/alt-tab-macos#562]
Version: 6.0.0 (but it was also happening in the one before, I just updated to confirm whether it still exists)
**Describe the bug**
I can trigger this with checking for updates:
![image](https://user-images.githubusercontent.com/87493/91525669-4f6d7000-e902-11ea-8f63-8ece81825d02.png)

Then this in-app notification bubble appears:
![Snip20200828_12](https://user-images.githubusercontent.com/87493/91525649-42e91780-e902-11ea-8183-7bca942ced4d.png)

And when I AltTab, it appears too
![Snip20200828_13](https://user-images.githubusercontent.com/87493/91525644-411f5400-e902-11ea-895b-52fa805bd3f7.png)

----
It _seems_ to me this is some buggy thing with PhpStorm in fact. 

For example, I trigger the update notification bubble and _don't_ AltTab but hover over it, I see the icons for closing:
![image](https://user-images.githubusercontent.com/87493/91525808-9b201980-e902-11ea-8ee9-b31cd9843630.png)

Once I AltTab and see this window in use AltTab to chose the notification bubble, those hover icons don't appear anymore:
![image](https://user-images.githubusercontent.com/87493/91525920-cefb3f00-e902-11ea-8d83-2a52bc9e1cb2.png)

----
Sometimes I open phpstorm and open projects, I can't reproduce it immediately. Needed to close it again, open a few (3?) projects, then I could reproduce it 🤷‍♀️

**Comment by lwouis** [comment]
Hey @mfn! Thanks for sharing this issue!

This is surprising as I use JetBrains products. I'm actually developing AltTab using AppCode. I tried your "Check for updates" reproduction steps, and I can't reproduce. It works correctly:

![image](https://user-images.githubusercontent.com/106195/91527319-88c4d080-e940-11ea-86c0-4bd5aebad2bb.png)

I'll download PHPStorm and test there

**Comment by lwouis** [comment]
Tested on PHPStorm, and I can't reproduce. I'm on this version:

```
PhpStorm 2020.2.1
Build #PS-202.6948.87, built on August 27, 2020
Licensed to PhpStorm Evaluator
Expiration date: September 27, 2020
Runtime version: 11.0.8+10-b944.31 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.6
GC: ParNew, ConcurrentMarkSweep
Memory: 725M
Cores: 8
Registry: run.processes.with.pty=TRUE
```

**Comment by mfn** [comment]
I use exactly the same version.

Yeah it's also not always reproducible, right now I can't either.

**Comment by mfn** [comment]
Btw, one awesome thing with the new AltTab version (I think already with 5?) is that, while it is open, I can finally use my screenshot software!

Wasn't possible before, AltTab would always close on me upon triggering the shortcuts I use (<kbd>ctrl-cmd-a</kbd>)

**Comment by lwouis** [comment]
> Wasn't possible before, AltTab would always close on me upon triggering the shortcuts I use

A trick I use for these kind of scenarios is using the built-in Screenshot.app and put a 5s timer

**Comment by mfn** [comment]
Nice tip, thanks; will remember it for such cases!

I still prefer to use https://snip.qq.com/ as they provide immediately the ability to draw on the canvas which I do 99% of the time 😆

**Comment by mfn** [comment]
In the meantime I'm on 6.1.0 and I can't reproduce it either (but it also didn't appear anymore also with the previous version) => closing!

**Comment by mfn** [comment]
Happened again right now with 6.2.0

![image](https://user-images.githubusercontent.com/87493/92408127-e2957980-f13c-11ea-8ad4-48ec21c1e6cc.png)

**Comment by lwouis** [comment]
Did it happen after your started AltTab? Like PHPStorm was already running and you started AltTab *after*?

**Comment by mfn** [comment]
> Like PHPStorm was already running and you started AltTab _after_?

No, it was running for a long time already, basically since https://github.com/lwouis/alt-tab-macos/issues/563#issuecomment-688027402

In the meantime I moved to the other version though from https://github.com/lwouis/alt-tab-macos/issues/563#issuecomment-688478090

**Comment by lwouis** [comment]
What about the 2 windows on the left of the notification window? Were they there from the beginning? Did they appear over time, did they appear exactly when the notification window appeared?

How often does this issue happen overall? Like if you close AltTab or PHPStorm now and re-open, is it going to be working fine for a while until it happens again, or is it doing it straight away?

I tried all sorts of things but can't reproduce locally.

**Comment by mfn** [comment]
> Were they there from the beginning?  Did they appear over time, did they appear exactly when the notification window appeared?

Yes, they exactly appeared together at the same time!

> How often does this issue happen overall? Like if you close AltTab or PHPStorm now and re-open, is it going to be working fine for a while until it happens again, or is it doing it straight away?

It happened this once after a while, because first time after this ticket was closed.

_Maybe_ this is a red herring thing because I temporarily used 5.3.x for the other issue. I.e. maybe I went back to the version which has this problem but maybe 6.x doesn't have it (as I said, haven't seen it since we closed the ticket which AFAIR was before 6.x was out).

I haven't seen it since 6.x but that's not a long time.

I tried some combination with closing AltTab and producing the popup notification in PS and then starting AltTab and the other way around, but not really reproducible.

Maybe I really saw this because I was on 5.x for testing the other issue after all 🤔

**Comment by lwouis** [comment]
Let's keep this ticket open, and please report here if it happens again on the latest versions. Also when it does, please try to remember the chronology of action: when did you start AltTab, when did you start PHPStorm, when did you notice the issue in AltTab.

Also how does it react if you quit PHPStorm, etc

**Comment by mfn** [comment]
Happened to me again today; very rarely this comes up:
![image](https://user-images.githubusercontent.com/87493/97259755-da43eb80-181b-11eb-958c-a3e9838425cd.png)

This is with 6.7.4, but after that upgraded to 6.8.0

**Comment by mfn** [comment]
Seems the DataGrip EAP also has this. I'm not using it as much as PhpStorm, so I didn't notice it until right now:
![image](https://user-images.githubusercontent.com/87493/97265393-dd90a480-1826-11eb-819e-594d92b35410.png)

This is with the latest AltTab 6.8.0

**Comment by lwouis** [comment]
The small blue rectangles seem to be either text selection or some suggestion? It seems IntelliJ uses window objects for a host of things. It's a cross-platform Java app after all, so it shouldn't be surprising that it doesn't integrate well in macOS.

I keep thinking these days that I should just add size check for the windows, as discussed in #456. It would probably remove all these false-positives at reasonable performance cost.

**Comment by lwouis** [comment]
@mfn here is a [local build](https://github.com/lwouis/alt-tab-macos/files/5445246/AltTab.app.zip) I made which filters out windows with no size, or a width/height < 100px. Could you try it out and let me know how it works for you? It will be helpful to not only test the Jetbrains EAP apps, but also regular apps to see that there is no regressions. It could filter out actual small windows. I can't imagine a legitimate window that users would want to see in AltTab that would be smaller than this though, but I may be wrong who knows.

**Comment by mfn** [comment]
@lwouis thank you, I just started it and was pretty quickly able to reproduce it:
![image](https://user-images.githubusercontent.com/87493/97302415-5577c280-1859-11eb-85f5-54deda3aef1a.png)

Double checked it's not a "released" version:
![image](https://user-images.githubusercontent.com/87493/97302438-60325780-1859-11eb-8f06-bd155405e057.png)

Now that I think of it, that's definitely a DataGrip EAP thing, I had nothing like that every before. Not in that amount and so easily happening.

**Comment by lwouis** [comment]
How can these window show when I added the size check? They must be bigger than 100x100 but have transparent regions 🙉 

I'll try installing DataGrip to see if I can reproduce. You're making me install the whole Jetbrains suite ;p

**Comment by mfn** [comment]
> You're making me install the whole Jetbrains suite ;p

I am so sorry for that 😱 

Well, it's a good suite. The DataGrip EAP is at https://www.jetbrains.com/datagrip/nextversion/

However I do have db connections set up, query them, copy paste columns content (e.g. json), create temporary window to reformat it => so they kind of actions _might_ relate to what kind of "windows" are created…

**Comment by lwouis** [comment]
You mean these are not present after a start? They only appear after you use the app a bunch?

If you could find which steps specifically trigger this, that would be ideal

**Comment by lwouis** [comment]
Omg yes! I could get one glitchy window finally! I set up a connection, and did come copy pastes. I think it's having a tooltip show up on hovering the table that did it though.

I'll finally be able to see these windows characteristics!

**Comment by lwouis** [comment]
Oh wow! There was a logic bug in a long boolean expression, and after spending 10min looking at it I realized why it was not filtering these windows. I'm surprised not more apps were impacted by the logic bug.

I'm going to push a public release with this change. Could you please tell me if [this build](https://github.com/lwouis/alt-tab-macos/files/5445495/AltTab.app.zip) fixes it for you?

**Comment by mfn** [comment]
Yes, I think it works now with your latest build. Fooled around in DataGrip but could not reproduce it.

**Comment by mparry** [comment]
Thanks for the fix! This has been annoying me in the current CLion EAP for a while but I hadn't got around to reporting it.

**Comment by mparry** [comment]
I am actually still seeing this in CLion EAP a little bit, but it's miles better than it was. I think you've successfully filtered most of the spurious windows that it's creating, but there does seem to be one or two still sneaking past. I'll post again here, or open a fresh issue, if I figure out what they are.

**Comment by lwouis** [comment]
@mparry that's surprising. A screenshot would help here. My assumption was that these windows are small pieces of the UI that Jetbrains coded as dialogs or windows, but that are not that to end user. Probably it's their Java UI (they use Swing I think?) frameworks that maps to macOS AppKit this way.

Based on what thumbnails are shown, i assumed that it would be filtered by not listing windows with no size, or with a size < 100x100.

If you're still seeing glitchy windows it means they are larger than that. It may be a different situation then. It would help if I could see what it looks like. Also as you said, your guess as to how trigger their apparition and what they depict would be most helpful

**Comment by mparry** [comment]
<img width="627" alt="Screenshot 2020-10-29 at 10 53 09" src="https://user-images.githubusercontent.com/20336381/97559628-9694e180-19d5-11eb-97ea-75fb7b90462c.png">

**Comment by lwouis** [comment]
Do you have consistent steps to reproduce? I need to get it locally to understand why the window is not filtered by it's size since it looks to be nil

**Comment by mparry** [comment]
Sorry, no. Indeed, it hasn't occurred at all today. I did pick up a Rider EAP update this morning, so it's possible they've altered something. Unless anyone else is still seeing anything, I'm personally quite happy for you to leave this issue closed, until more concrete details are available. As I said above, it was rather annoying before because there might be 10+ spurious windows in AltTab, but I haven't seen more than 1 since your last change (and 0 today).

**Comment by mparry** [comment]
I still don't have a repro but here's a somewhat more informative screenshot:

![Screenshot 2020-11-02 at 16 39 59 (2)](https://user-images.githubusercontent.com/20336381/97894674-afc9c500-1d2a-11eb-95b4-a34aeed8f49f.png)

As you can see, it's a tooltip. However, this certainly doesn't happen every time a tooltip is shown.

**Comment by lwouis** [comment]
Tooltips are not showing for me in CLion (public release, not EAP). That's the IDE I use to develop AltTab, so I think I would have run into the issues by now. This makes me think it's EAP specific, which is also what I observed above with PHPStorm or DataGrip.

It would be nice to get Jetbrains perspective on this issue by reporting it to them. They may shed some light on what they changed in the EAP channel that could create this issue.

**Comment by Alexsey** [comment]
I can confirm the bug is still there and relevant for the WebStorm as well. Althought, after the last fix, it become much harder to reproduce - I can work for half a day and not seen any empty items

**Comment by mparry** [comment]
One way that I can make it happen slightly more reliably - maybe 50% of the time? - is to invoke AltTab while I am actually hovering over code so that a tooltip displays - the tooltip is often then present in the window list. Most of the time, it will disappear if I stop hovering (rather than leaving something permanently in the list, as I see less often) but perhaps this would at least help figure out why it's getting past your filtering.

**Comment by Alexsey** [comment]
Yes, I agree with @mparry - it's relatively easy to get the tooltip to alttab with the proposed way (about 20-40% in my case). But tooltips in alttab are not persistent - they will disappear after the tooltip close. But sometimes there can be empty socets that would persist untill IDE restart, like in the initial issue - and that one are much harder to reproduce :( Will keep an eye on what can couse them

**Comment by lwouis** [comment]
> relevant for the WebStorm as well

Are you using WebStorm EAP or stable release?

**Comment by Alexsey** [comment]
EAP

**Comment by mfn** [comment]
Had this happen today again to me with latest AltTab and EAP:
![image](https://user-images.githubusercontent.com/87493/99071689-e9b08c00-25b2-11eb-8afd-8c13c1818a6d.png)

Just for documentation. But it really happens rarely.

The notification window in question was already long gone at the point I saw it here. Neither focusing not closing it via AltTab was possible.

I even closed all PhpStorm windows so that only the "project chooser" / welcome screen would appear and they would still be displayed via AltTab.

Only when I completely closed PhpStorm, they were gone.

I forgot to test what would have happened if I would have restarted AltTab.

**Comment by lwouis** [comment]
Do you see these windows normally in AltTab? I mean in addition to the fact that they remain after they are closed. It seems from the visuals that these shouldn't appear ever. The issue would be 2 sided: how can this show up in the first place, and how come once it's shown it stays there even when it's closed.

**Comment by mfn** [comment]
> Do you see these windows normally in AltTab? I

No, not at all!

And I absolutely agree with this:
> how can this show up in the first place

I think they shouldn't show up in the first place.

> and how come once it's shown it stays there even when it's closed.

To be clear, I wrote:
> I even closed all PhpStorm windows so that only the "project chooser" / welcome screen would appear and they would still be displayed via AltTab.

What I mean with this is, the "process" of PhpStorm was still present all along. It's just _within_ the various open project windows have been closed.

Granted, I know nothing technically about all this but I can imagine that unless the process disappears, there are still some dangling references. So that even if I close the "main window" of a project, the overall java process is still there (and AFAIK PhpStorm & friends run in a VM which only shuts down if you truly completely quit PhpStorm, not just when I close a project window).

**Comment by mfn** [comment]
I've one such window currently. It's a pretty big one (a "notification bubble" for a git commit message with it's content can be quite big on the screen), but again usually this doesn't happen:
![image](https://user-images.githubusercontent.com/87493/99264694-18339e80-2821-11eb-9379-96997e965049.png)


> I forgot to test what would have happened if I would have restarted AltTab.

I now did test this and after stopping/starting AltTab, this window disappeared ❗ too.

**Comment by lwouis** [comment]
I just released v6.13.0 which should fix the issue on all Jetbrains apps 👍 Please let me know if you still face issues on that version

**Comment by FirstTimeInForever** [comment]
Seen this issue with current IDEA EAP (2021.1-EAP).
For the context: IDEA was performing indexing and importing gradle project.
AltTab version `6.15.0`
![image](https://user-images.githubusercontent.com/7830574/107646627-39265700-6c8b-11eb-8ecd-1674fa8200a5.png)

**Comment by lwouis** [comment]
I think it would be nice to open tickets in Jetbrains support system, in addition to workaround their bugs on AltTab's side. Issues where AltTab displays wrong windows are always because app authors use `NSWindow` for things that are not windows. Jetbrains uses Swing I believe, so they do their UI through abstractions that map poorly to AppKit on macOS. This is the root cause. They should address it. In addition to us working around the issue in the meanwhile.

**Comment by lwouis** [comment]
I witnessed this today. Very interesting:

![image](https://user-images.githubusercontent.com/106195/109265636-35c5ca80-784a-11eb-83f8-d16b8638b9ab.png)

![image](https://user-images.githubusercontent.com/106195/109265651-3a8a7e80-784a-11eb-949d-2850f9184211.png)

![image](https://user-images.githubusercontent.com/106195/109265656-3e1e0580-784a-11eb-8f52-be54c1d982ed.png)

You can see on the last screenshot that Mission Control is showing the 2 IntelliJ notifications. Even to the OS, these are independent windows, and not light HUDs. AltTab is here doing "better" than the OS, showing that the issue is with IntelliJ to begin with.

**Comment by lwouis** [comment]
I witnessed another tooltip showing in AltTab today. Here are the logs for it:

```
Optional("com.jetbrains.AppCode") Optional("") 0 Optional("AXDialog") Optional("AXWindow") Optional((333.0, 110.0))
```

* It has an empty title, but some legitimate windows don't have a title either, so we can filter based on that.
* It's a `AXDialog`, but popups should be shown in AltTab, so we can filter based on that.
* It has a width and a height bigger than the 100px limit we set in AltTab, so we can filter based on that.

Currently I don't think there is any way we could prevent such popups showing in AltTab. It's really Jetbrains who ought to not implement their tooltips using `AXDialog` `NSWindow`.

**Comment by AfzalivE** [comment]
Anyone also finding that when AltTab is running, some of the popups just don't disappear? Not sure if it's happening in PHPStorm as well but it's definitely happening on the beta/canary versions of Android Studio.

**Comment by lwouis** [comment]
@AfzalivE if it's only happening on the beta/canary, then it's clearly a regression. I suggest you open a ticket with Jetbrains to get someone from their team to look into the issue

**Comment by twyatt** [comment]
Related Android Studio bug: https://issuetracker.google.com/issues/189250915
