### ISSUE TITLE
[Question] How do I add "Activity Monitor" to the blacklist?

### ISSUE THREAD

**Issue by boldandbusted** [lwouis/alt-tab-macos#564]
Howdy. Thank you for Alt-Tab, it really makes moving around windows and applications much easier. :) So, the question I have is in the subject. I tried naively entering "Activity Monitor" into the Blacklist, but that doesn't seem to be working. Cheers!

**Comment by lwouis** [comment]
Hi @boldandbusted!

The blacklists take applications `bundleIdentifier`s. ActivityMonitor's is: `com.apple.ActivityMonitor`. So please add this to blacklist it.

I'm sorry it is not very user friendly. There is a ticket open to improve it #539, so hopefully it gets better 👍

**Comment by boldandbusted** [comment]
Thank you very much! Shall I close this for ya?

**Comment by lwouis** [comment]
Happy it's working for you now!

Thank you for sharing this tip to find the ID using Activity Monitor. It's pretty easy to do indeed. Ideally we will add a list of app to select so it will be even easier 👍
