### ISSUE TITLE
Contentless previews of hidden app shown in Alt Tab

### ISSUE THREAD

**Issue by anh-chu** [lwouis/alt-tab-macos#577]
Hi.

I am 6.2.0, MacOS Big Sur (I know). After updating from 6.1.0, now AltTab shows even windows that I have hidden as contentless previews as seen here.

![IMG_0099](https://user-images.githubusercontent.com/34973633/92327455-1c567980-f084-11ea-8051-9e5077d74a67.JPG)

**Comment by SoPat712** [comment]
This is a feature, not a bug. You can turn it off in settings if you don't like it by checking `hide apps with no open windows`

**Comment by anh-chu** [comment]
Thanks, I didn't know about that setting.
