### ISSUE TITLE
Previous window rectangle sticks around for a couple of seconds before completely switching apps.

### ISSUE THREAD

**Issue by SoPat712** [lwouis/alt-tab-macos#578]
**Describe the bug**

The previous window portion behind the alt-tab overlay sticks around in space of the new window for like 1 second before being filled up by the new content. It's a difficult bug to catch, and probably small, but it would be great if it could get fixed, as it's extremely annoying to wait 1 second between app switch trying to let the window catch up with app switching. This did not happen with versions < 6.2.0, so the code to cause this bug must have been exposed in this newest version of the app.

**Screenshots / video**

This is not really something I can very easily get a screenshot of, and to be completely certain, I'm not sure if this is even reproducable

**Steps to reproduce the bug**

See above.

You can try switching apps very fast to catch it, but I switched apps pretty slowly and still got the issue. If this bug isn't clear enough, don't hesitate to ask questions in the comments

**Comment by lwouis** [comment]
Hey @SoPat712! Thanks for sharing this issue!

It has already been identified by another user, and is being discussed in #563. I'll close this ticket as duplicate, so we can keep the conversation in one place
