### ISSUE TITLE
Max Size is too inflexible on ultrawide monitors

### ISSUE THREAD

**Issue by Tomcc** [lwouis/alt-tab-macos#579]
**Describe the bug**

First of all I'm really not sure if this is a bug or a feature request... but if you squint you could see it as an accessibility problem for widescreen users, so it may be a bug :)

When using an ultrawide monitor (eg. 5122x1440), there is no ideal setting for the window size.
The default 80% is e x t r e m e l y w i d e, and reducing it to a % where it would make sense causes the height to be too small and needlessly hide rows.

**Screenshots / video**

This is what 80% looks like:
![Screen Shot 2020-09-07 at 00 53 28](https://user-images.githubusercontent.com/553214/92362488-ed043480-f0a4-11ea-914a-c28eb5aba2c5.jpg)
Most of the space is wasted and it forces me to turn my head to look at the options all the way on the left.

And this is what the width I would like (15%) looks like:
![Screen Shot 2020-09-07 at 00 54 01](https://user-images.githubusercontent.com/553214/92362548-00af9b00-f0a5-11ea-9142-e4afd7ceb21d.jpg)

Now the width is ok, but it's not high enough and it's hiding rows for no reason.

I think the issue here is that width and height should be decoupled... and personally I think that defining the width using a % doesn't work well if someone uses many different screens with their Mac, the panel's size will be all over the place.
For my use case where I want a column of options, setting a max size in pixels would be much nicer.

**Steps to reproduce the bug**

1. Find an ultrawide monitor
2. Try to use Alt Tab and fiddle with the Max Size %
3. See the above

**Comment by lwouis** [comment]
Hey @Tomcc! Thanks for sharing this feedback!

AltTab currently doesn't support your use-case. Thus I'm flagging this as an enhancement.

I think you're right that the best way to support this layout is to split `Max size on screen` into `Max width on screen` and `Max height on screen`.

I'll also take the opportunity to:

* Rename `Min/Max windows per row` into `Window min/max width in row` for more clarity on what these sliders d
* Rename `Rows of windows` into `Rows of thumbnails`, as this setting only applies if to thumbnails
* Make it so checking `Hide window thumbnails` disables `Rows of thumbnails` to illustrate the relationship of these 2 sliders
* Make it so it's impossible to have a `Window min width in row` bigger than `Window max width in row`

Actually, I've done the work already. Here is a [video showcase](https://www.loom.com/share/2536d15599534b8b9fa38495b78a462b). Let me know what you think.

It will ship in the next release

**Comment by Tomcc** [comment]
Wow, I don't think anyone ever fixed a bug I reported with a video showcase, I don't even know what to say :)

Thanks for fixing this so quickly! It looks like it does allow me to , I'll try it when the new version is out.

And thanks again for making Alt Tab, I was using Contexts but I had a few issues with it. This one is so much better!
