### ISSUE TITLE
Add option to display all windows of all *visible* screens in multi monitor setup

### ISSUE THREAD

**Issue by BFriedrichs** [lwouis/alt-tab-macos#583]
**Is your feature suggestion related to a problem? Please describe.**
This (I think) only applies when the native setting "Screens have separate spaces" is enabled.
Currently when this setting is enabled:
* **"Active Space" + "All Screens"** only shows the windows of each individual monitor (given the currently active space).
* **"All Spaces" + "All Screens"** shows windows from both spaces but also all other non-visible spaces.

This comes down to what I assume macOS considers to be an active space vs. what I as a user consider to be my active working space.

**Describe the solution you'd like**
I would like to see an additional setting that allows me to see all windows from all *visible* spaces.
I'm sadly not sure if it's possible to detect if spaces are visible but it would be ideal. 

**Describe alternatives you've considered**
I don't think this applies for this request.

**Comment by lwouis** [comment]
Hi @BFriedrichs! Thank you for sharing this suggestion!

Just so I understand clearly:

* This applies only to multi-monitor setups
* Today you can only show `All Spaces` or `Active Space` (space with the keyboard focus)
* You want to have a new 3rd option: `Visible Spaces`. It would show windows from all Spaces which the user can currently see on their displays.

I think it's a good idea. I'm using a single monitor, so for me active Space = visible Space, but on a multi-monitor setup, you can view multiple Spaces, yet only one of them is active (receives keyboard input).

On the feasibility side, it's most likely doable. There are many private APIs too in that area, so I think tech won't be a blocker.

**Comment by BFriedrichs** [comment]
This is exactly correct, thank you for the fast response :) I'm looking forward to it

**Comment by JiaboHou** [comment]
I too would love to see a feature like this, and am willing to help test this if needed!

**Comment by lwouis** [comment]
I would really like to implement this. I'm completely swamped with work and personal life though, otherwise it would be done already. It should be a reasonably small addition so anyone interested to contribute, consider getting your feet wet 👍

**Comment by lwouis** [comment]
I implemented this ticket 🥳

Could you please try out [this test build](https://github.com/lwouis/alt-tab-macos/files/5518218/AltTab.app.zip) and let me know if it works for you? Here are some scenarios I used to test the feature:

* Plug external monitor
* Unplug external monitor
* Create new space
* Delete space
* Mirror internal and external displays
* `System Preferences > Mission Control > "Displays have separate Spaces"` checkbox checked, and unchecked

I didn't have time to test the last item, so your help here would be greatly appreciated 👍

**Comment by BFriedrichs** [comment]
It's working beautifully for me, thank you :) I have the `"Displays have separate Spaces"` option enabled. 

The only thing I noticed is that when activating AltTab immediately after switching to a different space using a keyboard shortcut it shows the windows of the previous space, but I assume thats down to the animation not being finished and realistically is not an issue at all.

**Comment by JiaboHou** [comment]
Testing this out right now, and it seems to work great so far. Thank you so much!

**Comment by lwouis** [comment]
> The only thing I noticed is that when activating AltTab immediately after switching to a different space using a keyboard shortcut it shows the windows of the previous space, but I assume thats down to the animation not being finished and realistically is not an issue at all.

Interesting. I think that's a regression introduced quite some time ago. I think it's already happening on the public release.

**Comment by lwouis** [comment]
I'll release this, and opened another issue for the issue spotted by @BFriedrichs above

**Comment by tbena** [comment]
I see his issue is closed and that the option was renamed to visible spaces but I still get the original behavior described in this issue. I only see windows from the active space and not from the other visible space on the other monitor.

**Comment by lwouis** [comment]
Hi @tbena,

Could you please open a new bug ticket? In the template, you will be able to share steps to reproduce as well as a video of the issue. This way, we can diagnose together if it's a misunderstanding or a bug, and if it's a bug it can get debugged and fixed.

Thank you 🙇
