### ISSUE TITLE
Alternatingly switching beween apps and in-app windodows briefly shows old alt-tab window

### ISSUE THREAD

**Issue by mfn** [lwouis/alt-tab-macos#586]
**Describe the bug**

I noticed this maybe starting with 6.2.0 (?) and now paid more attention (6.3.0).

- Switch between apps
- Then start switching between windows of an apps
- For a fraction of seconds, the "all apps windows" is shown, then the "in-app windows" are shown

This also works in reverse: switch between in-apps, then switch apps: for a brief moment the old in-apps windows appear and are then "overwritten.

It's best noticeable if you really concentrate on that and quickly switch around, although "being quick" isn't relevant. It _is there_, like: once you see / know if, hard to un-see.

**Comment by lwouis** [comment]
Hey @mfn! Thanks for pointing this issue out!

I noticed this also yesterday. I think it was introduced when I fixed the visual glitch when switching between 2 monitors of different resolution

**Comment by lwouis** [comment]
I think the latest release 6.5.0 fixed this issue

**Comment by lwouis** [comment]
@mfn could you please confirm if the issue is fixed or still happening? Thank you!

**Comment by mfn** [comment]
Thank for the ping! I don't recall seeing this in recent times, I was on a semi-up2date version and I'm on the latest incidentally since few days, not having seen it either.

Closing in good faith 🤞 , thank you!
