### ISSUE TITLE
Input field for window apparition delay not wide enough to handle more than 2 digits without wrapping.

### ISSUE THREAD

**Issue by adrianbj** [lwouis/alt-tab-macos#59]
![image](https://user-images.githubusercontent.com/871211/67629548-94350000-f834-11e9-850d-a46196222174.png)

**Comment by lwouis** [comment]
I'm aware that the preferences are pretty rudimentary for now. I added this to provide an easier option than editing the JSON file directly.

I'll close this ticket as plans to improve and overall roadmap for better UI are detailed in #49.
