### ISSUE TITLE
Latest version Alt-tab shows apps whose windows are closed.

### ISSUE THREAD

**Issue by acharkq** [lwouis/alt-tab-macos#592]
**Describe the bug**

In the latest version, alt-tab shows apps whose windows are closed.
<img width="1440" alt="Screen Shot 2020-09-09 at 15 19 01 (2)" src="https://user-images.githubusercontent.com/34520988/92567520-6459e400-f2b0-11ea-9ffc-35bbbb7282af.png">

But in the setting, I have selected not to show apps whose windows are closed.
![Screen Shot 2020-09-09 at 15 23 46](https://user-images.githubusercontent.com/34520988/92567566-763b8700-f2b0-11ea-900b-4ccb83306c3b.png)

**Comment by acharkq** [comment]
I just fixed this by deleting the previous preference file

**Comment by lwouis** [comment]
Hi @acharkq! Thanks for sharing this issue!

I'm a bit confused by what you explained here.

You say that you updated to 6.4.0, and that broke this feature:

![image](https://user-images.githubusercontent.com/106195/92594656-0e9c3080-f2de-11ea-882d-4ab5e7b71dd1.png)

I don't think there is code from 6.3.0 to 6.4.0 that touches that feature

**Comment by acharkq** [comment]
Sorry, this is the first screenshot that I should have uploaded. This screenshot shows what the problem looks like.

![Screen Shot 2020-09-09 at 15 19 01](https://user-images.githubusercontent.com/34520988/92595302-bca3dc80-f2d6-11ea-8752-d44bf9057491.png)

I actually upgraded from 6.2 to 6.4.

**Comment by lwouis** [comment]
This feature was introduced in 6.2.0. So when you updated to 6.2.0, you say you didn't want it (it is enabled by default), so you went into the preferences and you checked the box from my screenshot above?

Then when updating to 6.4.0, you noticed that the feature was re-enabled? And checking/unchecking the preference was not working? So you had to manually delete the preferences file?

**Comment by acharkq** [comment]
I think the checkbox for hiding apps with no open windows should have been there for a long time.

I remember to have checked that box when I first use your app, maybe a month ago.

And Yes, the checking/unchecking now is not working. If I uncheck the box now, I couldn't find windows for apps who don't have open windows.

Thank you for being responsive and thank you very much for developing this app.
