### ISSUE TITLE
delay after updating from 6.2.0 to 6.4.0

### ISSUE THREAD

**Issue by mrc247-DE** [lwouis/alt-tab-macos#594]
after updating from 6.2.0 to 6.4.0 I notice a big delay when, in my case, pressing command + tab.

It doesn't always happen, but it happens frequently and causes irritation.

best regards

**Comment by lwouis** [comment]
Hey @mrc247-DE! Thanks for reporting this issue!

I'm aware of it, and we are discussing this in great details in #563. Let's keep the conversation in one place 👍

**Comment by mrc247-DE** [comment]
I'm sorry, I haven't seen that there is already a topic.
