### ISSUE TITLE
AltTab taking as slow as 1.5 seconds to open, much of the time

### ISSUE THREAD

**Issue by mindfulsource** [lwouis/alt-tab-macos#595]
**Describe the bug**

Since the latest release (or the one just before it, in the past day or two), AltTab more often than not takes very long to open, then right after that, opens fast as normal. Maybe after a couple more minutes again, it's slow the first time. That makes it slow basically most of the time. Must be bug in current latest version.

**Screenshots / video**

Video:

https://streamable.com/ntjmbq

I had accessibility show keypresses. Note the first one, how long it takes to open, then other ones fast as normal.

**Steps to reproduce the bug**

I'm not sure, but as you can see, a minimal 'fresh' install triggers it, just have a lot of windows open.

**Comment by lwouis** [comment]
Hey @mindfulsource! Thanks for reporting this issue!

I'm aware of it, and we are discussing this in great details in #563. Let's keep the conversation in one place 👍
