### ISSUE TITLE
Possible to pass through shortcuts to "blacklist" apps?

### ISSUE THREAD

**Issue by max-sixty** [lwouis/alt-tab-macos#599]
**Describe the bug**

I've been using AltTab for a few days now and really enjoying it. Thanks again for the excellent app!

Here's a case of a small issue I'm having. It's probably a narrow case for a narrow set of users, so I wouldn't imagine it's worth prioritizing, but posting here if it's helpful to know about. And it might well be an issue with NoMachine, which seems to interact with MacOS in idiosyncratic ways.

**Screenshots / video**

(I'm not sure these would be helpful in this case but let me know anything else you need)

**Steps to reproduce the bug**

- I use a remote app "NoMachine", which uses the alt+tab shortcut internally (it's a remote desktop solution that connects to a Linux machine, which itself uses alt+tab)
- I've added `com.nomachine.nxdock` to the "Blacklist"
- When I hit alt+tab with NoMachine is selected, AltTab (the app) doesn't show, as expected. 
- But alt+tab (the keys) don't seem to pass through to NoMachine. It doesn't show Linux's app switcher (i.e. nothing happens)
- If I change the shortcut in AltTab to alt+ctrl+tab, then alt+tab does get passed through to NoMachine
- Ideally apps on the "Blacklist" would have shortcuts passed directly through

**Comment by lwouis** [comment]
Hi @max-sixty! Thank you for sharing this issue!

Indeed, this is a regression introduced in v5 when I rewrote the whole keyboard input system, to avoid the Secure Input issue in macOS.

I have found a way to have this work as you expect. This will be delivered in the next-next release (next release is a hotfix for a crash at launch) 👍

**Comment by lwouis** [comment]
Closing this issue as it should be fixed now. Please let me know if it persists somehow 👍

**Comment by max-sixty** [comment]
Thanks @lwouis !

**Comment by max-sixty** [comment]
Just to confirm, this is working really well!
