### ISSUE TITLE
Does hide window thumbnail still require screen recording permission?

### ISSUE THREAD

**Issue by mustafawm** [lwouis/alt-tab-macos#600]
Hello,

Thanks for your work, the app looks really good 👍

Currently the app does not start unless both permissions are granted but does it have to be this way?
<img width="507" alt="Screen Shot 2020-09-11 at 9 26 59 pm" src="https://user-images.githubusercontent.com/13101565/92920369-88b2ed80-f475-11ea-813e-a64fa42de55f.png">

It says that the `screen recording`  permission is needed for the thumbnails option so can we have it so if the screen recording permission is not granted, only this option be disabled (instead of the whole app not starting up)?
<img width="417" alt="Screen Shot 2020-09-11 at 9 30 24 pm" src="https://user-images.githubusercontent.com/13101565/92920670-02e37200-f476-11ea-9b4a-d788f9038deb.png">

**Comment by lwouis** [comment]
Hey @mustafawm! Thanks for your feedback!

You can see on the screenshot you took that the permission is not only about screenshots but also titles of windows. It is also probably required for more internal things like getting window characteristics like size, position, role, etc.

Basically I had this thought before when i introduced the checkbox, but realized the dependencies run deep, and it's not possible
