### ISSUE TITLE
Zoom doesn't show up among running apps

### ISSUE THREAD

**Issue by Stokestack** [lwouis/alt-tab-macos#603]
**Describe the bug**
When you're in an active Zoom session, Zoom doesn't show up in Alt-Tab. It does show up if you've launched the app and it's just sitting on the log-in screen.

**Steps to reproduce the bug**

Have Alt-Tab running.
Start a Zoom session.
Try to Alt-Tab between other apps and Zoom.

**Comment by lwouis** [comment]
Hi @Stokestack! Thank you for sharing this issue!

I tried to reproduce, and it works great. I can see Zoom's home window, and also ongoing video-meeting windows.

Could you please share a video to help clarify what exactly is not working, and how to reproduce the issue?

Thank you!

**Comment by SoPat712** [comment]
This is happening to me too actually. I've been using Zoom for work, and the zoom meeting windows randomly disappear from alt-tab. This usually happens after a couple times switching between apps, and the window just randomly disappears. I'm not sure how to reproduce it, but I'll look into getting a video that you can watch.

**Comment by lwouis** [comment]
Oh so it's not as the OP described: it doesn't show up ever. It's more an intermitent issue where sometimes after moving focus around it would not show anymore?

That sounds like an issue with tab detection, which is a very fragile heuristic in the app

**Comment by SoPat712** [comment]
Is there any way I could send you app logs for alt-tab between some time to another time of me using zoom? I'm not able to reproduce it while having the video recording for some weird reason, I think I'm doing something differently but I'm not sure what to fix?

**Comment by lwouis** [comment]
I don't have advanced logs in the app, especially on release builds since i want the app to be low impact on the user machine and high performance. So logs are limited in what I can deduce from them.

It's very much an exercice in me need to understand what situations/steps lead to the issue, and then I would be able to reproduce and fix it.

**Comment by Stokestack** [comment]
In my case it is as described: **When streaming**, Zoom **never** appears in Alt-Tab. It **does** appear if it's **sitting on the log-in screen**

Perhaps some of the reports of sometimes/sometimes-not are overlooking this condition.

**Comment by lwouis** [comment]
In my case, I see the login window, and meeting windows. I see every window, all of the time.

@Stokestack you're saying that you never see the meeting windows? That is, fullscreened and not fullscreened? Could you share a video of that? I think we may all be talking about different things when we say "when streaming" or "meeting windows".

Also please all share which version of Zoom you're using. It's probably one of the factors at play here

**Comment by SoPat712** [comment]
My Zoom version is 5.3.0, which I believe is the most recent Zoom version.

**Comment by Stokestack** [comment]
I just tried this again. In a Zoom session with a single participant, Zoom did show up in Alt-Tab. It's the only time I've ever been able to see an active Zoom session in Alt-Tab. I never full-screen it, so I don't think that has any significance.

When I say "streaming,' I mean that you are communicating with people over Zoom and not just sitting there with the log-in dialog up (which has always shown up in Alt-Tab).

**Comment by lwouis** [comment]
Could it be about single-participant vs multiple participants? Could it be about the view selected like grid view, presenter view, etc?

**Comment by SoPat712** [comment]
I've updated Zoom and Alt-tab, and don't have this issue anymore? @Stokestack you might want to look into uninstalling both apps and using something like AppCleaner to remove all files and then reinstall both apps fresh.

**Comment by SoPat712** [comment]
Nevermind, I just got it again in this current Zoom meeting. I killed Alt-tab, and now it shows up again.

**Comment by lwouis** [comment]
It really sound to me like some tab detection false positive. Perhaps it's the way the meeting window starts instantly fullscreened? Do you have such a setting, or does it launch as a normal window, then you fullscreen it? Is the window always not listed in AltTab, or is is listed, then after fullscreening it, it's no longer shown?

**Comment by SoPat712** [comment]
Zoom meetings always launch first as a windowed app, but automatically fullscreen. That may be causing problems? The zoom meeting windows don't show up all the time(the actual meeting), but the main window 

![image](https://user-images.githubusercontent.com/30350506/94345087-81511f80-fff1-11ea-9687-6cf92ca69cf7.png)


always shows up for me. That makes me inclined to think this happens because of the zoom fullscreening windows behavior.

**Comment by SoPat712** [comment]
I've just looked into it, and found that there is a setting that may possibly be causing the problem.

![image](https://user-images.githubusercontent.com/30350506/94369496-ff77f980-00b7-11eb-85b2-b9d67306f418.png)

I've turned it off, and will get back to you if the problem happens again @lwouis. @Stokestack I recommend you do the same.

**Comment by SoPat712** [comment]
It happened again, even with the setting turned off. Thoroughly confused as to why. It mostly happens whenever a participant starts screensharing, I can look into that more over the course of the day.

**Comment by lwouis** [comment]
The setting was off, but was the meeting window fullscreened? My guess is that the issue stems from the tab detection code flagging the meeting window as being a tabbed window, thus not showing it. It's my best guess based on the behavior described in this ticket. I can't reproduce locally so i can only guess.

Was the window fullscrened? Could you see it in AltTab originally? Then someone started sharing their screen: did the meeting window change like split into 2, resized, exit and re-entered fullscreen?

You can also check the preference in AltTab to "show standard tabs as individual windows". If that brings the meeting window which was previously missing, then it's a clear confirmation that tab detection heuristic is misbehaving

**Comment by SoPat712** [comment]
When Zoom started up, the window now starts up as a normal window. I do manually fullscreen Zoom, but I'm not sure why that would change anything. When someone starts screen-sharing, the window layout change is from gallery mode with 20 people to one zoom window for the screen-share, and the weird floating sidebar thingy that Zoom creates. Zoom remains fullscreen during this change. I've tested it myself, and breakout rooms also induce this behavior. I've also noticed that the automatic fullscreen preference doesn't apply to breakout rooms, and while I don't use this in any of my meetings, it might lead back to a solution.

I don't know what a standard tab is, but I'll turn that on today and see if that fixes any problems. Thanks for all the help!

**Comment by SoPat712** [comment]
Hey, the video was a great explanation of the faults of MacOS. I will try and get a video, but for the privacy of the people in the Zoom call, I will try and blur their faces when I record the issue taking place. Either way, I have turned on show standard tabs as windows, and I hope that that is able to fix the issue!

**Comment by Stokestack** [comment]
Great video, and very informational for all Mac OS developers and users. Thanks!

This, like so many other UI flaws in Mac OS, arise from the same stupid mistake: forcing all applications to share a single menu, which turns your entire desktop into a single window.

I'm not surprised that full-screening an application essentially makes it into a tab; a tab of the always-present desktop window. I'll spare you my lecture on why every other desktop GUI does windows and menus right, and Mac OS does it wrong. But what you're trying to work around here is a great example.

**Comment by SoPat712** [comment]
This issue has been fixed for me in the experimental build you posted in one of these threads. I've constantly been using Zoom over the last week or so, and haven't had it happen to me yet. 

It might also be because of the "show standard tabs as windows" option. Either way, the problem is gone for me personally.

**Comment by lwouis** [comment]
@Stokestack do you still have the issue, or can I close this ticket?

**Comment by SoPat712** [comment]
I'm actually having the opposite issue. The login window or the meeting window is sticking around even after the app is quit. I can get you a screenshot today.

**Comment by SoPat712** [comment]
This issue was technically solved when I set the preference show standard tabs as windows though. I can open another issue if you'd like?

**Comment by lwouis** [comment]
@SoPat712  If you're referring to "The login window or the meeting window is sticking around even after the app is quit", yes please, create another issue. You will have the template to help you fill the issue so that it's actionable for me 👍

**Comment by SoPat712** [comment]
Ok, I just turned off "Show Standard tabs as windows", and now I'm not seeing Zoom half the time too. So Zoom is just completely broken now. The meeting window sticking around is a problem, along with Zoom not showing. I think both issues should stay open for the time being.

**Comment by thirtythreeforty** [comment]
I have this problem.

Specifically it happens to me when a window is maximized: I have a multi-monitor setup, and Alt-Tab is configured to show only windows on that screen. However, if a window overlaps _one pixel_ onto the other monitor, it shows up in _neither_ screen's Alt-Tab listing!

**Comment by SoPat712** [comment]
Please enable this

![image](https://user-images.githubusercontent.com/30350506/99854368-b2ae1d80-2b52-11eb-865c-603fa6d8f48c.png)

You may get issue #668 , but it's better to have more windows than no windows at all.

**Comment by SoPat712** [comment]
@lwouis I haven't had this issue since my last comment 19 days ago. Seeing as no one else has commented, would closing this be a good idea?

**Comment by lwouis** [comment]
@Stokestack @thirtythreeforty, what do you think? Have you experienced the issue recently?

**Comment by thirtythreeforty** [comment]
My issue as described is still present.

Namely, windows that overlap screens appear on neither screen's AltTab listing, when "Screen showing AltTab" is selected:

![Screen Shot 2020-12-10 at 3 29 53 PM](https://user-images.githubusercontent.com/3952613/101832133-8e63b200-3afc-11eb-8e0f-13806e3fa100.png)


My workaround is to set it to display windows from all screens, but I do not prefer this setting.

**Comment by thirtythreeforty** [comment]
I would prefer that this setting picks windows not by their bounding box, but by their centroid.

**Comment by Stokestack** [comment]
Hi @lwouis , thanks for the follow-up. I haven't noticed it with Zoom, although I probably haven't tried lately. BUT... it does happen with TextMate, oddly enough. It showed TextMate was running, but AltTab put it at the end of the list because it thought it didn't have a window; but it did, with an open document.

**Comment by lwouis** [comment]
@thirtythreeforty I think the issue you have been talking about in your messages is a different issue that this general ticket here.

I would like to implement what you describe, as I think it makes a lot of sense. I'll open another ticket for that

**Comment by lwouis** [comment]
What's the current situation with Zoom? Is the OP issue still happening, or should I close this ticket? @Stokestack @SoPat712

**Comment by Stokestack** [comment]
Hey thanks for the follow-up. I haven't tried it recently, so I don't know. Generally Alt-Tab is working well. I'll try to remember to test it on my next call.

**Comment by MatthewScholefield** [comment]
Heads up, I do still consistently face this issue in a repeatable way. It happens whenever I join a meeting directly via link when the zoom app is initially closed.

When this happens the zoom meeting window isn't in alt-tab. If I quite and re-open alt-tab it will correctly find the meeting window and additionally if I have zoom initially running and click a meeting link it will also show correctly in alt-tab.

Should we re-open or should I make a new issue?

**Comment by lwouis** [comment]
> If I quite and re-open alt-tab it will correctly find the meeting window

This is most likely #1324

**Comment by MatthewScholefield** [comment]
Hmm, nope. I actually was able to get more specific details so I went ahead and made #2951.

**Comment by lwouis** [comment]
Could you please try out [this local build](https://github.com/user-attachments/files/24265844/AltTab.app.zip), and let me know?

In that build, I've removed the filtering of windows which are higher level than the normal level. That is, windows that float on top of others. Normally, we remove them from the list. I actually wonder if this is good these days. So if you see more windows you consider windows, and and no new windows you would consider popups/HUDs, then I'll release this change 👍 

It also contains my work-in-progress for video thumbnails, so please ignore that part

Thank you

**Comment by Stokestack** [comment]
I will check this out, thanks! And this reminds me: Right now Alt-Tab shows absolutely nothing in its UI (MBP M1 under latest Mac OS). Just an empty overlay. We'll see if this build resolves that.

**Comment by Stokestack** [comment]
Looks like this works, thanks! If I start a new meeting, the window with the camera view does show up in Alt-Tab. Also, other apps are showing up now.

**Comment by lwouis** [comment]
> Also, other apps are showing up now.

Could you please share with apps/windows are showing up now?
I'd like to verify that we show the right windows 👍

**Comment by Stokestack** [comment]
Here's a screen shot.

![Image](https://github.com/user-attachments/assets/46beeac2-ef00-4903-ad77-a2a99c72ab36)
