### ISSUE TITLE
hiding minimized/hidden windows does not work anymore

### ISSUE THREAD

**Issue by mpl** [lwouis/alt-tab-macos#605]
**Describe the bug**

I've just updated to 3.5.0, and now alttab shows me the previews for apps which are still running, but which do not have any window open. I do not want to see these previews, and it used to work that way, which was great.

I thought maybe it had to do with the hidden and/or minimized options, so I've set these to "hide" but it does not seem to change anything for that case.

What am I missing?

If there is no way to avoid that behaviour for now, which version of AltTab should I rollback to, to fix it?

**Screenshots / video**

<img width="1440" alt="Screenshot 2020-09-13 at 16 47 42" src="https://user-images.githubusercontent.com/626071/93021726-a8b4ef00-f5e4-11ea-9fa3-cbb2c9a7c567.png">

<img width="686" alt="Screenshot 2020-09-13 at 17 07 45" src="https://user-images.githubusercontent.com/626071/93021735-b66a7480-f5e4-11ea-8ef4-24e37dab3bb4.png">

**Comment by lwouis** [comment]
Could you please try checking the new preference to disable that feature?


![](https://user-images.githubusercontent.com/106195/92594656-0e9c3080-f2de-11ea-882d-4ab5e7b71dd1.png)

**Comment by mpl** [comment]
@lwouis aah, so that's what I missed! thanks, it works as expected now.
