### ISSUE TITLE
Version 6.5.0 crashes when starting the Mac

### ISSUE THREAD

**Issue by mrc247-DE** [lwouis/alt-tab-macos#607]
after upgrading to version 6.5.0, alt-tab crashes every time I start my Mac. If I start it manually afterwards there are no problems. I sent error reports.

**Comment by lwouis** [comment]
There have been 92 users sending 212 crash reports in AppCenter, but their reports where hard to figure out. Thanks to your ticket, I was able to reproduce by restarting. I then realize it was a data-race that was in the app from the very beginning, but was never practically happening until I moved the System Permissions timer to a background thread recently.

I'll push a fix quickly for this. Thanks a lot for sharing the issue!

**Comment by mrc247-DE** [comment]
thank you again for the quick support :-)
