### ISSUE TITLE
Option to choose preferred "Finder" application

### ISSUE THREAD

**Issue by ybbond** [lwouis/alt-tab-macos#611]
## Rationale
I use [dCommander](http://devstorm-apps.com/dc/) as Finder replacement. **altTab** supports opening new finder tab if none exist. It'd be convenient if user may choose which Finder replacement app to open new tab to if selected.

<img width="183" alt="Screen Shot 2020-09-16 at 19 28 11" src="https://user-images.githubusercontent.com/25895873/93337033-c38c9b00-f852-11ea-9088-bbd6a17e3035.png">

## Solution Proposal
New option for `General` tab to choose which application that would be opened if the "Open new Finder tab" choosen.

## Alternative
If the commands to open each of Finder replacements are to diverse, add a text input so user can fill it with AppleScript or terminal command.

**Comment by lwouis** [comment]
Hi @ybbond! Thanks for sharing this feedback!

I just downloaded dCommander to try and see how the UX is. Unfortunately it's a commercial app so I can't really explore. I was able to boot a window though

It seems like this app doesn't replace the Finder like all the other Finder replacement apps (see #84). Instead, it functions as a standalone, independent app. It has its own icon in the Dock and in the built-in macOS app-switcher.

Thus I think in your case you could simply add the regular Finder to the ignore list, so it's not displayed. You would then have dCommander's windows shown, and if you close them all, the "open new window" option for dCommander, presented in AltTab.

![image](https://user-images.githubusercontent.com/106195/93468055-5f88d600-f929-11ea-97a7-2fd520167e4f.png)

What do you think?

**Comment by ybbond** [comment]
ooooh right, the "new tab" icon is not exclusive to Finder.app, but any applications that is active (in dock), but has no active window, right?

Thank you for the explanation, your implementation should work. I will close this issue
