### ISSUE TITLE
Dev Release branch of alt-tab

### ISSUE THREAD

**Issue by SoPat712** [lwouis/alt-tab-macos#622]
I think a development branch would be a good idea for alt-tab as it would mean that testing on the dev branch would make your job much easier before releasing to the stable branch. Bugs for the dev branch could be labeled DEV: " " or something along those lines. It would be a good idea allowing us to get new features while sacrificing the stability, because I don't really care about 100% stability in apps and I have a lot of time to waste finding bugs.

**Comment by lwouis** [comment]
There is already a dev branch on github. It's called `develop`. Any enthusiast user can check if out and see what's soon to be released.

I think you're thinking of a *dev/beta chanel*? That would differ from a dev branch from being a release of an executable app, compared to the branch being only the code that still needs to be compiled to run. Such an endeavor would require:

* Storing those release somewhere. Currently I store everything on github which is very efficient. No backend involved at all. We could store dev/beta releases in the same place, with suffixes like `-beta.1` or something
* Adding instructions and a download link on [the website](https://alt-tab-macos.netlify.app/)
* Update the CI/CD pipeline to handle the builds, version numbers, PR
* Update the code for Sparkle so the auto-update system handles users being on the `beta` channel, and potentially switching back to `stable`
* Update AppCenter and the CI pipeline to handle crash reports from those

Overall it's a lot of work and extra complexity. I don't feel that this initiative would be rewarded unfortunately. There are not many people interested in helping out with testing. Maybe a dozen max. I usually manually share beta builds on the relevant tickets here on github. I think it's a reasonable way to deal with this given that I have to rally enthusiasts, often the users asking for the tickets will be the only one willing to put effort into testing.

I'll close this ticket for now as I don't see it as a realistic value bringing initiative in the current project environment. If other people express interest, the topic will be revisited of course

**Comment by SoPat712** [comment]
Yes, I was thinking of a beta channel. It does seem like a lot of work though, you're right! Thanks for entertaining the idea.
