### ISSUE TITLE
Monal app window not rendered in alt-tab-macos window switcher preview

### ISSUE THREAD

**Issue by foss-** [lwouis/alt-tab-macos#623]
**Description**

Monal app window not rendered for unknown reason. It is a catalyst app if that is somehow relevant.

**Screenshot**

This is with monal window open and showing content.
![monal](https://user-images.githubusercontent.com/5708172/94362933-c42cf900-00be-11eb-929d-9c3640f97a43.png)

**Reproduce**

1. install http://monal.im/Monal-OSX/Monal-OSX.zip from https://monal.im
2. with monal open use alt-tab-macos
3. see that the window preview is not rendered

**Comment by lwouis** [comment]
I followed the steps but couldn't reproduce. Monal is showing correctly in AltTab for me.

What specific window are you not seeing? I'm seeing the base window, as well as when there is any popover partially covering it:

![image](https://user-images.githubusercontent.com/106195/94441110-50354280-01dd-11eb-833e-37783d98d207.png)

![image](https://user-images.githubusercontent.com/106195/94441177-680cc680-01dd-11eb-8b2a-1f94d64b54bd.png)

I don't have an account and contacts to test sending messages. Maybe that's the window that's not working for you?

What if you restart AltTab? Any change?

**Comment by foss-** [comment]
Thanks for looking into this. For me it doesn't matter what part of the app is displayed, but alt-tab-macos preview just shows the placeholder which is usually shown when an app does not have an open window. Is that part working for you? The Monal app itself is showing fine. The report is just about the alt-tab-macos window preview in the application switcher.

**Comment by lwouis** [comment]
Yes that's what i meant above. I can see all windows correctly listed in AltTab. I don't see the "no open window for this app" icon that's on your screenshot because i see Monal current open window listed in AltTab.

What happens when you restart AltTab? Or Monal? What version of Monal, AltTab, macOS, or you running?

**Comment by foss-** [comment]
macOS Catalina 10.15.7 (19H2)
Monal 4.8 (650) (beta from monal.im)
alt-tab-macos 6.7.1

Restarted mac and now monal window preview is there. Fascinating – not sure what got stuck. Closing.
