### ISSUE TITLE
Allow up and down arrows

### ISSUE THREAD

**Issue by mbikovitsky** [lwouis/alt-tab-macos#64]
Similar to #53, but this time allow the up and down arrow keys to move between rows. Currently these keys are sent to the application that was last active.

**Comment by lwouis** [comment]
This is significantly harder than left/right as it involves understanding what is up and down visually and the complex `NSCollectionView` that I customized with `CollectionViewCenterFlowLayout`.
`
Also, I'm thinking about maybe using the arrow keys for #9

**Comment by lwouis** [comment]
Closing as duplicate of #270
