### ISSUE TITLE
Keep historic order of windows after having used cmd+tab

### ISSUE THREAD

**Issue by b-pfl** [lwouis/alt-tab-macos#644]
Hi all, I just found this App today and I must say that I am really happy that I found this App and hope that this will be a good and stable replacement of HyperSwitch. 

**Is your feature suggestion related to a problem? Please describe.**
While trying out the App today, I figured out that the behavior seems to be different from HyperSwitch when I mix the use of alt+tab and cmd+tab. For this use case, please open >= 2 applications where each application has multiple windows (e.g. application 1 has windows 1a, 1b, 1c and application 2 has 2a, 2b, 2c, 2d).
1.  When only using alt+tab, the order of windows is from most recently used to the "oldest" window and get updated correctly when switching between windows.
(Example history: 1c, 2a, 2c, 1b, 2b, 1a, 2d)
2. Once I change applications once with cmd+tab, the order gets destroyed: While only one windows will get the focus, also the other windows will become visible (behind the active window) and the alt+tab App seems to consider them as being used. 
Let's see what happens when having the history mentioned above (i.e. working in window 1c): If I press cmd+tab once in that case, MacOS will bring all windows of application 2 to the front with 2a being in front of everything. What happens now is that the window history of alt+tab now gets re-arranged. Instead of only swapping 1c and 2a, the new alt+tab history will have all windows of application 2 as most recently used windows: (2a,2c, 2b, 2d, 1c, 1b, 1a). Thus, when I now want to switch back to the previously active window (1c), I have to press alt+tab multiple times instead of only pressing this combination once. This gets quite annoying if you have a lot of open windows.

**Describe the solution you'd like**
In step 2, the history of active windows should be maintained. This helps to be able to quickly get back to the most recently used window. Thus, the new history after having used cmd+tab should be (2a, 1c, 2c, 1b, 2b, 1a, 2d) and the app should ignore that the other windows of application 2 had been brought to the front (without being active windows). It would be nice to have at least an option to switch to this proposed behavior.

**Describe alternatives you've considered**
If you install HyperSwitch, this app follows my proposed ordering.

**Comment by lwouis** [comment]
Hi @b-pfl! Thanks for the feedback!

Here is a [video response](https://www.loom.com/share/40364fc92a3840d1858a2193a6d88bfa) where I show that it seems to work as you want it to, in my case. I'm not able to reproduce.
