### ISSUE TITLE
Applications disappear from the alt-tab

### ISSUE THREAD

**Issue by newtohere-ui** [lwouis/alt-tab-macos#645]
For example, the "Preview" app from apple disappeared from the alt-tab

![](https://user-images.githubusercontent.com/72489967/95415298-7471eb80-0962-11eb-9120-045014604180.png)
](url)

**Comment by lwouis** [comment]
Hey @newtohere-ui, I'm not sure what you opened a clone of #639? Let's keep the discussion in the original ticket, okay? I'm closing this duplicate
