### ISSUE TITLE
Some Adobe apps windows don't show up in AltTab

### ISSUE THREAD

**Issue by Rizowsky** [lwouis/alt-tab-macos#647]
Hello,
Just reporting on AE 2020 windows not being shown in AltTab at all. Using the latest version 6.73 on macOS 10.15.7. 
Photoshop/Illustrator are working as intended.

edit: There is a 7 day free [trial](https://www.adobe.com/products/aftereffects/free-trial-download.html) for After Effects per account.

**Comment by lwouis** [comment]
Another user shared a video showing issues with Photoshop and Illustrator. There was also #581. Overall the Adobe Suite seems to be creating all sorts of issues.

I want to support it as it's a major piece of technology. It's hard to do though as i don't own a license, and trial versions expire then i'm stuck.

Someone knows how i could get some open-source or non-commercial license maybe?

**Comment by codesoho** [comment]
Thank you for replying. Adobe's GUI has been very unreliable over the years. Many apps have been acquired by the company by simply buying out other rivals (Aldus, Macromedia, etc.) so things are very out of sync. 

As for the license I don't think there is any free option unfortunately. Only free alternative would be creating new dummy account every 7 days or as needed. Ironically the most hassle free option is simply pirating their software :)

**Comment by lwouis** [comment]
> Only free alternative would be creating new dummy account every 7 days or as needed

I think they fingerprint the machine these days, so there is no file I could remove from my machine that would let me restart the trial.

Piracy is out of the question as I don't want to run a binary from an untrusted source. What if someone put a keylogger or a ransomware inside? I'm not familiar enough with the pirating scene to know trusted crackers.

**Comment by codesoho** [comment]
Yeah, that's understandable. 
I can share my personal subscription with you although its only photoshop atm. It supports up to two computers at a time. Unfortunately my other adobe (work) account with all apps is already split between me and a video editor.

**Comment by SoPat712** [comment]
@lwouis TNT has been a trusted crack source for years. If you'd like to discuss further, I recommend you message me on Discord. My discord tag is Intellijence#3188. I do recommend however for all users to purchase their software if you make money from it, or use it on a daily basis. In this case, it's just for testing purposes, so I'm sure it's fine

**Comment by jsh9** [comment]
I've noticed that the Adobe Reader window is also missing.  Since Adobe Reader is free, you may not need a cracked After Effects of Premier to reproduce this error.

**Comment by lwouis** [comment]
From #710, After Effects 2020 also exhibits the issue.

**Comment by nourijp** [comment]
Hi there.  I just wanted to add that a similar issue is still happening.

I looked the messages above, and I wasn't sure if a solution had been found yet, but just in case, I thought I would leave an update that the issue is still occurring. 

_Also, besides the issue with Adobe apps, I just wanted to say thank you for making the app. It really brings a very useful feature to mac os._

**Comment by lwouis** [comment]
@nourijp thank you! I would love some support to tackle this ticket. It's aggregating different issues on different Adobe apps. What's really missing here is detailed information. For instance, I would love to see videos of what you are experiencing, and also get steps to reproduce. That way there is a chance I can reproduce on my machine, debug the issue, make a fix, and ship it to everyone.

**Comment by nourijp** [comment]
@lwouis sure thing.  I will send a video to you as soon as I can. I'm not sure how helpful it will be, but I will try to capture as much detail as I can

**Comment by guillaumebrunerie** [comment]
Same issue here with After Effects 2021, it simply does not show up in the list of windows when doing Alt-Tab, even though it is open. The only way to go back to the window is to click on it or on the AE icon in the dock.
I’ve noticed that the title bar looks "older" or at least different from the way the title bar of other apps looks like. Maybe it is somehow using an old UI API that doesn’t register the window in the same way? Maybe someone knows the name of this different UI and maybe that would help with debugging/reproducing it?

Here is a screenshot of it, you can see that Alt-Tab only shows five windows even though there are six windows open, and After Effects has a light title bar while all the other apps have a dark one.
<img width="1169" alt="Screen Shot 2021-06-18 at 10 15 26" src="https://user-images.githubusercontent.com/787865/122529883-3a430880-d01e-11eb-9620-555f136d6447.png">

**Comment by lwouis** [comment]
The latest release may fix this issue. Could you please let me know if you still face this issue on the latest version of AltTab?

**Comment by guillaumebrunerie** [comment]
I'm afraid this made no difference for me, I have installed AltTab 6.40.0 and restarted my computer just in case, but windows of After Effects 2022 still do not show up in AltTab (unless I disable the "Hide apps with no open windows" in which case After Effects always appears at the end of the list).

**Comment by lwouis** [comment]
Maybe it's #447. It could also be something unique to AE but that i can't test since i don't have a license. Unless they have a trial version?
