### ISSUE TITLE
Shortcuts with Fn key

### ISSUE THREAD

**Issue by chavlji** [lwouis/alt-tab-macos#661]
Why is Fn key not supported to be used as a key modifier? I have keys remapped and my thumb is always resting on Fn key, so it would be super useful for me if I could use it as a key binding... And I think I'm not the only one :D

**Comment by lwouis** [comment]
Hi @chavlji! It's a valid question! The `fn` key is unique in many regards, but I don't think there is a technical reason stopping us from binging to it. AltTab uses the ShortcutRecording library for shortcut recording. I'll open a ticket there to ask why it's not currently supported to record a shortcut with the `fn` key.

**Comment by lwouis** [comment]
After discussing with the main maintainer of ShortcutRecorder, I got convinced that adding support for the `fn` key as a modifier for shortcuts is not a good idea. Please [check out the discussion there for more details](https://github.com/Kentzo/ShortcutRecorder/issues/132).

**Comment by chavlji** [comment]
😢  Thanks anyway. I guess I'll have to find some workaround. I'll post my findings here...

**Comment by lwouis** [comment]
You can remap keys to achieve that, externally to AltTab. I use BTT for that. It's the more complete app for remaps of any kind (mouse, trackpad, keyboard, etc). It's the best but it's paid for. There is a good free alternative with Karabiner Elements but it's hard to configure in my experience

**Comment by chavlji** [comment]
I have a bunch of such stuff installed including BTT paid version and Karabiner.

Unfortunately, it's not just a simple key binding remap. I don't want to remap `fn` to `option` as default. Instead of `fn + tab` I'd have to send `fn up`, `alt down`, `tab click`. And at the `fn` released I'd have to call `alt up`. A lot of conditions, that are really hard to achieve in those tools. Hammerspoon, on the other hand, enables you to do such stuff, but it's not capturing keys with kexts as eg. Karabiner does, and thus it isn't so reliable on such exotic actions.

If I find out how to do it, I'll post it here...
