### ISSUE TITLE
Alt-tab shows extra Zoom windows that don't exist

### ISSUE THREAD

**Issue by SoPat712** [lwouis/alt-tab-macos#668]
**Describe the bug**

Leftover window is seen upon leaving the breakout room.

**Screenshots / video**

![image](https://user-images.githubusercontent.com/30350506/97324549-5522fb80-1848-11eb-849e-8927bed17283.png)

**Steps to reproduce the bug**

1. Go to Zoom
2. Join a breakout room
3. Leave breakout room

**Comment by SoPat712** [comment]
![image](https://user-images.githubusercontent.com/30350506/97347567-5ada0a80-1863-11eb-920b-c2d7411d81e8.png)
Another image that better shows it happening again.

**Comment by SoPat712** [comment]
Another one, of the login window

![image](https://user-images.githubusercontent.com/30350506/97484409-187dff80-192f-11eb-80ad-f2b287c67681.png)

**Comment by lwouis** [comment]
You are saying all of these windows remain in AltTab after they are closed in Zoom?

I'll try your reproduction steps with the "breakout room" above. I'm not sure what a breakout room is but i guess there is a button somewhere to go there. Hopefully i can find that UI and reproduce the issue

**Comment by SoPat712** [comment]
Yes, this windows remain even after Zoom is closer. A breakout room is a feature in Zoom that separates certain people into separate sections of the same Zoom call.

**Comment by SoPat712** [comment]
The breakout room feature doesn't happen at all anymore. I think that was a Zoom issue. The login window issue is still occurring however. Not sure why.

**Comment by SoPat712** [comment]
This issue stopped occuring. A zoom update may have fixed it, but it hasn't happened since. Closing this issue.
