### ISSUE TITLE
Apps with no windows is not showing in AltTab

### ISSUE THREAD

**Issue by blueberry6401** [lwouis/alt-tab-macos#669]
**Describe the bug**
I'm not sure if this is a bug or not, but I found an option to choose where the Hidden window to show, so I consider this is a bug. I had choosen that option to "Show".

**Steps to reproduce the bug**

1. Open Safari and Finder.
2. Close Safari window with Cmd+W.
3. Cmd+Tab to switch to Finder.
4. Cmd+Tab again, there is no Safari.

Which I expect to happen is the safari is shown in AltTab, and after switched to it, AltTab will send an event to simulate the action when user press safari on the dock to make it open a new window.

**Comment by lwouis** [comment]
Hi @blueberry6401!

> I found an option to choose where the Hidden window to show

Are you talking about this?

![image](https://user-images.githubusercontent.com/106195/97612609-fc777c80-1a5a-11eb-9894-f93e7af69666.png)

This is about *hidden* windows. Not closed windows. Hiding a window is not closing it. Actually you can't hide a window. You can only hide an app, which hides all its windows.

![image](https://user-images.githubusercontent.com/106195/97612721-1fa22c00-1a5b-11eb-80b2-b27f95b24896.png)

This preference show or doesn't show, these hidden windows. Hidden with `cmd+H`.

> Close Safari window with Cmd+W.

You are closing a window. It's then closed, not hidden. Thus it can't be shown in AltTab as it doesn't exist anymore.

> Which I expect to happen is the safari is shown in AltTab

It should be shown a "an app with no window" icon, at the end of the list:

![image](https://user-images.githubusercontent.com/106195/97613079-95a69300-1a5b-11eb-95b9-e2a0997dd5f0.png)

Selected this icon will do exactly what you described:

> AltTab will send an event to simulate the action when user press safari on the dock to make it open a new window

**Comment by blueberry6401** [comment]
@lwouis I see, it's because I often open a lot of apps and safari is at the end of the list, where I need to scroll to see.
Can you please add an option to make safari in my example in the 2nd position, not at the end of the list?

**Comment by lwouis** [comment]
There is already a ticket for what you described: https://github.com/lwouis/alt-tab-macos/issues/664

Please follow progress there 👍
