### ISSUE TITLE
Open new window feature

### ISSUE THREAD

**Issue by ptitvert** [lwouis/alt-tab-macos#674]
**Describe the bug**

To be honest, I don't know if that is a bug, or an enhancement or something else.

I am using Alt-Tab, and love it. It solved my usability issue with macOS.

I open this ticket, because, I've noticed today (maybe this is new... I've never seen it before... or never noticed it) something that disturb me, and even by reading the issues on GitHub, I understand the functionality, but still don't like it.

I would like to be able to disable the functionality to open a new window, if the application is open, but doesn't have any windows. 

I understand that you want to add new functionalities, and I am all with you, but with that, you should also be able to let the user decide if they want to use that new feature or not. And in that context, I consider that as a bug, IMHO.

I have checked the settings, and couldn't find anything to disable that feature, if one wants.

**Screenshots / video**

![image](https://user-images.githubusercontent.com/9589209/98230557-952a6280-1f5b-11eb-9858-28bc22ea8658.png)

**Steps to reproduce the bug**

1. For example, just close all the open Finder windows
2. Click on "alt-tab"
3. It will show you the finder icon with the PLUS symbol to help you open a new window
4. It should not be there, at least from my point of view :-)

**Comment by lwouis** [comment]
Hi @ptitvert!

I agree with you, and that's why I added a toggle preference to switch it off when I introduced the feature.

Please check that checkbox in the Preferences, and it won't show anymore:

![image](https://user-images.githubusercontent.com/106195/98244658-20831280-1fb3-11eb-9bbd-641358bb1feb.png)

Thank you

**Comment by ptitvert** [comment]
Thank you! I was completely blind!
