### ISSUE TITLE
DBGL (DOSBox Game Launcher) not showing up when AltTab already runs

### ISSUE THREAD

**Issue by mfn** [lwouis/alt-tab-macos#679]
I'm using 6.9.0 on 10.15.7

**Describe the bug**

The window does not appear in AltTab _when_ AltTab is already running

When I've DBGL open and quit/start AltTab, the window appears.

**Steps to reproduce the bug**

I'm starting DBGL via the included `dbgl` shell script:
```
#!/bin/sh
BASEDIR=`dirname "$0"`
cd "$BASEDIR"
if test -f "/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java"; then
	exec "/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java" \
  -XstartOnFirstThread \
  -classpath "$BASEDIR"/lib:"$BASEDIR" \
  -jar dbgl.jar
else
	exec java \
  -XstartOnFirstThread \
  -classpath "$BASEDIR"/lib:"$BASEDIR" \
  -jar dbgl.jar
fi
```
start with
`Launching DBGL using 64-Bit VM 12.0.1 on Mac OS X v10.15.7x86_64, HSQL Database Engine 2.5.0, SWT v4934cocoa`

I don't double click on the "app" you can download, because I've it on NAS shared drive and I dual launch it also from Windows.

**Comment by lwouis** [comment]
Hi @mfn! Thanks for sharing this issue.

I downloaded this app, and was able to reproduce the issue. The behavior stems from this:

* DBGL starts and declares itself with `activationPolicy == .prohibited`. See [Apple docs about it](https://developer.apple.com/documentation/appkit/nsapplication/activationpolicy/prohibited):

> The application doesn’t appear in the Dock and may not create windows or be activated.

> This corresponds to the value of the LSBackgroundOnly key in the application’s Info.plist file being 1. This is also the default for unbundled executables that don’t have Info.plist files.

In addition, after a short delay, the app switches to another `activationPolicy`. This is why AltTab shows it if you launch AltTab **after** DBGL. At this point the `activationPolicy` is no longer `.prohibited`.

I consider this a bug from DBGL. Could you please [ask them for support](http://members.quicknet.nl/blankendaalr/dbgl/#contact)? Hopefully they can fix the issue. The only alternative to workaround this from AltTab's perspective would be to listen to the hundreds of daemons and other processes and see if they change their policy over time. This has performance implications that I don't think are warranted. An app should have the right policy in the first place.

**Comment by lwouis** [comment]
Update: I was a bit fast to reply. After working on #677, I found that in order to support some very exotic scenarios, I had introduced a regression. What I said above about the fact that observing all apps would have performance penalty is not the case. The way I observe is very low impact, so I re-introduced it.

Next release of AltTab should fix the issue with DBGL. I still suggest you follow the link I gave and let the author know so he fixes what I described above (just share with him the link to this ticket). That being said, AltTab will work around the issue, and show the app properly on the next release 👍

**Comment by mfn** [comment]
> Next release of AltTab should fix the issue with DBGL. I still suggest you follow the link I gave and let the author know so he fixes what I described above (just share with him the link to this ticket). That being said, AltTab will work around the issue, and show the app properly on the next release 👍

ok, thanks, and glad you suggest that because I just it off the PM to the author 😅

**Comment by mfn** [comment]
Confirmed: it works now: even when AltTab is already running and I start DBGL, it properly shows up => Thank you 👍
