### ISSUE TITLE
PathFinder not showing up in window-less apps anymore

### ISSUE THREAD

**Issue by SoPat712** [lwouis/alt-tab-macos#686]
**Describe the bug**

Pathfinder refuses to show up windowless apps, but fixes itself once i open it using any app launcher, and close the windo.

**Screenshots / video**

Initial image of pathfinder in the dock:
![image](https://user-images.githubusercontent.com/30350506/98722747-6e0ad100-235f-11eb-8574-5662b651bd92.png)

Initial Image of alt-tab: 
![Gitasdf](https://user-images.githubusercontent.com/30350506/98718959-1c614700-235d-11eb-9abe-7e4362325b55.png)

After opening Path finder from Alfred: 
![gitsasdfasdf2](https://user-images.githubusercontent.com/30350506/98719296-9396db00-235d-11eb-875e-ffcf7b5bdbe2.png)

After closing pathfinder with a CMD+W shortcut: 
![sadfa](https://user-images.githubusercontent.com/30350506/98719454-c93bc400-235d-11eb-9619-04f2991167e5.png)

**Comment by lwouis** [comment]
I don't understand the problem you perceive.

1. The app is closed? So nothing is shown
2. The app is running with 1 window. So that window is shown
3. The window is closed but the app is still open. So we show an app without window icon

What's the issue here? What did you expect?

**Comment by SoPat712** [comment]
The app wasn't closed. I forgot to add the image here, but the dock shows that the open during the time of the first image. 

![image](https://user-images.githubusercontent.com/30350506/98722747-6e0ad100-235f-11eb-8574-5662b651bd92.png)


Alt-tab, on the other hand, shows this:

https://user-images.githubusercontent.com/30350506/98718959-1c614700-235d-11eb-9abe-7e4362325b55.png

**Comment by lwouis** [comment]
I downloaded PathFinder to try and reproduce the issue. Your steps are still not clear to me.

How do you have PathFinder initially opened without any window on step 1? When I open it, after I push away the trial window, it opens a window by default. That window is visible in AltTab. I can then close it, and AltTab shows a no-window icon for PathFinder.

I can never get PathFinder open but nothing is showing in AltTab. What are the exact steps you use to reproduce. Please don't be afraid to really spell every detail. Of course a video would help a ton here to visualize the scenario in motion.

**Comment by SoPat712** [comment]
Alright, so basically, I have purchased PathFinder, because it's a great app. I have it set to open on startup, since I use it so much. The first 2 pictures have been taken immediately after all the apps have started up on my computer, and you can see that PathFinder is shown as "open" in my dock, which is denoted with the dot to the left of the app. The problem is that after startup, Alt-tab doesn't show Pathfinder **at all** until I manually click the pathfinder icon in the dock. Then, Alt-tab apparently updates the open apps, and shows Pathfinder as a **windowed** app, which makes sense. After the app window is closed, then it becomes a windowless app, and Alt-tab is able to properly show PathFinder as a window-less app. This doesn't specifically occur on startup, and has happened a couple times after waking up from sleep. I haven't updated PathFinder in a while, and this only started happening on 6.9.0, so I'm 99% sure that this is an issue with alt-tab. If further elaboration is needed, I'll try to find some time to put together a video.

**Comment by SoPat712** [comment]
I'm thinking about it now, and the trial window might be forcing the app to open a window, which is a solution to the issue I was having, but you shouldn't have to buy the app to debug the issue. I'll try and get back to you with a reproducible method.

**Comment by lwouis** [comment]
You say that PF starts at login for you. After you finish login-in, do you see window from PF, or is it running but window-less? How about the checkbox here, is it checked for PathFinder?

![image](https://user-images.githubusercontent.com/106195/98823420-6a696e00-2475-11eb-815e-d08ff348b329.png)

There have been issues in the past with this checkbox (see #292, and you may remember #390).

You also say it happens also after wake-up. What is this scenario exactly?

* You have PF running with no window
* AltTab shows it
* You put the laptop to sleep
* You wake the laptop
* AltTab doesn't show a window-less icon for PF anymore?

Finally you say that the issue started in 6.9.0. Which version were you running before? That would help narrow a potential regression between 2 points in time in the code.

**Comment by SoPat712** [comment]
I used this preference: 

![image](https://user-images.githubusercontent.com/30350506/98828230-d14f3e80-2405-11eb-99d0-3de8c234c1c7.png)

It's located here:

![Screen Shot 2020-11-11 at 10 08 38 AM](https://user-images.githubusercontent.com/30350506/98828332-f2b02a80-2405-11eb-8436-c040dfc23275.png)


I'm turning that off right now, and placing it into Login items as we speak.

I'll get back to you if that fixes it.

**Comment by SoPat712** [comment]
Also, this issue happened between this version and the last version. I'm always extremely vigilant about updating mac apps(not so much for MacOS versions, but we know how Apple is about those), and basically always have the latest version of all the apps that I use at all times.

**Comment by SoPat712** [comment]
I placed PF into the users and groups startup items, and haven't had the issue since. Not sure if it was fixed in the latest update, or if it was fixed by the startup items thing, but thanks either way!
