### ISSUE TITLE
Thumbnails get clipped off-screen when too many windows are open

### ISSUE THREAD

**Issue by gingerr** [lwouis/alt-tab-macos#69]
As a test for the vertical placement of the `ThumbnailPanel` I opened way to many windows to see what happens. The `ThumbnailPanel` expands out of the visibleFrame. There will be some solution required for this use case.

**Comment by lwouis** [comment]
**Clarification for AltTab**

The UI is fine as long as the thumbnails fit the screen:

![image](https://user-images.githubusercontent.com/106195/67913361-23913900-fbd0-11e9-85f2-31189625e4ef.png)

Then if more windows are open, the UI is clipped at the bottom:

![image](https://user-images.githubusercontent.com/106195/67913405-46235200-fbd0-11e9-97d4-e1c91dba9297.png)

Note that you can still select the off-screen thumbnails.

**Hyperswitch behaves the same**

![image](https://user-images.githubusercontent.com/106195/67913489-9995a000-fbd0-11e9-8809-f45d01b1c148.png)

Note that even though the window has its bottom corners rounded, more thumbnails are indeed clipped away at the bottom. You can still blindly select then with a few tabs, as for AltTab.

**macOS command-tab shrinks icons**

![image](https://user-images.githubusercontent.com/106195/67914154-a3200780-fbd2-11e9-9b79-31c7bdd5a370.png)

![image](https://user-images.githubusercontent.com/106195/67914165-a6b38e80-fbd2-11e9-8a48-8770594aa972.png)

**macOS Mission Control shrinks thumbnails**

![image](https://user-images.githubusercontent.com/106195/67914236-dd89a480-fbd2-11e9-9dff-bc47e910423c.png)

![image](https://user-images.githubusercontent.com/106195/67914359-3a855a80-fbd3-11e9-89cd-112ade6afb45.png)

**Windows 10 alt-tab clips but let's user cycle to off-screen thumbnails**

![image](https://user-images.githubusercontent.com/106195/67914932-e9766600-fbd4-11e9-8a9f-ca9cacc2c316.png)

![image](https://user-images.githubusercontent.com/106195/67914937-eda28380-fbd4-11e9-8b28-a2c0b613d5d3.png)

**WindowsSwitcher clips but let's user cycle to off-screen thumbnails**

![image](https://user-images.githubusercontent.com/106195/67915113-6bff2580-fbd5-11e9-818b-5cf2a711e6b6.png)

**Comment by lwouis** [comment]
Hard clip: AltTab, HyperSwitch

I can see 3 ways to implement a solution:

* "Scrolling" row by row (like WindowSwitcher, Windows 10 alt-tab)
* Paginate (not row by row, but page by page)
* Downscaling the thumbnails (like Apple MC and command-tab)

Right now I prefer downscaling as it's the easiest to implement, and I think it's the best UX

**Comment by gingerr** [comment]
@lwouis Nice evaluation/comparison of the solutions in other applications. Fully agree here, the downscale has the best UX since it does not require any additional non-native navigation ideas to scroll or paginate and one can see at once his pile of windows.

**Comment by akx** [comment]
👍 for downscaling!
