### ISSUE TITLE
Big Sur?

### ISSUE THREAD

**Issue by zouterover** [lwouis/alt-tab-macos#693]
**Is your feature suggestion related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Comment by lwouis** [comment]
This is literally the laziest ticket someone has ever opened in the history of this repo. 2 words in the title then a questin mark. Whole body is the template, untouched.

Could you please consider that other people may not be able to read your mind. I don't know what you mean by "Big Sur?".

Did you spot a specific issue? There are some open tickets that people have reported from the Beta. Look into them.

Do you want improvements to take into account the new OS capabilities? Please write about your ideas.

**Comment by zouterover** [comment]
King of laziness here. Sorry, did not want to be rude, especially since I really dig AltTab. You're right, I could have been more elaborate. Thought it might suffice, as Big Sur is out now and was wondering when it will be supported (had seen on the AltTab site it is not yet supported). Read [this issue](https://github.com/lwouis/alt-tab-macos/issues/657). So will wait before upgrading to Big Sur. Lazy people can not survive without AltTab.

**Comment by lwouis** [comment]
My overall plan is still the same I described in the ticket you linked:

In a few weeks/months, once BigSur is stable, i'll launch AltTab on it, see what's broken or what feels out of place in the new environement, then get to work on supporting it. During that time it seems from other people report that it's working in the first place. Anyway let's wait and see. It came out yesterday so let's wait out the first few patches

**Comment by lucasschonrock** [comment]
Running alt-tab-macos on Big sur right now with no issues at all.

**Comment by SoPat712** [comment]
I don't know why anyone updates their MacOS version within 2 months of a large release. They are always completely riddled with bugs.

**Comment by andreaswilli** [comment]
I'm running Big Sur 11.0.1 (20B29) and did not experience any issues with AltTab so far.

**Comment by SoPat712** [comment]
I've heard of people having issues with battery life because of `mds_stores` excessive CPU usage, I've heard of Macs refusing to boot after being updated, and in general, I have a rule not to update until bugs stop appearing as frequently, which is almost always 2 months after each major version release.

**Comment by skyzyx** [comment]
> I don't know why anyone updates their MacOS version within 2 months of a large release. They are always completely riddled with bugs.

I'm a perpetual beta user. I work on finding the bugs and reporting them. For fun.

**Comment by lwouis** [comment]
This ticket has no clear goal. I'll close it. There are a number of specific tickets tagged with "macOS 11 Big Sur". Let's continue the conversation there
