### ISSUE TITLE
Alt-tab not responding when dragging file from folder in Dock

### ISSUE THREAD

**Issue by RoadToDream** [lwouis/alt-tab-macos#706]
First I need to say alt-tab is definitely the best window switcher I have ever used on macOS, thank you for bringing the feature to us. I was using Contexts, but it discontinues and lacks the ability to show screenshot. 
I have got only one bug(not sure if it is a bug or a feature) during recent use, also have a suggestion and it will be posted in another issue. 
**Describe the bug**
Alt-tab will not respond when dragging file from folder in dock or desktop.

**Screenshots / video**
![alt-tab](https://user-images.githubusercontent.com/8088354/99911329-6f65c300-2ca8-11eb-91a4-dda288ebb19f.gif)

**Steps to reproduce the bug**
Drag file from folder in Dock or from desktop, press alt+tab, alt-tab will not show.

**Comment by lwouis** [comment]
Thanks @RoadToDream for sharing this issue!

I was able to reproduce. It only happen in the specific scenario of **dragging something from inside a folder in the Dock**. Dragging a folder from the Dock directly works, dragging a folder from a Finder window works.

I'm guessing it may have to do with the heuristic we use to detect if Mission Control is active or not. I'll look into it in more details as soon as I have some time 👍

**Comment by RoadToDream** [comment]
Thanks for confirming! 
Also dragging folder or file from desktop also may not invoke Alt-tab, seems I didn't describe that clearly. 

> Thanks @RoadToDream for sharing this issue!
> 
> 
> 
> I was able to reproduce. It only happen in the specific scenario of **dragging something from inside a folder in the Dock**. Dragging a folder from the Dock directly works, dragging a folder from a Finder window works.
> 
> 
> 
> I'm guessing it may have to do with the heuristic we use to detect if Mission Control is active or not. I'll look into it in more details as soon as I have some time 👍

**Comment by RoadToDream** [comment]
> Thanks @RoadToDream for sharing this issue!
> 
> I was able to reproduce. It only happen in the specific scenario of **dragging something from inside a folder in the Dock**. Dragging a folder from the Dock directly works, dragging a folder from a Finder window works.
> 
> I'm guessing it may have to do with the heuristic we use to detect if Mission Control is active or not. I'll look into it in more details as soon as I have some time 👍
Thanks for confirming that. And I agree that the issue is related to the status of mission control, as Alt-tab will also not show when "Show desktop" is active.

**Comment by lwouis** [comment]
AltTab not showing during Mission Control is intentional design though. I added that as a refinement to the experience. Previously you could do it. It's very weird to focus different windows while they are small in Mission Control. Pretty goofy UX. I thought it would be unexpected and removed that.

That being said, i know the code checking for MC is brittle and i could imagine it does false negatives in some scenarios where it should not trigger

**Comment by RoadToDream** [comment]
Oh, I get what you mean, and that scenario should be a little weird. 
May I share some of my thoughts? 
When people triggered Mission Control, they should be intentional to do so. At that moment, probability of accidentally trigger Alt-Tab is pretty low, and if people do press alt+tab, they should intend to invoke Alt-tab on purpose. If Alt-tab doesn't get invoked, there will be some weirdness in the functionality side(and of course we get rid of the weirdness on aesthetic side). 
So adding the support or not is totally depend on the choice on functionality or aesthetic but not the capability of this app, and I totally respect your choice. After all, the app is good enough for me at every level 👍

**Comment by lwouis** [comment]
To add to that: Other apps don't show when MC is active. Dialogs/Pop-ups never show. I discovered these UX rules from Apple a bit randomly, but they have established guidelines for which apps/windows should be hidden during MC. There are APIs to automate that normally. For some reason however there is no API to know if MC is active.

So overall it's not only that i think focusing a miniature window is goofy looking and unexpected UX, it's also the recommended way from Apple Human Interface Guidelines

**Comment by lwouis** [comment]
> Alt-tab will also not show when "Show desktop" is active

I read too fast I think the first time. I realize now that you were talking about "Show desktop", not "Expose" (i.e. all windows being spread and shown at once). I tested, and indeed the built-in app switcher shows in "Show desktop" (and not in "Expose").

It would like to support that. I'll open another ticket to follow that enhancement, as the current ticket is about a bug with drag-and-drop.

**Comment by RoadToDream** [comment]
Hi @lwouis , thank you so much for all the efforts and making it work!
Working perfectly now!
