### ISSUE TITLE
Disable window selection "Mouse hover" when mouse is not moved

### ISSUE THREAD

**Issue by RoadToDream** [lwouis/alt-tab-macos#707]
Continues from the last issue. Just wanna make this app be better. 

**Is your feature suggestion related to a problem? Please describe.**
Activate window using both arrow key and mouse is useful, but sometimes it is confused when my mouse isn't moved a lot but is accidentally at the location of a window. Alt-tab will switch to that window even I just want to use alt+tab to switch to the next one. 

**Describe the solution you'd like**
Disable mouse hover to select when mouse is not moved a lot(like 5 pixels, currently the activation area seems to be set to 1 pixel or so), that should significantly decrease the probability of the occurrence. 

**Describe alternatives you've considered**

**Comment by lwouis** [comment]
Please have a look at #286. I have thought hard and experimented already on the idea you describe. There are issues with all implementations I came up with, so I suggest to follow up conversation in that ticket, if you can suggest an implementation that has a positive net value to the app 👍

**Comment by RoadToDream** [comment]
Sorry I didn't do a complete search before submit the issue. Have already looked that thread and make another proposal, might be a viable solution(not perfect).
