### ISSUE TITLE
Adobe Premiere Pro windows don't show in Alt-tab

### ISSUE THREAD

**Issue by SoPat712** [lwouis/alt-tab-macos#710]
**Describe the bug**

Alt-tab doesn't show Adobe Premiere pro

**Screenshots / video**

![image](https://user-images.githubusercontent.com/30350506/100529363-d0176300-31b4-11eb-85f3-ffa53ce64534.png)

**Steps to reproduce the bug**

1. Open Adobe Premiere
2. Run Alt-tab
3. Profit

**Comment by lwouis** [comment]
Seems similar to #647

**Comment by SoPat712** [comment]
I'll close this as a duplicate of #647. It seems like the Adobe suite just doesn't like alt-tab lol.
