### ISSUE TITLE
Screen specific windows selector

### ISSUE THREAD

**Issue by superlevure** [lwouis/alt-tab-macos#713]
Hi, 

**Is your feature suggestion related to a problem? Please describe.**
In a multi-screens configuration, it's frustrating to get the windows of screen #1 appear on the window selector of screen #2 and the other way around

**Describe the solution you'd like**
I wish we could have a feature to have screen specific windows selector, so if I have focus on screen #n and hit <cmd> + <tab> I can only switch between windows of screen #n

**Describe alternatives you've considered**
I have tried every "competitors" of alt-tab and no one ships this feature (maybe it's not doable ?) 

Anyway, thanks so much for alt-tab I'm so glad to have found it. If you folks have a patreon or something I'll definitely would want to give something 

Cheers

**Comment by lwouis** [comment]
Hi @superlevure!

I believe what you're describing is already possible through the preferences:

![image](https://user-images.githubusercontent.com/106195/101146083-f1b59600-365d-11eb-8bc6-396a9ea3743b.png)

You can also set up the screen that AltTab appears on with this second preference:

![image](https://user-images.githubusercontent.com/106195/101146199-101b9180-365e-11eb-88f1-40e6f293b490.png)

Is that satisfying your need? 👍

**Comment by superlevure** [comment]
YES ! 

It's exactly what I needed, my bad for having missed it.

Thank you !!
