### ISSUE TITLE
Enhancement: Additional layout options

### ISSUE THREAD

**Issue by kthornbloom** [lwouis/alt-tab-macos#717]
Amazing work on this! After using for a bit, I found that it's faster for me to recognize app icons than window thumbnails, so I'm using it like this:

<img width="1282" alt="Screen Shot 2020-12-08 at 8 36 11 AM" src="https://user-images.githubusercontent.com/3322795/101490877-f8c7f700-3930-11eb-8d65-ff89f10f6a1a.png">

However, it looks a bit odd laid out horizontally now. Two possible solutions:

A) Add a "Use Large Icons" checkbox which would put the app icon in place of the thumbnail, (see Apple's Launchpad)
B) Add a "Column Layout" checkbox would would present them just like the screenshot above, but in a vertical list.

**Comment by lwouis** [comment]
Hi @kthornbloom! Everything you described here is already possible by playing with the various preferences available today in the app.

Please see https://github.com/lwouis/alt-tab-macos/issues/432#issuecomment-659313901 for more info. You can also just explore the preferences and really tailor the experience for your needs 👍

**Comment by kthornbloom** [comment]
@lwouis - Ah, thank you! The "Window min/max width in row" was a little unclear to me at first, but I get it now. For anyone else, here's the video of how to set this up:
https://www.loom.com/share/5eb4a0a3aec6409abc46081b6de98d11

The only thing I still couldn't figure out is having the text under the icons (see below) however, I'm 100% happy with using it in the list style view. 

![Screen Shot 2020-12-09 at 8 26 16 AM](https://user-images.githubusercontent.com/3322795/101635800-73a81500-39f8-11eb-97d7-35b2e8d2e0c6.png)

Thanks again!

**Comment by lwouis** [comment]
Thanks for sharing your solution with everyone here! Eventually there will be an easier way to set it up in this specific layout. It's a matter of me finding time to work through the many tickets
