### ISSUE TITLE
Unite apps do not display a name in alt-tab

### ISSUE THREAD

**Issue by SoPat712** [lwouis/alt-tab-macos#723]
Unite is an app that basically turns websites into apps.

Unite 4 came with a pretty large update, which apparently changed the way that windows worked, and now alt-tab is unable to display the names of these apps.

![image](https://user-images.githubusercontent.com/30350506/101836704-e3f38b00-3b0b-11eb-8938-b6879babb14d.png)

Here is a [link to the app.](https://www.bzgapps.com/unite) I believe the app has a free trial for you to be able to test this out.

I am running the latest Catalina, and the latest Alt-Tab.

**Comment by SoPat712** [comment]
Yeah, it's slowly happening to all my other Unite apps too. The first day I make the Unite app, the name shows up fine, but then after a day, it starts freaking out and starts giving it weird names

**Comment by SoPat712** [comment]
Ok, I've looked into it more, and it looks like it's Unite's fault. Unite offers a preference that removes the title from the top of the app.
![image](https://user-images.githubusercontent.com/30350506/102281142-63160400-3efc-11eb-9e23-36d4b2c595a6.png)

When that title is removed, a day or two later when alt-tab checks for title names again or something, the app name is blank and alt-tab uses the empty name. Is there any other way for alt-tab to get the app list instead of 

Does alt-tab use `class func runningApplications(withBundleIdentifier: String) -> [NSRunningApplication]` to get application names? Is there something else that would allow me to be able to turn the title off and also not have empty times for alt-tab? @lwouis

**Comment by lwouis** [comment]
Hey @SoPat712!

I'm not clear on what the goal is here. I downloaded and tested this Unite app. It creates an app for a single website. It asked me for a title. After I launched that website-app, AltTab is correctly showing it with the title i picked. I then went into this app's preferences, and checked "Hide Title":

![image](https://user-images.githubusercontent.com/106195/106576390-6767b080-6580-11eb-9f0a-08bc9465a197.png)

I then see the app still in AltTab, now with a blank title.

This seems to work as intended all around here.

What behavior would you want instead? What am I missing?
