### ISSUE TITLE
Option to disable a shortcut (Shortcut 1 or Shortcut 2)

### ISSUE THREAD

**Issue by Luckey-Elijah** [lwouis/alt-tab-macos#724]
**Is your feature suggestion related to a problem? Please describe.**
I only want to use Shortcut 1 sometimes. I understand I can change the keybinding for the shortcuts, but I would prefer to select an option to disable the shortcut.

**Describe the solution you'd like**
A button or option to disable a Shortcut, rather updating the keybindings to "disable" them.

**Describe alternatives you've considered**
Update the keybindings for a shortcut each time I want to disable it or turn it off without disabling the entire application.

**Comment by lwouis** [comment]
Hi @Luckey-Elijah!

So you're talking about this here:

![image](https://user-images.githubusercontent.com/106195/101987653-e0f9c580-3cd8-11eb-918b-8c8540e3a0d1.png)

You're saying that you would like a button to disable each shortcut. Like next to shortcut1, a button to disable shortcut1, and same thing for shortcut2?

That seems a bit unnecessary to me. It would increase UI complexity, to avoid 1 click, right? Currently you click on the binding:

![image](https://user-images.githubusercontent.com/106195/101987695-19010880-3cd9-11eb-925a-3f1ce5045e41.png)

Then on the cross to clear it:

![image](https://user-images.githubusercontent.com/106195/101987691-16061800-3cd9-11eb-86d8-2f45fc375be4.png)

Adding a disable toggle would go from 2 clicks to 1 click, but add complexity to the UI. It doesn't strike me as a clear-cut improvement.

What do you think?

**Comment by Luckey-Elijah** [comment]
Actually, I never realized you can click on the X to clear it! I would just rebind it to a combo I never used - never clearing it, which is pretty much what I am looking for.

Thank you.
