### ISSUE TITLE
Better preferences migration

### ISSUE THREAD

**Issue by lwouis** [lwouis/alt-tab-macos#73]
From discussion in #71:

**If the json parsing fails, we can:**

* show the user there was a problem
* possibly send that to some stats server for telemetry but this is a controversial topic in the OSS community
* remove the existing file and use the defaut from the current app

**Better handle when parsing works**

* remove the version key/value and instead do some smart merging of old prefs and new defaults

**Comment by mfn** [comment]
> show the user there was a problem

To would probably the easiest for a start and, until the software is deemed stable, probably as the most economical way. IMHO :)
