### ISSUE TITLE
Add CD to Homebrew

### ISSUE THREAD

**Issue by lwouis** [lwouis/alt-tab-macos#75]
Add a step to deliver builds to Homebrew on TravisCI, in addition to the current delivery on Github releases.

Also document the brew option in README.md

[Some preliminary discussion](https://github.com/Homebrew/homebrew-cask/issues/71674#issuecomment-547699742)

**Comment by OranShuster** [comment]
according to him this option is not meant for this.
cask-repair is very easy i use it all the time. it totally automates PRing the new version (it enters the SHA and opens the PR for you after you give it the new version)
it can be automated pretty easily but can also be done manually in <1 minute

**Comment by lwouis** [comment]
> it can be automated pretty easily

I would like to encourage you to open a PR here! Your know-how would be very useful here :)

**Comment by OranShuster** [comment]
tried to automake cask-repair with `expect` and its totally not working...
i guess we can swap it for a simple python script and manually edit the .rb file

**Comment by OranShuster** [comment]
Seems like we don't really need to do this 
https://github.com/Homebrew/homebrew-cask/issues/63171
there is atlest one automated process for updating casks that have an appcast automatically

you can see the output of one of them here
http://macupdater.net/cask-repair/

or here
https://github.com/Homebrew/homebrew-cask/issues/55268

**Comment by lwouis** [comment]
I opened a [PR to open the current cask](https://github.com/Homebrew/homebrew-cask/pull/75859) with the correct minimum macOS version.
