### ISSUE TITLE
Can't change keybinds on Big Sur

### ISSUE THREAD

**Issue by theRealPadster** [lwouis/alt-tab-macos#759]
**Describe the bug**

The preferences pane does not appear to allow me to change the "shortcut 1" or "shortcut 2" keybinds. They are just buttons that don't do anything. As I just installed Alt-Tab, I wasn't sure if it was possible, but upon some research, I think the keys are supposed to be dropdowns that allow you to change the keybinds. Mine are just buttons. 

**Screenshots / video**

![image](https://user-images.githubusercontent.com/1565883/103450162-5590a600-4c80-11eb-86a9-fd25711d9a03.png)

**Steps to reproduce the bug**

1. Open preferences pane
2. Click on 'Controls'
3. Click on the button for the option key, ('Hold <option> and press <tab>')
4. Button presses but nothing happens

Again, I just installed Alt-Tab, so I'm not sure if anything changed or if this is no longer supported, but I thought I would post here in case it's an issue or someone can help me out here :)

**Comment by theRealPadster** [comment]
So as soon as I posted this, I went back, and it allowed me to change the key when I clicked the button. The only difference I could see was for some reason before, the close/minimize window buttons were greyed out, whereas now they are coloured. Maybe it somehow lost focus and the buttons stopped working? I was fully using the preferences pane before when they were greyed out though, so not sure what happened here...

![image](https://user-images.githubusercontent.com/1565883/103450224-1878e380-4c81-11eb-8fa0-9037e94c6d56.png)

**Comment by lwouis** [comment]
Hey @theRealPadster! Thanks for sharing this issue!

i know from crash reports that there may be a bug in the library i use to record these shortcuts (ShortcutRecorder). I see only a few crashes out of probably 10s of 1000s of users, so imagine it only happens in rare conditions, probably some kind of data race.

Is there any way you can reproduce the issue? Like restarting the app and doing what you did the first time when it failed to work for you?

Getting reproduction steps is the number 1 goal. Fixing after that is pretty much guaranteed.

**Comment by aseifert** [comment]
For me it happens when I have the settings window open and then use the app to switch between windows and back into the settings window. Not every single time but quite often this results in a greyed out settings window where I can still change most things it seems, just not the keyboard shortcuts. Closing the settings window and opening it again fixes it for me.

I'm on the Macbook Pro M1 using macOS 11.1.

**Comment by lwouis** [comment]
Thanks @aseifert! I was able to reproduce it on my Big Sur VM! It doesn't happen on my Catalina host, but happens very often on Big Sur following your repro steps. Very useful! Thank you!

I'll debug it now that I can reproduce 👍

**Comment by theRealPadster** [comment]
Ah yes, that does it for me too! Sorry, I tried to replicate the issue earlier but couldn't get it to happen, but this seems to work.

**Comment by theRealPadster** [comment]
@lwouis Just installed a fresh copy from homebrew. It seems to work sometimes, but not always. It was working when I first tried. Then I alt-tabbed (option-tab, default keybind) to my browser and back, and the window was no longer focused. You can tell because the menu bar still has the browser app name and menu items there, though I am clicking on the Alt-Tab prefs window. Seems to sometimes get in this stuck state after alt-tabbing from the prefs window and back.

**Comment by lwouis** [comment]
I was able to reproduce not exactly this issue, but the fact that some of AltTab's own windows would have the grey "traffic light" icons even though they are focused. I'll ship a new release with a fix soon. Please let me know if it fixes this issue, as I hope it will

**Comment by theRealPadster** [comment]
Updated to 6.40.0 and messed with the settings window a bit and I haven't been able to break it yet, so I think you're good! Thanks :)
