### ISSUE TITLE
Fade out animation has a white flash starting with Big Sur

### ISSUE THREAD

**Issue by Pythomiere** [lwouis/alt-tab-macos#760]
![alttab](https://user-images.githubusercontent.com/69103204/103455216-1d995b00-4ca0-11eb-8a52-17fcca8797ff.gif)

**Comment by lwouis** [comment]
I'm not sure what's happening on your gif. There is no distinction between Dark and Light mode for AltTab.

It looks like this on my machine, in Dark then Light mode:

https://user-images.githubusercontent.com/106195/103475659-9ad4e500-4df2-11eb-9b1c-319921495558.mov

You can see the smooth fade-out animation.

Some questions that may help diagnose the issue:

* Are you on Big Sur maybe?
* What happens in Light mode?
* Did it always act like this, or is this happening after an update of macOS or AltTab?

**Comment by Pythomiere** [comment]
It will only happen in a dark background.

https://user-images.githubusercontent.com/69103204/103488884-3f403280-4dc5-11eb-90f4-f63cc55f807f.mov

**Comment by lwouis** [comment]
The animation is handled entirely by macOS (by AppKit, technically), so I'm not sure what I can do about this. It's not reproducible on my machine as well.

* Are you on macOS Big Sur (macOS 11)?
* Does it happen with the default AltTab preferences? You can reset preferences by running this command in the Terminal: `defaults delete com.lwouis.alt-tab-macos`

**Comment by Pythomiere** [comment]
I am in Big Sur now. I set up a new account and run with the default setting but the problem still occurs, I do not think this is the setting's problem. 

<img width="686" alt="Screen Shot 2021-01-04 at 1 01 43 PM" src="https://user-images.githubusercontent.com/69103204/103579808-db357100-4e8d-11eb-9342-23fa0e78e5ab.png">
<img width="686" alt="Screen Shot 2021-01-04 at 1 01 57 PM" src="https://user-images.githubusercontent.com/69103204/103579817-dcff3480-4e8d-11eb-8215-a7a0363c9340.png">

**Comment by lwouis** [comment]
The preferences on your screenshot are heavily customized. Could you try with the default preferences and only activating the fade out animation?

I'm trying to diagnose if it's a Big Sur issue, or maybe your preferences, especially relative to layout, or maybe both.

**Comment by Pythomiere** [comment]
Yeah, it still occurs even if I use the guest account with default settings.

**Comment by awefuiawef** [comment]
Also getting this on the latest big sur. Contexts also recently had this bug pop up in big sur, could be related? https://twitter.com/josiahbryan/status/1347196619926761473

**Comment by zacharee** [comment]
This is happening for me too on Monterey. I've been playing around with window animations (and getting into macOS development), but I haven't found anything yet.

**Comment by zacharee** [comment]
I think I've fixed this with the following changes:

The `updateFadeOutAnimation()` function should look like this:

```
func updateFadeOutAnimation() {
    if (Preferences.fadeOutAnimation && !isVisible) {
        alphaValue = 0
    } else {
        alphaValue = 1
    }
    animationBehavior = .none
}
```

The `orderOut()` function should be overridden with the following contents:

```
override func orderOut(_ sender: Any?) {
    if (Preferences.fadeOutAnimation) {
        NSAnimationContext.runAnimationGroup({ (context) -> Void in
            animator().alphaValue = 0
        }, completionHandler: {
            super.orderOut(sender)
        })
    } else {
        super.orderOut(nil)
    }
}
```

The `show()` function should look like this:

```
func show() {
    makeKeyAndOrderFront(nil)
    if (Preferences.fadeOutAnimation) {
        animator().alphaValue = 1
    }
    MouseEvents.toggle(true)
    thumbnailsView.scrollView.flashScrollers()
}
```

Basically, instead of relying on the AppKit animation, just animate and set the alpha value. This should also add a fade-in animation like the fade-out animation. I'm not completely sure if delaying the platform `orderOut()` behavior until after an animation runs is the best idea, but it does seem to work on Monterey.

**Comment by lwouis** [comment]
> Basically, instead of relying on the AppKit animation, just animate and set the alpha value. 

But why is this now necessary? The built-in animation was working fine in previous macOS versions. Apple introduced a bug in macOS 11 that needs a workaround from apps now?

**Comment by zacharee** [comment]
> > Basically, instead of relying on the AppKit animation, just animate and set the alpha value.
> 
> But why is this now necessary? The built-in animation was working fine in previous macOS versions. Apple introduced a bug in macOS 11 that needs a workaround from apps now?
> 
> Btw thank you for working on this! 👍

Yeah it seems so. The window flashes white when performing a fade animation with the default AppKit animation. Probably some issue with the material in the framework, but I don't know enough about how it works to say for sure.

The custom fade animation could probably be put behind a version conditional to only run on Big Sur and above, just in case the system animation is different on 10.10-10.15.

**Comment by lwouis** [comment]
That's a good idea. It's super easy to do version conditional in swift as well, so easy win here.

Do you think you could share a PR with the fix? That way you will get automatically credited for it in the app and on the website 👍

**Comment by lwouis** [comment]
I was trying to test https://github.com/lwouis/alt-tab-macos/pull/1201, but I actually can't reproduce the issue.

I'm on a BigSur VM. I use a black background, I invoke AltTab, I switch to another window which closes AltTab, and I recorded on my phone at 240 FPS and the transition is smooth. It doesn't flash white like on the OP gif. Here is the [slow-mo video on a dark background](https://youtu.be/LS2-oGzn9NA), on my macOS 11 VM.

I asked earlier in this thread, but it went unanswered: does this happen in Light mode, or only in Dark mode? It seems that Dark and Light modes have AltTab show the same background on macOS 10 and 11, so I'm not sure this ticket should have "dark mode" in its title, unless someone can confirm that it is only happening with dark mode. @zacharee could you please clarify this maybe?

Do you have any tips to reproduce the issue? It works fine on my machine.

**Comment by zacharee** [comment]
I've got macOS in Dark Mode.

**Comment by lwouis** [comment]
I need help to reproduce the issue. See my observations and questions above (e.g. does it happen in Light mode? What are exact steps to reproduce the issue?)

**Comment by zacharee** [comment]
The steps to reproduce are just to enable the fade out animation in Appearance and then use the keyboard shortcut to open the switcher. Once you release the keys, the white flash happens.

The white flash also happens for me in light mode, since the switcher background stays dark gray after the theme change.

Super slo-mo in both light and dark mode: https://photos.app.goo.gl/stMU38P47rsJRBMt8

**Comment by lwouis** [comment]
When I compare both our videos, I noticed that your AltTab background color is not as white as mine, before the shortcut is even released.

Yours | Mine
-|-
![image](https://user-images.githubusercontent.com/106195/140595859-133c5c16-222b-4248-96a6-7ddee0d19394.png) | ![image](https://user-images.githubusercontent.com/106195/140595870-600406dd-60ae-402d-b1b6-6ad4077240b5.png)

**Comment by lwouis** [comment]
Could you please test [this build](https://github.com/lwouis/alt-tab-macos/files/7489840/AltTab.app.zip), and tell me how it fares on your machine?

**Comment by zacharee** [comment]
That build still has the white flash for me.

**Comment by isametry** [comment]
@lwouis Hi, I'm on Monterey 12.4 and the current AltTab release (6.40.0) still exhibits the flash for me.

![flash](https://user-images.githubusercontent.com/46103746/170874513-990de352-9c29-483a-b17a-54ec9bce21c1.gif)

In comparison, the build you uploaded above doesn't, but the UI looks very dark, with almost no blending of the background. I'm assuming that's a part of the fix?

**Comment by lwouis** [comment]
### Looking at the preferences window in different macOS versions:

Catalina | Big Sur | Monterey | 
-|-|-
![image](https://user-images.githubusercontent.com/106195/171135790-a27fbb37-a07e-4371-878a-4447c318654e.png) | ![image](https://user-images.githubusercontent.com/106195/171135672-d7edd990-2f6c-4890-95a6-9bfefa4052fc.png) | ![image](https://user-images.githubusercontent.com/106195/171135695-6d3cb623-c478-4122-bdf5-e4ac3a2583a3.png)

* On Big Sur, the tab icons of the preferences window overflow at the top of their box.
* On every version, I think the icons should take into account Dark Mode (see how it's white in the menubar, but black in the dropdown):  
  ![image](https://user-images.githubusercontent.com/106195/171140422-c665e363-5292-4b19-9b6d-3393466bdb1b.png)

### Looking at the fade-out animation on different macOS versions:

**Catalina**

https://user-images.githubusercontent.com/106195/171139153-2f4d810c-1c5e-4025-be42-ff27a8266a1c.mov

**Big Sur**

https://user-images.githubusercontent.com/106195/171137840-5dfdaabd-6dc6-4e8d-973e-44aa702b9f00.mov

**Monterey**

https://user-images.githubusercontent.com/106195/171137895-af734f86-c91c-4749-9cc7-0f1446dd80cb.mov

All versions show the fade-out effect work correctly. So is it not version-based, but something else? Maybe it's on Apple Silicon? Maybe it's on specific displays like macbook vs external display?

**Comment by lwouis** [comment]
Could you please tell me how this build fares on your system? [AltTab.app.zip](https://github.com/lwouis/alt-tab-macos/files/8804096/AltTab.app.zip) @isametry

**Comment by lwouis** [comment]
@isametry  Thank you for the very nice videos! It's cool to see the various background. Black showcases the best still though, I think.

It looks like, for 1 frame, it switches from black to grey, then does the correct fade-out animation.

Given that I've shown above in one of my video that this happens for the macOS native app switcher, I think it's clear that it's a bug Apple introduced at some point in Big Sur, probably on `NSVisualEffectView`.

I guess the only road left is custom animation, since the SDK one is broken.

Here is a build where I removed the SDK animation, and used the technique from https://github.com/lwouis/alt-tab-macos/pull/1201: [AltTab.app.zip](https://github.com/lwouis/alt-tab-macos/files/8806684/AltTab.app.zip). It looks pretty smooth on my machine, and I couldn't find any regression with it.

Could you please try it out?

**Comment by isametry** [comment]
@lwouis Looks perfect to me👏👏 

### Full speed

https://user-images.githubusercontent.com/46103746/171217390-e1b35472-6e19-48a4-b0d0-cb6f6096eb53.mp4

https://user-images.githubusercontent.com/46103746/171217416-e98ed254-35ca-41f3-92a4-3d13ea37950e.mp4

### 0.1× speed

https://user-images.githubusercontent.com/46103746/171217479-d7a53375-a957-4876-b4d2-0210189d5f8a.mp4

https://user-images.githubusercontent.com/46103746/171217488-60f3b41a-80d9-455b-bfa4-613d03956c93.mp4

**Comment by lwouis** [comment]
Ok I'll ship a new release with this change soon then~
