### ISSUE TITLE
Remove strict requirement for screen recording

### ISSUE THREAD

**Issue by yd-null** [lwouis/alt-tab-macos#773]
Fantastic work! Just a thought though - as the thumbnail feature is optional, why have a requirement for it at runtime?

IMO.. It would be an improvement if the application could be ran without the strict requirement for screen recording. 

If the user allows screen recording on first initial launch, enable thumbnails, else leave thumbnails off with a note next to the checkbox in preferences or a pop up reminder to enable screen recording if trying to enable via preferences?

**Comment by lwouis** [comment]
Hi @yd-null! Please see my answer on this: https://github.com/lwouis/alt-tab-macos/issues/600#issuecomment-691061724
