### ISSUE TITLE
Show on Multiple Monitors at the Same Time?

### ISSUE THREAD

**Issue by matan129** [lwouis/alt-tab-macos#785]
**Is your feature suggestion related to a problem? Please describe.**
Unrelated to any problem.

**Describe the solution you'd like**
I have two monitors, and I'd like alt-tab switcher to appear on both windows, not just the active one / the one that has the mouse.

**Describe alternatives you've considered**
Nothing really, the current options are good but not good enough IMHO.

Btw, if it's a low hanging fruit I'd love to make the PR myself, please let me know :+1:.
Awesome app!

**Comment by lwouis** [comment]
Hi @matan129! There is already a ticket for this enhancement: https://github.com/lwouis/alt-tab-macos/issues/535#issuecomment-674921293

I think it's quite an ambition feature perhaps for a first contribution. However don't let it stop you. How familiar are you with macOS development? There is a [good introduction here if you want to get a feeling for the project](https://alt-tab-macos.netlify.app/contributing).

Let me know if I can help! We have a [discord channel](https://discord.gg/mHvmcqT) and you can always reply here or email me 👍
