### ISSUE TITLE
Screen Recording Permissions

### ISSUE THREAD

**Issue by ztroop** [lwouis/alt-tab-macos#790]
Hello! I wanted to know why **Screen Recording** is required to run this application. Beyond what the starting pop-up says, I'd appreciate a bit more detail. Is there no other way to retrieve window titles? Perhaps the documentation can discuss this in more depth. :book:

**Comment by lwouis** [comment]
Please take a look at https://github.com/lwouis/alt-tab-macos/issues/600#issuecomment-691061724

This permission is needed to display window titles, without which the app is useless to almost all users

**Comment by ztroop** [comment]
Thanks, I appreciate the fast response!
