### ISSUE TITLE
Reset back to default option

### ISSUE THREAD

**Issue by D1stinctProgrammer** [lwouis/alt-tab-macos#807]
**Is your feature suggestion related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Comment by D1stinctProgrammer** [comment]
It would be great if users were able to reset the app back to default, as they installed it as when tinkering with settings and unable to access the default settings it is a longer process to uninstall and reinstall the app again.

**Comment by lwouis** [comment]
Reinstalling the `.app` will not reset the preferences. Preferences are using macOS default system. This means they are stored by macOS together with your session preferences. You can use the built-in tool called `defaults` to reset the preferences of any app, or the global preferences. For instance, entering this into the Terminal will reset AltTab's preferences:

```bash
defaults delete com.lwouis.alt-tab-macos
```

We could also add a UI for this. You're the first person to request this though, so I'll wait until a few more people do to invest time into this. In the meanwhile you can use the command I shared to do it 👍

**Comment by macintacos** [comment]
@lwouis just started checking out alt-tab, played with some sliders, absolutely _hated_ my results (😅) and was frustrated to see there was no way to reset things to default settings. Would be nice ot have this button, if only for people who are starting out that don't really know what they're doing (like me!) and want to just get back to a sane place :)
