### ISSUE TITLE
Space number starts from 0

### ISSUE THREAD

**Issue by yanzhang0219** [lwouis/alt-tab-macos#838]
**Describe the bug**

I am using two extra monitors along with my laptop (total 3 screens with alignment left, middle and right). The left one has one workspace, the middle one has two workspaces and the right one has one workspace. Then I press `CMD-TAB`, I notice that the workspace number starting from 0 instead of 1. 

Thank you very much.

**Comment by lwouis** [comment]
I released a new version of AltTab 6 days ago that should fix this issue. I'm going to close it now.

@yanzhang0219 Could you please confirm that the fix works for you? Thank you!

**Comment by yanzhang0219** [comment]
I updated it just now and it works. 
Thank you very much.
