### ISSUE TITLE
After update from 6.16.0 to 6.17.0, when the application relaunched, windows won't populate in alt+tab list

### ISSUE THREAD

**Issue by evulhotdog** [lwouis/alt-tab-macos#844]
**Describe the bug**

I updated from 6.16.0 to 6.17.0 through the "Check for Updates" option within the app, then relaunched. Once it relaunched, it showed a very small subset (maybe one or two windows) out of 20 or so. Then to get the apps to re-appear in the list, I had to close / reopen them, sort of to "register" them with the app. Switching to them, away from them, back to them, didn't allow them to be shown in the app. I could be in an app, in a workspace, and nothing would show in the alt tab window (I think it just didn't show anything when the shortcut was pressed.)

I'm not sure this is specifically related to the update, but just mentioning it in case it did.

**Screenshots / video**
Nope, sorry!

**Steps to reproduce the bug**

1. Be on 6.16.0 
2. Update to 6.17.0 through auto update mechanism
3. Attempt to alt+tab to switch to different windows across spaces, apps, etc
4. See very few windows appear, if any.

**Comment by lwouis** [comment]
Hi @evulhotdog!

I wasn't able to reproduce the issue you described:

* On 6.16.0, press alt-tab, see 5 windows
* Auto-update to 6.17.0, press alt-tab, see same 5 windows

**Comment by evulhotdog** [comment]
Yeah, it definitely seemed like an odd scenario. I even tried to restart (quit through prefs) alt-tab and it did the same thing over and over again. Not sure what situation I got myself in that it didn't play nice. It's the first time it's ever happened.

**Comment by lwouis** [comment]
Could you please share a video so I can understand better what you're seeing? Or at least a screenshot with 6.16.0 and one with 6.17.0. It would help to know which windows are not shown: windows on other Spaces, fullscreened, on a different monitor, etc?

**Comment by evulhotdog** [comment]
Well, that's the problem. Once I rebooted, it stopped happening. Otherwise I would absolutely give you everything you could want. 

Sorry!

**Comment by lwouis** [comment]
You're saying that it happened consistently even when restarting AltTab, but that a system reboot fixed it and it's now consistently working for you?

**Comment by evulhotdog** [comment]
That is 100% correct. 

I thought it was incredibly weird, and because it was happening across app restarts, I rebooted as a last resort leap of faith, and oddly, it worked.

It's obviously possible something else caused it, but I can't think of anything thats directly related.

**Comment by lwouis** [comment]
Sounds like it could be macOS not giving the permissions to AltTab. Maybe an issue with quarantine, GateKeeper, or Apple certificate servers not being reachable.

I'll close this issue as nothing seems to point at a defect in AltTab, and it's not reproducible
