### ISSUE TITLE
Not working properly with Adobe Acrobat

### ISSUE THREAD

**Issue by bnaman50** [lwouis/alt-tab-macos#851]
**Describe the bug**

It is not working properly with Adobe Acrobat. I have two pdfs open in two separate Windows (instead of tabs) but Window switcher only shows one pdf. 
The most weird part is that when I first open the two Pdfs, it works perfectly, but when I start to edit (highlight/comment) of the Pdfs, it just starts showing only one of those in the window switches (Option+`).

**Screenshots / video**
Here is the screenshot of the windows/pdfs using Touchpad gesture. 
![image](https://user-images.githubusercontent.com/5251592/109461996-872bb080-7a28-11eb-9d4e-22f92c2eb23a.png)

Whereas this is what AltTab shows me 
![image](https://user-images.githubusercontent.com/5251592/109462141-a9253300-7a28-11eb-9d02-37926295497d.png)

**Steps to reproduce the bug**
1. Open two Pdfs in Adobe Acrobat. 
2. Start to edit one of those. 
3. Try Windows Switcher. 

I am a huge fan of this project and really appreciate the work you guys have done. It would be great if you could fix these pesky bugs. 

Thanks, 
Naman

**Comment by lwouis** [comment]
I downloaded [Adobe Acrobat Reader DC](https://get.adobe.com/reader/). Is this the same app you're using?

I opened 2 PDFs. By default they open in tabs. I dragged-and-dropped the second tab outside the UI, and it created a second window. At this point, AltTab lists both windows correctly.

Can you clarify the steps you go through to reproduce? A video would be even better.

By the way, I got this popup, which I think is Adobe Acrobat Reader DC noticing that AltTab is observing it. Did you get it as well? Which options did you select? It seems they do extra stuff to be better recognized by apps like AltTab.

Finally what version of AltTab and Adobe Acrobat Reader DC are you running?

**Comment by lwouis** [comment]
@bnaman50 Could you take a look at my response above? Thank you!

**Comment by bnaman50** [comment]
Hey, I really apologise for not being able to provide feedback. I'll try to make a detailed post on this weekend. 

Thanks, 
Naman

**Comment by lwouis** [comment]
Closing this as it's unactionable at the moment
