### ISSUE TITLE
Apple Books app doesn't show up in Alt-Tab

### ISSUE THREAD

**Issue by Stokestack** [lwouis/alt-tab-macos#856]
**Describe the bug**
Books isn't listed among running apps in Alt-Tab. We've seen this before with other apps. There's probably something weird about the window.

**Steps to reproduce the bug**

1. Open a book in Books.
2. With Alt-Tab running, press Command-Tab.

It's a bit more annoying than some apps being missing, because if you're bouncing back and forth between a programming book and your IDE... yeah, you get the picture.

**Comment by lwouis** [comment]
Duplicate of #481. See also #627 #748

**Comment by Stokestack** [comment]
Search failure on my part.

**Comment by lwouis** [comment]
@Stokestack No worries 👍
