### ISSUE TITLE
open alt-tab where cursor is

### ISSUE THREAD

**Issue by koin612** [lwouis/alt-tab-macos#859]
**Is your feature suggestion related to a problem? Please describe.**
On multiple displays I often scroll through my browser which doesn't require focus of the window. When I press alt-tab then the UI opens on a different monitor than I would expect and I have to search it.

**Describe the solution you'd like**
Optionally, the UI could open on the display where the cursor is currently.

**Comment by lwouis** [comment]
This is already a preference you can set:

![image](https://user-images.githubusercontent.com/106195/110122057-7a310780-7e02-11eb-82dd-5cfd76f5e362.png)
