### ISSUE TITLE
AltTab way too slow compared to HyperSwitch

### ISSUE THREAD

**Issue by jasonhan-vassar** [lwouis/alt-tab-macos#86]
Hi, I'm a Catalina user who is looking to switch away from the closed-source HyperSwitch. However, AltTab feels like there's a slight delay before the actual switching occurs, and there seems to be no preference that fixes it. Do you know if this will be getting worked on in the future? I would definitely donate if that gets fixed!

**Comment by lwouis** [comment]
Hi @jasonhan-vassar! I believe we already have #62 to track slowness during window focus. Your description is a bit unclear though, so maybe you are thinking about slowness to display the thumbnails? That one is currently discussed in #45
