### ISSUE TITLE
No visible way to define keyboard shortcuts (or information on what the shortcuts are)

### ISSUE THREAD

**Issue by tarkowski** [lwouis/alt-tab-macos#866]
Hello, the preference pane does not provide information on what the keyboard shortcuts for launching AltTab are - although the "Controls" pane references "Shortcut 1" and "Shortcut 2". There is also no visible way to set them.

**Comment by lwouis** [comment]
Hi @tarkowski 

You can simply click on the shortcut to replace them with other keys 👍

**Comment by tarkowski** [comment]
Hello, thank you for the response. The solution does not seem to work. I'm including a screenshot. Pressing the "Shortcut 1" button (click or double click) does not do anything.
<img width="566" alt="Screenshot 2021-03-17 at 16 21 55" src="https://user-images.githubusercontent.com/594926/111492538-0a454a00-873d-11eb-8363-c58492c1ed98.png">

**Comment by lwouis** [comment]
You need to press these buttons here to customize the various shortcuts:

![image](https://user-images.githubusercontent.com/106195/111502080-dc85f280-8788-11eb-899a-7d5d017d1dfb.png)

Shortcut 1 and 2 are tabs. They let you have 2 shortcuts to show different things. By default shortcut 1 is `option-tab` to show all windows, while shortcut 2 is ``` option-` ``` to show windows of the active app only. Everything is customizable.

**Comment by tarkowski** [comment]
Thank you for clarifying this. I find the menu descriptions unclear, as they suggest that the shortcut is used to open next window, but that it's not also a shortcut that launches AltTab. For example, Alfred describes this menu item as "Alfred hotkey", with an added explanation that this shortcut launches the app. So myabe you can consider some UI improvements around this in the future? thanks once again ,Alek
