### ISSUE TITLE
Brew installation on site should be `brew install --cask alt-tab`

### ISSUE THREAD

**Issue by Luckey-Elijah** [lwouis/alt-tab-macos#870]
**Describe the bug**

The latest versions on homebrew prefer cask like `--cask` rather than `cask` in the install.

The site says to install like: `brew cask install alt-tab`
When the brew-preferred method is: `brew install --cask alt-tab`

**Screenshots / video**

N/A

**Steps to reproduce the bug**

N/A

**Comment by meiser79** [comment]
Over and over the same bug reports, see #725, #780, #829 and #870.
