### ISSUE TITLE
Invoke with command line

### ISSUE THREAD

**Issue by prasskaly** [lwouis/alt-tab-macos#879]
Hi, 
Thank you for a wonderful app that solves the most needed switching app. Your implementation is much better than the System default.
Is it possible to invoke the app using command line ? 
Something like /Applications/AltTab.app --args 1 (for main AltTab) and --args 2 (for same app switching) ?
This can help me remap to an easier keybinding - like double press Left Shift to AltTab

**Comment by lwouis** [comment]
There is a ticket for CLI support: #371. It even has an in-progress PR: #768.

Now if you end-goal is to have `double-shift` to invoke AltTab, there are many ways you could achieve that without changing AltTab. You could use something like [BTT](https://folivora.ai/) which I recommend as a user, and bind whatever event to the standard shortcut `option-tab` of AltTab. You could bind `double-shift`, a mouse gesture, a bluetooth signal, whatever you fancy.

In addition, I imagine that you want the UI to stay open after you `double-shift`? If so, this is supported by switching here to `Do nothing`:

![image](https://user-images.githubusercontent.com/106195/112283937-0335b300-8ccc-11eb-8068-6767fb20cc00.png)
