### ISSUE TITLE
Can you make this less long?

### ISSUE THREAD

**Issue by lowking** [lwouis/alt-tab-macos#895]
The place in the picture
![image](https://user-images.githubusercontent.com/33308659/113513126-a58e4a00-959a-11eb-9523-da7970b08225.png)

**Comment by lwouis** [comment]
Hi @lowking!

I'm not sure what you are asking for. Could you please explain in more details?

If you are asking for AltTab UI to take less space on screen, you have many parameters you can chance in the preferences:

![image](https://user-images.githubusercontent.com/106195/113526893-afde3180-95f6-11eb-8ad3-78df5bb995f1.png)

**Comment by lowking** [comment]
Details.
I have 2 screens, one for MacBook Pro and one for external monitor (vertical screen), all settings are displayed normally on MacBook Pro, but not on vertical screen (like the picture above shows).

Max height on screen is a percentage, not a fixed height, so this problem will occur. So I hope I can set the max height on screen for each of the 2 screens, and I can set the position of the windows on the different screens.

**Comment by lwouis** [comment]
As I understand it, you are asking for per-monitor appearance preferences. Something like what the built-in `System Preferences > Displays` does.

There is a [ticket discussing this already a bit](https://github.com/lwouis/alt-tab-macos/issues/535#issuecomment-674921293). It's not supported at the moment, and it would be very complex to implement it, so unless someone contributes it, I don't expect this feature to come out soon, unfortunately.

Closing this ticket. Please follow this in the other ticket 👍
