### ISSUE TITLE
Mouse scroll support on window thumbnails

### ISSUE THREAD

**Issue by prasskaly** [lwouis/alt-tab-macos#902]
Currently, mouse scroll does not do anything on the window thumbnails.
It would be helpful if you can add support to use mouse scroll to highlight the window thumbnails in a serial fashion.(just like how the System Cmd+Tab, mouse scroll behaves) and then open the selected window with keyboard/click.

This is only a suggestion to an already great tool to make it even better. 
For the first time ever, I use the mouse (mapped gesture button to altTab)  to list and switch windows without using keyboard. Thank you for this.

**Comment by lwouis** [comment]
> Currently, mouse scroll does not do anything on the window thumbnails

Actually it does: if you have many windows, it will let you scroll to reach the ones out of sight in AltTab's UI.

Regarding more scroll support, there is a ticket that encompasses this but also more: https://github.com/lwouis/alt-tab-macos/issues/730#issuecomment-744329724
