### ISSUE TITLE
Version 6.18.1 crashes immediately

### ISSUE THREAD

**Issue by MaralWa** [lwouis/alt-tab-macos#905]
I just installed version 6.18.1 manually but AltTab crashes immediately.

I am using Mac OS Catalina 10.15.7

**Comment by lwouis** [comment]
Hi @MaralWa

When you restart AltTab, does it show you a pop up to submit a crash report?

Did you use a previous version? You may want to remove the preferences just in case it conflicts somehow, by running `defaults delete com.lwouis.alt-tab-macos` in Terminal.

**Comment by MaralWa** [comment]
Hi Iwouis,

no,it did not show a pop up to submit a crash report, only its icon flashed up  for a second. I use Bartender. Could this have something to do with the problrm? I just removed the preferences of the previous version as you suggested. After that I could start it and a message popped asking whether I want to send a crash report because AltTab crashed before.

Now AltTab seems to run stable.

Thank your very much for  your quick response.

Ciao!

MaralWa

**Comment by lwouis** [comment]
Oh cool! So it was corrupted preferences! I'm so dumb, I should have asked you to share your preferences before I told you to remove them. I may have learned about what corrupted it in the first place by seeing them. Oh well :p

Glag you're back on track 👍
