### ISSUE TITLE
Selected thumbnail not very visible when over dark background

### ISSUE THREAD

**Issue by jberdine** [lwouis/alt-tab-macos#909]
**Is your feature suggestion related to a problem? Please describe.**
When the AltTab list of thumbnails is shown over a light background, the selected window's thumbnail is easily visible due to the difference in color between the "border" of the selected window and the window containing all the thumbnails. But when the windows behind are dark, the difference between the selected window's border and the rest is very small and not very visible.

**Describe the solution you'd like**
If there was a way to do something like blend with the "inverse" of the windows behind, that would perhaps work. Personally, I would be just as happy with an option to disable transparency and not have to worry about the color or windows.

**Comment by lwouis** [comment]
Could you please refer to https://github.com/lwouis/alt-tab-macos/issues/82 and https://github.com/lwouis/alt-tab-macos/issues/440#issuecomment-660630274? If after you've read through what's involved, and still think there is something to be done here, then could you please propose a detailed plan on what we could do? Maybe it could be another theme, maybe a more complex/dynamic solution.

A workaround I could also suggest is to use the Windows 10 theme, which has a nice white border for selection, making it unmissable:

![image](https://user-images.githubusercontent.com/106195/114415999-2d9fcf80-9beb-11eb-9903-8933fa75fcbd.png)

**Comment by jberdine** [comment]
Thanks @lwouis, I had not realized that difference between the themes, I can use the w10 one. I'm not familiar enough with blending techniques, etc. to make a concrete suggestion along those lines. One point regarding #82 is that I'm unsure that it is light mode vs dark mode that is the crucial criterion, as there are still dark windows in light mode and vice versa.
