### ISSUE TITLE
Screen Sharing permission request missing

### ISSUE THREAD

**Issue by mitchusher-doordash** [lwouis/alt-tab-macos#915]
**Describe the bug**

On first launch, AltTab reports that it needs access for screen recording. When clicking the button it brings up the privacy settings as expected, but Alt Tab isn't in the list to allow.

OSX 10.15.7, installed via homebrew

**Screenshots / video**

<img width="381" alt="Screen Shot 2021-04-14 at 11 41 44 AM" src="https://user-images.githubusercontent.com/82408870/114755044-743e1880-9d16-11eb-918f-d121e2c4392c.png">

**Steps to reproduce the bug**

1. Install fresh from Homebrew
2. Launch for first time
3. Click "Open Screen Recording Preferences"

**Comment by lwouis** [comment]
There was a ticket for this issue previously: https://github.com/lwouis/alt-tab-macos/issues/340

It's really hard to know what's going wrong here. It's probably a macOS bug.

As an individual workaround, check out this solution here: https://github.com/lwouis/alt-tab-macos/issues/340#issuecomment-639576674
