### ISSUE TITLE
Better implementation of focusing windows

### ISSUE THREAD

**Issue by lwouis** [lwouis/alt-tab-macos#922]
Today, AltTab uses a complex implementation to focus windows. Indeed, the public APIs don't do the job, so we have to dabble in private APIs, SPIs, and clever tricks. The current implementation works pretty well, but is not perfect. Indeed there have been 2 tickets which seem to show limits of this implementation:

* https://github.com/lwouis/alt-tab-macos/issues/852
* https://github.com/lwouis/alt-tab-macos/issues/921

This ticket is about finding a breakthrough implementation that goes from 99% to 100% success.

The latest efforts/explorations are [documented here](https://github.com/lwouis/alt-tab-macos/issues/852#issuecomment-789874007)

**Comment by lwouis** [comment]
The focus issue come from the apps themselves. Feishu has fixed it for instance. Closing this as AltTab is doing the right thing, and apps which such issue are very rare/niche.

**Comment by probablykasper** [comment]
Could it potentially work if the new window receives focus _after_ the AltTab menu is closed? Maybe the old window doesn't lose focus because the AltTab menu is open.

I'm not able to reproduce the issue using the macOS native `` Cmd+` `` shortcut, so maybe there's a way
