### ISSUE TITLE
No element selected

### ISSUE THREAD

**Issue by decodism** [lwouis/alt-tab-macos#926]
**Describe the bug**

In some cases, no element is selected when a window is closed in AltTab.

**Steps to reproduce the bug**

Not consistent

- Close the last window on the right in AltTab

**Comment by lwouis** [comment]
Hi @decodism, thanks for sharing this issue!

I was able to reproduce it consistently by spawning 2 Finder windows, then closing the right-most one in AltTab.

The issue happens whether the window is closed with the shortcut, or by clicking the red button with the mouse.
