### ISSUE TITLE
Finder and After Effects not available

### ISSUE THREAD

**Issue by stormer** [lwouis/alt-tab-macos#931]
Hi, 

For some reason Adobe After Effects, Adobe Premiere nor the Finder show up as options when I alt tab to select a different application, whilst other Adobe applications are fine. Interestingly what sets these two Adobe applications apart from the rest is that they both use workspaces that utilise 2 monitors (as does the Finder I guess).

I'm running MacOS Catalina (10.15.7)

**Comment by lwouis** [comment]
The After Effects issue is already tracked here: #647

However, the Finder is something no-one has reported before. Could you please share a video to showcase the Finder issue especially? It would help a lot understand. Reading your text description, I'm not sure what the issue is exactly.

Thank you! 👍

**Comment by stormer** [comment]
Hey, thanks for getting back to me on this.

Thanks for the AE issue, I'll take a look at that later.

With regard to the Finder issue, I've uploaded a screen recording here:
https://www.dropbox.com/s/cmru1av1vj48n45/altTab.mov?dl=0 As I was in the
process of recording it using QuickTime, I noticed that QT too wasn't
showing up in the list of applications when I use altTab. So at 00:07
you'll see that neither the Finder icon nor the QuickTime icons are showing
up - only Firefox, TextEdit and Chrome. At 00:14 you can see that QuickTime
is running

Anyhow, let me know if that video answers your questions.

Many thanks and cheerio
--
Mob: +49 (0)174 328 8749

**Comment by lwouis** [comment]
Oh! You have a very custom layout to show only the app icons. I thought you were using the built-in macOS app switcher for a minute there.

Could you please share your preferences? You can simply share a screenshot of this tab in the preferences:

![image](https://user-images.githubusercontent.com/106195/115642348-bb02c280-a355-11eb-8b6a-999f5b5592f4.png)

**Comment by stormer** [comment]
Hi, here you go:
[image: Screenshot 2021-04-22 at 10.05.28 copy.jpg]
--
Mob: +49 (0)174 328 8749

**Comment by lwouis** [comment]
@stormer it seems the image as an email attachment doesn't work on Github

**Comment by stormer** [comment]
![Screenshot 2021-04-22 at 13 37 52](https://user-images.githubusercontent.com/6817/115708174-f6aa8600-a36f-11eb-8852-81088d11921c.png)

**Comment by lwouis** [comment]
Well, you have actively decided to not see apps with no open windows, so AltTab is obeying that:

![image](https://user-images.githubusercontent.com/106195/117621996-20a3db00-b1ad-11eb-84d9-e5fa0b6f7a51.png)

Please uncheck that box if you want to see apps with no open window.

**Comment by stormer** [comment]
Thanks for getting back to me on this. That makes total sense but even with
the "Hide apps with no open window:" check box deselected, it doesn't show
After Effects, despite AE having open windows.

**Comment by lwouis** [comment]
This issue mixes 2 very different issues. It seems that the Finder issue is solved for you. I'd like to refer you to [this clarification I shared previously](https://github.com/lwouis/alt-tab-macos/issues/931#issuecomment-824047683).
