### ISSUE TITLE
[FR] open the selected window in fullscreen and minimize the current fullscreen window 

### ISSUE THREAD

**Issue by NightMachinary** [lwouis/alt-tab-macos#934]
I like to switch between different Chrome windows in a workspace-like way. I.e., I have one fullscreen Chrome window open, and some other windows minimized. I want the new window I select via alt-tab to replace the current fullscreen window; That is, the current window gets minimized, and the selected window is unminimized in its place.

It's kind of like Opera's workspaces, if you have seen them.

**Comment by lwouis** [comment]
You could simply fullscreen all your windows, the use AltTab to switch between them. Is there a reason you want the other windows to be minimized when you are fullscreening one? The fact that's they are minimized seems unnecessary since you can't see them anyway behind the fullscreen's window

**Comment by NightMachinary** [comment]
@lwouis I want to have somewhere around 15 such windows; Keeping them all in my already crowded fullscreen spaces will make the space switcher completely unusable, which is not a worthy tradeoff for me.

**Comment by lwouis** [comment]
What do you call "the space switcher"? You mean the top bar that appears when in Mission Control, with all the Spaces listed? Or you mean the 3 fingers swipe left-right to switch to the next space? Something else?

I'm thinking that if you fullscreen everything, then you can switch with AltTab, so why do you need this space switcher in addition to AltTab?

**Comment by NightMachinary** [comment]
@lwouis I mean this:
![image](https://user-images.githubusercontent.com/36224762/116349400-255bad00-a805-11eb-9c81-cda0105ea31a.png)

I have set AltTab to only show the windows of the current app, so I can't use it to switch between apps. 

I also like to put my frequently used spaces near each other and use the three-finger swipe on them.

**Comment by lwouis** [comment]
> I have set AltTab to only show the windows of the current app, so I can't use it to switch between apps.

You can have 2 shortcuts in AltTab. One for "windows of the current app", and another for another type of navigation.

I think given the current customization options, you can figure out a flow that works with your way of working.

Your flow is quite unique, and I can't imagine an elegant way of integrating it very directly in the preferences. Instead I think you can tailor the 2 shortcut slots to get an experience that works for you. Ideally you wouldn't need to swipe or use Mission Control, and AltTab would be the only tool you need to switch between windows.

I'm going to close this as I don't see a path to something else at this time.
