### ISSUE TITLE
Keep the application workable when no access to screen recording

### ISSUE THREAD

**Issue by andre487** [lwouis/alt-tab-macos#945]
Now a permission of screen recording is critical for the application work and you can't proceed to its launch without grant this permission.

Some people (like me) are afraid of grant permissions like screen recording. And I think that the application can work without this permission. 

I suggest that in case of lack the screen recording permission the application can work in something like "Windows XP mode" when Alt+Tab window contains not screenshots but application icons:

![Windows XP Alt+Tab](https://user-images.githubusercontent.com/1009104/117533455-9ebd8180-aff5-11eb-9dca-1051fd51140f.png)

**Comment by lwouis** [comment]
I like this goal, and i would have implemented it if i could, when i added support from Catalina (which introduced this new permission).

However, the permission is required to get the windows titles as well as the screenshots. The app would be useless without the permission, unfortunately.
