### ISSUE TITLE
When you alt-tab without any active app application crash

### ISSUE THREAD

**Issue by Xicy** [lwouis/alt-tab-macos#95]
When list count equals 0 and step 0, try to modulo to 0 and return undefined and crash, you can use ` list.count == 0 ? 0 : ` like that function for prevent crashing 

```
 static func moveFocusedWindowIndex(_ step: Int) -> Int {
        return list.count == 0 ? 0 : (focusedWindowIndex + step < 0 ? list.count - 1 : (focusedWindowIndex + step) % list.count)
    }
```

**Comment by lwouis** [comment]
Thank you very much for sharing this issue! I made a fix and merged it to release a new version today! It should fix that issue :)
