### ISSUE TITLE
Bear Not Showing Up

### ISSUE THREAD

**Issue by JaiRelan** [lwouis/alt-tab-macos#955]
Bear (the markdown app) wasn't showing up... I restarted Bear and made sure the normal inbuilt Mac command+tab recognised it, but it still didn't appear in alt-tab. 

Restarting my Mac fixed the problem.

I know I'm not much help but I didn't take any screenshots and can't really figure out how to replicate it. Just thought I should make an issue so that you can keep an eye out for it next time...

Thank you and love alt-tab!

**Comment by lwouis** [comment]
We already have a ticket for Bear: #630 Please check out the discussion there 👍
