### ISSUE TITLE
Un-maximized Chrome with Youtube doesn't show at all

### ISSUE THREAD

**Issue by hedefalk** [lwouis/alt-tab-macos#958]
**Describe the bug**

Can't tab to Chrome after un-maximizing video and tabbing away.

**Steps to reproduce the bug**

1. Chrome with Youtube video maximized.
2. Tab-away to other app. 
3. Tab back to Youtube - yey (this doesn't work without alttab)
4. Now press escape in youtube video to un-maximize.
5.  Tab to other window. 
6. Try to tab back to video - no Chrome at all.

**Comment by lwouis** [comment]
Hi @hedefalk!

I couldn't reproduce the issue after following the steps. Everything works fine for me.

Could you please share a video of the issue so I can see it in motion and understand better?

Thank you!

**Comment by hedefalk** [comment]
@lwouis 

No audio here, but the mechanics is what I described above. I can reproduce reliable over and over. 

I can alt-tab to a maximized youtube-window unlike built-in, but after hitting esc to un-maximize and tabbing away, chrome in entirety is removed from alt-tabbable apps. It then remains removed until something happens.

https://user-images.githubusercontent.com/116520/119217829-279be900-badd-11eb-97d3-8d53a47bab7a.mov

**Comment by japplin** [comment]
I'm also having this bug

**Comment by lwouis** [comment]
Is this still happening? It's been a year, so I'll close the ticket. Let me know if it's still relevant. I may very well be since the tab detection and fullscreen apps are still a best-effort hack, since there are no public API for it.
