### ISSUE TITLE
Thumbnail scaling doesn't look great on low-DPI screens

### ISSUE THREAD

**Issue by statico** [lwouis/alt-tab-macos#963]
First, thank you all for making this wonderful tool. You all rock!

**Describe the bug**

I use a 1920x1080 144hz gaming monitor as my primary display. When I use AltTab, the thumbnails look pixelated and jaggy, like they haven't been scaled nicely.

![image](https://user-images.githubusercontent.com/137158/119171046-e80bc900-ba18-11eb-8981-b041fe407ff4.png)

**Steps to reproduce the bug**

1. Use a non-high-DPI display
2. Press command-tab
3. Squint & sneer

**Suggestion**

Based on some cursory research, it looks like this could be fixed in `ThumbnailView.swift` somehow using some kind of image scaling interpolation settings. Some links:

- [SO: Scaled image in NSImageView looks bad with layer-backing on](https://stackoverflow.com/q/13588865/102704)
- [SO: kCAFilterNearest maginifcation filter (UIImageView)](https://stackoverflow.com/q/6541352/102704)
- [CALayer::magnificationFilter docs](https://developer.apple.com/documentation/quartzcore/calayer/1410907-magnificationfilter)

**Comment by lwouis** [comment]
Hi @statico

There is already an open PR on this this topic. Please check out the conversation there. It's quite a complex situation.

I'll close this ticket in the meanwhile to keep the efforts centralized
