### ISSUE TITLE
Custom Keybinds

### ISSUE THREAD

**Issue by ghost** [lwouis/alt-tab-macos#965]
Hi, is it possible for you to make keybinds for the alt tab app? Like I would like to see the preview of windows when I use cmd tab rather than have them both available, as in disabling the alt tab and switching it to cmd tab, but with all the looks and settings, because I need option tab for other apps and that will cause a huge problem. Sorry if it diddn't make much sense, english isn't my first language.

**Comment by lwouis** [comment]
AltTab has preferences. In the preferences, you can customize many things, including keybings:

![image](https://user-images.githubusercontent.com/106195/119245506-ccd5c080-bbb4-11eb-8626-7b649f195139.png)
