### ISSUE TITLE
Is providing screen recording permissions a must? is it safe?

### ISSUE THREAD

**Issue by leemun1** [lwouis/alt-tab-macos#970]
Is granting permissions for screen record a must for the functionality of the app?

My main concern is that the permission allows the app to screen record even when I am using other applications, which seems quite sketchy.

Given that the permission is required for showing screenshots and title of open windows, is there a way I can opt out of that, and only cycle through my windows by their names and icons?

**Comment by lwouis** [comment]
This has been discussed/answered a few times already:

- https://github.com/lwouis/alt-tab-macos/issues/945
- https://github.com/lwouis/alt-tab-macos/issues/773
- https://github.com/lwouis/alt-tab-macos/issues/790
