### ISSUE TITLE
Alt Tab doesn't bring other windows in front of Web Catalog apps

### ISSUE THREAD

**Issue by autonia** [lwouis/alt-tab-macos#979]
**Describe the bug**

I have several apps generated using Web Catalog (https://webcatalog.app/). Alt Tab doesn't bring other windows in front of Web Catalog apps when the app is selected.

**Screenshots / video**

In this GIF, the Node RED window is a Web Catalog app.

![2021-06-02 at 13 31 21](https://user-images.githubusercontent.com/1128613/120548288-0c678e00-c3a7-11eb-9e36-fb47d7fff477.gif)

**Steps to reproduce the bug**

1. Create app with Web Catalog.
2. Launch app.
3. Bring Web Catalog app to front.
4. Try to switch to another app using Alt Tab.
5. See that Web Catalog app remains in front.

**Comment by lwouis** [comment]
The symptoms look very similar to https://github.com/lwouis/alt-tab-macos/issues/1038#issuecomment-883164524

**Comment by lwouis** [comment]
Ok WebCatalog is an Electron app, so this issue is probably from https://github.com/lwouis/alt-tab-macos/issues/992. This is a regression in Electron. VSCode fixed it by upgrading to the latest Electron. This Web Catalog app probably should do the same
