### ISSUE TITLE
AltTab doesn't always catch new windows as apps are opened and closed throughout the day

### ISSUE THREAD

**Issue by skyzyx** [lwouis/alt-tab-macos#980]
**Describe the bug**

My computer starts up, AltTab loads, and I begin working. Throughout the day, as I open and close apps, I find that the windows I have open aren't always available when I go to look for them in the AltTab interface.

This is a standard feature of the built-in macOS tab-switching, and as a result, my expectations are that AltTab would function in the same way.

Quitting AltTab and restarting the app resolves the issue.

**Screenshots / video**

Forgive the poorly-chopped screenshot.

![Untitled](https://user-images.githubusercontent.com/39447/120710971-0e4f5100-c47c-11eb-835c-bbddf87e6696.png)

In this case, I opened Mail.app a few minutes ago, and it's still not in the list.

**Steps to reproduce the bug**

1. Launch AltTab.
2. Open and close windows/applications throughout the day.
3. Invoke AltTab with the key command.
4. Notice that not all of the windows you have open are represented in the AltTab UI.

My computer pretty much runs all the time, and I find that I have to quit/restart AltTab once or twice per week to pick up the missing windows (that I notice).

_Possibly_ related to #431. But maybe not.

**Comment by lwouis** [comment]
Hi @skyzyx,

Are you on Big Sur?

> In this case, I opened Mail.app a few minutes ago, and it's still not in the list.

When do you open Mail.app? Manually by clicking the Dock icon? Does it open already fullscreen? Does it open and restore windows from the previous session?

We already have https://github.com/lwouis/alt-tab-macos/issues/639 to track this issue, so I'll close this ticket, but please do answer my questions above in https://github.com/lwouis/alt-tab-macos/issues/639, where we can focus our efforts and get to a reproducible scenario so I can debug and fix the issue 👍

**Comment by skyzyx** [comment]
Yes, I'm on Big Sur. I switched to AltTab during the Big Sur beta.

I launch Mail.app usually via Alfred.app (app launcher). It opens in full-screen mode, which is how I always run it.

Most of the apps I run, I use in full-screen mode — Mail, Safari, iTerm, VS Code, Slack, Messages, Music, Things.

Apps that I consistently run windowed (not full-screen) — Contacts, Reminders, Notes, Finder windows.

I most often observe the full-screen apps missing from AltTab. When possible, I have the apps restore previous state.
