### ISSUE TITLE
AltTab no longer bringing Finder windows to front

### ISSUE THREAD

**Issue by ribrob** [lwouis/alt-tab-macos#982]
**Describe the bug**

Finder windows are not being brought to the front (all other regular app windows work as expected).

A key change in my setup is that I've moved to an M1 iMac.

Note that finder windows _are_ brought to the front on my laptop as expected.

**Steps to reproduce the bug**

- Alt-tab through apps as usual
- Select the Finder icon
- No Finder window comes to the front

**Setup**

Alt-Tab Version 6.22.1
Big Sur 11.4 (20F71)
iMac M1

**Comment by lwouis** [comment]
Hi @ribrob 

I'm not sure I understand the issue. You wrote "Select the Finder icon". Are you referring to selecting a window from the Finder, or selecting the Finder app icon that's shown when you have no open window from the Finder?

**Comment by ribrob** [comment]
Scratch that - solved it - I'd misconfigured AltTab on the new machine. Sorry!
