### ISSUE TITLE
Notification badges respect the icon size

### ISSUE THREAD

**Issue by davesnx** [lwouis/alt-tab-macos#983]
Thanks @lwouis for the great program, such a good addition to Mac.

**Describe the bug**

The icons of the notification look too small when you set the icon size to big. I attached a screenshot. I'm not sure If tag it as bug or as a feature.

**Screenshots / video**

![Screenshot 2021-06-07 at 17 14 23](https://user-images.githubusercontent.com/3763599/121042293-d285f580-c7b3-11eb-934a-ac91d76b2acf.png)
**Steps to reproduce the bug**

**Comment by lwouis** [comment]
Duplicate of https://github.com/lwouis/alt-tab-macos/issues/559#issuecomment-682036665
