### ISSUE TITLE
New preference: switch to app with no open window -> just focus, or launch

### ISSUE THREAD

**Issue by lwouis** [lwouis/alt-tab-macos#999]
From: https://github.com/lwouis/alt-tab-macos/issues/664#issuecomment-716937529

Today, when the user focuses the icon of an app with no open window, it "launches" the app. This is equivalent of the user double-clicking the app icon. This often creates a new window (e.g. with Finder).

This ticket is about adding a new preference to let users decide if they want to launch the app, or simply activate it (app name shows in the menubar; windows from other apps lose focus; main window from that app gets focus).

**Comment by lwouis** [comment]
Probably too niche.

**Comment by bernardjoseph** [comment]
I would also opt for such a preference, because that is the behavior of the MacOS switcher. I also noticed that the Preview application does not create a new window when launching. Unfortunately, the issue is already closed.

**Comment by lwouis** [comment]
@bernardjoseph if more people ask for it, it will be added.

**Comment by amypotato** [comment]
I’d be very interested in this feature also +1
